- .github/workflows/ubuntu_20.04/Dockerfile.ci
- .github/workflows/ubuntu_22.04/Dockerfile.ci
- .github/workflows/ubuntu_24.04/Dockerfile.ci
- doc/source/development/building_from_source.rst
- doc/source/drivers/vector/xodr.rst
- docker/alpine-normal/Dockerfile
- docker/ubuntu-full/Dockerfile
- ogr/ogrsf_frmts/xodr/ogrxodrdatasource.cpp
Now, catching of XML parsing errors is possible from within this XODR driver. This was not possible until recently where libOpenDRIVE dependency has been extended with the necessary functionality (see [Expose xml_parse_result for external queryability](https://github.com/pageldev/libOpenDRIVE/pull/98)).
None
> XODR: Implement handling of XML parsing errors

- autotest/osr/osr_epsg.py
- ogr/ogrspatialreference.cpp
> [Backport release/3.9] EPSGTreatsAsNorthingEasting(): make it work correctly with compound CRS

- autotest/ogr/ogr_hana.py
With PR #10543 , the new fast extent functionality for HANA was added to GDAL.
Unfortunately, one of the tests is failing randomly. Until a fixed test case is available, let's remove it for now.
#10543
https://github.com/OSGeo/gdal/pull/10543#issuecomment-2271154989
> HANA: Remove flaky fast extent estimation test

- doc/source/drivers/vector/mvt.rst
[mapbox/tippecanoe](https://github.com/mapbox/tippecanoe) links to felt/tippecanoe with the mention
> Note: there is an active fork of this project over at https://github.com/felt/tippecanoe
So I think it is fair to update the link in the GDAL documentation as well.
> Link to felt/tippecanoe

- autotest/gcore/cog.py
- frmts/gtiff/cogdriver.cpp
- frmts/gtiff/gt_overview.cpp
- frmts/gtiff/gt_overview.h
- frmts/gtiff/gtiffdataset_write.cpp
Fixes regression introduced in 3.5 per 383f727fc1f
Fixes #10536
> COG: properly deal with mask bands w.r.t resampling when generating JPEG output, or when input has a mask band

- autotest/gcore/cog.py
- frmts/gtiff/cogdriver.cpp
- frmts/gtiff/gt_overview.cpp
- frmts/gtiff/gt_overview.h
- frmts/gtiff/gtiffdataset_write.cpp
> [Backport release/3.9] COG: properly deal with mask bands w.r.t resampling when generating JPEG output, or when input has a mask band

- frmts/pdf/CMakeLists.txt
When dependencies are missing, the error is totally misleading.
```
CMake Error at cmake/helpers/GdalDriverHelper.cmake:390 (message):
gdal_target_link_libraries(): PRIVATE is a mandatory argument.
Call Stack (most recent call first):
frmts/pdf/CMakeLists.txt:82 (gdal_target_link_libraries)
```
This simple patch explicitly generates better errors.
Only tested on Ubuntu.  closes #10568
> PDFium: Avoid confusing/misleading error

- autotest/ogr/ogr_sql_test.py
- ci/travis/osx/before_install.sh
- ogr/swq.cpp
The backslash followed by single-quote sequence was dealt as a way of
escaping the single-quote character, but this also prevented to use
backslash at the end of a single-quoted literal. So no longer make
backslash a special character inside single-quoted strings
Fixes #10416
> OGR SQL: do not make backslash a special character inside single-quoted strings, to improve compliance wih SQL92

- autotest/gdrivers/nitf.py
- doc/source/drivers/raster/nitf.rst
- doc/source/drivers/raster/nitf_advanced.rst
- frmts/nitf/nitfdataset.cpp
- frmts/nitf/nitffile.c
- frmts/nitf/nitfrasterband.cpp
> NITF: add an alias of existing ABPP creation option as NBITS; propagate NBITS/ABPP creation option to JPEG2000 drivers

- alg/gdalwarper.cpp
- autotest/gdrivers/gti.py
- doc/source/drivers/raster/gti.rst
- frmts/vrt/gdaltileindexdataset.cpp
- gcore/gdal_misc.cpp
- gcore/gdal_priv.h
Similar to PR #10407 but for the GTI driver
```rst
Starting with GDAL 3.10, the :oo:`NUM_THREADS` open option can
be set to control specifically the multi-threading of GTI datasets.
It defaults to ``ALL_CPUS``, and when set, overrides :config:`GDAL_NUM_THREADS`
or :config:`GTI_NUM_THREADS`. It applies to band-level and dataset-level
RasterIO(), if more than 1 million pixels are requested and if the mosaic is
made of only non-overlapping tiles.
-  .. oo:: NUM_THREADS
:choices: integer, ALL_CPUS
:default: ALL_CPUS
Determines the number of threads used when an operation reads from
multiple sources.
This can also be specified globally with the :config:`GTI_NUM_THREADS`
configuration option.
-  .. config:: GTI_NUM_THREADS
:choices: integer, ALL_CPUS
:default: ALL_CPUS
Determines the number of …
```
> GTI: add multi-threaded implementation for rasterband and dataset IRasterIO() for non-overlapping tiles

- ogr/ogrsf_frmts/shape/ogrshapelayer.cpp
> Shape: fix off-by-one write heap buffer overflow when deleting exactly 128, 232, etc. features and repacking

- autotest/gdrivers/gti.py
- doc/source/drivers/raster/gti.rst
- frmts/vrt/gdaltileindexdataset.cpp
Fix issues reported in https://lists.osgeo.org/pipermail/gdal-dev/2024-July/059230.html
- GTI: start looking for OVERVIEW_<idx>_xxxx metadata items at index 0
- GTI: automatically add overviews of overviews, unless the OVERVIEW_LEVEL=NONE open option is specified
> GTI driver fixes

- autotest/ogr/ogr_geojson.py
- ogr/ogrsf_frmts/geojson/ogrgeojsonwritelayer.cpp
Fixes https://github.com/qgis/QGIS/issues/58169
> GeoJSON: make sure geometry is reprojected even when it is invalid after coordinate rounding (3.9.0 regression)

- autotest/ogr/ogr_libkml.py
- ogr/ogrsf_frmts/libkml/ogrlibkmlfeaturestyle.cpp
Fixes https://github.com/qgis/QGIS/issues/58208
> LIBKML: fix LIBKML_RESOLVE_STYLE=YES when reading a KML file with dataset-level styles (3.9.1 regression)

- autotest/ogr/ogr_libkml.py
- ogr/ogrsf_frmts/libkml/ogrlibkmlfeaturestyle.cpp
Fixes https://github.com/qgis/QGIS/issues/58208
Backport of PR #10473
> [Backport 3.9] LIBKML: fix LIBKML_RESOLVE_STYLE=YES when reading a KML file with dataset-level styles (3.9.1 regression)

- apps/gdallocationinfo.cpp
- autotest/gdrivers/gpkg.py
- autotest/ogr/ogr_gpkg.py
- doc/source/drivers/raster/gpkg.rst
- doc/source/user/sql_sqlite_dialect.rst
- gcore/gdal_priv.h
- ogr/ogrsf_frmts/gpkg/ogrgeopackagedatasource.cpp
- ogr/ogrsf_frmts/sqlite/ogrsqlitesqlfunctionscommon.cpp
- ogr/ogrsf_frmts/sqlite/ogrsqliteutility.cpp
- ogr/ogrsf_frmts/sqlite/ogrsqliteutility.h
> GPKG/SQLITE SQL: extend gdal_get_pixel_value()/gdal_get_layer_pixel_value() to support an interpolation method

- alg/polygonize.cpp
- alg/polygonize_polygonizer.cpp
- alg/polygonize_polygonizer.h
- swig/include/python/python_exceptions.i
On the test case of
https://lists.osgeo.org/pipermail/gdal-dev/2024-July/059158.html, this reduces the runtime to 8 minutes (with GeoParquet output, without spatial sorting), by optimizing some implementation details.
I believe this could be further reduced as most of the time is still spent in malloc/free of temporary objects (the output is 90 million polygons!) and some objects could be reused, but that would be more extensive changes
> Polygonize: optimizations to reduce runtime

- apps/gdalinfo_lib.cpp
- autotest/utilities/test_gdalinfo_lib.py
- doc/source/programs/gdalinfo.rst
- frmts/grib/CMakeLists.txt
- frmts/grib/gribdataset.cpp
- frmts/grib/gribdataset.h
- swig/include/python/gdal_python.i
and: GRIB: display hint to speed-up operations when using gdalinfo on a remote GRIB2 file with an .idx side car file
Demo:
```
$ gdalinfo /vsis3/noaa-hrrr-bdp-pds/hrrr.20220804/conus/hrrr.t00z.wrfsfcf01.grib2
Warning 1: If metadata does not matter, faster result could be obtained by adding the -nomd switch to gdalinfo
Warning 1: If nodata value does not matter, faster result could be obtained by adding the -nonodata switch to gdalinfo
```
> gdalinfo: add -nonodata and -nomask options

- autotest/ogr/ogr_libkml.py
- ogr/ogrsf_frmts/libkml/ogrlibkmlfeature.cpp
- ogr/ogrsf_frmts/libkml/ogrlibkmlgeometry.cpp
- ogr/ogrsf_frmts/libkml/ogrlibkmllayer.cpp
- For longitudes, accept in range [-540,540] and normalize to [-180,180]. Error out beyond
- For latitudes, accept in range [-90,90]. Error out beyond
Fixes #10483
> LIBKML writing: validate longitude, latitude to be in range

- autotest/ogr/ogr_pg.py
- autotest/ogr/ogr_pgdump.py
- ogr/ogrsf_frmts/pg/ogrpgdatasource.cpp
- ogr/ogrsf_frmts/pg/ogrpgtablelayer.cpp
- ogr/ogrsf_frmts/pgdump/ogr_pgdump.h
- ogr/ogrsf_frmts/pgdump/ogrpgdumpdatasource.cpp
- ogr/ogrsf_frmts/pgdump/ogrpgdumplayer.cpp
Also truncates too long table name and append part of their MD5 to make them unique.
Fixes #10522, #7629
> PG/PGDump: make sure spatial index name is unique, even if several tables have a long enough prefix

- autotest/ogr/ogr_sql_rfc28.py
- ogr/swq.cpp
> OGRSQL: return in error when 'Did not find end-of-string character' is emitted

- autotest/ogr/ogr_gtfs.py
- ogr/ogrsf_frmts/gtfs/ogrgtfsdriver.cpp
> [Backport release/3.9] GTFS: fix error when applying an attribute filter on a field whose advertized data type is not string

- autotest/ogr/ogr_geojson.py
- ogr/ogrsf_frmts/geojson/ogrgeojsonwritelayer.cpp
> [Backport release/3.9] GeoJSON: make sure geometry is reprojected even when it is invalid after coordinate rounding (3.9.0 regression)

- autotest/cpp/testcopywords.cpp
- gcore/gdal_priv_templates.hpp
> [Backport release/3.9] GDALCopyWords(): Fix double->uint64 when input value > UINT64_MAX thattwas wrongly converted to 0

- autotest/ogr/ogr_pg.py
- autotest/ogr/ogr_pgdump.py
- ogr/ogrsf_frmts/pg/ogrpgdatasource.cpp
- ogr/ogrsf_frmts/pg/ogrpgtablelayer.cpp
- ogr/ogrsf_frmts/pgdump/ogr_pgdump.h
- ogr/ogrsf_frmts/pgdump/ogrpgdumpdatasource.cpp
- ogr/ogrsf_frmts/pgdump/ogrpgdumplayer.cpp
> [Backport release/3.9] PG/PGDump: make sure spatial index name is unique, even if several tables have a long enough prefix

- autotest/ogr/ogr_sql_rfc28.py
- ogr/swq.cpp
> [Backport release/3.9] OGRSQL: return in error when 'Did not find end-of-string character' is emitted

- autotest/ogr/ogr_sql_test.py
- ogr/swq.cpp
> [Backport release/3.9] OGR SQL: do not make backslash a special character inside single-quoted strings, to improve compliance wih SQL92

- autotest/gdrivers/netcdf_multidim.py
- frmts/netcdf/netcdfmultidim.cpp
- swig/include/MultiDimensional.i
- swig/include/python/gdal_python.i
> [Backport release/3.9] netCDF multidim: fix use-after-free on string variables in ReadOneElement()

- autotest/gcore/vrt_read.py
- autotest/gdrivers/vrtprocesseddataset.py
- frmts/vrt/vrtdataset.h
- frmts/vrt/vrtsources.cpp
> [Backport release/3.9] VRT: fix reading from virtual overviews when SrcRect / DstRect elements are missing

- autotest/gcore/multidim.py
- gcore/CMakeLists.txt
- gcore/gdal.h
- gcore/gdal_priv.h
- gcore/gdalmultidim.cpp
- gcore/gdalmultidim_meshgrid.cpp
- swig/include/MultiDimensional.i
and map it to C GDALMDArrayGetMeshGrid() and Python gdal.MDArray.GetMeshGrid()
```cpp
/** Return a list of multidimensional arrays from a list of one-dimensional
* arrays.
*
* This is typically used to transform one-dimensional longitude, latitude
* arrays into 2D ones.
*
* More formally, for one-dimensional arrays x1, x2,..., xn with lengths
* Ni=len(xi), returns (N1, N2, ..., Nn) shaped arrays if indexing="ij" or
* (N2, N1, ..., Nn) shaped arrays if indexing="xy" with the elements of xi
* repeated to fill the matrix along the first dimension for x1, the second
* for x2 and so on.
*
* For example, if x = [1, 2], and y = [3, 4, 5],
* GetMeshGrid([x, y], ["INDEXING=xy"]) will return [xm, ym] such that
* xm=[[1, 2],[1, 2],[1, 2]] and ym=[[3, 3],[4, 4],[5, 5]],
* or more generally xm[any …
```
> Multidimensional API: add GDALMDArray::GetMeshGrid()

- frmts/kea/keaoverview.cpp
As per the documentation, classes that derive from `GDALRasterBand` should call `FlushCache()` in their destructor so that cached tiles are correctly written to file. In the KEA driver, this is correctly done for the `KEARasterBand` class, but not for the `KEAOverview` class (which also derives from `GDALRasterBand`). In some situations this was leading to the overviews not being written correctly.
xref: https://github.com/ubarsc/kealib/pull/65
ping @neilflood
> KEA: fix overview writing so that tiles are correctly flushed

- autotest/gdrivers/heif.py
- frmts/heif/heifdrivercore.cpp
Adds support for variable length `ftyp` box, and matches the major brand and compatible brand checks to libheif.
None known.
N/A.
> heif: make simple identification more robust

- frmts/kea/keaoverview.cpp
Backport #10616
**Authored by:** @gillins
> [Backport release/3.9] KEA: fix overview writing so that tiles are correctly flushed

- ogr/ogrsf_frmts/openfilegdb/filegdbindex_write.cpp
It adds calling GetIndexCount() to retrieve all the existing indexes before creating a new index.
Currently, creating a new index using OpenFileGDB drive causes all the existing indexes are lost.
For example, I have a table with two indexes "FDO_OBJECTID" for "OBJECTID" and "IDx" for "ID. Here are the contents of its gdbindexes file.
But after I run `./ogrinfo BASE.gdb -sql "CREATE INDEX DESCRIPTx ON PIPE_h(DESCRIPT)"`, there is only "DESCRIPTx" for "DESCRIPT" in its gdbindexes file.
I find it doesn't call GetIndexCount() to retrieve the existing indexes before creating a new index in the FileGDBTable::CreateIndex function. I think it might be the reason. After I add this line, everything works properly now.
> OpenFileGDB: add missing GetIndexCount() in FileGDBTable::CreateIndex

- ogr/ogrsf_frmts/openfilegdb/filegdbindex_write.cpp
Backport #10624
**Authored by:** @AlbertXingZhang
> [Backport release/3.9] OpenFileGDB: add missing GetIndexCount() in FileGDBTable::CreateIndex

- autotest/gdrivers/jp2kak.py
- frmts/jp2kak/jp2kakdataset.cpp
> JP2KAK: fix data corruption when creating multi-band tiled with the stripe compressor code path

- ogr/ogrsf_frmts/openfilegdb/gdalopenfilegdbrasterband.cpp
This is a left-over from a debugging step, that could potential crashes if that file cannot be created
> OpenFileGDB raster: do not generate debug 'tmp.jpg' file when reading JPEG tiles

- autotest/gdrivers/jp2kak.py
- frmts/jp2kak/jp2kakdataset.cpp
> [Backport release/3.9] JP2KAK: fix data corruption when creating multi-band tiled with the stripe compressor code path

- apps/gdal_translate_lib.cpp
- autotest/gcore/overviewds.py
- autotest/utilities/test_gdal_translate.py
- autotest/utilities/test_gdal_translate_lib.py
- gcore/gdaloverviewdataset.cpp
> [Backport release/3.9] gdal_translate/GDALOverviewDataset: fix half-pixel shift issue when rescaling RPC

- ogr/ogrsf_frmts/openfilegdb/gdalopenfilegdbrasterband.cpp
> [Backport release/3.9] OpenFileGDB raster: do not generate debug 'tmp.jpg' file when reading JPEG tiles

- autotest/gdrivers/netcdf.py
- frmts/netcdf/netcdfdataset.cpp
> [Backport release/3.9] netCDF: honour BAND_NAMES creation option in CreateCopy()

- .github/workflows/windows_build.yml
The GitHub Action for the Windows release builds the [PROJ](https://proj.org/) dependency from source.
The flag passed to disable building its testing tree was renamed and thus no longer working.
The flag was renamed with PROJ version `7.0`, and the version used for the build is `9.3`.
Properly disabling the testing tree building speeds up the PROJ build.
- https://github.com/OSGeo/gdal/blob/449d5f09b796a837ed5473ded4d8455106f1f235/.github/workflows/windows_build.yml#L33
- https://proj.org/en/9.4/install.html#cmdoption-arg-BUILD_TESTING
N/A
> GitHub Actions: fix disable tests flag when building proj for the Windows build

- gcore/gdaldataset.cpp
This avoids GDALDataset::IRasterIO() to potentially modify it.
> GDALDataset: move initialization of m_poPrivate->m_anBandMap to SetBand()

- autotest/ogr/ogr_openfilegdb_write.py
- ogr/ogrsf_frmts/openfilegdb/ogropenfilegdblayer_write.cpp
> [Backport release/3.9] OpenFileGDB writer: fix writing a Int32 field with value -21121

- doc/source/programs/gdalwarp.rst
Backport #10668
**Authored by:** @jratike80
> [Backport release/3.9] gdalwarp.rst: fix spelling of the -te parameters

- port/cpl_conv.cpp
Currently, we import `std::endian` via `type_traits` header from C++ standard library.
[cpl_conv.cpp#L87](https://github.com/OSGeo/gdal/blob/master/port/cpl_conv.cpp#L87)
However, based on [standard](https://en.cppreference.com/w/cpp/types/endian), `std::endian` should be included via `bit` header.
`type_traits` worked fine with C++20, as it transitevely includes `bit` header. 
However, in C++23 standard forced headers to clean up transitive includes, leading to failures in compilation in C++23 mode.
We were able to reproduce that both with clang 18, 19git, 20git both with libc++ (LLVM) and libstdc++ (GNU GCC).
This tiny fix replaces `type_traits` header with `bit` one. I've tested that both in C++20 and C++23 language modes, and it solves the compilation error.
For information purposes, …
> port/cpl_conv.cpp: Use the right header for std::endian in C++20/23

- port/cpl_conv.cpp
Backport #10677
**Authored by:** @gorloffslava
> [Backport release/3.9] port/cpl_conv.cpp: Use the right header for std::endian in C++20/23

- ogr/ogrsf_frmts/shape/gdal_shapelib_symbol_rename.h
Shapelib 1.6.1 introduced new API calls to read and write date attributes These need to be added to the rename header in order to avoid multiple definitions of these symbols
> Add new shapelib API functions to the symbol rename header

- ogr/ogrsf_frmts/sqlite/ogrsqlitedatasource.cpp
> SQLite/GPKG: fix potential double-free issue when concurrently closing datasets when Spatialite is available

- ogr/ogrsf_frmts/sqlite/ogrsqlitedatasource.cpp
> [Backport release/3.9] SQLite/GPKG: fix potential double-free issue when concurrently closing datasets when Spatialite is available

- autotest/gcore/numpy_rw.py
- swig/include/gdal_array.i
Avoids a surprisingly expensive lookup in `gdal_array.NumericTypeCodeToGDALTypeCode`. This was showing up in profiling of a script that calls `ReadAsArray` many times; these changes improve total script runtime by ~10%.
I re-implemented the function `flip_code` because I saw it used in the wild: https://github.com/search?q=gdal_array.flip_code&type=code
> Python bindings: Avoid linear scan in gdal_array.NumericTypeCodeToGDALTypeCode

- autotest/ogr/ogr_geom.py
There was not much testing of that, apart from indirect testing in the DXF driver when it uses this infrastructure for OCS transformation
> autotest: check that OGRGeomety::transform() correctly deals with Z transformation

- autotest/gdrivers/netcdf_multidim.py
- autotest/gdrivers/s102.py
- frmts/netcdf/netcdfdataset.cpp
- frmts/netcdf/netcdfdataset.h
- frmts/netcdf/netcdflayer.cpp
- frmts/netcdf/netcdfvirtual.cpp
- frmts/netcdf/netcdfvirtual.h
- gcore/gdalpamdataset.cpp
- GDALPamDataset::XMLInit(): preserve DerivedDataset nodes that affect S102 PAM saving
- netCDF: make nc_enddef/nc_reddef calls more consistent in netCDFVID
- netCDF: do not override GDALPamDataset::TrySaveXML() to allow proper mixing of classic and multidim PAM metadata
> PAM .aux.xml classic vs multidim fixes

- autotest/gdrivers/netcdf.py
- autotest/gdrivers/netcdf_multidim.py
- autotest/gdrivers/s102.py
- frmts/netcdf/netcdfdataset.cpp
- frmts/netcdf/netcdfdataset.h
- frmts/netcdf/netcdflayer.cpp
- frmts/netcdf/netcdfvirtual.cpp
- frmts/netcdf/netcdfvirtual.h
- gcore/gdalpamdataset.cpp
> netcdf.py: use tmp_path

- alg/gdalgeoloc_dataset_accessor.h
> [Backport release/3.9] Geoloc: fix bad usage of path API that resulted in temporary files not being created where expected

- frmts/mrsid/mrsiddataset.cpp
> [Backport release/3.9] MrSID: prevent infinite recursion in MrSIDDataset::IRasterIO() in some cases

- alg/contour.cpp
- alg/gdal_alg.h
- apps/gdal_contour.cpp
- autotest/utilities/test_gdal_contour.py
- doc/source/programs/gdal_contour.rst
> gdal_contour: add a -gt option to define the transaction flush interval (default it to 100,000)

- doc/source/programs/gdal_rasterize.rst
Update the `gdal_rasterize` CLI documentation related to the `-at` and `-sql` options.
https://github.com/OSGeo/gdal/issues/10649
> gdal_rasterize docs: add notes about -at and -sql options

- swig/include/java/typemaps_java.i
- swig/include/ogr.i
- swig/java/CMakeLists.txt
- swig/java/apps/OGRTest.java
- swig/java/javadoc.java
- swig/java/test_data/iso_8859_1.csv
- Java bindings: make sure a valid UTF-8 string is passed to NewStringUTF()
- Java bindings: OGR module: add various xxxxAsByteArray() method that return a byte[] when content is not UTF-8
Fixes #10521
Fixes #10630
> Java: UTF-8 related fixes

- apps/gdal_rasterize_bin.cpp
- apps/gdal_rasterize_lib.cpp
- apps/gdal_utils_priv.h
```
Usage: gdal_rasterize [--help] [--long-usage] [--help-general]
[-b <band>...]... [-i] [-at]
[[-burn <value>...]...|[-a <attribute_name>]|[-3d]]
[-add]
[[-l <layer_name>]...|[-sql <sql_statement>]]
[-where <expression>] [-dialect <sql_dialect>] [-a_nodata <value>] [-init <value>...]...
[-a_srs <srs_def>] [-to <NAME>=<VALUE>]... [-te <xmin> <ymin> <xmax> <ymax>]
[[-tr <xres> <yres>]|[-ts <width> <height>]]
[-tap] [-optim AUTO|VECTOR|RASTER] [-co <NAME>=<VALUE>]...
[-ot Byte|Int8|[U]Int{16|32|64}|CInt{16|32}|[C]Float{32|64}] [-of <output_format>]
[-oo <NAME>=<VALUE>]... [--quiet]
<src_datasource> <dst_filename>
Burns vector geometries into a raster.
<src_datasource>                                            Any vector supported readable datasource. 
<dst_filename> …
```
> [argparse][gdal_rasterize] Port to arg parser

- doc/source/drivers/raster/gif.rst
- doc/source/drivers/raster/gtiff.rst
- doc/source/drivers/raster/jp2mrsid.rst
- doc/source/drivers/raster/jpeg.rst
- doc/source/drivers/raster/png.rst
Fixes incorrect / missing / typos World Files references in GIF, GTiff, JP2MrSID, JPEG, GTiff and PNG drivers' docs.
* OS:
* Compiler:
> Docs: fix incorrect and missing World Files references (GIF, GTiff, JP2MrSID, JPEG, GTiff, PNG)

- autotest/gdrivers/ogcapi.py
- autotest/ogr/ogr_oapif.py
- frmts/ogcapi/gdalogcapidataset.cpp
- ogr/ogrsf_frmts/wfs/ogroapifdriver.cpp
> OAPIF/OGCAPI: combine CURL error message and data payload (when it exists) to form error message

- autotest/ogr/ogr_openfilegdb.py
- frmts/http/httpdriver.cpp
- ogr/ogrsf_frmts/geojson/ogr_geojson.h
- ogr/ogrsf_frmts/geojson/ogrgeojsondatasource.cpp
- ogr/ogrsf_frmts/geojson/ogrgeojsonseqdriver.cpp
and GeoJSON like driver: avoid fetching unrecognized HTTP dataset more than once
Fixes https://lists.osgeo.org/pipermail/gdal-dev/2024-August/059364.html
> HTTP driver: make parsing of Content-Disposition header aware of double quotes around filename=

- autotest/gdrivers/gti.py
- doc/source/drivers/raster/gti.rst
- frmts/vrt/CMakeLists.txt
- frmts/vrt/gdaltileindexdataset.cpp
@cholmes / @TomAugspurger 
A toot from @mdsumner  (https://mastodon.social/@mdsumner@rstats.me/113053401068184789) made me aware of STAC GeoParquet, and I've quickly realized this was very close to be handled by the recent GDAL Tile Index driver (https://gdal.org/en/latest/drivers/raster/gti.html), which is a generalization of the STACIT one, able to understand any OGR vector layer.
With this PR:
```
$ gdalinfo GTI:/vsicurl/https://github.com/stac-utils/stac-geoparquet/raw/main/tests/data/naip.parquet
Driver: GTI/GDAL Raster Tile Index
Files: none associated
Size is 23688, 14787
Coordinate System is:
PROJCRS["NAD83 / UTM zone 14N",
BASEGEOGCRS["NAD83",
DATUM["North American Datum 1983",
ELLIPSOID["GRS 1980",6378137,298.257222101,
LENGTHUNIT["metre",1]]],
PRIMEM["Greenwich",0, …
```
> GTI driver: recognize STAC GeoParquet catalogs

- alg/gdalwarper.cpp
- autotest/cpp/test_alg.cpp
- autotest/cpp/test_gdal.cpp
- autotest/gdrivers/vrtwarp.py
- doc/source/spelling_wordlist.txt
- frmts/vrt/vrtwarped.cpp
- gcore/gdal.h
- gcore/gdal_misc.cpp
Fixes https://lists.osgeo.org/pipermail/gdal-dev/2024-August/059412.html and a bit beyond
> Fix issues related to warping and source nodata value

- autotest/ogr/ogr_pg.py
With that, successfully passes test with PostgreSQL 17.0rc1 + PostGIS 3.4.3
> autotest: ogr_pg.py: make it work with PostgreSQL release candidates

- alg/viewshed/viewshed.cpp
- doc/source/development/rfc/rfc12_filemanagement.rst
- doc/source/drivers/raster/gti.rst
- doc/source/drivers/raster/nitf.rst
- doc/source/drivers/vector/csv.rst
- doc/source/spelling_wordlist.txt
- gcore/gdaldataset.cpp
- swig/java/javadoc.java
Just a start here, will review the spelling list qnd have more PRs to come.
doc, small typos in 
- GTI driver
- NITF (found when updating the spelling list for GTI)
- core gdaldataset
- swig javadoc
> doc: gti typo (and some others)

- autotest/ogr/ogr_ogrtest.py
The ogrtest.check_feature_geometry(poly_ccw, poly_cw) used to wrongly pass with earlier GEOS versions!
> autotest/ogr/ogr_ogrtest.py: fix with GEOS 3.13

- ogr/ogrfeature.cpp
- ogr/ogrsf_frmts/generic/ogrunionlayer.cpp
- ogr/ogrsf_frmts/sqlite/ogrsqlitelayer.cpp
- ogr/ogrsf_frmts/sqlite/ogrsqlitetablelayer.cpp
- UnionLayer: avoid some potential O(n^2) issues with n=field_count
- SQLite: avoid some potential O(n^2) issues with n=field_count
- OGRFeature: optimizations while accessing field count
Fixes #10765
> Various optimizations to help with layers with big number of fields

- ogr/ogrsf_frmts/generic/ogrsfdriver.cpp
> Make OGRSFDriver::TestCapability(ODrCCreateDataSource) work with defered-loaded drivers

- apps/gdal_rasterize_lib.cpp
- autotest/utilities/test_gdal_rasterize.py
Fixes #10766
argparser is confused by arguments that have at_least_one cardinality, if they immediately precede positional arguments, which is quite undersandable, because if we suppose that we have a -foo argument that takes strings. How would the parser be supposed to distinguish values of -foo from positional filename argument in: ``-foo value1 value2 filename`` ... ? For numeric values, it could probably be tweaked to correctly separate. The problem is that the parse stage doesn't know the type of values of an argument (as they are actions like others...). So my take is that is would be hard to fix argparse to deal with that without significant changes in its code. Basically, currently at_least_one cardinality only works for the last positional argument, and nothing else.
Hum actually …
> gdal_rasterize: fix (workaround) regressions related to argparse for -b / -burn / -init arguments (master only)

- ogr/ogrsf_frmts/generic/ogrsfdriver.cpp
> [Backport release/3.9] Make OGRSFDriver::TestCapability(ODrCCreateDataSource) work with defered-loaded drivers

- alg/gdaltransformer.cpp
- doc/source/programs/gdalwarp.rst
Attempts to add some clarity to documentation of gdalwarp's `-et` parameter, gleaned from review of `GDALApproxTransform`.
> Doc: Clarify behavior of gdalwarp -et option

- .readthedocs.yaml
git log will emit a blank line which passes the grep -v test and prevents exiting.
> CI: Fix ReadTheDocs test for [ci skip] with multiline commit messages

- apps/gdalwarp_lib.cpp
- autotest/utilities/test_gdalwarp_lib.py
Fixes regression introduced by https://github.com/OSGeo/gdal/pull/7911
Test case: https://lists.osgeo.org/pipermail/gdal-dev/2024-September/059512.html
Fixes #10827
> gdalwarp: fix crash/infinite loop when using -tr one a 1x1 blank raster (3.8.0 regression)

- alg/viewshed/combiner.h
- alg/viewshed/cumulative.cpp
- alg/viewshed/cumulative.h
- alg/viewshed/notifyqueue.h
- alg/viewshed/progress.h
- alg/viewshed/util.h
- alg/viewshed/viewshed.cpp
- alg/viewshed/viewshed.h
- alg/viewshed/viewshed_types.h
- port/cpl_worker_thread_pool.cpp
> Fix issue with gdal_viewshed with gcc 9.4 in debug mode (master only)

- alg/gdalwarper.cpp
- doc/source/spelling_wordlist.txt
and document XSCALE and YSCALE warping options
Ref #10813
> gdalwarper.cpp: more details about OPTIMIZE_SIZE

- apps/ogr2ogr_lib.cpp
- autotest/cpp/test_ogr.cpp
- autotest/cpp/test_ogr_wkb.cpp
- autotest/utilities/test_ogr2ogr_lib.py
- ogr/ogr_geometry.h
- ogr/ogr_wkb.cpp
- ogr/ogr_wkb.h
- ogr/ogrct.cpp
- ogr/ogrgeometryfactory.cpp
- ogr/ogrsf_frmts/gpkg/ogr_geopackage.h
- ogr/ogrsf_frmts/gpkg/ogrgeopackagedatasource.cpp
- ogr/ogrsf_frmts/gpkg/ogrgeopackageutility.cpp
- ogr/ogrsf_frmts/gpkg/ogrgeopackageutility.h
(on top of PR #10716)
Use newly added OGRWKBTransform(), when possible, to speed-up -t_srs in Arrow code path (which is triggered in Parquet/GPKG -> anything, when no option or no other option than -t_srs is specified). Also use multi-threaded coordinate transformation by splitting the features within each batch in several sub-batches, each processed in its own thread.
Can result in a 3.3x speed-up in ogr2ogr Parquet->Parquet -t_srs use case on a 3.2 million feature dataset:
No reprojection:
```
$ time ogr2ogr out.parquet nz-building-outlines.parquet
real	0m5,687s
user	0m5,254s
sys	0m1,032s
```
Reprojection EPSG:2193 ("NZGD2000 / New Zealand Transverse Mercator 2000") to EPSG:4326 without optimization:
```
$ time ogr2ogr out.parquet nz-building-outlines.parquet -t_srs EPSG:4326 --config …
```
> ogr2ogr: speed-up reprojection in Arrow code path

- apps/ogr2ogr_lib.cpp
- ogr/ogrsf_frmts/arrow/ogrfeatherdriver.cpp
- ogr/ogrsf_frmts/arrow_common/ogr_arrow.h
- ogr/ogrsf_frmts/arrow_common/ograrrowrandomaccessfile.h
- ogr/ogrsf_frmts/arrow_common/vsiarrowfilesystem.hpp
- ogr/ogrsf_frmts/parquet/ogr_parquet.h
- ogr/ogrsf_frmts/parquet/ogrparquetdataset.cpp
- ogr/ogrsf_frmts/parquet/ogrparquetdriver.cpp
- port/cpl_vsi_virtual.h
- port/cpl_vsil_curl.cpp
- port/cpl_vsil_curl_class.h
- VSIVirtualHandle: add a Interrupt() method and implement in in /vsicurl/ (and related filesystems)
- Parquet: in dataset mode, make sure all files are closed before closing the GDALDataset, to avoid crashes particularly on /vsicurl/ (and related filesystems) files
- ogr2ogr: remove hack related to Parquet dataset
> Parquet: in dataset mode, make sure all files are closed before closing the GDALDataset

- autotest/gdrivers/wmts.py
- frmts/wmts/wmtsdataset.cpp
> WMTS: when reading a WMTS capabilities file, use in priority Operation.GetCapabilities.DCP.HTTP to retrieve the URL

- autotest/ogr/ogr_jsonfg.py
- ogr/ogrsf_frmts/jsonfg/ogrjsonfgreader.cpp
During that phase, we only need the geometry type.
> JSONFG: avoid Polyhedron/Prism geometry instantiation during initial scan

- autotest/ogr/ogr_flatgeobuf.py
- ogr/ogrsf_frmts/generic/ogr_gensql.cpp
- ogr/ogrsf_frmts/generic/ogr_gensql.h
- ogr/ogrsf_frmts/generic/ogrlayerarrow.cpp
- ogr/ogrsf_frmts/generic/ogrlayerarrow.h
- ogr/ogrsf_frmts/ogrsf_frmts.h
- perftests/bench_ogr_batch.cpp
This can speed-up ``ogr2ogr -sql`` scenarios where the source is Arrow/Parquet/FlatGeoBuf and the SQL statement is something as simple as "SELECT column_a [AS renamed], ... FROM the_layer [WHERE some_cond] [LIMIT limit]"  with all or a subset of columns, not reordered compared to the source layer, or repeated.
e.g. ``time ogr2ogr out.arrow  nz-building-outlines.parquet -sql "select building_id from \"nz-building-outlines\""`` goes down from 11.8 s to 4.4 s
(GeoPackage as a source had already an efficient Arrow SQL layer implementation)
> GenSQL layer: implement OLCFastGetArrowStream when underlying layer does and for very simple SQL statements

- autotest/gcore/rasterio.py
- gcore/gdalnodatamaskband.cpp
- gcore/overview.cpp
- gcore/rasterio.cpp
Fixes #10758
Also make sure that for other resampling methods, the working data type is large enough (e.g using Float64 for Int32/UInt32/Int64/UInt64). While doing so, fix an underlying bug in the convolution based code, where a hard-coded pixel stride value of 4 was used instead of sizeof(TWork), which I believe wasn't visible before.
> Overview: fix nearest and mode resamplings to be exact with all data types

- swig/python/setup.py.in
Previous workarounds (PR #8003) no longer worked with latest SWIG versions
Refs #4907
> Python bindings: silence SWIG 'detected a memory leak' message

- autotest/ogr/ogr_geojson.py
- ogr/ogrsf_frmts/mem/ogrmemlayer.cpp
> [Backport release/3.9] MEM layer: fix UpdateFeature() that didn't mark the layer as updated, which caused GeoJSON files to not be updated

- swig/python/setup.py.in
> [Backport release/3.9] Python bindings: silence SWIG 'detected a memory leak' message

- .github/workflows/ubuntu_22.04/services.sh
- .github/workflows/ubuntu_22.04/test.sh
- .github/workflows/ubuntu_24.04/services.sh
- .github/workflows/ubuntu_24.04/test.sh
This has become unreliable lately with failures like in https://github.com/OSGeo/gdal/actions/runs/10930480309/job/30377732865?pr=10840
```
+ docker exec -t gdal-sql1 /opt/mssql-tools/bin/sqlcmd -l 30 -S localhost -U SA -P DummyPassw0rd -Q CREATE DATABASE TestDB
Error response from daemon: container fba0406fd45fd855feea4090a0b46c321d70c1b4e000ba318ff1045c400d1b43 is not running
```
Although I can't reproduce the error locally
> CI: disable MSSQL Docker based testing

- doc/source/development/rfc/index.rst
- doc/source/development/rfc/rfc101_raster_dataset_threadsafety.rst
- doc/source/spelling_wordlist.txt
Rendered view at https://gdal--10676.org.readthedocs.build/en/10676/development/rfc/rfc101_raster_dataset_threadsafety.html
> Add RFC101 text: Raster dataset read-only thread-safety

- ogr/ogrsf_frmts/miramon/mm_wrlayr.c
- ogr/ogrsf_frmts/miramon/ogrmiramonlayer.cpp
MiraMonVector: fix Issue 369216702
Fixes Issue 369216702
https://issues.oss-fuzz.com/issues/369216702
> MiraMonVector: fix Issue 369216702

- swig/include/python/gdal_python.i
> Python bindings: clarify destNameOrDestDS semantics regarding updates

- alg/gdalgeoloc.cpp
- alg/gdalgeoloc_dataset_accessor.h
- autotest/gcore/vrt_read.py
- frmts/vrt/vrtsourcedrasterband.cpp
- frmts/vrt/vrtsources.cpp
Fixes #10809 
Timing back from ages (half an hour or so) to 20 seconds.
Also fixes a bug related to Int64/UInt64 VRT bands with nodata.
> Speed-up geolocation-array based warping of Sentinel3 datasets

- autotest/gdrivers/vrtwarp.py
- frmts/vrt/vrtdataset.h
- frmts/vrt/vrtwarped.cpp
This benefits use cases with a 'large' number of overview levels, and where creation of the GDALWarpOperation for each one is slow (might involve PROJ operations)
On a warped VRT using a source GeoTIFF with 7 overview levels, ``gdal_translate warped_vrt.vrt out.tif -outsize 1024 0`` goes from 1.6 sec to 0.9 s.
> Warped VRT: instantiate overview bands in a lazy fashion for faster execution

- doc/source/drivers/raster/vrt.rst
- doc/source/spelling_wordlist.txt
- doc/source/user/index.rst
- doc/source/user/security.rst
Adapted from https://trac.osgeo.org/gdal/wiki/SecurityIssues
> Doc: add a page about security issues

- alg/contour.cpp
- alg/marching_squares/segment_merger.h
- alg/marching_squares/square.h
- autotest/alg/contour.py
> [gdal_contour] Fix regression when fixed level == raster max

- alg/gdalwarpkernel.cpp
- autotest/utilities/test_gdalwarp_lib.py
Amends https://github.com/OSGeo/gdal/pull/6482
Fixes #10892
> Warper: fix too lax heuristics about antimeridian warping for Avg/Sum/Q1/Q3/Mode algorithms

- apps/test_ogrsf.cpp
- autotest/ogr/ogr_libkml.py
- doc/source/drivers/vector/libkml.rst
- ogr/ogrsf_frmts/libkml/fieldconfig.h
- ogr/ogrsf_frmts/libkml/ogr_libkml.h
- ogr/ogrsf_frmts/libkml/ogrlibkmlfeature.cpp
- ogr/ogrsf_frmts/libkml/ogrlibkmlfeature.h
- ogr/ogrsf_frmts/libkml/ogrlibkmlfield.cpp
- ogr/ogrsf_frmts/libkml/ogrlibkmlfield.h
- ogr/ogrsf_frmts/libkml/ogrlibkmlgeometry.cpp
- ogr/ogrsf_frmts/libkml/ogrlibkmllayer.cpp
> LIBKML: report XML id attribute as 'id' field; implement SetFeature() and DeleteFeature() for regular layers

- autotest/gcore/vsicurl.py
- doc/source/spelling_wordlist.txt
- doc/source/user/configoptions.rst
- doc/source/user/virtual_file_systems.rst
- port/cpl_http.cpp
- port/cpl_vsil_curl.cpp
- port/cpl_vsil_curl_class.h
Can be configured with the CPL_VSIL_CURL_AUTHORIZATION_HEADER_ALLOWED_IF_REDIRECT=YES/NO/IF_SAME_HOST config option
Fixes https://lists.osgeo.org/pipermail/gdal-dev/2024-September/059536.html
>  /vsicurl/: no longer forward Authorization header when doing redirection to other hosts.

- autotest/gdrivers/mem.py
- doc/source/drivers/raster/mem.rst
- frmts/mem/memdataset.cpp
```
Starting with GDAL 3.10, opening a MEM dataset using the above syntax is no
longer enabled by default for security reasons.
If you want to allow it, define the ``GDAL_MEM_ENABLE_OPEN`` configuration
option to ``YES``, or build GDAL with the ``GDAL_MEM_ENABLE_OPEN`` compilation
definition.
.. config:: GDAL_MEM_ENABLE_OPEN
:choices: YES, NO
:default: NO
:since: 3.10
Whether opening a MEM dataset with the ``MEM:::`` syntax is allowed.
```
> Raster MEM driver: disable opening a dataset with MEM::: syntax by default

- alg/gdalwarpkernel.cpp
- autotest/utilities/test_gdalwarp_lib.py
> [Backport release/3.9] Warper: fix too lax heuristics about antimeridian warping for Avg/Sum/Q1/Q3/Mode algorithms

- autotest/gdrivers/pdf.py
- frmts/pdf/pdfdataset.cpp
> [Backport release/3.9] PDF: avoid 'Non closed ring detected' warning when reading neatlines from OGC Best Practice encoding

- apps/gdaltransform.cpp
- autotest/cpp/test_cpl.cpp
- ogr/ogrsf_frmts/csv/ogrcsvlayer.cpp
- port/cpl_string.cpp
Fixes https://github.com/Toblerity/Fiona/issues/1454
> CPLGetValueType(): do not recognize '01' as integer, but as string

- autotest/gcore/gdal_stats.py
- autotest/gcore/hfa_rfc40.py
- autotest/gcore/hfa_srs.py
- autotest/gcore/hfa_write.py
- autotest/gcore/pam.py
- autotest/gcore/tiff_ovr.py
- autotest/gcore/tiff_read.py
- autotest/gdrivers/hfa.py
- autotest/gdrivers/pcidsk.py
- autotest/pyscripts/test_gdalinfo_py.py
- autotest/pyscripts/test_pct.py
- autotest/utilities/test_gdal_translate.py
- autotest/utilities/test_gdalinfo.py
- frmts/CMakeLists.txt
- frmts/hfa/CMakeLists.txt
- gcore/CMakeLists.txt
- gcore/gdaldefaultoverviews.cpp
- ogr/ogr_proj_p.h
Note that when built as a plugin, HFA .aux overview building is not supported
> HFA (Erdas Imagine) driver: make it optional and buildable as a plugin

- doc/source/sponsors/faq.rst
Fix link in documentation. Broken due to migration to readthedocs.
The link is now the same as in index.html
> [doc] fix link to GDAL sponsorship prospectus

- apps/gdalwarp_lib.cpp
- autotest/gcore/rasterio.py
- autotest/utilities/test_gdalwarp.py
- gcore/rasterio.cpp
Fixes #10873
Uniformize logic with the one of GDALBandGetBestOverviewLevel2()
> gdalwarp: be more robust to numerical instability when selecting overviews

- apps/gdaltransform.cpp
- autotest/cpp/test_cpl.cpp
- ogr/ogrsf_frmts/csv/ogrcsvlayer.cpp
- port/cpl_string.cpp
> [Backport release/3.9] CPLGetValueType(): do not recognize '01' as integer, but as string

- autotest/utilities/test_gdalwarp_lib.py
- swig/include/python/gdal_python.i
> Python bindings: fix passing a dict value to the transformerOptions argument of gdal.Warp()

- docker/alpine-normal/Dockerfile
- docker/alpine-small/Dockerfile
- docker/ubuntu-full/Dockerfile
- docker/ubuntu-full/bh-gdal.sh
- docker/ubuntu-full/bh-proj.sh
- docker/ubuntu-small/Dockerfile
The -q parameter to wget makes it completely
silent, even on faliure which gives build errors
that are difficult to diagnose. Someone
else had the same problem 15 years ago:
https://serverfault.com/questions/70889/wget-to-print-errors-but-nothing-otherwise
and the easiest way to robustly print
errors but nothing else seems to be
to use curl instead.
Since the docker images already include
curl, switch them to use that instead.
I'm getting intermittent build failures when building GDAL images. I can't reproduce the problem, but network-related operations have failed before (#9571), so print an error when things go wrong.
No issue filed.
* OS:
* Compiler:
> docker: print HTTP errors on failure

- autotest/gdrivers/nitf.py
- doc/source/drivers/raster/nitf.rst
- frmts/nitf/nitfdataset.cpp
when JPEG2000_DRIVER=JP2OpenJPEG
Fixes #10927
> NITF: properly take into account comma-separated list of values for JPEG2000 QUALITY

- apps/gdalwarp_lib.cpp
- autotest/gcore/rasterio.py
- autotest/utilities/test_gdalwarp.py
- gcore/rasterio.cpp
> [Backport release/3.9] gdalwarp: be more robust to numerical instability when selecting overviews

- autotest/ogr/ogr_pg.py
- ogr/ogrsf_frmts/pgdump/ogrpgdumpdatasource.cpp
> [Backport release/3.9] PG/PGDump: properly truncates identifiers exactly of 64 characters

- autotest/utilities/test_gdalwarp_lib.py
- swig/include/python/gdal_python.i
> [Backport release/3.9] Python bindings: fix passing a dict value to the transformerOptions argument of gdal.Warp()

- frmts/dimap/dimapdataset.cpp
> [Backport release/3.9] DIMAP: emit verbose error message if not able to open image file

- autotest/utilities/test_gdalinfo.py
- autotest/utilities/test_ogrinfo.py
- doc/source/programs/raster_common_options.rst
- doc/source/programs/vector_common_options.rst
- gcore/gdal_misc.cpp
Fixes #10878
Note: only available in utilities-as-binaries, not utilities-as-libraries...
Returns drivers in the order of their registration.
Example
```shell
$ gdalinfo --formats -json
[
{
"short_name":"VRT",
"long_name":"Virtual Raster",
"scopes":[
"raster",
"multidimensional_raster"
],
"capabilities":[
"open",
"create",
"create_copy",
"virtual_io"
],
"file_extensions":[
"vrt"
]
},
...
]
```
```shell
$ ogrinfo --formats -json
[
{
"short_name":"FITS",
"long_name":"Flexible Image Transport System",
"scopes":[
"raster",
"vector"
],
"capabilities":[
"open",
"create"
],
"file_extensions":[
"fits"
]
},
...
]
```
> Make gdalinfo/ogrinfo --formats -json work

- docker/alpine-normal/Dockerfile
- docker/alpine-small/Dockerfile
- docker/ubuntu-full/bh-gdal.sh
- docker/ubuntu-full/bh-proj.sh
- docker/ubuntu-small/Dockerfile
The rsync commands use the wrong
directory, so the commands fail
and print an error message, but
the build continues.
Fix the commands so they work,
but leave the missing error
detection as is.
> docker: fix ccache

- frmts/wms/wmsmetadataset.cpp
> WMS: try to be robust to servers using CRS instead of SRS in 1.1.1 mode (and warn about that)

- frmts/gtiff/gtiffdataset_read.cpp
Fixes https://github.com/cogeotiff/rio-tiler/issues/697
> GTiff: use main dataset GetSiblingFiles() for overviews

- ogr/ogrfeature.cpp
> OGRFeature: SetXXX() methods: more informative warning messages reporting field name and value for out-of-range values

- alg/gdal_alg_priv.h
- alg/gdal_rpc.cpp
- alg/gdaltransformer.cpp
- alg/gdalwarper.h
- alg/gdalwarpoperation.cpp
- autotest/gdrivers/vrtwarp.py
- frmts/vrt/vrtdataset.h
- frmts/vrt/vrtwarped.cpp
Fixes https://github.com/rasterio/rasterio/issues/3203
With that optimization:
```
$ gdalwarp /vsicurl/https://sentinel-cogs.s3.us-west-2.amazonaws.com/sentinel-s2-l2a-cogs/15/T/VK/2023/10/S2B_15TVK_20231008_0_L2A/TCI.tif in.vrt
$ CPL_DEBUG=VSICURL GDAL_INGESTED_BYTES_AT_OPEN=32768 GDAL_HTTP_MULTIRANGE=YES GDAL_HTTP_MERGE_CONSECUTIVE_RANGES=YES GDAL_DISABLE_READDIR_ON_OPEN=EMPTY_DIR python -c "from osgeo import gdal; ds = gdal.Open('in.vrt'); ds.ReadRaster(0, 0, ds.RasterXSize, ds.RasterYSize, ds.RasterXSize // 5, ds.RasterYSize // 5)"
/home/even/gdal/gdal/build_cmake/swig/python/osgeo/gdal.py:311: FutureWarning: Neither gdal.UseExceptions() nor gdal.DontUseExceptions() has been explicitly called. In GDAL 4.0, exceptions will be enabled by default.
warnings.warn(
VSICURL: …
```
> VRTWarpedDataset::IRasterIO(): optimize I/O when requesting whole image at a resolution that doesn't match an overview

- doc/source/user/sql_sqlite_dialect.rst
Anyway, above it already said
> case-insensitively (as all field names are in a SELECT statement):
> Update sql_sqlite_dialect.rst removing repeated section

- docker/alpine-normal/Dockerfile
- docker/alpine-small/Dockerfile
- docker/ubuntu-full/Dockerfile
- docker/ubuntu-full/bh-gdal.sh
- docker/ubuntu-full/bh-proj.sh
- docker/ubuntu-small/Dockerfile
- docker/util.sh
This changes a lot of things all over the place, but the big picture is:
- Release builds pass `--no-cache` to Docker so they don't accidentally pick up something from the Docker cache. For local experimentation, that can be overridden by passing `--docker-cache` to build.sh.
- The deb packages+lists are cached in Docker for non-release builds. This avoids fetching the same thing from the network repeatedly. The cache for apt can only be used by one build at the time so that is mounted with `sharing=locked`. To avoid blocking concurrent docker image builds, apt-get calls were put in a separate `RUN` statement from a long-running compilation.
- Separation of rsync and ccache behavior, which lets the user disable the gdal rsync daemon but still benefit from ccache and the Docker cache.
It's …
> docker: enable more caching

- alg/gdalwarpoperation.cpp
- apps/gdalwarp_lib.cpp
- autotest/cpp/test_cpl.cpp
- autotest/utilities/test_gdalwarp.py
- doc/source/programs/gdalwarp.rst
- port/cpl_string.cpp
- port/cpl_string.h
Validates the `-wm` argument to gdalwarp so that invalid values cause a failure. Also allows more clear specification of memory amount with units (`-wm 1G`, `-wm 200MB`), or as a fraction of usable memory (`-wm 10%`). Probably overkill for this purpose but I think there are other places the same function could be used, such as the parsing of `GDAL_CACHEMAX`.
#10888, #10889
> gdalwarp: allow specifying units of warp memory

- docker/ubuntu-full/Dockerfile
I did not realize that PROJ is built twice
in ubuntu-full, so add the cache mount
to the first build as well.
> docker/ubuntu-full: cache both PROJ builds

- autotest/gdrivers/ecw.py
- autotest/gdrivers/nitf.py
- frmts/ecw/ecwdataset.cpp
> JP2ECW: report JPEG2000 tile size as GDAL block size for ECW SDK >= 51 (up to 2048x2048 and dataset dimensions)

- autotest/ogr/ogr_pg.py
- ogr/ogrsf_frmts/pg/ogrpgdatasource.cpp
Fixes https://lists.osgeo.org/pipermail/gdal-dev/2024-October/059608.html
> PG: avoid error when the original search_path is empty

- swig/python/gdal-utils/osgeo_utils/samples/validate_cloud_optimized_geotiff.py
It adds an invocation of `gdal.useExceptions()` to validate_cloud_optimized_geotiff.py.
> Invoke 'gdal.UseExceptions' in validate_cloud_optimized_geotiff.py

- autotest/ogr/ogr_arrow.py
- autotest/ogr/ogr_parquet.py
- doc/source/drivers/vector/arrow.rst
- ogr/ogrsf_frmts/arrow/ogrfeatherdriver.cpp
- ogr/ogrsf_frmts/arrow/ogrfeatherdrivercore.cpp
- ogr/ogrsf_frmts/arrow/vsifilesystemregistrar.cpp
In c889f141e44071e8c21627e4f2a5fc4229da989a (3.10.0dev), we have introduced a (C++) bridge from GDAL VSI to Arrow file system that used the 'vsi://' prefix. But as we are also going to introduce at the Python level as bridge from GDAL VSI to fsspec (https://github.com/OSGeo/gdal/pull/10985) that is going to use a 'gdalvsi://' prefix, better use the same prefix.
> Use 'gdalvsi://' protocol prefix (instead of 'vsi://') for Arrow VSI file system

- docker/ubuntu-full/Dockerfile
- docker/ubuntu-full/bh-set-envvars.sh
- docker/ubuntu-full/tiledb-cmake-ccache.patch
- docker/ubuntu-small/Dockerfile
- docker/util.sh
- scripts/binaries_allow_list.csv
This PR removes the build support for openjpeg since that hasn't been active since the upgrade to Ubuntu 20.04, and adds ccache for the non-OSGeo projects that are built as part of producing the ubuntu-full image.
> docker: add ccache for upstream builds

- autotest/gdrivers/netcdf.py
- frmts/netcdf/netcdfdataset.cpp
> netCDF: do not emit error when longitude axis unit is degrees_east and latitude axis unit is degrees_north

- apps/ogr2ogr_lib.cpp
- ogr/ogr_recordbatch.h
- ogr/ogrsf_frmts/generic/ogrlayerarrow.h
as this might be an expensive operation on some drivers.
Covered by existing tests.
> ogr2ogr: optim: call GetArrowStream() only once on source layer when using Arrow interface

- autotest/ogr/ogr_libkml.py
- ogr/ogrsf_frmts/libkml/ogrlibkmllayer.cpp
Addresses https://github.com/OSGeo/gdal/pull/10840#issuecomment-2407730851
> LIBKML: don't report OLCRandomWrite/OLCDeleteFeature if first Placemark has no id

- docker/ubuntu-full/Dockerfile
I've observed while building 3.9.3 image systematic failures when using curl on https://github.com/ content, when run under the arm64 architecture under docker buildx (with qemu)
Cf:
```
* Host github.com:443 was resolved.
* IPv6: (none)
* IPv4: 140.82.121.3
*   Trying 140.82.121.3:443...
* Connected to github.com (140.82.121.3) port 443
* ALPN: curl offers h2,http/1.1
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [122 bytes data]
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
{ [19 bytes data]
* TLSv1.3 (IN), TLS handshake, Certificate (11):
{ [3137 bytes data]
* TLSv1.3 (IN), TLS handshake, CERT …
```
> docker/ubuntu-full/Dockerfile: revert to using wget for https://github.com/ stuff

- docker/ubuntu-full/Dockerfile
I've observed while building 3.9.3 image systematic failures when using curl on https://github.com/ content, when run under the arm64 architecture under docker buildx (with qemu)
Cf:
```
* Host github.com:443 was resolved.
* IPv6: (none)
* IPv4: 140.82.121.3
*   Trying 140.82.121.3:443...
* Connected to github.com (140.82.121.3) port 443
* ALPN: curl offers h2,http/1.1
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [122 bytes data]
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
{ [19 bytes data]
* TLSv1.3 (IN), TLS handshake, Certificate (11):
{ [3137 bytes data]
* TLSv1.3 (IN), TLS handshake, CERT …
```
> [3.9] docker/ubuntu-full/Dockerfile: revert to using wget for https://github.com/ stuff

- apps/gdal_rasterize_lib.cpp
... even if it has no effect.
Fix #11028
> [gdal_rasterize] allow -q in library mode

- apps/gdal_rasterize_lib.cpp
> [Backport release/3.10] [gdal_rasterize] allow -q in library mode

- ogr/ogrlinestring.cpp
The existing error message is pretty useless (and not grammatically correct).
> Improve error message when OGRSimpleCurve point limit is exceeded

- ogr/ogrlinestring.cpp
Backport #11038
**Authored by:** @atlight
> [Backport release/3.10] Improve error message when OGRSimpleCurve point limit is exceeded

- .github/workflows/code_checks.yml
Issue has been reported to https://sourceforge.net/p/ruamel-yaml-clib/tickets/38/
> CI: fix 'other_checks' job that breaks on 'cffconvert --validate'

- MIGRATION_GUIDE.TXT
These links got broken when Trac was retired, let's update them to prevent confusion (I recently had to dig up RFC 73 for someone).
> MIGRATION_GUIDE.TXT: migrate away from Trac links

- autotest/gdrivers/dimap.py
- frmts/dimap/dimapdataset.cpp
CC @tbonfort 
In b3f3ce79e914164b57c7ca58a8e0515e7b5a836b , you added logic to register metadata on the bands, but it doesn't look to work with the fake dataset we have in autotest/gdrivers/data/dimap2/vhr2020_ms_fs/MS-FS/DIM_MS-FS.XML, nor a PNEO_ORTHO_BUNDLE-FS_REFLECTANCE_JPEG2000_4326_NONE_STD_A one I likely got during the development of the PNEO support.
The reason I ask is that I rather see a Radiometric_Data.Radiometric_Calibration.Band_Spectral_Range (rather than Radiometric_Data.Radiometric_Calibration.Instrument_Calibration.Band_Measurement_List as expected by the driver) element with subnodes like:
```
<Band_Spectral_Range>
<BAND_ID>R</BAND_ID>
<CALIBRATION_DATE>2019-05-20T09:07:00Z</CALIBRATION_DATE>
<MEASURE_DESC>Spectral Range values of raw radiometric Band</MEASURE_DESC> …
```
> DIMAP: for PNEO products, use the new color interpretations for the NIR, RedEdge and DeepBlue/Coastal bands

- .github/workflows/ubuntu_24.04/expected_gdalinfo_formats.txt
- .github/workflows/windows_conda_expected_gdalinfo_formats.txt
- frmts/snap_tiff/snaptiffdriver.cpp
Fixes https://github.com/qgis/QGIS/issues/59112
> SNAP_TIFF: do not declare extension to avoid confusing QGIS

- autotest/ogr/ogr_geojson.py
- ogr/ogrsf_frmts/generic/ogrlayerarrow.cpp
Fixes
https://github.com/geopandas/pyogrio/issues/487#issuecomment-2422851167 regarding GeoJSON
> Arrow reading: generic code path (as used by GeoJSON): fix mis-handling of timezones

- autotest/gdrivers/dimap.py
- frmts/dimap/dimapdataset.cpp
> [Backport release/3.10] DIMAP: for PNEO products, use the new color interpretations for the NIR, RedEdge and DeepBlue/Coastal bands

- .github/workflows/ubuntu_24.04/expected_gdalinfo_formats.txt
- .github/workflows/windows_conda_expected_gdalinfo_formats.txt
- frmts/snap_tiff/snaptiffdriver.cpp
> [Backport release/3.10] SNAP_TIFF: do not declare extension to avoid confusing QGIS

- autotest/ogr/ogr_gpkg.py
- ogr/ogrsf_frmts/gpkg/ogrgeopackagetablelayer.cpp
> [Backport release/3.10] GPKG: prevent from creating field with same name or with the name of the geometry field

- autotest/ogr/ogr_geojson.py
- ogr/ogrsf_frmts/generic/ogrlayerarrow.cpp
> [Backport release/3.10] Arrow reading: generic code path (as used by GeoJSON): fix mis-handling of timezones

- ogr/ogrsf_frmts/gpkg/ogr_geopackage.h
- ogr/ogrsf_frmts/gpkg/ogrgeopackagedatasource.cpp
- ogr/ogrsf_frmts/gpkg/ogrgeopackagelayer.cpp
- ogr/ogrsf_frmts/gpkg/ogrgeopackagetablelayer.cpp
> [Backport release/3.10] GPKG: fix memleaks in usage of GetSpatialRef(int, ...)

- frmts/heif/heifdataset.cpp
In reworking the heif driver to support tiles (in #10982), I inadvertently introduced a memory leak. This fixes that.
N/A
* OS:
* Compiler:
> heif: fix memory leak of image data

- frmts/jp2lura/jp2luradrivercore.cpp
I discovered accidentally the method was mis-identifying a EXR dataset as recognized by the JP2Lura driver while investigating https://github.com/OSGeo/gdal/issues/11095. This dates back to 2e650d8cace54238f863ca705cd20030409cf295 where for some reason (I suspect wrong copy&paste) the Identify() logic was completely changed
> JP2Lura: fix Identify() method

- autotest/ogr/ogr_openfilegdb_write.py
- ogr/ogrsf_frmts/filegdb/FGdbUtils.cpp
- ogr/ogrsf_frmts/openfilegdb/filegdb_reserved_keywords.h
- ogr/ogrsf_frmts/openfilegdb/ogropenfilegdblayer_write.cpp
> FileGDB/OpenFileGDB: update (and unify) list of reserved keywords that can't be used for column/table names

- frmts/jp2lura/jp2luradrivercore.cpp
> [Backport release/3.10] JP2Lura: fix Identify() method

- doc/source/drivers/raster/gtiff.rst
I suppose that recommending 256x256, 512x512, or 1024x1024 sized blocks makes sense, because the "group" in JPEG XL is 256x256 pixels.
> Doc: document that JXL-in-GeoTIFF requires tiled=yes

- apps/gdal_translate_lib.cpp
- apps/gdalwarp_lib.cpp
- apps/ogr2ogr_lib.cpp
- autotest/utilities/test_gdal_translate.py
- autotest/utilities/test_gdalwarp_lib.py
- autotest/utilities/test_ogr2ogr.py
- autotest/utilities/test_ogr2ogr_lib.py
- swig/include/python/gdal_python.i
Addresses some cases where invalid values to command line arguments would be silently accepted and converted to zero or otherwise misinterpreted.
#10889
> Remove some unchecked float parsing in command line utils

- apps/ogr2ogr_lib.cpp
- autotest/utilities/test_ogr2ogr_lib.py
> ogr2ogr: fix -explodecollections on empty geometries

- apps/ogr2ogr_lib.cpp
- autotest/utilities/test_ogr2ogr_lib.py
> [Backport release/3.10] ogr2ogr: fix -explodecollections on empty geometries

- frmts/heif/heifdataset.cpp
Adds compile-time checks that the required enum values are present in the version of libheif we are compiling against.
This came out of #11095.
* OS:
* Compiler:
> heif: protect against testing for enums that might not exist

- autotest/gdrivers/jpegxl.py
- doc/source/drivers/raster/cog.rst
- doc/source/drivers/raster/gtiff.rst
- doc/source/drivers/raster/jpegxl.rst
- frmts/gtiff/cogdriver.cpp
- frmts/gtiff/geotiff.cpp
- frmts/jpegxl/jpegxl.cpp
- frmts/jpegxl/jpegxldrivercore.cpp
to be in sync with latest libjxl
Fixes #11095
> JPEGXL: allow a minimum DISTANCE of 0.01, max of 25 and revise QUALITY to DISTANCE formula

- .github/workflows/cmake_builds.yml
- .github/workflows/conda.yml
Fixes following action warning:
'Mambaforge is now deprecated! Future Miniforge releases will NOT build Mambaforge installers. We advise you switch to Miniforge at your earliest convenience. More details at
https://conda-forge.org/news/2024/07/29/sunsetting-mambaforge/. If you require Mambaforge, you may pin your installer to one found in https://github.com/conda-forge/miniforge/releases/tag/24.7.1-0'
> CI: 'miniforge-variant: Mambaforge' is no longer supported; use Miniforge instead

- .github/workflows/cmake_builds.yml
- .github/workflows/conda.yml
> [Backport release/3.10] CI: 'miniforge-variant: Mambaforge' is no longer supported; use Miniforge instead

- autotest/gdrivers/jpegxl.py
- doc/source/drivers/raster/cog.rst
- doc/source/drivers/raster/gtiff.rst
- doc/source/drivers/raster/jpegxl.rst
- frmts/gtiff/cogdriver.cpp
- frmts/gtiff/geotiff.cpp
- frmts/jpegxl/jpegxl.cpp
- frmts/jpegxl/jpegxldrivercore.cpp
> [Backport release/3.10] JPEGXL: allow a minimum DISTANCE of 0.01, max of 25 and revise QUALITY to DISTANCE formula

- autotest/gcore/tiff_write.py
- frmts/gtiff/tif_jxl.c
Similar to fix done in standalone JPEGXL driver in PR #11099
> tif_jxl: writer: propagate DISTANCE/QUALITY setting to extra channel

- ogr/ogr_core.h
> ogr_core.h: suppress warning when building with -Wpedantic for C < 23

- ogr/ogr_core.h
> [Backport release/3.10] ogr_core.h: suppress warning when building with -Wpedantic for C < 23

- autotest/gcore/misc.py
Simplifies one test, for multiple CreateCopy format checks.
At https://github.com/OSGeo/gdal/pull/11093#discussion_r1813240336 @rouault identified that the JPEG 2000 test case suppression was obsolete. This PR removes that obsolete code.
The change looks bigger than that, because of the required re-indent and slightly confusing diff. The only part that is actually removed is this:
```
skip = False
if drv.ShortName == "JPEG2000":
if (nBands == 2 or nBands >= 5) or not (
datatype == gdal.GDT_Byte
or datatype == gdal.GDT_Int16
or datatype == gdal.GDT_UInt16
):
skip = True
if skip is False:
```
* OS:
* Compiler:
> tests: simplify createcopy test

- autotest/cpp/test_cpl.cpp
- autotest/gcore/vsifile.py
- doc/source/user/configoptions.rst
- gcore/gdalrasterblock.cpp
- port/cpl_string.cpp
- port/cpl_vsil_cache.cpp
- port/cpl_vsil_curl.cpp
Uses `CPLParseMemorySize` for consistent parsing and error reporting from `GDAL_CACHEMAX`, `VSI_CACHE_SIZE`, `CPL_VSIL_CURL_CACHE_SIZE`, and `CPL_VSIL_CURL_CHUNK_SIZE`.
> Use CPLParseMemorySize for GDAL_CACHEMAX and similar config options

- ogr/ogrsf_frmts/arrow_common/ograrrowlayer.hpp
- ogr/ogrsf_frmts/arrow_common/ograrrowwriterlayer.hpp
- ogr/ogrsf_frmts/parquet/ogrparquetlayer.cpp
Essentially to fix compiler warnings about missing cases in switch() and fix a deprecation warning.
Support for DECIMAL32 and DECIMAL64 should work on the read side, but not actually tested. The ogrlayerarrow.cpp generic code isn't ready for them yet.
No support on the write side to limit backwards compatibility issues.
> Add (minimum) support for libarrow 18.0.0

- ogr/ogrsf_frmts/arrow_common/ograrrowlayer.hpp
- ogr/ogrsf_frmts/arrow_common/ograrrowwriterlayer.hpp
- ogr/ogrsf_frmts/parquet/ogrparquetlayer.cpp
> [Backport release/3.10] Add (minimum) support for libarrow 18.0.0

- autotest/ogr/ogr_gpkg.py
- doc/source/drivers/vector/gpkg.rst
- doc/source/drivers/vector/sqlite.rst
- ogr/ogrsf_frmts/sqlite/ogrsqlitedatasource.cpp
unless the user specifies a value of this pragma through OGR_SQLITE_PRAGMA.
For example, Debian and Conda-Forge SQLite3 builds already turn on secure_delete. Make sure that this is done for all SQLite3 builds.
> SQLite/GPKG: turn on SQLite 'PRAGMA secure_delete=1' by default

- autotest/osr/osr_basic.py
- ogr/ogr_srs_api.h
- ogr/ogrspatialreference.cpp
- swig/include/osr.i
Refs https://github.com/rasterio/rasterio/pull/3206/files#r1813149328
> Add OSRGetAuthorityListFromDatabase() to get the list of CRS authorities used in the PROJ database.

- swig/python/osgeo/__init__.py
Fixes #11140
This changes the global warnings configuration, which is not appropriate to do inside a library.
> Python bindings: __init__.py: remove calls to warnings.simplefilter()

- autotest/ogr/ogr_gpkg.py
- doc/source/drivers/vector/gpkg.rst
- doc/source/drivers/vector/sqlite.rst
- ogr/ogrsf_frmts/sqlite/ogrsqlitedatasource.cpp
> [Backport release/3.10] SQLite/GPKG: turn on SQLite 'PRAGMA secure_delete=1' by default

- autotest/osr/osr_basic.py
- ogr/ogr_srs_api.h
- ogr/ogrspatialreference.cpp
- swig/include/osr.i
> [Backport release/3.10] Add OSRGetAuthorityListFromDatabase() to get the list of CRS authorities used in the PROJ database.

- swig/python/osgeo/__init__.py
> [Backport release/3.10] Python bindings: __init__.py: remove calls to warnings.simplefilter()

- .github/workflows/cmake_builds.yml
- swig/python/modify_cpp_files.cmake
> [Backport release/3.10] Python bindings: fix compatibility issue with SWIG 4.3.0 and PYTHONWARNINGS=error

- swig/include/csharp/gdal_csharp.i
Fixes #11032
This is the first time I have dealt with configuration SWIG, and I'm not a C++ expert, so there might be a better way of generating the bindings. I tried to take inspiration of how the other SWIG interface code was written.
It is intentional that the `vsi_l_offset` is mapped to "int" in C#, since the use case will in most cases probably be:
```csharp
IntPtr ptr = Gdal.GetMemFileBuffer(vsiPath, out int length, false);
byte[] buffer = new byte[length];
Marshal.Copy(ptr, buffer, 0, length);
```
And Marshal.Copy only supports int for buffer length. It seems like unsigned long and unsigned long long pointers are handled similarly in other parts of the binding code (casted to signed int), so hopefully this is OK.
> CSharp bindings: Add VSIGetMemFileBuffer bindings

- .github/workflows/cmake_builds.yml
- .github/workflows/ubuntu_24.04/Dockerfile.ci
- .pre-commit-config.yaml
- autotest/gcore/test_gdal_fsspec.py
- autotest/pymod/gdaltest.py
- doc/requirements.txt
- doc/source/api/python/general.rst
- doc/source/api/python/osgeo.gdal_fsspec.rst
- doc/source/api/python/osgeo.rst
- doc/source/spelling_wordlist.txt
- swig/include/cpl.i
- swig/include/python/gdal_python.i
- swig/python/CMakeLists.txt
- swig/python/osgeo/gdal_fsspec.py
This enables using GDAL virtual file systems with other libraries of the Python ecosystem that accept [fsspec](https://filesystem-spec.readthedocs.io/en/latest/) paths
"""Module exposing GDAL Virtual File Systems (VSI) as a "gdalvsi" fsspec implementation.
Importing "osgeo.gdal_fsspec" requires the Python "fsspec"
(https://filesystem-spec.readthedocs.io/en/latest/) module to be available.
A generic "gdalvsi" fsspec protocol is available. All GDAL VSI file names must be
simply prefixed with "gdalvsi://". For example:
- "gdalvsi://data/byte.tif" to access relative file "data/byte.tif"
- "gdalvsi:///home/user/byte.tif" to access absolute file "/home/user/byte.tif"
- "gdalvsi:///vsimem/byte.tif" (note the 3 slashes) to access VSIMem file "/vsimem/byte.tif"
- …
> Python bindings: add a osgeo.gdal_fsspec module that on import will register GDAL VSI file system handlers as fsspec AbstractFileSystem

- alg/gdalwarpkernel.cpp
- autotest/utilities/test_gdalwarp_lib.py
On extracted2.tif dataset from
https://github.com/OSGeo/gdal/issues/11042#issuecomment-2420556574 (12500 x 10000 pixels, 3 bands, Byte) ``gdalwarp -s_srs EPSG:8353 -t_srs EPSG:3857 -r cubic extracted2.tif tmp.tif -overwrite`` goes from 30.4 seconds to 26.0.
and  improve performance of Byte/UInt16 multi-band bicubic warping with XSCALE=1 and YSCALE=1 on SSE2 / x86_64
``gdalwarp -s_srs EPSG:8353 -t_srs EPSG:3857 -r cubic extracted2.tif tmp.tif -overwrite -wo XSCALE=1 -wo YSCALE=1`` goes from 19.0 seconds to 15.7.
> Warper: improve performance of multi-band bicubic warping

- apps/gdal_footprint_lib.cpp
- apps/gdal_rasterize_lib.cpp
- apps/gdaltindex_lib.cpp
- apps/gdalwarp_lib.cpp
- apps/ogr2ogr_lib.cpp
Removes usages of `add...Directly` methods in applications, preferring `unique_ptr` overloads instead.
#4371
> apps: use unique_ptr overloads of addGeometry, addRing

- apps/gdallocationinfo.cpp
- apps/gdaltransform.cpp
- apps/gdalwarp_lib.cpp
- frmts/grib/gribdataset.cpp
- port/cpl_conv.cpp
- port/cpl_conv.h
- port/cpl_error.cpp
- port/cpl_progress.cpp
Refreshed every tick (so 2.5%)
(only on interactive terminals. Tested with bash on Linux and cmd on Windows, but should work for all reasonable terminals)
```
Before 5 seconds:
0...10...20...
After 5 seconds:
0...10...20...30...40...50                           - estimated remaining time: 00:00:07
Upon completion:
0...10...20...30...40...50...60...70...80...90...100 - done in 00:00:13.
```
Fixes #11100
> GDALTermProgress: display estimated remaining time for tasks >= 10 seconds

- autotest/cpp/test_ogr.cpp
- ogr/ogr_feature.h
- ogr/ogrfeature.cpp
Adds `OGRFeature::SetGeometry(unique_ptr<OGRGeometry>)` and  `OGRFeature::SetGeomField(int, unique_ptr<OGRGeometry>)` 
https://github.com/OSGeo/gdal/issues/11146
> OGRFeature: Add SetGeometry overloads taking unique_ptr<OGRGeometry>

- doc/source/development/rfc/index.rst
- doc/source/development/rfc/rfc102_embedded_resources.rst
- doc/source/spelling_wordlist.txt
[Rendered view](https://gdal--10913.org.readthedocs.build/en/10913/development/rfc/rfc102_embedded_resources.html)
> Add RFC 102 text: Embedding resource files into libgdal

- doc/build_doc_snapshot.sh
- doc/source/conf.py
> Doc: fix issue with Unicode zero-width space character and PDF output

- autotest/ogr/ogr_gpkg.py
- ogr/ogrsf_frmts/gpkg/ogr_geopackage.h
- ogr/ogrsf_frmts/gpkg/ogrgeopackagedatasource.cpp
- ogr/ogrsf_frmts/gpkg/ogrgeopackagetablelayer.cpp
On a .gpkg of 1.6 GB with a table of 3.2 million features, this decreases the time from 1 minute to 12 seconds (with secure delete enabled, or 1 second with secure delete disabled)
> GPKG: optimize speed of 'DELETE FROM table_name', especially on ones with RTree

- autotest/gcore/tiff_write.py
- frmts/gtiff/geotiff.cpp
- frmts/gtiff/gtiffdataset_write.cpp
- frmts/gtiff/libtiff/tiff.h
- frmts/gtiff/tif_jxl.c
- frmts/gtiff/tif_jxl.h
DNG 1.7 JXL support tested with https://github.com/darktable-org/darktable/files/14973538/input.zip from https://github.com/darktable-org/darktable/issues/16618 with: ``gdal_translate GTIFF_DIR:off:135912:input.dng out.tif``
> TIFF JXL: add support for Float16 and Compression=52546 which is JPEG XL from DNG 1.7 specification

- .pre-commit-config.yaml
- doc/source/_static/announcement.css
- doc/source/_static/announcement.js
- doc/source/conf.py
displayed on top of all pages of the website (doesn't stick when scrolling down):
Preview: https://gdal--11178.org.readthedocs.build/en/11178/
> Doc: add a top-page banner advertizing the survey

- MIGRATION_GUIDE.TXT
- autotest/cpp/test_ogr_swq.cpp
- autotest/ogr/ogr_sql_test.py
- ogr/swq_expr_node.cpp
- ogr/swq_op_general.cpp
Fixes https://github.com/ropensci/osmextract/issues/298 (provided they     also fix their SQL expressions)
Given https://github.com/ropensci/osmextract/raw/master/inst/its-example.osm.pbf and https://raw.githubusercontent.com/ropensci/osmextract/refs/heads/master/inst/osmconf.ini, with the later one modified to add ``,access,bicycle,service`` at end of line 58 (attributes of the "lines" layer), the following request now returns 104 records, with both GDAL 3.9 and this PR, and with the OGR SQL dialect or the SQLite one:
```
ogrinfo -ro its-example.osm.pbf -sql "SELECT * FROM lines WHERE (highway IS NOT NULL)
AND
(highway NOT IN (
'abandoned', 'bus_guideway', 'byway', 'construction', 'corridor', 'elevator',
'fixme', 'escalator', 'gallop', 'historic', 'no', 'planned', 'platform',
'proposed', …
```
> OGR SQL: fix wrong handling of NULL expression in AND and NOT (3.10.0 regression) 

- MIGRATION_GUIDE.TXT
- autotest/cpp/test_ogr_swq.cpp
- autotest/ogr/ogr_sql_test.py
- ogr/swq_expr_node.cpp
- ogr/swq_op_general.cpp
> [Backport release/3.10] OGR SQL: fix wrong handling of NULL expression in AND and NOT (3.10.0 regression) 

- apps/gdalenhance.cpp
- autotest/utilities/test_gdalenhance.py
Resolves leaks in `gdalenhance`, as reported in #11159. In fact, the `gdalenhance` tests were never being run under the ASAN build configuration because the test invocation `gdalenhance --utility-version` leaked, which caused the test suite to determine that `gdalenhance` was unavailable and skip all tests.
Also adds some new tests to verify removal of leaks in other error situations.
#11159
> gdalenhance: fix memory leaks

- doc/source/community/index.rst
- doc/source/development/index.rst
- doc/source/development/rfc_process.rst
> Doc: add a page describing the RFC process step by step

- CMakeLists.txt
According to Craig Scott in https://discourse.cmake.org/t/is-there-any-reason-to-prefer-include-ctest-or-enable-testing-over-the-other/1905/2 , using include(CTest) adds unnecessary clutter that is only needed for dashboard submission. enable_testing() is enough otherwise
"Port" of https://github.com/OSGeo/shapelib/pull/162
> CMake: use enable_testing() instead of include(CTest)

- autotest/cpp/test_ogr.cpp
- ogr/ogr_geometry.h
- ogr/ogrgeometryfactory.cpp
Adds an overload of `OGRGeometry::createFromWkt` to more easily get a `unique_ptr<OGRGeometry>` from a WKT string. I don't know how others feel about the `std::pair` return in place of an "out" parameter. The diff in [autotest/cpp/test_ogr.cpp](https://github.com/OSGeo/gdal/compare/master...dbaston:gdal:ogrgf-fromwkt-return-unique#diff-ffa7db56afd816d72be86c8da3ea0e2c938a35b5e648ea49de5a7aa5b3efe2ff)[autotest/cpp/test_ogr.cpp](https://github.com/OSGeo/gdal/compare/master...dbaston:gdal:ogrgf-fromwkt-return-unique#diff-ffa7db56afd816d72be86c8da3ea0e2c938a35b5e648ea49de5a7aa5b3efe2ff) demonstrates the simplification nicely. 
Unfortunately this technique isn't generally applicable to methods currently returning a raw pointer. I'm not sure what the best pattern for addressing those is. Maybe …
> OGRGeometryFactory: Add createFromWkt overload returning unique_ptr

- .github/workflows/ubuntu_24.04/expected_ogrinfo_formats.txt
- .github/workflows/windows_conda_expected_ogrinfo_formats.txt
- autotest/ogr/ogr_aivector.py
- autotest/pyscripts/test_pct.py
- doc/source/drivers/vector/aivector.rst
- doc/source/drivers/vector/index.rst
- frmts/drivers.ini
- ogr/ogrsf_frmts/CMakeLists.txt
- ogr/ogrsf_frmts/aivector/CMakeLists.txt
- ogr/ogrsf_frmts/aivector/ograivectordriver.cpp
- ogr/ogrsf_frmts/generic/ogrregisterall.cpp
- ogr/ogrsf_frmts/ogrsf_frmts.h
With that latest breakthrough, OGR is finally feature complete.
> Add read-only AIVector (Artificial intelligence powered vector) driver

- autotest/gnm/gnm_test.py
A recent update of msys2 mingw (presumably Python 3.11 -> 3.12) causes the test_gnm_filenetwork_open() test to fail when run just after test_gnm_filenetwork_create(), presumably because the just created dataset has not been properly closed.
Cf https://github.com/OSGeo/gdal/actions/runs/11755814302/job/32752542561?pr=11224
> autotest: fix test failure with msys2 mingw64

- apps/argparse/argparse.hpp
- apps/gdalargumentparser.cpp
Now:
```
$ gdaldem TPI --help
Usage: gdaldem TPI [--help] [--long-usage] [--help-general]
[-of <output_format>] [-compute_edges] [-b <value>] [-co <NAME>=<VALUE>]... [--quiet]
input_dem output_TPI_map
Note: gdaldem TPI --long-usage for full help.
```
vs before:
```
$ gdaldem TPI --help
Usage: TPI [--help] [--long-usage] [--help-general]
[-of <output_format>] [-compute_edges] [-b <value>] [-co <NAME>=<VALUE>]... [--quiet]
input_dem output_TPI_map
Note: TPI --long-usage for full help.
```
argparse.hpp stream fix submitted to upstream in https://github.com/p-ranav/argparse/pull/382
> gdaldem: fix help message for subcommands

- apps/argparse/argparse.hpp
- apps/gdalargumentparser.cpp
> [Backport release/3.10] gdaldem: fix help message for subcommands

- autotest/cpp/CMakeLists.txt
- autotest/cpp/test_gdal.cpp
- autotest/cpp/test_gdal_minmax_element.cpp
- autotest/gcore/basic_test.py
- ci/travis/osx/script.sh
- doc/source/api/python_samples.rst
- gcore/CMakeLists.txt
- gcore/gdal.h
- gcore/gdal_minmax_element.hpp
- gcore/gdal_priv.h
- gcore/gdalrasterband.cpp
- perftests/CMakeLists.txt
- perftests/testperf_gdal_minmax_element.cpp
- swig/include/Band.i
- swig/include/python/gdal_python.i
- swig/python/gdal-utils/osgeo_utils/samples/gdal_minmax_location.py
and add a gdal_minmax_location.py script:
```
$ python ../swig/python/gdal-utils/osgeo_utils/samples/gdal_minmax_location.py byte.tif
Minimum=74.0 at (col,line)=(9,17), (X,Y)_georef=(441290.0,3750270.0), (long,lat)_WGS84=(-117.6358076,33.8929309)
Maximum=255.0 at (col,line)=(2,18), (X,Y)_georef=(440870.0,3750210.0), (long,lat)_WGS84=(-117.6403456,33.8923662)
```
(on top of PR #11199)
> Add GDALRasterComputeMinMaxLocation / GDALRasterBand::ComputeMinMaxLocation, and map it to SWIG

- autotest/cpp/CMakeLists.txt
- autotest/cpp/test_gdal_minmax_element.cpp
- ci/travis/osx/script.sh
- gcore/CMakeLists.txt
- gcore/gdal_minmax_element.hpp
- perftests/CMakeLists.txt
- perftests/testperf_gdal_minmax_element.cpp
Refs https://github.com/qgis/QGIS/pull/59285
NaN values are taken into account for float/double
Contains a SSE2 optimized version for int8/uint8/int16/uint16/int32/uint32/float/double in the no-nodata case (also taking into account NaN), which is about 10x times than std::min_element / std::max_element
Also add SSE2 optimization for uint8, int8, uint16, int16, uint32, int32, float and double nodata cases
<details>
<summary>
With gcc 9.4 (not so different with gcc 14.2.1, which is just slightly bit better for the "(nodata case, using std::min_element with nodata aware comparison)" cases for uint8/int8/uint16/int16, and significantly better for uint32/int32, but still behind our manual optimization ):
</summary>
```bash
$ (cd perftests && g++ -DGDAL_COMPILATION -std=c++17 -I../../port …
```
> Add gdal_minmax_element.hpp public header, that can also be vendored, to find the min/max elements in a buffer

- autotest/cpp/test_ogr.cpp
- ogr/ogr_geometry.h
- ogr/ogrcurvecollection.cpp
- ogr/ogrgeometry.cpp
- ogr/ogrgeometrycollection.cpp
- ogr/ogrlinestring.cpp
- scripts/cppcheck.sh
as suggested by performance warnings of Coverity Scan
> OGRGeometry classes: implement move constructor and move assignment operator

- docker/ubuntu-full/bh-gdal.sh
- docker/ubuntu-small/Dockerfile
This reduces the size of the small Ubuntu
image by 4 MB. There also seems to be
a slight speedup, the user time for the example
from #10809 goes from 34.x seconds to
33.x seconds on my computer.
> docker: enable IPO

- swig/csharp/CMakeLists.txt
that no longer accept invalid PRE_BUILD keyword in OUTPUT form of add_custom_command() per https://cmake.org/cmake/help/latest/policy/CMP0175.html
Should fix error of https://github.com/OSGeo/gdal/actions/runs/11805369849/job/32887659405?pr=11254
> CMake: fix swig/csharp/CMakeLists.txt compatibility with CMake 3.31

- gcore/rasterio.cpp
- swig/csharp/CMakeLists.txt
Technically it is safer to cast a pointer to uintptr_t than our custom type. At least, it better documents the intent. In practice, I doubt this changes much.
CC @schwehr  w.r.t #11253 . Very low chance that it fixes your issue
> GDALCopyWords64(): tidy code

- alg/gdal_interpolateatpoint.cpp
- autotest/cpp/CMakeLists.txt
- autotest/cpp/test_gdal_vectorx.cpp
- gcore/gdal_vectorx.h
During my work on the file `alg/gdal_interpolateatpoint.cpp`, I saw that there was a repetitive pattern: doing everything on X and Y. Both as integer to manage the pixel, and as double to use the coordinates in the image.
I missed a functionality where x,y (or even x,y,z) could be used as an object, and do some basic operations on that, like subtract another point, multiply by a factor, etc. Something I am used to with Eigen library.
Once that development was finished I tried something, to see if it makes sense. This is it.
The main feature is the template class `VectorX`. Both the size and type are templated. You can make it double, int, even complex<double>. Size can be any, but I think the most common would be 2, maybe 3. Four predefined types are included: `Vector2i`, `Vector3i`, …
> gdal::VectorX Prototype

- .github/workflows/ubuntu_24.04/Dockerfile.ci
This reverts commit 33d2b37943b836b1e86edde793fc5d48fbf0fae7.
http://cfconventions.org/Data/standardized-region-list/standardized-region-list.xml has been restored per https://github.com/cf-convention/cf-convention.github.io/issues/555
Fixes #11256
> Revert "CI: disable cfchecker based tests"

- autotest/cpp/test_gdal.cpp
- autotest/gcore/rasterio.py
- autotest/gcore/vrtmisc.py
- autotest/gdrivers/mem.py
- autotest/gdrivers/vrtwarp.py
- frmts/mem/memdataset.cpp
- frmts/vrt/vrtdataset.cpp
- frmts/vrt/vrtwarped.cpp
- gcore/gdaldataset.cpp
- gcore/gdaldriver.cpp
- gcore/gdalmultidim.cpp
- gcore/gdalrasterband.cpp
- gcore/rasterio.cpp
- port/cpl_port.h
in:
- GDALCopyWords[64]
- GDALRasterBand/GDALDataset::RasterIO
- GDALDataset::AddBand: MEM and VRT implementations
- GDALDriver::Create()
Fixes #11257
> Raster API: error out on GDT_Unknown/GDT_TypeCount

- autotest/utilities/test_gdal_translate_lib.py
- swig/include/python/gdal_python.i
and fixes a copy&paste issue in the similar argument of gdal.TileIndex()
Refs https://github.com/OSGeo/gdal/issues/11231#issuecomment-2469443347
> Python bindings: add a colorInterpretation argument to gdal.Translate()

- doc/source/programs/ogr2ogr.rst
Backport #11278
**Authored by:** @phidrho
> [Backport release/3.10] Update ogr2ogr.rst - missing filename option

- cmake/helpers/GdalCompilationFlags.cmake
Fixes #11286
@andrew-aitchison Can you confirm it fixes your issue?
> CMake: use add_compile_options() instead of setting CMAKE_CXX_FLAGS for -fno-finite-math-only

- cmake/helpers/GdalCompilationFlags.cmake
> [Backport release/3.10] CMake: use add_compile_options() instead of setting CMAKE_CXX_FLAGS for -fno-finite-math-only

- frmts/avif/avifdataset.cpp
Fixes a typo in the error message associated with a bad band count.
N/A.
- [N/A] Add documentation
- [N/A] Updated Python API documentation (swig/include/python/docs/)
N/A.
> avif: typo fix

- apps/ogr2ogr_lib.cpp
- autotest/ogr/ogr_parquet.py
Since 3.10.0, reprojecting from GPKG/FlatGeoBuf/Parquet uses the Arrow optimized code path. But the way we dealt with a temporary array was incorrect when writing to Parquet/Arrow ...
Workaround: add ``--config OGR2OGR_USE_ARROW_API=NO``
> ogr2ogr: fix 'ogr2ogr out.parquet in.gpkg/fgb/parquet -t_srs {srs_def}' optimized code path (3.10.0 regression)

- autotest/ogr/ogr_gpkg.py
- ogr/ogrsf_frmts/gpkg/ogrgeopackagedatasource.cpp
Fixes #11282, which is due to a9745e5f8df that mapped CopyDataSource() onto CreateCopy(), but the GPKG driver implementation of CreateCopy() wasn't ready to deal with vector dataset.
> GPKG: make CreateCopy() work on vector datasets

- autotest/ogr/ogr_dxf.py
- ogr/ogrsf_frmts/dxf/ogr_dxf.h
- ogr/ogrsf_frmts/dxf/ogrdxfwriterds.cpp
- ogr/ogrsf_frmts/dxf/ogrdxfwriterlayer.cpp
as it is apparently a reserved value.
Fixes #11299
> DXF writer: do not set 0 as the value for DXF code 5 (HANDLE)

- apps/gdal_translate_bin.cpp
- apps/gdalinfo_bin.cpp
> [Backport release/3.10] gdalinfo: fix bound checking for value of -sds argument

- swig/include/java/gdal_java.i
- swig/include/java/typemaps_java.i
- swig/java/apps/GDALTestIO.java
- swig/java/javadoc.java
> Java bindings: add byte[] org.gdal.gdal.GetMemFileBuffer(String filename)

- autotest/ogr/ogr_gpkg.py
- ogr/ogrsf_frmts/gpkg/ogrgeopackagetablelayer.cpp
> GPKG: make sure gpkg_ogr_contents.feature_count = 0 on a newly created empty table

- swig/java/build_java_doc.cmake
- swig/java/make_doc.sh
Cf https://lists.osgeo.org/pipermail/gdal-dev/2024-November/059815.html
> Java bindings: remove useless -link when invoking javadoc

- cmake/helpers/GdalVersion.cmake
As noted in #11315 as a side note, I wondered why we are getting as `${GDAL_VERSION}` `3.10.0dev` and not just `3.10.0` when checking out a release tag via:
```
git clone --depth 1 --branch v3.10.0 https://github.com/OSGeo/gdal.git .
```
Reason is, that the suffix `dev` will be always added when the `.git` directory is present even the `GDAL_RELEASE_NAME` (within `gdal_version.h.in`) doesn't contain it anymore. Therefore I added a logic to parse the git tags.
Results (from CMake output) when switching between different tags or current `master`:
- `master`:
```
-- GDAL_VERSION          = 3.11.0dev
-- GDAL_ABI_FULL_VERSION = 311
```
- Tag `3.10.0`
```
-- GDAL_VERSION          = 3.10.0
-- GDAL_ABI_FULL_VERSION = 310
```
- Tag `3.10.0RC3` (same Git revision as the release version)
```
-- …
```
> Set GDAL_DEV_SUFFIX to the pre-release suffix if a corresponding Git tag was found

- autotest/ogr/ogr_gpkg.py
- ogr/ogrsf_frmts/gpkg/ogrgeopackagetablelayer.cpp
> [Backport release/3.10] GPKG: make sure gpkg_ogr_contents.feature_count = 0 on a newly created empty table

- cmake/helpers/GdalVersion.cmake
Backport #11335
**Authored by:** @SunBlack
> [Backport release/3.10] Set GDAL_DEV_SUFFIX to the pre-release suffix if a corresponding Git tag was found

- apps/ogr2ogr_lib.cpp
- autotest/cpp/CMakeLists.txt
- autotest/cpp/test_ogr.cpp
- autotest/ogr/ogr_adbc.py
- autotest/ogr/ogr_flatgeobuf.py
- autotest/ogr/ogr_gpkg.py
- autotest/ogr/ogr_mem.py
- autotest/ogr/ogr_parquet.py
- autotest/utilities/test_ogr2ogr_lib.py
- ogr/ogrsf_frmts/adbc/ogradbclayer.cpp
- ogr/ogrsf_frmts/arrow_common/ograrrowlayer.hpp
- ogr/ogrsf_frmts/flatgeobuf/ogrflatgeobuflayer.cpp
- ogr/ogrsf_frmts/generic/ograrrowarrayhelper.cpp
- ogr/ogrsf_frmts/generic/ogrlayerarrow.cpp
- ogr/ogrsf_frmts/generic/ogrlayerarrow.h
- ogr/ogrsf_frmts/gpkg/ogr_geopackage.h
- ogr/ogrsf_frmts/gpkg/ogrgeopackagelayer.cpp
- ogr/ogrsf_frmts/gpkg/ogrgeopackagetablelayer.cpp
* GetArrowStream(): add DATETIME_AS_STRING=YES/NO. Defaults to NO. Added in GDAL 3.11. Whether DateTime fields should be returned as a (normally ISO-8601 formatted) string by drivers. The aim is to be able to handle mixed timezones (or timezone naive values) in the same column. All drivers must honour that option, and potentially fallback to the OGRLayer generic implementation if they cannot (which is the case for the Arrow, Parquet and ADBC drivers).
When DATETIME_AS_STRING=YES, the TIMEZONE option is ignored.
Fixes https://github.com/geopandas/pyogrio/issues/487
* OGRLayer::GetArrowStream(): when DATETIME_AS_STRING=YES, expose "GDAL:OGR:type":"DateTime" metadata in the ArrowSchema of DateTime fields
* CreateFieldFromArrowSchema(): take into account GDAL:OGR:Type=DataTime when …
> OGRLayer::GetArrowStream(): add a DATETIME_AS_STRING=YES/NO option

- .github/workflows/benchmarks/test.sh
- alg/CMakeLists.txt
- alg/gdal_rpc.cpp
- alg/gdaldither.cpp
- alg/gdalgrid.cpp
- alg/gdalgridsse.cpp
- alg/gdalpansharpen.cpp
- alg/gdalwarpkernel.cpp
- ci/travis/osx/script.sh
- frmts/gti/CMakeLists.txt
- frmts/gti/gdaltileindexdataset.cpp
- frmts/png/CMakeLists.txt
- frmts/png/filter_sse2_intrinsics.c
- frmts/png/pngdataset.cpp
- frmts/png/pngdataset.h
- gcore/gdal_minmax_element.hpp
- gcore/gdal_priv_templates.hpp
- gcore/gdalsse_priv.h
- gcore/overview.cpp
(on top of https://github.com/OSGeo/gdal/pull/11237)
Comparing https://github.com/OSGeo/gdal/actions/runs/11766759419/job/32774680289?pr=11237 (before) and https://github.com/rouault/gdal/actions/runs/11766932147/job/32775064275 (this PR), shows on Apple Silicon:
before:
```
Name (time in us)                                                             Min                       Max                      Mean                 StdDev                    Median                     IQR            Outliers          OPS            Rounds  Iterations
test_gdalwarp[cubic-1]                                             1,393,559.0000 (>1000.0)  1,408,203.0000 (>1000.0)  1,402,279.4000 (>1000.0)   5,568.3731 (753.32)   1,402,622.0000 (>1000.0)    6,975.2500 (>1000.0)       2;0       0.7131 (0.00) …
```
> Use SSE2 optimizations on ARM Neon for warping, pansharpening, gridding, dithering, RPC, PNG, GTI

- autotest/gdrivers/exr.py
- frmts/exr/exrdataset.cpp
The update of OpenEXR in alpine:edge from 3.1.13-r2 (https://github.com/OSGeo/gdal/actions/runs/11960737896/job/33345432787) to 3.3.2-r0
(https://github.com/OSGeo/gdal/actions/runs/12000822356/job/33450446198) causes multiple tests to crash when reading pixels. This is apparently linked to tiled files.
```
$ valgrind apps/gdallocationinfo temp.exr 0 0
Report:
Location: (0P,0L)
Band 1:
==96901== Invalid write of size 8
==96901==    at 0x11A9E833: ??? (in /usr/lib/libOpenEXRCore-3_3.so.32.3.3.2)
==96901==    by 0x11A9EFEC: ??? (in /usr/lib/libOpenEXRCore-3_3.so.32.3.3.2)
==96901==    by 0x11AA728A: exr_decoding_run (in /usr/lib/libOpenEXRCore-3_3.so.32.3.3.2)
==96901==    by 0xA2F275E: ??? (in /usr/lib/libOpenEXR-3_3.so.32.3.3.2)
==96901==    by 0xA2EFBFF: …
```
> tests: skip tests that crash with OpenEXR 3.3.2

- frmts/pcraster/libcsf/attrsize.c
- frmts/pcraster/libcsf/csfimpl.h
- frmts/pcraster/libcsf/delattr.c
- frmts/pcraster/libcsf/gattrblk.c
- frmts/pcraster/libcsf/getattr.c
Coverity Scan has false positives about calls to CsfGetAttrIndex() that might return NR_ATTR_IN_BLOCK whereas they can not. Adding a CsfGetAttrBlockAndIdx() function that returns both the block and index should make it happy.
@kordejong can you double check that?
> libcsf: address (false positive) Coverity warnings

- autotest/ogr/ogr_parquet.py
- port/cpl_vsil_curl.cpp
- port/cpl_vsil_curl_class.h
> /vsicurl/: fix to allow to read Parquet partitionned datasets from public Azure container using /vsicurl/

- autotest/postinstall/test_cpp/test_cpp.cpp
- gdal.cmake
- ogr/ogr_api.h
- ogr/ogr_feature.h
- ogr/ogr_geometry.h
- ogr/ogr_srs_api.h
- ogr/ograpispy.h
- port/cpl_error.h
Fixes #11311
@SunBlack can you give this a try?
> CMake: export -DGDAL_DEBUG as PUBLIC for debug builds

- alg/contour.cpp
- autotest/alg/contour.py
Fixes 3.10.0 regression
Fixes #11340
> GDALContourGenerateEx(): return CE_None even if the raster is at constant value

- ogr/ogr_api.h
- ogr/ogr_feature.h
- ogr/ogrsf_frmts/ogrsf_frmts.dox
- port/cpl_conv.cpp
- port/cpl_csv.cpp
- port/cpl_error.cpp
- port/cpl_path.cpp
- port/cpl_vsil_curl.cpp
> [Backport release/3.10] Doxygen docs: use \code instead of <pre>

- autotest/ogr/ogr_parquet.py
- port/cpl_vsil_curl.cpp
- port/cpl_vsil_curl_class.h
> [Backport release/3.10] /vsicurl/: fix to allow to read Parquet partitionned datasets from public Azure container using /vsicurl/

- alg/contour.cpp
- autotest/alg/contour.py
> [Backport release/3.10] GDALContourGenerateEx(): return CE_None even if the raster is at constant value

- apps/ogr2ogr_lib.cpp
- autotest/ogr/ogr_oci.py
- doc/source/drivers/vector/oci.rst
- ogr/ogrsf_frmts/oci/ogr_oci.h
- ogr/ogrsf_frmts/oci/ogrocidrivercore.cpp
- ogr/ogrsf_frmts/oci/ogrocisession.cpp
- ogr/ogrsf_frmts/oci/ogrocitablelayer.cpp
- ogr/ogrsf_frmts/oci/ogrociwritablelayer.cpp
> [Backport release/3.10] OCI: add a TIMESTAMP_WITH_TIME_ZONE layer creation option, and ogr2ogr tweaks

- gcore/gdaldrivermanager.cpp
Fixes #11332
In GDALPluginDriverProxy::GetRealDriver(), return a nullptr if GDAL_NO_AUTOLOAD is set and plugins are not available. This avoids the call the CPLGetSymbol.
In custom builds like my bazel build, this lets me completely remove `CPLGetSymbol` from the build. When GDAL runs in a sandbox, it is helpful to not even have a chance for this function to run. Any call to CPLGetSymbol would cause the sandbox to trigger a violation and kill the work.
#11332
* OS: Custom linux with bazel build
* Compiler: llvm
**Note**: Failure that I can't tell if it's related to the change I made. The most recent commits on head fail too, but it's luck on which one.
```
Executing transaction: ...working... done
+ test -f …
```
> gdaldrivermanager.cpp: Do not look for plugins in GetRealDriver when GDAL_NO_AUTOLOAD set.

- autotest/ogr/ogr_dxf.py
- ogr/ogrsf_frmts/dxf/ogr_dxf.h
- ogr/ogrsf_frmts/dxf/ogrdxfwriterds.cpp
- ogr/ogrsf_frmts/dxf/ogrdxfwriterlayer.cpp
as it is apparently a reserved value.
Fixes #11299
Backport of PR #11304
> [Backport 3.10] DXF writer: do not set 0 as the value for DXF code 5 (HANDLE)

- autotest/gdrivers/data/wmts/WMTSCapabilities_THEMIS_NightIR_ControlledMosaics_100m_v2_oct2018.xml
- autotest/gdrivers/wmts.py
- autotest/osr/osr_epsg.py
- frmts/http/httpdriver.cpp
- frmts/wmts/wmtsdataset.cpp
- ogr/ogrspatialreference.cpp
Fixes #11387
- OGRSpatialReference::importFromEPSG(): tries with ESRI when it looks like an ESRI code, but with a warning when that succeeds
- WMTS: for geographic CRS with official lat,lon order, be robust to bounding box and TopLeftCorner being in the wrong axis order and emits a warning
- HTTP driver: re-emit warnings/errors raised by underlying driver
> Assorted set of fixes for WMTS issue

- autotest/ogr/ogr_pg.py
- ogr/ogrsf_frmts/pg/ogrpgdatasource.cpp
Fixes #11386
Continuation of fix of ab40f2d954c77fc937a8ff4e4c5481b6502e1f8e / PR #10980 that was incomplete
> PG: avoid error when the original search_path contains something like '"", something_else'

- autotest/gdrivers/netcdf_multidim.py
- frmts/netcdf/netcdfmultidim.cpp
In the same vain as https://github.com/OSGeo/gdal/pull/11381
> netCDF multidim: report correct axis order when reading SRS with EPSG geographic CRS + geoid model

- apps/gdalwarp_lib.cpp
- autotest/gcore/cog.py
- autotest/gcore/tiff_write.py
- frmts/gtiff/gtiffdataset_write.cpp
- frmts/gtiff/gtiffrasterband.cpp
> GTiff/gdalwarp/COG: preserve pre-multiplied alpha information from source TIFF

- autotest/gdrivers/avif.py
- autotest/gdrivers/avif_heif.py
- autotest/gdrivers/heif.py
- frmts/heif/heifdataset.cpp
- frmts/heif/heifdataset.h
- gcore/geoheif.cpp
Fixes an axis-ordering bug in GeoHEIF driver, in particular for EPSG:4326 CRS.
https://gitlab.ogc.org/ogc/T20-GIMI/-/issues/59
- [N/A] Add documentation
- [N/A] Updated Python API documentation (swig/include/python/docs/)
N/A
> GeoHEIF: Fixed respecting CRS axis order (e.g., for EPSG:4326)

- autotest/gdrivers/avif.py
- autotest/gdrivers/avif_heif.py
- autotest/gdrivers/heif.py
- frmts/heif/heifdataset.cpp
- frmts/heif/heifdataset.h
- gcore/geoheif.cpp
Modifies the HEIF part of the GeoHEIF parsing to extract properties in Init(). It also reduces the amount of code by collecting all the properties at once (and only once), which should offset the cost of getting properties where we have no geospatial context.
It also removes a bit of debug output from the avif_heif.py test that is not needed.
It also removes some unused code (ExtractUserDescription) from the HEIF driver that should have been removed before merging.
This is related to #11384 in that it addresses the problem where the order of operations makes a difference to the outcome. It doesn't address the part of #11384 that fixes the axis order though.
@jerstlouis Can you check that part?
- [N/A] Add documentation
- [N/A] Updated Python API documentation (swig/include/python/docs/) …
> heif: geoheif properties cleanup

- autotest/gdrivers/data/wmts/WMTSCapabilities_THEMIS_NightIR_ControlledMosaics_100m_v2_oct2018.xml
- autotest/gdrivers/wmts.py
- autotest/osr/osr_epsg.py
- frmts/http/httpdriver.cpp
- frmts/wmts/wmtsdataset.cpp
- ogr/ogrspatialreference.cpp
> [Backport release/3.10] Assorted set of fixes for WMTS issue

- doc/source/development/cmake.rst
Closes #11315 as all other improvements should be implemented on the CMake side.
Is there any Job within the workflow, where I can see the preview of the doc, as I locally don't have Sphinx installed?
> Add a hint in the documentation, that the configuration file was created with SameMinorVersion.

- ogr/ogr_geometry.h
- ogr/ogrlibjsonutils.cpp
- ogr/ogrsf_frmts/gml/ogr_gml.h
- ogr/ogrsf_frmts/gml/ogrgmldatasource.cpp
- ogr/ogrutils.cpp
Related to https://lists.osgeo.org/pipermail/gdal-dev/2024-November/059853.html
Before:
```
$ time ogr2ogr -f "mapinfo file" lakes.mif Jarvi10.shp -progress -limit 30000
real    0m7,983s
$ time ogr2ogr -f csv lakes.csv Jarvi10.shp -progress -limit 30000  -lco geometry=as_wkt
real    0m10,311s
$ time ogr2ogr -f gml lakes.gml Jarvi10.shp -progress -limit 30000
real    0m14,525s
$ time ogr2ogr -f geojson lakes.json Jarvi10.shp -progress -limit 30000
real    0m19,116s
```
After:
```
$ time ogr2ogr -f gml lakes.gml Jarvi10.shp -progress -limit 30000
real    0m12,706s
$ time ogr2ogr -f geojson lakes.json Jarvi10.shp -progress -limit 30000
real    0m15,565s
```
> Speed optimizations for GML and GeoJSON writing

- autotest/gdrivers/data/vrt/arraysource_array_constant.vrt
- autotest/gdrivers/vrtmultidim.py
- frmts/vrt/data/gdalvrt.xsd
> [Backport release/3.10] gdalvrt.xsd: fix schema to reflect that <Array> can be a child of <ArraySource>

- apps/ogr2ogr_lib.cpp
- autotest/utilities/test_ogr2ogr_lib.py
- ogr/ogrgeometryfactory.cpp
Fixes #11438
Passing "--config OGR2OGR_USE_ARROW_API=NO" or "-t_srs {srs_def}" can be used as a workaround
> ogr2ogr: fix crash with -ct and using Arrow code path (e.g source is GeoPackage) (3.10.0 regression)

- autotest/ogr/ogr_flatgeobuf.py
- ogr/ogrsf_frmts/flatgeobuf/ogrflatgeobuflayer.cpp
- this fixes the crash when writing an empty polygon. Fixes #11419
- this avoids a reading error when writing an empty line
@bjornharrtell Can you confirm that FlatGeobuf is not a fan of EMPTY geometries ?
> FlatGeobuf writing: in SPATIAL_INDEX=NO mode, deal with empty geometries as if there were null

- apps/ogr2ogr_lib.cpp
- autotest/utilities/test_ogr2ogr_lib.py
- ogr/ogrgeometryfactory.cpp
> [Backport release/3.10] ogr2ogr: fix crash with -ct and using Arrow code path (e.g source is GeoPackage) (3.10.0 regression)

- frmts/kea/keacopy.cpp
Changes the chunksize used for copying the RAT to be the default native HDF5 chunksize (10000) rather and 1000. This should improve performance while copying to a KEA file.
https://github.com/ubarsc/kealib/pull/68
* OS:
* Compiler:
> KEA: use native chunksize for copying RAT

- frmts/kea/keacopy.cpp
Backport #11443
**Authored by:** @gillins
> [Backport release/3.10] KEA: use native chunksize for copying RAT

- apps/ogrinfo_lib.cpp
Fix wrong command line help text for the "summary only" option and add points at the end of some help texts for making them consistent.
> Ogrinfo: command line help text fixes

- gcore/gdalrasterblock.cpp
> [Backport release/3.10] GDALRasterBlock: make sure mutex is initialize in repeated calls to GDALAllRegister / GDALDestroyDriverManager

- autotest/cpp/test_cpl.cpp
- autotest/ogr/ogr_shape.py
- port/cpl_path.cpp
> [Backport release/3.10] CPLGetPath()/CPLGetDirname(): make them work with /vsicurl? and URL encoded

- doc/source/programs/gdalbuildvrt.rst
Adds a note about the default value of cells not covered by a source (to `-te`) and does some general cleanup/formatting.
> Doc: Updates to gdalbuiltvrt docs

- autotest/gdrivers/tiledb_write.py
- frmts/tiledb/tiledbdense.cpp
Hopefully this solves compatibility issues and resolves #11485 for all recent TileDB versions.
In TileDB 2.27.0, `delete_array()` and `delete_group()` will clean up the parent directory when they can. I suspect the test fails because the driver code tries to delete a directory that has already been removed.
> Remove dir only if it exists

- autotest/gcore/vsicurl.py
- doc/source/user/virtual_file_systems.rst
- port/cpl_known_config_options.h
- port/cpl_vsil_curl.cpp
- port/cpl_vsil_curl_class.h
This can for example be used when managing Shared Access Signatures (SAS) on application side, and not wanting to include the signature as part of the filename propagated through GDAL.
> /vsicurl/: add a VSICURL_QUERY_STRING path specific option

- autotest/ogr/ogr_gml.py
- ogr/ogrsf_frmts/gmlutils/gmlutils.cpp
> [Backport release/3.10] GML: honour SWAP_COORDINATES=YES even when the geometry has no SRS

- autotest/ogr/ogr_pg.py
- doc/source/drivers/vector/pg.rst
- ogr/ogrsf_frmts/pg/ogrpgdatasource.cpp
Fixes #11486
(not appropriate for backport)
> PG: add escaping syntax for TABLES open option to allow table names with open parenthesis

- alg/gdalrasterize.cpp
- autotest/alg/rasterize.py
Related to https://lists.osgeo.org/pipermail/gdal-dev/2024-December/059948.html
> GDALRasterizeLayers(): do not emit warning about missing SRS if the target raster dataset has no SRS

- doc/source/development/rfc/index.rst
- doc/source/development/rfc/rfc103_schema_open_option.rst
Formatted preview: https://gdal--11071.org.readthedocs.build/en/11071/development/rfc/rfc103_schema_open_option.html
> [rfc] Add RFC 103 - OGR_SCHEMA open option

- autotest/ogr/ogr_gpkg.py
- ogr/ogrsf_frmts/gpkg/ogrgeopackagetablelayer.cpp
> [Backport release/3.10] GPKG: fix FID vs field of same name consistency check when field is not set

- autotest/ogr/data/vrt/invalid.vrt
- autotest/ogr/ogr_vrt.py
- doc/source/drivers/vector/vrt.rst
- ogr/ogrsf_frmts/vrt/ogr_vrt.h
- ogr/ogrsf_frmts/vrt/ogrvrtlayer.cpp
> OGR VRT: accept SrcRegion value to be any geometry type as well as SetSpatialFilter()

- autotest/ogr/data/vrt/invalid.vrt
- autotest/ogr/ogr_vrt.py
- doc/source/drivers/vector/vrt.rst
- ogr/ogrsf_frmts/vrt/ogr_vrt.h
- ogr/ogrsf_frmts/vrt/ogrvrtlayer.cpp
> [Backport release/3.10] OGR VRT: accept SrcRegion value to be any geometry type as well as SetSpatialFilter()

- autotest/ogr/ogr_vrt.py
- ogr/ogrsf_frmts/vrt/ogrvrtlayer.cpp
> [Backport release/3.10] OGR VRT: fix SrcRegion.clip at OGRVRTLayer level

- port/cpl_vsil_win32.cpp
Workaround issue of https://github.com/msys2/MINGW-packages/pull/22907#issuecomment-2564743982
> cpl_vsil_win32.cpp: no longer test for __MSVCRT_VERSION__ >= 0x0601 assuming this is always available given how antiquated this is

- autotest/gcore/tiff_read.py
- frmts/gtiff/gtiffdataset.h
- frmts/gtiff/gtiffdataset_read.cpp
- frmts/gtiff/gtiffdataset_write.cpp
- frmts/gtiff/gtiffrasterband_read.cpp
- frmts/gtiff/gtiffrgbaband.cpp
> GTiff: more robust handling of I/O errors in network optimized code paths

- apps/gdaladdo.cpp
- autotest/gcore/tiff_ovr.py
- autotest/utilities/test_gdaladdo.py
- gcore/gdaldataset.cpp
> [Backport release/3.10] gdaladdo / GDALDataset::BuildOverviews(): validate values of decimation factors

- frmts/vrt/vrtprocesseddataset.cpp
Prevent a null pointer dereference when handling the builtin arguments `scale_{band}` and `offset_{band}`. As far as I can tell, these lines are never hit by GDAL proper, so the problem would only arise with a user-defined processed dataset function.
> [Backport 3.10] VRT processed dataset: Read scale and offset from src dataset

- frmts/vrt/vrtprocesseddataset.cpp
- gcore/gdalmultidim.cpp
- gcore/gdalmultidim_gltorthorectification.cpp
- gcore/gdalnodatamaskband.cpp
- gcore/gdalrasterband.cpp
- gcore/overview.cpp
- gcore/rasterio.cpp
- gcore/rawdataset.cpp
and also: gcore: use GDALCopyWords64() instead of GDALCopyWords() for microscopic perf improvement
> VRTProcessedDataset: reduce block size when amount of RAM for temp buffers would be too large

- autotest/gcore/multidim.py
- gcore/gdalmultidim.cpp
Add a BAND_IMAGERY_METADATA options to papszOptions:
JSON serialized object defining which arrays of the poRootGroup, indexed by non-X and Y dimensions,
should be mapped as band metadata items in the
band IMAGERY domain.
The object currently accepts 2 members:
- "CENTRAL_WAVELENGTH_UM": Central Wavelength in micrometers.
- "FWHM_UM": Full-width half-maximum in micrometers.
The value of each member should be an object with the following members:
- "array": (required) full name of a band parameter array. Such array must be a one dimensional array, and its dimension must be one of the dimensions of the array on which the method is called (excluding the X and Y dimensons).
- "unit": (optional) unit of the values pointed in the above array. Can be a literal string or a string of the form …
> GDALMDArray::AsClassicDataset(): allow to set band IMAGERY metadata domain

- autotest/gcore/gcps2geotransform.py
Corrected the Python signature of gdal.GCPsToGeoTransform and updated test cases to reflect accurate parameter usage and expected results.
> 11259: Fix GDALGCPsToGeoTransform documentation and usage in tests

- doc/source/drivers/raster/gtiff.rst
GTiff: docs fix bad link for geo_metadata tiff tag
> update reference since link is no longer available

- autotest/ogr/ogr_gml_geom.py
- ogr/gml2ogrgeometry.cpp
> gml:CircleByCenterPoint: correctly take into account radius.uom for projected CRS

- autotest/ogr/ogr_gml_geom.py
- ogr/gml2ogrgeometry.cpp
> [Backport 3.10] gml:CircleByCenterPoint: correctly take into account radius.uom for projected CRS

- autotest/postinstall/test_cpp/test_cpp.cpp
- gdal.cmake
- ogr/ogr_api.h
- ogr/ogr_feature.h
- ogr/ogr_geometry.h
- ogr/ogr_srs_api.h
- ogr/ograpispy.h
- port/cpl_error.h
This reverts commit d0dcf04a2685cb00cbe8a6a7983a543a1860dbd8.
This reverts PR #11363, which is probably inappropriate for the stable branch, given issue reported in https://lists.osgeo.org/pipermail/gdal-dev/2025-January/060023.html
> [3.10] Revert "CMake: Export -DGDAL_DEBUG as PUBLIC for debug builds"

- autotest/gcore/vrt_read.py
- frmts/vrt/vrtsourcedrasterband.cpp
Unfortunately, we have to give up using source overviews and basically apply the VRT at its full resolution before doing the resampling.
> VRT: avoid artifacts on source boundaries when the VRT has an alpha or mask band, and non-nearest neighbour resampling is involved

- alg/gdalwarpkernel.cpp
- apps/ogr2ogr_lib.cpp
- autotest/cpp/test_ogr.cpp
- frmts/aigrid/gridlib.c
- frmts/bsb/bsb_read.c
- frmts/gtiff/geotiff.cpp
- frmts/hfa/hfaband.cpp
- frmts/vrt/vrtsources.cpp
- gcore/gdalrasterblock.cpp
- ogr/gml2ogrgeometry.cpp
- ogr/ogr_geometry.h
- ogr/ogrct.cpp
- ogr/ogrgeojsonwriter.cpp
- ogr/ogrgeometryfactory.cpp
- ogr/ogrpgeogeometry.cpp
- ogr/ogrsf_frmts/dwg/ogrdgnv8layer.cpp
- ogr/ogrsf_frmts/elastic/ogrelasticlayer.cpp
- ogr/ogrsf_frmts/filegdb/FGdbLayer.cpp
- ogr/ogrsf_frmts/gmlas/ogrgmlasxsdcache.cpp
- ogr/ogrsf_frmts/ili/ogrili1datasource.cpp
- ogr/ogrsf_frmts/ili/ogrili1layer.cpp
- ogr/ogrsf_frmts/parquet/ogrparquetwriterlayer.cpp
- ogr/ogrspatialreference.cpp
- port/cpl_error.h
- port/cpl_known_config_options.h
to emit an error/debug message only once during the life-time of a process.
> Add CPLErrorOnce() and CPLDebugOnce()

- autotest/cpp/test_gdal.cpp
- frmts/gtiff/gtiffoddbitsband.cpp
- frmts/libertiff/libertiffdataset.cpp
- gcore/gdal_priv.h
- gcore/rasterio.cpp
and use them in GTiff and LIBERTIFF drivers
> Add GDALExpandPackedBitsToByteAt0Or255() and GDALExpandPackedBitsToByteAt0Or1()

- cmake/helpers/GdalCAndCXXStandards.cmake
Something about my configuration was causing the following complaint
> CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS-NOTFOUND 
Some searching showed https://discourse.cmake.org/t/cmake-3-28-cmake-cxx-compiler-clang-scan-deps-notfound-not-found/9244/3 
My configuration didn't have `clang-tools` installed, so I didn't have `clang-scan-deps` available. I shouldn't have *needed* it, but I don't understand why our CMake configuration thinks it does.
This PR tells CMake that it doesn't need it. When we upgrade to C++20 modules 😄, we can switch it back on.
> Explicitly set CMAKE_CXX_SCAN_FOR_MODULES=0

- cmake/helpers/GdalCAndCXXStandards.cmake
Backport #11615
**Authored by:** @hobu
> [Backport release/3.10] Explicitly set CMAKE_CXX_SCAN_FOR_MODULES=0

- frmts/zlib/contrib/infback9/minified_zutil.h
Fixes https://github.com/OSGeo/gdal/actions/runs/12695906104/job/35388828521?pr=11609
```
In file included from /Users/runner/work/gdal/gdal/frmts/zlib/contrib/infback9/infback9.c:6:
/Users/runner/work/gdal/gdal/frmts/zlib/contrib/infback9/minified_zutil.h:175:11: error: 'OS_CODE' macro redefined [-Werror,-Wmacro-redefined]
[  5%] Building CXX object apps/CMakeFiles/appslib.dir/Unity/unity_3_cxx.cxx.o
175 | #  define OS_CODE 19
|           ^
/Users/runner/work/gdal/gdal/frmts/zlib/contrib/infback9/minified_zutil.h:146:11: note: previous definition is here
146 | #  define OS_CODE  7
|           ^
```
> Fix build in infback9 on MacOS and unity builds

- frmts/gtiff/tif_jxl.c
- frmts/gtiff/tif_jxl.h
Ran into errors on a custom Android build on Arm.
Fixes build errors on an obscure target config when copying these two files into a custom build of libtiff.
1. The TIFF_SIZE_FORMAT use is generally good practice.
2. The head include fix is for a when the header is used in other files where  the `TIFF` type might not already be defined.
```
third_party/tiff/libtiff/tif_jxl.c:418:31: error: format specifies type 'long' but the argument has type 'size_t' (aka 'unsigned int') [-Werror,-Wformat]
416 |                               "JxlDecoderExtraChannelBufferSize returned %ld, "
|                                                                          ~~~
|                                                                          %zu
417 |                               "expecting %u",
418 | …
```
> tif_jxl: Add include for TIFF type and use TIFF_SIZE_FORMAT for error.

- frmts/aigrid/gridlib.c
- port/cpl_error.h
Callers of things in cpl_error.h should not have to be aware of internally required includes.
Minor cleanup from https://github.com/OSGeo/gdal/commit/ad15a8e141c4841ef1696ad88d0ea55272c82d01
> cpl_error.h: Move the include of stdbool for CPLErrorOnce into the header.

- frmts/zlib/contrib/infback9/minified_zutil.h
> [Backport release/3.10] Fix build in infback9 on MacOS and unity builds

- autotest/cpp/test_cpl.cpp
- frmts/eeda/eedadataset.cpp
- frmts/pds/pdsdataset.cpp
- frmts/pds/vicardataset.cpp
- frmts/pds/vicardataset.h
- frmts/pds/vicarkeywordhandler.cpp
- frmts/rmf/rmfdataset.cpp
- gcore/gdaljp2box.cpp
- gcore/gdalmultidim.cpp
- gcore/gdalrasterband.cpp
- gcore/rasterio.cpp
- gcore/rawdataset.cpp
- ogr/ogr_swq.h
- ogr/ogrsf_frmts/cad/libopencad/cadheader.cpp
- ogr/ogrsf_frmts/generic/ogr_gensql.cpp
- ogr/ogrsf_frmts/gmlutils/ogrwfsfilter.cpp
- ogr/ogrsf_frmts/oapif/ogroapifdriver.cpp
- ogr/swq_expr_node.cpp
- ogr/swq_op_general.cpp
- port/cpl_safemaths.hpp
The code base has assumed for many many years that we have access to 64-bit integer types.
> Remove uses of #ifdef CPL_HAS_GINT64

- autotest/gdrivers/data/vrt/processed_OutputBands_FROM_LAST_STEP.vrt
- autotest/gdrivers/vrtprocesseddataset.py
- doc/source/drivers/raster/vrt_processed_dataset.rst
- frmts/vrt/data/gdalvrt.xsd
- frmts/vrt/vrtdataset.h
- frmts/vrt/vrtprocesseddataset.cpp
Alternative to #11573 . Introduces an attribute `scale` to `<Input>` with default value `auto`. This will cause input datasets with a defined scale or offset to be unscaled to Float64 (also causing output bands to be Float64). `<Input unscale="false">` prevents this and keeps the current behavior. `<Input scale="true">` invokes the unscaling machinery regardless of the defined scale/offset values in the input dataset, so that the output type is always consistent.
~~I don't love the implementation which ends up touching `VRTProcessedDataset` in several places. I think a cleaner implementation could involve creating a method like `GDALRasterBand* GDALRasterBand::GetUnscaled()`. If the band was not scaled it could return a reference to itself; for a band with scaling it could return a a …
> VRT processed dataset: unscale source raster values

- autotest/gcore/gcps2geotransform.py
- gcore/gdal_misc.cpp
> [Backport release/3.10] GDALGCPsToGeoTransform(): return FALSE when invalid geotransform is generated

- port/cpl_path.cpp
- port/cpl_vsil_abstract_archive.cpp
Fixes https://issues.oss-fuzz.com/issues/388868487
This is just a band-aid... The use of CPLFormFilename() and friends is so dangerous with the rotating TLS buffers that may end up overwritten if too many calls are nested...
> Fix read heap-buffer-overflow on nested /vsitar/ calls

- alg/gdalwarpkernel.cpp
- apps/gdal_rasterize_lib.cpp
- apps/gdal_translate_lib.cpp
- apps/gdaladdo.cpp
- apps/gdalbuildvrt_lib.cpp
- apps/ogrlineref.cpp
- frmts/envisat/EnvisatFile.c
- frmts/gtiff/libgeotiff/geotiff_proj4.c
- frmts/gxf/gxf_ogcwkt.c
- frmts/gxf/gxf_proj4.c
- frmts/gxf/gxfopen.c
- frmts/gxf/gxfopen.h
- frmts/ilwis/ilwisdataset.cpp
- frmts/mrf/marfa_dataset.cpp
- frmts/mrf/mrf_band.cpp
- frmts/ogcapi/gdalogcapidataset.cpp
- frmts/stacit/stacitdataset.cpp
- frmts/usgsdem/usgsdem_create.cpp
- frmts/vrt/pixelfunctions.cpp
- frmts/vrt/vrtdataset.cpp
- gcore/gdaldefaultoverviews.cpp
- gcore/gdalexif.cpp
- ogr/ogrsf_frmts/gpkg/ogrgeopackagetablelayer.cpp
- ogr/ogrutils.cpp
- port/cpl_minizip_unzip.cpp
Coverity Scan has updated their scanner, which has raised tons of new warnings. Just addressing the medium and high severity ones, but overall nothing alarming... Tons of low priority ones remainaing...
> Address medium and high severity new Coverity fixes

- port/cpl_path.cpp
- port/cpl_vsil_abstract_archive.cpp
> [Backport release/3.10] Fix read heap-buffer-overflow on nested /vsitar/ calls

- gcore/rasterio.cpp
- gcore/rasterio_ssse3.cpp
> Avoid clang warning in -fsanitize=undefined -O mode (master only)

- doc/source/user/configoptions.rst
Fixes the configoptions.rst documentation of directive 'ignore-env-vars' which is incorrectly named  (ignore-env-variables)
> DOC: configoptions fix ignore-env-vars directive

- doc/source/user/configoptions.rst
Backport #11647
**Authored by:** @mdsumner
> [Backport release/3.10] DOC: configoptions fix ignore-env-vars directive

- swig/python/CMakeLists.txt
- swig/python/install_python.cmake.in
> [Backport release/3.10] Python bindings: on Debian, fix install target with non-Debian provided python version

- autotest/ogr/ogr_gml_geom.py
- ogr/gml2ogrgeometry.cpp
> CreateGeometryFromGML(): recognize aixm:ElevatedPoint (ignoring the elevation)

- alg/gdaltransformer.cpp
- autotest/gcore/interpolateatpoint.py
- doc/source/spelling_wordlist.txt
- gcore/gdal.h
- gcore/gdal_priv.h
- gcore/gdaldataset.cpp
- gcore/gdalrasterband.cpp
- swig/include/Band.i
- swig/include/java/gdal_java.i
- swig/include/python/gdal_python.i
and corresponding C functions GDALDatasetGeolocationToPixelLine() and GDALRasterInterpolateAtGeolocation()
and Python Band.InterpolateAtGeolocation()
> Add convenience GDALDataset::GeolocationToPixelLine() and GDALRasterBand::InterpolateAtGeolocation()

- autotest/pymod/gdaltest.py
- frmts/vrt/vrtdriver.cpp
This will make autotest simpler, as well as for end users / third party code that needs to determine the capabilities of the VRT driver
CC @dbaston
> VRT: advertize expression dialects in 'ExpressionDialects' driver metadata item

- alg/gdalwarper.cpp
- alg/gdalwarper.h
- alg/gdalwarpkernel.cpp
- alg/gdalwarpoperation.cpp
- autotest/alg/warp.py
On top of https://github.com/OSGeo/gdal/pull/11649, renames several variables as suggested in https://github.com/OSGeo/gdal/pull/11649#discussion_r1914799598
While editing the code, I noticed that
- unlike "sum" and "average", mode resampling was not considering partial pixel coverage
- a logic error prevented the value of -1 from being selected as the mode
This PR addresses both of these issues.
> Warper: Fixes related to mode resampling

- alg/gdalwarper.cpp
- alg/gdalwarper.h
- alg/gdalwarpkernel.cpp
- alg/gdalwarpoperation.cpp
- autotest/alg/warp.py
Adds a `TIE_STRATEGY` warping option to provide some control over the destination pixel value during "mode" resampling when multiple source values appear at the same frequency. The current behavior of choosing the first value encountered can introduce a spatial bias (favoring values from the north/west) that is undesirable in some applications.
> Warper: Add TIE_STRATEGY warp option

- apps/CMakeLists.txt
- apps/gdalalg_raster.cpp
- apps/gdalalg_raster_overview.h
- apps/gdalalg_raster_overview_add.cpp
- apps/gdalalg_raster_overview_add.h
- apps/gdalalg_raster_overview_delete.cpp
- apps/gdalalg_raster_overview_delete.h
- apps/gdalalg_raster_reproject.cpp
- autotest/cpp/test_gdal_algorithm.cpp
- autotest/utilities/test_gdal.py
- autotest/utilities/test_gdalalg_raster_overview.py
- doc/source/conf.py
- doc/source/programs/gdal_raster.rst
- doc/source/programs/gdal_raster_overview.rst
- doc/source/programs/gdal_raster_overview_add.rst
- doc/source/programs/gdal_raster_overview_delete.rst
- doc/source/programs/gdal_raster_reproject.rst
- doc/source/programs/index.rst
- gcore/gdalalgorithm.cpp
- gcore/gdalalgorithm.h
Docs previews: https://gdal--11614.org.readthedocs.build/en/11614/programs/gdal_raster_overview_add.html and https://gdal--11614.org.readthedocs.build/en/11614/programs/gdal_raster_overview_delete.html
> Add 'gdal raster overview add' and 'gdal raster overview delete'

- apps/CMakeLists.txt
- apps/gdalalg_raster.cpp
- apps/gdalalg_raster_clip.cpp
- apps/gdalalg_raster_clip.h
- apps/gdalalg_raster_pipeline.cpp
- autotest/utilities/test_gdalalg_raster_pipeline.py
- doc/source/conf.py
- doc/source/programs/gdal_raster.rst
- doc/source/programs/gdal_raster_clip.rst
- doc/source/programs/gdal_raster_pipeline.rst
- doc/source/programs/index.rst
Inspired from https://rasterio.readthedocs.io/en/stable/api/rasterio.rio.clip.html
> Add 'gdal raster clip' and 'gdal raster pipeline read ... ! clip ... ! write ...'

- autotest/cpp/CMakeLists.txt
> [Backport release/3.10] Fix compiler warning on fetched googletest on fedora:rawhide with latest clang

- alg/contour.cpp
- alg/marching_squares/level_generator.h
- alg/marching_squares/polygon_ring_appender.h
- alg/marching_squares/segment_merger.h
- apps/gdal_contour.cpp
- autotest/alg/contour.py
- autotest/cpp/test_marching_squares_polygon.cpp
- autotest/utilities/test_gdal_contour.py
- doc/source/programs/gdal_contour.rst
Fixes #11564 by not including raster min/max when polygonize and fixed levels are specified.
MIN and MAX literals can be used to specify raster min/max values, e.g.:
-fl MIN 10 20 30 MAX
> [gdal_contour] Do not include min/max when polygonize

- autotest/ogr/data/csv/double_quotes_in_middle_of_field_bis.csv
- autotest/ogr/ogr_csv.py
- port/cpl_csv.cpp
> CSV: fix parsing files with double-quote inside a field value

- apps/ogr2ogr_lib.cpp
- autotest/utilities/test_ogr2ogr_lib.py
- ogr/ogrsf_frmts/shape/ogrshapelayer.cpp
> Shapefile driver/ogr2ogr to Shapefile: write DateTime as ISO8601 string, both in Arrow and non-Arrow code paths

- autotest/ogr/data/csv/double_quotes_in_middle_of_field_bis.csv
- autotest/ogr/ogr_csv.py
- port/cpl_csv.cpp
> [Backport release/3.10] CSV: fix parsing files with double-quote inside a field value

- .github/workflows/conda.yml
- ci/travis/conda/upload.sh
As shown in https://github.com/OSGeo/gdal/issues/11676 our current strategy is to always consider the upload stage to have succeeded. Change that to fail on errors, or lack of packages to upload.
> CI: gdal-master conda upload: harden script to detect errors

- autotest/pyscripts/test_gdal_calc.py
- simplify generation of temporary file names, since they'll be cleaned up automatically
- separate independent tests into separate functions
- add tests for untested arguments
- avoid copying input dataset for every test function
- use vsimem where possible
> autotest: update tests for gdal_calc

- doc/source/development/rfc/index.rst
- doc/source/development/rfc/rfc105_safe_path_manipulation_functions.rst
- doc/source/spelling_wordlist.txt
[Rendered view](https://gdal--11640.org.readthedocs.build/en/11640/development/rfc/rfc105_safe_path_manipulation_functions.html)
> Add RFC 105 text: Add and use safe path manipulation functions

- apps/argparse/argparse.hpp
- apps/gdalargumentparser.cpp
- doc/source/programs/gdal_translate.rst
- doc/source/programs/gdaladdo.rst
- doc/source/programs/gdalbuildvrt.rst
- doc/source/programs/gdalwarp.rst
- doc/source/programs/ogrinfo.rst
Fixes #11692
argparse.hpp change submitted upstream in https://github.com/p-ranav/argparse/pull/393
> traditional CLI: limit argparse output width to 80; edit a few doc page to match that

- autotest/ogr/ogr_gpkg.py
- autotest/ogr/ogr_sqlite.py
- autotest/pymod/ogrtest.py
- ogr/ogr_api.h
- ogr/ogr_feature.h
- ogr/ogrfeature.cpp
- ogr/ogrfielddefn.cpp
- ogr/ogrsf_frmts/generic/ogrlayer.cpp
- ogr/ogrsf_frmts/gpkg/ogr_geopackage.h
- ogr/ogrsf_frmts/gpkg/ogrgeopackagedatasource.cpp
- ogr/ogrsf_frmts/gpkg/ogrgeopackagetablelayer.cpp
- ogr/ogrsf_frmts/ogrsf_frmts.h
- ogr/ogrsf_frmts/pg/ogr_pg.h
- ogr/ogrsf_frmts/pg/ogrpgtablelayer.cpp
- ogr/ogrsf_frmts/sqlite/ogr_sqlite.h
- ogr/ogrsf_frmts/sqlite/ogrsqlitebase.h
- ogr/ogrsf_frmts/sqlite/ogrsqlitedatasource.cpp
- ogr/ogrsf_frmts/sqlite/ogrsqlitetablelayer.cpp
- swig/include/ogr.i
This actually fixes transactional editing in QGIS for GPKG:
https://github.com/qgis/QGIS/pull/59797#issuecomment-2544133498
Followup https://github.com/OSGeo/gdal/pull/11609
I have also moved the IsGenerated flag to the field definition class as recommended by Even.
> [SQLite] Support SAVEPOINT

- autotest/ogr/ogr_dxf.py
- ogr/ogrsf_frmts/dxf/ogrdxfwriterlayer.cpp
Adds support for writing MultiPoints by DXF driver.
#11686 
It comes from this [thread](https://www.mail-archive.com/gdal-dev@lists.osgeo.org/msg42154.html).
* OS:
* Compiler:
> Handle MultiPoints in DXF writer (fixes #11686)

- autotest/ogr/ogr_geom.py
- ogr/ogrlinestring.cpp
> [Backport release/3.10] Fix GeodesicLength() that was quite severely broken as working only on closed linestrings (3.10.0 regression)

- autotest/gcore/cog.py
a -> b
Just a minor typo such that the second JPEG_QUALITY check was a repeat of the first.
> cog.py: Fix test_cog_creation_of_overviews_with_compression.

- .github/workflows/ubuntu_20.04/Dockerfile.ci
Download from GitHub master to avoid failures such as https://github.com/OSGeo/gdal/actions/runs/12948440864/job/36117116656
Currently the contents of this file are identical to the one downloaded from www.partow.net.
Downloading a specific hash would likely break when the repository is force-pushed (see https://gitlab.opengeosys.org/ogs/ogs/-/merge_requests/3981, https://github.com/LMMS/lmms/issues/5064)
> CI: Download exprtk from GitHub

- docker/alpine-normal/Dockerfile
- docker/ubuntu-full/Dockerfile
Use the release branch instead of the master branch.
> CI: Point ExprTk to release branch

- apps/CMakeLists.txt
- apps/gdalalg_raster.cpp
- apps/gdalalg_raster_mosaic.cpp
- apps/gdalalg_raster_mosaic.h
- apps/gdalalg_raster_stack.cpp
- apps/gdalalg_raster_stack.h
- autotest/utilities/test_gdalalg_raster_mosaic.py
- doc/source/conf.py
- doc/source/programs/gdal_raster.rst
- doc/source/programs/gdal_raster_mosaic.rst
- doc/source/programs/gdal_raster_stack.rst
- doc/source/programs/index.rst
Also allow gdal raster mosaic to generate regular datasets, not just VRT
Fixes #11706
> Rename 'gdal raster buildvrt' to 'gdal raster mosaic', and add 'gdal raster stack'

- autotest/gcore/cog.py
`BLOCKSIZE` --> `BLOCKXSIZE`
I got a warning from running the test, but it passed before.
This is a trivial bug in testing.
> cog.py: Fix typo in test_cog_write_jpegxl_alpha

- frmts/plmosaic/plmosaicdataset.cpp
> [Backport 3.10] PLMOSAIC: Use a unique user-agent string to isolate usage of driver

- autotest/ogr/ogr_gml_geom.py
- ogr/gml2ogrgeometry.cpp
> gml:CircleByCenterPoint(): return a 5-point CIRCULARSTRING for compliance with ISO/IEC 13249-3:2011

- apps/gdalalg_raster_mosaic.cpp
- apps/gdalalg_raster_stack.cpp
- apps/gdalbuildvrt_lib.cpp
- autotest/utilities/test_gdalalg_raster_mosaic.py
- doc/source/programs/gdal_raster_mosaic.rst
- doc/source/programs/gdal_raster_stack.rst
- doc/source/programs/gdalbuildvrt.rst
- gdal raster mosaic/stack: add a --resolution=same mode, and default to it
- gdalbuildvrt: add '-resolution same' mode to check all source rasters have the same resolution
- gdal raster mosaic/stack: turn gdalbuildvrt -strict mode
Fixes #11717 
CC @dbaston
> gdal raster mosaic/stack: turn gdalbuildvrt -strict mode, and add a --resolution=same mode mode

- autotest/ogr/ogr_gml_geom.py
- ogr/gml2ogrgeometry.cpp
> [Backport release/3.10] gml:CircleByCenterPoint(): return a 5-point CIRCULARSTRING for compliance with ISO/IEC 13249-3:2011

- doc/source/programs/ogrinfo.rst
I tried to combine this with my patch 62 but failed.
> Update ogrinfo.rst to note -dialect is ignored with -where.

- doc/source/programs/gdal_rasterize.rst
Hope I got it right.
I tried to combine this with my patch 63 but failed.
> Update gdal_rasterize.rst to optimize -optim

- autotest/gdrivers/data/stacit/test_stac_1.1.json
- autotest/gdrivers/stacit.py
- frmts/stacit/stacitdataset.cpp
> [Backport release/3.10] STACIT: STAC 1.1 support

- ogr/ogrsf_frmts/miramon/mm_wrlayr.c
Fixes a memory leak that happens in the case where polygon zero creates the database but some error occurs in the creation of the polygon zero. The database must be destroyed and created again next time the polygon zero is created. It's been reproduced in the case of skipFailures==true.
> MiraMonVector: Fix issue 393742177 oss-fuzz

- autotest/ogr/ogr_mvt.py
- doc/source/drivers/vector/mvt.rst
- ogr/ogrsf_frmts/mvt/ogrmvtdataset.cpp
> [Backport release/3.10] MVT: allow generating tilesets with more than 1 tile at zoom level 0

- autotest/ogr/ogr_gpkg.py
- ogr/ogrsf_frmts/gpkg/ogrgeopackagedatasource.cpp
- ogr/ogrsf_frmts/sqlite/ogrsqlitedatasource.cpp
> SQLite/GPKG: run PRELUDE_STATEMENTS after end of initialization, in particular after Spatialite loading

- swig/python/modify_cpp_files.cmake
Fixes https://github.com/OSGeo/gdal/issues/11795
Current code checks `CPLGetLastErrorType` to see if there is an error. If so, `Py_XDECREF(resultobj)` is called, which causes the error to be reset. The subsequent call to `CPLGetLastErrorMsg()` then returns an empty string.
> SWIG: Avoid losing error message

- doc/source/download.rst
- doc/source/spelling_wordlist.txt
Adds installation instructions for users of pixi as an alternative to conda/mamba.
https://github.com/OSGeo/gdal/issues/11551
> download.rst: add instructions to install via pixi (fixes #11551)

- doc/source/download.rst
- doc/source/spelling_wordlist.txt
Hey @rouault , I wasn't able to cherry-pick 9a253c049b12f6fe09f2db2ad27627aaf82f29 but I was able to cherry-pick the other commits you listed.
Apologies, I have never cherry-picked commits before.
Edit: Fixes https://github.com/OSGeo/gdal/pull/11802
> Backport 11802 to release/3.10

- ogr/ogr_api.cpp
- swig/include/python/docs/ogr_geometry_docs.i
> Doc: specify what happens for Z/M for AddPoint() / AddPoint_2D()

- autotest/ogr/ogr_libkml.py
- ogr/ogrsf_frmts/libkml/ogr_libkml.h
- ogr/ogrsf_frmts/libkml/ogrlibkmldatasource.cpp
- ogr/ogrsf_frmts/libkml/ogrlibkmllayer.cpp
> LIBKML: fix error when creating a Id field of type integer

- MIGRATION_GUIDE.TXT
- alg/gdal_alg.h
- alg/gdal_crs.cpp
- alg/gdal_rpc.cpp
- alg/gdal_tps.cpp
- alg/gdalgeoloc.cpp
- alg/gdaltransformer.cpp
- alg/gdalwarpoperation.cpp
- apps/gdalwarp_lib.cpp
- autotest/gcore/geoloc.py
- doc/source/spelling_wordlist.txt
- ogr/ogr_spatialref.h
- ogr/ogrct.cpp
Fixes #11817
Kind of a breaking change, but the current behavior was highly inconsistent and hard to reason about.
New paragraph in MIGRATION_GUIDE.TXT:
- The following methods OGRCoordinateTransformation::Transform(size_t nCount, double *x, double *y, double *z, double *t, int *pabSuccess) and OGRCoordinateTransformation::TransformWithErrorCodes(size_t nCount, double *x, double *y, double *z, double *t, int *panErrorCodes) are modified to return FALSE as soon as at least one point fails to transform (to be consistent with the other form of Transform() that doesn't take a "t" argument), whereas previously they would return FALSE only if no transformation was found. When FALSE is returned the pabSuccess[] or panErrorCodes[] arrays indicate which point succeeded or failed to transform.
The …
> Make all Transform methods of OGRCoordinateTransformation and GDALTransformerFunc return FALSE as soon as one point fails to transform

- autotest/utilities/test_gdalalg_info.py
- autotest/utilities/test_gdalalg_pipeline.py
- autotest/utilities/test_gdalalg_raster_convert.py
- autotest/utilities/test_gdalalg_raster_edit.py
- autotest/utilities/test_gdalalg_raster_info.py
- autotest/utilities/test_gdalalg_raster_mosaic.py
- autotest/utilities/test_gdalalg_raster_overview.py
- autotest/utilities/test_gdalalg_raster_pipeline.py
- autotest/utilities/test_gdalalg_vector_clip.py
- autotest/utilities/test_gdalalg_vector_convert.py
- autotest/utilities/test_gdalalg_vector_filter.py
- autotest/utilities/test_gdalalg_vector_info.py
- autotest/utilities/test_gdalalg_vector_pipeline.py
- doc/source/programs/gdal_cli_from_python.rst
- doc/source/programs/index.rst
- swig/include/python/gdal_python.i
- Python bindings: add syntaxic sugar to get/set algorithm arguments
- Doc: add a few examples of how to use GDAL algorithms from Python
> Python bindings: add syntaxic sugar to get/set algorithm arguments + doc

- apps/gdal_rasterize_lib.cpp
- autotest/utilities/test_gdal_rasterize.py
But warn if it has a decimal part.
Fixes #11829
> [gdal_rasterize] Also accept doubles for -ts

- ogr/ogrsf_frmts/mysql/ogrmysqldatasource.cpp
MYSQL_OPT_RECONNECT is deprecated since mysql 80034
Fixes #11842
> [mysql] Remove deprecated reconnect option for mysql >= 80034

- autotest/gdrivers/jpegxl.py
- Remove extra empty lines
- Rename `outfilename` and `tmpfilename` -> `filename`
- Rename `/vsimem/out.jxl` to be specific to each test function
- Use `with open()` to load data with `.read()`
- Fix spelling: `withing` -> `within`
- Add a comment explaining the double run in `test_jpegxl_rasterio()`
Fixes #11833
> jpegxl.py: Minor cleanup.

- alg/gdaltransformer.cpp
- doc/Makefile
- frmts/gtiff/gtiffdataset_read.cpp
- frmts/safe/safedataset.cpp
- gcore/gdal_misc.cpp
- ogr/ogrsf_frmts/adbc/ogradbcdataset.cpp
- port/cpl_error.h
Small utility class to set TurnFailureIntoWarning and restore it when deleted.
Fix #11831
> CPLTurnFailureIntoWarning backuper

- apps/CMakeLists.txt
- apps/gdalalg_raster.cpp
- apps/gdalalg_raster_calc.cpp
- apps/gdalalg_raster_calc.h
- autotest/gdrivers/vrtderived.py
- autotest/utilities/test_gdalalg_raster_calc.py
- doc/source/programs/gdal_raster.rst
- doc/source/programs/gdal_raster_calc.rst
- doc/source/programs/index.rst
- frmts/vrt/vrtexpression_muparser.cpp
- frmts/vrt/vrtsources.cpp
- gcore/gdalalgorithm.h
- swig/include/python/gdal_python.i
Adds a `gdal raster calc` tool that provides much of the functionality of `gdal_calc.py`. Some differences with `gdal_calc.py`:
- VRT output is supported, using the `muparser` expression engine
- input names are not restricted to A-Z; the syntax is `--input X=file.tif` rather than `-X file.tif`
- rather than have an `--allBands` flag, the expression can either refer to all bands of a raster (`--calc "X + 3"`) or a single band of a raster (`--calc "X[1] + 3"`)
- the `--extent union` and `--extent intersection` arguments are not supported, at least for now. I think these may best be handled by separate calls to `gdal raster mosaic/stack` and `gdal raster calc` but could be persuaded otherwise without much difficulty
- the various nodata handling flags of `gdal_calc.py` are not supported …
> Add 'gdal raster calc'

- apps/gdalalg_vector_clip.cpp
- apps/gdalalg_vector_pipeline.cpp
- apps/gdalalg_vector_pipeline.h
- apps/gdalalg_vector_read.cpp
- apps/gdalalg_vector_reproject.cpp
- apps/gdalalg_vector_select.cpp
- apps/gdalalg_vector_write.cpp
- autotest/utilities/test_gdalalg_vector_clip.py
- autotest/utilities/test_gdalalg_vector_pipeline.py
- autotest/utilities/test_gdalalg_vector_reproject.py
- ogr/ogrsf_frmts/generic/CMakeLists.txt
- ogr/ogrsf_frmts/generic/ogrlayerdecorator.h
- ogr/ogrsf_frmts/generic/ogrlayerwithtranslatefeature.cpp
- ogr/ogrsf_frmts/generic/ogrlayerwithtranslatefeature.h
- ogr/ogrsf_frmts/generic/ogrmutexeddatasource.cpp
- ogr/ogrsf_frmts/generic/ogrwarpedlayer.cpp
- ogr/ogrsf_frmts/generic/ogrwarpedlayer.h
On-the-fly reading of OSM requires to be able to iterate over features at the dataset level, and not just at the layer level. Let's implement that.
> gdal vector: make 'read', 'clip' and 'reproject' compatible of OSM-type of datasources that require ODsCRandomLayerRead

- autotest/ogr/ogr_hana.py
This PR adds a code to HANA tests that is responsible for cleaning up old schemas created by previous test runs.
> HANA: Cleanup schemas of old test runs

- doc/source/drivers/raster/vrt.rst
Fixes the small typo for `<Scale>`: 0.0 (The default for Offset) is used, instead of the Scale default of 1.0.
None
* OS:
* Compiler:
> Doc: Fix example `Scale` factor in `vrt.rst`

- ogr/ogrsf_frmts/miramon/mm_wrlayr.c
Fixes the error: A nullptr is expected when the section is not present in an INI file. However, in a particular case, the function MMReturnValueFromSectionINIFile returned a value other than nullptr. Although this did not cause an immediate error, it resulted in incorrect information being presented to the user.
No tests needed because it's a matter of information in a rare case.
Some user information has been corrected and updated in a not supported old metadata case.
Ignore the name of the MiraMonRaster branch (it is a name I had prepared for a future development).
> MiraMonVector fix error: Unexpected Non-nullptr Return

- ogr/ogr_geocoding.cpp
learn.microsoft.com explicitly recommends including winsock.h to get `struct timeval` definition.
Current version breaks when compiling with `-DWIN32_LEAN_AND_MEAN`.
> Add missing #include with struct timeval declaration

- ogr/ogrsf_frmts/miramon/mm_wrlayr.c
> [Backport release/3.10] MiraMonVector fix error: Unexpected Non-nullptr Return

- ogr/ogr_geocoding.cpp
Backport #11881
**Authored by:** @georgthegreat
> [Backport release/3.10] Add missing #include with struct timeval declaration

- autotest/alg/sieve.py
- autotest/alg/transformgeoloc.py
- autotest/alg/warp.py
- autotest/gcore/hfa_rfc40.py
- autotest/gcore/interpolateatpoint.py
- autotest/gcore/pixfun.py
- autotest/gcore/rasterio.py
- autotest/gcore/tiff_ovr.py
- autotest/gcore/tiff_write.py
- autotest/gcore/virtualmem.py
- autotest/gcore/vrt_read.py
- autotest/gdrivers/lcp.py
- autotest/gdrivers/memmultidim.py
- autotest/gdrivers/netcdf.py
- autotest/gdrivers/rmf.py
- autotest/gdrivers/tiledb_write.py
- autotest/gdrivers/vrtderived.py
- autotest/gdrivers/vrtpansharpen.py
- autotest/ogr/ogr_parquet.py
- autotest/pyscripts/test_gdal2tiles.py
- autotest/pyscripts/test_gdal2xyz.py
- autotest/pyscripts/test_gdal_retile.py
- autotest/pyscripts/test_validate_geoparquet.py
- autotest/utilities/test_gdal_rasterize.py
- autotest/utilities/test_gdal_viewshed.py
- autotest/utilities/test_gdallocationinfo.py
- swig/python/setup.py.in
> Python bindings: honour GDAL_PYTHON_BINDINGS_WITHOUT_NUMPY=YES/1/ON/TRUE or NO/0/OFF/FALSE

- frmts/gdalallregister.cpp
Follow on to these commits:
- 67992681aeadfac03ca4793889ba34a8937cbe72 - Remove R Object Data Store (*.rda) driver
- a4de9c081b9a3a7022c0e79575b88b5fc17ae77a Merge pull request #11758 from rouault/remove_geoconcept
- This was cumulative with previous PRs and contains the removal of rda
> gdalallregister.cpp: Finish removing rda driver.

- doc/source/drivers/vector/pmtiles.rst
This fixes what I think is a error in the `pmtiles` docs by fixing `MapVector` to be `Mapbox Vector`. This matches the upstream format name at https://github.com/mapbox/vector-tile-spec
> doc: update tile terminology in pmtiles.rst

- gcore/gdal_misc.cpp
- gcore/gdal_version.h.in
Not that the previous default has to be denied in any way, but there are serious concerns that it could cause high collateral damage and endanger people doing good.
> Set an empty GDAL_RELEASE_NICKNAME by default

- alg/gdalwarpoperation.cpp
- apps/gdalwarp_bin.cpp
- autotest/alg/warp.py
- autotest/gcore/vrt_read.py
- frmts/gti/gdaltileindexdataset.cpp
- frmts/gtiff/gtiffdataset_read.cpp
- frmts/gtiff/gtiffsplitbitmapband.cpp
- frmts/http/httpdriver.cpp
- frmts/vrt/vrtdataset.cpp
- frmts/vrt/vrtdataset.h
- frmts/vrt/vrtsourcedrasterband.cpp
- gcore/gdalmultidim.cpp
- ogr/ogrspatialreference.cpp
- port/cpl_error.cpp
- port/cpl_error_internal.h
Fixes #11904 
also uses a cleaner infrastructure to do that and retrofit its use everywhere where the old infrastructure was used previously
> VRT and multitthreaded warp: propagate errors from auxiliary threads to main thread

- autotest/gdrivers/zarr_driver.py
- Break up massive wkt string in `test_zarr_read_crs`
- Wrap a few places with `gdal.quiet_errors` where ZARR_V3 gives "Warning 1: fill_value = null is invalid" on open
- Remove a commented out debugging print
> zarr_driver.py: Minor cleanup.

- apps/argparse/argparse.hpp
Similar to #11879, `typename Iterator` might be just a raw pointer. The most corrent way would be using `std::iterator_traits` to get the type properly, but it seems that current static_cast can be simply removed.
> Fix build when iterators are raw pointers

- doc/source/spelling_wordlist.txt
- swig/include/python/docs/osr_coordinatetransformation_docs.i
- swig/include/python/osr_python.i
> [Backport release/3.10] Doc: Fix axis order of points in osr.CoordinateTransformation examples

- alg/gdalpansharpen.cpp
- alg/gdalpansharpen.h
- autotest/gdrivers/vrtpansharpen.py
> Pansharpen: avoid I/O errors when extent of PAN and MS bands differ by less than the resolution of the MS band

- autotest/conftest.py
> [Backport release/3.10] autotest/conftest.py: be robust to -rcX postfix on Curl version such as curl 8.13.0-rc1 of fedora:rawhide

- ogr/ogrsf_frmts/miramon/mm_gdal_functions.c
Corrects the spelling of a Catalan word in metadata. It ensures that "Nombre de vèrtexs" is written instead of "Nombre de vertexs".
This change follows the same approach used for other words, making tests unnecessary as it is merely an aesthetic adjustment.
> MiraMonVector: fixing a word in Catalan language

- alg/CMakeLists.txt
- alg/gdal_alg.h
- alg/gdal_homography.cpp
- alg/gdaltransformer.cpp
- autotest/alg/gcps2homography.py
- autotest/alg/homography.py
- autotest/alg/warp.py
- autotest/gcore/transformer.py
- doc/source/spelling_wordlist.txt
- gcore/gdal.h
- swig/include/gdal.i
Adds new transform type, Homography.
Adds functions to compute homography from a list of GCPs.
Adds functions to serialize and deserialize a homography
Automatically selects homography transform when there are 4 or 5 GCPs present. Homography provides an exact fit for 4 GCPs, and a better fit for 5 GCPs than the existing method (affine transformation).
#11940 
~~- [ ] AI (Copilot or something similar) supported my development of this PR~~
~~- [ ] Updated Python API documentation (swig/include/python/docs/)~~
* OS: WSL
> New Transform type: Homography

- frmts/pdf/pdfdrivercore.cpp
If I'm not mistaken, the default value for the DPI open option ( = GDAL_PDF_DPI config option) is 150, not 72, according to https://gdal.org/en/stable/drivers/raster/pdf.html.
This PR just fixes the DPI open option description.
> PDF: Fix default value for DPI open option description

- autotest/pyscripts/test_gdal2tiles.py
- swig/python/gdal-utils/osgeo_utils/gdal2tiles.py
Fixes --srcnodata from being ignored when the dataset does not need to be reprojected.
(Continuation of PR #11965)
> gdal2tiles.py: apply srcnodata values in non-reprojected datasets

- apps/gdal_contour_lib.cpp
- apps/gdal_translate_lib.cpp
- apps/gdalalg_raster_contour.cpp
- apps/gdalalg_raster_contour.h
- autotest/utilities/test_gdalalg_raster_contour.py
- doc/source/programs/gdal_raster_contour.rst
Fixes #11957
1. "gdal raster contour autotest/gcore/data/byte.tif out.gpkg", which lacks one of the required argument, shows the help message of the old gdal_contour utility. It should only indicate the name of one of the missing required arguments
2. "gdal raster contour --interval 1 autotest/gcore/data/byte.tif out.gpkg" repeated twice overwrites the output file. It should require a --overwrite flag to be specified to do that
> [cli][contour] Fix CLI issues #11957

- alg/gdalwarper.h
- alg/gdalwarpoperation.cpp
- autotest/utilities/test_gdalwarp_lib.py
First commit raises an error if warp option `INIT_DEST` is set to something other than a number or "NO_DATA". (The number can still be invalid.) Also raises an error with `INIT_DEST=NO_DATA` if there is no `NoData` value.
This caused a test failure in an existing test. After fixing that test, I simplified it in the second commit.
> Warper: Guard against some invalid values of INIT_DEST

- autotest/ogr/ogr_gpkg.py
- ogr/ogrsf_frmts/gpkg/ogrgeopackagetablelayer.cpp
> GPKG: fix SetNextByIndex() followed by GetNextFeature() without explicit call to GetLayerDefn()

- autotest/gcore/vsigs.py
- port/cpl_conv.cpp
> /vsigs/ (and /vsiaz/): invalidate cached state of files/directories when changing authentication parameters

- autotest/gcore/vsigs.py
- port/cpl_conv.cpp
> [Backport release/3.10] /vsigs/ (and /vsiaz/): invalidate cached state of files/directories when changing authentication parameters

- ogr/ogrsf_frmts/miramon/mm_gdal_driver_structs.h
- ogr/ogrsf_frmts/miramon/mm_wrlayr.c
- ogr/ogrsf_frmts/miramon/ogrmiramonlayer.cpp
Adds Vertical Reference System to MiraMon metadata file.
Corrects a minor issue with the zMin and zMax values in the Z header.
No tests required as this change only affects additional metadata information.
> MiraMonVector: writting VRS in metadata file + fixing error in Z header

- ogr/ogrsf_frmts/mssqlspatial/ogrmssqlspatialdatasource.cpp
The query was testing whether [dbo].[geometry_columns] exists, but then attempting to create just [geometry_columns] (without "dbo").
This fails if the table will be created in any schema other then "dbo".
Adjust to check whether just [geometry_columns] exists, so that we are checking whether the table exists in the ACTUAL schema we'll be creating it in.
Port of https://github.com/qgis/QGIS/pull/61101
> [mssqlspatial] Fix creation of metadata tables

- apps/gdalalg_raster_pipeline.cpp
- apps/gdalalg_vector_pipeline.cpp
- autotest/utilities/test_gdalalg_raster_pipeline.py
- autotest/utilities/test_gdalalg_vector_pipeline.py
> gdal raster/vector pipeline: fix PROJ strings as CRS

- swig/include/python/python_exceptions.i
> Python bindings: gdal.UseExceptions(): do not emit ModuleNotFound message when numpy not available

- alg/gdalwarpoperation.cpp
- autotest/utilities/test_gdalwarp_lib.py
> Warp: fix reprojecting on empty source window with nodata != 0 and MEM driver

- alg/gdalwarpoperation.cpp
- autotest/utilities/test_gdalwarp_lib.py
> [Backport 3.10] Warp: fix reprojecting on empty source window with nodata != 0 and MEM driver

- apps/ogr2ogr_lib.cpp
- autotest/ogr/ogr_openfilegdb_write.py
- gcore/gdaldriver.cpp
given that now FileGDB write support actually uses OpenFileGDB one.
> ogr2ogr: do not warn when writing to .gdb without explicit OpenFileGDB/FileGDB output driver specification

- apps/ogr2ogr_lib.cpp
- autotest/utilities/test_ogr2ogr_lib.py
Workaround is to set the OGR2OGR_USE_ARROW_API=NO configuration option
Fixes https://lists.osgeo.org/pipermail/gdal-dev/2025-March/060389.html
> ogr2ogr: fix -upsert with a GPKG source

- autotest/gdrivers/grib.py
- frmts/grib/degrib/g2clib/gridtemplates.c
- frmts/grib/gribdataset.cpp
> GRIB2: fix reading Transverse Merctor with negative easting/falsing; also fix reading it with scale factor != 0.9996

- doc/requirements.txt
Allows the doc requirements to be installed correctly when running:
```
cd /gdal/doc
python3 -m pip install -r requirements.txt
```
Currently, the following error is returned:
```
ERROR: Double requirement given: sphinx-rtd-theme>=3.0.0 (from -r requirements.txt (line 12)) (already in sphinx_rtd_theme (from -r requirements.txt (line 9)), name='sphinx-rtd-theme')
```
> Docs: Remove duplicate from docs requirement.txt

- .github/workflows/doc_checks.yml
- doc/CMakeLists.txt
#11951 may have made it more difficult for contributors to build documentation by requiring that the Doxygen build succeed without warnings in order to run Sphinx. There are reasons this could fail spuriously (different Doxygen version, for example). This PR adds a build option so that we can require Doxygen to succeed in CI but not require it by default.
cc @chambbj
> CMake: Allow Sphinx build to proceed if Doxygen produces warnings

- autotest/pyscripts/test_pct.py
- doc/source/programs/rgb2pct.rst
- swig/python/gdal-utils/osgeo_utils/rgb2pct.py
Adds `--options` to `rgb2pct.py` so that GeoTIFF creation options can be passed to the GeoTIFF driver, for example `--options COMPRESS=LZW`
#12031
> rgb2pct.py - added options

- doc/CMakeLists.txt
- gcore/gdaldrivermanager.cpp
- port/cpl_conv.cpp
1) `FAIL_ON_WARNINGS` is not a real Doxygen option, not sure how that ended up there. It is ignored by my Doxygen install but causes a failure on Windows with Doxygen from conda. The intended behavior is already captured in `WARN_AS_ERROR=FAIL_ON_WARNINGS_PRINT`.
2) Incredibly, Doxygen substitutes environment variables referenced with parentheses like `$(VARNAME)`. If `$(VARNAME)` expands to a Windows-style path with `\` , it then tried to interpret each component of a path as a Doxygen directive and unsurprisingly fails.
> Doc: Doxygen fixes

- autotest/gdrivers/netcdf.py
- frmts/netcdf/netcdfdataset.cpp
Increase precision of netCDF `GeoTransform` attribute and preferentially use it instead of calculated geotransform. Resolves https://github.com/OSGeo/gdal/issues/11993
> netCDF: Use GeoTransform attribute to prevent precision loss

- autotest/pyscripts/gdal2tiles/test_option_parser.py
- doc/source/programs/gdal2tiles.rst
- docker/alpine-normal/Dockerfile
- docker/ubuntu-full/Dockerfile
- docker/ubuntu-small/Dockerfile
- swig/python/gdal-utils/osgeo_utils/gdal2tiles.py
PIL 10.0 has deprecated antialias:
```
ANTIALIAS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZOS instead.
https://pillow.readthedocs.io/en/stable/releasenotes/10.0.0.html#
```
Fixes #12030
> gdal2tiles: remap PIL (Python Imaging Library)' 'antialias' resampling to GDAL Lanczos

- alg/gdal_alg.h
- alg/gdal_alg_priv.h
- alg/gdaltransformer.cpp
- alg/gdalwarper.cpp
- alg/gdalwarper.h
- alg/gdalwarpoperation.cpp
- apps/gdalalg_raster_reproject.cpp
- apps/gdalwarp_lib.cpp
- apps/ogr2ogr_lib.cpp
- autotest/alg/warp.py
- autotest/gcore/transformer.py
- autotest/utilities/test_gdalwarp_lib.py
- autotest/utilities/test_ogr2ogr_lib.py
- doc/source/programs/ogr2ogr.rst
- ogr/ogrct.cpp
- ogr/ogrct_priv.h
- swig/include/Operations.i
- swig/include/python/gdal_python.i
and add options to set PROJ's ALLOW_BALLPARK=NO and ONLY_BEST=YES
Fixes #11945
> gdalwarp / ogr2ogr: emit a warning if different coordinate operations are used during reprojection

- autotest/pymod/gdaltest.py
Follow-up to https://github.com/OSGeo/gdal/pull/12040
> gdaltest.py: Avoid error with pytest < 8.2

- ogr/ogrsf_frmts/miramon/mm_constants.h
- ogr/ogrsf_frmts/miramon/mm_gdal_constants.h
- ogr/ogrsf_frmts/miramon/mm_gdal_driver_structs.h
- ogr/ogrsf_frmts/miramon/mm_gdal_functions.c
- ogr/ogrsf_frmts/miramon/mm_gdal_functions.h
- ogr/ogrsf_frmts/miramon/mm_gdal_structures.h
- ogr/ogrsf_frmts/miramon/mm_rdlayr.c
- ogr/ogrsf_frmts/miramon/mm_rdlayr.h
- ogr/ogrsf_frmts/miramon/mm_wrlayr.c
- ogr/ogrsf_frmts/miramon/mm_wrlayr.h
- ogr/ogrsf_frmts/miramon/ogrmiramonlayer.cpp
- Cleans up the code:
- Removes the use of GDAL_COMPILATION.
- Rewrites certain wrapper functions to use native GDAL-style implementations.
- Moves the following functions from mm_wrlayr.c/h to mm_gdal_functions.c/h: 
-   MMReturnValueFromSectionINIFile()
-   MMReturnCodeFromMM_m_idofic()
-   MMCheck_REL_FILE()
The existing tests are sufficient to verify that this cleanup has been applied correctly.
Everything should continue to work as before, as no functional changes have been introduced.
Part of this PR is related to a future upcoming MiraMon raster driver — it involves code relocation only.
The other part addresses the removal of the GDAL_COMPILATION differentiation, which is no longer necessary in the current context.
> MiraMonVector refactoring: Code cleanup and relocation of three utility functions

- .pre-commit-config.yaml
Excludes `swig\python\setup.py.in` from Python precommit checks as it is a mix of Python and variable placeholders. 
Fix for #12118
> Exclude setup.py.in from Precommit Checks

- doc/source/download.rst
Updating these with a command that worked with me. I couldn't run the instructions as written because I don't have write access to the base environment on the system I'm working on. But my understanding is that mamba is no longer necessary anyway.
Also updated the install command to explicitly include `-c conda-forge`; a vanilla `conda install -c gdal-master gdal` happily installs GDAL 3.6 (surprise!)
> Doc: Simplify conda gdal-master instructions

- apps/gdal_translate_lib.cpp
- autotest/gcore/vrt_read.py
- autotest/utilities/test_gdal_translate.py
- autotest/utilities/test_gdal_translate_lib.py
References https://github.com/OSGeo/gdal/issues/12100
> gdal_translate: transform entire bounds of -projwin, not just two corners

- apps/gdal_translate_lib.cpp
- autotest/pymod/gdaltest.py
- autotest/utilities/test_gdal_translate_lib.py
Adds some tests for `gdal_translate` error cases and fixes three issues uncovered:
- warning for `projwin_srs` was emitted with `CE_None` (consider `CE_Failure` for `gdal raster clip`)
- range check for `-srcwin` did not check height of window for overflow
- no error message raised if output driver cannot be detected
> autotest: add tests for gdal_translate error cases

- gdal.cmake
> CMake: avoid detection of C23 #embed on too old compilers

- autotest/gcore/gdal_stats.py
- autotest/pyscripts/test_gdalcompare.py
- swig/include/python/gdal_python.i
- swig/python/gdal-utils/osgeo_utils/gdalcompare.py
> gdalcompare: do not emit exception when all pixels are invalid 

- swig/python/gdal-utils/osgeo_utils/gdal2tiles.py
After generating tiles with gdal2tiles, we got leaflet.html to see the result, but the layer is not enabled by default. I believe it makes sense to enable it by default.
* OS:
* Compiler:
> Enable the generated tile layer by default

- autotest/gcore/vsicurl.py
- doc/source/user/configoptions.rst
- doc/source/user/virtual_file_systems.rst
- port/cpl_known_config_options.h
- port/cpl_vsil_curl.cpp
- port/cpl_vsil_curl_class.h
- GDAL_HTTP_MAX_CACHED_CONNECTIONS corresponds to https://curl.se/libcurl/c/CURLMOPT_MAXCONNECTS.html
- GDAL_HTTP_MAX_TOTAL_CONNECTIONS corresponds to https://curl.se/libcurl/c/CURLMOPT_MAX_TOTAL_CONNECTIONS.html
Fixes #11855
> /vsicurl/: add GDAL_HTTP_MAX_CACHED_CONNECTIONS and GDAL_HTTP_MAX_TOTAL_CONNECTIONS config options

- ogr/ogrsf_frmts/gmlas/ogr_gmlas.h
- ogr/ogrsf_frmts/gmlas/ogrgmlasreader.cpp
For example on CityGML Lod3 file
https://drive.opendata.craig.fr/s/opendata/download?path=%2F3d%2Fbati3d_isere%2F02_CIM%2FCityGML%2FCC_Gresivaudan&files=2024_BC2_Gresivaudan_2021_LoD3_solaire.zip which is 185 MB large uncompressed, "ogrinfo GMLAS:38_Chartreuse_LoD3.gml -oo remove_unused_layers=yes" goes from 16.8 seconds down to 8.5.
> GMLAS: speed up parsing by using maps and saving a few memory allocations

- apps/gdal_translate_lib.cpp
- autotest/utilities/test_gdal_translate_lib.py
- swig/include/python/gdal_python.i
1) Sets `GDALTranslateOptions::bQuiet` to `true` by default. Otherwise, it is only `true` when called constructed with a progress callback. Possibly this variable could be removed altogether, as there are other methods for squelching errors.
2) Exposes `gdal_translate` options `-epo` and `-eco` as `errorIfWindowPartiallyOutsideSource` and `errorIfWindowCompletelyOutsideSource`. I would love for these to be True by default, but...backwards compatibility. (Maybe they could be the default for `gdal raster clip` though? ) I also don't love the names, maybe there is a better way to do it with a single text argument.
> Python bindings: expose gdal_translate -eco and -epo

- doc/source/development/dev_environment.rst
- scripts/setdevenv.ps1
Similar to https://github.com/OSGeo/gdal/commit/60bd384411bb783194b24582c1bbd424cb5f01df this adds a PowerShell script for setting up a development environment for the Python bindings:
```ps1
cd C:\docs\gdal\build
cmake --build . --target python_binding
C:\docs\gdal\scripts\setdevenv.ps1
python
>>> import osgeo
```
> Add PowerShell environment setup script

- port/cpl_vsi_mem.cpp
At least one config/platform needs `#include <cstdlib>`. std::strtoll here was introduced in 5b9ddbb4e9af9fa90edbe59e74bd94b0d6c52fb4 / #12099
This is on google3 linux with a bazel build and llvm less than 2 weeks old:
```
third_party/gdal/port/cpl_vsi_mem.cpp:782:37: error: no member named 'strtoll' in namespace 'std'; did you mean simply 'strtoll'?
782 |                 static_cast<time_t>(std::strtoll(mtime, nullptr, 10));
|                                     ^~~~~~~~~~~~
|                                     strtoll
include/stdlib.h:200:22: note: 'strtoll' declared here
200 | extern long long int strtoll
```
https://en.cppreference.com/w/cpp/string/byte/strtol
> cpl_vsi_mem.cpp: Add include for std::strtoll.

- ogr/ogrsf_frmts/generic/ogrregisterall.cpp
- ogr/ogrsf_frmts/ogrsf_frmts.h
Trivial cleanup:
The switch in #12124 / 9dbe489c4fcec4553c1eb01b4b227e6fafab76e0 to the MEM driver that can do both raster and vector in-memory work left references to `MEM_ENABLED` and `RegisterOGRMEM()`.
```shell
find . -name \*.cpp -o -name \*.h | xargs egrep 'MEM_ENABLED|RegisterOGRMEM'
./ogr/ogrsf_frmts/ogrsf_frmts.h:void CPL_DLL RegisterOGRMEM();
./ogr/ogrsf_frmts/generic/ogrregisterall.cpp:#ifdef MEM_ENABLED
./ogr/ogrsf_frmts/generic/ogrregisterall.cpp:    RegisterOGRMEM();
```
> Remove references to RegisterOGRMEM after #12124

- gcore/gdalmultidim.cpp
- swig/include/python/docs/gdal_mdm_docs.i
- swig/include/python/gdal_python.i
- swig/python/CMakeLists.txt
This pull request is a first attempt to create Python API documentation using the SWIG/Doxygen/Docstring approach. 
An example function from the "Multi-dimensional array API" has been documented, as discussed in #11916. 
The automated SWIG generated docstring is below:
```python
def CreateMDArray(self, *args):
r"""
CreateMDArray(Group self, char const * name, int dimensions, ExtendedDataType data_type, char ** options=None) -> MDArray
""""
```
This is the source C++ function and docstring:
```c++
/** Create a multidimensional array within a group.
*
* It is recommended that the GDALDimension objects passed in aoDimensions
* belong to this group, either by retrieving them with GetDimensions()
* or creating a new one with CreateDimension().
*
* Optionally implemented.
*
* Drivers known to …
```
> Add example Python API gdal_mdm_doc

- doc/source/programs/migration_guide_to_gdal_cli.rst
Fix a non-existent option of `gdal vector concat` usage in the migration guide.
> doc: Fix the usage of `gdal vector concat` in the migration guide

- autotest/ogr/ogr_gmlas.py
Fixes failing CI runs such as https://github.com/OSGeo/gdal/actions/runs/14602163924/job/40962681614?pr=12199#step:18:4447
FWIW the problematic URL can be accessed from Firefox because it automatically switches to https. Maybe GDAL should do something similar.
> autotest gmlas.py: Skip test if external schema URL cannot be accessed

- autotest/ogr/ogr_shape.py
- swig/include/Driver.i
- swig/include/python/docs/gdal_driver_docs.i
This is simply an alias for `Create(fname, 0, 0, 0, GDT_Unknown)`. In Python this is also equivalent to `CreateDataSource`, but `CreateDataSource` implies a distinction between a `Dataset` and a `DataSource` that no longer exists.
> SWIG: Add Driver.CreateVector

- autotest/osr/osr_basic.py
- swig/include/python/docs/osr_spatialreference_docs.i
- swig/include/python/osr_python.i
> Python bindings: Accept CRS definition in osr.SpatialReference constructor

- apps/gdalwarp_lib.cpp
Almost divides by two execution time in #12170 (so if there is a small regression somewhere, this should largely offset it)
Fixes #12170
> gdalwarp: speed-up warping to COG with heavy transformers (TPS / geoloc) by avoiding to instantiate it twice

- doc/source/drivers/raster/vrt.rst
- doc/source/spelling_wordlist.txt
Some subelements of `VRTRasterDerivedBand` are applicable across different type of Pixel Functions but were mentioned in sub sections. This PR adds a top-level section for those subelements.
* OS:
* Compiler:
> Doc: vrt.rst: Describe Common Elements of VRTDerivedRasterBand

- frmts/mrf/mrf_band.cpp
Fixes Coverity 1432696
Relevant lines of Coverity analysis
```
827    {
CID 1432696: (#1 of 1): Out-of-bounds access (OVERRUN)
21. overrun-buffer-arg: Overrunning dynamic array filedst.buffer by passing it to a function that accesses it at byte filedst.size + 63.[show details]
828        usebuff = DeflateBlock(filedst, poMRFDS->pbsize - filedst.size,
829                               deflate_flags);
291    // If we allocated a buffer, we need to copy the data to the input buffer.
7. access_dbuff_in_call: Calling memcpy indexes array src.buffer with index src.size.
292    memcpy(src.buffer, dbuff, src.size);
```
CC @lucianpls 
At the beginning I thought this was a false positive from Coverity Scan but reading and re-reading the code again, I believe it is right and at least theoritically …
> MRF: DeflateBlock(): avoid potential buffer overrun

- alg/llrasterize.cpp
- autotest/alg/rasterize.py
This fixes https://github.com/OSGeo/gdal/issues/12129
I could not come up with cases where floor would be more appropriate than the absolute difference, but maybe I don't see the full context here.
In addition, one could argue that EPSILON_INTERSECT_ONLY should be used instead of the fixed value of 0.01
I've added a test based on the initial failing file.
> gdal_rasterize: fix/simplify vertical/horizontal detection

- alg/gdalwarpoperation.cpp
- apps/gdalwarp_lib.cpp
- autotest/cpp/test_cpl.cpp
- autotest/utilities/test_gdalwarp_lib.py
- frmts/vrt/vrtmultidim.cpp
- ogr/ogrsf_frmts/cad/libopencad/dwg/r2000.cpp
- ogr/ogrsf_frmts/parquet/ogrparquetwriterlayer.cpp
- port/cpl_conv.cpp
- port/cpl_conv.h
- Issue error if `-srcnodata` and `-dstnodata` cannot be parsed
- Issue error if numeric input to `INIT_DEST` cannot be parsed
- Temporarily allow `INIT_DEST=NO_DATA`  without a NoData value, to accommodate rasterio usage
> GDALWarp: Harden NoData value parsing

- apps/CMakeLists.txt
- apps/gdalalg_raster.cpp
- apps/gdalalg_raster_fillnodata.cpp
- apps/gdalalg_raster_fillnodata.h
- apps/gdalalg_raster_pipeline.cpp
- apps/gdalalg_raster_pipeline.h
- autotest/utilities/test_gdalalg_raster_fillnodata.py
- doc/source/conf.py
- doc/source/programs/gdal_raster.rst
- doc/source/programs/gdal_raster_fillnodata.rst
- doc/source/programs/index.rst
```bash
Usage: gdal raster fillnodata [OPTIONS] <INPUT> <OUTPUT>
Fill nodata raster regions by interpolation from edges.
-i, --input <INPUT>                                  Input raster dataset [required]
-o, --output <OUTPUT>                                Output raster dataset (created by algorithm) [required]
Common Options:
-h, --help                                           Display help message and exit
--version                                            Display GDAL version and exit
--json-usage                                         Display usage as JSON document and exit
--drivers                                            Display driver list as JSON document and exit
--config <KEY>=<VALUE>                               Configuration option [may be …
```
> [cli] Port gdal_fillnodata to CLI

- doc/source/tutorials/code/vector_api_tut.py
- doc/source/tutorials/code/vector_api_tut2.py
- doc/source/tutorials/multidimensional_api_tut.rst
- doc/source/tutorials/vector_api_tut.rst
Related to #11917, this PR updates 2 more tutorials to use tabs for C++/C/Python code examples.
Other changes:
- Legacy examples for "With GDAL < 2.3 and C++" removed as discussed in #11917
- Python2 code updated to Python3 (print statements missing parentheses, `raw_input` changed to `input`), and added `gdal.UseExceptions()`).
- Full Python scripts moved to own files, and then included in the tutorial using `literalinclude`. This made it easier to test and format the scripts.
I've run through and tested the Python examples, but not the C/C++ ones (I'm not sure if I'd be able to correct any issues with these, although I could open an issue if they aren't working). 
The full C/C++ examples could also be moved to separate code files - let me know if I should do this.
> Move 2 more tutorials to use tabs

- swig/python/CMakeLists.txt
- swig/python/pyproject.toml.setuptools_gte_77
Avoids:
```
********************************************************************************
Please use a simple string containing a SPDX expression for `project.license`. You can also use `project.license-files`. (Both options available on setuptools>=77.0.0).
By 2026-Feb-18, you need to update your project and remove deprecated calls
or your builds will no longer be supported.
See https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license for details.
********************************************************************************
********************************************************************************
Please consider removing the following classifiers in favor of a SPDX license expression:
License :: OSI Approved :: MIT License
See …
```
> Python bindings: avoid deprecation warning with setuptools >= 77

- gdal.cmake
When building a separate project, this allows `find_package(GDAL CONFIG)` to import from a GDAL build tree using `cmake -DCMAKE_FIND_ROOT_PATH=/home/dan/dev/gdal/build-release ..`
See https://cmake.org/cmake/help/latest/guide/importing-exporting/index.html#exporting-targets-from-the-build-tree
> CMake: Export GDAL library targets

- autotest/gcore/numpy_rw.py
- swig/include/python/gdal_python.i
Resolves https://github.com/OSGeo/gdal/issues/12005
> Python bindings: Add Dataset.ReadAsMaskedArray

- apps/CMakeLists.txt
- apps/gdalalg_raster.cpp
- apps/gdalalg_raster_sieve.cpp
- apps/gdalalg_raster_sieve.h
- autotest/utilities/test_gdalalg_raster_sieve.py
- doc/source/conf.py
- doc/source/programs/gdal_raster.rst
- doc/source/programs/gdal_raster_sieve.rst
- doc/source/programs/index.rst
```
Usage: gdal raster sieve [OPTIONS] <INPUT> <OUTPUT>
Remove small polygons from a raster dataset.
-i, --input <INPUT>                                  Input raster dataset [required]
-o, --output <OUTPUT>                                Output raster dataset (created by algorithm) [required]
Common Options:
-h, --help                                           Display help message and exit
--version                                            Display GDAL version and exit
--json-usage                                         Display usage as JSON document and exit
--drivers                                            Display driver list as JSON document and exit
--config <KEY>=<VALUE>                               Configuration option [may be repeated]
--progress …
```
> [cli] gdal raster sieve

- autotest/ogr/data/topojson/topojson_with_crs.topojson
- autotest/ogr/ogr_topojson.py
- ogr/ogrsf_frmts/geojson/ogr_geojson.h
- ogr/ogrsf_frmts/geojson/ogresrijsondriver.cpp
- ogr/ogrsf_frmts/geojson/ogresrijsonreader.cpp
- ogr/ogrsf_frmts/geojson/ogrgeojsondatasource.cpp
- ogr/ogrsf_frmts/geojson/ogrgeojsondriver.cpp
- ogr/ogrsf_frmts/geojson/ogrgeojsonlayer.cpp
- ogr/ogrsf_frmts/geojson/ogrtopojsonreader.cpp
> TopoJSON: read a top level 'crs' member, and other fixes in GeoJSON and ESRIJSON drivers

- apps/gdalalg_vector_geom_set_type.cpp
- apps/gdalalg_vector_geom_set_type.h
- autotest/utilities/test_gdalalg_vector_geom_set_type.py
- doc/source/programs/gdal_vector_geom_set_type.rst
Replaces four mutually-exclusive flags with a single option, a sort of complement to 3c0d9011ef325b0d1ef3aa3b4ef66b089f258147
> gdal vector geom set-type: replace dimension flags with single option

- autotest/gdrivers/vrtderived.py
- doc/source/drivers/raster/vrt.rst
- frmts/vrt/pixelfunctions.cpp
Adds a "reclassify" pixel function. Can map values from individual values or specified ranges.
Doesn't currently check the ranges to make sure they are non-overlapping. Range checking is via O(n) lookup, could be improved by binary search later.
> VRTDerivedRasterBand: Add reclassify pixel function

- doc/source/drivers/vector/pg.rst
Simple change at documentation which adds valuable knowledge about the `PG_USE_COPY` option
Valuable knowledge about the option behavior was found at https://github.com/OSGeo/gdal/issues/1039#issuecomment-431696843
- No AI was used to contribute this piece
> Cleaned-up noise as this is a doc-only change
Not relevant
I'm not used to the .rst docs, please tell me if the formatting isn't correct.
The intent is the change being reflected at https://gdal.org/en/stable/drivers/vector/pgdump.html#environment-variables,
I've supposed this file was the SSoT for the knowledge about that option, please tell me if I'm wrong.
> Information about PG_USE_COPY on pg.rst docs

- autotest/gdrivers/vrtderived.py
- doc/source/drivers/raster/vrt.rst
- frmts/vrt/CMakeLists.txt
- frmts/vrt/pixelfunctions.cpp
- frmts/vrt/vrtreclassifier.cpp
- frmts/vrt/vrtreclassifier.h
Made a few changes after reviewing comparable interfaces in 
SAGA: https://saga-gis.sourceforge.io/saga_tool_doc/2.2.5/grid_tools_15.html
GRASS: https://grass.osgeo.org/grass-stable/manuals/r.reclass.html
QGIS: https://docs.qgis.org/3.40/en/docs/user_manual/processing_algs/qgis/rasteranalysis.html#reclassify-by-table
ArcGIS: https://pro.arcgis.com/en/pro-app/latest/tool-reference/spatial-analyst/reclassify.htm
gdal_reclassify: https://github.com/chiatt/gdal_reclassify
GDAL reclassify CLI: https://github.com/sacridini/reclassify_cli/tree/master
terra reclassify: https://search.r-project.org/CRAN/refmans/terra/html/classify.html
Simplifies the code somewhat by removing the "default" argument and moving it into the mapping table. Allows `NO_DATA` to appear on either side of an entry in the …
> VRT reclassification improvements

- apps/CMakeLists.txt
- apps/gdalalg_raster.cpp
- apps/gdalalg_raster_fill_nodata.cpp
- apps/gdalalg_raster_fill_nodata.h
- apps/gdalalg_raster_pipeline.cpp
- apps/gdalalg_raster_pixel_info.cpp
- apps/gdalalg_raster_pixel_info.h
- autotest/utilities/test_gdalalg_raster_fill_nodata.py
- autotest/utilities/test_gdalalg_raster_pixel_info.py
- doc/source/conf.py
- doc/source/programs/gdal_raster.rst
- doc/source/programs/gdal_raster_fill_nodata.rst
- doc/source/programs/gdal_raster_pixel_info.rst
- doc/source/programs/index.rst
suggested by @dbaston to be consistent with 'gdal raster clean-collar' and 'gdal raster color-map'
> Rename 'gdal raster fillnodata' as 'gdal raster fill-nodata' and 'gdal raster pixelinfo' as 'gdal raster pixel-info'

- apps/gdalalg_main.cpp
- apps/gdalalg_main.h
- autotest/cpp/test_gdal_algorithm.cpp
- gcore/gdalalgorithm.cpp
- gcore/gdalalgorithm.h
Refs #12253
```
$ gdal --help
Usage: gdal <COMMAND> [OPTIONS]
where <COMMAND> is one of:
- convert:  Convert a dataset (shortcut for 'gdal raster convert' or 'gdal vector convert').
- driver:   Command for driver specific operations.
- info:     Return information on a dataset (shortcut for 'gdal raster info' or 'gdal vector info').
- mdim:     Multidimensional commands.
- pipeline: Execute a pipeline (shortcut for 'gdal raster pipeline' or 'gdal vector pipeline').
- raster:   Raster commands.
- vector:   Vector commands.
- vsi:      GDAL Virtual System Interface (VSI) commands.
Common Options:
-h, --help              Display help message and exit
--json-usage            Display usage as JSON document and exit
--config <KEY>=<VALUE>  Configuration option [may be repeated]
Options: …
```
> gdal CLI: make --version and --drivers only available to top 'gdal' utility

- apps/gdalalg_raster_clean_collar.cpp
- apps/gdalalg_raster_clip.cpp
- apps/gdalalg_raster_color_map.cpp
- apps/gdalalg_raster_contour.cpp
- apps/gdalalg_raster_footprint.cpp
- apps/gdalalg_raster_mosaic.cpp
- apps/gdalalg_raster_reproject.cpp
- apps/gdalalg_raster_scale.cpp
- apps/gdalalg_raster_stack.cpp
- apps/gdalalg_raster_viewshed.cpp
- autotest/gcore/algorithm.py
- autotest/utilities/test_gdalalg_raster_clean_collar.py
- autotest/utilities/test_gdalalg_raster_clip.py
- autotest/utilities/test_gdalalg_raster_color_map.py
- autotest/utilities/test_gdalalg_raster_contour.py
- autotest/utilities/test_gdalalg_raster_footprint.py
- autotest/utilities/test_gdalalg_raster_mosaic.py
- autotest/utilities/test_gdalalg_raster_reproject.py
- autotest/utilities/test_gdalalg_raster_scale.py
- autotest/utilities/test_gdalalg_raster_viewshed.py
- doc/source/programs/gdal_raster_contour.rst
- doc/source/programs/gdal_raster_footprint.rst
- doc/source/programs/gdal_raster_mosaic.rst
- doc/source/programs/gdal_raster_reproject.rst
- doc/source/programs/gdal_raster_scale.rst
- doc/source/programs/gdal_raster_stack.rst
- doc/source/programs/gdal_raster_viewshed.rst
> gdal cli: add hyphens to separate composite-word argument names

- apps/gdalalg_raster_reclassify.cpp
- autotest/utilities/test_gdalalg_raster_reclassify.py
FYI @dbaston : using ``VRTDerivedRasterBand::AddSimpleSource(GDALRasterBand*)`` allows it to work with a unnamed / MEM source dataset
> gdal raster reclassify: allow it to accept a MEM input dataset

- apps/gdalalg_raster_calc.cpp
- apps/gdalalg_raster_contour.cpp
- apps/gdalalg_raster_convert.cpp
- apps/gdalalg_raster_create.cpp
- apps/gdalalg_raster_fill_nodata.cpp
- apps/gdalalg_raster_mosaic.cpp
- apps/gdalalg_raster_polygonize.cpp
- apps/gdalalg_raster_stack.cpp
- apps/gdalalg_raster_viewshed.cpp
- apps/gdalalg_vector_convert.cpp
- apps/gdalalg_vector_grid.cpp
- apps/gdalalg_vector_output_abstract.cpp
- apps/gdalalg_vector_pipeline.cpp
- apps/gdalalg_vector_rasterize.cpp
- autotest/utilities/test_gdalalg_raster_create.py
- autotest/utilities/test_gdalalg_raster_index.py
- autotest/utilities/test_gdalalg_raster_polygonize.py
- autotest/utilities/test_gdalalg_vector_convert.py
- autotest/utilities/test_gdalalg_vector_rasterize.py
- gcore/gdal_misc.cpp
- gcore/gdal_priv.h
- gcore/gdalalgorithm.cpp
- gcore/gdalalgorithm.h
- gcore/gdaldriver.cpp
and avoid overwriting a real file when outputting to MEM
> GDALAlgorithm: move common code dealing with overwriting in GDALAlgorithm::ProcessDatasetArg()

- apps/CMakeLists.txt
- cmake/helpers/configure.cmake
> [Backport release/3.11] Add linking to -latomic for std::atomic<uint64_t> on architectures where it is needed

- frmts/georaster/georaster_rasterband.cpp
- frmts/georaster/georaster_wrapper.cpp
Support long schema/table/column name. It used to only support length up to 64, not it is supported up to 128, which is the maximum length of the table/column name in Oracle.  
N/A
* OS:
* Compiler:
> Support long schema/table/column name

- autotest/ogr/ogr_geom.py
- ogr/ogrgeometry.cpp
@lbartoletti  When testing https://gitlab.com/sfcgal/SFCGAL/-/merge_requests/383 and running autotest/ogr/ogr_geometry.py, I saw SFCGAL tests where skipped even when the GDAL build was against SFCGAL. I realize this was due to the SFCGAL presence detection test failing due to broken 3D geometries. By default OGR export to pre-ISO WKB ...
> OGRGeometry::OGRexportToSFCGAL(): fix for 3D geometries for SFCGAL >= 1.5.2

- autotest/ogr/ogr_geom.py
- ogr/ogrgeometry.cpp
> [Backport release/3.11] OGRGeometry::OGRexportToSFCGAL(): fix for 3D geometries for SFCGAL >= 1.5.2

- autotest/utilities/test_gdalalg_raster_info.py
- gcore/gdalalgorithm.cpp
> [Backport release/3.11] GDALAlgorithm: fix reading a .gdalg.json dataset with 'GDALG' input format option specified

- doc/source/drivers/vector/csv.rst
Driver also creates PRJ side-car file when this option is used. This wasn't documented, and there is no separate LCO to create PRJ file only.
> Doc: added missing .prj to CREATE_CSVT

- autotest/utilities/test_gdalalg_vector_geom_simplify.py
- gcore/gdalalgorithm.cpp
An alternative would be to simply disallow NaN unless an `.AllowNaN()` is called when constructing the argument.
> GDALAlgorithm: Refuse NaN for arguments with specified valid ranges

- doc/source/conf.py
Currently, when building the docs several warnings are output:
```
checking consistency... C:\docs\gdal\doc\source\api\index.rst: document is referenced in multiple toctrees: ['index_pdf
', 'index'], selecting: index_pdf <- api/index
C:\docs\gdal\doc\source\community\index.rst: document is referenced in multiple toctrees: ['index_pdf', 'index'], selecting: index_pdf
<- community/index
C:\docs\gdal\doc\source\contributing\index.rst: document is referenced in multiple toctrees: ['index_pdf', 'index'], selecting: index_p
df <- contributing/index
C:\docs\gdal\doc\source\download.rst: document is referenced in multiple toctrees: ['index_pdf', 'index'], selecting: index_pdf <- down
load
...
```
This PR excludes the index_pdf.pdf for non-latex builds to stop the warnings. The original …
> Exclude index_pdf.rst for non-latex builds

- doc/source/tutorials/vector_api_tut.rst
- doc/source/user/multidim_raster_data_model.rst
PR also switches  `.. tab:: Python` to `.. group-tab:: Python`. This ensures all tabs in the group are switched to when one is selected, similar to `.. code-tab:`.
`.. code-tab:` cannot be used here, as it does not work with `literalinclude`.
> Add tabs to MDM raster docs

- autotest/utilities/test_gdalalg_vector_geom_simplify.py
- gcore/gdalalgorithm.cpp
> [Backport release/3.11] GDALAlgorithm: Refuse NaN for arguments with specified valid ranges

- autotest/requirements.txt
Our baseline since GDAL 3.9 is Python >= 3.8
> autotest/requirements.txt: remove mentions of python < 3.7.

- apps/gdalmdimtranslate_lib.cpp
- autotest/utilities/test_gdalalg_mdim_convert.py
gdal mdim translate doesn't validate bad `transpose` values that evaluate to 0
```
gdalmdimtranslate \
/vsicurl/https://github.com/OSGeo/gdal/raw/refs/heads/master/autotest/gdrivers/data/zarr/array_dimensions.zarr/ \
/vsimem/out.zarr -array "name=var,transpose=[a,1]"
```
Applies a check that zero values for transpose are equal to "0".
> MDIM translate: ensure valid axis values in transpose

- autotest/ogr/ogr_gml_geom.py
- ogr/gml2ogrgeometry.cpp
> GML geometry parser: recognize '<gml:Curve><gml:segments/></gml:Curve>' as LINESTRING EMPTY

- autotest/gcore/vsifile.py
- autotest/ogr/ogr_libkml.py
- ogr/ogrsf_frmts/libkml/ogrlibkmldrivercore.cpp
- ogr/ogrsf_frmts/libkml/ogrlibkmlfield.cpp
- port/cpl_minizip_zip.cpp
- ZIP creation: do not warn on filenames within ZIP that are non-Latin1
- LIBKML: advertize Date/Time/DateTime/Integer64 (mapped as string) as types on creations; do proper mapping of bool
Fixes #12292
> ZIP filename warning suppression, and LIBKML warning suppression

- autotest/ogr/ogr_gml_geom.py
- ogr/gml2ogrgeometry.cpp
> [Backport release/3.11] GML geometry parser: recognize '<gml:Curve><gml:segments/></gml:Curve>' as LINESTRING EMPTY

- apps/gdalalg_raster_calc.cpp
- autotest/cpp/test_gdal_algorithm.cpp
- frmts/vrt/pixelfunctions.cpp
- frmts/vrt/vrtprocesseddatasetfunctions.cpp
- frmts/zarr/zarr_v2_array.cpp
- frmts/zarr/zarr_v3_array.cpp
- gcore/gdal_priv.h
- gcore/gdal_typetraits.h
- gcore/gdalcachedpixelaccessor.h
- gcore/gdalrasterband.cpp
> [Backport release/3.11] Do not include cpl_float.h in gdal_priv.h, to avoid issues on Windows  with min/max macros

- apps/gdalalg_raster_tile.cpp
- apps/gdalalg_raster_tile.h
- autotest/utilities/test_gdalalg_raster_tile.py
- doc/source/programs/gdal2tiles.rst
- doc/source/programs/gdal_raster_tile.rst
> [Backport release/3.11] gdal raster tile: port --excluded-values, --excluded-values-pct-threshold, --nodata-values-pct-threshold from gdal2tiles

- autotest/gcore/vrt_read.py
- doc/source/drivers/raster/vrt.rst
- frmts/vrt/vrtdataset.cpp
Implements 'transpose' for the vrt connection options. This allows nomination of a variable by name and the `iXDim` and `iYDim` index positions for passing to `AsClassicDataset`. 
```bash
"vrt://autotest/gdrivers/data/netcdf/foo_5dimensional.nc?transpose=/temperature:3,4"
"vrt://autotest/gdrivers/data/zarr/array_dimensions.zarr?transpose=/var:1,0"
```
The original motivation was this HDF5, which doesn't have georeferencing in 2D form, but by using multidim cast to classic we get the transform that derives, and can add further augmentation like 'a_srs'. 
(needs earthdata auth). 
```bash
gdalinfo "vrt:///vsicurl/https://gpm1.gesdisc.eosdis.nasa.gov/data/GPM_L3/GPM_3IMERGHHE.07/1998/001/3B-HHR-E.MS.MRG.3IMERG.199 …
```
> VRT: 'transpose' for vrt:// connection

- doc/source/drivers/raster/examples/drivers/raster/stacit.py
- doc/source/drivers/raster/examples/stacit.py
- doc/source/drivers/raster/stacit.rst
Adds command-line and Python examples to the STACIT driver page, using the tabs Sphinx plugin. 
This is a sample pull request to get feedback on if this is a good approach to use for other drivers. 
cc @dbaston @rouault
- What is the best approach for handling the old and new command-line interfaces? Include both with a ` # from GDAL 3.11+` note? Only use the new approach for the latest docs?
- I have added `bash` (Linux) examples, and `PowerShell` (Windows) examples - as quoting can differ between the two operating systems (I ran into issues with the current examples). My personal preference is to not also include `cmd` Windows examples, but maybe these should also be added?
- I added the Python examples as separate scripts, and parts can then be included in the docs. This allows them to …
> Add STACIT driver examples

- autotest/cpp/CMakeLists.txt
- autotest/cpp/test_driver_metadata_multithread.cpp
- frmts/avif/avifdataset.cpp
- frmts/grib/gribdataset.cpp
- frmts/gtiff/cogdriver.cpp
- frmts/jpeg/jpgdataset.cpp
- frmts/jpeg/jpgdataset.h
- frmts/netcdf/netcdfdataset.cpp
- frmts/nitf/nitfdataset.cpp
- frmts/vrt/vrtdataset.h
- frmts/vrt/vrtdriver.cpp
- frmts/zarr/zarrdriver.cpp
- ogr/ogrsf_frmts/arrow/ogrfeatherdriver.cpp
- ogr/ogrsf_frmts/gpkg/ogrgeopackagedriver.cpp
- ogr/ogrsf_frmts/parquet/ogrparquetdriver.cpp
> [Backport 3.11] AVIF, GRIB, COG, JPEG, netCDF, NITF, VRT, ZARR, GPKG, ARROW, PARQUET: fix multithreading race in getting driver metadata

- autotest/gdrivers/wms.py
- doc/source/drivers/raster/wms.rst
- frmts/wms/CMakeLists.txt
- frmts/wms/frmt_wms_iiif.xml
- frmts/wms/minidriver_iiifimage.cpp
- frmts/wms/minidriver_iiifimage.h
- frmts/wms/wmsdriver.cpp
- frmts/wms/wmsdrivercore.cpp
```
$ gdalinfo IIIF:https://asge.jarvis.memooria.org/images/iiif/db/6431901e-7474-4c51-aa57-41dfddf13604 
Driver: WMS/OGC Web Map Service
Files: none associated
Size is 7236, 5238
Metadata:
CACHE_PATH=/home/even/.cache/gdalwmscache/1b6a019f0189df3f4dcfba57e2090320
Image Structure Metadata:
INTERLEAVE=PIXEL
Corner Coordinates:
Upper Left  (    0.0,    0.0)
Lower Left  (    0.0, 5238.0)
Upper Right ( 7236.0,    0.0)
Lower Right ( 7236.0, 5238.0)
Center      ( 3618.0, 2619.0)
Band 1 Block=256x256 Type=Byte, ColorInterp=Red
Overviews: 3618x2619, 1809x1309, 904x654, 452x327, 226x163, 113x81
Band 2 Block=256x256 Type=Byte, ColorInterp=Green
Overviews: 3618x2619, 1809x1309, 904x654, 452x327, 226x163, 113x81
Band 3 Block=256x256 Type=Byte, ColorInterp=Blue
Overviews: 3618x2619, 1809x1309, …
```
> WMS: add a mini-driver for International Image Interoperability Framework (IIIF) Image API 3.0

- frmts/vrt/pixelfunctions.cpp
- frmts/vrt/vrtdataset.h
- frmts/vrt/vrtderivedrasterband.cpp
When adding the `SOURCE_NAMES` argument that is used to pass source names to the VRT expression parser, I didn't notice that a mechanism for such internal arguments already exists. This updates `SOURCE_NAMES` to use that existing machinery.
> VRTDerivedBand: Make source_names work like other builtin arguments

- frmts/pdf/pdfdataset.cpp
- frmts/pdf/pdfobject.cpp
- frmts/pdf/pdfobject.h
- frmts/pdf/pdfsdk_headers_poppler.h
> [cleanup] PDF driver: use Page::getPageObj() getter for Poppler >= 25.03.00

- autotest/gdrivers/vrtderived.py
- doc/source/drivers/raster/vrt.rst
- frmts/vrt/pixelfunctions.cpp
Makes pixel functions NoData-aware for _non-complex_ inputs. For most functions with <= 2 inputs, a NoData input results in a NoData output. For functions with > 2 inputs, the `propagateNoData` parameter is used to determine whether to ignore `NoData` inputs or cause them to produce `NoData` outputs.
There is definitely room to simplify the pixel function implementations but I didn't pursue that here, just focused on getting correct behavior for now.
Will conflict with #12406
> VRT pixel functions: Handle NoData values

- doc/source/drivers/raster/vrt.rst
Manually wrap text to avoid horizontal scrolling.
Remove backticks that are not interpreted by the parser.
> Doc: Formatting fixes for pixel function table

- apps/gdalalg_raster_mosaic.cpp
- apps/gdalalg_raster_mosaic.h
- apps/gdalbuildvrt_lib.cpp
- autotest/utilities/test_gdalalg_raster_mosaic.py
- autotest/utilities/test_gdalbuildvrt_lib.py
- doc/source/drivers/raster/vrt.rst
- doc/source/programs/gdal_raster_mosaic.rst
- doc/source/programs/gdalbuildvrt.rst
- frmts/vrt/vrtdataset.cpp
- frmts/vrt/vrtdataset.h
- frmts/vrt/vrtderivedrasterband.cpp
- swig/include/python/gdal_python.i
Adds a `-pixel-function` argument to `gdalbuildvrt` and `gdal raster mosaic` to specify how overlapping inputs should be handled.
I don't think the name "pixel function" is especially descriptive, but it's been around for a while so people seem to know what it means. (Like VSI?)
Keeping this as draft for now because I want to figure out a better solution for non-contributing sources. The failing "min" test is a good illustration of the problem.
#11952
> BuildVRT: Support pixel functions

- apps/gdalalg_raster_calc.cpp
- autotest/cpp/test_gdal.cpp
- autotest/gdrivers/vrtderived.py
- autotest/utilities/test_gdalalg_raster_calc.py
- frmts/vrt/CMakeLists.txt
- frmts/vrt/pixelfunctions.cpp
- frmts/vrt/vrtdataset.h
- frmts/vrt/vrtderivedrasterband.cpp
- gcore/gdal_misc.cpp
- gcore/gdalsse_priv.h
- GDALDataTypeUnion(): adjust to avoid Byte + CInt32 to go to CFloat64
- VRTDerivedRasterBand::IRasterIO(): select a smaller source transfer type that the output buffer type if possible
- gdal raster calc: remove setting SourceTransferType (no longer needed since above commit)
- VRTDerivedRasterBand::IRasterIO(): do not zero/nodata initialize source buffer when not needed
-  VRT pixel function: optimize 'sum' for common data types
Summing two 20k x 20k Byte rasters,
with this PR:
```
|+--------------+--------------------+--------+
| Transfer type | VRTRasterBand type | timing |
|+--------------+------------------- + -------+
| Int16/UInt16  | Float32            | 1.4s   |
| Int32         | Float32            | 1.9s   |
| Int32         | Int32              | 2.5s   |
| Byte          | …
```
> VRTDerivedRaster: optimizations, in particular for sum(), and make 'gdal raster calc' use sum() when possible

- apps/gdalwarp_lib.cpp
- port/cpl_vsil_s3.cpp
- gdalwarp to format without Create() support: create temporary file with CPLGenerateTempFilenameSafe() instead in final directory (which might be /vsis3/)
- /vsis3/ with CPL_VSIL_USE_TEMP_FILE_FOR_RANDOM_WRITE=YES: unlink temporary file immediately after creation (on Unix)
Fixes https://lists.osgeo.org/pipermail/gdal-dev/2025-May/060584.html
> Enhance temporary file management when warping to COG on /vsis3/

- doc/source/conf.py
This PR rolls back the change added in https://github.com/OSGeo/gdal/pull/12315 as this broke incremental builds. 
I closed #12419 which attempted to exclude one of the indexes based on the build type. It was beoming overly complex with little benefit. 
The messages `index.rst: document is referenced in multiple toctrees: ['index', 'index_pdf'], selecting: index_pdf <- api/index` are `INFO` so not warnings. If they had been warnings, they could be silenced in `conf.py` using:
```
suppress_warnings = [
"toc.multiple_toc_parents",  # Suppresses "document is referenced in multiple toctrees"
]
```
cc @dbaston
> Docs: Revert dynamic exclude_patterns

- autotest/gcore/tiff_ovr.py
- frmts/vrt/vrtsources.cpp
- gcore/gdal.h
- gcore/overview.cpp
- gcore/rasterio.cpp
In GDALRegenerateOverviewsMultiBand() (ROMB), when too much memory would be needed for generating an overview block, the overviews are generated in a temporary file and then copied to the actual overview dataset. The size of this temporary file is not limited, and it has extra problems with pixel interleaved output, since the bands are copied one at a time for the full overview.
This issue was reported in issue #12303 and was partially addressed in #12307, which raised the allowable memory limit which triggers the problem code path, but did not limit the size of the temporary file or the pixel interleaved problems.
This PR addresses the remaining problems by chunking the output overview when possible, and using the temporary file path for a single chunk at a time.
#12303, #12307
To …
> GDALOverviews: Limit external file size in GDALRegenerateOverviewsMultiBand

- apps/gdaldem_lib.cpp
- autotest/utilities/test_gdaldem_lib.py
- gcore/gdalsse_priv.h
This also unifies and simplifies with the existing SSE2 optimization that worked on integer data type.
On https://rockyweb.usgs.gov/vdelivery/Datasets/Staged/Elevation/1m/Projects/WA_FEMAHQ_2018_D18/TIFF/USGS_1M_10_x56y512_WA_FEMAHQ_2018_D18.tif
master:
```
$ hyperfine --warmup 2 --  "time gdaldem hillshade USGS_1M_10_x56y512_WA_FEMAHQ_2018_D18.tif mem -of mem -q"
Benchmark #1: time gdaldem hillshade USGS_1M_10_x56y512_WA_FEMAHQ_2018_D18.tif mem -of mem -q
Time (mean ± σ):      4.379 s ±  0.257 s    [User: 4.186 s, System: 0.190 s]
Range (min … max):    4.079 s …  4.696 s
```
this PR:
```
$ hyperfine --warmup 2 --  "time gdaldem hillshade USGS_1M_10_x56y512_WA_FEMAHQ_2018_D18.tif mem -of mem -q"
Benchmark #1: time gdaldem hillshade USGS_1M_10_x56y512_WA_FEMAHQ_2018_D18.tif mem -of mem -q …
```
> hillshade: implement SSE2 optimization on Float32 input data type

- apps/gdal_translate_lib.cpp
- apps/gdaldem_lib.cpp
- autotest/utilities/test_gdalalg_raster_aspect.py
- autotest/utilities/test_gdalalg_raster_hillshade.py
- autotest/utilities/test_gdalalg_raster_roughness.py
- autotest/utilities/test_gdalalg_raster_slope.py
- frmts/mem/memdataset.cpp
- frmts/mem/memdataset.h
- gcore/gdal_misc.cpp
- gcore/gdal_priv.h
- gcore/gdaloverviewdataset.cpp
and hillshade: enable to use SSE2 implementation when using streaming dataset (previously was only used when outputing directly to final raster)
> gdaldem/gdal raster hillshade/slope/aspect/roughness/tpi/tri streaming: expose overviews if source has overviews

- apps/gdalalg_raster_edit.cpp
- apps/gdalalg_raster_edit.h
- autotest/utilities/test_gdalalg_raster_edit.py
- doc/source/programs/gdal_raster_edit.rst
- swig/include/python/gdal_python.i
Accepting both GCPs set by value, or pointing to a vector dataset
> gdal raster edit: add a --gcp option

- MIGRATION_GUIDE.TXT
- frmts/hfa/hfadataset.cpp
- frmts/hfa/hfadataset.h
- frmts/kea/kearat.cpp
- frmts/kea/kearat.h
- frmts/mrf/marfa_dataset.cpp
- gcore/gdal_rat.cpp
- gcore/gdal_rat.h
- gcore/gdalmultidim_rat.cpp
- ogr/ogrsf_frmts/openfilegdb/ogr_openfilegdb.h
Fixes a Coverity Scan warning in the HFA driver whose implementation of SetValue() delegates to ValuesIO(), but ignored the return code of this later function.
And MRF: fix Coverity Scan warnings about division by zero and "wrapper object use after free" (for papapoOverviewBands, false positive). CC @lucianpls
> Make GDALRasterAttributeTable::SetValue() methods return a CPLErr

- doc/source/api/python/mdim_api.rst
- swig/include/MultiDimensional.i
- swig/include/python/docs/gdal_mdm_docs.i
I added in titles to allow an automatic TOC for the page as it was easy to become lost on the page, and this allows users to quickly jump to a class. 
One question on the SWIG Python bindings - nearly all functions in `gdal.py` have the arguments `(self, *args)`, this is unlike the MapServer bindings which have arguments that mirror their C functions, e.g. `(self, postData, url)`. 
With the example of `CreateDimension` the function is fully documented in `gdalmultidim.cpp`:
```c++
std::shared_ptr<GDALDimension> GDALGroup::CreateDimension(
CPL_UNUSED const std::string &osName, CPL_UNUSED const std::string &osType,
CPL_UNUSED const std::string &osDirection, CPL_UNUSED GUInt64 nSize,
CPL_UNUSED CSLConstList papszOptions)
{
CPLError(CE_Failure, CPLE_NotSupported,
"CreateDimension() not …
```
> Document 2 more Multi-dimensional array API Python Functions

- cmake/helpers/GdalCompilationFlags.cmake
Enable parallel compilation with MSVC, making the build faster on most multi-core machines.
While projects do run in parallel if there are CPUs available, some projects (alg, appslib, ogr) have a lot of files that need to be compiled and take much longer to complete than drivers. This makes the gdal build time much longer than it needs to be.
On a 16 core desktop, this makes a simple gdal compilation finish in 1m40s from 3m52s. Similar results on a 6core laptop, going from 10m20s to 7m10s.
* OS: Windows
* Compiler: MSVC
> MSVC build: Add parallel compile option

- apps/gdalalg_raster_mosaic.cpp
- autotest/utilities/test_gdalalg_raster_mosaic.py
- frmts/vrt/vrtdataset.h
- frmts/vrt/vrtderivedrasterband.cpp
- gcore/gdalalgorithm.cpp
CC @dbaston 
```
$ gdal raster mosaic --pixel-function=<TAB<>TAB>
cmul                dB2amp              exp                 imag                inv                 median              mul                 pow                 scale
complex             dB2pow              expression          intensity           log10               min                 norm_diff           real                sqrt
conj                diff                geometric_mean      interpolate_exp     max                 mod                 phase               reclassify          sum
dB                  div                 harmonic_mean       interpolate_linear  mean                mode                polar               replace_nodata
$ gdal raster mosaic --pixel-function=median --pixel-function-arg=<TAB>
==>
$ gdal …
```
> gdal raster mosaic: add completion/choices for --pixel-function and --pixel-function--arg

- swig/python/setup.py.in
Build error:
```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -O3 -fPIC -O3 -I/Users/mkuhn/dev/vcpkg/vcpkg/buildtrees/gdal/arm64-osx-dynamic-rel/port -I/Users/mkuhn/dev/vcpkg/vcpkg/buildtrees/gdal/src/v3.11.0-0688d3c8f1.clean/port -I/Users/mkuhn/dev/vcpkg/vcpkg/buildtrees/gdal/arm64-osx-dynamic-rel/gcore -I/Users/mkuhn/dev/vcpkg/vcpkg/buildtrees/gdal/src/v3.11.0-0688d3c8f1.clean/gcore -I/Users/mkuhn/dev/vcpkg/vcpkg/buildtrees/gdal/src/v3.11.0-0688d3c8f1.clean/alg -I/Users/mkuhn/dev/vcpkg/vcpkg/buildtrees/gdal/src/v3.11.0-0688d3c8f1.clean/ogr/ -I/Users/mkuhn/dev/vcpkg/vcpkg/buildtrees/gdal/src/v3.11.0-0688d3c8f1.clean/ogr/ogrsf_frmts -I/Users/mkuhn/dev/vcpkg/vcpkg/buildtrees/gdal/src/v3.11.0-0688d3c8f1.clean/g …
```
> Add -isysroot when building py bindings (macos)

- swig/python/setup.py.in
Backport #12533
**Authored by:** @m-kuhn
> [Backport release/3.11] Add -isysroot when building py bindings (macos)

- autotest/gcore/numpy_rw.py
- swig/include/gdal_array.i
Don't promote a boolean array to float64 when trying to write the data
Fix a performance issue when writing out a numpy array of booleans. With this change, saving out a 6000x6000 array to a geotiff is now 66% faster! Memory savings is also useful.
> Add np.bool to map of gdal codes

- autotest/gdrivers/jpeg.py
- frmts/jpeg/jpgdataset.cpp
Fix missing `FLIR` subdomain when reading the relative humidity of the FLIR metadata.
* OS:
* Compiler:
> Fix subdomain of FLIR metadata

- port/cpl_vsi_mem.cpp
`VSIGetMemFileBuffer` prints a debug message if called on a file with borrowed data, so let's clarify that you're not supposed to use it that way.
* OS:
* Compiler:
> vsimem: clarify `bUnlinkAndSeize` docs

- apps/data/ogrinfo_output.schema.json
- apps/gdalalg_vector_info.cpp
- apps/gdalalg_vector_info.h
- apps/ogrinfo_lib.cpp
- autotest/utilities/test_gdalalg_vector_info.py
- doc/source/programs/gdal_vector_info.rst
- ogr/ogrsf_frmts/sqlite/ogrsqlitelayer.cpp
The default format with cli is json, this was implicitly setting -al.
The old behavior is kept for ogrinfo while gdal vector info requires -al.
Fix #12510
> [cli] gdal vector info do not implicitly set -al with -json

- ogr/ogrsf_frmts/lvbag/CMakeLists.txt
- ogr/ogrsf_frmts/lvbag/ogrlvbagdatasource.cpp
- ogr/ogrsf_frmts/lvbag/ogrlvbagdriver.cpp
- ogr/ogrsf_frmts/lvbag/ogrlvbaglayer.cpp
This removes the warning compiler flags set in #12563. It also improves code style by using brackets for all statement blocks.
> Remove compiler flags as defined in #12563

- doc/source/drivers/vector/filegdb.rst
Updates a dead link in the documentation for the ESRI File Geodatabase driver.
The docs previously directed individuals to an old ESRI download page, however according to an [ESRI Blog](https://www.esri.com/arcgis-blog/products/developers/data-management/guide-to-the-file-geodatabase-api) the official place to download it from now is directly from their GitHub repo.
N/A
N/A
* OS: N/A
* Compiler: N/A
> FileGDB Docs: fixed dead link for ESRI download

- doc/source/drivers/vector/filegdb.rst
Backport #12579
**Authored by:** @trodaway
> [Backport release/3.11] FileGDB Docs: fixed dead link for ESRI download

- autotest/ogr/ogr_fielddomain.py
- autotest/ogr/ogr_openfilegdb_write.py
- autotest/ogr/ogr_parquet.py
- ogr/ogrsf_frmts/openfilegdb/filegdb_fielddomain.h
- swig/include/Dataset.i
- swig/include/ogr.i
- swig/include/python/typemaps_python.i
> Python bindings: fix issues with None bounds for ogr.CreateRangeFieldDomain() and ogr.CreateRangeFieldDomainDateTime()

- autotest/ogr/ogr_fielddomain.py
- autotest/ogr/ogr_openfilegdb_write.py
- autotest/ogr/ogr_parquet.py
- ogr/ogrsf_frmts/openfilegdb/filegdb_fielddomain.h
- swig/include/Dataset.i
- swig/include/ogr.i
- swig/include/python/typemaps_python.i
> [Backport release/3.11] Python bindings: fix issues with None bounds for ogr.CreateRangeFieldDomain() and ogr.CreateRangeFieldDomainDateTime()

- frmts/ecw/ecwdataset.cpp
- gcore/gdal_priv_templates.hpp
Fix for https://trac.osgeo.org/osgeo4w/ticket/883
Fixes build errors:
```
FAILED: alg/CMakeFiles/alg.dir/gdalrasterize.cpp.obj
C:\src\osgeo4w\scripts\vs2022\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\cl.exe  /nologo /TP -DGDAL_COMPILATION -DHAVE_AVX_AT_COMPILE_TIME -DHAVE_GEOS=1 -DHAVE_SSE_AT_COMPILE_TIME -DHAVE_SSSE3_AT_COMPILE_TIME -DINTERNAL_QHULL -DNOMINMAX -D_CRT_NONSTDC_NO_DEPRECATE -D_CRT_SECURE_NO_DEPRECATE -IC:\src\osgeo4w\src\gdal-dev\gdal\apps -IC:\src\osgeo4w\src\gdal-dev\gdal\alg -IC:\src\osgeo4w\src\gdal-dev\gdal\gcore -IC:\src\osgeo4w\src\gdal-dev\osgeo4w\build\gcore -IC:\src\osgeo4w\src\gdal-dev\gdal\port -IC:\src\osgeo4w\src\gdal-dev\osgeo4w\build\port -IC:\src\osgeo4w\src\gdal-dev\gdal\ogr -IC:\src\osgeo4w\src\gdal-dev\gdal\ogr\ogrsf_frmts …
```
> Fix osgeo4w gdal-dev

- ogr/ogrgeometry.cpp
- swig/include/python/docs/ogr_geometry_docs.i
Fixes the description of the return value of `OGRGeometry::IsRing()`, consistent with https://libgeos.org/doxygen/group__prop.html#gabaeb1320a591615a4907cc6929f42e15
> Doc: fix description of the return value for OGRGeometry::IsRing()

- autotest/ogr/data/dxf/byblock-bylayer-new.dxf
- autotest/ogr/ogr_dxf.py
- ogr/ogrsf_frmts/dxf/ogrdxf_feature.cpp
The logic involved in computing the correct color for entities generated by INSERTs (block references) for DXF files is complex, because of:
* special color values (ByBlock/ByLayer) that create a kind of inheritance structure for color
* the magical layer 0 which behaves specially when used with these special color values
There were a number of lingering issues in GDAL's implementation of this logic which have been resolved in this commit.
I believe this commit correctly addresses all possible cases for 2 levels of block nesting (blocks within blocks). A comprehensive test case, with 818 entities when fully exploded, is included.
It is not clear whether the logic in this commit extends correctly to 3+ levels of nesting. This has not been tested. However, based on real-world experience …
> DXF: further refine ByBlock and ByLayer color handling

- autotest/cpp/CMakeLists.txt
- autotest/cpp/test_gdal.cpp
- autotest/gcore/band_arithmetic.py
- autotest/gcore/basic_test.py
- autotest/gdrivers/vrtderived.py
- doc/source/api/gdalrasterband_cpp.rst
- doc/source/drivers/raster/vrt.rst
- doc/source/spelling_wordlist.txt
- doc/source/user/band_algebra.rst
- doc/source/user/index.rst
- frmts/gtiff/gt_jpeg_copy.cpp
- frmts/gtiff/gt_overview.cpp
- frmts/gtiff/gtiffdataset.cpp
- frmts/gtiff/gtiffdataset_write.cpp
- frmts/vrt/pixelfunctions.cpp
- frmts/vrt/vrtdataset.cpp
- frmts/vrt/vrtdataset.h
- frmts/vrt/vrtderivedrasterband.cpp
- frmts/vrt/vrtdriver.cpp
- frmts/vrt/vrtsources.cpp
- gcore/CMakeLists.txt
- gcore/gdal.h
- gcore/gdal_fwd.h
- gcore/gdal_priv.h
- gcore/gdalcomputedrasterband.cpp
- gcore/gdalrasterband.cpp
- swig/include/Band.i
- swig/include/gdal.i
- swig/include/gdal_array.i
- swig/include/python/gdal_python.i
Documentation in https://gdal--12507.org.readthedocs.build/en/12507/user/band_algebra.html
Uses VRTDerivedRasterBand and pixel functions underneath.
Demo program converting a RGB image to grey level:
- Python:
```python
from osgeo import gdal
gdal.UseExceptions()
with gdal.Open("rgbsmall.tif") as ds:
R = ds.GetRasterBand(1)
G = ds.GetRasterBand(2)
B = ds.GetRasterBand(3)
greylevel = (0.299 * R + 0.587 * G + 0.114 * B).astype(gdal.GDT_Byte)
gdal.GetDriverByName("GTiff").CreateCopy("greylevel.tif", greylevel)
```
- C++:
```cpp
#include <gdal_priv.h>
int main()
{
GDALAllRegister();
auto poDS = std::unique_ptr<GDALDataset>(GDALDataset::Open("rgbsmall.tif"));
auto& R = *(poDS->GetRasterBand(1));
auto& G = *(poDS->GetRasterBand(2));
auto& B = *(poDS->GetRasterBand(3));
auto greylevel = (0.299 * …
```
> GDALRasterBand: define +, -, *, /, AsType(), gdal::min()/max() to perform band lazy-evaluated arithmetics from C++, C and SWIG (Python)

- autotest/gdrivers/vrtderived.py
- doc/source/drivers/raster/vrt.rst
- frmts/vrt/pixelfunctions.cpp
- frmts/vrt/vrtdataset.h
- frmts/vrt/vrtderivedrasterband.cpp
Enables expressions such as the one shown in the example here: https://usdaforestservice.github.io/gdalraster/reference/calc.html#ref-examples
> VRTDerivedBand expressions: Add _CENTER_X_ and _CENTER_Y_ built-in variables

- doc/source/glossary.rst
- doc/source/index.rst
- doc/source/programs/gdal_raster_color_map.rst
- doc/source/programs/gdal_raster_color_merge.rst
- doc/source/spelling_wordlist.txt
- doc/source/tutorials/gdal_grid_tut.rst
- doc/source/tutorials/geotransforms_tut.rst
- doc/source/user/raster_data_model.rst
The GDAL docs contain a lot of abbreviations and technical terms. A glossary defining these terms and abbreviations could be of use to a reader. 
This PR adds a glossary page to the GDAL docs, with an example link, as a starting point for discussions to see if this would be a good idea to include and expand upon. 
The glossary uses the standard Sphinx glossary approach, similar to MapServer https://mapserver.org/glossary.html
Terms can link to the glossary using the following syntax. An example is included in this PR. 
```
:term:`EPSG`
```
There is an OSGeo Lexicon mailing list that was looking to "Coordinate definitions for terminology used within the OSGeo context" - https://lists.osgeo.org/mailman/listinfo/lexicon. I've emailed the list to see if there are any definition datasets that …
> Add a glossary and example link

- doc/source/drivers/vector/dxf.rst
Fixes links to external web pages about $INSUNITS, $MEASUREMENT and AutoCAD 2000 DXF Reference in https://gdal.org/en/latest/drivers/vector/dxf.html
* OS:
* Compiler:
> DXF: Fix links to external resources in docs

- autotest/gcore/vsizip.py
- port/cpl_vsi_virtual.h
- port/cpl_vsil_abstract_archive.cpp
- port/cpl_vsil_gzip.cpp
- port/cpl_vsil_libarchive.cpp
- port/cpl_vsil_tar.cpp
> [Backport release/3.11] /vsizip/ / /vsitar/: make it respect bSetError / VSI_STAT_SET_ERROR_FLAG flag, in particular when used with /vsicurl/

- port/cpl_conv.cpp
> [Backport release/3.11] Fix build with libcxx 19.1.7 on OpenBSD

- apps/data/gdalinfo_output.schema.json
- apps/gdalinfo_lib.cpp
- autotest/gdrivers/rraster.py
- autotest/utilities/test_gdalinfo.py
- autotest/utilities/test_gdalinfo_lib.py
Fixes https://lists.osgeo.org/pipermail/gdal-dev/2025-June/060666.html
> gdalinfo JSON output: attach 'rat' object to 'band', and add missing elements in gdalinfo_output.schema.json

- apps/gdalinfo_lib.cpp
- autotest/utilities/test_gdalinfo_lib.py
> [Backport release/3.11] gdalinfo JSON output: return integer nodata value of integer bands as integer

- apps/data/gdalinfo_output.schema.json
- apps/gdalinfo_lib.cpp
- autotest/gdrivers/rraster.py
- autotest/utilities/test_gdalinfo.py
- autotest/utilities/test_gdalinfo_lib.py
> [Backport release/3.11] gdalinfo JSON output: attach 'rat' object to 'band', and add missing elements in gdalinfo_output.schema.json

- autotest/ogr/ogr_adbc.py
- ogr/ogrsf_frmts/adbc/ogradbcdataset.cpp
- ogr/ogrsf_frmts/adbc/ogradbcdrivercore.cpp
Implement a minimal loading function for DuckDB when ADBC driver manager is not available.
The implementation is based on ADBC's code; call `dlopen()` and `dlsym()` (on non-Windows platforms).
- https://github.com/apache/arrow-adbc/blob/bbf3389e0616fe51105001d4ad06f9a360c86da7/c/driver_manager/adbc_driver_manager.cc#L1661-L1717
- https://github.com/apache/arrow-adbc/blob/bbf3389e0616fe51105001d4ad06f9a360c86da7/c/driver_manager/adbc_driver_manager.cc#L174
- https://github.com/apache/arrow-adbc/blob/bbf3389e0616fe51105001d4ad06f9a360c86da7/c/driver_manager/adbc_driver_manager.cc#L225
Close #12631 
* OS: macOS 15.5
* Compiler: Apple clang 17.0.0
> Implement a minimal loading function for DuckDB

- apps/gdalalg_raster_overview_add.cpp
- apps/gdalalg_raster_overview_add.h
- autotest/utilities/test_gdalalg_raster_overview.py
- doc/source/programs/gdal_raster_overview_add.rst
- frmts/gtiff/gt_overview.cpp
- frmts/gtiff/gt_overview.h
- frmts/gtiff/gtiffdataset.h
- frmts/gtiff/gtiffdataset_write.cpp
- frmts/mrf/marfa.h
- gcore/gdal_priv.h
- gcore/gdaldataset.cpp
- gcore/gdaldefaultoverviews.cpp
to add specified input raster datasets as overviews of the target dataset.
Source overviews may come from any GDAL supported format, provided they
have the same number of bands and geospatial extent than the target
dataset.
That mode is currently only implemented when the target dataset is in
GeoTIFF format, or when using :option:`--external`.
.. example::
:title: Add 3 existing datasets at scale 1:25K, 1:50K and 1:100K as overviews of :file:`my.tif`.
.. code-block:: bash
gdal raster overview add --overview-src ovr_25k.tif --overview-src ovr_50k.tif --overview-src ovr_100k.tif --dataset my.tif
Fixes #12614
> gdal raster overview add: add a --overview-src option

- ogr/ogrsf_frmts/sqlite/sqlite_rtree_bulk_load/sqlite_rtree_bulk_load.c
`<math.h>` doesn't transitively include `<stdlib.h>` anymore in llvm near upstream head.
Caused by this commit:
https://github.com/llvm/llvm-project/commit/584cc376870505821b5ff0b0e80be85ee563ff0c
> [libc++] Move std::abs into __math/abs.h (https://github.com/llvm/llvm-project/pull/139586)
>
> `template <class = int>` is also added to our implementations to avoid an ambiguity between the libc's version and our version when both are visible.
> 
> This avoids including `<stdlib.h>` in `<math.h>`.
> sqlite_rtree_bulk_load.c: include <stdlib.h>

- autotest/gcore/basic_test.py
- doc/source/spelling_wordlist.txt
- swig/include/python/gdal_python.i
Add block window iterator to Python `Band` object. I couldn't decide between returning a tuple (which can be unpacked directly into `ReadAsArray`) or a custom type with members for `xoff`, `xsize`, etc. Ended up returning a type that behaves both ways. Maybe this is inadvisable for some reason.
> Python bindings: Add Band.BlockWindows()

- autotest/gdrivers/heif.py
- cmake/helpers/CheckDependentLibraries.cmake
- CMake: fix LIBHEIF_SUPPORTS_TILES check when the include directory is not a system path
- heif.py: fix network test
> HEIF fixes

- ogr/ogrsf_frmts/s57/s57.h
- ogr/ogrsf_frmts/s57/s57reader.cpp
Fixes https://issues.oss-fuzz.com/issues/428506175
> S57: fix nullptr dereference on invalid dataset when GDAL_DATA not set

- autotest/cpp/test_ogr.cpp
- ogr/ogrutils.cpp
Fixes https://lists.osgeo.org/pipermail/gdal-dev/2025-June/060685.html
> OGRParseDate(): do not round second=59.999999 to 60.0 but 59.999

- autotest/gcore/vsizip.py
- frmts/georaster/cpl_vsil_ocilob.cpp
- port/cpl_vsil_gzip.cpp
- port/cpl_vsil_libarchive.cpp
- port/cpl_vsil_sparsefile.cpp
- port/cpl_vsil_unix_stdio_64.cpp
- port/cpl_vsil_win32.cpp
> [Backport release/3.11] /vsizip/: fix memory leak when opening a SOZip-enabled file

- doc/source/programs/gdal_raster_clean_collar.rst
fix some typos in gdal raster clean-collar docs.
it should be **--add-alpha** and **--add-mask** instead of **--addalpha** and **--addmask**
> fix typo in clean-collar docs

- autotest/gdrivers/png.py
- doc/source/drivers/raster/png.rst
- frmts/png/pngdataset.cpp
> PNG: implement read/write support for background color through 'BACKGROUND_COLOR' dataset metadata item

- swig/java/CMakeLists.txt
Restore -fno-strict-aliasing to the java swig bindings, it was dropped again at some time point in the cmake transition. It's still recommended by swig documentation to have this flag.
https://swig.org//Doc4.3/Java.html#Java_compiling_dynamic
https://bugs.gentoo.org/948810
* OS: Gentoo Linux amd64
* Compiler: gcc (Gentoo 15.1.1_p20250705-r1 p2) 15.1.1 20250705
> CMake Java: restore -fno-strict-aliasing

- apps/gdal_footprint_lib.cpp
Fixes #12724
(I couldn't come up with a test case to reproduce the situation of the initial issue)
> gdal_footprint: fail if there is a simplification error and there is a single input feature

- autotest/gdrivers/zarr_driver.py
- frmts/zarr/zarr.h
- frmts/zarr/zarr_group.cpp
- frmts/zarr/zarr_v2_array.cpp
- frmts/zarr/zarr_v2_group.cpp
- frmts/zarr/zarr_v3_array.cpp
- frmts/zarr/zarr_v3_group.cpp
- frmts/zarr/zarrdriver.cpp
- port/cpl_json.cpp
and fix creating a /vsizip/ file
Fixes #12790
>  Zarr: make GDALDataset::Close() report errors when write failure occurs

- alg/gdalwarpoperation.cpp
- apps/gdalwarp_lib.cpp
> [Backport release/3.11] gdalwarp: for TPS warping, use -wo SOURCE_EXTRA=5 by default

- autotest/gcore/nodatamaskband.py
- gcore/gdalnodatamaskband.cpp
Fixes regression introduced by 93703e7d6a201807c48bd0951359457c75fcf028
> GDALNoDataMaskBand::IRasterIO(): fix corruption when reading from Byte band and nLineSpace > nBufXSize (3.10.0 regression)

- apps/CMakeLists.txt
- apps/gdalalg_vector.cpp
- apps/gdalalg_vector_clean_coverage.cpp
- apps/gdalalg_vector_clean_coverage.h
- apps/gdalalg_vector_pipeline.cpp
- autotest/utilities/test_gdalalg_vector_clean_coverage.py
- doc/source/conf.py
- doc/source/programs/gdal_vector_clean_coverage.rst
- doc/source/programs/index.rst
Adds a pipeline step to clean a polygonal coverage. Could also see an argument for combining with with `gdal vector make-valid`.
> Add gdal vector clean-coverage

- autotest/gdrivers/netcdf.py
- frmts/netcdf/netcdfdataset.cpp
> [Backport release/3.11] netCDF: make LIST_ALL_ARRAYS=YES work on datasets that have no 2D array

- autotest/gcore/nodatamaskband.py
- gcore/gdalnodatamaskband.cpp
> [Backport release/3.11] GDALNoDataMaskBand::IRasterIO(): fix corruption when reading from Byte band and nLineSpace > nBufXSize (3.10.0 regression)

- autotest/cpp/CMakeLists.txt
Handle both -D_FORTIFY_SOURCE=2 and -Wp,-D_FORTIFY_SOURCE=2 variants when removing FORTIFY_SOURCE flags for unit test compilation with -O0.
Fixes a CMake compilation error that occurs when building GDAL unit tests on systems using hardened compiler flags with the `-Wp,-D_FORTIFY_SOURCE=2` format.
The existing code in `autotest/cpp/CMakeLists.txt` only removes the `-D_FORTIFY_SOURCE=2` variant when compiling unit tests with `-O0` optimization, but doesn't handle the `-Wp,-D_FORTIFY_SOURCE=2` variant used by modern hardened build environments. This leaves dangling `-Wp,` prefixes that cause compilation to fail with "too many filenames" errors.
The fix adds string replacement for both variants to ensure clean flag removal.
Fixes #12840
* OS: Amazon …
> Fix CMake compilation with -Wp,-D_FORTIFY_SOURCE=2 flags

- .github/workflows/ubuntu_24.04/Dockerfile.ci
- ogr/ogrsf_frmts/mongodbv3/mongocxxv3_headers.h
- ogr/ogrsf_frmts/mongodbv3/ogrmongodbv3driver.cpp
Fix api incompatibilities with >=mongo-cpp-driver-4.
https://www.mongodb.com/docs/languages/cpp/cpp-driver/current/upgrade/#api-breaking-changes-in-v4.0
k_string is available as far back as 3.7, but I think its simpler to just check if the version is higher than 4.
* OS: Gentoo Linux amd64
* Compiler: gcc (Gentoo 15.1.1_p20250705-r1 p2) 15.1.1 20250705
> MongoDB: compatibility with >=mongo-cpp-driver-4

- ogr/ogrsf_frmts/oci/ogrociwritablelayer.cpp
To fix the error  "ORA-12899: value too large for column ..." when loading vector data to DB.
N/A
* OS:
* Compiler:
> Set the varchar2 type length to be "CHAR" instead of the default "BYTE"

- ogr/ogrsf_frmts/oci/ogrociwritablelayer.cpp
Backport #12848
**Authored by:** @fechen123
> [Backport release/3.11] Set the varchar2 type length to be "CHAR" instead of the default "BYTE"

- gcore/gdaldataset.cpp
- gcore/gdaljp2metadata.cpp
Why?
- Slightly more readable with the form `std::min({a, b, c, ...}`
- Slightly better performance for non-optimized builds
An example to play with: https://godbolt.org/z/sKfTMz6GE
Spotted reviewing https://github.com/OSGeo/gdal/commit/ac95cad0fc09b71b39756fd85b7791523b284a6e / https://github.com/OSGeo/gdal/pull/12814
It's a C++11 feature, so safe to do: https://en.cppreference.com/w/cpp/algorithm/min.html
> gcore: Use initializer list for min or max of more than 2 numbers.

- autotest/gcore/rat.py
- gcore/gdal_rat.cpp
- swig/include/gdal_array.i
Prevent `GDALRasterAttributeTable::ValuesIO` from accessing incorrect locations whenever `iStartRow` is nonzero.
> RAT: Avoid invalid memory access in ValuesIO

- .github/workflows/cmake_builds.yml
- autotest/alg/warp.py
- autotest/gcore/test_driver_metadata.py
- autotest/gcore/transformer.py
- autotest/gcore/vsifile.py
- autotest/pymod/xmlvalidate.py
otherwise when running pytest autotest/gcore, a segmentation fault within libxml2 occurs when python exits:
```
Results (533.34s (0:08:53)):
2825 passed
5 xfailed
1977 skipped
Thread 1 received signal SIGSEGV, Segmentation fault.
0x00007ffdd7a749e6 in ntdll!RtlWaitOnAddress () from C:\WINDOWS\SYSTEM32\ntdll.dll
(gdb) bt
#0  0x00007ffdd7a749e6 in ntdll!RtlWaitOnAddress () from C:\WINDOWS\SYSTEM32\ntdll.dll
#1  0x00007ffdd7a3fcb4 in ntdll!RtlEnterCriticalSection () from C:\WINDOWS\SYSTEM32\ntdll.dll
#2  0x00007ffdd7a3fae2 in ntdll!RtlEnterCriticalSection () from C:\WINDOWS\SYSTEM32\ntdll.dll
#3  0x00007ffda5703a1f in ?? () from C:\dev\msys64\mingw64\bin\libxml2-16.dll
#4  0x00007ffda570b038 in ?? () from C:\dev\msys64\mingw64\bin\libxml2-16.dll
#5  0x00007ffda5731586 in ?? () from …
```
> autotest: allow to run test suite without lxml to avoid crashes on mingw64

- cmake/modules/packages/FindMSSQL_ODBC.cmake
- doc/source/development/building_from_source.rst
Adds version 18 of the [Microsoft ODBC Driver 18 for SQL Server](https://go.microsoft.com/fwlink/?linkid=2307162) to the CMake module, which searches for libraries in common locations such as `C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\180` 
Related build docs also updated.
> Add v18 of Microsoft ODBC Driver for SQL Server to CMake module

- swig/include/Band.i
- swig/include/java/gdal_java.i
- swig/java/CMakeLists.txt
- swig/java/apps/GDALClose.java
> [Backport release/3.11] Java bindings: avoid double free with Band.GetDataset().Close()

- autotest/gdrivers/jpeg.py
- frmts/jpeg/jpgdataset.cpp
- some metadata domains were not reported
- looking for EXIF metadata and not finding any would populate the default metadata domain with an empty list
Fixes https://lists.osgeo.org/pipermail/gdal-dev/2025-August/060826.html
> JPEG: fix GetMetadataDomainList()

- autotest/gdrivers/netcdf.py
> netcdf.py: Remove trailing `_` from test_arbitrary_3Daxis_order_

- frmts/aaigrid/aaigriddataset.cpp
- frmts/cals/calsdataset.cpp
- frmts/rcm/rcmdataset.cpp
- frmts/vrt/vrtrawrasterband.cpp
- frmts/wms/minidriver_tiled_wms.cpp
- frmts/xyz/xyzdataset.cpp
- ogr/ogrsf_frmts/pg/ogrpgdatasource.cpp
- port/cpl_string.h
Avoid misuses such that the one in the RCM driver
> CPLString / CPLStringList: do not allow implicit cast to void*

- gcore/gdaldataset.cpp
> [Backport release/3.11] GDALAntiRecursionStruct: fix so that a std::map doesn't increase out of control

- autotest/ogr/data/gml_jpfgd/ElevPt_JGD2024.xml
- autotest/ogr/ogr_gml_fgd_read.py
- ogr/ogrsf_frmts/gml/ogrgmldatasource.cpp
- ogr/ogrsf_frmts/gmlutils/gmlutils.cpp
- ogr/ogrspatialreference.cpp
> [Backport release/3.11] GML: takes into account JGD2024 CRS from recent Japan's Fundamental Geospatial Data (FGD)

- apps/gdal_translate_lib.cpp
- apps/gdalwarp_lib.cpp
- autotest/cpp/test_cpl.cpp
- autotest/gdrivers/isis.py
- autotest/gdrivers/pds4.py
- doc/source/drivers/raster/isis3.rst
- doc/source/drivers/raster/pds4.rst
- doc/source/user/configoptions.rst
- frmts/pds/isis3dataset.cpp
- frmts/pds/pds4dataset.cpp
- frmts/pds/pds4dataset.h
- frmts/pds/pdsdrivercore.cpp
- port/cpl_conv.h
- port/cpl_known_config_options.h
- port/cpl_path.cpp
*  ISIS3: adds a _data member in json:ISIS3 metadata
that contains the offline content as hexadecimal encoded.
```
"Table_SecondTable": {
"Bytes": 5,
"Name": "SecondTable",
"StartByte": 1,
"_container_name": "Table",
"^Table": "in.bin",
"_data": "0102030405",
"_type": "object",
}
```
Adds two open options:
- INCLUDE_OFFLINE_CONTENT=YES/NO: Whether to include a _data member in
json:ISIS3 metadata with offline content of label objects. Defaults to
YES
- MAX_SIZE_OFFLINE_CONTENT=<int>: Maximum size of offline content to
include in _data member, in bytes. Defaults to 100,000,000
*   ISIS3 -> PDS4 GeoTIFF: propagate json:ISIS3 metadata
Add a PROPAGATE_SRC_METADATA=YES/NO (default YES) creation option to the
PDS4 driver to control this.
*   gdal_translate/gdalwarp: add a GDALHistory section to …
> ISIS3 metadata enhancements

- frmts/jp2kak/jp2kakdataset.h
This static method was removed in 443ad2010bcb4639c324958fc2db16a8ed639341
> jp2kakdataset.h: Remove JP2KAKDataset::Identify

- alg/gdaltransformer.cpp
- apps/gdalwarp_lib.cpp
- autotest/utilities/test_gdalwarp_lib.py
> [Backport release/3.11] Warping: avoid inserting CENTER_LONG when warping whole >=360 longitude range to WebMercator

- cmake/helpers/GdalSwigBindings.cmake
- swig/python/CMakeLists.txt
Fixes #13033
@geographika Can you give a try at that? I didn't really try to reproduce your issue, but yesterday I managed to build in my Windows VM. But inspecting the rules I spotted a dependency issue that could potentially cause a file to be concurrently read and write.
> CMake: avoid potential dependency problem when building Python bindings

- autotest/gcore/vsis3.py
- doc/source/user/configoptions.rst
- doc/source/user/virtual_file_systems.rst
- port/cpl_http.cpp
- port/cpl_known_config_options.h
- port/cpl_vsil_s3.cpp
> /vsis3/ (and /vsigs/, /vsiaz/, etc.): by default squash '/./' and '/../' sequences in path, unless the GDAL_HTTP_PATH_VERBATIM config option is set

- autotest/gcore/cog.py
- frmts/gtiff/cogdriver.cpp
- frmts/gtiff/gtiffdataset.cpp
- frmts/gtiff/gtiffdataset_read.cpp
- frmts/gtiff/gtiffdataset_write.cpp
Fixes #13014
```
$ gdal_translate byte.tif cog.tif -outsize 1024 0 -of COG -co OVERVIEW_RESAMPLING=AVERAGE
$ gdalinfo cog.tif
[...]
Image Structure Metadata:
LAYOUT=COG
COMPRESSION=LZW
INTERLEAVE=BAND
OVERVIEW_RESAMPLING=AVERAGE
[...]
$ exiftool -j cog.tif | jq '.[0].GDALMetadata'
"<GDALMetadata>\n  <Item name=\"OVERVIEW_RESAMPLING\" domain=\"IMAGE_STRUCTURE\">AVERAGE</Item>\n</GDALMetadata>\n"
```
> COG: write OVERVIEW_RESAMPLING in IMAGE_STRUCTURE metadata domain, and expose it when present

- frmts/miramon/miramon_band.cpp
Fixes the issue 445248683 from fuzzer where the name of the band was searched in the particular section [ATTRIBUTE_DATA:name] **or** in [ATTRIBUTE_DATA] section. This name has not to be found in [ATTRIBUTE_DATA] section. 
Note: Ignore the name of the fork where this PR comes, it's because I am improving palette stuff. I only commit the appropiated file.
https://issues.oss-fuzz.com/issues/445248683
> MiraMonRaster: searching NomFitxer in the appropiate place

- apps/gdalinfo_lib.cpp
- autotest/utilities/test_gdalinfo_lib.py
> GDALInfo(): fix crash on datasets not linked to a driver

- autotest/ogr/ogr_mitab.py
- ogr/ogr_featurestyle.h
- ogr/ogrfeaturestyle.cpp
- ogr/ogrsf_frmts/mitab/mitab_feature.cpp
> [Backport release/3.11] MapInfo .tab: fix support of px vs pt for pen width, including fractional point width

- doc/source/tutorials/vector_geoparquet_tut.rst
Test the Parquet tutorial with new GDAL release, and update to work with new version of Overture data.
It seems as though the data links will expire every 2 months - https://docs.overturemaps.org/release-calendar/#data-retention-policy, and there doesn't seem to be a permanent alias such as "main" that could be used for the URLs.
Other minor changes are that info output defaults to text, unless ` -f json` is used. 
I did get an error when running the following command:
```console
gdal vector filter `
--input "PARQUET:/vsis3/overturemaps-us-west-2/release/2025-09-24.0/theme=divisions/type=division_area/" `
--where "country='BA' AND subtype='county'" `
--output counties.parquet
```
Rerunning it worked but I got a warning:
```
```
I'm not sure if these should be documented in the tutorial, …
> Doc: Add note about Overture data retention and test in GDAL 3.11.4

- doc/source/development/rfc/index.rst
- doc/source/development/rfc/rfc109_gdal_cpp_api.rst
==> [Rendered view](https://gdal--13071.org.readthedocs.build/en/13071/development/rfc/rfc109_gdal_cpp_api.html)
> Add RFC 109 text: Split of gdal_priv.h and addition of public C++ headers

- autotest/utilities/test_gdalalg_raster_clip.py
- gcore/gdalalgorithm.cpp
> Make 'gdal raster/vector clip' work with --like dataset being a PostgreSQL (vector) dataset

- apps/gdalalg_abstract_pipeline.cpp
- apps/gdalalg_abstract_pipeline.h
- apps/gdalalg_vector_change_field_type.cpp
- apps/gdalalg_vector_change_field_type.h
- autotest/ogr/ogr_csv.py
- autotest/ogr/ogr_geojson.py
- autotest/ogr/ogr_sqlite.py
- autotest/utilities/test_gdalalg_vector_change_field_type.py
- frmts/xyz/xyzdataset.cpp
- ogr/data/ogr_fields_override.schema.json
- ogr/ogr_schema_override.cpp
- ogr/ogr_schema_override.h
- ogr/ogrsf_frmts/csv/ogrcsvdatasource.cpp
- ogr/ogrsf_frmts/geojson/ogrgeojsondatasource.cpp
- ogr/ogrsf_frmts/gml/ogrgmldatasource.cpp
- ogr/ogrsf_frmts/sqlite/ogrsqlitedatasource.cpp
For pipelines like ``read test.csv ! change-field-type --src-field-type String --field-type Date ! change-field-type --field-name int --field-type Integer64 ! ...`, translate the change-field-type content as a OGR_SCHEMA open option for drivers that support it
(@elpaso what we discussed recently)
> Pipeline: merge change-field-type steps immediately following open to create a OGR_SCHEMA

- .github/workflows/docker.yml
- docker/README.md
- docker/alpine-normal/build.sh
- docker/alpine-small/build.sh
- docker/ubuntu-full/Dockerfile
- docker/ubuntu-full/build.sh
- docker/ubuntu-small/build.sh
- docker/util.sh
PR makes some changes so that `latest` docker images which make use of multi-platform capability are pushed to ghcr.io/osgeo/gdal.
This PR makes an attempt to have it such that the `Docker/build-all.sh` script can still be used both locally and in CI, but when used in CI, the multi-process builds would make use of attestation and the multi-node runners; but when used locally, it will use emulation to generate the builds.
Fixes some issues left-over from #13066
If merged, the commits should be squashed.
* OS:
* Compiler:
> Touchup Docker Image Generation

- autotest/gdrivers/zarr_driver.py
- doc/source/drivers/raster/zarr.rst
- frmts/zarr/zarrdriver.cpp
- frmts/zarr/zarrdrivercore.cpp
Sometimes remote online Zarr stores won't have a reliable directory listing. In such cases, one can point to one of the following metadata files for GDAL to detect the correct driver to open the Zarr store:
- zarr.json
- .zmetadata
- .zgroup
- .zarray
Real life example with ESA's EOPF Zarr: `gdalmdiminfo /vsicurl/https://objectstore.eodc.eu:2222/e05ab01a9d56408d82ac32d69a5aae2a:202504-s02msil2a/15/products/cpm_v256/S2A_MSIL2A_20250415T094041_N0511_R036_T35VLC_20250415T155631.zarr/.zmetadata `
> Support remote zarr without directory listing.

- .github/workflows/release.yml
- mkgdaldist.sh
On a git-tag starting with "v", versioned docker images are created with attestation, and with both amd64 and arm64 platforms and "joined" via a manifest.
Furthermore `mkgdaldist.sh` is run, creating the source release artifacts, which are uploaded to a draft release on github.  The source releases are also have attestation run on them.
> Migrate gdal release tasks to CI workflow

- .github/workflows/release.yml
When doing a `beta` or `RC` release, use `test.pypi.org` instead of regular `pypi` for the python packages.
> When doing a RC or Beta release, push to test.pypi
