OSGeo/gdal

appveyor.yml

add comment for RDP access

---

gdal/ogr/ogr2gmlgeometry.cpp

Found with:
autotest2/cpp/ogr/ogrgeometryfactory_wkt_fuzzer
autofuzz AddressSanitizer

Fix leak in ogr2gmlgeometry.cpp on append fail.

---

gdal/swig/python/setup.py

Adds the python scripts to the python module.  They are installed if you build via gnumake, but they're not included in the python module.
Python

add scripts to python module

---

autotest/cpp/test_gdal.cpp
autotest/cpp/test_ogr.cpp
gdal/gcore/gdal_priv.h
gdal/gcore/gdaldataset.cpp
gdal/ogr/ogr_api.h
gdal/ogr/ogr_apitut.dox
gdal/ogr/ogr_feature.h
gdal/ogr/ogr_geometry.h
gdal/ogr/ogrcurve.cpp
gdal/ogr/ogrfeature.cpp
gdal/ogr/ogrsf_frmts/generic/ogrlayer.cpp
gdal/ogr/ogrsf_frmts/ogrsf_frmts.h

Add GDALDataset::GetLayers(), GetBands() and GetFeatures(), that accept iterator and [] access
Add friendly way to iterate over field values of a feature, and to query/modify them with []
https://trac.osgeo.org/gdal/ticket/7210

Add dataset layer, band, feature and field iterators

---

autotest/gdrivers/kmlsuperoverlay.py
autotest/gdrivers/netcdf.py
autotest/gdrivers/netcdf_cf.py
autotest/gdrivers/netcdf_cfchecks.py
autotest/ogr/ogr_csv.py
autotest/ogr/ogr_pg.py
autotest/ogr/ogr_sql_sqlite.py
autotest/ogr/ogr_sqlite.py
autotest/ogr/ogr_wasp.py
gdal/swig/python/samples/crs2crs2grid.py
gdal/swig/python/samples/densify.py
gdal/swig/python/samples/fft.py
gdal/swig/python/samples/gdal2grd.py
gdal/swig/python/samples/gdal_ls.py
gdal/swig/python/samples/val_repl.py
gdal/swig/python/scripts/gdal_retile.py
gdal/swig/python/scripts/gdalcompare.py
gdal/swig/python/scripts/gdalmove.py

Silences E271 diagnostics about multiple spaces after keywords. `git diff -w` shows no differences.

Python code: Fix E271: multiple spaces after keyword.

---

gdal/frmts/ecw/lookup.py

Removes some E999 warnings due to inconsistent use of tabs and spaces in indentation.

Python code: Fix E999 TabError: inconsistent use of tabs and spaces in indentation.

---

autotest/gcore/hfa_srs.py
autotest/gcore/testnonboundtoswig.py
autotest/gcore/tiff_srs.py
autotest/gcore/vsicrypt.py
autotest/gdrivers/netcdf_cf.py
autotest/gdrivers/nitf.py
autotest/ogr/ogr_gml_geom.py
autotest/ogr/ogr_ods.py
autotest/ogr/ogr_shape.py

Silences diagnostic E262 (`inline comment should start with '#'`).

Python code: Fix E262: inline comment should start with '# '.

---

autotest/ogr/ograpispy.py

Uses Python's `difflib` to show the differences between the expected and generated script if there are any differences.

Python code: Use unified_diff in autotest/ogr/ograpispy.py

---

gdal/ltmain.sh
gdal/m4/libtool.m4
gdal/m4/ltoptions.m4
gdal/m4/ltsugar.m4
gdal/m4/ltversion.m4
gdal/m4/lt~obsolete.m4

Upgrades the `libtool` support files to those from version 2.4.6. Fixes the problem reported in PR #438.
#438

Run libtoolize -fc to upgrade to libtool 2.4.6 files.

---

gdal/swig/python/samples/ogr2ogr.py
gdal/swig/python/scripts/gdal_retile.py

Python code: Fix E712: comparison to False should be 'if cond is False:' or 'if not cond:`

---

autotest/gdrivers/netcdf_cfchecks.py
autotest/pymod/gdaltest_python3.py
gdal/scripts/completionFinder.py

Python code: Fix E401 (multiple imports on one line)

---

autotest/gcore/tiff_ovr.py
autotest/gcore/tiff_write.py
autotest/gdrivers/netcdf_cfchecks.py
autotest/ogr/ogr_index_test.py
autotest/ogr/ogr_join_test.py
autotest/ogr/ogr_mysql.py
autotest/ogr/ogr_pg.py
autotest/ogr/ogr_sql_sqlite.py
autotest/osr/osr_epsg.py
autotest/pymod/gdaltest.py
gdal/swig/python/samples/gdal_vrtmerge.py
gdal/swig/python/samples/magphase.py
gdal/swig/python/scripts/gdal_merge.py

Silences W503 warnings about line breaks around binary operators.

Python code: Fix W503 warnings

---

gdal/ogr/ogrfeature.cpp

Found with autofuzz on the CSV driver

Check for nan in OFTTime in OGRFeature::GetFieldAsString

---

autotest/gdrivers/rda.py
gdal/frmts/rda/rdadataset.cpp

Change extension to .dgrda to differentiate from R data. Added test for file format.
* OS:
* Compiler:

change extension to .dgrda to differentiate from R data

---

gdal/port/cpl_conv.cpp
gdal/port/cpl_conv.h

Implements new CPLReadLine3L().
See https://lists.osgeo.org/pipermail/gdal-dev/2018-April/048436.html
#365

implement CPLReadLine3L()

---

autotest/gcore/tiff_write.py
autotest/gdrivers/ecw.py
autotest/gdrivers/jp2lura.py
autotest/gdrivers/jp2openjpeg.py
autotest/gdrivers/netcdf_cf.py
autotest/ogr/ogr_index_test.py
autotest/utilities/test_gnmutils.py

Pylint has identified a number of `pass` statements that have no effect. Remove them.

Python code: Remove unnecessary pass statements

---

autotest/gdrivers/lcp.py
autotest/gdrivers/pcraster.py

Calls `post_reason` from the right module. Found with Pylint.

Python code: Use gdaltest.post_reason not gdal.post_reason.

---

autotest/gdrivers/netcdf_cfchecks.py
gdal/swig/include/python/docs/doxy2swig.py
gdal/swig/python/samples/validate_cloud_optimized_geotiff.py

Python `isinstance()` allows a tuple of types, so that `isinstance(obj, A) or isinstance(obj, B)` can be simplified with just `isinstance(obj, (A, B))`.

Python code: Merge isinstance() calls

---

autotest/gdrivers/wcs.py
gdal/frmts/wcs/wcsdataset.cpp
gdal/frmts/wcs/wcsdataset.h
gdal/frmts/wcs/wcsdataset100.cpp
gdal/frmts/wcs/wcsdataset110.cpp
gdal/frmts/wcs/wcsdataset201.cpp
gdal/frmts/wcs/wcsutils.cpp

Check error when getting capabilities. Do not add zero capabilities entry to cache. Correct action if global metadata file is missing. In metadata record only subdataset NAME and DESC. In v2 put dataset metadata to global domain.
#515 #516

Improvements to WCS driver

---

autotest/gdrivers/netcdf_cfchecks.py

Removes code marked unreachable by Pylint.

Python code: Remove dead code

---

gdal/ogr/ogrsf_frmts/mssqlspatial/ogrmssqlspatialtablelayer.cpp

Fix layer-schema separation problem as per #586
* OS:
* Compiler:

Fix layer-schema separation problem (#586)

---

autotest/gdrivers/netcdf_cfchecks.py
autotest/gdrivers/nitf.py
autotest/ogr/ogr_tiger.py
autotest/pymod/gdaltest.py

Silences Pylint warnings about `file` being a redefined built-in.

Python code: Rename 'file' -> 'filename'

---

gdal/GNUmakefile

Fixes the datadir in gdal.pc
#608 
* OS:
* Compiler:

Fix the datadir in gdal.pc.

---

gdal/ogr/ogrsf_frmts/shape/dump_symbols.sh

Python code: Another rodata_symbol_list fix

---

gdal/port/cpl_string.h
gdal/port/cplstring.cpp

I have found a better readable, equally valid solution to the problem already treated in pull request #321
Sorry for the confusion.

Opals tuw no std string symbols2

---

autotest/gdrivers/postgisraster.py
autotest/ogr/ogr_vfk.py

Some new flake8 violations have crept in. There are no diffs with `git diff -w --ignore-blank-lines`.

Python code: Fix new flake8 violations

---

CONTRIBUTING.md

Fixes the name of git repository in CONTRIBUTING.md.

Documentation: fix the name of git repository from git@ to https://

---

gdal/port/cpl_vsi_mem.cpp

Makes local path variables const.
Trying to track down a weird memory leak.
Found via autofuzz with the OpenFGDB fuzzer.
Does not actually fix the bug, but makes reasoning about it easier.

NormalizePath: Convert CPLString to std::string, return the str and use std::replace.

---

gdal/ogr/ogrsf_frmts/edigeo/ogr_edigeo.h
gdal/ogr/ogrsf_frmts/edigeo/ogredigeodatasource.cpp

Fixes this issue: https://trac.osgeo.org/gdal/ticket/6955
Edigeo driver manages both ways to link an object with several faces.

EDIGEO: reading multipolygons (fixes #6955)

---

gdal/frmts/rmf/rmflzw.cpp

* Remove 'goto'.
* Extract code-table creation to separate function.

RMF: Improved LZW decoder code

---

gdal/swig/python/scripts/gdal2tiles.py

This change fixes progress bar output for the case with using -x option
#747 #729

Fix progress bar for -x option

---

autotest/gdrivers/rmf.py
gdal/frmts/rmf/frmt_rmf.html
gdal/frmts/rmf/rmfdataset.cpp
gdal/frmts/rmf/rmfdataset.h

* Parallelize data compression
* Add internal tile write-cache
* Add compressed overviews support.

RMF: Rework write pipeline

---

autotest/gcore/mask.py
gdal/gcore/gdalrasterband.cpp

Make sure to add an AlphaMask flag for alpha band in a Uint16 1 band dataset. 
https://lists.osgeo.org/pipermail/gdal-dev/2018-July/048832.html

[WIP] add Alpha tags for alpha band in Uint16 One band dataset

---

gdal/frmts/rmf/rmfdataset.cpp
gdal/frmts/rmf/rmfdataset.h
gdal/frmts/rmf/rmfjpeg.cpp

* Add RMFDataset::ReadTile() function
* Remove IRasterIO call from IWriteBlock to avoid deadlocks
* Expose NBITS to metadata if needed

RMF: Rework read pipeline

---

gdal/frmts/rmf/rmfdataset.cpp

Fix memory access after free at RMFDataset destructor (refs #774)

RMF: Fix memory access after free at RMFDataset destructor

---

Vagrantfile
gdal/scripts/vagrant/gdal.sh
gdal/scripts/vagrant/postgis.sh

Fix vagrant script to fail to build csharp binding.
#783

Fix issue #783

---

gdal/port/cpl_multiproc.cpp

Inside LXC/Docker container the CPU count can be limited, but standart syscall returns CPU count of the host system. However, we can determine CPUs assigned to the container from cgroup configuration.
See: https://www.kernel.org/doc/Documentation/cgroup-v1/cpusets.txt
Related issue with RAM: #640

CPLGetNumCPUs(): take into account cgroup limitation

---

Vagrantfile
gdal/scripts/vagrant/sfcgal.sh

update sfcgal version in Vagrant environment

vagrant: install dependency sfcgal 1.3.5

---

gdal/aclocal.m4
gdal/configure
gdal/configure.ac

This is to avoid patching systems where gdal has to depend
transitively on libtirpc (through libogdi).
Fixes build system issues.
None.
* OS: Linux
* Compiler:

use ogdi.pc if available

---

Vagrantfile
gdal/scripts/vagrant/openjpeg.sh
gdal/scripts/vagrant/sfcgal.sh

Enable generic vagrant-cachier bucket for wget.

Vagrant: introduce wget cache

---

gdal/frmts/gtiff/geotiff.cpp

Fixes a compilation error that for unknown reasons is not caught in CI but is obvious when considering existing pragmas.
* OS: Debian 10 (testing)
* Compiler: GCC 8.2.0

Fix missing pragma causing compilation failure due to missing bTryCopy

---

gdal/port/cpl_aws.cpp

Followup to #956 and #958 
Some OSs return `Xen` in the DMI `sys_vendor` ID which breaks out before the UUID check happens, which means Xen instances can be incorrectly identified as not-EC2.
Reverses the order of checks. No OSs that I've tested populate the hypervisor-id under Nitro instance types.
Cherry-pick applies cleanly to 2.3 so I'll apply that after this passes CI & is merged.

AWS: fix issue in updated ec2 identification

---

CONTRIBUTING.md

Related with documentation, with focus on string #108; just a minor formatting proposal for the sake of clarity 
There is no issues or pull request related
* OS: Mac OSX High Sierra
* Compiler: Clang LLVM

CONTRIBUTING.md: minor reformatting

---

Vagrantfile
gdal/scripts/vagrant/gdal.sh
gdal/swig/csharp/GNUmakefile

A workaround for issue #967. revert to comment out `make test` for swig/csharp.
#967 
#824

Vagrant: workaround for #967

---

Vagrantfile

Install libgeotiff-epsg package in vagrant environment

Vagrant: install libgeotiff-epsg

---

gdal/scripts/vagrant/swig-3.0.8.sh

add swig 3.0.8 installation script for binding developer
- Vagrant guest

Vagrant: add swig 3.0.8 for developer

---

autotest/gcore/tiff_write.py
gdal/swig/python/samples/validate_cloud_optimized_geotiff.py

This PR removes the requirement for overviews in a COG and matches the current draft of the specification - https://github.com/cogeotiff/cog-spec/blob/master/spec.md
https://github.com/cogeotiff/cog-spec/issues/2

remove requirement for overviews in a COG

---

Vagrantfile
gdal/scripts/vagrant/gdal-mingw.sh

Work around for #1058 
- removes libproj-mingw 
#1058 
Vagrant

Vagrant: work around for #1058

---

gdal/frmts/grib/gribdataset.cpp

This issue seems to be introduced in gdal 2.3.x. 
Test File: http://tgftp.nws.noaa.gov/SL.us008001/ST.opnl/DF.gr2/DC.ndfd/AR.conus/VP.001-003/ds.wx.bin
Using GDAL 2.3.2, the NoData Value is reported as 1.40115833447838459e-41 instead of the expected 9999.
With GDAL 2.3.2:
```
Band 42 Block=2145x1 Type=Float64, ColorInterp=Undefined
Description = 0[-] SFC="Ground or water surface"
NoData Value=1.40115833447838459e-41
Metadata:
GRIB_COMMENT=Weather string [-]
GRIB_DISCIPLINE=0(Meteorological)
GRIB_ELEMENT=Wx
GRIB_FORECAST_SECONDS=190800 sec
GRIB_IDS=CENTER=8(US-NWSTG) MASTER_TABLE=1 LOCAL_TABLE=0 SIGNF_REF_TIME=1(Start_of_Forecast) REF_TIME=2018-10-30T19:00:00Z PROD_STATUS=0(Operational) TYPE=1(Forecast)
GRIB_PDS_PDTN=0
GRIB_PDS_TEMPLATE_ASSEMBLED_VALUES=1 192 2 0 0 255 255 1 53 1 0 0 255 …
```

grib: interpret missing data values correctly for complex packing

---

gdal/gcore/gdaldllmain.cpp

Experiments have shown that a __attribute__((destructor )) function is called
*AFTER* the destructor of static C++ objects. Which is prone to crash is
code called by this destructor function then uses those C++ objects.
There could have been a solution by making the destructor function a C++
object itself and playing with gcc __attribute__((init_priority(XXXX))),
unfortunately the destructor of static C++ objects in functions/methods
is always called before the destructor of objects with explicit priority,
so there is no workaround.
With MSVC, apparently according to
https://stackoverflow.com/questions/4496233/which-is-called-first-dllmain-or-global-static-object-constructor
DllMain(DLL_PROCESS_DETACH) is called before C++ object destruction,
so it seems safe to keep it.

GDALDestroy(): no longer call it automatically on GCC/CLang (non-MSVC) builds

---

autotest/gcore/tiff_write.py
gdal/frmts/gtiff/libtiff/tif_webp.c

Fixes the bug reported https://gitlab.com/libtiff/libtiff/merge_requests/32 that webp compression in TIFF doesn't support lossless compression.
https://gitlab.com/libtiff/libtiff/merge_requests/32
* OS:
* Compiler:

enable lossless compression for webp in tiff

---

autotest/conftest.py

Use osgeo package for python interface in autotest.

autotest: import from osgeo package

---

autotest/gdrivers/ngw.py
gdal/frmts/formats_list.html
gdal/ogr/ogrsf_frmts/ngw/drv_ngw_raster.html
gdal/ogr/ogrsf_frmts/ngw/gdalngwdataset.cpp
gdal/ogr/ogrsf_frmts/ngw/ngw_api.cpp
gdal/ogr/ogrsf_frmts/ngw/ogr_ngw.h
gdal/ogr/ogrsf_frmts/ngw/ogrngwdriver.cpp
gdal/port/cpl_http.cpp

1. Add CreateCopy function to NGW driver. 
1. Add upload form capability to CPLHTTPFetch 
No

NGW: Add CreateCopy function to NGW driver

---

gdal/ogr/ogrsf_frmts/mitab/mitab_spatialref.cpp

MITAB: Remove outdated comment
* OS:
* Compiler:

Remove outdated comment

---

gdal/ogr/ogrsf_frmts/oci/drv_oci.html
gdal/ogr/ogrsf_frmts/oci/ogrocidriver.cpp

OCI driver misses OpenOption MULTI_LOAD (fixes #1233)

---

gdal/GDALmake.opt.in
gdal/configure
gdal/configure.ac

now that #1250 and #1268 are done, also allow raw drivers to be disabled

add raw to drivers that can be disabled

---

gdal/gcore/gdal.h

Fix incorrect copy/paste for DCAP_GNM capability dox

Fix dox for DCAP_GNM

---

gdal/configure
gdal/configure.ac

adding a safety check for grib at configure time

grib requires png

---

Vagrantfile
gdal/scripts/vagrant/gdal-mingw.sh
gdal/scripts/vagrant/install-proj6-mingw.sh
gdal/scripts/vagrant/install-proj6.sh

- Install proj.6 library from git HEAD
- Build sqlite3 and proj.6 with mingw32-w64
- Install mingw32-w64 binaries into /usr/local/x86_64-w64-mingw32/
- Fixed #1281
install PROJ version6 library
#1281 
Vagrant

Vagrant: install PROJ6

---

gdal/frmts/gtiff/geotiff.cpp

make gtiff emit merged consecutive multi-range reads

---

gdal/port/cpl_vsil_hdfs.cpp

This addresses the issue with reading certain datasets on HDFS file systems reported in https://github.com/OSGeo/gdal/issues/1333 .  This issue was caused by the fact that `hdfsRead` evidently does not always return all requested bytes when the file in question is on HDFS.
I did not include a unit test update because this problem is hard to trigger on a local file system (and therefore, a unit test for this specific problem would require a running HDFS cluster -- I am however open to testing ideas and will include any that are requested).
https://github.com/OSGeo/gdal/issues/1333
A clean Ubuntu 18.10 virtual machine using OpenJDK 11.  Tested with Hadoop 2.9.2 in a [single node cluster](https://hadoop.apache.org/docs/stable/hadoop-project-dist/hadoop-common/SingleCluster.html) …

vsihdfs: More Than One hdfsRead Call Sometimes Needed

---

gdal/swig/python/scripts/gdal2tiles.py

Python's `multiprocessing.Pool` type has some methods that can replace some of the manual interprocess communication used in `gdal2tiles.py` in a cleaner and less error-prone way.
This fixes a bug when combining the `--exclude` option with `--processes`: the skipped fully transparent tiles were not properly writing a completion event to the queue, so the progress bar did not reflect these skipped tiles, and the progress bar process hung waiting to receive the expected number of results from the queue.
Similarly, if one of the subprocesses threw an exception, there were cases where the program would hang waiting to receive on a queue.

gdal2tiles: Multiprocessing fixes and cleanup

---

gdal/frmts/dted/frmt_dted.html

This PR updates the URL for the DTED spec.

DTED: fix dead URL in documentation

---

gdal/frmts/grib/degrib/g2clib/dec_png.c
gdal/frmts/gtiff/libgeotiff/geo_names.c
gdal/frmts/pdf/pdfobject.cpp
gdal/frmts/pds/pds4vector.cpp
gdal/gcore/gdaldataset.cpp
gdal/gcore/gdalsse_priv.h
gdal/ogr/ogrfeaturedefn.cpp
gdal/ogr/ogrsf_frmts/geoconcept/geoconcept.c
gdal/port/cpl_json_streaming_parser.cpp
gdal/port/cpl_string.cpp
gdal/port/cpl_virtualmem.cpp

Multiple commits addressing warnings for both GCC (8.2) and clang (7.0).
Please let me know if you'd rather have several PRs open (one per commit?) instead. Some of them seem clearly false positives, but I think it's worth using #pragmas for those to have a silent build.
Environment configured with:
```
./configure --prefix=/usr --with-netcdf --with-libtiff --with-sqlite3 --with-geotiff --with-mysql --with-python --with-curl --with-hdf5 --with-perl --with-geos --with-png --with-poppler --with-spatialite --with-openjpeg CFLAGS="$CFLAGS -Werror" CXXFLAGS="$CXXFLAGS -Werror" CC=$(CC) CXX=$CXX)
```
Where `CFLAGS` == `CXXFLAGS` == `=-march=native -mtune=native -O3 -pipe -fno-plt -Wall -Wextra -g3 -gdwarf-4 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer`
And CC and CXX changed for gcc and …

Address compiler warnings

---

gdal/frmts/gtiff/frmt_gtiff.html

Doc: fix typo "Sudatasets" -> "Subdatasets"

---

README.md
gdal/docker/README.md
gdal/docker/alpine-normal/Dockerfile
gdal/docker/alpine-normal/build.sh
gdal/docker/alpine-small/Dockerfile
gdal/docker/alpine-small/build.sh
gdal/docker/alpine-ultrasmall/Dockerfile
gdal/docker/alpine-ultrasmall/build.sh
gdal/docker/ubuntu-full/Dockerfile
gdal/docker/ubuntu-full/build.sh
gdal/docker/ubuntu-small/Dockerfile
gdal/docker/ubuntu-small/build.sh

@hobu I'd like to explicitly put a license in the Dockerfile, if possible Public domain, so that anyone feel free to reuse as they wish. As this is derived from the PROJ Dockerfile you authored, I need your permission. And I believe you're the owner of https://hub.docker.com/u/osgeo . Would it be possible to add myself as a contributor ('rouault' login in hub.docker.com) so I can push osgeo/gdal packages ?-

Add Dockerfile for different configurations

---

autotest/gdrivers/tiledb_write.py
gdal/frmts/tiledb/tiledbdataset.cpp

Currently the TileDB driver supports a container of subdatasets, each dataset within this container can have a different number of bands. It is useful to be able to create this container within GDAL for TileDB, particularly so when the number of bands and the extent of associated sources line up, e,g, a DEM and an image. 
This PR adds support for registering additional datasets with a source image and to be able to write and retrieve these in an easy manner. Compared to the current subdataset support this implementation uses the band component as a third dimension which will improve access times. It is a future task to add a check to see if all the subdatasets in the `copysubdatasets` match a base raster and to implement this as a performance option in that case.
None

TileDB co-registered attributes per band

---

gdal/frmts/tiledb/tiledbdataset.cpp

When writing multiple attributes to TileDB they were being freed before the query was submitted. This copies the pattern in `CreateCopy` of caching these blocks in a vector and then calling `VSIFree`
https://github.com/OSGeo/gdal/issues/1498

TileDB: fix memleak writing multiple attributes (fixes #1498)

---

gdal/frmts/gtiff/geotiff.cpp

Currently the blocks being compressed are flushed to disk in the order
the worker threads complete. Which may be different from the order in
which they were submitted. This is not desirabe and this commit makes
sure that the blocks are flushed to disk in the order they were requested
to be written.

GTiff: make -co NUM_THREADS produce reproducible output

---

gdal/frmts/gtiff/libtiff/tif_dirwrite.c

In most situations of BigTIFF file, the tile/strip sizes are of reasonable size,
that is they fit on a 4-byte LONG, or even on a 2-byte SHORT.
So in that case, use LONG/SHORT instead of LONG8
to save some space. For uncompressed file, it is easy to detect such situations
by checking at the TIFFTileSize64()/TIFFStripSize64() return. For compressed file,
we must take into account the fact that compression may sometimes result in
larger compressed data. So we allow this optimization only for a few select
compression times, and take a huge security margin (10x factor). We also only
apply this optimization on multi-strip files, so as to allow easy on-the-fly
growing of single-strip files whose strip size could grow above the 4GB threshold.
This change is compatible with the BigTIFF …

libtiff: BigTIFF creation: write TileByteCounts/StripByteCounts tag with SHORT or LONG when possible

---

gdal/doc/source/drivers/raster/kea.rst

Fix a minor typo `likea` -> `libkea`

fix typo libkea doc

---

gdal/doc/source/drivers/vector/osm.rst

Make osmconf.ini link to point to GitHub

---

gdal/frmts/mrsid/nmake.opt

Add platform-specific directories to the list of locations searched
for the MrSID SDK libraries.
This enables use of SDK bundle with libraries for both, Win64 and Win32.
* OS: Windows
* Compiler: MSVC+NMAKE

NMAKE: Add MRSID_PLATFORM to frmts/mrsid/nmake.opt

---

gdal/frmts/jp2kak/makefile.vc
gdal/frmts/jpipkak/makefile.vc
gdal/nmake.opt

* Allow users to tweak/append extras to `KAKINC`
* Set `KAKADU_7_5_OR_LATER=YES` by default, unless user already defined it.
* OS: Windows
* Compiler: MSVC + NMAKE

NMAKE: Allow extra customisation points for Kakadu config

---

gdal/doc/source/drivers/raster/fits.rst

This pull request updates fits.rst documentation file to describe new features added in FITS driver (#1298)

Update FITS documentation for version 3.0

---

autotest/ogr/ogr_sxf.py
gdal/doc/source/drivers/vector/sxf.rst
gdal/ogr/ogrsf_frmts/mitab/mitab_imapinfofile.cpp
gdal/ogr/ogrsf_frmts/shape/ogrshapelayer.cpp
gdal/ogr/ogrsf_frmts/sxf/ogr_sxf.h
gdal/ogr/ogrsf_frmts/sxf/ogrsxfdatasource.cpp
gdal/ogr/ogrsf_frmts/sxf/ogrsxfdriver.cpp
gdal/ogr/ogrsf_frmts/sxf/ogrsxflayer.cpp
gdal/port/cpl_recode.cpp
gdal/port/cpl_string.h

SXF: Expose 'config options' to 'open options list' for convenience

---

gdal/port/cpl_vsil_curl.cpp

fix CPL_VSIL_CURL_ALLOWED_EXTENSIONS with query string (#1614)

---

gdal/ogr/ogrsf_frmts/sxf/ogr_sxf.h
gdal/ogr/ogrsf_frmts/sxf/ogrsxfdriver.cpp

Add identify function as suggested at #1607

SXF: Add driver identify function (refs #1607)

---

gdal/ogr/ogrsf_frmts/elastic/ogrelasticdatasource.cpp

ES: Set 'application/json' in RunRequest() with POST (fixes #1628)

---

gdal/frmts/tiledb/tiledbdataset.cpp

OS GDAL builds with TileDB are currently broken on Conda due to an ambiguity with `size_t`, the simple fix is to use `uint64_t` and only 64 bit architectures are supported by this driver.

tiledb: removed ambiguous use of size_t

---

gdal/docker/README.md

normal typo in docker README

---

gdal/doc/source/programs/gdaladdo.rst

Adds a gdaladdo example with subdataset to the docs

Doc gdaladdo: Add example with subdataset

---

gdal/swig/python/scripts/gdal_calc.py
gdal/swig/python/scripts/gdal_merge.py
gdal/swig/python/scripts/gdal_pansharpen.py
gdal/swig/python/scripts/gdal_proximity.py
gdal/swig/python/scripts/gdal_sieve.py
gdal/swig/python/scripts/pct2rgb.py
gdal/swig/python/scripts/rgb2pct.py

Fixes #1719. 
Issue #1533 was the same problem in a different file, I applied the same change here as in the fix for that issue (ac68564d3c012ec5), but I can also add tests if you like.

Fix GetOutputDriverFor() UnboundLocalError when multiple drivers found (fixes #1719)

---

gdal/frmts/rdb/rdbdataset.cpp

Fixes warning reported by cppcheck
Fixes #1766

RDB: fixes cppcheck warning

---

autotest/ogr/ogr_flatgeobuf.py
gdal/ogr/ogrsf_frmts/flatgeobuf/ogrflatgeobuflayer.cpp

Early adopters has found potential problems when doing spatial filtering but I cannot reproduce yet. This basic test does not hurt though.

FlatGeobuf: Filtering fixes

---

gdal/ogr/ogrsf_frmts/flatgeobuf/ogr_flatgeobuf.h
gdal/ogr/ogrsf_frmts/flatgeobuf/ogrflatgeobufdataset.cpp
gdal/ogr/ogrsf_frmts/flatgeobuf/ogrflatgeobuflayer.cpp

Checks return values for all I/O and memory allocations to make sure to handle potential errors and some tidying up.

FlatGeobuf: Rework/improve error handling

---

gdal/ogr/ogrsf_frmts/flatgeobuf/ogrflatgeobufdataset.cpp

VERIFY_BUFFERS is incorrectly treated like a layer create option so it's ignored as an open option and as such cannot be turned off. This PR fixes that. I have also done some initial measurements of the performance hit and looks like it's about 30%.

FlatGeobuf: Fix VERIFY_BUFFERS open option handling

---

autotest/ogr/ogr_flatgeobuf.py
gdal/ogr/ogrsf_frmts/flatgeobuf/ogr_flatgeobuf.h
gdal/ogr/ogrsf_frmts/flatgeobuf/ogrflatgeobufdataset.cpp
gdal/ogr/ogrsf_frmts/flatgeobuf/ogrflatgeobuflayer.cpp

This intends to fix https://github.com/OSGeo/gdal/issues/1863. Problem was I did not have correct logic in place to seek the correct position depending on if the file contains a spatial index or not.

FlatGeobuf: Fixes for index handling

---

gdal/ogr/ogrsf_frmts/flatgeobuf/ogr_flatgeobuf.h
gdal/ogr/ogrsf_frmts/flatgeobuf/ogrflatgeobufdataset.cpp
gdal/ogr/ogrsf_frmts/flatgeobuf/ogrflatgeobuflayer.cpp

Intends to fix https://github.com/OSGeo/gdal/issues/1849.

FlatGeobuf: Buffer size bound checks

---

autotest/ogr/ogr_gpkg.py
gdal/ogr/ogrsf_frmts/gpkg/ogrgeopackagedatasource.cpp

The same behaviour is also present in the Spatialite and PG driver (and potentially others), but that pull request only covers the GPKG case

GPKG: on layer creation, check if the SRS is consistent with its advertize AUTHORITY/ID, and if not do not use official EPSG entries (fixes #1857)

---

gdal/doc/source/drivers/raster/fits.rst

This PR add to the documentation details about the FITS/WCS metadata translation

Details on FITS/WCS metadata translation.

---

autotest/ogr/ogr_flatgeobuf.py
gdal/ogr/ogrsf_frmts/flatgeobuf/ogr_flatgeobuf.h
gdal/ogr/ogrsf_frmts/flatgeobuf/ogrflatgeobuflayer.cpp

Adds complete set of 2D WKT geometry roundtrip test and some refactoring

FlatGeobuf: WKT roundtrip tests and nullptr validation

---

autotest/ogr/ogr_flatgeobuf.py
gdal/apps/test_ogrsf.cpp
gdal/doc/source/drivers/vector/flatgeobuf.rst
gdal/ogr/ogrsf_frmts/flatgeobuf/ogr_flatgeobuf.h
gdal/ogr/ogrsf_frmts/flatgeobuf/ogrflatgeobufdataset.cpp
gdal/ogr/ogrsf_frmts/shape/ogrshapedatasource.cpp
gdal/port/cpl_conv.h
gdal/port/cpl_path.cpp

FlatGeoBuf: add support for multiple layers in a directory of .fgb files, and fix single layer support (fixes #1862)

---

autotest/ogr/ogr_flatgeobuf.py
gdal/ogr/ogrsf_frmts/flatgeobuf/ogrflatgeobuflayer.cpp

Aims to fix #1897. Have not been able to find out why I'm not getting the expected geometry and or geometry type in roundtrip test.

FlatGeobuf: Fix Z/M handling

---

autotest/osr/osr_basic.py
gdal/ogr/ogr_proj_p.cpp
gdal/ogr/ogr_proj_p.h
gdal/ogr/ogrspatialreference.cpp

Helps performance for MapServer PROJ6 migration

OSR: add an internal cache for importFromEPSG() and importFromWkt().

---

gdal/alg/viewshed.cpp
gdal/apps/gdal_viewshed.cpp
gdal/apps/makefile.vc
gdal/swig/include/Operations.i
gdal/swig/python/extensions/gdal_wrap.cpp
gdal/swig/python/osgeo/gdal.py

Doxygen warning fixes for `gdal_viewshed`

Viewshed doxygen fixes

---

gdal/ogr/ogrsf_frmts/flatgeobuf/ogrflatgeobuflayer.cpp
gdal/ogr/ogrsf_frmts/flatgeobuf/packedrtree.cpp

Aims to mitigate oss-fuzz issues 18092, 18103, 18036 and 18057.

FlatGeobuf: Fixes for weaknesses detected by oss-fuzz

---

gdal/ogr/ogrsf_frmts/flatgeobuf/ogrflatgeobuflayer.cpp

Mitigation for https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=18250.

FlatGeobuf: Avoid early allocation with risk of leak

---

gdal/configure
gdal/configure.ac
gdal/frmts/ecw/ecwcreatecopy.cpp
gdal/frmts/ecw/ecwdataset.cpp
gdal/frmts/ecw/gdal_ecw.h
gdal/frmts/ecw/jp2userbox.cpp
gdal/nmake.opt

- implementation for API breaking changes.
- handle "newabi" rename to "cpp11abi" in configure
- example information in nmake.opt
Windows & Linux

ECW: required changes for upcoming 5.5 release

---

autotest/ogr/ogr_flatgeobuf.py
gdal/ogr/ogrsf_frmts/flatgeobuf/ogr_flatgeobuf.h
gdal/ogr/ogrsf_frmts/flatgeobuf/ogrflatgeobuflayer.cpp

Aims to mitigate https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=18343.

FlatGeobuf: Additional size checks

---

gdal/ogr/ogrsf_frmts/flatgeobuf/ogr_flatgeobuf.h
gdal/ogr/ogrsf_frmts/flatgeobuf/ogrflatgeobufdataset.cpp
gdal/ogr/ogrsf_frmts/flatgeobuf/ogrflatgeobuflayer.cpp

This PR is to implement what is suggested at https://github.com/OSGeo/gdal/issues/1964.

FlatGeobuf: Write in two passes if index requested

---

autotest/gdrivers/mem.py
gdal/frmts/mem/memdataset.cpp

Preserves access mode for datasets opened using MEM driver.
#1971

preserve access mode in mem driver

---

gdal/ogr/ogrsf_frmts/flatgeobuf/ogr_flatgeobuf.h
gdal/ogr/ogrsf_frmts/flatgeobuf/ogrflatgeobufdataset.cpp
gdal/ogr/ogrsf_frmts/flatgeobuf/ogrflatgeobuflayer.cpp

Aims to fix https://github.com/OSGeo/gdal/issues/1966

FlatGeobuf: Read feature indices on demand

---

gdal/doc/.azure-pipelines.yml

Fail Azure jobs on any command error 

---

gdal/ogr/ogrsf_frmts/flatgeobuf/ogr_flatgeobuf.h
gdal/ogr/ogrsf_frmts/flatgeobuf/ogrflatgeobufdataset.cpp
gdal/ogr/ogrsf_frmts/flatgeobuf/ogrflatgeobuflayer.cpp

A follow up optimization after conclusions in https://github.com/OSGeo/gdal/issues/1966.
Tested locally to significantly improve read performance when reading through vsigzip.

FlatGeobuf: Optimize reads for index search

---

gdal/alg/gdalwarpkernel.cpp

This workarounds a PROJ bug also fixed per https://github.com/OSGeo/PROJ/pull/1726

Multithreaded warper: make sure a transformer object is used by the the thread which created it (fixes #1989)

---

gdal/port/cpl_vsil_curl.cpp
gdal/port/cpl_vsil_curl_class.h
gdal/port/cpl_vsil_webhdfs.cpp

Kudos to @tbonfort for the easy reproducer.

/vsicurl (and derived filesystems): fix concurrency issue with multithreaded reads (fixes #1244)

---

autotest/gcore/tiff_srs.py
autotest/osr/osr_ct_proj.py
gdal/frmts/gtiff/gt_wkt_srs.cpp
gdal/ogr/ogr_proj_p.cpp
gdal/ogr/ogr_proj_p.h
gdal/ogr/ogr_srs_api.h
gdal/ogr/ogrct.cpp
gdal/ogr/ogrspatialreference.cpp
gdal/swig/include/osr.i
gdal/swig/python/extensions/osr_wrap.cpp
gdal/swig/python/osgeo/osr.py

[Backport 3.0] Several TOWGS84 related changes

---

autotest/gcore/overviewds.py
gdal/gcore/gdaloverviewdataset.cpp

Addresses last point of https://lists.osgeo.org/pipermail/gdal-dev/2019-May/050218.html

Overview dataset (-oo OVERVIEW_LEVEL): expose mask if the source dataset has a mask with overviews

---

gdal/swig/python/scripts/gdal2tiles.py

See #2020
Fix bytes/MB mismatch in cache calculation
#2020

Update cache calculation in gdal2tiles.py

---

gdal/doc/source/programs/gdal_viewshed.rst

Were those typos?
Also, does -md need to be a multiple of the resolution?
* OS:
* Compiler:

Update gdal_viewshed.rst for typos

---

gdal/alg/viewshed.cpp

#1737  What does this PR do?
fixes #2027 and updates description comments to GDALViewshedGenerate
#2027 
N/A

Fix for RasterIO error when writing target raster in certain cases (#2027)

---

gdal/doc/source/programs/gdal_polygonize.rst

Just text typo fix
* OS:
* Compiler:

Update gdal_polygonize.rst - typo fix

---

README.md

readme URL fix - issues

---

gdal/doc/source/drivers/vector/csv.rst

Document the easiest way to read CSV files which contain plain XYZ data without header line.

Doc: How to open XYZ file without header line

---

gdal/ogr/ogrsf_frmts/flatgeobuf/geometryreader.cpp
gdal/ogr/ogrsf_frmts/flatgeobuf/geometrywriter.cpp
gdal/ogr/ogrsf_frmts/flatgeobuf/geometrywriter.h
gdal/ogr/ogrsf_frmts/flatgeobuf/ogrflatgeobuflayer.cpp

~~Intends to fix issue 19198 in oss-fuzz.~~ (had proper fix in master already)
Also includes minor serialization cleanup that reduces file size somewhat and prepares for mixed geometry collections.

FlatGeobuf: Serialization cleanup

---

gdal/doc/source/programs/gdallocationinfo.rst

Not sure if .tsv and .txt are supposed to both be used, probably just one of them.
* OS:
* Compiler:

changed file extension in example

---

gdal/ogr/ogrsf_frmts/flatgeobuf/geometryreader.cpp
gdal/ogr/ogrsf_frmts/flatgeobuf/geometryreader.h
gdal/ogr/ogrsf_frmts/flatgeobuf/geometrywriter.h

@mloskot my C++ is rusty (unique_ptr wasn't around 20 years ago), but I now think I see the point of it and I hope I'm doing this correctly.

FlatGeobuf: Simplify memory management with unique_ptr

---

gdal/doc/source/drivers/raster/cosar.rst

Docs: Fix type sizes in cosar.rst

---

gdal/swig/include/python/gdal_python.i
gdal/swig/python/osgeo/gdal.py

https://gdal.org/programs/gdalwarp.html#cmdoption-gdalwarp-wm
Fixes documentation
N/A
N/A

Fix warpMemoryLimit python documentation

---

gdal/frmts/cals/calsdataset.cpp
gdal/gcore/gdal.h
gdal/swig/include/gdal.i

This PR fixes minor quirks found while starting to use the GDAL raster API.

Fix documentation and meta data quirks

---

gdal/doc/source/development/rfc/rfc28_sqlfunc.rst
gdal/doc/source/drivers/vector/db2.rst
gdal/doc/source/drivers/vector/geomedia.rst
gdal/doc/source/drivers/vector/ingres.rst
gdal/doc/source/drivers/vector/mssqlspatial.rst
gdal/doc/source/drivers/vector/mysql.rst
gdal/doc/source/drivers/vector/oci.rst
gdal/doc/source/drivers/vector/odbc.rst
gdal/doc/source/drivers/vector/pg.rst
gdal/doc/source/drivers/vector/pgeo.rst
gdal/doc/source/drivers/vector/sqlite.rst
gdal/doc/source/drivers/vector/vrt.rst
gdal/doc/source/drivers/vector/walk.rst

Update links for SQL dialects

---

gdal/ogr/ogrsf_frmts/flatgeobuf/ogrflatgeobuflayer.cpp
gdal/ogr/ogrsf_frmts/flatgeobuf/packedrtree.cpp
gdal/ogr/ogrsf_frmts/flatgeobuf/packedrtree.h

FlatGeobuf: Minor optimization to tree search

---

autotest/ogr/data/testfgb/testmixed.geojson
autotest/ogr/ogr_flatgeobuf.py
gdal/ogr/ogrsf_frmts/flatgeobuf/ogrflatgeobuflayer.cpp

FlatGeobuf: Support mixed geometries

---

gdal/ogr/ogrsf_frmts/flatgeobuf/ogrflatgeobuflayer.cpp

ref https://github.com/OSGeo/gdal/issues/2254

FlatGeobuf: Advertize strings as UTF8

---

gdal/ogr/ogrsf_frmts/mitab/mitab_spatialref.cpp

Fix incorrect identification of MapInfo GDA2020 CRS

---

gdal/doc/source/drivers/vector/mssqlspatial.rst

Docs: Add more examples of working connection strings

---

gdal/ogr/ogrsf_frmts/flatgeobuf/packedrtree.cpp

ref https://github.com/OSGeo/gdal/issues/2282
I believe this is will resolve the issue, but should find a testcase to verify.

FlatGeobuf: Fix FID stability on spatial searches

---

gdal/configure
gdal/configure.ac

configure.ac: optimize the jni_lib compatibility.

---

gdal/doc/source/programs/gdal2tiles.rst
gdal/swig/python/scripts/gdal2tiles.py

Add the option tilesize in gdal2tiles.py to specify the tile size in Pixel / Tile on the command line.

Added option for setting the tile size (default is 256 Pixel per Tile)

---

gdal/configure
gdal/configure.ac

Added search for proj library in lib64 directory.

---

gdal/doc/source/user/virtual_file_systems.rst

Adding documentation for swift large object usage.
#2202

Adding note to use the '--use-slo' option for swift large objects.

---

autotest/gdrivers/dted.py
gdal/doc/source/drivers/raster/dted.rst
gdal/frmts/dted/dteddataset.cpp

Attempt to address #2384 for the DTED driver with ``DTED_APPLY_PIXEL_IS_POINT=TRUE`` environment variable.

Add DTED_APPLY_PIXEL_IS_POINT environment switch to provide

---

gdal/doc/source/programs/ogrtindex.rst

Corrects simple spelling mistake in documentation.

Spelling correction in docs.

---

gdal/doc/source/community.rst

Now accessible via OSGeo UserID credentials !

Mention Matrix room along with IRC channel

---

gdal/ogr/ogrsf_frmts/s57/s57reader.cpp

* OS: Ubuntu 18.04
* Compiler: GCC 7.5

Added field "ATTF" in case missing when applying updates (fixes #2249)

---

gdal/docker/README.md

Add usage instructions to docker readme.
https://github.com/OSGeo/gdal/issues/2419

Update docker README

---

gdal/doc/source/programs/gdalwarp.rst

Change Sse for Set.
I am newbie with gdal, and not English speaker, so sorry if this is not a typo.

Fix typo on gdalwarp.rst

---

gdal/doc/source/drivers/raster/jp2openjpeg.rst

Simple typo fix.
None
* OS:
* Compiler:

fix typo in docs

---

gdal/configure
gdal/configure.ac
gdal/m4/ax_lib_sqlite3.m4

Fixes https://github.com/OSGeo/gdal/pull/2395#issuecomment-620557715

configure: use sed -E or sed -r depending on runtime availability

---

gdal/configure
gdal/configure.ac
gdal/frmts/jpegls/jpegls_header.h
gdal/frmts/jpegls/jpeglsdataset.cpp
gdal/nmake.opt

Supersedes https://github.com/OSGeo/gdal/pull/2449

Add support for CharLS 2.1

---

gdal/ogr/ogrsf_frmts/flatgeobuf/feature_generated.h
gdal/ogr/ogrsf_frmts/flatgeobuf/flatbuffers/base.h
gdal/ogr/ogrsf_frmts/flatgeobuf/flatbuffers/code_generators.h
gdal/ogr/ogrsf_frmts/flatgeobuf/flatbuffers/flatbuffers.h
gdal/ogr/ogrsf_frmts/flatgeobuf/flatbuffers/flatc.h
gdal/ogr/ogrsf_frmts/flatgeobuf/flatbuffers/flexbuffers.h
gdal/ogr/ogrsf_frmts/flatgeobuf/flatbuffers/grpc.h
gdal/ogr/ogrsf_frmts/flatgeobuf/flatbuffers/hash.h
gdal/ogr/ogrsf_frmts/flatgeobuf/flatbuffers/idl.h
gdal/ogr/ogrsf_frmts/flatgeobuf/flatbuffers/minireflect.h
gdal/ogr/ogrsf_frmts/flatgeobuf/flatbuffers/reflection.h
gdal/ogr/ogrsf_frmts/flatgeobuf/flatbuffers/reflection_generated.h
gdal/ogr/ogrsf_frmts/flatgeobuf/flatbuffers/stl_emulation.h
gdal/ogr/ogrsf_frmts/flatgeobuf/flatbuffers/util.h
gdal/ogr/ogrsf_frmts/flatgeobuf/header_generated.h

FlatBuffers 1.12 was released a while ago and I made the update for FlatGeobuf but forgot to bring it here unfortunately. Sorry to be too late to the 3.1 party with this. :(

FlatGeobuf: updated against FlatBuffers 1.12

---

gdal/alg/gdaltransformer.cpp

Fix a man pages build failure on Debian/Ubuntu
#2491 
Tested in my environment only (Ubuntu 19.10 / Debian 10)
* OS: Debian 10 / Ubuntu 19.10
* Doxygen 1.8.13
* breathe                       4.18.0        
* Sphinx                        3.0.3         
* sphinx-rtd-theme              0.4.3         
* sphinxcontrib-applehelp       1.0.2         
* sphinxcontrib-devhelp         1.0.2         
* sphinxcontrib-htmlhelp        1.0.3         
* sphinxcontrib-jsmath          1.0.1         
* sphinxcontrib-qthelp          1.0.3         
* sphinxcontrib-serializinghtml 1.1.4

fix incomplete definition for Sphinx

---

.travis.yml
autotest/gcore/tiff_ovr.py
autotest/gcore/tiff_write.py
autotest/gdrivers/exr.py
autotest/gdrivers/gpkg.py
autotest/gdrivers/mrf.py
autotest/gdrivers/pdf.py
autotest/gdrivers/vrtpansharpen.py
autotest/ogr/ogr_mvt.py
gdal/ci/travis/s390x/before_install.sh
gdal/ci/travis/s390x/install.sh
gdal/ci/travis/s390x/script.sh
gdal/frmts/hdf5/bagdataset.cpp
gdal/frmts/hdf5/gh5_convenience.cpp
gdal/frmts/hdf5/hdf5multidim.cpp
gdal/frmts/netcdf/netcdfsg.cpp
gdal/frmts/pds/vicardataset.cpp
gdal/ogr/ogrsf_frmts/gmlas/ogrgmlasdatasource.cpp
gdal/ogr/ogrsf_frmts/shape/shpopen.c
gdal/ogr/ogrsf_frmts/sxf/ogrsxfdatasource.cpp
gdal/ogr/ogrsf_frmts/sxf/ogrsxflayer.cpp

Not all drivers are big-endian ready though. See ci/travis/s390x/script.sh for a few blacklisted ones

Big-endian related fixes and enable Travis-CI s390x / IBM Z configuration

---

gdal/nmake.opt
gdal/swig/makefile.vc

Adds `PYEXEC` to nmake.opt to specify the name of the executable in `PYDIR`. The purpose of this is to allow easy configuration when building python bindings using a debug build of python i.e. "python.exe" -> "python_d.exe". By default this new variable is set to "python.exe" which is the same used in the swig/makefile.vc. 
*note* several superfluous removal of whitespace/line endings were included by accident due to my IDE but then I saw that these were options enabled by the `.editorconfig` file, which i took to mean that clean up of this kind is welcome. Happy to revert those changes if undesired. 
* OS: Windows 10 1909
* Compiler: MSVC 1924 (Visual Studio 16.5.4)

nmake.opt and swig/makefile.vc: Add a PYEXEC var

---

autotest/cpp/test_cpl.cpp
autotest/cpp/test_gdal.cpp
autotest/gcore/cog.py
autotest/gdrivers/gpkg.py
gdal/apps/gdalinfo_lib.cpp
gdal/data/tms_LINZAntarticaMapTileGrid.json
gdal/data/tms_NZTM2000.json
gdal/doc/source/drivers/raster/cog.rst
gdal/doc/source/drivers/raster/gpkg.rst
gdal/frmts/gtiff/cogdriver.cpp
gdal/frmts/gtiff/geotiff.cpp
gdal/frmts/gtiff/gt_overview.cpp
gdal/frmts/gtiff/gt_overview.h
gdal/gcore/GNUmakefile
gdal/gcore/makefile.vc
gdal/gcore/tilematrixset.cpp
gdal/gcore/tilematrixset.hpp
gdal/ogr/ogrsf_frmts/gpkg/ogrgeopackagedatasource.cpp
gdal/ogr/ogrsf_frmts/gpkg/ogrgeopackagedriver.cpp
gdal/port/cpl_json.cpp
gdal/port/cpl_json.h

and add NZTM2000 and LINZAntarticaMapTileGrid definitions

COG (and GPKG): add support for using custom TILING_SCHEME using OGC 17-083r2 JSON encoded definitions

---

gdal/doc/source/programs/gdallocationinfo.rst

https://github.com/OSGeo/gdal-docs/pull/2
x y mandatory

gdallocationinfo.rst: x y mandatory

---

gdal/ogr/ogrsf_frmts/gpkg/ogrgeopackagedatasource.cpp

Fixes https://github.com/OSGeo/gdal/issues/2518

GPKG Vector: hide also view "geometry_columns"

---

gdal/doc/source/drivers/raster/wms.rst

I hope that the ":ref" leads to correct result and fixes https://github.com/OSGeo/gdal/issues/2526.

Doc: link WMS doc with WMTS doc

---

gdal/doc/source/programs/gdalmanage.rst

(Some of the lines didn't even have a matching pair too.)

Clean up unneeded and non-ASCII quote mess

---

gdal/doc/source/programs/gdal_edit.rst

Else wrecks whole line upon rendering.

Clean up destructive "-"

---

gdal/doc/source/programs/gdaltransform.rst

Group parts of otherwise hard to parse/understand sentence

---

gdal/doc/source/programs/gdalbuildvrt.rst

with is -> which is

---

gdal/doc/source/programs/gdalbuildvrt.rst

prioritary -> priority

---

gdal/doc/source/user/virtual_file_systems.rst

Officially document single vs. double slash chains

---

gdal/doc/source/faq.rst

(Else one thinks it must be miles away.)

Add colon to acknowledge that we know we are talking about the following

---

gdal/doc/source/drivers/vector/wfs.rst

Just one of the many places needed to be fixed for #2052 .
P.S., UNTESTED.

Mention how to add any HTTP(S) header

---

gdal/doc/source/drivers/raster/wmts.rst

Mention how to add arbitrary headers

---

gdal/doc/source/drivers/raster/wms.rst

Mention how to send any random HTTP header.

---

autotest/cpp/test_ogr.cpp
gdal/ogr/ogr_geometry.h

Should fix issue reported in
https://lists.osgeo.org/pipermail/gdal-dev/2020-May/052192.html

ogr_geometry.h: export OGRWktOptions class

---

gdal/doc/source/user/virtual_file_systems.rst

Helping to finish #2571 via guess as how example from #2052 works.

Document CPL_CURL_VERBOSE

---

gdal/ogr/ogrsf_frmts/osm/ogr_osm.h
gdal/ogr/ogrsf_frmts/osm/ogrosmdatasource.cpp

OSM: remove limitation to 10000 nodes per way.

---

gdal/gcore/gdal_priv.h
gdal/ogr/ogr_expat.h
gdal/ogr/ogrsf_frmts/ogrsf_frmts.h

Smart Pointers where I could have used them. By no means complete.

Memory safe alternatives for C++11 > era

---

autotest/utilities/test_gdal_translate.py
autotest/utilities/test_gdalinfo.py
autotest/utilities/test_gdalwarp.py
gdal/apps/gdal_translate_bin.cpp
gdal/apps/gdal_translate_lib.cpp
gdal/apps/gdal_utils_priv.h
gdal/apps/gdalinfo_bin.cpp
gdal/apps/gdalinfo_lib.cpp
gdal/apps/gdalwarp_bin.cpp
gdal/apps/gdalwarp_lib.cpp
gdal/doc/source/programs/gdal_translate.rst
gdal/doc/source/programs/gdalinfo.rst
gdal/doc/source/programs/gdalwarp.rst
gdal/doc/source/programs/options/if.rst

gdalinfo, gdal_translate, gdalwarp: add a -if switch to be able to specify input driver(s)

---

gdal/frmts/ecw/ecwcreatecopy.cpp
gdal/frmts/ecw/ecwdataset.cpp
gdal/frmts/ecw/gdal_ecw.h

Fix stream code, minor spelling & comment fixes. Merging this PR will mean it is up to date with our repo which we can then work from in future.
* OS:
* Compiler:

Update ECW driver: Fix stream code & minor cosmetic changes

---

gdal/ogr/ogrfeature.cpp

OGRFeature::GetFieldAsString(): remove 80 character limitation when formatting string/integer/real lists

---

.github/workflows/code_checks.yml
gdal/configure
gdal/configure.ac

configure: add  in LIBS when detecting PROJ when no path is specified

---

gdal/Doxyfile
gdal/gcore/gdal.h
gdal/gcore/gdal_priv.h
gdal/ogr/ogr_geometry.h
gdal/ogr/ogr_spatialref.h
gdal/port/cpl_conv.h

Doc building: fix warnings when using recent Doxygen and/or Sphinx+Breathe

---

gdal/data/ruian_vf_ob_v1.gfs
gdal/data/ruian_vf_v1.gfs

Fixes typos in VFR GFS files
#2682

fix typo in VFR GFS files BonitovaneDilRizeniId -> BonitovanyDilRizeniId

---

gdal/doc/source/tutorials/osr_api_tut.rst

I think GDAL is better at geospatial data processing than it is at spelling. :) 
Thank for the nice tools. I use them daily.

Fix a couple of spelling mistakes

---

autotest/gcore/vsis3.py
gdal/doc/source/user/virtual_file_systems.rst
gdal/frmts/gtiff/geotiff.cpp
gdal/gcore/mdreader/reader_geo_eye.cpp
gdal/port/GNUmakefile
gdal/port/cpl_vsi_virtual.h
gdal/port/cpl_vsil_az.cpp
gdal/port/cpl_vsil_gs.cpp
gdal/port/cpl_vsil_oss.cpp
gdal/port/cpl_vsil_s3.cpp
gdal/port/cpl_vsil_swift.cpp
gdal/port/cpl_vsil_uploadonclose.cpp
gdal/port/cpl_vsil_webhdfs.cpp
gdal/port/makefile.vc

(for GTiff creation in particular) through temporary local file when CPL_VSIL_USE_TEMP_FILE_FOR_RANDOM_WRITE config option is set to YES

 /vsis3/ and other cloud file system: allow random-write access

---

gdal/alg/gdalwarpoperation.cpp

Separate nResWinSize in X and Y directions, so as to avoid situation
where we grab the whole raster width because of anti-meridian discontinuity to
cause to grab the whole raster height too ! So as to avoid excessive memory usage
Related to #2754 but doesn't fix it.

GDALWarpOperation::ComputeSourceWindow(): modify extra source pixel computation

---

autotest/ogr/ogr_sql_sqlite.py
autotest/ogr/ogr_sql_test.py
autotest/ogr/ogr_vrt.py
gdal/ogr/ogrsf_frmts/sqlite/ogrsqlitevirtualogr.cpp
gdal/ogr/ogrsf_frmts/vrt/ogrvrtlayer.cpp
gdal/ogr/swq.cpp
gdal/swig/include/python/ogr_python.i
gdal/swig/python/osgeo/ogr.py

Adresses the use case of https://lists.osgeo.org/pipermail/gdal-dev/2020-July/052401.html
Continuation of https://github.com/OSGeo/gdal/issues/1057

OGR: better support for layers with field names differing by case in OGR SQL, SQL SQLite and VRT

---

autotest/ogr/ogr_fgdb.py
gdal/apps/ogrinfo.cpp
gdal/ogr/ogrsf_frmts/filegdb/FGdbLayer.cpp

and:  ogrinfo: report field alternative name

FileGDB: add support for reading and writing field alternative names

---

gdal/frmts/netcdf/netcdfdataset.cpp
gdal/frmts/netcdf/netcdfmultidim.cpp

When NCDF_DEBUG  is defined compilation fails

Fix compilation with NCDF_DEBUG defined

---

gdal/ogr/ogrsf_frmts/flatgeobuf/packedrtree.cpp

ref https://github.com/OSGeo/gdal/issues/2773

FlatGeobuf: Fix from upstream

---

autotest/gcore/vsiaz.py
gdal/doc/source/user/virtual_file_systems.rst
gdal/port/cpl_aws.cpp
gdal/port/cpl_aws.h
gdal/port/cpl_azure.cpp
gdal/port/cpl_azure.h
gdal/port/cpl_vsil_az.cpp
gdal/port/cpl_vsil_curl_class.h
gdal/port/cpl_vsil_s3.cpp

Both to be used with AZURE_STORAGE_ACCOUNT

/vsiaz/: add a AZURE_NO_SIGN_REQUEST=YES config option for unsigned public buckets and AZURE_SAS to provided Shared Access Signature

---

gdal/gcore/gdalrasterband.cpp

Just about a typo I saw when reading the docs. I'm almost ashamed of so little added value for the merge effort :-)

Fix a small typo

---

gdal/doc/source/programs/gdal_calc.rst
gdal/swig/python/scripts/gdal_calc.py

There was a question on gis.stackexchange.com about logical operator in gdal_calc expressions. It would be nice to extend the doc with an example.

New example with logical operator for gdal_calc.py

---

autotest/gcore/cog.py
gdal/doc/source/drivers/raster/cog.rst
gdal/frmts/gtiff/geotiff.cpp

See https://github.com/cogeotiff/rio-cogeo/issues/151#issuecomment-669240560

TIFF/COG: report content of the header ghost area in metadata

---

gdal/ogr/ogrsf_frmts/geomedia/ogrgeomediadatasource.cpp
gdal/ogr/ogrsf_frmts/odbc/ogrodbcdatasource.cpp
gdal/ogr/ogrsf_frmts/walk/ogrwalkdatasource.cpp

I missed these in the original PR, sorry!

Followup 69d00e30c: also quote DBQ values in other drivers

---

gdal/doc/source/drivers/vector/pgeo.rst

...which works correctly with gdal for reading Personal Geodatabase files

[pgeo][docs] Add note about maintained mdbtools fork 

---

gdal/doc/source/drivers/vector/pgeo.rst

Refs discussion at https://github.com/OSGeo/gdal/pull/2854#issuecomment-673335197

[pgeo][doc] Remove outdated instructions regarding MDBTools and DSN setup requirements

---

autotest/ogr/ogr_gpkg.py
autotest/ogr/ogr_sqlite.py
gdal/doc/source/drivers/vector/gpkg.rst
gdal/doc/source/drivers/vector/pg.rst
gdal/doc/source/drivers/vector/sqlite.rst
gdal/ogr/ogrsf_frmts/gpkg/ogrgeopackagedatasource.cpp
gdal/ogr/ogrsf_frmts/gpkg/ogrgeopackagedriver.cpp
gdal/ogr/ogrsf_frmts/sqlite/ogrsqlitedatasource.cpp
gdal/ogr/ogrsf_frmts/sqlite/ogrsqlitedriver.cpp

... that can be used for example to attach other databases

SQLite and GPKG drivers: add a PRELUDE_STATEMENTS open option

---

autotest/ogr/data/lvbag/pnd2.xml
autotest/ogr/ogr_lvbag.py
gdal/doc/source/drivers/vector/lvbag.rst
gdal/ogr/ogrsf_frmts/lvbag/ogrlvbaglayer.cpp

LVBAG: Fixes #2804

---

autotest/ogr/ogr_pgeo.py

If only one driver was available then the first attempt to switch
would deregister the available driver, and it was then no
longer available for retrieval via GetDriverByName for subsequent
attempts to switch back to it

Fix PGeo test execution when only Pgeo OR MDB driver is available, not both

---

gdal/ogr/ogrsf_frmts/flatgeobuf/ogrflatgeobuflayer.cpp

ref https://github.com/OSGeo/gdal/issues/2874

FlatGeobuf: Init and merge extent on feature write

---

gdal/alg/marching_squares/point.h
gdal/alg/marching_squares/polygon_ring_appender.h

This patch reworks `polygon_ring_appender` to avoid some cases that caused
massive slowness. This involved doing 2 main things:
1. The `isIn` check has been reworked to avoid a dependency on OGR and
instead the winding number algorithm has been implemented directly. The
code itself was based on the reference code at geomalgorithms.com
2. Rather than sort all the rings in the destructor, the `addLine`
function has been reworked to put each new ring in the correct position
as it is added. To enable this, the `Ring` class was reworked to hold a
vector of child instances directly, effectively building a tree of
rings. Then in the destructor, we can simply walk the tree and write out
every other level as a polygon.
#2241
* OS: Ubuntu 18.04
* Compiler: …

Rework polygon_ring_appender to avoid slowness

---

gdal/frmts/mrf/marfa.h
gdal/frmts/mrf/marfa_dataset.cpp
gdal/frmts/mrf/mrf_band.cpp

Fixes for MRF Create function.
In MRF, calling Create and closing the file without writing any data would not actually create the files.
In addition, there were a few cases where an exception raised when trying to create the file was not caught.
* OS:
* Compiler:

Mrf: Fixes for Create()

---

autotest/ogr/ogr_gpkg.py
autotest/ogr/ogr_pg.py
gdal/gcore/gdal.h
gdal/gcore/gdal_priv.h
gdal/gcore/gdaldataset.cpp
gdal/ogr/ogr_api.h
gdal/ogr/ogrsf_frmts/generic/ogrdatasource.cpp
gdal/ogr/ogrsf_frmts/pg/ogr_pg.h
gdal/ogr/ogrsf_frmts/pg/ogrpgdatasource.cpp
gdal/ogr/ogrsf_frmts/sqlite/ogr_sqlite.h
gdal/ogr/ogrsf_frmts/sqlite/ogrsqlitedatasource.cpp
gdal/swig/include/Dataset.i
gdal/swig/include/ogr.i
gdal/swig/python/extensions/gdal_wrap.cpp
gdal/swig/python/extensions/ogr_wrap.cpp
gdal/swig/python/osgeo/gdal.py
gdal/swig/python/osgeo/ogr.py

This PR adds a method to interrupt running queries
launched by ExecuteSQL.

Add AbortSQL (initial proof of concept)

---

gdal/swig/python/scripts/gdalcompare.py

gdal/swig/python/scripts/gdalcompare.py - export def find_diff(goldenfile, new_file, check_sds=False) into a function for reuse

gdalcompare.py - export find_diff into a function

---

gdal/frmts/aaigrid/aaigriddataset.cpp

Only scan the bytes actually read by VSIFReadL.
Fixes #2970

aaigriddataset: Improve search for float data.

---

autotest/ogr/ogr_flatgeobuf.py
gdal/ogr/ogrsf_frmts/flatgeobuf/header_generated.h
gdal/ogr/ogrsf_frmts/flatgeobuf/ogrflatgeobuflayer.cpp

ref https://github.com/bjornharrtell/flatgeobuf/pull/75

FlatGeobuf: metadata extensions

---

autotest/ogr/ogr_flatgeobuf.py
gdal/ogr/ogrsf_frmts/flatgeobuf/header_generated.h
gdal/ogr/ogrsf_frmts/flatgeobuf/ogrflatgeobuflayer.cpp

Backport of https://github.com/OSGeo/gdal/pull/2929 to release/3.1

FlatGeobuf: metadata extensions backport

---

gdal/doc/source/user/virtual_file_systems.rst

Minor doc fix to vsizip for shapefile example

DOC: shp/ subdir for poly.zip

---

autotest/gcore/tiff_write.py

jpeg test enhancement backported from #3014

gtiff jpeg ovr test: check quality can be overidden

---

gdal/frmts/dted/dteddataset.cpp

#2887  What does this PR do?
Adds support for E08 dted metadata

DTED: add support for EGM08 for dted metadata "E08"

---

gdal/gcore/gdaldataset.cpp
gdal/ogr/ogr_api.cpp
gdal/ogr/ogr_geocoding.cpp
gdal/ogr/ograssemblepolygon.cpp
gdal/ogr/ogrfeature.cpp
gdal/ogr/ogrfeaturedefn.cpp
gdal/ogr/ogrfeaturestyle.cpp
gdal/ogr/ogrgeometry.cpp
gdal/ogr/ogrsf_frmts/ogrsf_frmts.dox
gdal/swig/include/python/docs/ogr_datasource_docs.i
gdal/swig/include/python/docs/ogr_feature_docs.i
gdal/swig/include/python/docs/ogr_featuredef_docs.i
gdal/swig/include/python/docs/ogr_geometry_docs.i
gdal/swig/include/python/docs/ogr_layer_docs.i
gdal/swig/java/javadoc.java
gdal/swig/python/extensions/ogr_wrap.cpp
gdal/swig/python/osgeo/ogr.py

Replace the phrase "an handle" with "a handle" everywhere, using a combination of sed commands.
I'm not exactly sure if any of the files modified are generated, like the .i files in gdal/swig/include/python/docs.
Let me know and I'll drop them from my fork.

Doc: replace 'an handle' with 'a handle' everywhere in the project

---

autotest/gcore/hdf4_read.py
autotest/gcore/hdf4multidim.py
gdal/doc/source/drivers/raster/hdf4.rst
gdal/frmts/hdf4/hdf4dataset.cpp
gdal/frmts/hdf4/hdf4dataset.h
gdal/frmts/hdf4/hdf4multidim.cpp

Unless the new open option LIST_SDS is set to YES
Fixes https://lists.osgeo.org/pipermail/gdal-dev/2020-October/052736.html

HDF4: do not report SDS when there are EOS_SWATH or EOS_GRID in it

---

gdal/doc/source/drivers/raster/ogcapi.rst
gdal/frmts/ogcapi/gdalogcapidataset.cpp
gdal/ogr/ogrsf_frmts/wfs/ogroapifdriver.cpp

This bridges the OGCAPI driver with the existing OAPIF driver

OGCAPI: support handling of vector content through items API

---

gdal/ogr/ogrct.cpp
gdal/ogr/ogrspatialreference.cpp

Do not merge before https://github.com/OSGeo/PROJ/pull/2370 is merged

OSR: make it robust to dealing with datum ensemble objects. Depends on https://github.com/OSGeo/PROJ/pull/2370 / PROJ 7.2

---

.github/workflows/validate_xml.yml

This PR adds a Github workflow to validate XML files against an XSD with xmllint.
Example failure mode here:
https://github.com/matthew-baran/gdal/actions/runs/313204128
Happy Birthday GDAL!
https://github.com/OSGeo/gdal/pull/3071
* OS:
* Compiler:

CI: Add a Github workflow for XML validation

---

gdal/NEWS

added updated OGR GRASS driver entry [ci skip]

---

gdal/doc/source/drivers/raster/gtiff.rst
gdal/gcore/gdaldataset.cpp
gdal/swig/java/javadoc.java
gdal/swig/python/README.rst

This PR fixes documentation errors, and it extents GTiff driver documentation with an alternative way of helping GDAL find `proj.db`.

Improve documentation

---

autotest/gcore/rasterio.py
gdal/gcore/rasterio.cpp
gdal/swig/include/gdal_array.i
gdal/swig/include/python/gdal_python.i
gdal/swig/python/extensions/gdal_array_wrap.cpp
gdal/swig/python/extensions/gdal_wrap.cpp
gdal/swig/python/osgeo/gdal.py
gdal/swig/python/osgeo/gdal_array.py

GDALDataset::RasterIO(): make it take into account properly floating-point window coordinates in nearest resampling case

---

autotest/utilities/test_gdal_viewshed.py
gdal/doc/source/programs/gdal_viewshed.rst

gdal_viewshed.rst - added info about refraction_coeff.
test_gdal_viewshed.py - refactor and fix test_gdal_viewshed_invalid_input
* OS: Win10

gdal_viewshed - added refraction_coeff docs and test refactor

---

gdal/doc/source/programs/gdal_viewshed.rst

Rephrased some of the text and added a table with typical refraction values.
Sorry for not including in the previous PR.

gdal_viewshed.rst - refraction coeff - table with typical values.

---

gdal/doc/source/_extensions/redirects.py

@rouault , as per discussed in https://github.com/qgis/QGIS/pull/39104

Add a drv_shape.html to drivers/vector/shapefile.html redirect

---

gdal/doc/source/programs/gdal2tiles.rst
gdal/doc/source/programs/gdal_grid.rst
gdal/doc/source/programs/gdal_merge.rst
gdal/doc/source/programs/gdal_polygonize.rst
gdal/doc/source/programs/gdal_proximity.rst
gdal/doc/source/programs/gdal_rasterize.rst
gdal/doc/source/programs/gdal_retile.rst
gdal/doc/source/programs/gdalcompare.rst
gdal/doc/source/programs/nearblack.rst
gdal/doc/source/programs/pct2rgb.rst
gdal/doc/source/programs/rgb2pct.rst

gdal/doc/source/programs/*.rst - correct the `program::` section of the documentation.
These sections appear incorrect.

gdal/doc/source/programs/*.rst - correct the `program::` section

---

gdal/doc/source/tutorials/geotransforms_tut.rst
gdal/doc/source/tutorials/index.rst
gdal/doc/source/tutorials/raster_api_tut.rst

adds some documentation about geotransforms
gdal/doc/source/tutorials/geotransforms_tut.rst - new tutorial with some info about geotransforms.
gdal/doc/source/tutorials/[index.rst, raster_api_tut.rst] - reference geotransforms_tut.rst

gdal/doc/source/tutorials/geotransforms_tut.rst - new tutorial with some info about geotransforms.

---

autotest/ogr/ogr_flatgeobuf.py
gdal/ogr/ogrsf_frmts/flatgeobuf/GNUmakefile
gdal/ogr/ogrsf_frmts/flatgeobuf/makefile.vc
gdal/ogr/ogrsf_frmts/flatgeobuf/ogr_flatgeobuf.h
gdal/ogr/ogrsf_frmts/flatgeobuf/ogrflatgeobufdataset.cpp
gdal/ogr/ogrsf_frmts/flatgeobuf/ogrflatgeobufeditablelayer.cpp
gdal/ogr/ogrsf_frmts/flatgeobuf/ogrflatgeobuflayer.cpp

ref https://github.com/OSGeo/gdal/issues/3097

FlatGeobuf; editable capabilities

---

autotest/gdrivers/fits.py
gdal/doc/source/drivers/raster/fits.rst
gdal/frmts/fits/fitsdataset.cpp

FITS: add support for creation and update of binary tables

---

autotest/utilities/test_gdal_rasterize_lib.py
gdal/apps/gdal_rasterize_lib.cpp

gdal_rasterize: make -i work again (fixes #3124)

---

gdal/doc/source/drivers/raster/mbtiles.rst

Docs: Document that MBTiles vector is write-once

---

gdal/doc/source/user/ogr_sql_dialect.rst

Please check the syntax of references to the C++ API.

Doc: Updates to SQL OGR page

---

autotest/cpp/test_gdal.cpp
autotest/gdrivers/pcidsk.py
gdal/frmts/pcidsk/pcidskdataset2.cpp
gdal/frmts/pcidsk/pcidskdataset2.h

(while SetMetadata/SetMetadataItem is not called)

PCIDSK: make GetMetadataItem() returns the same const char* for a given key

---

autotest/gcore/overviewds.py
gdal/gcore/gdaldataset.cpp
gdal/gcore/gdaloverviewdataset.cpp

Adresses https://rasterio.groups.io/g/main/message/649

GDALOpenEx(): supports OVERVIEW_LEVEL=NONE to indicate overviews shouldn't be exposed

---

gdal/frmts/gtiff/geotiff.cpp

These tags are useful if we need to rewrite the file.

GTiff: Export compression tags to metadata

---

autotest/gdrivers/wmts.py
gdal/frmts/wms/gdalhttp.cpp

Identify local wmts tiles not found with CURLE_FILE_COULDNT_READ_FILE and map to http status 404
fixes #2941
older discussion #2958
Built on windows.
Built and tested on linux (ubuntu/docker(

Jano Simas WMTS: Map CURLE_FILE_COULDNT_READ_FILE to 404

---

.github/workflows/asan/start.sh
.github/workflows/asan_build.yml
.github/workflows/mingw_w64.yml
.github/workflows/mingw_w64/start.sh
.github/workflows/ubuntu_18.04/install.sh
.github/workflows/ubuntu_18.04_32bit.yml
.github/workflows/ubuntu_18.04_32bit/start.sh
.travis.yml
autotest/asan_suppressions.txt
autotest/gcore/pixfun.py
autotest/ogr/ogr_geom.py
gdal/alg/internal_libqhull/poly.c
gdal/port/cpl_userfaultfd.cpp

- Add mingw_w64, ubuntu_18.04_32bit and asan_build
- Optimize caching of ubuntu_18.04
- Disable all remaining configurations of .travis.yml except s390x

Migrate all relevant remaining Travis-CI jobs to github workflow actions

---

gdal/doc/source/api/python_gotchas.rst

Fixes a small typo in the python_gotchas.rst document.
* OS:
* Compiler:

Update python_gotchas.rst- fix small typo

---

autotest/pyscripts/test_gdal_calc.py

Remove global code from ` test_gdal_calc.py`
Fix #3223 
#3223

do not use global code in pytest

---

gdal/doc/source/development/rfc/rfc77_drop_python2_support.rst

Update the status of RFC77.
I'm not sure if I gave proper credits.
https://gdal.org/development/rfc/rfc77_drop_python2_support.html
https://github.com/OSGeo/gdal/pull/3165
https://github.com/OSGeo/gdal/pull/3237
https://github.com/OSGeo/gdal/pull/3241
https://github.com/OSGeo/gdal/issues/3114

rfc/rfc77_drop_python2_support.rst - status update

---

.github/workflows/ubuntu_18.04/start.sh
autotest/gdrivers/bag.py
autotest/utilities/test_ogr2ogr_lib.py
gdal/apps/ogr2ogr_bin.cpp
gdal/apps/ogr2ogr_lib.cpp
gdal/doc/source/programs/ogr2ogr.rst
gdal/swig/include/python/gdal_python.i
gdal/swig/python/osgeo/gdal.py

Follow up to https://github.com/OSGeo/gdal/pull/2209.
Testcase verified working locally.

ogr2ogr: -emptyStrAsNull option

---

gdal/ogr/ogrsf_frmts/cad/libopencad/cadobjects.cpp
gdal/ogr/ogrsf_frmts/cad/libopencad/dwg/r2000.cpp
gdal/third_party/LercLib/Lerc2.h

Fixes the gdal build with gcc11 and recent clang (didn't check the exact clang version). This is needed since these files use `std::numeric_limits` without importing `<limits>`.
* OS: Linux
* Compiler: gcc11 and/or clang

Add some missing <limits> includes

---

.github/workflows/conda.yml
gdal/ci/travis/conda/upload.sh

Follow-on fixups for #3276. Once upload is working I will put the branch conditional back. @rouault please let me merge this when ready.

Fix upload of conda package to Anaconda

---

.github/workflows/code_checks.yml
.github/workflows/conda.yml
gdal/ci/travis/conda/upload.sh

Hope this is now working as expected.

gdal-master Conda package upload

---

gdal/gcore/overview.cpp

Followup https://github.com/OSGeo/gdal/commit/e984e8fba5b45396cfe0e8872911a2d894ca7429 https://github.com/OSGeo/gdal/commit/2e935688ad60db272d746df3a3ee3bdf78c0812e

Doc: add missing "RMS" resampling alg in GDALRegenerateOverviewsMultiBand()

---

gdal/swig/python/osgeo/utils/gdal2xyz.py

gdal2xyz.py improvements and documentation
* skip_ndv - allow to skip lines with uninteresting data values
True/False - skip lines with NDV data points;
Sequence/Number - skip lines with given value (per band or per ds)
* support more flexible input options for srcfile, skip, band_nums
* type hinting added
* add --allBands command line option
* add main function

gdal2xyz.py improvements and documentation

---

gdal/ci/travis/conda/upload.sh

Package upload wasn't working due to need for anaconda client install into environment.

need anaconda client for package upload

---

gdal/swig/python/scripts/gdal2tiles.py

Adds some basic type annotations to the main running functions and easily typed functions of gdal2tiles.
Currently, this does not bring much but it's a good start I believe. Would this be accepted?
It might prove useful to allow quicker introductions into the scripts. 
N/A

gdal2tiles: Start on basic type annotations

---

gdal/swig/python/osgeo/utils/auxiliary/base.py
gdal/swig/python/osgeo/utils/auxiliary/numpy_util.py
gdal/swig/python/osgeo/utils/auxiliary/util.py

a few minor fixes for https://github.com/OSGeo/gdal/pull/3343
https://github.com/OSGeo/gdal/pull/3343

fix for #3343

---

gdal/swig/python/osgeo/utils/gdal2xyz.py

gdal2xyz.py improvements - refactor and simplify and add option to return numpy arrays of the result values
https://github.com/OSGeo/gdal/pull/3341 (prerequisite) - please review it first

gdal2xyz.py improvements - refactor and simplify and add option to return numpy arrays of the result values

---

gdal/gcore/gdalpython.cpp

Fixes https://github.com/qgis/QGIS/issues/41048

GDAL Python embedding: fix loading in QGIS/Windows (or any process with more than 100 modules)

---

autotest/alg/fillnodata.py
autotest/alg/warp.py

This shortens the tests, and provides more information to `pytest` to display when there's an error (instead of manually printing things.)
- #949
- #963
- [n/a?] Add documentation

autotest: Parameterize alg tests.

---

autotest/gdrivers/wms.py
gdal/frmts/wms/minidriver_virtualearth.cpp

Fixes https://github.com/OSGeo/gdal/issues/3432

Update default values for VirtualEarth minidriver

---

gdal/doc/source/drivers/raster/wms.rst

Reflect https://github.com/OSGeo/gdal/commit/633cfd90334ab604ad46c1cbcf36f083b27e49ab in the docs

Reflect changes of VirtualEarth driver in the docs

---

autotest/ogr/data/lvbag/vbo2.xml
autotest/ogr/data/lvbag/vbo3.xml
autotest/ogr/data/lvbag/vbo4.xml
autotest/ogr/ogr_lvbag.py
gdal/ogr/ogrsf_frmts/lvbag/ogr_lvbag.h
gdal/ogr/ogrsf_frmts/lvbag/ogrlvbaglayer.cpp

* Change the field type from string to stringlist for `gebruikersdoel`
* Add a secondary address to datasource LIG, STA, VBO.
Fixes #3221 .

LVBAG specification enhancements

---

gdal/swig/python/osgeo/utils/auxiliary/color_palette.py
gdal/swig/python/osgeo/utils/auxiliary/color_table.py
gdal/swig/python/osgeo/utils/auxiliary/extent_util.py
gdal/swig/python/osgeo/utils/auxiliary/numpy_util.py
gdal/swig/python/osgeo/utils/auxiliary/util.py

Fix some bugs in utils.auxiliary
Add some types hinting, rename PathOrDS

utils.auxiliary fixes

---

gdal/frmts/netcdf/netcdfdataset.cpp

netCDF: Set scope for raster/vector-only options in driver metadata

---

gdal/ogr/ogrsf_frmts/amigocloud/ogr_amigocloud.h
gdal/ogr/ogrsf_frmts/amigocloud/ogramigocloudtablelayer.cpp

This change fixes the json encoder to escape nested string properly.

AmigoCloud driver: fix json encoder to handle nested strings.

---

autotest/gdrivers/wms.py
gdal/doc/source/drivers/raster/wms.rst
gdal/frmts/wms/minidriver_tiled_wms.cpp
gdal/frmts/wms/wmsdriver.cpp
gdal/frmts/wms/wmsmetadataset.cpp
gdal/frmts/wms/wmsmetadataset.h
gdal/frmts/wms/wmsutils.cpp

WMS: tWMS, improves usability with NASA GIBS services
Add a couple of open options to the tiled WMS minidriver, to make it more user friendly to connect to NASA GIBS services.
-oo TiledGroupName=<Name>
When a tiledWMS handle file does not contain a TiledGroupName node, this open option can be used to pick one.
Example: -oo TiledGroupname="MODIS Terra CorrectedReflectance TrueColor tileset"
-oo Change=<key>:<value>
When a tiledWMS service offers declares parameters using the Change node, this open option can be used to provide a value.
GIBS usually allows a **time** parameter, with allowed values being ISO9601 formatted dates
Example: -oo Change=time:2021-01-30
The open options work with the WMS metadriver also, where the TiledGroupName becomes a substring filter.
This command will show as …

Wms t wms params

---

autotest/ogr/ogr_geom.py
gdal/ogr/ogr_api.h
gdal/ogr/ogr_geometry.h
gdal/ogr/ogrgeometry.cpp
gdal/swig/include/ogr.i
gdal/swig/python/extensions/ogr_wrap.cpp
gdal/swig/python/osgeo/ogr.py

This PR adds GEOSNormalize functionality to OGR as OGR_G_Normalize() and binds it to SWIG 
* OS:
* Compiler:

Add OGR_G_Normalize() and bind it to SWIG

---

gdal/ogr/ogrsf_frmts/amigocloud/ogramigoclouddatasource.cpp

SQL queries with DELETE, INSERT, UPDATE need to use HTTP POST.
SELECT should use HTTP GET.

AmigoCloud driver: Fix SQL delete

---

gdal/doc/source/community/service_providers.rst
gdal/doc/source/gdal_rtd/static/css/gdal.css

avoid description text to leak below logo and randomization for contributors and other service providers sections.

Doc: improve layout of service providers

---

.github/workflows/ubuntu_20.04.yml
gdal/swig/python/setup.py

replace `readme = open('README.rst', 'rb').read().decode('utf-8')` with `readme = open('README.rst', encoding="utf-8").read()`

gdal/swig/python/setup.py - use a better way handle readme encoding

---

gdal/doc/source/drivers/raster/til.rst

Corrects bad path in the TIL driver docs
None

Docs: correct TIL driver path

---

autotest/ogr/data/lvbag/inval_polygon2.xml
autotest/ogr/ogr_lvbag.py
gdal/ogr/ogrsf_frmts/lvbag/ogrlvbaglayer.cpp

LVBAG: Convert MultiPolygon to Polygon

---

autotest/gdrivers/memmultidim.py
gdal/swig/include/python/gdal_python.i
gdal/swig/python/osgeo/gdal.py

Python bindings: allow list or array types as input of MDArray.Write()

---

gdal/doc/source/programs/gdaltindex.rst

- example added for user convenience

gdaltindex manual: explain file based list usage

---

gdal/doc/source/software_using_gdal.rst

Also actinia happily uses GDAL

added: actinia entry

---

autotest/cpp/test_osr.cpp
gdal/ogr/ogr_spatialref.h
gdal/ogr/ogrspatialreference.cpp

OGRSpatialReference: delegate to PROJ (>= 8.1) import from OGC URN and URL.

---

gdal/doc/source/software_using_gdal.rst

Add the ViRGiS project to the list of Software using GDAL
None
Documentation only change

Add ViRGiS to software using GDAL

---

autotest/gdrivers/ngw.py
autotest/ogr/ogr_ngw.py
gdal/doc/source/drivers/vector/ngw.rst
gdal/ogr/ogrsf_frmts/ngw/gdalngwdataset.cpp
gdal/ogr/ogrsf_frmts/ngw/ngw_api.cpp
gdal/ogr/ogrsf_frmts/ngw/ogr_ngw.h
gdal/ogr/ogrsf_frmts/ngw/ogrngwdriver.cpp
gdal/ogr/ogrsf_frmts/ngw/ogrngwlayer.cpp

1. Add new functions for NGW driver (NGW feature extension support, fields alternative name support).
2. Fix random fails on unit tests. 
#3530, #1145

NGW: Add extensions support. Add alternative field name support. Fix unit test for more checks of sandbox.nextgis.com availability (Fix #3530)

---

autotest/pyscripts/test_gdal_utils.py
gdal/swig/python/gdal-utils/osgeo_utils/auxiliary/progress.py
gdal/swig/python/gdal-utils/osgeo_utils/auxiliary/raster_creation.py

Add some auxiliary functions to be used in `gdal2xyz`, `gdalcalc`, `gdallocationinfo` and others.
https://github.com/OSGeo/gdal/pull/3416

add auxiliary functions to gdal-utils

---

autotest/pyscripts/test_gdal2xyz.py
gdal/swig/python/gdal-utils/osgeo_utils/gdal2xyz.py

gdal2xyz.py - add `dst_nodata` option. 
gdal2xyz.py - add nodata to the return value of the gdal2xyz function
gdal2xyz.py - in order to be consistent with other utils - rename parameters skip_no_data -> skip_nodata; no_data_value -> src_nodata - currently only in master (not yet released).
gdal2xyz.rst - added documentation
index.rst - update with gdal2xyz.rst
added progress callback function; use exceptions when needed

gdal2xyz.py - improvements and added documentation.

---

gdal/swig/python/gdal-utils/osgeo_utils/epsg_tr.py
gdal/swig/python/gdal-utils/osgeo_utils/esri2wkt.py
gdal/swig/python/gdal-utils/osgeo_utils/samples/loslas2ntv2.py

epsg tr + esri2wkt - use ArgumentParser; add proper Help; some fixes

epsg tr+esri2wkt - use ArgumentParser; add proper Help and some fixes

---

autotest/pyscripts/test_gdal_calc.py
autotest/pyscripts/test_gdal_utils.py
gdal/swig/python/gdal-utils/osgeo_utils/auxiliary/base.py
gdal/swig/python/gdal-utils/osgeo_utils/auxiliary/batch_creator.py
gdal/swig/python/gdal-utils/osgeo_utils/auxiliary/color_palette.py
gdal/swig/python/gdal-utils/osgeo_utils/auxiliary/color_table.py
gdal/swig/python/gdal-utils/osgeo_utils/auxiliary/raster_creation.py
gdal/swig/python/gdal-utils/osgeo_utils/auxiliary/util.py
gdal/swig/python/gdal-utils/osgeo_utils/gdal2xyz.py
gdal/swig/python/gdal-utils/osgeo_utils/gdal_calc.py
gdal/swig/python/gdal-utils/osgeo_utils/samples/gdallocationinfo.py

Related to: https://github.com/OSGeo/gdal/issues/1613
https://github.com/OSGeo/gdal/pull/3717 is still draft
I've made this separate PR for the parts that are ready.

Improve support for PathLike objects in gdal-utils

---

gdal/frmts/tiledb/tiledbdataset.cpp

This PR adds /vsigs/ support to the TileDB driver, allowing it to access datasets on gcs.

Add /vsigs/ support to the tiledb driver

---

.github/workflows/ubuntu_20.04/build-deps.sh
.github/workflows/ubuntu_20.04/build.sh
gdal/alg/gdalwarpkernel_opencl.cpp
gdal/alg/gdalwarpkernel_opencl.h

and add minimal CI (compile time only) testing

gdalwarpkernel_opencl: fix compiler warnings 

---

gdal/alg/polygonize.cpp
gdal/swig/python/gdal-utils/osgeo_utils/auxiliary/util.py
gdal/swig/python/gdal-utils/osgeo_utils/samples/gdallocationinfo.py

gdallocationinfo.py - fix for input of single x,y
util.py - GetOutputDriversFor fix for filename: Path
gdal/alg/polygonize.cpp - fix docs formatting

`gdal-utils` and docs fixes

---

gdal/swig/python/gdal-utils/osgeo_utils/gdal_pansharpen.py
gdal/swig/python/gdal-utils/osgeo_utils/gdal_proximity.py
gdal/swig/python/gdal-utils/osgeo_utils/gdal_sieve.py
gdal/swig/python/gdal-utils/osgeo_utils/gdalattachpct.py
gdal/swig/python/gdal-utils/osgeo_utils/gdalcompare.py
gdal/swig/python/gdal-utils/osgeo_utils/gdalmove.py
gdal/swig/python/gdal-utils/osgeo_utils/ogrmerge.py

add type hints and make main logic functions for some gdal-utils

`gdal-utils` - add type hints

---

autotest/pymod/test_py_scripts.py
autotest/pyscripts/test_gdal_calc.py
gdal/swig/python/gdal-utils/osgeo_utils/auxiliary/gdal_argparse.py
gdal/swig/python/gdal-utils/osgeo_utils/auxiliary/raster_creation.py
gdal/swig/python/gdal-utils/osgeo_utils/gdal2xyz.py
gdal/swig/python/gdal-utils/osgeo_utils/gdal_calc.py
gdal/swig/python/gdal-utils/osgeo_utils/gdal_fillnodata.py
gdal/swig/python/gdal-utils/osgeo_utils/gdal_merge.py
gdal/swig/python/gdal-utils/osgeo_utils/gdal_polygonize.py
gdal/swig/python/gdal-utils/osgeo_utils/pct2rgb.py
gdal/swig/python/gdal-utils/osgeo_utils/rgb2pct.py
gdal/swig/python/gdal-utils/osgeo_utils/samples/densify.py
gdal/swig/python/gdal-utils/osgeo_utils/samples/epsg_tr.py
gdal/swig/python/gdal-utils/osgeo_utils/samples/esri2wkt.py
gdal/swig/python/gdal-utils/osgeo_utils/samples/fft.py
gdal/swig/python/gdal-utils/osgeo_utils/samples/gcps2vec.py
gdal/swig/python/gdal-utils/osgeo_utils/samples/gdal_lut.py
gdal/swig/python/gdal-utils/osgeo_utils/samples/gdallocationinfo.py
gdal/swig/python/gdal-utils/osgeo_utils/samples/hsv_merge.py
gdal/swig/python/gdal-utils/osgeo_utils/samples/ogr_dispatch.py
gdal/swig/python/gdal-utils/osgeo_utils/samples/ogr_layer_algebra.py
gdal/swig/python/gdal-utils/osgeo_utils/samples/rel.py
gdal/swig/python/gdal-utils/osgeo_utils/samples/val_repl.py

I've refactored most of `gdal-utils` scripts with the use of an enhanced argparser.
I'm panting the bases for generating the `.rst` files from the `.py` sources to improve the documentation - see `gdal_calc.py` for example for full details.

gdal-utils - parsing refactor

---

gdal/swig/python/gdal-utils/osgeo_utils/auxiliary/color_table.py
gdal/swig/python/gdal-utils/osgeo_utils/gdalattachpct.py

backport #https://github.com/OSGeo/gdal/pull/3751

type hints fix and variable init (backport #3751)

---

gdal/ogr/ogrsf_frmts/ili/ili2reader.cpp

This PR fixes non contiguous curves for COORD/ARC sequences in the Interlis driver

Ili: Fix non contiguous curves for COORD/ARC sequences

---

autotest/gcore/cog.py
autotest/gdrivers/eedai.py
autotest/osr/osr_metacrs.py

Fix CI tests on OSX
* OS: OSX
* Compiler:

Fix tests for OSX

---

gdal/configure
gdal/configure.ac
gdal/m4/geos.m4
gdal/m4/sfcgal.m4

configure: fix explicit disabling of geos/sfcgal

---

gdal/gcore/overview.cpp

Simplify color table handling a bit. Eliminate an unnecessary call to fetch the color table.
- [x ] All CI builds and checks have passed
* OS:
* Compiler:

Color table cleanup

---

.github/workflows/fedora_rawhide.yml

because of https://github.com/OSGeo/gdal/pull/3812/checks?check_run_id=2526882894

CI: switch to fedora:34 instead of rawhide 

---

autotest/ogr/ogr_gpkg.py
gdal/ogr/ogrsf_frmts/gpkg/ogrgeopackagetablelayer.cpp

See https://github.com/qgis/QGIS/issues/25795
and https://github.com/qgis/QGIS/pull/43118

GPKG: accept CreateField with a column with the fid column name and type=real, width=20, precision=0

---

gdal/doc/source/api/index.rst

Since the original Node.js bindings are not actively developed anymore
* OS:
* Compiler:

Add node-gdal-async

---

gdal/swig/python/gdal-utils/osgeo_utils/auxiliary/util.py

Without this PR `get_bands` only accept non-negative `ovr_idx: int`.
This PR adds the option to supply a negative `ovr_idx` and also `ovr_res` (as in `get_ovr_idx`)
For instance, this allow the user to use also these inputs to `gdallocationinfo`.
https://github.com/OSGeo/gdal/pull/3608

util.py - `get_bands(ovr_idx)` to support also negative `ovr_idx` and resolution

---

gdal/gcore/gdal.h

A very small doxygen PR - no code affected

mention RASTERIO_EXTRA_ARG_CURRENT_VERSION

---

gdal/ogr/ogrsf_frmts/flatgeobuf/feature_generated.h
gdal/ogr/ogrsf_frmts/flatgeobuf/flatbuffers/base.h
gdal/ogr/ogrsf_frmts/flatgeobuf/flatbuffers/code_generators.h
gdal/ogr/ogrsf_frmts/flatgeobuf/flatbuffers/flatbuffers.h
gdal/ogr/ogrsf_frmts/flatgeobuf/flatbuffers/flexbuffers.h
gdal/ogr/ogrsf_frmts/flatgeobuf/flatbuffers/grpc.h
gdal/ogr/ogrsf_frmts/flatgeobuf/flatbuffers/idl.h
gdal/ogr/ogrsf_frmts/flatgeobuf/flatbuffers/minireflect.h
gdal/ogr/ogrsf_frmts/flatgeobuf/flatbuffers/pch/flatc_pch.h
gdal/ogr/ogrsf_frmts/flatgeobuf/flatbuffers/pch/pch.h
gdal/ogr/ogrsf_frmts/flatgeobuf/flatbuffers/reflection.h
gdal/ogr/ogrsf_frmts/flatgeobuf/flatbuffers/reflection_generated.h
gdal/ogr/ogrsf_frmts/flatgeobuf/flatbuffers/stl_emulation.h
gdal/ogr/ogrsf_frmts/flatgeobuf/flatbuffers/util.h
gdal/ogr/ogrsf_frmts/flatgeobuf/header_generated.h
gdal/ogr/ogrsf_frmts/flatgeobuf/ogrflatgeobuflayer.cpp

FlatGeobuf: Upgrade to Flatbuffers 2.0

---

autotest/gcore/misc.py
gdal/apps/test_ogrsf.cpp
gdal/ogr/ogrsf_frmts/sqlite/ogrsqlitetablelayer.cpp
gdal/swig/include/python/gdal_python.i
gdal/swig/python/GNUmakefile
gdal/swig/python/extensions/gdal_array_wrap.cpp
gdal/swig/python/extensions/gdal_wrap.cpp
gdal/swig/python/extensions/gdalconst_wrap.c
gdal/swig/python/extensions/gnm_wrap.cpp
gdal/swig/python/extensions/ogr_wrap.cpp
gdal/swig/python/extensions/osr_wrap.cpp
gdal/swig/python/osgeo/gdal.py

(fixes qgis/QGIS#43224) and add tests to cover most drivers

 SQLite: fix crash when calling GetMetadataItem() with domain==nullptr 

---

autotest/cpp/test_osr_ct.cpp
gdal/ogr/ogr_srs_api.h
gdal/ogr/ogrct.cpp

OGRCT: Export novel OGRCoordinateTransformation functions to C API

---

gdal/port/cpl_odbc.cpp

Fix incorrect ODBC type mapping for a number of SQL types

---

autotest/gcore/tiff_ovr.py
gdal/gcore/overview.cpp

nodata mask may be different per band. The method `GDALRegenerateOverviewsMultiBand` was taking the first band as a mask for all the bands. This PR fixes that problem.
Fixes issue #3913 
There is a unit test modified. After looking (visually) at the result of this test in master and in this branch, it looks better with this branch. I am curious how a change in the nodata mask affects a file without nodata value.
EDIT: this change is gone. I leave this in the description to understand the conversation.

Nodata multiband interpolated overviews

---

gdal/doc/source/api/index.rst
gdal/doc/source/drivers/raster/cog.rst

Doc: add links to cogger+godal

---

gdal/frmts/ecw/ecwcreatecopy.cpp
gdal/frmts/ecw/ecwdataset.cpp
gdal/frmts/ecw/gdal_ecw.h
gdal/frmts/gtiff/geotiff.cpp
gdal/frmts/gtiff/gt_citation.cpp
gdal/frmts/gtiff/gt_citation.h
gdal/frmts/gtiff/gt_wkt_srs.cpp
gdal/frmts/gtiff/gt_wkt_srs.h
gdal/frmts/gtiff/gt_wkt_srs_for_gdal.h
gdal/frmts/jp2kak/jp2kakdataset.cpp
gdal/frmts/jp2lura/jp2luradataset.cpp
gdal/frmts/jpeg2000/jpeg2000dataset.cpp
gdal/frmts/jpipkak/jpipkakdataset.cpp
gdal/frmts/jpipkak/jpipkakdataset.h
gdal/frmts/mrsid/mrsiddataset.cpp
gdal/frmts/openjpeg/openjpegdataset.cpp
gdal/gcore/gdalgeorefpamdataset.cpp
gdal/gcore/gdalgeorefpamdataset.h
gdal/gcore/gdaljp2abstractdataset.cpp
gdal/gcore/gdaljp2metadata.cpp
gdal/gcore/gdaljp2metadata.h

No functional change. Extracted from https://github.com/OSGeo/gdal/pull/3810

SRS handling cleanup in GTiff and JPEG2000 drivers

---

autotest/pyscripts/test_gdal_utils.py
gdal/swig/python/gdal-utils/osgeo_utils/auxiliary/color_palette.py
gdal/swig/python/gdal-utils/osgeo_utils/auxiliary/color_table.py

* gdal/swig/python/gdal-utils/osgeo_utils/auxiliary/color_palette.py - add support methods (color_entry_to_color, is_numeric), make 'ndv' an attribute to fix issues with creating gdal.ColorTable from ColorPalette
* gdal-utils/osgeo_utils/auxiliary/color_table.py - color_table_from_color_palette - move the logic from get_color_table and handle the case of non-numeric palette
* autotest/pyscripts/test_gdal_utils.py - add tests for ColorPalette and the correspondent gdal.ColorTable

ColorPalette bug fixes and tests

---

autotest/ogr/ogr_shape.py
autotest/ogr/ogr_sql_rfc28.py
gdal/ogr/swq_op_general.cpp

Fix 3977 iso 8601 dates in filter

---

autotest/gdrivers/derived.py
gdal/frmts/derived/deriveddataset.cpp

if `RPC` metadata domain exists in the source dataset, ensure it is copied over to the derived dataset. Not sure what other domains would be appropriate to also pull into derived datasets in general.
* OS:
* Compiler:

Also copy RPC metadata if it exists when creating a derived dataset

---

gdal/doc/source/programs/gdal_translate.rst

small fix to syntax

---

gdal/doc/source/tutorials/osr_api_tut.rst

It implements some minor spelling and grammar fixes in osr_api_tut.rst.
None
- [x ] Add documentation

Spellcheck and wording fixes in osr_api_tut.rst

---

autotest/ogr/data/dxf/block-hidden-entities.dxf
autotest/ogr/ogr_dxf.py
gdal/ogr/ogrsf_frmts/dxf/ogrdxf_feature.cpp

DXF: Correctly handle hidden (invisible) INSERTs

---

autotest/gcore/vrt_read.py
autotest/gdrivers/sentinel2.py
autotest/gdrivers/vrtderived.py
gdal/doc/source/drivers/raster/vrt.rst
gdal/frmts/derived/deriveddataset.cpp
gdal/frmts/dimap/dimapdataset.cpp
gdal/frmts/sentinel2/sentinel2dataset.cpp
gdal/frmts/til/tildataset.cpp
gdal/frmts/vrt/vrtdataset.cpp
gdal/frmts/vrt/vrtdataset.h
gdal/frmts/vrt/vrtderivedrasterband.cpp
gdal/frmts/vrt/vrtdriver.cpp
gdal/frmts/vrt/vrtfilters.cpp
gdal/frmts/vrt/vrtrasterband.cpp
gdal/frmts/vrt/vrtrawrasterband.cpp
gdal/frmts/vrt/vrtsourcedrasterband.cpp
gdal/frmts/vrt/vrtsources.cpp
gdal/gcore/gdal_proxy.h
gdal/gcore/gdalproxypool.cpp

VRT: add API to add SimpleSource/ComplexSource by filename + band number

---

autotest/gdrivers/memmultidim.py
autotest/gdrivers/netcdf_multidim.py
autotest/gdrivers/zarr_driver.py
gdal/apps/gdalmdiminfo_lib.cpp
gdal/frmts/grib/gribdataset.cpp
gdal/frmts/hdf4/hdf4multidim.cpp
gdal/frmts/hdf5/bagdataset.cpp
gdal/frmts/hdf5/hdf5dataset.h
gdal/frmts/hdf5/hdf5multidim.cpp
gdal/frmts/netcdf/netcdfdataset.cpp
gdal/frmts/netcdf/netcdfmultidim.cpp
gdal/frmts/zarr/zarr.h
gdal/frmts/zarr/zarr_array.cpp
gdal/frmts/zarr/zarr_group.cpp
gdal/frmts/zarr/zarrdriver.cpp
gdal/gcore/gdal_pam.h
gdal/gcore/gdal_priv.h
gdal/gcore/gdaldataset.cpp
gdal/gcore/gdalmultidim.cpp
gdal/gcore/gdalpamdataset.cpp
gdal/swig/include/MultiDimensional.i
gdal/swig/python/extensions/gdal_wrap.cpp
gdal/swig/python/osgeo/gdal.py

For now only GetSpatialRef()/SetSpatialRef(), and apply it to Zarr
Also retrofit MDArray statistics storing/retrieval to use the new mechanism.

Add PAM capabilities to GDALMDArray

---

gdal/port/cpl_vsi_mem.cpp

Replace the explicit reference counting with `shared_ptr` in vsimem
#4180

Convert VSIMemFile to shared_ptr

---

gdal/frmts/ers/ersdataset.cpp

Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=36701

ERS: avoid long open delay on bogus datasets that reference themselves

---

autotest/gdrivers/pcidsk.py
gdal/frmts/pcidsk/sdk/core/cpcidskfile.cpp

CC @pciphelippeneveu  This was a regression in the SDK

PCIDSK: fix retrieval of RPC metadata (3.3 regression) (fixes #4118)

---

autotest/gdrivers/srtmhgt.py
gdal/frmts/srtmhgt/srtmhgtdataset.cpp

Also support auxiliary files with .err, .img, .num, .img.num and .swb extensions from other NASADEM products (fixes #4239)

SRTMHGT: support .hgts files from NASADEM SHHP

---

gdal/ogr/ogrsf_frmts/pgeo/ogrpgeodatasource.cpp

Seems the case will vary depending on how the database was created

[pgeo] Make identification of system tables case insensitive

---

gdal/ogr/ogr_xerces.cpp
gdal/ogr/ogr_xerces_headers.h

Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=37356

GMLAS/Xerces: use our own accessor to honour GDAL_HTTP_TIMEOUT

---

gdal/ogr/ogrsf_frmts/pgeo/ogrpgeodatasource.cpp

These tables are present in the "Autodesk Test.mdb" test file

[pgeo] Add more internal tables to block list

---

gdal/ogr/ogrsf_frmts/mvt/ogrmvtdataset.cpp

See https://github.com/MapServer/MapServer/pull/6389

MVT reader: be tolerant to broken points generated by Mapserver.

---

gdal/configure
gdal/m4/geos.m4
gdal/m4/sfcgal.m4

Fix GEOS detection in cross compilation

---

gdal/apps/ogr2ogr_lib.cpp
gdal/frmts/pds/pds4vector.cpp
gdal/ogr/ogrsf_frmts/generic/ogreditablelayer.cpp

Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=37768

Fix a few quadratic performance issues when creating fields

---

autotest/ogr/ogr_pgeo.py
gdal/ogr/ogrsf_frmts/pgeo/ogr_pgeo.h
gdal/ogr/ogrsf_frmts/pgeo/ogrpgeodatasource.cpp

[pgeo] Add GetLayerByName override which can retrieve private layers by name

---

gdal/ogr/ogrsf_frmts/pgeo/ogrpgeodriver.cpp

[pgeo] Add identify method

---

gdal/ogr/ogrsf_frmts/pgeo/ogrpgeodatasource.cpp

These are found in some older Personal Geodatabase files

[pgeo] Also flag "Selections" and "SelectedObjects" tables as private layers

---

gdal/ogr/ogrsf_frmts/odbc/ogrodbcdriver.cpp

[odbc] Add identify support

---

autotest/ogr/ogr_odbc.py
gdal/ogr/ogrsf_frmts/odbc/ogr_odbc.h
gdal/ogr/ogrsf_frmts/odbc/ogrodbcdatasource.cpp

[odbc] Add GetLayerByName, IsPrivateLayer support

---

autotest/ogr/ogr_esrijson.py
gdal/ogr/ogrsf_frmts/geojson/ogrgeojsondriver.cpp

Fixes https://lists.osgeo.org/pipermail/gdal-dev/2021-September/054632.html

ESRIJSON: make 'ESRIJSON:http://' connection string scroll results

---

gdal/doc/source/_extensions/driverproperties.py
gdal/doc/source/drivers/raster/dods.rst

Prototype deprecated driver note in documentation

---

gdal/frmts/pds/pds4dataset.cpp

Some products such as Clementine_UVVIS/basemap_45n_025e.xml have a
number of <?xml-model> tags which cause the xmlns="http://pds.nasa.gov/pds4/pds/v1"
to not be entirely in the first 1024 bytes used for identification.
Relax the check to avoid that issue.

PDS4: fix opening of some .xml files with large number of <?xml-model> tags

---

autotest/gdrivers/ngw.py
autotest/ogr/ogr_ngw.py

CC @BishopGIS The second commit will have to be reverted once the server is more reliable

Temporarily disable NGW tests on CI as they are flaky (refs #4453) 

---

autotest/gdrivers/pds4.py
gdal/frmts/pds/pds4dataset.cpp

Fixes PDS4_raster/LROC_NAC use case.

PDS4: accept optional <Reference_List> element in template.

---

autotest/gdrivers/data/pds4/template_with_sp.xml
autotest/gdrivers/pds4.py
gdal/frmts/pds/pds4dataset.cpp

Fixes PDS4_raster/multi_galileo_nims_tube.gcube_cahill_2019 use case

PDS4: fixes for compatibility with sp:Spectral_Characteristics in template.

---

gdal/frmts/pcidsk/pcidskdataset2.cpp
gdal/frmts/pcidsk/sdk/core/cpcidskfile.cpp
gdal/frmts/pcidsk/sdk/core/cpcidskfile.h
gdal/frmts/pcidsk/sdk/core/pcidskopen.cpp
gdal/frmts/pcidsk/sdk/pcidsk.h

Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=38885
CC @pciphelippeneveu

PCIDSK: avoid long processing time by limiting the number of bands.

---

gdal/port/cpl_userfaultfd.cpp

Fix the error hint message (should be 1)

fix error hint message

---

.gitignore
gdal/.gitignore
gdal/GNUmakefile

Configure removal followup

---

.gitignore
autotest/.gitignore
gdal/swig/python/.gitignore

Add all files generated by a Linux build and test to the respective .gitignore

gitignore files generated during a Linux build/test

---

gdal/doc/source/drivers/vector/pgeo.rst

With the new mdbtools, Ogr works directly on the mdb files as in Windows.
* OS:
* Compiler:

libmdbodbc package is not present on Debian

---

gdal/frmts/georaster/georaster_dataset.cpp

Issue #4564 
* OS:
* Compiler:

Fix issue 4564 that cannot handle schema name properly by adding owner checking in the DB query

---

gdal/doc/source/drivers/raster/gtiff.rst
gdal/frmts/gtiff/tif_jxl.c

JXL: use SRGB, document allowed bands for lossy

---

gdal/doc/requirements.txt

Adds docutils to `doc/requirements.txt` because for some reason `sphinx` does not pull it automatically

Adds docutils to doc/requirements.txt

---

gdal/doc/source/programs/gdal_viewshed.rst

Replaced the flag VISIBLE by NORMAL in the documentation to fit the actual behaviour of the code:    
`FAILURE: -om must be either NORMAL, DEM or GROUND`
* OS: NA
* Compiler: NA

Update gdal_viewshed.rst fix gdal_viewshed -om option default from 'VISIBLE' to 'NORMAL'

---

frmts/netcdf/netcdfdataset.cpp

REF: netCDF don't compare WKT to CF params

---

autotest/ogr/ogr_edigeo.py
doc/source/drivers/vector/edigeo.rst

Fix doc broken links for Edigeo
Mention unmaintained Geotools Edigeo module

Fix broken links, mention unmaintained module

---

doc/source/user/virtual_file_systems.rst

Docs: fixes wrong link for sample SHP zip file

Fix link to sample SHP zip

---

autotest/gdrivers/zarr_driver.py
frmts/zarr/zarr_group.cpp

Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=40949

Zarr: be robust to duplicated array and group names in NCZarr metadata, which could lead to performance issues

---

gdal/frmts/grib/degrib/degrib/myerror.cpp

Backport of PR #4830
Should fix (or at least help..) for the scenario of
https://lists.osgeo.org/pipermail/gdal-dev/2021-November/055009.html

[Backport 3.4] GRIB: fix thread-safetey of errSprintf()

---

cmake/modules/packages/FindOpenEXR.cmake
doc/source/build_hints.rst

If this works out we could consider making it a cache entry.

Adding documentation regarding build hints for external library OpenEXR

---

frmts/gtiff/tif_jxl.c

Fixes VS17.0 build error. Closes #4842.

Initialize jxl structures with zeros.

---

ogr/ogrsf_frmts/gpkg/ogrgeopackagedatasource.cpp
ogr/ogrsf_frmts/gpkg/ogrgeopackagetablelayer.cpp

Recent sqlite versions have an optimization for columns declared with a
NOT NULL constraint that makes it possible that on corrupted databases
that would violate the constraint a "WHERE c IS NOT NULL" is not
honored. We relied on this assuming that the returned rows would be such
that c != NULL.
Issue described in more detail at https://sqlite.org/forum/forumpost/47dae2beeb
With this commit, we rather do a check on application side.

GPKG: fix nullptr dereference on corrupted databases with sqlite >= 3.35

---

doc/source/api/csharp/csharp_raster.rst

Fix the  self-contradiction desctiption in  csharp_raster.rst.
* OS:
* Compiler:

document: Update csharp_raster.rst

---

autotest/gcore/vsis3.py
doc/source/user/virtual_file_systems.rst
port/cpl_aws.cpp
port/cpl_aws.h

See https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-role.html

/vsis3/: allow setting AWS_PROFILE to a profile that uses IAM role assumption

---

.github/workflows/cmake_builds.yml
CMakeLists.txt
autotest/cpp/CMakeLists.txt
frmts/tiledb/CMakeLists.txt
frmts/tiledb/tiledbdataset.cpp
port/CMakeLists.txt
port/cpl_compressor.cpp
port/cpl_minizip_unzip.h
port/cpl_minizip_zip.h
port/cpl_vsil_gzip.cpp
port/cpl_xml_validate.cpp
port/cpl_zlib_header.h

and also fix warnings with clang and Conda (spotted on Mac too)

CMake CI: fix Mac homebrew build and run tests

---

cmake/modules/packages/FindGeoTIFF.cmake
cmake/modules/packages/FindPROJ.cmake
doc/source/build_hints.rst

CMake: locate debug & release libs for PROJ and GEOTIFF

---

autotest/gcore/tiff_write.py
gdal/doc/source/drivers/raster/gtiff.rst
gdal/doc/source/programs/gdaladdo.rst
gdal/frmts/gtiff/geotiff.cpp
gdal/frmts/gtiff/gt_overview.cpp
gdal/frmts/gtiff/gt_overview.h
gdal/frmts/gtiff/gtiff.h

Backport of https://github.com/OSGeo/gdal/pull/4856

[Backport 3.4] GTiff: LERC overview related improvements

---

autotest/osr/osr_ct.py
ogr/ogrct.cpp

By default, if the source or target SRS definition refers to an official
CRS through a code, GDAL will use the official definition if the official
definition and the source/target SRS definition are equivalent. Note that TOWGS84[]
clauses are ignored when checking equivalence. Starting with GDAL 3.4.1, if
you set the OGR_CT_PREFER_OFFICIAL_SRS_DEF configuration option to NO,
the source or target SRS definition will be always used.
Fixes https://github.com/OSGeo/PROJ/issues/2955

OGR_CT: add a OGR_CT_PREFER_OFFICIAL_SRS_DEF config option

---

autotest/ogr/ogr_sqlite.py
doc/source/drivers/vector/sqlite.rst
ogr/ogrsf_frmts/sqlite/ogr_sqlite.h
ogr/ogrsf_frmts/sqlite/ogrsqlitedatasource.cpp
ogr/ogrsf_frmts/sqlite/ogrsqlitedriver.cpp
ogr/ogrsf_frmts/sqlite/ogrsqlitetablelayer.cpp
ogr/ogrsf_frmts/sqlite/ogrsqlitevirtualogr.cpp

See https://sqlite.org/stricttables.html

SQLite: add a STRICT=YES layer creation option to create tables as SQLite >= 3.37 STRICT tables

---

doc/source/api/python_gotchas.rst

add a crashing case that looks distinctly different from other cases.
* OS:
* Compiler:

Python Gotchas: Put a distinct case

---

alg/gdaltransformer.cpp
autotest/gdrivers/data/vrt/bug4997.vrt
autotest/gdrivers/data/vrt/bug4997_intermediary.vrt
autotest/gdrivers/vrtwarp.py
autotest/utilities/test_gdalwarp_lib.py
frmts/vrt/vrtwarped.cpp

gdalwarp: do not emit "Point outside of projection domain" / "tolerance condition error" (fixes #4934)

---

ogr/ogrsf_frmts/dwg/dwg_headers.h
ogr/ogrsf_frmts/dwg/ogr_dwg.h
ogr/ogrsf_frmts/dwg/ogrdwglayer.cpp

When reader encounter AcDbFace, it translate it to 4 vertices polygon

[DWG] : support AcDbFace reading (fixes #4535)

---

alg/internal_libqhull/geom_r.c
alg/internal_libqhull/global_r.c
alg/internal_libqhull/libqhull_r.c
alg/internal_libqhull/mem_r.c
alg/internal_libqhull/poly2_r.c
alg/internal_libqhull/poly_r.c
alg/internal_libqhull/qhull_ra.h
alg/internal_libqhull/qset_r.c
alg/internal_libqhull/user_r.c

A number of them might be legit, but hard to figure out.

Internal libqhull: silence Coverity Scan warnings

---

cmake/modules/packages/FindQHULL.cmake
configure.ac
doc/source/build_hints.rst

configure/CMake: add selection of qhull_r vs qhullstatic_r

---

ogr/ogrsf_frmts/flatgeobuf/ogrflatgeobuflayer.cpp

ref https://github.com/OSGeo/gdal/issues/5060

FlatGeobuf: If CRS WKT detected to be non UTF-8 force it

---

frmts/bsb/bsbdataset.cpp

Refs https://lists.osgeo.org/pipermail/qgis-developer/2022-January/064399.html

Add missing kap file extension for bsb driver

---

cmake/helpers/CheckDependentLibraries.cmake

CMake: Update CheckDependentLibraries.cmake to fix zlib name typo

---

.github/workflows/asan/start.sh
.github/workflows/asan_build.yml
autotest/asan_suppressions.txt
autotest/lsan_suppressions.txt

Backport of https://github.com/OSGeo/gdal/pull/5125

[Backport 3.4] CI ASAN: port to Ubuntu 20.04 (fixes #5124)

---

swig/csharp/makefile.vc

CSharp: Switch default platform target to AnyCPU #1368

---

swig/csharp/dll_template.csproj

Brings the CMAKE Csharp build scripts in line with #5148 
#5148 
* OS:
* Compiler:

CMAKE : Csharp change to AnyCPU

---

autotest/ogr/ogr_fgdb.py
autotest/ogr/ogr_gpkg.py
autotest/ogr/ogr_openfilegdb.py
autotest/ogr/ogr_pgeo.py
gcore/gdal.h
gcore/gdal_priv.h
gcore/gdaldataset.cpp
ogr/ogrsf_frmts/filegdb/FGdbDatasource.cpp
ogr/ogrsf_frmts/filegdb/ogr_fgdb.h
ogr/ogrsf_frmts/generic/ogremulatedtransaction.cpp
ogr/ogrsf_frmts/generic/ogrmutexeddatasource.cpp
ogr/ogrsf_frmts/generic/ogrmutexeddatasource.h
ogr/ogrsf_frmts/gpkg/ogr_geopackage.h
ogr/ogrsf_frmts/gpkg/ogrgeopackagedatasource.cpp
swig/include/Dataset.i
swig/python/extensions/gdal_wrap.cpp
swig/python/osgeo/gdal.py

~~Implemented for OpenFileGDB driver only for now~~
~~The FileGDB and GPKG drivers will require special implementations of this, which will be done shortly. For now I'm after general feedback on the API.~~
Implemented for all drivers which currently support field domains

Add GetFieldDomainNames method to retrieve all field domain names which are available for a dataset

---

ogr/ogrsf_frmts/ili/imdreader.cpp

ILI IMDReader: fix various potential crashes on invalid output (CID 1469239, 1469241, 1469243, 1469244, 1469245)

---

doc/source/programs/vector_common_options.rst

Improve the documentation of the [Common options for vector programs](https://gdal.org/programs/vector_common_options.html#common-options-for-vector-programs) by adding a description how multiple categories can be selected with the [`--debug` option](https://gdal.org/programs/vector_common_options.html#cmdoption-debug)
No

OGR Doc: Describe the use of multiple debug prefixes

---

autotest/alg/warp.py
doc/source/programs/gdalwarp.rst

Test and clarify behavior of mode resampling when there are two or more values with an equal number of pixels.
None

gdalwarp: Test and document mode behavior in case of ties

---

swig/python/setup.py
swig/python/setup.py.in

(refs https://github.com/OSGeo/gdal/pull/5296#issuecomment-1037460842)

Python bindings: remove all traces of distutils

---

doc/source/software_using_gdal.rst

Add listing for TAK

---

ogr/ogrsf_frmts/filegdb/FGdbLayer.cpp
ogr/ogrsf_frmts/filegdb/ogr_fgdb.h

Detailed analysis in https://github.com/Esri/file-geodatabase-api/issues/46
Fixes qgis/qgis#45760

FileGDB: workaround a crash involving binary field and CDF datasets

---

.github/workflows/cmake_builds.yml
frmts/ceos2/ceos.c
frmts/ceos2/ceos.h
ogr/ogrsf_frmts/mssqlspatial/include_msodbcsql.h
ogr/ogrsf_frmts/mssqlspatial/ogr_mssqlspatial.h

Fixes #5317
@dg0yt I believe this can go first into master, and you'll queue your further fixes on top of it ?

Fix build issues with latest msys2 mingw64 compiler & re-enable CI builds

---

autotest/pyscripts/gdal2tiles/test_vsimem.py
gdal/swig/python/gdal-utils/osgeo_utils/gdal2tiles.py

[Backport 3.4] gdal2tiles: detect write error when creating tiles, and allow outputing to /vsi filesystems (fixes #3382, fixes #5370)

---

doc/source/programs/ogrmerge.rst

Fix missing closing bracket

---

autotest/gcore/vsicredential.py
autotest/gcore/vsigs.py
autotest/gcore/vsis3.py
autotest/pymod/gdaltest.py
doc/source/user/virtual_file_systems.rst
port/cpl_alibaba_oss.cpp
port/cpl_alibaba_oss.h
port/cpl_aws.cpp
port/cpl_aws.h
port/cpl_azure.cpp
port/cpl_azure.h
port/cpl_google_cloud.cpp
port/cpl_google_cloud.h
port/cpl_swift.cpp
port/cpl_swift.h
port/cpl_vsi.h
port/cpl_vsil.cpp
port/cpl_vsil_curl.cpp
port/cpl_vsil_curl_class.h
port/cpl_vsil_swift.cpp
port/cpl_vsil_webhdfs.cpp
swig/include/cpl.i
swig/python/extensions/gdal_wrap.cpp
swig/python/osgeo/gdal.py

which makes it easier if using the same virtual file system but
with different credentials (e.g. different credentials for bucket
"/vsis3/foo" and "/vsis3/bar")

Add VSISetCredential() to set /vsi[s3|gs|az|...] credentials for a given file prefix

---

cmake/helpers/configure.cmake
cmake/template/cpl_config.h.in
nmake.opt
port/cpl_aws_win32.cpp
port/makefile.vc

refs https://github.com/OSGeo/gdal/pull/3022#issuecomment-1063681408

Make cpl_aws_win32.cpp compilation conditioned by atlbase.h availability

---

doc/source/drivers/raster/vrt.rst

This is a clarification for what NoDataValue means in a VRT.

Clarify the meaning of NoDataValue

---

.github/workflows/cmake_builds.yml
.github/workflows/validate_xml.yml

libaec migration cherry-picked from #5453.

Minor CI updates

---

alg/gdaltransformer.cpp
autotest/gcore/geoloc.py

Patch in gdaltransformer.cpp by @warmerdam

GDAL Transformer: implement DST_METHOD=GEOLOC_ARRAY

---

gcore/gdalpamdataset.cpp

DOC: add warning about GDAL_PAM_ENABLED=OFF

---

autotest/gcore/pam.py
gcore/gdalpamdataset.cpp

When GDAL is built without PAM support or the GDAL_PAM_ENABLED
configuration option is set to NO, a number of drivers will misbehave.
e.g drivers whose dataset/band classes extend GDALPamDataset/RasterBand,
and when methods like SetDescription(), SetColorInterpretation() are
called. Before that change, this would cause a CPLError() to be emitted.
With that change, when PAM is disabled, only the loading and writing of
.aux.xml files is disabled, but setters on PAM dataset/rasterband will
work.
CC @tbonfort

Avoid CPLError() on number of drivers when PAM is disabled

---

.github/workflows/cmake_builds.yml
.gitignore
gdal.cmake
man/CMakeLists.txt
man/man1/README.txt
mkgdaldist.sh

CMake / mkgdaldist.sh: adjustments related to man pages and extraneous directories

---

doc/source/tutorials/osr_api_tut.rst

- fix 'a/an'
- 'recognize' spelling (is more common that 'ise' in gdal/)
tiny text updates

osr_api_tut.rst:  minor edits

---

ogr/ogrsf_frmts/hana/ogr_hana.h
ogr/ogrsf_frmts/hana/ogrhanadatasource.cpp
ogr/ogrsf_frmts/hana/ogrhanalayer.cpp
ogr/ogrsf_frmts/hana/ogrhanaresultlayer.cpp
ogr/ogrsf_frmts/hana/ogrhanatablelayer.cpp

This change introduces lazy initialization of HANA layers.

Lazy initialization of HANA layers

---

swig/python/setup.py

GDAL python bdist package build problem in master (#5614)

---

cmake/helpers/CheckDependentLibraries.cmake
cmake/modules/packages/FindBRUNSLI.cmake
doc/source/build_hints.rst
frmts/mrf/CMakeLists.txt

Detects and configures the [BRUNSLI library](https://github.com/google/brunsli) for use within MRF, when building with CMake
Issue #5068
* OS:
* Compiler:

MRF: Add brunsli to cmake system

---

ogr/ogrsf_frmts/hana/ogrhanadatasource.cpp
ogr/ogrsf_frmts/hana/ogrhanafeaturereader.cpp

HANA: Coverity scan related fixes

---

apps/ogr2ogr_lib.cpp
ogr/ogr_feature.h
ogr/ogrfeature.cpp
ogr/ogrsf_frmts/arrow_common/ograrrowlayer.hpp
ogr/ogrsf_frmts/arrow_common/ograrrowwriterlayer.hpp
ogr/ogrutils.cpp

With those optimizations, "ogr2ogr out.parquet nz-buildings-outlines.parquet" goes from 19.7 seconds down to 12.6 sec

Various optimizations for access to OGRFeature, and apply it to Parquet driver

---

apps/ogr2ogr_lib.cpp

I'm not completely sure it is a good idea.
As noted in the code, this makes work again something that was documented in GDAL 1.1.8 and got broken at GDAL 1.3.2 as far as I can see. The alternative would be to change the doc of the PG driver.

ogr2ogr: make 'ogr2ogr [-f PostgreSQL] PG:dbname=.... source [srclayer] -lco OVERWRITE=YES' work as if -overwrite was specified (fixes #5640)

---

CONTRIBUTING.md
apps/gdalwarp_bin.cpp
apps/gdalwarp_lib.cpp

Mainly coding style change;
and I also change CONTRIBUTING.md:81 due to my personal failure when adding fork using HTTPS.

GDALWarp utility improvement 

---

gdal.cmake

gdal.cmake: add GDAL_EXTRA_LINK_LIBRARIES (upstream OSGeo4W patch)

---

.github/workflows/ubuntu_20.04.yml
ci/travis/ubuntu_1804/script.sh

This change fixes autotest failure in HANA driver #5721.

Fix issue #5721

---

ogr/ogrsf_frmts/flatgeobuf/flatbuffers/stl_emulation.h
ogr/ogrsf_frmts/flatgeobuf/flatbuffers/verifier.h

Intends to fix https://github.com/OSGeo/gdal/issues/5718 which has been fixed upstream by https://github.com/google/flatbuffers/pull/7304.

FlatGeobuf: Upgrade flatbuffers again

---

doc/source/drivers/vector/gpkg.rst

Update of the GeoPackage vector documentation.
N/A
Not relevant.

GPKG: Add example of GPKG file update

---

ogr/ogrsf_frmts/gpkg/ogr_geopackage.h
ogr/ogrsf_frmts/gpkg/ogrgeopackagetablelayer.cpp

GPKG: speed-up GetFeature() by keeping a prepared statement

---

autotest/ogr/ogr_gpkg.py
ogr/ogrsf_frmts/gpkg/ogr_geopackage.h
ogr/ogrsf_frmts/gpkg/ogrgeopackagedatasource.cpp
ogr/ogrsf_frmts/gpkg/ogrgeopackagetablelayer.cpp

not worth enough/appropriate for backport

GPKG: do not list layers referenced in gpkg_contents but that have no corresponding table (fixes qgis/qgis#30670)

---

ogr/ogrsf_frmts/lvbag/ogrlvbagdriver.cpp

... and when reading from /vsi network file systems, give up after 10
probed files, if none was detected as a LVBAG file.
Otherwise this could be really sluggish when GDAL tries to open a remote
directory with lots of files, and that it is not a LVBAG dataset
CC @yorickdewid Does that sound good to you ?

LVBAG: scan only .xml files when passed a directory

---

autotest/gdrivers/nitf.py
gdal/frmts/nitf/nitfdataset.cpp
gdal/gcore/gdalpamdataset.cpp

[Backport 3.4] NITF: do not put PAM metadata in a Subdataset node of .aux.xml file i there's a single dataset (3.4.0 regression) (fixes #5790)

---

autotest/ogr/ogr_fgdb.py
gcore/gdaldataset.cpp
ogr/ogrsf_frmts/filegdb/FGdbLayer.cpp

(issue with embedded libxml2 in SDK), and fallback to OpenFileGDB driver to reliably retrieve it (fixes #5841)

FileGDB: avoid crash when reading layer with AliasName with XML special characters

---

gcore/gdalrasterband.cpp

Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=47786. master only

ComputeRasterMinMax(): avoid potential crash due to recent improvements

---

autotest/ogr/ogr_parquet.py
autotest/osr/osr_proj4.py
ogr/ogrsf_frmts/parquet/ogrparquetwriterlayer.cpp
ogr/ogrspatialreference.cpp

Cf https://github.com/OSGeo/PROJ/pull/3221 and https://github.com/opengeospatial/geoparquet/discussions/110

Avoid issues with PROJJSON with id in members of datum ensemble

---

doc/source/api/csharp/csharp_conda.rst
doc/source/api/csharp/csharp_vector.rst
doc/source/build_hints.rst

Minor updates to the CSharp docs around the Cmake build process
None
* OS:
* Compiler:

Doc: csharp documentation updates

---

doc/source/user/ogr_sql_dialect.rst

Make the phrasing of the special fields section in the OGR SQL dialect docs less awkward and grammatically correct.

OGR SQL dialect: improve awkward grammar

---

ogr/ogrsf_frmts/wfs/ogr_wfs.h
ogr/ogrsf_frmts/wfs/ogrwfsdatasource.cpp
ogr/ogrsf_frmts/wfs/ogrwfslayer.cpp

Fixes https://lists.osgeo.org/pipermail/gdal-dev/2022-June/055939.html

WFS: make <PagingAllowed> and <PageSize> elements work in WFS XML configuration file

---

autotest/cpp/test_ogr.cpp
ogr/ogr_feature.h
ogr/ogrfielddefn.cpp

Fix loss of split/merge policy when cloning field domains

---

.github/workflows/fedora_rawhide/start.sh

[Backport release/3.5] CI: fedora_rawhide: fix issue with lxml python package

---

frmts/netcdf/netcdfdataset.cpp

- nc_create() crashes on an invalid output directory
- it seems that netCDF 4.9.0 is back to expected filenames in current
code page rather than UTF-8.

netCDF: fix 2 issues with netCDF 4.9.0 of msys2-mingw64 (fixes #5970)

---

frmts/netcdf/netcdfdataset.cpp

[Backport release/3.5] netCDF: fix 2 issues with netCDF 4.9.0 of msys2-mingw64 (fixes #5970)

---

LICENSE.TXT

LICENSE.TXT: mention licenses of FlatGeoBuf / Flatbuffers

---

autotest/ogr/ogr_sql_test.py
ogr/ogrsf_frmts/generic/ogr_gensql.cpp

[Backport release/3.5] OGRSQL: fix GetFeature() to return a feature such that GetFeature(fid).GetFID() == fid (fixes #5967)

---

frmts/gtiff/geotiff.cpp
frmts/gtiff/libtiff/tif_webp.c

Most of the changes are in libtiff themselves

GTiff driver: WEBP: avoid unnecessary temporary buffer creation and copy

---

autotest/gcore/vsiaz_real_instance_auto.py

[Backport release/3.5] CI: avoid random failure on Mac on test_vsiaz_sas() test

---

autotest/pyscripts/test_gdal2xyz.py
swig/python/gdal-utils/osgeo_utils/gdal2xyz.py

[Backport release/3.5] gdal2xyz.py: fix parsing of -b option (fixes #5984)

---

autotest/cpp/test_gdal.cpp
frmts/vrt/vrtsources.cpp
gcore/gdalproxypool.cpp

[Backport release/3.5] VRT: take into account open options when sharing sources (fixes #5989)

---

ogr/ogrsf_frmts/vfk/ogrvfklayer.cpp
ogr/ogrsf_frmts/vfk/vfkdatablock.cpp
ogr/ogrsf_frmts/vfk/vfkpropertydefn.cpp
ogr/ogrsf_frmts/vfk/vfkreader.cpp
ogr/ogrsf_frmts/vfk/vfkreader.h
ogr/ogrsf_frmts/vfk/vfkreaderp.h

VFK: Support for UTF-8

---

.github/workflows/windows_build.yml
cmake/modules/packages/FindECW.cmake
cmake/modules/packages/FindPoppler.cmake
ogr/ogrsf_frmts/sqlite/CMakeLists.txt

Note that only compilation is tested. For some reason, running the build
does not work. Probably something missing / conflicting in the PATH.
Hard/impossible to debug remotely.
But as we have already a working Windows build in cmake_builds.yml,
that's OK

windows_build.yml: migrate to CMake

---

autotest/gcore/histogram.py
gcore/gdalrasterband.cpp

[Backport release/3.5] GetHistogram(): deal with undefined behaviour when raster values are at infinity, or with pathological min/max bounds

---

.github/workflows/ubuntu_18.04/install.sh
.github/workflows/ubuntu_18.04_32bit/start.sh

[Backport release/3.5] CI: fix build issue with latest spatialite

---

apps/commonutils.cpp
frmts/gtiff/cogdriver.cpp
swig/python/gdal-utils/osgeo_utils/auxiliary/util.py

Adds DMD_Extension metadata for the COG driver. I don't know all the ramifications of this change
None that I'm aware of

COG: Copy DMD_Extension from GTiff driver

---

docker/ubuntu-full/Dockerfile
docker/ubuntu-full/bh-gdal.sh
docker/ubuntu-full/bh-proj.sh

[Backport release/3.5] docker/ubuntu-full: fix building WITH_FILEGDB=yes [ci skip]

---

CONTRIBUTING.md
doc/source/build_hints.rst
swig/python/CMakeLists.txt
swig/python/modify_cpp_files.cmake
swig/python/osgeo/gdal.py
swig/python/osgeo/gdal_array.py
swig/python/osgeo/gnm.py
swig/python/osgeo/ogr.py
swig/python/osgeo/osr.py

to regenerated files, and copy regenerated files into source directory
refs #5680

swig/python/CMakeLists.txt: apply all customizations from GNUmakefile

---

frmts/gtiff/geotiff.cpp
frmts/gtiff/libtiff/tif_read.c
frmts/gtiff/libtiff/tiffvers.h

[Backport release/3.5] GTiff: fix reading some JPEG compressed COG files through /vsicurl/

---

alg/gdalwarpkernel_opencl.h

[Backport release/3.5] Fix build with OpenCL support on case-sensitive Apple systems (fixes #6117)

---

doc/source/build_hints.rst
doc/source/drivers/raster/mbtiles.rst
doc/source/drivers/vector/parquet.rst

This PR fixes a few typos in the documentation.
None

Doc: fix a few typos

---

doc/source/drivers/vector/parquet.rst
ogr/ogrsf_frmts/parquet/ogrparquetdriver.cpp

Backport #6140
**Authored by:** @agiudiceandrea

[Backport release/3.5] Parquet driver: fix compression methods

---

autotest/ogr/ogr_gpkg.py
autotest/ogr/ogr_sqlite.py
doc/source/drivers/vector/gpkg.rst
doc/source/drivers/vector/sqlite.rst
ogr/ogrsf_frmts/gpkg/ogr_geopackage.h
ogr/ogrsf_frmts/gpkg/ogrgeopackagedatasource.cpp
ogr/ogrsf_frmts/gpkg/ogrgeopackagetablelayer.cpp
ogr/ogrsf_frmts/sqlite/ogr_sqlite.h
ogr/ogrsf_frmts/sqlite/ogrsqlitebase.h
ogr/ogrsf_frmts/sqlite/ogrsqlitedatasource.cpp
ogr/ogrsf_frmts/sqlite/ogrsqlitedriver.cpp

Relationships will be reported for tables which utilise FOREIGN KEY constraints, and have ``PRAGMA foreign_keys = ON``.

[sqlite] Implement support for relationship retrieval

---

autotest/gcore/tiff_read.py
autotest/gcore/tiff_write.py
autotest/gdrivers/jp2openjpeg.py
autotest/gdrivers/netcdf.py
autotest/gdrivers/vrtpansharpen.py
autotest/gdrivers/wms.py
autotest/gdrivers/zarr_driver.py
autotest/ogc_cite_testing/generate_sample_gpkg.py
autotest/ogr/ogr_sql_sqlite.py
autotest/osr/osr_basic.py
autotest/osr/osr_proj4.py
swig/python/gdal-utils/osgeo_utils/samples/build_jp2_from_xml.py
swig/python/gdal-utils/osgeo_utils/samples/validate_jp2.py

[Backport release/3.5] Fix flake8 E275 missing whitespace after keyword warnings

---

autotest/gdrivers/wms.py
autotest/ogr/ogr_sql_sqlite.py

Refs https://github.com/OSGeo/gdal/pull/6143#issuecomment-1201310969

Cleanup failure strings in tests

---

frmts/postgisraster/postgisrasterdataset.cpp
ogr/ogrgeometry.cpp
ogr/swq_op_general.cpp
port/cpl_vsi_mem.cpp

[Backport release/3.5] Fix build with -DDEBUG_VERBOSE (fixes #6147)

---

apps/gdalwarp_lib.cpp
autotest/utilities/test_gdalwarp_lib.py

[Backport release/3.5] gdalwarp: fix issue with wrong resolution when reprojecting between geographic CRS with source extent slightly off [-180,180]

---

frmts/sigdem/sigdemdataset.cpp

In new C++ std::fill declared in `<algorithm>` header. This PR adds inclusion of this header.
* OS:
* Compiler:

fmts/sigdem: Add missing header

---

alg/rasterfill.cpp
autotest/alg/fillnodata.py
autotest/gcore/mask.py
gcore/gdal_priv.h
gcore/gdalrasterband.cpp

(fixes rasterio/rasterio#2474)

GDALFillNodata(): make it work properly when providing a non-null hMaskBand and using smoothing iterations

---

alg/rasterfill.cpp
autotest/alg/fillnodata.py
autotest/gcore/mask.py
gcore/gdal_priv.h
gcore/gdalrasterband.cpp

[Backport release/3.5] GDALFillNodata(): make it work properly when providing a non-null hMaskBand and using smoothing iterations

---

autotest/gcore/vsicurl.py
doc/source/user/virtual_file_systems.rst
frmts/stacit/stacitdataset.cpp
frmts/vrt/vrtsources.cpp
port/cpl_vsil_curl.cpp
port/cpl_vsil_curl_class.h

[Backport release/3.5] STACIT: make it work with Planetary Computer and resource URL signing

---

alg/gdal_rpc.cpp
autotest/gcore/tiff_read.py
autotest/gcore/tiff_write.py
autotest/gcore/vrt_read.py
frmts/vrt/vrtsources.cpp

Backport of https://github.com/OSGeo/gdal/pull/6225

[Backport 3.5] RPC DEM extraction: use a block base approach to query the DEM

---

alg/gdaltransformer.cpp
autotest/osr/osr_basic.py
autotest/osr/osr_ct_proj.py
autotest/utilities/test_gdalwarp_lib.py
ogr/ogrct.cpp
ogr/ogrspatialreference.cpp

gdalwarp: fix target extent computation in EPSG:4326 to ESRI:53037

---

apps/gdal_translate_lib.cpp
autotest/gcore/tiff_srs.py
autotest/gcore/tiff_write.py
autotest/gdrivers/gpkg.py
autotest/utilities/test_gdal_translate_lib.py
frmts/gtiff/gt_wkt_srs.cpp
ogr/ogrsf_frmts/gpkg/ogrgeopackagedatasource.cpp

[Backport 3.5] Set of fixes related to preservation of the dynamic nature of a dynamic CRS

---

alg/gdaltransformer.cpp
autotest/osr/osr_basic.py
autotest/osr/osr_ct_proj.py
autotest/utilities/test_gdalwarp_lib.py
ogr/ogrct.cpp
ogr/ogrspatialreference.cpp

[Backport 3.5] gdalwarp: fix target extent computation in EPSG:4326 to ESRI:53037

---

cmake/helpers/configure.cmake
cmake/template/cpl_config.h.in
gdal.cmake

Backport #6245
**Authored by:** @dg0yt

[Backport release/3.5] Fix propagation of CPL_DISABLE_DLL

---

.github/workflows/asan/start.sh
.github/workflows/cmake_builds.yml
.github/workflows/ubuntu_20.04/build-deps.sh
autotest/ogr/ogr_hana.py
ogr/ogrsf_frmts/hana/ogr_hana.h
ogr/ogrsf_frmts/hana/ogrhanadatasource.cpp

[Backport release/3.5] HANA: fix incorrect encoding of SQL statements

---

swig/python/gdal-utils/osgeo_utils/gdal2tiles.py

Backport #6252
**Authored by:** @candux

[Backport release/3.5] gdal2tiles: fix OpenLayers CDN

---

ogr/ogrsf_frmts/flatgeobuf/geometryreader.cpp
ogr/ogrsf_frmts/flatgeobuf/geometryreader.h

Replaces https://github.com/OSGeo/gdal/pull/5691

FlatGeobuf: Minor optimizations removal of redundant checks

---

autotest/ogr/ogr_hana.py
ogr/ogrsf_frmts/hana/ogr_hana.h
ogr/ogrsf_frmts/hana/ogrhanadatasource.cpp
ogr/ogrsf_frmts/hana/ogrhanatablelayer.cpp
ogr/ogrsf_frmts/hana/ogrhanautils.cpp
ogr/ogrsf_frmts/hana/ogrhanautils.h

[Backport release/3.5] HANA: LaunderName returns wrong value for non-ASCII characters

---

port/cpl_odbc.cpp

Backport #6255
**Authored by:** @lefrog

[Backport release/3.5] ODBC: fix issue with odbc large data (fixes #6196)

---

swig/python/gdal-utils/osgeo_utils/gdal2tiles.py

Credits to https://www.gavinharriss.com/code/opacity-control

gdal2tiles: fix googlemaps.html to port from ancient Google Maps V2 API to V3

---

cmake/helpers/configure.cmake

[Backport release/3.5] CMake: fix build with Mac Catalyst

---

swig/python/gdal-utils/osgeo_utils/gdal2tiles.py

Credits to https://www.gavinharriss.com/code/opacity-control
Backport of PR #6285

[Backport 3.5] gdal2tiles: fix googlemaps.html to port from ancient Google Maps V2 API to V3

---

autotest/ogr/ogr_hana.py
ogr/ogrsf_frmts/hana/ogrhanadatasource.cpp

[Backport release/3.5] HANA: inform about missing mandatory connection parameters

---

ogr/ogrsf_frmts/hana/ogrhanadatasource.cpp

[Backport release/3.5] HANA: fix coverity scan issue #6315

---

apps/ogr2ogr_lib.cpp
autotest/ogr/ogr_pgdump.py
autotest/utilities/test_ogr2ogr.py
autotest/utilities/test_ogr2ogr_lib.py
ogr/ogrsf_frmts/pg/ogr_pg.h
ogr/ogrsf_frmts/pg/ogrpgtablelayer.cpp
ogr/ogrsf_frmts/pgdump/ogrpgdumpdatasource.cpp

when outputing to PG/PGDump (fixes https://github.com/OSGeo/gdal/issues/6261)

ogr2ogr: make sure geometry column name is going through laundering

---

frmts/nitf/rpftocfile.cpp

Backport #6341
**Authored by:** @adegwerthAirbus

[Backport release/3.5] NITF: RPF use more robust way to detect legends/overviews

---

autotest/gcore/tiff_ovr.py
doc/source/drivers/raster/gtiff.rst
doc/source/programs/gdaladdo.rst
frmts/gtiff/geotiff.cpp

GTiff: honour COMPRESS_OVERVIEW and INTERLEAVE_OVERVIEW for internal overviews

---

frmts/pdf/CMakeLists.txt

[Backport release/3.5] CMake: Poppler: tighten fix of PR #6347 for broken 18.04 package

---

autotest/gdrivers/envi.py
frmts/raw/envidataset.cpp
frmts/raw/envidataset.h

ENVI: implement 'default bands' to read/write R,G,B color interpretation

---

autotest/cpp/test_cpl.cpp
port/cpl_worker_thread_pool.cpp

If a job executed by SubmitJob() submits itself another job on the same thread pool, it will currently deadlock if there are no waiting/free threads in the thread pool. Detect that situation and execute the job synchronously then.

CPLWorkerThreadPool::SubmitJob(): avoid potential deadlock when called from worker thread

---

autotest/gcore/tiff_write.py
frmts/gtiff/geotiff.cpp

Backport #6395
**Authored by:** @tbonfort

[Backport release/3.5] GTiff: fix marking alpha channels that are not the last one

---

.github/workflows/cmake_builds.yml

(https://github.com/OSGeo/gdal/actions/runs/3089082782/jobs/4996283881)

CI build-linux-ubuntu-focal: fix error with latest VM update

---

alg/gdalchecksum.cpp
autotest/gcore/tiff_read.py
autotest/gcore/vrt_read.py
autotest/gdrivers/aigrid.py
autotest/gdrivers/bsb.py
autotest/gdrivers/doq1.py
autotest/gdrivers/jp2openjpeg.py
autotest/gdrivers/jpeg.py
autotest/gdrivers/mrf.py
autotest/gdrivers/sar_ceos.py
autotest/gdrivers/usgsdem.py
autotest/gdrivers/vrtderived.py
frmts/gtiff/geotiff.cpp

- GDALChecksumImage(): make it return -1 in case of error
- GDALChecksumImage(): read per block (instead of per line) for integer data type case

Checksum improvements

---

autotest/ogr/ogr_gpkg.py
doc/source/drivers/vector/gpkg.rst
ogr/ogrsf_frmts/gpkg/ogrgeopackagedatasource.cpp
ogr/ogrsf_frmts/gpkg/ogrgeopackagedriver.cpp
ogr/ogrsf_frmts/sqlite/ogrsqlitedatasource.cpp

[Backport 3.5] GPKG: add a IMMUTABLE=YES/NO open option

---

alg/gdalgeoloc.cpp
alg/gdalgeoloc_dataset_accessor.h
gcore/gdalcachedpixelaccessor.h

[Backport release/3.5] Geoloc: optimize backmap generation time when using temporary GTiff dataset backing

---

autotest/ogr/data/gml/feature_with_gml_description.gml
autotest/ogr/data/gml/feature_with_gml_description.xsd
autotest/ogr/ogr_gml_read.py
ogr/ogrsf_frmts/gml/gmlfeatureclass.cpp
ogr/ogrsf_frmts/gml/gmlreader.h
ogr/ogrsf_frmts/gml/ogr_gml.h
ogr/ogrsf_frmts/gml/ogrgmldatasource.cpp

GML: read <gml:description>, <gml:identifier>, <gml:name> fields in a  feature 

---

autotest/gcore/vrtmisc.py
frmts/vrt/vrtdataset.cpp
frmts/vrt/vrtsources.cpp

Backport of https://github.com/OSGeo/gdal/pull/6426

[Backport 3.5] VRT serialization: do not (generally) open source band when serialization of a ComplexSource with NODATA (fixes qgis/QGIS#48052)

---

ogr/ogrgeometry.cpp

DOC: fix OGRGeometry::ConcaveHull() docstring

---

autotest/gdrivers/envi.py
frmts/raw/envidataset.cpp
frmts/sigdem/sigdemdataset.cpp
frmts/wms/wmsdriver.cpp
ogr/ogr_fromepsg.cpp
ogr/ogr_spatialref.h
ogr/ogrsf_frmts/geojson/ogresrijsonreader.cpp
ogr/ogrsf_frmts/openfilegdb/ogropenfilegdblayer.cpp
ogr/ogrsf_frmts/shape/ogrshapelayer.cpp
ogr/ogrspatialreference.cpp

Add a OGRSpatialReference::FindBestMatch() method and use it for ENVI driver

---

autotest/cpp/test_cpl.cpp
frmts/stacta/stactadataset.cpp
frmts/stacta/stactadataset.h
ogr/ogr_proj_p.cpp
ogr/ogr_proj_p.h
ogr/ogrct.cpp
ogr/ogrsf_frmts/openfilegdb/filegdbindex.cpp
port/cpl_mem_cache.h
port/cpl_noncopyablevector.h
port/cpl_vsil_cache.cpp

No functional change. Maybe marginal performance improvements by removing useless std::shared_ptr usage

LRU cache improvements

---

frmts/jpegxl/jpegxl.cpp

(as suggested in libjxl 0.7.0 release notes)

JPEGXL: use JxlDecoderCloseInput() when available

---

frmts/gtiff/libtiff/tif_close.c
frmts/gtiff/libtiff/tif_dir.c
frmts/gtiff/libtiff/tif_dir.h
frmts/gtiff/libtiff/tif_dirread.c
frmts/gtiff/libtiff/tif_open.c
frmts/gtiff/libtiff/tiffiop.h

Includes https://gitlab.com/libtiff/libtiff/-/merge_requests/386

Internal libtiff: Improved IFD-Loop Handling

---

ogr/ogrsf_frmts/gpkg/ogrgeopackagedatasource.cpp

Backport #6476
**Authored by:** @dirkvdb

[Backport release/3.5] GPKG: raster overlays: Fix min max mean std_dev values when creating overviews

---

alg/gdalwarpkernel.cpp
autotest/utilities/test_gdalwarp_lib.py

Given ``gdalwarp world_ocean_ssh.tif average.tif -te -6400000 -6400000 6400000 6400000 -ts 60 60 -t_srs "ESRI:102020" -r average -overwrite --debug on && gdal_translate average.tif out_average.png -ot byte -scale -outsize 1000 0``,
with the fix:
without the fix:

gdalwarp: fix artefacts around antimeridian for average/mode/min/max/med/q1/q3/sum/rms resampling (fixes #6478)

---

autotest/ogr/ogr_geojsonseq.py
doc/source/drivers/vector/geojsonseq.rst
ogr/ogrsf_frmts/geojson/ogrgeojsonseqdriver.cpp
port/cpl_vsi_virtual.h
port/cpl_vsil_stdin.cpp
port/cpl_vsil_stdout.cpp

GeoJSONSeq: add support for appending features to an existing file

---

ogr/ogrsf_frmts/hana/ogrhanatablelayer.cpp

HANA: remove use of std::regex

---

ogr/ogrsf_frmts/sxf/ogrsxfdatasource.cpp
ogr/ogrsf_frmts/sxf/org_sxf_defs.h

Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=52346
CC @drons

SXF: fix floating-point division by zero, and other issues with uninitialized values

---

ogr/ogrsf_frmts/mitab/mitab_datfile.cpp

Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=52339

TABDATFile::AddField(): fix nullptr dereference in error code path

---

ogr/ogrsf_frmts/mitab/mitab_datfile.cpp

[Backport release/3.5] TABDATFile::AddField(): fix nullptr dereference in error code path

---

doc/source/user/ogr_sql_dialect.rst

Fix an incorrect example expression in the OGR SQL documentation
N/A

Fix dollars to cents conversion expression

---

frmts/sentinel2/sentinel2dataset.cpp

[Backport release/3.5] SENTINEL2: avoid potential stack-buffer-overflow. Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=52499

---

ogr/ogrsf_frmts/hana/ogrhanadatasource.cpp

This PR reworks the building of a connection string by following the official [documentation](https://help.sap.com/docs/SAP_HANA_CLIENT/f1b440ded6144a54ada97ff95dac7adf/7cab593774474f2f8db335710b2f5c50.html).

HANA: properly handle special characters in connection string

---

doc/source/drivers/vector/oci.rst

This is a follow-up on https://github.com/OSGeo/gdal/pull/6565#issuecomment-1287476591.

OCI: clarify text regarding ALL_SDO_GEOM_METADATA

---

.github/workflows/backport.yml
.github/workflows/cmake_builds.yml
.github/workflows/conda.yml
.github/workflows/macos.yml

This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …

GitHub Workflows security hardening

---

alg/gdalchecksum.cpp
alg/gdalgrid.cpp

Backport #6625
**Authored by:** @szekerest

[Backport release/3.6] Fix VS2017 broken builds (#6624)

---

ogr/ogrsf_frmts/openfilegdb/filegdbindex.cpp

(fixes geopandas/geopandas#2253)

OpenFileGDB: do not use buggy .spx spatial index found in some datasets

---

ogr/ogrsf_frmts/openfilegdb/filegdbindex.cpp

[Backport release/3.6] OpenFileGDB: do not use buggy .spx spatial index found in some datasets

---

frmts/hdf5/hdf5vfl.h

[Backport release/3.6] HDF5: fix build with libhdf5 1.13.2 and 1.13.3 (fixes #6657)

---

doc/source/programs/gdal_calc.rst

Minimal document adjustment
N/A
* OS:
* Compiler:

[Minor adjustment] update gdal_calc.rst documentation

---

autotest/gcore/hdf4_read.py
cmake/modules/packages/FindHDF4.cmake
frmts/hdf4/CMakeLists.txt
frmts/hdf4/hdf4dataset.cpp
frmts/hdf4/hdf4imagedataset.cpp

[Backport release/3.6] HDF4: fix opening more than 32 simultaneous HDF4_EOS files (fixes #6665)

---

cmake/helpers/CheckDependentLibraries.cmake

(refs https://github.com/spack/spack/pull/33856#issue-1446090634)

CMake: remove RECOMMENDED flag to BRUNSLI and QB3. Add it for CURL

---

doc/source/download.rst

Doc: download.rst: mention Spack

---

cmake/helpers/CheckDependentLibraries.cmake

and make it a FATAL_ERROR if the user used -DGDAL_USE_ARMADILLO=ON

CMake: do not use Armadillo if it lacks LAPACK support (such as on Alpine)

---

autotest/ogr/ogr_gpkg.py
ogr/ogrsf_frmts/gpkg/ogr_geopackage.h
ogr/ogrsf_frmts/gpkg/ogrgeopackagetablelayer.cpp
ogr/ogrsf_frmts/vdv/ogrvdvdatasource.cpp

[Backport release/3.6] GPKG: add support for reading tables with generated columns (fixes #6638)

---

autotest/gdrivers/gpkg.py
doc/source/drivers/raster/gpkg.rst
ogr/ogrsf_frmts/gpkg/gdalgeopackagerasterband.cpp
ogr/ogrsf_frmts/gpkg/ogr_geopackage.h
ogr/ogrsf_frmts/gpkg/ogrgeopackagedatasource.cpp

[Backport release/3.6] GPKG raster: implement setting the nodata value for Byte dataset (fixes #1569)

---

cmake/helpers/CheckDependentLibraries.cmake

[Backport release/3.6] CMake: do not use Armadillo if it lacks LAPACK support (such as on Alpine)

---

frmts/rmf/rmfdataset.cpp
frmts/rmf/rmfdataset.h

[Backport release/3.6] RMF: Implement GetSuggestedBlockAccessPattern

---

autotest/alg/applyverticalshiftgrid.py
autotest/alg/warp.py
autotest/gcore/numpy_rw.py
autotest/gcore/thread_test.py
autotest/gcore/tiff_write.py
autotest/gcore/vsifile.py
autotest/gdrivers/ecw.py
autotest/gdrivers/hfa.py
autotest/gdrivers/jp2kak.py
autotest/gdrivers/lcp.py
autotest/gdrivers/mrf.py
autotest/gdrivers/nitf.py
autotest/gdrivers/vrtderived.py
autotest/ogr/ogr_elasticsearch.py
autotest/ogr/ogr_fgdb.py
autotest/ogr/ogr_geom.py
autotest/ogr/ogr_pcidsk.py
autotest/ogr/ogr_sql_test.py
autotest/ogr/ogr_tiger.py
autotest/ogr/ogr_vrt.py
autotest/osr/osr_esri.py
autotest/pyscripts/test_ogr2ogr_py.py
autotest/utilities/test_ogr2ogr.py
autotest/utilities/test_ogr2ogr_lib.py
frmts/pcidsk/ogrpcidsklayer.cpp
frmts/pcidsk/pcidskdataset2.cpp

Backport of https://github.com/OSGeo/gdal/pull/6696

[Backport 3.6] autotest: fix PytestReturnNotNoneWarning deprecation warning (fixes #6644)

---

.pre-commit-config.yaml

LNT: Fix flake8 repo in pre-commit-config

---

.pre-commit-config.yaml

Backport #6706
**Authored by:** @snowman2

[Backport release/3.6] LNT: Fix flake8 repo in pre-commit-config

---

alg/gdalwarpoperation.cpp

Backport #6708
**Authored by:** @mplough-kobold

[Backport release/3.6] Also log number of chunks in warp operation progress debug logs

---

doc/source/drivers/raster/vrt.rst

Backport #6723
**Authored by:** @scottstanie

[Backport release/3.6] DOC: fix typos in vrt.rst

---

frmts/georaster/georaster_dataset.cpp

Fix a build warning, see  #6710

GeoRaster: Fix build warning nBands shadow (fixes #6710)

---

autotest/ogr/ogr_gpkg.py
autotest/pyscripts/test_ogrmerge.py
ogr/ogrsf_frmts/gpkg/ogr_geopackage.h
ogr/ogrsf_frmts/gpkg/ogrgeopackagedatasource.cpp
swig/python/gdal-utils/osgeo_utils/ogrmerge.py

that is when stacking several source geopackages into a multiple-layer single geopackage.
Can speed up to a 10x factor such cases.
The optimization is triggered only if:
- the output .gpkg file does not exist
- all source files are .gpkg
- -single is *not* specified

ogrmerge.py: add optimization for GPKG -> GPKG non-single layer case

---

autotest/gdrivers/gpkg.py
swig/include/cpl.i
swig/python/extensions/gdal_wrap.cpp
swig/python/osgeo/gdal.py

and
gpkg.py: make test 51 conditioned by value of gdal.CPLGetUsablePhysicalRAM()

SWIG: add gdal.GetNumCPUs() and gdal.GetUsablePhysicalRAM()

---

autotest/gdrivers/gpkg.py
swig/include/cpl.i
swig/python/extensions/gdal_wrap.cpp
swig/python/osgeo/gdal.py

[Backport release/3.6] SWIG: add gdal.GetNumCPUs() and gdal.GetUsablePhysicalRAM()

---

ogr/ogrsf_frmts/generic/ograrrowarrayhelper.h

[Backport release/3.6] OGRArrowArrayHelper::SetDate(): simplify implementation

---

autotest/gcore/tiff_read.py

We came across the same test failure while packaging this for Nixpkgs: https://github.com/NixOS/nixpkgs/pull/201730#issuecomment-1321141198

don't only skip test failing on macOS on Travis

---

autotest/gcore/tiff_read.py

Backport #6754
**Authored by:** @dotlambda

[Backport release/3.6] don't only skip test failing on macOS on Travis

---

autotest/gcore/vsiaz.py
port/cpl_vsil_az.cpp

[Backport release/3.6] /vsiaz/: make AppendBlob operation compatible of Azurite (fixes #6759)

---

ogr/ogrsf_frmts/generic/ogrlayer.cpp

[Backport release/3.6] Doc: OGR_L_GetArrowStream(): clarify lifecycle (fixes #6772)

---

.github/workflows/windows_build.yml

[Backport release/3.6] CI: windows_build.yml: remove conflicting libraries

---

docker/ubuntu-full/bh-proj.sh
docker/util.sh
scripts/reformat.sh
swig/python/fallback_build_mingw32_under_unix_py37.sh

[Backport release/3.6] Fix shellcheck issues with the shellcheck of ubuntu 22.04

---

apps/gdalbuildvrt_lib.cpp
autotest/utilities/test_gdalbuildvrt_lib.py

[Backport release/3.6] gdalbuildvrt: make -addalpha working when there's a mix of bands with or without alpha (fixes #6794)

---

autotest/ogr/ogr_mitab.py
ogr/ogrsf_frmts/mitab/mitab_spatialref.cpp

Fixes https://github.com/qgis/QGIS/issues/50956

MITAB: add support for 'Philippine Reference System 1992' datum

---

autotest/ogr/ogr_mitab.py
ogr/ogrsf_frmts/mitab/mitab_spatialref.cpp

[Backport release/3.6] MITAB: add support for 'Philippine Reference System 1992' datum

---

doc/source/drivers/vector/mssqlspatial.rst
ogr/ogrsf_frmts/mssqlspatial/ogrmssqlspatialdatasource.cpp

Backport #6797
**Authored by:** @ninsbl

[Backport release/3.6] MSSQLSPATIAL: Get UID and PWD from environment variable

---

ogr/ogrsf_frmts/flatgeobuf/packedrtree.cpp
ogr/ogrsf_frmts/flatgeobuf/packedrtree.h

I upstreamed changes done at https://github.com/OSGeo/gdal/pull/6804 but wanted to keep API so this brings that here + a tiny optimization removing a redundant reversal.

FlatGeobuf: Align with upstream

---

apps/ogr2ogr_lib.cpp
autotest/utilities/test_ogr2ogr_lib.py

[Backport release/3.6] ogr2ogr: densify points of spatial filter specified with -spat_srs to avoid reprojection artifacts

---

autotest/ogr/ogr_fgdb.py
ogr/ogrsf_frmts/filegdb/FGdbLayer.cpp

[Backport release/3.6] FileGDB: avoid crash in the SDK if passing incompatible geometry type (fixes #6836)

---

autotest/ogr/ogr_gpkg.py
autotest/ogr/ogr_sqlite.py
ogr/ogrsf_frmts/sqlite/ogrsqlitedatasource.cpp

(Sorry, can't believe I let this slip through :scream_cat: )

[sqlite] Fix relationships determined through foreign keys have tables reversed

---

autotest/ogr/ogr_gpkg.py
autotest/ogr/ogr_sqlite.py
ogr/ogrsf_frmts/sqlite/ogrsqlitedatasource.cpp

[Backport release/3.6] [sqlite] Fix relationships determined through foreign keys have tables reversed

---

apps/bench_ogr_batch.cpp

I love Bach but this looks like a typo

APPS: Typo bench_ogr_bach ->  bench_ogr_batch

---

autotest/utilities/test_gdalinfo_lib.py
data/gdalinfo_output.schema.json
gdal.cmake

Add data/gdalinfo_output.schema.json to validate gdalinfo -json output

---

swig/csharp/CMakeLists.txt

Backport #6874
**Authored by:** @runette

[Backport release/3.6] CMake: Fix NetStandard

---

autotest/gdrivers/nitf.py
data/nitf_spec.xml
data/nitf_spec.xsd
doc/source/drivers/raster/nitf.rst
frmts/nitf/nitfdataset.cpp
frmts/nitf/nitfdataset.h
frmts/nitf/nitfdes.c
frmts/nitf/nitffile.c
frmts/nitf/nitflib.h

- nitf_spec.xml: add definition for subheader of CSATTB, CEEPHB and CSSFAB DES of GLAS/GFM
- NITF: add capability of decoding DES data part as XML fields and add descriptors for CSATTB, CEEPHB and CSSFAB DES
- NITF: add VALIDATE and FAIL_IF_VALIDATION_ERROR open options

NITF: add support for CSATTB, CEEPHP and CSSFAB DES, decoding of DES data part and validation options

---

autotest/gcore/vsiaz.py
port/cpl_azure.cpp

[Backport release/3.6] /vsiaz/: accept Azure connection string with only BlobEndpoint and SharedAccessSignature (fixes #6870)

---

frmts/ogcapi/gdalogcapidataset.cpp

[Backport release/3.6] OGCAPI: update for map api; also for tiles but not working properly due to churn in tilematrixset spec (fixes #6832)

---

autotest/ogr/ogr_pg.py
autotest/ogr/ogr_pgdump.py
ogr/ogrsf_frmts/pg/ogrpgdatasource.cpp
ogr/ogrsf_frmts/pgdump/ogrpgdumpdatasource.cpp

Backport #6896
**Authored by:** @palmerj

[Backport release/3.6] Fix PG and PGDump drivers to support the TEMPORARY layer CO

---

data/tms_MapML_CBMTILE.json

ref https://github.com/OSGeo/gdal/commit/cb2bcd906eb97fc986541118991cfae5179d7669#r93063795

Fix CBMTILE TMS [skip ci]

---

data/tms_MapML_CBMTILE.json

Backport #6921
**Authored by:** @vincentsarago

[Backport release/3.6] Fix CBMTILE TMS [skip ci]

---

apps/ogr2ogr_lib.cpp
autotest/ogr/ogr_geojson.py
ogr/ogrsf_frmts/geojson/ogrgeojsondatasource.cpp

[Backport 3.6] ogr2ogr: make -nln flag with GeoJSON output even if a name exists in input GeoJSON (fixes #6920)

---

autotest/ogr/data/parquet/schema.json
autotest/ogr/ogr_parquet.py
doc/source/drivers/vector/parquet.rst
ogr/ogr_core.h
ogr/ogrsf_frmts/arrow_common/ogr_arrow.h
ogr/ogrsf_frmts/arrow_common/ograrrowwriterlayer.hpp
ogr/ogrsf_frmts/parquet/ogrparquetlayer.cpp
ogr/ogrsf_frmts/parquet/ogrparquetwriterlayer.cpp

[Backport release/3.6] Parquet: update to GeoParquet 1.0.0-beta.1 specification (fixes #6646)

---

alg/gdalwarpkernel.cpp

[Backport release/3.6] Warp: fix crash in multi-threaded mode when doing several warping runs with the same WarpOperation

---

autotest/ogr/ogr_gpkg.py
ogr/ogrsf_frmts/gpkg/ogr_geopackage.h
ogr/ogrsf_frmts/gpkg/ogrgeopackagedatasource.cpp
ogr/ogrsf_frmts/gpkg/ogrgeopackagetablelayer.cpp

[Backport release/3.6] GPKG: fix threaded RTree building when creating several layers (3.6.0 regression)

---

doc/source/development/rfc/index.rst
doc/source/development/rfc/rfc89_sql_logging_callback.rst

RFC89: SQL query logging callback

RFC89: sql logging callback

---

autotest/test_random_tiff.py

Fixes a minor typo.
I don't know. To get familiar with the project source code I ran a test and I ran into this minor issue on the first thing i tried. Since it's such a minor issue, I did not bother to check if there's an issue/pull request for this.
* OS:
* Compiler:

minor typo

---

autotest/utilities/test_ogr2ogr_lib.py
swig/include/python/gdal_python.i
swig/python/osgeo/gdal.py

Add some extra options to the python binding of VectorTranslate (in VectorTranslateOptions)
Related: #6486
* OS: developed on Windows, but should be cross platform
* Compiler: used python 3.9 while developing

Python bindings: VectorTranslate: add some extra options (#6486)

---

autotest/gcore/test_driver_metadata.py
ogr/ogrsf_frmts/ngw/ogrngwdriver.cpp

[Backport release/3.6] NGW: remove DCAP_ items set to NO (refs #6994) / Add test for all drivers

---

autotest/gdrivers/jpeg.py
autotest/gdrivers/jpegxl.py
frmts/jpeg/jpgdataset.cpp
frmts/jpegxl/jpegxl.cpp

Lossless JPEG -> JPEGXL was already implemented

JPEG: implement lossless copy from JPEGXL that has JPEG reconstruction box

---

autotest/gcore/basic_test.py
autotest/gcore/vsiaz.py
autotest/gcore/vsigs.py
autotest/gcore/vsis3.py
autotest/ogr/ogr_basic_test.py
autotest/osr/osr_basic.py
autotest/pymod/gdaltest.py
swig/include/python/gdal_python.i
swig/include/python/ogr_python.i
swig/include/python/osr_python.i
swig/python/osgeo/gdal.py
swig/python/osgeo/ogr.py
swig/python/osgeo/osr.py

and also add gdal.enable_exceptions() context manager

Python bindings: add gdal.config_option() and gdal.config_options() context manager

---

alg/gdalwarpkernel.cpp
autotest/postinstall/test_cmake.sh
autotest/postinstall/test_gdal-config.sh
autotest/postinstall/test_pkg-config.sh
autotest/pyscripts/test_osr_util.py
doc/source/development/rfc/rfc47_dataset_caching.rst
doc/source/development/rfc/rfc77_drop_python2_support.rst
doc/source/drivers/vector/netcdf.rst
doc/source/programs/raster_common_options.rst
frmts/mrf/marfa_dataset.cpp
frmts/vrt/pixelfunctions.cpp
gcore/gdal_misc.cpp
gcore/gdalmultidim.cpp
ogr/ogr_geo_utils.cpp
ogr/ogrsf_frmts/openfilegdb/ogropenfilegdblayer.cpp
ogr/ogrspatialreference.cpp
port/cpl_http.cpp
port/cpl_minizip_zip.cpp
swig/python/gdal-utils/README.rst

Convert most cases of `the the` to `the`
None
None - just comments

the the -> the

---

swig/python/setup.py.in

Backport #7032
**Authored by:** @rcoup

[Backport release/3.6] python: fix setup.py directory list issue on macOS

---

doc/source/drivers/vector/openfilegdb.rst
ogr/ogrsf_frmts/filegdb/FGdbDriver.cpp
ogr/ogrsf_frmts/openfilegdb/ogropenfilegdbdriver.cpp

[Backport release/3.6] Fix typo filed->field

---

autotest/cpp/test_osr.cpp
ogr/ogr_spatialref.h
ogr/ogr_srs_panorama.cpp

1. Add new projection, datum, ellipsoid codes of Panorama GIS. 
2. Add well known spatial references set by EPSG codes in importFromPanorama function.
3. Add exportVertCSToPanorama function.
4. Add unit tests.

OSR_Panorama: Add some spatial references (GSK 2011, SK 1995, Vertical CS etc.). Add unit tests. 

---

ogr/ogrsf_frmts/openfilegdb/filegdbtable.cpp

@nyalldawson you're right the comment was erroneous. I've run git blame to reconstruct the history of this code. hopefully my updated comments should give a picture on why we do the slow method currently.
Have you hit perf issues in that code path ? Perhaps organizePolygons() could use GEOS in a better way (actually it tries to avoid using it as much as possible when it is not strictly needed, by doing cheap topological checks first)

OpenFileGDB geometry builder: fix comment related to polygon reconstruction (fixes #7047)

---

ogr/ogrsf_frmts/gpkg/ogrgeopackagetablelayer.cpp

Backport #7056
**Authored by:** @theroggy

[Backport release/3.6] Fix ogr2ogr error + invalid gpkg output file in some cases

---

ogr/ogrsf_frmts/openfilegdb/filegdbtable_write.cpp

Hopefully this should fix Coverity warning:
```
CID 1502589 (#4 of 4): Inefficient vector resizing with reserve.
(INEFFICIENT_RESERVE)
1. inefficient_reserve: A std::vector has its capacity adjusted with
reserve() in a manner that is likely to have severe performance penalties.
To avoid a quadratic time penalty when using reserve(), always
increase the capacity by a multiple of its current value
```
CC @nyalldawson

OpenFileGDB writer: reserve arrays with an exponential strategy

---

ogr/ogrsf_frmts/hana/ogrhanadatasource.cpp

[Backport release/3.6] HANA: fix DSN open option

---

autotest/cpp/test_cpl.cpp
autotest/gcore/tiff_read.py
frmts/gtiff/geotiff.cpp
port/cpl_vsi.h
port/cpl_vsi_virtual.h
port/cpl_vsil_cache.cpp
port/cpl_vsil_curl.cpp
port/cpl_vsil_curl_class.h
port/cpl_vsil_plugin.cpp
port/cpl_vsil_plugin.h

- Add VSIVirtualHandle::AdviseRead() virtual method with empty implementation
- VSICachedFile: implement AdviseRead()
- VSIPlugin: implement AdviseRead()
- GTiff: call AdviseRead() in multithreaded read implementation
- /vsicurl/: implement AdviseRead() in a background thread
Fixes #6456
CC @tbonfort

Add VSIVirtualHandle::AdviseRead()

---

autotest/ogr/ogr_gpkg.py
ogr/ogrsf_frmts/gpkg/ogrgeopackagelayer.cpp
ogr/ogrsf_frmts/gpkg/ogrgeopackagetablelayer.cpp

GeoPackage: GetNextArrowArray(): fix retrieving only the geometry

---

autotest/ogr/ogr_gpkg.py
ogr/ogrsf_frmts/gpkg/ogrgeopackagelayer.cpp
ogr/ogrsf_frmts/gpkg/ogrgeopackagetablelayer.cpp

[Backport release/3.6] GeoPackage: GetNextArrowArray(): fix retrieving only the geometry

---

doc/source/development/rfc/index.rst
doc/source/development/rfc/rfc90_read_compressed_data.rst

Rendered view [here](https://github.com/rouault/gdal/blob/rfc90_text/doc/source/development/rfc/rfc90_read_compressed_data.rst)

Add text for RFC90: Direct access to compressed raster data

---

.github/workflows/conda.yml

This should hopefully get the Conda builder ✅ again.

Conda build fix up

---

autotest/pymod/test_py_scripts.py
autotest/pyscripts/test_gdal_retile.py
swig/python/gdal-utils/osgeo_utils/gdal_retile.py

[Backport release/3.6] gdal_retile.py: fix wrong basename for .aux.xml files (fixes #7120)

---

ogr/ogrsf_frmts/openfilegdb/ogr_openfilegdb.h
ogr/ogrsf_frmts/openfilegdb/ogropenfilegdbdatasource.cpp
ogr/ogrsf_frmts/openfilegdb/ogropenfilegdblayer.cpp

[Backport release/3.6] OpenFileGDB: fix performance issue when identifying a CRS

---

autotest/ogr/ogr_geojsonseq.py
ogr/ogrsf_frmts/geojson/ogrgeojsonseqdriver.cpp

[Backport release/3.6] GeoJSONSeq: fix writing to /vsigzip/ (fixes #7130)

---

doc/source/development/rfc/index.rst
doc/source/development/rfc/rfc91_dataset_close.rst

Rendered view in https://github.com/rouault/gdal/blob/rfc91_text/doc/source/development/rfc/rfc91_dataset_close.rst

Add RFC 91 text: GDALDataset::Close() method

---

autotest/gdrivers/rmf.py
frmts/rmf/rmfdataset.cpp
frmts/rmf/rmfdataset.h
ogr/ogr_srs_panorama.cpp

Add to RMF driver support metadata items: scale and name. 
Add vector mask (frame) support. 
Add write vertical spatial reference system to RMF header.
Add unit test.

RMF: Add scale, name, frame support. Add vertical CS write support.

---

autotest/gcore/vsicurl.py
autotest/pymod/webserver.py
port/cpl_vsil_curl.cpp
port/cpl_vsil_curl_class.h

This partially reverts the part of 63aa56e7985 that causes the regression and which I can't make sense...

/vsicurl/: fix CPL_VSIL_CURL_USE_HEAD=NO mode (fixes #7150)

---

autotest/gdrivers/nitf.py
frmts/nitf/nitfdataset.cpp
frmts/nitf/nitffile.c

NITF: update CLEVEL to appropriate values when using compression / multiple image segments

---

autotest/gcore/vsicurl.py
autotest/pymod/webserver.py
port/cpl_vsil_curl.cpp
port/cpl_vsil_curl_class.h

[Backport release/3.6] /vsicurl/: fix CPL_VSIL_CURL_USE_HEAD=NO mode (fixes #7150)

---

autotest/ogr/ogr_shape.py
ogr/ogrsf_frmts/shape/dbfopen.c
ogr/ogrsf_frmts/shape/shape2ogr.cpp

[Backport release/3.6] Shapefile: fix adding features in a .dbf without columns (fixes qgis/qgis#51247)

---

autotest/gdrivers/tiledb_read.py
autotest/gdrivers/tiledb_write.py
frmts/tiledb/tiledbdataset.cpp
gcore/rasterio.cpp

Backport #7128
**Authored by:** @normanb

[Backport release/3.6] tiledb rasterio

---

autotest/gdrivers/zmap.py
frmts/zmap/zmapdataset.cpp

[Backport release/3.6] ZMap creation: fix potential truncation of nodata value (fixes #7203)

---

doc/source/development/rfc/index.rst
doc/source/development/rfc/rfc92_wkb_only_geometries.rst

==> [Rendered view](https://github.com/rouault/gdal/blob/rfc92_text/doc/source/development/rfc/rfc92_wkb_only_geometries.rst)

Add RFC 92 text: WKB Only geometries

---

.github/workflows/doc_build.yml
doc/source/conf.py

Doc: fix Search functionality

---

autotest/pyscripts/test_gdal2tiles.py
autotest/pyscripts/test_gdal_ls_py.py
autotest/pyscripts/test_gdal_polygonize.py
autotest/pyscripts/test_gdal_retile.py
autotest/pyscripts/test_gdal_sieve.py
autotest/pyscripts/test_gdalinfo_py.py
autotest/pyscripts/test_ogr2ogr_py.py
autotest/pyscripts/test_ogrinfo_py.py
autotest/pyscripts/test_ogrmerge.py
autotest/utilities/test_gdal_create.py
autotest/utilities/test_gdal_grid.py
autotest/utilities/test_gdal_rasterize.py
autotest/utilities/test_gdal_translate.py
autotest/utilities/test_gdal_translate_lib.py
autotest/utilities/test_gdaldem.py
autotest/utilities/test_gdaldem_lib.py
autotest/utilities/test_gdalinfo.py
autotest/utilities/test_gdalinfo_lib.py
autotest/utilities/test_gdalmdiminfo_lib.py
autotest/utilities/test_gdalwarp.py
autotest/utilities/test_gdalwarp_lib.py
autotest/utilities/test_ogr2ogr.py
autotest/utilities/test_ogr2ogr_lib.py
autotest/utilities/test_ogrinfo.py

autotest: use pytest.mark.require_driver() in utilities/ and pyscripts/

---

frmts/vrt/vrtderivedrasterband.cpp

correct typo in vrtderivedrasterband error

---

cmake/helpers/configure.cmake
cmake/template/cpl_config.h.in
port/cpl_config.h.in
port/cpl_multiproc.cpp

Backport #7318
**Authored by:** @ffontaine

[Backport release/3.6] fix uclibc build without NPTL

---

autotest/ogr/ogr_mitab.py
ogr/ogrsf_frmts/mitab/mitab_feature.cpp

[Backport release/3.6] MITAB: Fix possible crash on NULL feature text

---

autotest/ogr/ogr_geojson.py
ogr/ogrsf_frmts/geojson/ogrgeojsonwriter.cpp

Fix #7336 (only when NATIVE_DATA=TRUE)

JSON: Fix json mixed types roundtrip

---

autotest/ogr/ogr_geojson.py
ogr/ogrsf_frmts/geojson/ogrgeojsonwriter.cpp

[Backport release/3.6] JSON: Fix json mixed types roundtrip

---

doc/source/development/rfc/index.rst
doc/source/development/rfc/rfc93_update_feature.rst

==> [rendered view](https://github.com/rouault/gdal/blob/rfc93_text/doc/source/development/rfc/rfc93_update_feature.rst)

Add RFC 93 text: OGRLayer::UpdateFeature() method

---

doc/source/tutorials/raster_api_tut.rst

* Follow C++ Core Guidelines in the C++ code to make it safer
* Also make the examples complete by defining the filename (previously it was undeclared variable)
* Add main take in argument for filename 
* Remove unused cpl_conv in c++ tutorial
* Use unique pointer over raw pointer
* Use unique pointer implicit bool operator to check validity (nullptr)
* Define the access mode as a const to be more clear
* Exit the example if the filename is not provided (arguments not correct)
* #7380
* Compiler: Sphinx

Doc: Follow c++ core guidelines (fixes #7380)

---

autotest/gdrivers/ehdr.py
gcore/rawdataset.cpp
gcore/rawdataset.h

(on top of https://github.com/OSGeo/gdal/pull/7405)
only the last commit is the performance enhancement. All other ones are fixes for pre-existing bugs uncovered by the optim!

RAW: fix performance issue when reading files with very small width (fixes #1140)

---

gcore/rawdataset.cpp
gcore/rawdataset.h

Partial backport of https://github.com/OSGeo/gdal/pull/7406

[Backport 3.6] Raw: various bug fixes for the Direct I/O code path

---

autotest/ogr/ogr_sql_rfc28.py
ogr/CMakeLists.txt
ogr/swq_parser.cpp
ogr/swq_parser.y
ogr/swq_select.cpp

[Backport release/3.6] OGRSQL: fix 'SELECT ... WHERE ... AND ... AND ... AND ... UNION ALL .…' (fixes #3395)

---

autotest/alg/applyverticalshiftgrid.py
autotest/alg/contour.py
autotest/alg/cutline.py
autotest/alg/polygonize.py
autotest/alg/rasterize.py
autotest/alg/sieve.py
autotest/alg/transformgeoloc.py
autotest/alg/warp.py
autotest/gcore/cog.py
autotest/gcore/gdal_stats.py
autotest/gcore/hfa_write.py
autotest/gcore/histogram.py
autotest/gcore/mask.py
autotest/gcore/misc.py
autotest/gcore/pam.py
autotest/gcore/rasterio.py
autotest/gcore/rat.py
autotest/gcore/tiff_ovr.py
autotest/gcore/tiff_read.py
autotest/gcore/tiff_write.py
autotest/gcore/transformer.py
autotest/gcore/virtualmem.py
autotest/gcore/vrt_read.py
autotest/gdrivers/openfilegdb.py
autotest/gdrivers/pds4.py
autotest/gnm/gnm_test.py

autotest: use pytest.mark.require_driver() in remaining modules

---

doc/source/programs/ogr2ogr.rst

Doc: clarify use of clip args in ogr2ogr

---

autotest/pyscripts/test_gdal2xyz.py
swig/python/gdal-utils/osgeo_utils/gdal2xyz.py

[Backport release/3.6] gdal2xyz.py: fix -srcnodata and -dstnodata options (fixes #7410)

---

frmts/hdf5/CMakeLists.txt

[Backport release/3.6] HDF5: fix detecting if HDF5 library is thread-safe (refs #7340)

---

autotest/alg/cutline.py
autotest/conftest.py
autotest/gcore/vrt_read.py
autotest/gdrivers/stacit.py
autotest/ogr/ogr_basic_test.py
autotest/ogr/ogr_fgdb.py
autotest/ogr/ogr_geoconcept.py
autotest/ogr/ogr_geojson.py
autotest/ogr/ogr_geom.py
autotest/ogr/ogr_geos.py
autotest/ogr/ogr_gml_read.py
autotest/ogr/ogr_ili.py
autotest/ogr/ogr_layer_algebra.py
autotest/ogr/ogr_mvt.py
autotest/ogr/ogr_openfilegdb.py
autotest/ogr/ogr_sql_sqlite.py
autotest/pyscripts/test_ogr2ogr_py.py
autotest/utilities/test_gdal_grid.py
autotest/utilities/test_gdalwarp_lib.py
autotest/utilities/test_ogr2ogr.py
autotest/utilities/test_ogr2ogr_lib.py
autotest/utilities/test_ogrlineref.py
cmake/template/pytest.ini.in

Adds a marker to skip tests requiring GEOS.
#7423

autotest: Add pytest.mark.require_geos

---

ogr/ogrspatialreference.cpp

fixes a small error in the docs

swap deprecation & since comment

---

doc/source/programs/gdalcompare.rst

There is no `gdalcompare.compare` function, it must be `gdalcompare.compare_db`. This updates the function name to `compare_db`.
* OS:
* Compiler:

Doc: update function reference in gdalcompare.rst

---

autotest/gcore/cog.py
frmts/gtiff/cogdriver.cpp

(fine tune 6310c1aecb3b31365fb36daedf064b3aaf3884ca)

COG: relax a bit the tolerance when computing tile number 

---

ogr/ogrsf_frmts/sqlite/ogrsqlitevirtualogr.cpp

[Backport release/3.6] GDAL as a SQLite3 loadable extension: avoid crash on Linux

---

autotest/ogr/ogr_basic_test.py
autotest/ogr/ogr_csv.py
autotest/ogr/ogr_fgdb.py
autotest/ogr/ogr_geojson.py
autotest/ogr/ogr_geom.py
autotest/ogr/ogr_georss.py
autotest/ogr/ogr_gpkg.py
autotest/ogr/ogr_gpx.py
autotest/ogr/ogr_jml.py
autotest/ogr/ogr_join_test.py
autotest/ogr/ogr_mitab.py
autotest/ogr/ogr_mysql.py
autotest/ogr/ogr_oci.py
autotest/ogr/ogr_osm.py
autotest/ogr/ogr_pg.py
autotest/ogr/ogr_rfc35_mem.py
autotest/ogr/ogr_rfc35_mitab.py
autotest/ogr/ogr_rfc35_shape.py
autotest/ogr/ogr_rfc35_sqlite.py
autotest/ogr/ogr_rfc41.py
autotest/ogr/ogr_sql_rfc28.py
autotest/ogr/ogr_sql_sqlite.py
autotest/ogr/ogr_sql_test.py
autotest/ogr/ogr_sqlite.py
autotest/ogr/ogr_style.py
autotest/ogr/ogr_virtualogr.py
autotest/ogr/ogr_vrt.py
autotest/ogr/ogr_wfs.py
autotest/ogr/ogr_wkbwkt_geom.py

Partial implementation of #7418 
* OS:
* Compiler:

autotest: replace gdal.PushErrorHandler for autotest/ogr

---

doc/source/drivers/vector/pg.rst
ogr/ogrsf_frmts/pg/ogrpgtablelayer.cpp

Adds doc for some undocumented options in Postgres driver
https://trac.osgeo.org/gdal/ticket/3744
https://trac.osgeo.org/gdal/ticket/4138

Doc: Describe some PG config options

---

apps/gdalbuildvrt_lib.cpp
apps/gdalwarp_lib.cpp

gdalbuildvrt / gdalwarp: remove useless calls to OGRRegisterAll()

---

doc/source/development/building_from_source.rst

Fix wording in doc

---

autotest/ogr/ogr_flatgeobuf.py
doc/source/drivers/vector/flatgeobuf.rst
ogr/ogrsf_frmts/flatgeobuf/ogrflatgeobuflayer.cpp

Backport https://github.com/OSGeo/gdal/pull/7483 to 3.6.

[Backport 3.6] FlatGeobuf: improve handling of null geoms (#7483)

---

autotest/gcore/hdf4_read.py
autotest/gdrivers/netcdf.py
autotest/gdrivers/netcdf_cf.py
autotest/ogr/ogr_hana.py
autotest/ogr/ogr_pg.py
autotest/pymod/gdaltest.py

Unrelated cleanups to test files I've collected during the last couple of weeks. I'm trying to avoid a bunch of noise by putting these in the same PR but can split if it's preferable.

Autotest: Assorted cleanups

---

doc/source/development/rfc/index.rst
doc/source/development/rfc/rfc94_field_precision_width_metadata.rst

Add RFC 94 text.
Note: I took 94 because there is already a PR about 93.

RFC 94: Numeric fields width/precision metadata

---

docker/ubuntu-full/Dockerfile
docker/ubuntu-small/Dockerfile

Some RUN lines remove the apt lists, and others do not. Remove the apt lists for all RUN lines. This shrinks the ubuntu-small-latest-amd64 image size from 402MB to 357MB, and the ubuntu-full-latest-amd64 image from 1.86GB to 1.82GB.
As a bonus, this also reduces the differences between the small and full Dockerfiles.
If the build should not repeatedly download and remove the apt lists, the `RUN --mount=type=cache ..` technique could be used when BuildKit is used for all builds. (Example for caching apt packages including locking here: https://github.com/moby/buildkit/blob/master/frontend/dockerfile/docs/reference.md#run---mounttypecache).
Could not find any.
* OS:
* Compiler:

docker/ubuntu*/Dockerfile: remove apt lists

---

autotest/ogr/ogr_gpkg.py
gcore/gdal.h
ogr/ogr_core.h
ogr/ogrsf_frmts/gpkg/ogrgeopackagedriver.cpp
ogr/ogrsf_frmts/gpkg/ogrgeopackagetablelayer.cpp
swig/include/ogr.i

These values will be stored in the gpkg_data_columns metadata table

[gpkg] Add support for setting field alternative names and comments

---

swig/python/gdal-utils/osgeo_utils/gdal2tiles.py

The original writing is too old, it's time to upgrade to HTML5
update doctype to html5 format
none
Not required
* OS:  Not required
* Compiler: Not required

update doctype to html5 format

---

frmts/gtiff/geotiff.cpp

COG/GTiff: fix propagation of extra samples/alpha info that affects JXL compression, in multi-threaded case 

---

frmts/gtiff/geotiff.cpp

- early compute nBlocksPerRow/Column to avoid recomputing them at several places
- add a ComputeBlockId() helper method

A few code cleanups in geotiff.cpp

---

autotest/gcore/vsihdfs.py
doc/source/development/building_from_source.rst
doc/source/user/virtual_file_systems.rst
port/CMakeLists.txt
port/cpl_vsil_hdfs.cpp

/vsihdfs/: fix ReadDir() and EOF flag (fixes #7632)

---

apps/ogr2ogr_lib.cpp
autotest/utilities/test_ogr2ogr_lib.py

ogr2ogr: Restore use of 3d clipping polygons

---

doc/source/drivers/raster/georaster.rst
doc/source/drivers/raster/jp2openjpeg.rst

Progession -> Progression
and one "Option Options" -> "Open Options" :)

Fix typos in documentation

---

swig/python/gdal-utils/osgeo_utils/gdal_fillnodata.py

Fixes https://github.com/OSGeo/gdal/issues/7651
I took creation option parser from gdal_calc.py

Fix gdal_fillnodata creation option parser

---

frmts/grib/degrib/degrib/myerror.cpp
port/cpl_port.h
port/cpl_vsi_mem.cpp

Fixes https://lists.osgeo.org/pipermail/gdal-dev/2023-April/057154.html

GCC 13 warning fixes

---

doc/source/drivers/vector/ngw.rst

Fix NGW documentation links

---

alg/internal_libqhull/io_r.c
gcore/gdalmultidim_gridded.cpp
scripts/clang-format.sh

[Backport release/3.7] Avoids warning with gcc 13.1 of mingw64

---

.github/workflows/linux_build.yml

CI: Strip invalid characters from container tag

---

.github/workflows/linux_build.yml

[Backport release/3.7] CI: Strip invalid characters from container tag

---

doc/source/tutorials/warp_tut.rst

Small fixes to warp tutorial doc.

warp_tut.rst: small fixes

---

autotest/cpp/test_cpl.cpp
autotest/cpp/test_gdal.cpp
autotest/cpp/test_ogr.cpp
ci/travis/graviton2/script.sh
ci/travis/s390x/script.sh
port/cpl_recode_iconv.cpp

[Backport release/3.7] Fix issues on big endian hosts: recode from UTF-16, and broken tests

---

gcore/mdreader/reader_pleiades.cpp

Backport #7653
**Authored by:** @tbonfort

[Backport release/3.7] DIMAP: Correctly set RPC origin for SPOT, PHR and PNEO

---

autotest/ogr/ogr_mitab.py
ogr/ogrsf_frmts/mitab/mitab_spatialref.cpp

[Backport release/3.7] MITAB: fix reading CRS with LCC_2SP and non-metre unit (fixes #7715)

---

autotest/gdrivers/netcdf_multidim.py
frmts/netcdf/netcdfmultidim.cpp
gcore/gdalmultidim.cpp

- Multidim GDALGroup::CopyFrom(): modify logic to copy first indexing variables. Fixes issue with gdalmdimtranslate from Zarr to netCDF
- netCDF multidim: fix issues with data vs definition mode

Multidim related fixes

---

autotest/gdrivers/netcdf_multidim.py
frmts/netcdf/netcdfmultidim.cpp
gcore/gdalmultidim.cpp

Backport of https://github.com/OSGeo/gdal/pull/7710

[Backport 3.7] Multidim related fixes 

---

.github/workflows/code_checks.yml
autotest/ogr/ogr_geojson.py
ogr/ogrsf_frmts/geojson/libjson/GDAL_README.txt
ogr/ogrsf_frmts/geojson/libjson/json_object.c
ogr/ogrsf_frmts/geojson/libjson/json_tokener.c
ogr/ogrsf_frmts/geojson/libjson/json_util.c
scripts/clang-format.sh

Fixes https://github.com/qgis/QGIS/issues/52731

Fix parsing of floating-point numbers in JSON with internal libjson-c on Windows

---

frmts/zlib/contrib/infback9/minified_zutil.h

[Backport release/3.7] minified_zutil.h: fix build error on Gentoo and derivatives (fixes #7739)

---

frmts/wmts/wmtsdataset.cpp

[Backport release/3.7] WMTS: workaround buggy TileMatrix.TopLeftCorner of one server (fixes #5729)

---

autotest/ogr/ogr_mssqlspatial.py
ogr/ogrsf_frmts/mssqlspatial/ogr_mssqlspatial.h
ogr/ogrsf_frmts/mssqlspatial/ogrmssqlspatiallayer.cpp
ogr/ogrsf_frmts/mssqlspatial/ogrmssqlspatialtablelayer.cpp

MSSQL: fix crash in ogr2ogr when BCP is enabled

---

autotest/ogr/ogr_mssqlspatial.py
ogr/ogrsf_frmts/mssqlspatial/ogr_mssqlspatial.h
ogr/ogrsf_frmts/mssqlspatial/ogrmssqlspatiallayer.cpp
ogr/ogrsf_frmts/mssqlspatial/ogrmssqlspatialtablelayer.cpp

[Backport release/3.7] MSSQL: fix crash in ogr2ogr when BCP is enabled

---

.github/workflows/windows_build.yml

```
Invoke-WebRequest: D:\a\_temp\6583a48c-9e8d-43e9-93cc-43f2a9f47ef1.ps1:35
Line |
35 |  … pe Leaf)) { Invoke-WebRequest "$env:LIBDEFLATE_URL" -OutFile "$env:LI …
|                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| Authentication failed, see inner exception.
```
Cf https://github.com/OSGeo/gdal/actions/runs/5045071095/jobs/9048887297

CI: windows_build.yml: disable downloading of libdeflate.zip which now fails quasi systematically for unknown reason

---

.github/workflows/windows_build.yml

[Backport release/3.7] CI: windows_build.yml: disable downloading of libdeflate.zip which now fails quasi systematically for unknown reason

---

autotest/gdrivers/data/isg/approx_georeferencing_auto_corrected.isg
autotest/gdrivers/data/isg/approx_georeferencing_rejected_by_default.isg
autotest/gdrivers/data/isg/approx_georeferencing_warning.isg
autotest/gdrivers/isg.py
frmts/aaigrid/aaigriddataset.cpp

Adresses https://lists.osgeo.org/pipermail/gdal-dev/2023-May/057205.html

ISG: relax tolerence check to accept GEOIDEAR16_20160419.isg

---

autotest/gdrivers/zarr_driver.py
frmts/zarr/zarr_v3_array.cpp

on hold pending https://github.com/zarr-developers/zarr-specs/pull/236 adoption

Zarr V3: add support for fill_value for complex data types

---

doc/source/drivers/raster/vrt.rst

tiny typo (stray extra character)

Update vrt.rst - fix tiny typo

---

autotest/ogr/ogr_mssqlspatial.py
ogr/ogrsf_frmts/mssqlspatial/ogr_mssqlspatial.h
ogr/ogrsf_frmts/mssqlspatial/ogrmssqlgeometrywriter.cpp

MSSQL: fix GEOGRAPHY clockwise vertex order

---

autotest/ogr/ogr_mssqlspatial.py
ogr/ogrsf_frmts/mssqlspatial/ogrmssqlspatialtablelayer.cpp

MSSQL: Fix cannot write binary field in BCP mode

---

autotest/ogr/ogr_mssqlspatial.py
ogr/ogrsf_frmts/mssqlspatial/ogr_mssqlspatial.h
ogr/ogrsf_frmts/mssqlspatial/ogrmssqlgeometrywriter.cpp

[Backport release/3.7] MSSQL: fix GEOGRAPHY clockwise vertex order

---

autotest/ogr/ogr_mssqlspatial.py
ogr/ogrsf_frmts/mssqlspatial/ogrmssqlspatialtablelayer.cpp

[Backport 3.7] MSSQL: Fix cannot write binary field in BCP mode (#7841)

---

port/cpl_vsil_adls.cpp

[Backport release/3.7] /vsiadls/: make it take into account Azure SAS token

---

doc/source/_extensions/configoptions.py
doc/source/development/rfc/rfc26_blockcache.rst
doc/source/user/configoptions.rst
gcore/gdalrasterband.cpp

Adds documentation for `GDAL_BAND_BLOCK_CACHE` and changes code slightly to validate this option.

GDALRasterBand: Document and validate GDAL_BAND_BLOCK_CACHE

---

.github/workflows/cmake_builds.yml

Remove the clcache dependency which was causing troubles

CI: try to avoid libjpeg-turbo 2.0 from non-conda-forge channel to be installed

---

.github/workflows/cmake_builds.yml

Remove the clcache dependency which was causing troubles

[Backport 3.7] CI: try to avoid libjpeg-turbo 2.0 from non-conda-forge channel to be installed

---

frmts/netcdf/netcdfdataset.cpp
frmts/netcdf/netcdflayer.cpp

[Backport release/3.7] netCDF vector: fix crash on invalid layer (fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=58469)

---

doc/source/development/rfc/rfc31_ogr_64.rst
doc/source/development/rfc/rfc76_ogrpythondrivers.rst
doc/source/drivers/vector/sqlite.rst
doc/source/user/configoptions.rst

Adds definitions for some options listed in #7873.

Doc: Add assorted config option definitions

---

.github/workflows/fedora_rawhide/Dockerfile.ci

[Backport release/3.7] CI: fedora:rawhide: workarounds bug in Docker image

---

autotest/gdrivers/openfilegdb.py
doc/source/drivers/raster/openfilegdb.rst
ogr/ogrsf_frmts/openfilegdb/filegdbindex.cpp
ogr/ogrsf_frmts/openfilegdb/filegdbtable.cpp
ogr/ogrsf_frmts/openfilegdb/filegdbtable.h
ogr/ogrsf_frmts/openfilegdb/gdalopenfilegdbrasterband.cpp
ogr/ogrsf_frmts/openfilegdb/ogr_openfilegdb.h
ogr/ogrsf_frmts/openfilegdb/ogropenfilegdbdatasource.cpp

Builds upon https://github.com/OSGeo/gdal/pull/7884
Can be tested with datasets at
https://resources.gisdata.mn.gov/pub/data/elevation/lidar/county/washington/geodatabase/

OpenFileGDB: add support for FileGDB v9 raster

---

port/cpl_vsi_virtual.h

[Backport release/3.7] Add missing include <memory>

---

doc/source/drivers/vector/esrijson.rst

Replaces the command line example in the documentation for ESRIJSON.  The example URL  was not working due to its server being taken offline.  This one gives it a working example.
Issue #7901  - (Note: The URL was trimmed down from the one in the issue.)
N/A
N/A
* OS:
* Compiler:

Doc: ESRIJSON - update example server

---

autotest/ogr/ogr_mysql.py
ogr/ogrsf_frmts/mysql/ogr_mysql.h
ogr/ogrsf_frmts/mysql/ogrmysqldatasource.cpp

[Backport release/3.7] MySQL: add support for inserting new SRS in MySQL >= 8 INFORMATION_SCHEMA.ST_SPATIAL_REFERENCE_SYSTEMS table (refs #7781)

---

frmts/netcdf/netcdfdataset.cpp
frmts/netcdf/netcdfdataset.h
frmts/netcdf/netcdfmultidim.cpp

[Backport release/3.7] netCDF: parse coordinates attribute from Sentinel-3 Synergy product
