- gdal/PROVENANCE.TXT
The history, while interesting, can be preserved in version control. I think it's better that the content of the file corresponds to the source tree.
> * gdal/PROVENANCE.TXT: Update to remove directories that no longer exist.

- gdal/COMMITTERS
According to Even's instructions:
GDAL SVN committers that don't have yet push rights to github, please submit a 
pull request to gdal/COMMITTERS file with a new line with your contact 
information, so your github nickname can be added to the authorized list of 
people with push rights (if you already have push rights, please also update 
COMMITTERS with your info)
https://lists.osgeo.org/pipermail/gdal-dev/2018-March/048296.html
> Update my contact info to gdal/COMMITERS

- gdal/frmts/rda/frmt_rda.html
- gdal/frmts/rda/rdadataset.cpp
Fixes a bug whereby the driver uses the nativeTileFormat from the image metadata instead of defaulting to .tif. The nativeTileFormat field in the image metadata is only valid for the source Idaho data. Using the value may cause tile fetching from an unsupported RDA endpoing, Only TIF endpoint is officially supported at the present time.
Remove duplicate text block from documentation.
The RDA_NATIVE_FORMAT config option is meant to NOT BE documented. It is only used internally for testing against the RDA endpoints for future development.
- [ x] Add test case(s) - not needed
> default driver to fetch from tif RDA endpoint

- gdal/frmts/rda/frmt_rda.html
- gdal/frmts/rda/rdadataset.cpp
colorInterpretation in image metadata is optional and may not exist in some cases. Make reading "colorInterpretation" from image.json and check for empty before using  in the driver.
* OS:
* Compiler:
> RDA Drive: make m_osColorInterpretation optional

- gdal/GDALmake.opt.in
- gdal/ci/travis/osx/install.sh
Pass `--silent` to `libtool` in compile (C and C++), link, install and clean modes so that libtool does not show subordinate command lines. This allows `make -s` to operate properly.
> Pass --silent to libtool

- gdal/ogr/ogr_srs_esri.cpp
morphToESRI now checks the return from RemapGeogCSName.
There are similar cases not yet fixed.
Found with autofuzz.
> Detect when PROJCS cannot be found in RemapGeogCSName

- autotest/gdrivers/rda.py
- gdal/frmts/rda/frmt_rda.html
- gdal/frmts/rda/rdadataset.cpp
GBDX Auth was updated and now no longer requires client_id or client_secret creds (GBDX_CLIENT_ID or GBDX_CLIENT_SECRET) when fetching bearer tokens.
https://gbdxdocs.digitalglobe.com/docs/authentication-changes
* OS:
* Compiler:
> remove auth deprecated fields

- gdal/MIGRATION_GUIDE.TXT
- gdal/ogr/ogr_api.h
- gdal/ogr/ogr_feature.h
- gdal/ogr/ogrfeature.cpp
- gdal/ogr/ogrfeaturedefn.cpp
- gdal/ogr/ogrfielddefn.cpp
- gdal/ogr/ogrgeomfielddefn.cpp
- gdal/ogr/ogrsf_frmts/mitab/mitab.h
- gdal/ogr/ogrsf_frmts/mitab/mitab_feature.cpp
- gdal/ogr/ogrsf_frmts/openfilegdb/ogropenfilegdblayer.cpp
- gdal/ogr/ogrsf_frmts/pg/ogr_pg.h
- gdal/ogr/ogrsf_frmts/pg/ogrpgdatasource.cpp
- gdal/ogr/ogrsf_frmts/pg/ogrpglayer.cpp
- gdal/ogr/ogrsf_frmts/pg/ogrpgresultlayer.cpp
- gdal/ogr/ogrsf_frmts/pg/ogrpgtablelayer.cpp
- gdal/ogr/ogrsf_frmts/plscenes/ogr_plscenes.h
- gdal/ogr/ogrsf_frmts/plscenes/ogrplscenesdatav1layer.cpp
- gdal/ogr/ogrsf_frmts/shape/ogrshape.h
- gdal/ogr/ogrsf_frmts/shape/ogrshapelayer.cpp
This can have an impact on out-of-tree drivers. See MIGRATION_GUIDE.TXT
> Add const-correctness to methods in OGRFeatureDefn, OGRFeature and OGR[Geom]FieldDefn

- gdal/swig/python/setup.py
It's not very Pythonic to catch all exceptions with a bare `except` statement. The only thing we are trying to detect here is a compilation error, so we should catch `CompileError` only. All other exceptions should propagate back up the call stack for more helpful diagnostics.
> Catch CompileError only in setup.py

- gdal/swig/python/setup.py
The present version of `supports_cxx11` is complicated and involves forking the Python process to try and bury messages written to standard error by the compiler. Even then, comments suggest that it doesn't work properly on Ubuntu Precise. This patch simplifies this code using `os.dup()` and `os.dup2()` to temporarily redirect standard error and eliminates the `fork()` call.
* OS: All POSIX systems
* Compiler: g++
> Make silent output work in supports_cxx11

- gdal/scripts/fix_container_dot_size_zero.py
Replaces `x == a or x == b or x == c` with the simpler idiom  `x in [a, b, c]`. Submitting as a separate PR as other flake8 fixes are just whitespace tweaks.
> Python simplification

- gdal/scripts/check_broken_links.py
This PR simplifies the `check` function in `check_broken_links.py`. The change now checks the HTTP response against `requests.codes.ok`, not `200`. The `requests.get()` method does not raise exceptions for HTTP errors (just check `r.status_code`), so it is better to not catch any exceptions here. This eliminates a `flake8` warning about a catching a bare exception.
> Simplify gdal/scripts/check_broken_links.py

- gdal/swig/python/samples/densify.py
Eliminates `degrees()` and `radians()` functions. Use the ones in the `math` module instead.
> Use math.degrees, math.radians.

- gdal/swig/python/samples/classify.py
- gdal/swig/python/samples/crs2crs2grid.py
- gdal/swig/python/samples/gdal_lut.py
- gdal/swig/python/samples/magphase.py
- gdal/swig/python/samples/ogr2ogr.py
- gdal/swig/python/samples/validate_gpkg.py
- gdal/swig/python/samples/validate_jp2.py
- gdal/swig/python/scripts/gdalcompare.py
- gdal/swig/python/scripts/gdalident.py
Bare exceptions (where `except` does not specify an exception type) should be avoided because they undermine the exception system by catching every exception type. Many of the `except` statements in the Python code can be restricted to specific types (eg `OSError`, `ImportError`, etc).
> Avoid bare exceptions where possible

- autotest/gcore/pam.py
- autotest/gdrivers/grib.py
- autotest/gdrivers/mrf.py
- autotest/gdrivers/netcdf_cfchecks.py
- autotest/gdrivers/rraster.py
- autotest/pymod/gdaltest.py
It is more Pythonically correct to use `isinstance()` rather than compare types directly. It leads to more readable code, to boot.
> Python code: Do not compare types, use isinstance()

- gdal/swig/include/python/docs/doxy2swig.py
Removes the single, deprecated occurrence of `<>` in the Python code.
> Python code: '<>' is deprecated, use '!='

- autotest/gdrivers/netcdf_cfchecks.py
- gdal/swig/include/python/docs/doxy2swig.py
The `has_key()` method on dictionaries is deprecated. The preferred way to do this is to test `if k in dict`.
> Python code: Do not use deprecated has_key().

- autotest/gcore/tiff_read.py
- autotest/gcore/tiff_write.py
- autotest/gcore/vsifile.py
- autotest/gdrivers/kro.py
- autotest/gdrivers/nitf.py
- autotest/ogr/ogr_geom.py
- autotest/ogr/ogr_gmlas.py
- autotest/ogr/ogr_mvt.py
- autotest/ogr/ogr_ods.py
- autotest/ogr/ogr_shape.py
- autotest/ogr/ogr_sqlite.py
- autotest/ogr/ogr_wfs.py
- autotest/ogr/ogr_wktempty.py
Uses `if x` and `if not x` rather than `==` comparison with True and False. In most cases, the code is much easier to read. `if x != False` is very unnatural!
> Python code: Use if x/not x rather than == comparison with True/False

- autotest/gdrivers/grib.py
- autotest/gdrivers/netcdf.py
- autotest/pymod/gdaltest.py
- gdal/swig/python/scripts/gdal_retile.py
Removes a few `flake8` warnings about E116 (unexpected indentation of comments).
> Python code: Fix E116: unexpected indentation (comment)

- autotest/gdrivers/arg.py
- autotest/gdrivers/netcdf.py
Silences warnings E714: `test for object identity should be 'is not'`.
> Python code: Fix warning E714: test for object identity should be 'is not'.

- autotest/gdrivers/arg.py
- gdal/swig/python/samples/gdalinfo.py
Silences diagnostic E227 (`missing whitespace around bitwise or shift operator`).
> Python code: Fix E227: missing whitespace around bitwise or shift operator

- autotest/gdrivers/db2.py
- autotest/gdrivers/dimap.py
- autotest/gdrivers/ecw.py
- autotest/gdrivers/grib.py
- autotest/gdrivers/netcdf_cfchecks.py
- autotest/gdrivers/saga.py
- autotest/gdrivers/usgsdem.py
- autotest/ogr/ogr_geoconcept.py
- autotest/ogr/ogr_geom.py
- autotest/ogr/ogr_georss.py
- autotest/ogr/ogr_gpx.py
- autotest/ogr/ogr_libkml.py
- autotest/ogr/ogr_mem.py
- autotest/ogr/ogr_pg.py
- autotest/ogr/ogr_shape.py
- autotest/ogr/ogr_vfk.py
- autotest/ogr/ogr_wktempty.py
- autotest/pymod/gdaltest.py
- autotest/pymod/webserver.py
- gdal/swig/include/gdal_array.i
- gdal/swig/python/osgeo/gdal_array.py
- gdal/swig/python/samples/gdal_vrtmerge.py
- gdal/swig/python/samples/ogr2ogr.py
- gdal/swig/python/scripts/gdal_retile.py
- gdal/swig/python/scripts/mkgraticule.py
Fixes diagnostic E211: `whitespace before '('`. Note that there is one non-whitespace change in the `diff` output:
```
diff --git a/gdal/swig/python/samples/ogr2ogr.py b/gdal/swig/python/samples/ogr2ogr.py
index a1dd054..e554441 100755
--- a/gdal/swig/python/samples/ogr2ogr.py
+++ b/gdal/swig/python/samples/ogr2ogr.py
@@ -73,7 +73,7 @@ nLastTick = -1
def TermProgress( dfComplete, pszMessage, pProgressArg ):
global nLastTick
-    nThisTick = (int) (dfComplete * 40.0)
+    nThisTick = int(dfComplete * 40.0)
if nThisTick < 0:
nThisTick = 0
```
This code that mimics C did work, but only because `(int)` as just an over-parenthesised version of `int`.
> Python code: Fix E211: whitespace before '('.

- autotest/ogr/ogr_dxf.py
Silences the Pylint error:
```
autotest/ogr/ogr_dxf.py:2467: [E1121(too-many-function-args), ogr_dxf_33] Too many positional arguments for function call
```
> Python code: autotest/ogr/ogr_dxf.py: Fix E1121.

- autotest/alg/warp.py
- autotest/gdrivers/netcdf_cfchecks.py
- autotest/ogr/ogr_geom.py
- autotest/ogr/ogr_sde.py
- autotest/ogr/ogr_wasp.py
- autotest/pymod/gdaltest.py
Silences diagnostic E228 (`missing whitespace around modulo operator').
> Python code: Fix E228: missing whitespace around modulo operator

- gdal/port/GNUmakefile
cpl_json.h seems to not get installed in the current master branch. This file is required when building Fiona against the master branch of gdal:  https://travis-ci.org/rbuffat/Fiona/jobs/363032884#L2151
With this PR cpl_json.h gets installed.
> install cpl_json.h

- autotest/ogr/ograpispy.py
I think this was missed in the adjustments made for #418 ?
> Python code: Call print(), not print for Python 3.

- gdal/swig/include/python/docs/doxy2swig.py
Silences two warnings from `flake8` about unused variables.
> Python code: Remove unused variables and imports

- gdal/scripts/completionFinder.py
Fixed warnings about unused imports.
> Remove imports: os, os.path, subprocess.call.

- autotest/gcore/tiff_write.py
Simplifies the setup of the dictionary in `tiff_write_4`. There is no need to loop over the list of tuples when this works instead:
```
>>> lst = [(1,2), (3,4), (5,6)]
>>> dict(lst)
{1: 2, 3: 4, 5: 6}
```
> Python code: Simplify dictionary setup in autotest/gcore/tiff_write.py

- autotest/ogr/ograpispy.py
Fixes a typo that must have slipped through when this code was introduced a week ago.
> Python code: Fix typo in unified_diff `lineterm' argument

- gdal/swig/include/gdal_array.i
Removes some trailing semicolons in the SWIG interface files.
> Python code: Remove trailing semicolons in gdal_array.i 

- autotest/gcore/hfa_rfc40.py
- autotest/gcore/numpy_rw.py
- autotest/gcore/pam.py
- autotest/gcore/tiff_ovr.py
- autotest/gcore/tiff_write.py
- autotest/gdrivers/arg.py
- autotest/gdrivers/hfa.py
- autotest/gdrivers/jp2lura.py
- autotest/gdrivers/jp2openjpeg.py
- autotest/gdrivers/mrsid.py
- autotest/gdrivers/netcdf_cfchecks.py
- autotest/gdrivers/pds4.py
- autotest/gdrivers/wcs.py
- autotest/gdrivers/xmp.py
- autotest/gdrivers/xyz.py
- autotest/ogr/ogr_fgdb_stress_test.py
- autotest/ogr/ogr_geojson.py
- autotest/ogr/ogr_mitab.py
- autotest/ogr/ogr_mysql.py
- autotest/ogr/ogr_pg.py
- autotest/ogr/ogr_plscenes.py
- autotest/ogr/ogr_shape.py
- autotest/ogr/ogr_wfs3.py
- autotest/osr/osr_metacrs.py
- autotest/pymod/gdaltest.py
- autotest/pymod/webserver.py
- autotest/pyscripts/test_gdal_calc.py
- autotest/test_random_tiff.py
- autotest/utilities/test_gdal_translate_lib.py
- autotest/utilities/test_gdaldem_lib.py
Some variables shadow the names of built-in types (as found by `pylint`). This patch either renames the variables or avoids declaring a variable at all.
> Python code: Avoid using built-in types as variable names

- autotest/gcore/minixml.py
- autotest/gcore/tiff_write.py
- autotest/gcore/vsioss.py
- autotest/gcore/vsis3.py
- autotest/gcore/vsistdin.py
- autotest/gcore/vsizip.py
- autotest/gdrivers/jpeg.py
- autotest/ogr/ogr_fgdb.py
- autotest/ogr/ogr_gml_geom.py
- autotest/ogr/ogr_shape.py
- autotest/ogr/ogr_sql_sqlite.py
- autotest/ogr/ogr_wkbwkt_geom.py
- autotest/pymod/xmlvalidate.py
In Python, `'a' * 3 == 'aaa'`. Simplify convoluted `for` loops and `join()` with list comprehensions to construct strings at runtime.
> Python code: Use str * N instead of more convoluted ways to compute strings

- gdal/swig/include/python/docs/doxy2swig.py
- gdal/swig/python/scripts/gdal2tiles.py
Changes `gdal/swig/include/python/docs/doxy2swig.py` to use `isinstance` instead of `type(x) == types.T`. It is cleaner and improves Python 3 compatibility.
> Python code: Use isinstance()

- autotest/gdrivers/db2.py
Fixes a suspected typo in `db2.py`. Not sure how this ever worked?
> Python code: Typo fix in autotest/gdrivers/db2.py

- autotest/gdrivers/netcdf_cfchecks.py
Pylint warns about `sys.exit` shadowing the built-in `exit()`. Best to import `sys` and just refer to `sys.exit` for no ambiguity.
> Python code: Don't shadow exit().

- autotest/gcore/pamproxydb.py
- autotest/gcore/tiff_write.py
- autotest/gdrivers/georaster.py
- autotest/gdrivers/netcdf_cfchecks.py
- autotest/ogr/ogr_shape.py
- autotest/pymod/gdaltest.py
- gdal/frmts/ecw/lookup.py
- gdal/ogr/ogrsf_frmts/s57/s57tables.py
- gdal/swig/python/scripts/epsg_tr.py
- gdal/swig/python/scripts/esri2wkt.py
Pylint warns about uses of `string.split` and `string.strip`. This patch calls `strip()` and `split()` methods on string objects rather than calling the module functions `string.strip` and `string.split` which are not in Python 3. It's also more object oriented. :-)
> Python code: Simplify uses of string.split and friends

- gdal/swig/python/samples/hsv_merge.py
- gdal/swig/python/samples/ogr_dispatch.py
- gdal/swig/python/samples/ogr_layer_algebra.py
- gdal/swig/python/samples/rel.py
- gdal/swig/python/samples/val_repl.py
- gdal/swig/python/scripts/gdal2xyz.py
- gdal/swig/python/scripts/gdal_fillnodata.py
- gdal/swig/python/scripts/gdal_merge.py
- gdal/swig/python/scripts/gdal_pansharpen.py
- gdal/swig/python/scripts/gdal_polygonize.py
- gdal/swig/python/scripts/gdal_proximity.py
- gdal/swig/python/scripts/gdal_sieve.py
- gdal/swig/python/scripts/rgb2pct.py
Renames variables called `format` -> `frmt` to silence warnings from Pylint about shadowing the built-in `format()`.
> Python code: Rename 'format' -> 'frmt' to avoid shadowing the built-in format().

- gdal/swig/python/samples/tolatlong.py
I was confused as to why a variable representing longitude was called `int` (and reported by Pylint). I worked out that someone probably did a `long` -> `int` bulk replace at some point. ;-) Let's call it `lon` instead.
> Python code: gdal/swig/python/samples/tolatlong.py: 'int' -> 'lon'.

- autotest/alg/warp.py
- autotest/gcore/basic_test.py
- autotest/gcore/gdal_stats.py
- autotest/gcore/misc.py
- autotest/gcore/numpy_rw.py
- autotest/gcore/thread_test.py
- autotest/gcore/tiff_read.py
- autotest/gdrivers/isis.py
- autotest/gdrivers/wcs.py
- autotest/pymod/gdaltest.py
- autotest/pymod/gdaltest_python2.py
- autotest/pymod/gdaltest_python3.py
- autotest/pymod/webserver.py
- autotest/utilities/test_ogr2ogr_lib.py
- gdal/swig/python/samples/build_jp2_from_xml.py
- gdal/swig/python/samples/densify.py
- gdal/swig/python/samples/gdal_cp.py
- gdal/swig/python/samples/gdal_mkdir.py
- gdal/swig/python/samples/gdal_rm.py
- gdal/swig/python/samples/gdal_rmdir.py
- gdal/swig/python/samples/ogr_dispatch.py
- gdal/swig/python/scripts/gdal_calc.py
- gdal/swig/python/scripts/gdalcompare.py
Silences warnings from Pylint about unused arguments. I did not want to (yet) remove the argument and change the function signatures because I don't want to break the existing API. I will re-assess later.
> Python code: Silence unused argument warnings from Pylint

- autotest/gdrivers/netcdf_cfchecks.py
Same as the last patch on this branch. ;-)
> Python code: Use sys.exit() without shadowing the built-in exit()

- gdal/swig/python/samples/densify.py
Fixes the following warnings from Pylint:
```
gdal/swig/python/samples/densify.py:104: [W0715(raising-format-tuple), Translator.open] Exception arguments suggest string formatting might be intended
gdal/swig/python/samples/densify.py:106: [W0715(raising-format-tuple), Translator.open] Exception arguments suggest string formatting might be intended
```
> Python code: Fix exception raising in densify.py

- gdal/swig/include/python/gdal_python.i
Removes some trailing semicolons from Python code embedded in `.i` files. SWIG output files will need to be regenerated.
> Python code: Remove some more trailing semicolons

- autotest/gdrivers/vrtrawlink.py
The function `_xmlsearch` contained a for-else loop that ended in `else: None`. Since the function will return None if it control falls off the end of the function, these two lines can simply be deleted.
> Python code: vrtrawlink.py (_xmlsearch): Remove else: None

- gdal/swig/python/samples/ogr_layer_algebra.py
Silences a Pylint warning about a possibly undefined loop index variable. Defensively initialise `iLayer` in case there are  no loop iterations (ie. `cnt` is zero).
> * ogr_layer_algebra.py: Defensively initialise iLayer

- gdal/swig/python/scripts/gdal2tiles.py
Use explicit `numpy_available` variable and don't overload the use of the `numpy` name. This clean-up silences the following false positive warnings from Pylint (but we should still make the code clearer).
```
gdal/swig/python/scripts/gdal2tiles.py:619: [E1101(no-member), scale_query_to_tile] Instance of 'bool' has no 'zeros' member
gdal/swig/python/scripts/gdal2tiles.py:619: [E1101(no-member), scale_query_to_tile] Instance of 'bool' has no 'uint8' member
```
> * gdal/swig/python/scripts/gdal2tiles.py: Use explicit numpy_available

- autotest/gcore/tiff_write.py
- autotest/ogr/ogr_gml_read.py
- autotest/ogr/ogr_wasp.py
- gdal/swig/python/samples/gdalpythonserver.py
- gdal/swig/python/samples/ogr2ogr.py
- gdal/swig/python/scripts/ogrmerge.py
Changes list constructions from the form `[x for i  in range(n)]` to `[x] * n`. Not only is it clearer and more compact, it eliminates a `for` loop with an unreferenced loop index variable. ;-)
> Python code: Use [x] * n instead of [x for i in range(n)]

- autotest/gdrivers/netcdf_cf.py
- autotest/gdrivers/snodas.py
- autotest/ogr/ogr_openfilegdb.py
- autotest/ogr/ogr_shape.py
- autotest/osr/osr_basic.py
- gdal/swig/python/scripts/gdal_fillnodata.py
- gdal/swig/python/scripts/gdal_polygonize.py
- gdal/swig/python/scripts/gdal_sieve.py
Pylint warns about `is` comparisons with literals because it can return false negatives in some cases Two strings may have the same value but not be the same object. `==` returns `True` and `is` returns `False`. It is best to use `==`.
> Python code: Fix 'is' comparisons with literals

- autotest/gdrivers/netcdf_cfchecks.py
- autotest/gdrivers/wcs.py
- autotest/kml_generate_test_files.py
- autotest/ogr/ogr_gmlas.py
- autotest/ogr/ogr_shape.py
- autotest/ogr/ogr_sql_sqlite.py
- autotest/ogr/ogr_wfs.py
- autotest/pymod/webserver.py
- gdal/swig/python/samples/gdalpythonserver.py
- gdal/swig/python/samples/ogrinfo.py
- gdal/swig/python/scripts/gdal_calc.py
Silences  `useless-return` warnings from Pylint. For stub functions, I used the common idiom of using `pass` instead of `return` to show that the function is a placeholder.
> Python code: Remove useless returns

- autotest/ogr/ogr_rfc35_mem.py
- autotest/ogr/ogr_rfc35_mitab.py
- autotest/ogr/ogr_rfc35_shape.py
- autotest/ogr/ogr_rfc35_sqlite.py
Fixes issue #534 by renaming some argument names blacklisted by Pylint.
> Python code: Rename foo, bar, baz, baq -> field1, field2, field3, field4

- gdal/port/cpl_sha256.cpp
- gdal/port/cpl_vsil_crypt.cpp
This issue is fixed up by replacing byte type to CtyptoPP:byte in the following files:
gdal/port/cpl_sha256.cpp
gdal/port/cpl_vsil_crypt.cpp
* OS: Arch Linux
* Compiler: gcc/g++
> ogr2ogr: fix compilation error with Crypto++ 7.0.0 (fix #541)

- gdal/frmts/gtiff/libgeotiff/dump_symbols.sh
Change `$data_symbol_list` to `$rodata_symbol_list`. Looks like a bug?
> Scripts: Is this a bug in dump_symbols.sh?

- gdal/frmts/gtiff/libgeotiff/dump_symbols.sh
- gdal/frmts/gtiff/libtiff/dump_symbols.sh
- gdal/fuzzers/build_seed_corpus.sh
Suggestion from Shellcheck: Prefix `*` globs with `./` to ensure that filenames such as `--foo` become `./--foo` and won't be treated as an `--` command line option.
> Prefix * globs with ./

- autotest/gcore/hfa_srs.py
- autotest/gdrivers/netcdf.py
- autotest/gdrivers/netcdf_cf.py
- autotest/ogr/ogr_mitab.py
- autotest/pymod/gdaltest.py
- autotest/pymod/gdaltest_python2.py
- autotest/pymod/test_cli_utilities.py
Silences more Pylint warnings about bare exceptions. In this patch, we catch most of the `OSError` exceptions.
> Python code: Remove some more bare exceptions

- gdal/ci/travis/csa_common/before_install.sh
- gdal/ci/travis/csa_common/install.sh
- gdal/ci/travis/csa_common/script.sh
- gdal/ci/travis/csa_part_1/install.sh
- gdal/ci/travis/osx/script.sh
- gdal/ci/travis/precise/install.sh
- gdal/ci/travis/precise/script.sh
- gdal/ci/travis/python3/script.sh
- gdal/ci/travis/trusty_clang/install.sh
- gdal/ci/travis/trusty_clang/script.sh
- gdal/fuzzers/build_seed_corpus.sh
- gdal/mkgdaldist.sh
- gdal/scripts/fix_typos.sh
Avoids using `cd` in shell scripts -- it can be so fragile. In some cases, we use subshells and in others, we can just update paths so that a directory change isn't needed.
> Scripts: Avoid cd in shell scripts

- autotest/alg/warp.py
- autotest/ogr/ogr_mitab.py
Now that `enumerate()` is used instead of `range(len(x))`, Pylint discovers which loops don't use the index and can be replaced with `for elt in lst:`
> Python code: Remove some enumerate() calls when the index variable isn't used

- autotest/ogr/ogr_shape.py
Silences the last 'unreachable' warning from Pylint.
> Python code: Disable 'unreachable' warning from Pylint

- gdal/ogr/ogrsf_frmts/s57/s57tables.py
Rather than fixing the Pylint warnings in `EscapeLine()`, it was easier to replace it with this one line function body.
> Python code: Rewrite EscapeLine

- autotest/gdrivers/kmlsuperoverlay.py
- autotest/gdrivers/netcdf_cfchecks.py
- autotest/ogr/ogr_gml_read.py
- autotest/ogr/ogr_ili.py
- autotest/ogr/ogr_pdf.py
- autotest/ogr/ogr_shape.py
- autotest/pymod/xmlvalidate.py
- gdal/swig/python/scripts/gdalident.py
Pylint warns about variables called `file`, which collide with the `file` type. Rename them sensibly to silence such warnings.
> Python code: Rename file

- autotest/osr/osr_epsg.py
- gdal/ogr/ogr_fromepsg.cpp
See  https://lists.osgeo.org/pipermail/gdal-dev/2018-May/048495.html
> importFromEPSG(): append ' (deprecated)' at end of deprecated GCS

- gdal/swig/python/samples/gdalcopyproj.py
Renames 'input' to avoid a Pylint warning about re-defining a built-in.
> Python code: Rename 'input' -> 'inp'

- autotest/gcore/numpy_rw.py
- autotest/gdrivers/wcs.py
- autotest/ogr/ogr_pds.py
- autotest/ogr/ogr_pg.py
- autotest/ogr/ogr_sql_rfc28.py
- autotest/ogr/ogr_vfk.py
- autotest/utilities/test_gdalbuildvrt.py
- autotest/utilities/test_gdalwarp.py
- gdal/swig/python/samples/gdalfilter.py
Fixes a few new warnings introduced by fixing Pylint warnings. No differences are reported with `git diff -w --ignore-blank-lines`.
> Python code: Fix new PEP8 violations

- gdal/frmts/mbtiles/makefile.vc
Fixes an issue that prevented linking against an external zlib
* OS:
Win10
* Compiler:
VS2017
> $(ZLIB_FLAGS) had an extra parenthesis.

- CITATION
I don't think the definitive article "The" is part of the proper nouns of either the title or organization names, so I'm suggesting them to be removed. But it's fine to use "the" while wording (e.g.) the Open Source Geospatial Foundation.
> Doc: remove "The" from title and organization in CITATION

- gdal/swig/python/samples/ogr2ogr.py
Siliences Pylint warnings about `min` and `max` built-ins being redefined.
> Python code: Rename min, max -> mini, maxi.

- gdal/swig/python/samples/gdal_cp.py
Renames `buffer` to `buf` to silence Pylint warnings about `buffer` being re-defined. For consistency, other variables in this function starting with `buffer_` have been renamed accordingly.
> Python code: Rename buffer -> buf (and friends)

- gdal/alg/gdalwarpkernel_opencl.cpp
[fix use opencl memory leak](https://github.com/OSGeo/gdal/issues/610)
* OS:Windows10
* Compiler:Visual Studio2017
> fix use opencl memory leak

- autotest/gcore/tiff_write.py
- autotest/gdrivers/nitf.py
Removes Pylint warnings about the use of `exec()`.
> Python code: Use byte (b) prefix on Python 2 and 3

- gdal/ogr/ogrsf_frmts/oci/ogrocitablelayer.cpp
OGROCITableLayer::ReadTableDefinition - erroneous results for layer
dimensions and SDO_GTYPE information can be returned if multiple spatial
tables of the same name exist in the database (with different owners/schemas)
and the connecting user has select privileges over all of them.
In this situation the number of dimensions returned is either
1) the sum of the dimensions of all of the tables of the same name, or if
that produces no results
2) (if no schema qualification is specified) the dimensions of the first
table returned (which may or may not be the correct table)
A similar issue to No 2 above occurs when retrieving GTYPE information
To resolve this
a) when the tablename is not schema/owner qualified, use USER_SDO_* views
b) when the tablename is schema/owner qualified, ensure only …
> OGR/OCI: Ensure table Dims and GTYPE are retrieved for the correct table

- gdal/ogr/ogrsf_frmts/mysql/ogrmysqldatasource.cpp
Submits patch from vcpkg port of GDAL 2.3.0 to catch up with changes in libmysql from MySQL 8.0:
[MySQL 8.0 Reference Manual](https://dev.mysql.com/doc/refman/8.0/en/c-api-data-structures.html):
> The my_bool type was used before MySQL 8.0.
> As of MySQL 8.0, use the bool or int C type instead.
https://github.com/Microsoft/vcpkg/pull/3478
> MySQL: Replace my_bool with bool for >=8.0

- gdal/swig/python/scripts/gdal_merge.py
COMPONENT_NAME: gdal_merge.py
Applied NaN check for raster copy. This allows geotiffs with NaN for empty data to be merged correctly.
Implements an explicit check for nan data in gdal_merge.py.
* OS: ubuntu 16.04
* Compiler: icecc/gcc
> NaN empty data in gdal_merge.py

- gdal/swig/csharp/apps/GDALCreateCopy.cs
args[1] should be args[0], because “we can’t load SOURCE file, not DEST”
> Correct misspelling in info message

- autotest/osr/osr_basic.py
- autotest/osr/osr_epsg.py
- gdal/ogr/ogr_fromepsg.cpp
Appends ' (deprecated)' to the name of deprecated GEOCCSs like for PROJCSs and GEOGCSs.
See 39ce2084e05d494deafb93b977a7c4c6c0b36417 (for PROJCS), PR #575 (for GEOGCS) and https://lists.osgeo.org/pipermail/gdal-dev/2018-May/048495.html
See also https://github.com/qgis/QGIS/commit/e15f7cc06950b35a5d2db8054a7da7105397f564 about QGIS 3 now relying on "(deprecated)" string in crs name to properly update the field 'deprecated' of its crs database.
> importFromEPSG(): append ' (deprecated)' at end of deprecated GeoCCS

- gdal/fuzzers/build_seed_corpus.sh
- gdal/scripts/setdevenv.sh
Silences the last of the non-word splitting warnings from Shellcheck over `*.sh`. These two messages are still prevalent and can be cleaned up over time:
```
warning: Quote this to prevent word splitting. [SC2046]
note: Double quote to prevent globbing and word splitting. [SC2086]
```
> Shell scripts: Shellcheck fixes

- gdal/frmts/wcs/wcsdataset.cpp
Does not attempt to read band metadata if GetMetadata returns a nullptr.
#648
> WCS driver: consider GDALPamDataset::GetMetadata returning nullptr. (Fixes #648)

- gdal/ci/travis/trusty_32bit/script.sh
Runs Shellcheck over the shell scripts to keep the shell scripts in order. Skip `SC2046` and `SC2086` for now.
> Travis: Run Shellcheck (on 32-bit Trusty only)

- gdal/port/cpl_csv.cpp
Found with ASan and autofuzz.
Also, stop duplicating CPLStrlcat calls in the hardcoded find case.
> Fix buffer overflow in GDALDefaultCSVFilename with GDAL_NO_HARDCODED_FIND

- gdal/alg/gdal_crs.c
In practical examples it turns out that the quality of the approximation not always improves with increasing order of the polynomial as it should be the case. The reason is, that the linear equations are bad conditioned, because the absolute values of the GCP coordinates are big compared to the differences between different GCPs. Hence formulating the equations for the GCPs shifted by their mean value results in a better conditioned Problem. 
The modified procedure is implemented in 7167bb5b476ecac487b69c97f4fe41ccdafa58c0.
As a benchmark I implemented a solution which uses armadillo and solves the problem ||Ax - b|| ->min directly without using the normal equations ATAx=ATb, which is more stable.
To benchmark the results the mean quadratic deviation of the warped GCPs is computed. This …
> alg: gcp polynomial approximation

- gdal/makefile.vc
It was a mistake to delete the PDB prior to link/lib steps, since it's
needed by the compile steps that run earlier.
> NMAKE: Don't clobber PDB

- gdal/ogr/ogr_srs_esri.cpp
ogr_srs_esri_fuzzer - Heap Use-After-Free at strncasecmp
Input was: PROJCS(PARAMETER(latitude_of_center[[(Projection(Miller_Cylindrical))]],GEOGCS())
Found with autofuzz ASan
> morphToESRI: The projection node may be deleted, so make and use a copy of the name.

- gdal/port/cpl_vsil_gzip.cpp
Found with autofuzz using openfilegdbdatasource_fuzzer b/76119614
> VSIZipFilesystemHandler::Open: Fix leaks of poVirtualHandle

- autotest/gcore/gdal_stats.py
- gdal/doc/gdal_datamodel.dox
- gdal/gcore/gdal_priv.h
- gdal/gcore/gdalrasterband.cpp
Raster bands may contain pixels encoded as nodata. The proposed change adds a new STATISTICS_VALID_PERCENT metadata item to a raster band when raster band statistics are computed. Useful to get an estimate on the percentage of valid (not nodata) pixels, equivalent to e.g. percent cloud cover.
> add percentage of valid pixels to metadata when computing raster band statistics

- autotest/gdrivers/rmf.py
- gdal/frmts/rmf/rmfdataset.cpp
- gdal/frmts/rmf/rmfdataset.h
Latest versions of GIS Panorama support EPSG code as projection reference.
> RMF: Add optional projection import/export from EPSG code

- gdal/swig/java/GNUmakefile
When the new single JNI library introduced in #286, the Makefile was not fully updated to copy the new libraries from the .lib dir into the source directory for later copying during the install phase. This patch addresses that.
#286
First reported by a user via the Homebrew tap. OSGeo/homebrew-osgeo4mac#397
Tested on MacOS High Sierra.
> Fix JNI library installation

- gdal/configure
- gdal/configure.ac
Enable 12 bit JPEG-in-TIFF support when using internal tiff and jpeg librairies.
I have just changed the "if elif" statements order.
Fix #716
> Fix #716: 12 bit JPEG-in-TIFF support

- autotest/pyscripts/test_gdal_calc.py
- gdal/swig/python/scripts/gdal_calc.py
This adds the `--optfile` option to `gdal_calc.py`.
Other Python scripts use `gdal.GeneralCmdLineProcessor`, which parses the `optfile` flag. Gdal_calc, on the other hand, uses the Python optparse module. As in the C code, lines beginning with `#` are ignored.
A new test is included.
> Add support for --optfile to gdal_calc.py

- gdal/ogr/ogrsf_frmts/openfilegdb/filegdbtable.cpp
This fix reveals a separate leak.  I am letting the fuzzers find that
and file another bug on me.  The leak is not found testing with asan,
only with asan in fuzzing mode.
Found with autofuzz.  float-cast-overflow
> Catch a NaN in FileGDBDoubleDateToOGRDate to prevent undefined behavior.

- gdal/configure
- gdal/configure.ac
Because of this additionnal '$' the test will always fail and ECW5 will not be detected.
So, remove it.
> Remove additionnal '$' in front of '${CXX}' in configure to fix ECW5 detection

- gdal/apps/gdalasyncread.cpp
Here is a missing modification for https://github.com/OSGeo/gdal/commit/9bae05435e199592be48a2a6c8ef5f649fa5d113 
apps/gdalasyncread compilation fails with GDAL_RELEASE_NAME declaration not found error.
Fix compile error
> Apps: Fix  compile error of non default app

- Vagrantfile
- gdal/scripts/vagrant/gdal.sh
- gdal/scripts/vagrant/postgis.sh
- move Vagrantfile to project top
- change base image to Ubuntu trusty
- rsync sources to /home/vagrant
in order to keep host source clean
- Use ubuntu mirror site and dynamic selection.
Update Vagrant script to use Trusty as base image 
Because  Precise Pangolin  had been  end of life in April 2017.
> Vagrant: change base image to trusty

- gdal/ogr/ogrsf_frmts/avc/avc_e00write.cpp
avc: fix non existent member reference compile error
Fix compile error
> avc: fix non existent member reference

- autotest/cpp/gdal_unit_test.cpp
- autotest/cpp/test_data.h
- autotest/cpp/tut/tut_gdal.h
Support out of source compilation
tut test assumes run it in source.
This PR allows out of source execution.
> autotest: support out of source tut tests

- gdal/frmts/rmf/rmfdataset.cpp
* Main  buffer overflow fix 308e5fa
* Added tile table check (pointed by GCC ASAN) 6bd647d
* Added more header values check. Many of the values generated by oss-fuzz are random and can lead to buffer overflow next time. (74eea35 , e7f6b55, ecac52e)
> RMF: Fix issues #779 & #780

- autotest/gcore/tiff_write.py
- gdal/frmts/gtiff/geotiff.cpp
This PR saves the XMP xml data in the field `TIFFTAG_XMLPACKET` when  `GTiffDataset::SetMetadata` is called with the domain `xml:XMP`.
The method `GTiffDataset::OpenOffset` reads the field `TIFFTAG_XMLPACKET` and sets the value on the metadata domain `xml:XMP`. That gives the user access to the XMP xml string (and read/parse it on their own).
However, there is not way to write the XMP data in the field `TIFFTAG_XMLPACKET`. Third party software (like Exiv2) is not able then to read the XMP from a tiff file created with GDAL.
None
> GTiff: save XMP on field TIFFTAG_XMLPACKET

- Vagrantfile
- gdal/scripts/vagrant/gdal.sh
https://github.com/OSGeo/gdal/blob/9ec6971ca0dd41df454461387954def4f904cc60/Vagrantfile#L51
if the folder doesn't exist (eg. Virtualbox on OSX, no LXC/HyperV) then you get:
```
$ vagrant up
There are errors in the configuration of this machine. Please fix
the following errors and try again:
vm:
* The host path of the shared folder is missing: /tmp/.X11-unix/
```
The patch swaps it to use the override so it's LXC-specific rather than adding to the shared config object.
Certainly fixes it for my Virtualbox setup, but I don't have an LXC setup atm. @miurahr do you?
Just use the same approach as the [travis config](https://github.com/OSGeo/gdal/blob/master/gdal/ci/travis/trusty_clang/install.sh)
ccache was already installed, just wasn't being used. I can't see any reason _not_ to use it? …
> Vagrant tweaks

- gdal/frmts/rmf/rmfdataset.cpp
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=9660.
> RMF: Additional bit depth check for JPEG compressed datasets.

- gdal/gcore/gdalcolortable.cpp
> gdalcolortable.cpp: spelling: Paltte -> Palette [ci skip]

- gdal/scripts/vagrant/openjpeg.sh
In vagrant environment, install dependency openjpeg v2.3.0 as same version as travis trusy_clang environment
> vagrant: install dependency openjpeg v2.3.0

- autotest/pyscripts/test_gdal_edit.py
- gdal/swig/python/scripts/gdal_edit.dox
- gdal/swig/python/scripts/gdal_edit.py
With "-setstats" we can "fake" statistics which is very useful for tricking GIS programs to set the symbology as we want to. Can also eliminate outliers, etc...
> Introduce "setstats" option in gdal_edit.py

- autotest/pyscripts/test_gdal_calc.py
- gdal/swig/python/scripts/gdal_calc.py
This updates the `--optfile` option in gdal_calc.py, which was added in pull request #723. The current code doesn't match [the docs](https://gdal.org/gdal_utilities.html) because it doesn't treat quoted multi-word arguments as a single argument.
This pull request uses the python builtin library [shlex](https://docs.python.org/3.6/library/shlex.html) to parse optfile, and adds a appropriate test case.
> fix double-quote bug in gdal_calc --optfile support

- gdal/port/cpl_odbc.cpp
Correct an issue on Linux (and other UNIX systems) where wide-character string data is incorrectly retrieved from an ODBC database, due to the `wchar_t` wide-character type being greater than sixteen bits in length.
Fixes issue #839.
* Compiler: gcc 5.4.0
> ODBC: Fetch wide-char strings on UNIX (fixes #839)

- gdal/ogr/ogrsf_frmts/mssqlspatial/ogrmssqlspatialtablelayer.cpp
Allows date/time-valued feature attributes to be loaded into a Microsoft SQL Server database by modifying `OGRMSSQLSpatialTableLayer::AppendFieldValue()` to handle `OFTDateTime` fields specially,
- Formatting their value as an RFC 8601-compliant string and
- Adding an explicit `CAST` (to datetimeoffset, then datetime) to remove time zone information
so the field's value will be accepted by SQL Server.
Fixes issue #841.
* Compiler: g++ 5.4.0
> MSSQLSpatial: Accept date/time-valued feature attributes

- gdal/port/cpl_odbc.cpp
Modifies `CPLODBCSession::Failed()` so it retrieves the error message for a failed operation even when the driver reports the message has been truncated.
Fixes issue #850.
* Compiler: g++ 5.4.0
> ODBC: Get error message when truncated (fixes #850)

- autotest/ogr/ogr_mssqlspatial.py
- gdal/ogr/ogrsf_frmts/mssqlspatial/ogrmssqlspatialtablelayer.cpp
Allows features that specify a Z value to be created in a SQL Server database, by modifying `OGRMSSQLSpatialTableLayer` so it requests a suitable WKB variant when formatting geometry data to be passed to the database server.
It also extends the new test suite, `ogr_mssqlspatial.py`, to
- Identify the version of the database engine in use, to determine whether it supports features that have Z or M values (so tests that cannot pass can be skipped); and
- Test adding features of various types to the database (with code mostly duplicated from `ogr_pg.py`), including a 3D point type that happens to demonstrate the problem this PR corrects.
Fixes issue #852.
* Compiler: g++ …
> MSSQLSpatial: Support creating 3D features

- Vagrantfile
Install python-lxml package in Vagrant environment.
Some autotest staff depends on lxml.
> vagrant: install python-lxml for autotest dependency

- autotest/ogr/ogr_mssqlspatial.py
- gdal/ogr/ogrsf_frmts/mssqlspatial/ogr_mssqlspatial.h
- gdal/ogr/ogrsf_frmts/mssqlspatial/ogrmssqlspatialdatasource.cpp
- gdal/ogr/ogrsf_frmts/mssqlspatial/ogrmssqlspatialselectlayer.cpp
- gdal/ogr/ogrsf_frmts/mssqlspatial/ogrmssqlspatialtablelayer.cpp
Modify the MSSQLSpatial driver so that when creating features, it
- Uses only SRIDs considered valid by the database engine, with 0 (instead of -1) indicating an unknown spatial-reference system; and
- Preserves the SRID of the supplied feature's geometry, if its spatial-reference system is known, defaulting to the table's SRID otherwise.
Together these changes 
- Accommodate the fact tables in SQL Server generally do not have an associated SRID; and
- Allow features to be added to tables not registered in the `geometry_columns` table, without error and without modifying the interpretation of the original feature.
Fixes issue #860.
* Compiler: gcc 5.4.0
> MSSQLSpatial: Create features using a valid, sensible SRID

- autotest/utilities/test_ogr2ogr_lib.py
- gdal/apps/ogr2ogr_lib.cpp
- gdal/apps/ogr_utilities.dox
Extend `ogr2ogr`'s documentation to clarify the use of the "-select" and "-fieldmap" options. This would have saved me time this morning when I was trying to get `ogr2ogr` to omit a foreign-key column from a layer being loaded from a GeoPackage.
As I eventually discovered,
- [The "-select" option is quietly ignored when "-append" is specified.](https://github.com/OSGeo/gdal/blob/d1f5a1634136677bacd04fc6e07d2673b42d0f1c/gdal/apps/ogr2ogr_lib.cpp#L3394)
- "-fieldmap" can be used instead to omit source fields by specifying a value of -1 for their target index, [as shown in the last example on the page](https://www.gdal.org/ogr2ogr.html#ogr2ogr_example).
Since it's a little hard to tell from the diff, the specific text added to the page is:
"Note this setting is ignored when -append is used. …
> Doc: ogr2ogr: Clarify use of -select, -fieldmap

- autotest/ogr/ogr_nas.py
- gdal/frmts/postgisraster/postgisrasterdataset.cpp
- gdal/frmts/postgisraster/postgisrasterrasterband.cpp
- gdal/frmts/postgisraster/postgisrastertilerasterband.cpp
- gdal/ogr/ogrsf_frmts/nas/drv_nas.html
- gdal/ogr/ogrsf_frmts/nas/ogrnasdriver.cpp
- gdal/port/cpl_string.cpp
- gdal/port/cpl_string.h
- gdal/port/cplstring.cpp
add quoting to the postgisraster driver - untested, here to trigger tests…
https://issues.qgis.org/issues/19583
* OS:
* Compiler:
> add quoting to postgis raster driver

- gdal/doc/gdal_datamodel.dox
Corrected link to osr_tutorial from /ogr/osr_tutorial.html to /osr_tutorial.html
Fixes broken website link: https://www.gdal.org/gdal_datamodel.html (gdal_datamodel.dox) links to https://www.gdal.org/ogr/osr_tutorial.html however while the osr_tutorial.dox file lives under /ogr/, the website serves it at the root: https://www.gdal.org/osr_tutorial.html
* OS:
* Compiler:
> Update gdal_datamodel.dox with correct link to osr_tutorial

- gdal/swig/include/gdal_array.i
- gdal/swig/include/python/gdal_python.i
- gdal/swig/python/osgeo/gdal.py
- gdal/swig/python/osgeo/gdal_array.py
Current python imports are all under osgeo (ex. osgeo.gdal) but interface file defines it as
without osgeo.  Add `from osgeo` for imports and regenerate python files with SWIG 3.0.8.
It helps future deprecation of backward compatibility python files.
Autotest will run without (removing) compatibility python files where there are python2.7/dist-packages/gdal.py etc.
> Python: import paths in swig interface files and regenerate

- gdal/configure
- gdal/configure.ac
This unblocks building GDAL 2.3.1 with OpenJPEG on Python's manylinux1 platform based on CentOS 5, which has pkg-config 0.21.
Specifically, it resolves https://github.com/mapbox/rasterio/issues/1453 and an issue reported on the main Rasterio discussion group. I'm patching GDAL 2.3.1 and successfully building it with OpenJPEG in a manylinux1 container at https://travis-ci.com/sgillies/rasterio-wheels/jobs/145131192.
> Set minimum pkg-config version to 0.21

- gdal/swig/include/MajorObject.i
- gdal/swig/python/osgeo/gdal_array.py
Remove dependency for deprecated module in python binding.
replace `import gdal` with `import osgeo.gdal`
Same as #921  but here is a  missing modification 
#921 
> Python: add package to modules

- autotest/gcore/vsifile.py
- gdal/swig/include/cpl.i
- gdal/swig/include/perl/gdal_perl.i
- gdal/swig/python/extensions/gdal_wrap.cpp
- gdal/swig/python/osgeo/gdal.py
Add [`VSIFFlushL()`](https://www.gdal.org/cpl__vsi_8h.html#ac52ca4651926531e79e047709c9ea346) support to the SWIG Bindings.
eg. Python:
```python
gdal.VSIFFlushL(f)
```
Bindings regenerated with SWIG 3.0.8 on Linux
> Support for VSIFFlushL() in SWIG bindings

- gdal/frmts/formats_list.html
- gdal/frmts/raw/byndataset.cpp
- gdal/frmts/raw/byndataset.h
- gdal/frmts/raw/frmt_byn.html
Change driver long name at users request.
Apply suggested fixes to Identify() by taking scale into account.
Fix memory leak on GetProjectionRef ( return "" instead of return nullptr).
Reverse the formula for scaling of ordinates. According to the documentation if the header varaible scale is not 0 the boundaries and spacing should be multiplied by 1000 instead of divided like first coded.
```
--:-----------:------------------:------:----:---:---------------------------
18 Scale       Scale Boundaries   short  2    52  0: No scale applied to boundaries and spacing
1: Scale is applied (x1000)
```
> BYN - Change driver long name, fix Identify() and Scale issues

- autotest/gcore/vsifile.py
- gdal/swig/include/cpl.i
- gdal/swig/python/extensions/gdal_wrap.cpp
- gdal/swig/python/osgeo/gdal.py
Add support for [`VSIErrorReset()`](https://github.com/OSGeo/gdal/blob/d5f6bb89b0e0db0a06489419050d432e8f58ff47/gdal/port/cpl_vsi_error.cpp#L188-L197) into all the various SWIG bindings. Otherwise you can't clear [`VSIGetLastErrorNo()`](https://github.com/OSGeo/gdal/blob/d5f6bb89b0e0db0a06489419050d432e8f58ff47/gdal/port/cpl_vsi_error.cpp#L209-L222) which makes it hard to use.
This is a precursor to generally improving VSI error handling behaviour so VSI follows the `gdal.UseExceptions()` flag like the rest of GDAL. Currently there seems to be a mix of exceptions, error return codes, and ignoring...
[#7145: Python: VSI functions never throw exceptions](https://trac.osgeo.org/gdal/ticket/7145)
Bindings were rebuilt using v3.0.8 to match the existing code
> Add VSIErrorReset() into SWIG bindings

- gdal/frmts/mrsid/frmt_jp2mrsid.html
- gdal/frmts/mrsid/frmt_mrsid.html
- gdal/frmts/mrsid_lidar/frmt_mrsid_lidar.html
- gdal/frmts/mrsid_lidar/frmt_mrsid_lidar_view_point_cloud.html
Updates references to LizardTech in the MrSID format docs.  LizardTech corporate name is going away and the company is operating under the name of Extensis now.
None
This is an html-only change, no code involved.
* OS:
* Compiler:
> LizardTech corporate name change to Extensis

- autotest/gdrivers/gpkg.py
- gdal/ogr/ogrsf_frmts/gpkg/ogr_geopackage.h
- gdal/ogr/ogrsf_frmts/gpkg/ogrgeopackagedatasource.cpp
Properly delete gridded coverage raster layer from geopackages and remove also the corresponding records from gpkg_2d_gridded_coverage_ancillary and  gpkg_2d_gridded_tile_ancillary tables.
* OS:
* Compiler:
> Properly delete gridded coverage raster layer from geopackages

- gdal/frmts/pdf/GNUmakefile
GDAL 2.3.0+ requires C++11, but on macOS it requires to be using `-stdlib=libc++`
Probably no issue yet created.
* OS: macOS 10.12 Sierra
* Compiler: clang
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
> Fixed GNUMakefile to force libstdc++ for macOS

- gdal/gcore/gdaldataset.cpp
This PR fixes a small documentation bug by adding "BILINEAR", "CUBICSPLINE", and "LANCZOS" to the list of permitted resampling algorithm names for GDALBuildOverviews.
Replaces #968 @rouault
> Add bilinear, cubic spline, and lanczos to list of permitted algos

- autotest/pymod/gdaltest_python2.py
- autotest/pymod/gdaltest_python3.py
- gdal/frmts/wms/gdalhttp.cpp
- gdal/port/cpl_http.cpp
- gdal/port/cpl_http.h
- gdal/port/cpl_vsil_az.cpp
- gdal/port/cpl_vsil_curl.cpp
- gdal/port/cpl_vsil_s3.cpp
- gdal/port/cpl_vsil_webhdfs.cpp
This PR adds new environment variable `GDAL_HTTPS_PROXY` which is taken into account only for https URLS. If this variable is not set then `GDAL_HTTP_PROXY` affects both http and https URLs (this behavior is preserved). It is meant to overcome this issue: https://github.com/OSGeo/gdal/issues/878
> GDAL_HTTPS_PROXY

- autotest/cpp/test_cpl.cpp
- gdal/port/GNUmakefile
- gdal/port/cpl_auto_close.h
Sorry, my English is not good.
In the process of using GDAL, I often encounter places where resources need to be released.
In most cases, std::unique_ptr can be used to automatically release the resources used, but some special places can make it difficult to use or cause the code to be very messy.
For example, when using GDALBuildVRTOptions, I have to do some packaging to use std::unique_ptr, I feel very troublesome, so I simply wrote a template class CPLAutoClose, I think this can be shared.
* OS: Windows10 / Linux 4.16.3-1(ArchLinux)
* Compiler: MSVC 14.0 / gcc 7.3.1
> Add template class CPLAutoClose

- .gitignore
Add gitignore folders for IDEs such as Vagrant, CLion and VisualStudio Code
> gitignore: ignore IDEs and vagrant folders

- autotest/gdrivers/rmf.py
It read osge.gdal instead of obsolete module path.
> autotest: rmf: import gdal from osgeo

- .gitattributes
GNU Autoconf scripts are sensitive to CRLF. Specifically, `cpl_config.h.in` apparently must be LF  otherwise it is not updated correctly.
It is important for Windows/Linux hybrid environments, WSL or Docker.
Refines PR #984
> Force eol=lf for GNU Autoconf files

- autotest/alg/contour.py
- gdal/alg/contour.cpp
- gdal/alg/gdal_alg.h
- gdal/alg/marching_squares/level_generator.h
- gdal/apps/gdal_contour.cpp
- gdal/apps/gdal_utilities.dox
As proposed in mail thread "Gdal contour number of contour with -p", this PR adds amin and amax parameter for gdal_contour when command is used with option -p that generates polygons instead of lines.
N/A
N/A
> Add amin and amax parameter for gdal_contour to be used with option -p

- gdal/alg/contour.cpp
When you set big value for level parameter like 10000000000.0, the number is truncated to maximum int value. This PR corrects this issue.
N/A
N/A
> Correct big level value parsing bug

- gdal/frmts/jpeg/makefile.vc
pass $(JPEG12_FLAGS) when external jpeg library is used
https://github.com/OSGeo/gdal/issues/1014
- [ x ] All CI builds and checks have passed
Windows builds of gdal-2.3.0 with external jpeg library and jpeg12 enabled with internal jpeg12 source
* OS: Windows
* Compiler: msvc141
> JPEG: makefile.vc: always pass $(JPEG12_FLAGS) when external jpeg library is used (fixes #1014)

- gdal/frmts/gtiff/libtiff/tif_webp.c
This adds a check that the output buffer is the correct size when decoding a tiff with webp compression.
https://github.com/OSGeo/gdal/issues/1006
> checkout output buffer matches expected count

- autotest/gcore/misc.py
- gdal/gcore/gdaldllmain.cpp
- gdal/swig/include/cpl.i
- gdal/swig/include/gdalconst.i
- gdal/swig/include/python/gdal_python.i
- gdal/swig/include/python/python_exceptions.i
- gdal/swig/python/extensions/gdal_wrap.cpp
- gdal/swig/python/extensions/gdalconst_wrap.c
- gdal/swig/python/extensions/gnm_wrap.cpp
- gdal/swig/python/extensions/ogr_wrap.cpp
- gdal/swig/python/extensions/osr_wrap.cpp
- gdal/swig/python/osgeo/gdal.py
- gdal/swig/python/osgeo/gdalconst.py
1. Fixes an exit-time segfault when a custom error handler is installed and `CPL_DEBUG` is set.
2. Support a custom error handler via `gdal.SetErrorHandler()`. This also allows capturing logs for all  threads, which Push/Pop don't.
3. Fix some other error-handling bugs/omissions (eg. `CE_None` messages went nowhere)
4. Add a helper method, `gdal.ConfigurePythonLogging()` which:
* sets a default GDAL error handler
* passes all logged messages to Python's logging framework
* turns on `CPL_DEBUG` so the log framework can decide to filter debug messages
* maps GDAL's log levels to Python's
* maps `CPLE_*` error codes to names
https://gist.github.com/rcoup/ba0786ead611ed21b8e24ce364e4df1f has a test script:
* `test_errhandler.py --basic` is a simple testcase for the crash
* …
> Python logging improvements

- autotest/gcore/misc.py
- gdal/swig/include/python/gdal_python.i
- gdal/swig/python/osgeo/gdal.py
It's too verbose in many cases, with lots of noise from vsicurl and warping in particular. While you can filter it in Python, it requires additional configuration work.
Future idea is probably to increase some useful messages from CE_Debug up to CE_None, or add a CE_Trace level below CE_Debug.
Change the default value for the `enable_debug` parameter to `gdal.ConfigurePythonLogging()`
If the user has previously set `CPL_DEBUG=ON` in their environment, it'll keep propagating debug messages up.
#1017
> ConfigurePythonLogging: Don't turn cpl_debug on by default

- autotest/gdrivers/rda.py
- gdal/frmts/rda/frmt_rda.html
- gdal/frmts/rda/rdadataset.cpp
RDA tools have introduced an RDA Image Reference JSON spec that is different than the connection string previously. To allow users to seamlessly use the new image reference format in the GDAL driver GDALRDADataset::Identify checks for the new keywords and GDALRDADataset::Open uses either ParseImageReferenceString or ParseConnectionString (for backwards compatibility).
> enable support for DG RDA Image Reference string

- autotest/ogr/ogr_mssqlspatial.py
- gdal/ogr/ogrsf_frmts/mssqlspatial/ogrmssqlspatialtablelayer.cpp
Method OGRMSSQLSpatialTableLayer::ICreateFeature (in source file ogrmssqlspatialtablelayer.cpp) has been modified such that the INSERT statement now includes the OUTPUT clause, requesting the newly assigned FID.
It only modifies the INSERT statement when the FID is an IDENTITY column, and following a successful execution, fetches the result and calls the SetFID method on the passed-in feature.
> MSSQLSpatial: driver does not assign new ID following an INSERT (fixes ticket #1052)

- autotest/gdrivers/loslas.py
Fix loslas test failure not to found a test data.
Downloaded file NADCON.zip has nadcon.jar for grids data container.
try to unzip NADCON.zip and nadcon.jar to extract test data.
N.A.
* OS:
* Compiler:
> autotest: gdriver_loslas: see inside jar file for downloaded data

- autotest/cpp/test_marching_squares_contour.cpp
This should fix the problem seen by valgrind in #960.
A for loop was accessing the memory one byte too far.
* OS:
* Compiler:
> gdal_contours tests: Fix an off-by-one when accessing ring points (fixes #960)

- autotest/ogr/ogr_gmlas.py
When calling ogr_gmlas.py test and its test fails, python2 warns UnicodeEncodeError instead of showing
test result.
A patch fix print of debug message.
> autotest: fix UnicodeEncodeError when test fails in python2

- gdal/ogr/ogrsf_frmts/oci/drv_oci.html
Fixes gabled text in the OCI driver documentation:
The default value is â€œNO"
> Fix wrong doublequote charactes in OCI manual

- gdal/ci/travis/ubuntu_1804/before_install.sh
Minor tweaks for the ubuntu_1804 CI environment, saving some bandwidth/time.
* The `docker` package in ubuntu isn't actually docker. Docker is preinstalled in travis.
* It was pulling one version of the docker containers for mariadb/mysql,
and then implicitly running ':latest' (which implicitly pulled again).
I removed the pull command since it was unnecessary.
* Consolidate some apt-get installs to save a couple seconds
nothing relevant
> CI tweaks (ubuntu_1804 environment)

- gdal/ogr/ogrsf_frmts/csv/drv_csv.html
Adds documentation to CSV driver, describing how to 
use ogr2ogr to create CSV with GeoJSON encoded geometry.
https://github.com/OSGeo/gdal/issues/1076
N/A
N/A
> CSV Documentation: describe producing CSV with GeoJSON formatted geometries

- autotest/cpp/test_ogr.cpp
- autotest/ogr/data/gmlas/gmlas_test1_generated.xml
- autotest/ogr/ogr_mvt.py
- gdal/ogr/ogrsf_frmts/sqlite/ogr_sqlite.h
- gdal/ogr/ogrsf_frmts/sqlite/ogrsqlitelayer.cpp
- gdal/ogr/ogrsf_frmts/sqlite/ogrsqlitevirtualogr.cpp
- gdal/ogr/ogrutils.cpp
Modifies [the `OGRGetXMLDateTime()` function](https://github.com/OSGeo/gdal/blob/cdbba83cc3eea4ef48b3205865432f40fe0bbc52/gdal/ogr/ogrutils.cpp#L1378) to interpret a date/time field's `TZFlag` member in accordance with [the documentation](https://gdal.org/classOGRFeature.html#a4ca0f1bca72c88fe9f881871cdc401a5). Specifically, when formatting a date/time field, the function now
- Appends no timestamp qualifier for an unknown (`TZFlag` = 0) or local (`TZFlag` = 1) time zone;
- Appends "Z" for the GMT time zone (TZFlag = 100); and
- Appends a computed time-zone offset for all other `TZFlag` values.
I've reviewed every use of this function in the library and can see no areas where these changes would cause issues. No driver appears to modify either the field members before or the returned …
> OGRGetXMLDateTime(): Interpret TZFlag correctly (fixes #996)

- gdal/HOWTO-RELEASE
Twine is the state of the art. More efficient and much more secure. https://pypi.org/project/twine/
> Upload python sdist with twine

- gdal/port/cpl_error.cpp
- gdal/port/cpl_multiproc.h
Fixes [crashes in logging where error handlers receive the wrong context data](https://github.com/OSGeo/gdal/issues/1098).
Solves this by:
1. centralising error propagation (thread local handler stack + global) via a new local `ApplyHandler()` function.
2. pushing the active handler's user data onto a threadlocal variable (`CTLS_ERRORHANDLERACTIVEDATA`). 
3. it is represented there as a `void**` (because "no active userData" != "active userData that is 0")
4. make `CPLGetErrorHandlerUserData()` look at the threadlocal variable first.
I've kept the existing behaviour/semantics, including the differences between `CPLDebug(...)` & `CPLError(CE_Debug, ...)`.
The testcase from #1098 passes ok ("_ERROR:gdal:AppDefined: Cannot open TIFF file due to missing codec._"), as do the existing tests in …
> CPL: Propagate error handler user data correctly (fixes #1098)

- gdal/frmts/gtiff/libtiff/tif_webp.c
When testing compression with tiff and webp we discovered a memory leak with the allocation of a the compressed buffer being called more than once before being released in `TWebPCleanup`. 
The fix was to check whether the buffer was assigned and freed in `preencode`.
> fix memory leak with tiff webp encoding

- gdal/ogr/ogrsf_frmts/mssqlspatial/drv_mssqlspatial.html
- gdal/ogr/ogrsf_frmts/mssqlspatial/ogr_mssqlspatial.h
- gdal/ogr/ogrsf_frmts/mssqlspatial/ogrmssqlspatialdatasource.cpp
- gdal/ogr/ogrsf_frmts/mssqlspatial/ogrmssqlspatialtablelayer.cpp
When set to YES, MSSQLSPATIAL will always set the OGR_FID column using an OUTPUT clause when inserting features. This way, views (which will never have IDENTITY columns) or sequence generated ID columns are also supported.
Related to #1502 and #1053 in that it was still impossible to insert features in views (which are insertable/updatable)
> MSSQLSPATIAL: Adding configuration option MSSQLSPATIAL_ALWAYS_OUTPUT_FID

- autotest/gdrivers/eedai.py
- autotest/ogr/ogr_eeda.py
- gdal/frmts/eeda/drv_eeda.html
- gdal/frmts/eeda/eeda.h
- gdal/frmts/eeda/eedacommon.cpp
- gdal/frmts/eeda/eedadataset.cpp
- gdal/frmts/eeda/eedaidataset.cpp
- gdal/frmts/eeda/frmt_eedai.html
Replace:
- usage of `path` with `name`
- calls to "/v1/assets/**" with "/v1/projects/\*/assets/\*\*"
- calls to "/v1/assets:listImages" with "/v1/projects/\*/assets/\*\*:listImages"
- calls to "/v1/assets:getPixels" with "/v1/projects/\*/assets/\*\*:getPixels"
> EEDA: Replace usage of deprecated paths/field names

- gdal/port/cpl_http.cpp
Enable the cookie engine in gdal /vsicurl. In particular, allows users to specific the following environment variables, which permit command line interaction with NASA imagery on remote servers using single sign on authentication (https://urs.earthdata.nasa.gov).
GDAL_HTTP_COOKIEJAR
GDAL_HTTP_COOKIEFILE
**see example and output in comment below**
#1000
* OS: Ubuntu 18.04.1 LTS
* Compiler: gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
> cURL: added curl cookiefile and cookiejar variables (fixes #1000)

- autotest/ogr/data/all_geoms.mif.golden.csv
- gdal/ogr/ogr_core.h
- gdal/ogr/ogr_feature_style.html
- gdal/ogr/ogr_featurestyle.h
- gdal/ogr/ogrfeaturestyle.cpp
- gdal/ogr/ogrsf_frmts/mitab/mitab.h
- gdal/ogr/ogrsf_frmts/mitab/mitab_feature.cpp
This PR expose font family as additional style ID.
MapInfo Interchange Format (mif/mid) provides symbol style based on font, but now it is ignored when exporting style from TABFontPoint::GetStyleString() [(see: Appendix J: MapInfo Data Interchange Format, Symbol Clause – TrueType Font Syntax section)](https://web.archive.org/web/20060909054240/http://resource.mapinfo.com/static/files/document/1074660800077/interchange_file.pdf)
Previously, a font field was provided by OGRStyleSymbol, but it was deleted in b98fd4b51bda2f5de0b8c5876b704e5a2fa3ca95.
If it could be brought back, in my opinion, it would be a good place to store the symbol font.
> MITAB: Expose font family to feature style symbol ID

- autotest/gdrivers/wms.py
- autotest/ogr/ogr_gft.py
Output from pytest --durations=10:
```
137.55s call     gdrivers/wms.py::test_wms_16
127.26s call     gcore/vsis3.py::test_vsis3_read_credentials_ec2_expiration
27.98s call     ogr/ogr_gft.py::test_ogr_gft_ogr2ogr_spatial
17.39s call     ogr/ogr_carto.py::test_ogr_carto_test_ogrsf
16.74s call     ogr/ogr_gft.py::test_ogr_gft_write
16.21s call     gdrivers/mrf.py::test_mrf_lerc_with_huffman
14.00s call     gdrivers/gdalhttp.py::test_http_2
12.88s call     ogr/ogr_gft.py::test_ogr_gft_ogr2ogr_non_spatial
12.30s call     gdrivers/wms.py::test_wms_11
12.19s call     gdrivers/mbtiles.py::test_mbtiles_3
```
This skips the top three (so should save ~ 5 minutes on test runs!)
They can be run manually by adding `GDAL_RUN_SLOW_TESTS=YES` in the environment, same as a bunch of other tests.
n/a
those …
> Tests: Skip the 3 slowest tests by default

- gdal/swig/python/scripts/gdal2tiles.py
When leaflet tile cache viewer is generated with gdal2tiles, layers disappear at zoom levels greater than 18 due to the layers not explicitly defining a higher zoom level. This change defines maxZoom and minZoom per basemap layer and local tile cache layer. The max/min layer zoom levels are the same as the max/min zoom levels defined on the root map control.
Fixes "gdal2tiles does not allow max zoom >= 19 with leaflet" https://github.com/OSGeo/gdal/issues/1074.
* OS:
* Compiler:
> gdal2tiles: Give layers same min/max zoom levels as generated tile cache (fixes #1074)

- Vagrantfile
- gdal/scripts/vagrant/gdal-mingw.sh
- gdal/scripts/vagrant/gdal.sh
- gdal/scripts/vagrant/postgis.sh
resolve all the problem related to ubuntu PPA
Fix #1058 by removing root cause for dependency 
breakage of packages.
Ubuntugis-unstable PPA has a geos 3.5.0 package for trusty.
There are dependency chain for libgeos related to rasterlite. librasterlite depends on opensceangraph, which depends on gdal1h, that depends on libgeos 3.4.2.
Ubuntu Trusty has a geos 3.4.2 in standard release.
Similar things are happen on proj4 package. Multiple proj4 library versions causes crash, that is reported in #1058 
https://launchpad.net/~ubuntugis/+archive/ubuntu/ubuntugis-unstable
This patch removes ubuntugis-unstable PPA from apt repository, in order not to install geos 3.5.0.
#1058 
Vagrant
> Vagrant: fix geos mingw package dependency problem

- autotest/requirements.txt
We use node.iter_markers which was added in 3.6.0
Fixes #1165
> Require pytest 3.6.0+

- gdal/ci/travis/osx/before_install.sh
- gdal/ci/travis/osx/install.sh
- gdal/ci/travis/osx/script.sh
- gdal/frmts/eeda/eedacommon.cpp
- gdal/frmts/eeda/eedadataset.cpp
- gdal/frmts/hdf5/bagdataset.cpp
- gdal/frmts/mbtiles/mbtilesdataset.cpp
- gdal/frmts/plmosaic/plmosaicdataset.cpp
- gdal/frmts/rda/rdadataset.cpp
- gdal/ogr/ogrfeature.cpp
- gdal/ogr/ogrsf_frmts/amigocloud/ogramigoclouddatasource.cpp
- gdal/ogr/ogrsf_frmts/amigocloud/ogramigocloudlayer.cpp
- gdal/ogr/ogrsf_frmts/amigocloud/ogramigocloudtablelayer.cpp
- gdal/ogr/ogrsf_frmts/carto/ogrcartolayer.cpp
- gdal/ogr/ogrsf_frmts/cloudant/ogrcloudantdatasource.cpp
- gdal/ogr/ogrsf_frmts/cloudant/ogrcloudanttablelayer.cpp
- gdal/ogr/ogrsf_frmts/couchdb/ogrcouchdbdatasource.cpp
- gdal/ogr/ogrsf_frmts/couchdb/ogrcouchdblayer.cpp
- gdal/ogr/ogrsf_frmts/couchdb/ogrcouchdbtablelayer.cpp
- gdal/ogr/ogrsf_frmts/elastic/ogrelasticlayer.cpp
- gdal/ogr/ogrsf_frmts/geojson/ogresrijsonreader.cpp
- gdal/ogr/ogrsf_frmts/geojson/ogrgeojsonreader.cpp
- gdal/ogr/ogrsf_frmts/geojson/ogrgeojsonutils.cpp
- gdal/ogr/ogrsf_frmts/geojson/ogrgeojsonwriter.cpp
- gdal/ogr/ogrsf_frmts/geojson/ogrtopojsonreader.cpp
- gdal/ogr/ogrsf_frmts/plscenes/ogrplscenesdatav1dataset.cpp
- gdal/ogr/ogrsf_frmts/plscenes/ogrplscenesdatav1layer.cpp
- gdal/ogr/ogrsf_frmts/sqlite/ogrsqlitevirtualogr.cpp
- gdal/port/cpl_json.cpp
Resolve 64-bit build failures on OSX 10.12.6., following .travis.yml and using gdal/ci/travis/osx/*.sh. Updates assignment of the return value from json_object_array_lenght() to type 'auto' instead of 'int'. Some issues resolved by applying static_cast<int>().
None.
OSX 10.12.6, xcode, homebrew
> OSX: fix build failures due to json-c

- gdal/swig/python/scripts/gdal_fillnodata.py
`gdal_fillnodata.py` will preserve color interpretation and color table (if set) from the source band.
> gdal_fillnodata.py: preserve color interpretation and color table

- gdal/port/cpl_http.cpp
- gdal/port/cpl_vsil_curl.cpp
- gdal/port/cpl_vsil_curl_class.h
This fixes an issue where a keep-alive'd connection via a proxy is closed by the server (`Connection: close`), and subsequent range requests fail because the proxy's headers are treated as the response headers.
Slightly sanitised log:
```
...
VSICURL: Downloading 141768-152378 (https://mybucket.s3.amazonaws.com/my.tif)...
* Couldn't find host mybucket.s3.amazonaws.com in the .netrc file; using defaults
* Found bundle for host mybucket.s3.amazonaws.com: 0x7feda3f05830 [can pipeline]
* Re-using existing connection! (#1) with proxy localhost
* Connected to localhost (::1) port 8888 (#1)
> GET /my.tif HTTP/1.1
Host: mybucket.s3.amazonaws.com
Accept: */*
Range: bytes=141768-152378
x-amz-date: 20190117T135937Z
x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 …
```
> vsicurl: Ignore CONNECT response headers from proxy

- appveyor.yml
- autotest/gdrivers/kea.py
- gdal/frmts/hdf5/hdf5dataset.cpp
- gdal/frmts/hdf5/hdf5vfl.h
- gdal/frmts/kea/frmt_kea.html
- gdal/frmts/kea/keadataset.cpp
- gdal/frmts/kea/keadataset.h
- gdal/frmts/kea/keadriver.cpp
- gdal/frmts/kea/makefile.vc
This PR adapts the /vsi support added (using a Virtual File Layer) to the HDF5 driver in 2.4.0 for the KEA driver.
Since the KEA driver now calls directly into HDF5 (rather than via `kealib`) to set up the open properties the HDF5 C++ library must be linked in. This was already happening under Unix, but under Windows `hdf_cpp.lib` must be added to `KEA_LIB`. I'm not sure if there is a better way.
Here are some KEA files already online for testing:
https://bitbucket.org/chchrsc/kealib/downloads/classes.kea
https://bitbucket.org/chchrsc/kealib/downloads/utm.kea
cc: @danclewley @petebunting @neilflood
> KEA: add support for /vsi file systems

- gdal/ogr/ogrsf_frmts/elastic/ogrelasticdatasource.cpp
Fixes an issue when an Elasticsearch index have at least one mapping. If there is at least one mapping, currently it will not be possible to use these indices with the GDAL Elasticsearch driver as the layer name is compared to index name and these differ when there is at least one mapping. This error was introduced in GDAL 2.4.0 and from what I can see, commit fe55a01bed92b4fe751c5d5f9ea7a5bd1addc95d.
None, as far as I know.
Happens in every environment I've tested (Linux, Windows).
> Elasticsearch: Fixed index comparison bug when a index have atleast one mapping

- gdal/alg/gdalrasterize.cpp
When multiple geometry needs to be rasterized, if you use `GdalRasterizeGeometries` you must create a dataset (although it can be mem) and not like `GdalRasterizeLayersBuf` Write a piece of memory directly like that buffer.
But `GdalRasterizeLayersBuf` couldn't filter the geometry in layer, only the parts needed to raster, so I wrote this function.
> Add Gdalrasterizegeometries Example(use MEM Dataset) to Doxydocumentation.

- gdal/gnm/gnm_frmts/gnmregisterall.cpp
GDAL initialisation with `CPL_DEBUG=ON` looks like:
```
GNM: GNMRegisterAllInternal
GNM: RegisterGNMFile
GNM: RegisterGNMdatabase
... useful stuff relating to what you're doing ...
```
No other drivers or infrastructure log any messages on _registering_, only when they're actually used (eg. HTTP printing libcurl/libssl versions).
Strip these debug messages out.
> logging: Remove debug messages from GNM registration

- gdal/ogr/ogrsf_frmts/gpkg/ogrgeopackagedatasource.cpp
GPKG: Negative values other than -1 are valid for column `srs_id` in tables `gpkg_contents` and `gpkg_spatial_ref_sys`. There is no explicit mention that all negative values are invalid.
This is issue was discovered while working with a geopackage where one of the raster datasets in `gpkg_contents` has an `srs_id` with a value of -3. The `gpkg_spatial_ref_sys` table does contain a valid entry for -3.
* OS:
* Compiler:
> Geopackage srs_id fix for negative values

- gdal/MIGRATION_GUIDE.TXT
- gdal/configure
- gdal/configure.ac
- gdal/frmts/mrf/GNUmakefile
Rename ./configure arguments --without-bsb, --without-grib and --without-mrf to --disable-driver-bsb --disable-driver-grib and --disable-driver-mrf to be inline with #1250
> make bsb, grib and mrf follow disabling standard of #1250

- gdal/port/GNUmakefile
- gdal/port/cpl_vsi.h
- gdal/port/cpl_vsil_plugin.cpp
- gdal/port/cpl_vsil_plugin.h
- gdal/port/makefile.vc
This PR allows to dynamically register a VSI handler at runtime by passing a select number of callback functions. Our principle use-case is to be able to bypass the vsicurl handler when accessing remote datasets, to provide observability, custom error handling, retrying, logging, fine-grained concurrency control, fine-grained caching, and better stability under heavily multi-threaded loads.
> VSI plugins

- gdal/port/cpl_string.cpp
Avoid assertions in CPLGetValueType by adding `static_cast<unsigned char>` to all uses of isspace/isdigit.
Fixes https://github.com/OSGeo/gdal/issues/1322
Reproduced/tested on:
* Windows 10 x64 (msvc)
Also ran tests on:
* Ubuntu 18.04.02 x64 (g++)
> CPL: Fix assertion in CPLGetValueType when working with non-ASCII strings (fixes #1322)

- autotest/pyscripts/test_gdal_retile.py
- gdal/swig/python/scripts/gdal_retile.py
Issue #1314 - Modify `gdal_retile.py` to copy the NoData value from the input dataset to the output dataset.
> gdal_retile.py: respect nodata values on inputs

- autotest/gcore/rasterio.py
- autotest/gdrivers/kea.py
- gdal/frmts/arg/argdataset.cpp
- gdal/frmts/hfa/hfadataset.cpp
- gdal/frmts/mbtiles/mbtilesdataset.cpp
- gdal/frmts/pcidsk/pcidskdataset2.cpp
- gdal/gcore/gdaldataset.cpp
- gdal/gcore/gdalrasterband.cpp
When doing a RasterIO(GF_Write, ...) operation, check that the dataset/rasterband
access mode is GA_Update.
Fix a few drivers where access mode was not set correctly.
> RasterBand/Dataset::RasterIO(): enforce access mode on write

- gdal/ogr/ogrsf_frmts/pgdump/ogrpgdumpdatasource.cpp
This fixes the generated SQL for the pgdump driver.
Previously the driver emitted invalid SQL with UNLOGGED=ON.
According to documentation, Postgres has never recognized "CREATE TABLE UNLOGGED" as valid syntax.
None found.
> pgdump: Fix emitted SQL when UNLOGGED=ON

- Vagrantfile
Fix Vagrant configuration for LXC driver
LXC 2.1 introduce new configuration parameter keys and
LXC 3.0 removes legacy keys.
Here replace legacy key with new one.
Vagrant development environment
Vagrant driver: LXC
> Vagrant: new config key for LXC driver

- autotest/ogr/ogr_elasticsearch.py
- gdal/ogr/ogrsf_frmts/elastic/ogrelasticdatasource.cpp
- gdal/ogr/ogrsf_frmts/elastic/ogrelasticlayer.cpp
The current construction of the URL for Elasticsearch `_mapping` is incorrect and causes failures when converting data to Elasticsearch with a defined mapping file. In all versions of Elasticsearch, the PUT  _mapping URL should be constructed as `/{index_name}/_mapping/{mapping_type}`. This PR corrects the URL path for PUT mapping. See
https://www.elastic.co/guide/en/elasticsearch/reference/5.6/indices-put-mapping.html for more info.
n/a
> Elasticsearch: Fix _mapping url

- gdal/ogr/ogrsf_frmts/mssqlspatial/ogr_mssqlspatial.h
- gdal/ogr/ogrsf_frmts/mssqlspatial/ogrmssqlspatialdatasource.cpp
- gdal/ogr/ogrsf_frmts/mssqlspatial/ogrmssqlspatialtablelayer.cpp
- Adds methods and a MSSQL version type to the OGRMSSQLSpatial data source class to get and parse the database version
- Adds overrides for the GetExtent methods of the OGRLayer implementation for MSSQLSpatial which are more performant for large datasets
None that I know off
> MSSQLSpatial: Adding improved extent queries for MSSQLServer driver

- gdal/swig/python/scripts/gdal_calc.py
the orginal docs:
` Calc(calc="A*(A>0)", A="input.tif", A_Band=2, outfile="result.tif", NoDataValue=0)`
`A_Band` is wrong, `B` should be lower case.
> fix `gdal_calc.py Calc` function  docs error

- gdal/alg/gdalrasterize.cpp
Fixes a similar issue with gvBurnPoint than was already fixed in gvBurnScanline
#1338  573a97994e31c8f38580c70a9bee790c23d028e5
> rasterize: fix crash when working buffer is larger than 2GB (fix for gvBurnPoint) (fixes  #1338)

- gdal/swig/python/samples/validate_cloud_optimized_geotiff.py
closes #1403 
Change the size requirement for internal tiling and internal overview to be only `greater than` 512px 
#1403
> check if file is only greater than 512px

- gdal/configure
- gdal/configure.ac
- gdal/frmts/dted/frmt_dted.html
- Fix issue#1412
Signed-off-by: Bruno Friedmann <bruno@ioda-net.ch>
pg_config was never really meant to be used for programs using libpq. But for lack of better alternatives everyone started using it in the past. There is a better alternative now pkg-config libpq.
issue #1412
* OS: openSUSE Tumbleweed
* Compiler: gcc8
* PostgreSQL : version 11
> Switch usage of pg_config to pkg-config for PostgreSQL detection

- autotest/ogr/ogr_carto.py
- gdal/apps/ogr2ogr_lib.cpp
- gdal/ogr/ogrsf_frmts/carto/drv_carto.html
- gdal/ogr/ogrsf_frmts/carto/ogr_carto.h
- gdal/ogr/ogrsf_frmts/carto/ogrcartodatasource.cpp
- gdal/ogr/ogrsf_frmts/carto/ogrcartotablelayer.cpp
Changes how a table is overwritten in CARTO. Instead of 2 calls, first the DROP and then the CREATE TABLE, it defers the table drop and sends them both as a single transaction:
- `BEGIN; DROP TABLE "x"; CREATE TABLE "x" ...; COMMIT;`
It does this to avoid an issue in the CARTO platform where a map depending on a table could be dropped if it was "checked" during the update, that is between the drop and the creation of the table. It also enables future changes on how this dependency is handled internally.
Closes https://github.com/OSGeo/gdal/issues/1305.
> CARTO: Overwrite tables in single transactions

- gdal/ogr/ogrsf_frmts/carto/drv_carto.html
- gdal/ogr/ogrsf_frmts/carto/ogrcartodatasource.cpp
Improves the documentation around the CARTODBFY option. This is changed with CSV imports in mind since those don't set neither the output SRS or geometry type automatically.
Closes https://github.com/OSGeo/gdal/issues/1399
> CARTO: Improve documentation and warnings around CARTODBFY

- autotest/pyscripts/test_gdal_edit.py
- gdal/swig/python/scripts/gdal_edit.dox
- gdal/swig/python/scripts/gdal_edit.py
Previously, only a single scale and/or offset value could be set by gdal_edit.py, which was applied to all layers. Now, one can also specify one value per band, like this:
`gdal_edit.py -scale 1 10 100 -offset 0 -10 10 ThreeLayerFile.tif`
This functionality is useful for files with different scaling factors, which can, for example, be produced with `gdal_translate -scale_1 -scale_2 ...`
> Allow setting band-specific scale and offset values

- gdal/frmts/gtiff/libgeotiff/geo_normalize.c
- gdal/frmts/gtiff/libgeotiff/geo_normalize.h
- gdal/ogr/ogrct.cpp
- gdal/ogr/ogrsf_frmts/mongodbv3/ogrmongodbv3driver.cpp
The lintian QA tool reported a spelling error for GDAL 2.5.0-beta1:
* instanciate -> instantiate
> Fix spelling errors.

- autotest/utilities/test_gdal_translate.py
- autotest/utilities/test_gdal_translate_lib.py
- gdal/apps/gdal_translate_bin.cpp
- gdal/apps/gdal_translate_lib.cpp
- gdal/apps/gdal_utilities.dox
- gdal/swig/include/python/gdal_python.i
- gdal/swig/python/osgeo/gdal.py
If "-nogcp" is specified, gdal_translate will ignore the GCPs in the source
dataset. By default, nogcp is false and the GCPs in the source dataset are
copied to the destination dataset.
Add -nogcp option to gdal_translate. 
If "-nogcp" is specified, gdal_translate will ignore the GCPs in the source
dataset. By default, nogcp is false and the GCPs in the source dataset are
copied to the destination dataset.
* OS:
* Compiler:
> Add "-nogcp" option to gdal_translate binary and the python binding.

- gdal/frmts/pdf/gdal_pdf.h
- gdal/frmts/pdf/pdfdataset.cpp
Apply selection to all layers with a given name,
rather than only one of those layers chosen at random.
> Fix selection of Poppler PDF layers with duplicate names

- autotest/gdrivers/tiledb_write.py
- gdal/frmts/tiledb/tiledbdataset.cpp
Enables support for multiple attribute names when co-registering datasets with TileDB datasets.
https://github.com/OSGeo/gdal/pull/1483
> TileDB: support multiple attribute names in dataset metadata (fixes #1493)

- autotest/gdrivers/tiledb_write.py
- gdal/frmts/tiledb/tiledbdataset.cpp
When loading a TileDB array the band metadata wasn't being populated in the initial `XMLInit` call. This is because the TileDB driver needs to read the metadata first to determine the number of bands before creating the band objects. 
This PR adds a reload function that caches the XML and reloads the file after the bands have been created.
None
* OS:
* Compiler:
> TileDB: Added support for raster band metadata

- CITATION
- gdal/HOWTO-RELEASE
Fixes #1499 
Also updating CITATION to use HTTPS links, as are now supported.
HOWTO-RELEASE was updated as discussed in #1499, by splitting step 2 into 2.1 and 2.2.
> Update CITATION and HOWTO-RELEASE

- autotest/gdrivers/eedai.py
- autotest/ogr/ogr_eeda.py
- gdal/frmts/eeda/eedacommon.cpp
- gdal/frmts/eeda/eedadataset.cpp
- gdal/frmts/eeda/eedaidataset.cpp
- gdal/frmts/eeda/frmt_eedai.html
- `EarthEngineAsset.path` is no longer returned.
- `PixelDataType.(INTEGER|FLOAT32|FLOAT64)` are renamed to
`PixelDataType.(INT|FLOAT|DOUBLE)`.
- `EarthEngineAsset.time` is no longer returned (replaced by
`EarthEngineAsset.(start|end)_time`.
- `ListImagesResponse.assets` is renamed to
`ListImagesResponse.images`.
> EEDA: Bump to v1alpha.

- gdal/swig/python/scripts/gdal_calc.py
Fixes NaN-streaking in the output file when gdal_calc.py --allBands is used with tiled images.
gdal_calc --calc="A-B" --outfile=diff.tif -A A.tif -B B.tif --allBands=A --B_band=3
(where A.tif and B.tif are TILED GeoTIFF's with multiple bands).
This issue is because gdalc_calc.py gets the block size to work on from GetRasterBand().GetBlockSize(), which on a tiled image is typically something like 256x256. For the final block in the x-range, the block and buffer size is changed to fit the image. But these values aren't reverted back to their original values before looping to the next band. So when called with –allBands and TILED=YES, the block size and buffer is reduced for subsequent bands. If TILED=NO, the x-buffer will always be the image width (as far as I can tell), so the bug won't …
> gdal_calc.py: fixes streaking with --allBands option

- gdal/frmts/gtiff/geotiff.cpp
- gdal/frmts/gtiff/tifvsi.cpp
- gdal/frmts/gtiff/tifvsi.h
Or multiple level external overview.
This was a long standing problem. The issue was that each overview level (this
also applies to mask) within a same TIFF file shared the same TIFF* handle.
When switching between overviews, the handle had to be reset to point to a
new TIFF IFD, and reloading of the StripOffset/StripByteCount/TileOffset/TileByteCount
was done. For really big files, those can be several ten to hundred of MB large.
Now, each overview (mask) owns its own TIFF handle, sharing the underlying file
pointer though. Some care is needed in the tifvsi layer regarding some write
optimizations, as well when creating overviews, we must take care of forcing
a reload of the main TIFF handle so that the in-memory TIFF structure points
correctly to the next IFD.
Test case:
```
from osgeo …
```
> GTiff: improve performance of internal overview creation (fixes #1442)

- gdal/ogr/ogrsf_frmts/amigocloud/drv_amigocloud.html
- gdal/ogr/ogrsf_frmts/amigocloud/ogramigoclouddatasource.cpp
AmigoCloud moved its backend URL from www.amigocloud.com to app.amigocloud.com.
The requests are being redirected www -> app, so current build works fine, but we'd like to make this change for the future.
Replaces the default endpoint URL.
> Modify amigocloud URL endpoint.

- autotest/gcore/tiff_read.py
- gdal/frmts/gtiff/geotiff.cpp
- gdal/frmts/gtiff/libtiff/tif_config.h
- gdal/frmts/gtiff/libtiff/tif_dir.c
- gdal/frmts/gtiff/libtiff/tif_dir.h
- gdal/frmts/gtiff/libtiff/tif_dirread.c
- gdal/frmts/gtiff/libtiff/tif_dirwrite.c
- gdal/frmts/gtiff/libtiff/tif_jpeg.c
- gdal/frmts/gtiff/libtiff/tif_ojpeg.c
- gdal/frmts/gtiff/libtiff/tif_open.c
- gdal/frmts/gtiff/libtiff/tif_print.c
- gdal/frmts/gtiff/libtiff/tif_read.c
- gdal/frmts/gtiff/libtiff/tif_strip.c
- gdal/frmts/gtiff/libtiff/tif_write.c
- gdal/frmts/gtiff/libtiff/tiffio.h
- gdal/frmts/gtiff/libtiff/tiffiop.h
- gdal/frmts/gtiff/libtiff/tiffvers.h
- gdal/frmts/gtiff/tifvsi.cpp
The GTiffDataset::IsBlockAvailable() method used a trick for
builds with internal libtiff to avoid loading the whole tile/strip offset/bytecount
arrays.
Move that trick to libtiff itself:
- Add new open flags for TIFFOpen():
* 'D' enable use of defered strip/tile offset/bytecount array loading.
* 'O' on-demand loading of values instead of whole array loading (implies D)
- Add TIFFGetStrileOffset[WithErr]() and TIFFGetStrileByteCount[WithErr]()
public functions.
> GTiff/libtiff: move defered tile/strip offset/bytecount loading to libtiff

- gdal/doc/source/drivers/raster/bag.rst
Updated links to documents within the master branch of the BAG repository on GitHub.
> Update BAG documentation links

- gdal/doc/source/api/index.rst
Typo in doc - `doyxgen` instead of `doxygen`
> Typo in dyxogen

- gdal/doc/source/drivers/raster/wmts.rst
fix an older typo: WTMS to WMTS
See https://github.com/OSGeo/gdal/issues/1590
> typo: WTMS -> WMTS

- gdal/frmts/gtiff/libgeotiff/geo_normalize.c
Close #1595
Set the definition's UOMLength field after determining the value.
> Set the length in the definition after extraction.

- gdal/doc/source/programs/gdalbuildvrt.rst
`gdalbuildvrt` takes a `-r` parameter, not `-rr`.
> Double r typo for gdalbuildvrt resampling parameter

- gdal/doc/source/drivers/raster/gtiff.rst
- gdal/frmts/gtiff/geotiff.cpp
- gdal/frmts/gtiff/gt_overview.cpp
- gdal/frmts/gtiff/gtiff.h
The default overview blocksize is set to 128 whereas I'd argue that setting it to the same value as the full-resolution blocksize makes more sense.
> gtiff: make overview blocksize default to the same as the full-resolution 

- autotest/ogr/ogr_mitab.py
- gdal/ogr/ogrsf_frmts/mitab/mitab.h
- gdal/ogr/ogrsf_frmts/mitab/mitab_imapinfofile.cpp
- gdal/ogr/ogrsf_frmts/mitab/mitab_miffile.cpp
- gdal/ogr/ogrsf_frmts/mitab/mitab_tabfile.cpp
It seems that MITAB code was written before GDAL switched to UTF-8 encoding. 
I added a conversion from a UTF-8  to local encoding for the correct calculation of the number of characters in the field names.
Before my changes, field names were truncated to 16 characters, but the MITAB supports 31.
> MITAB: Fix long fields write in local encoding

- gdal/ogr/ogrsf_frmts/elastic/ogrelasticlayer.cpp
When GeoJSON data was converted to Elasticsearch versions >=5, the GeoJSON type field was incorrectly mapped to a `string` instead of `text`. Elasticsearch would return an error on the unsupported field type. This PR fixes the field mapping similar to how it is done earlier in the BuildMap() function.
N/A
> Elasticsearch: GeoJSON type field should be mapped as text in ES>=5

- gdal/frmts/grib/degrib/degrib/degrib2.cpp
- gdal/frmts/grib/degrib/degrib/inventory.cpp
- gdal/frmts/grib/degrib/degrib/metaprint.cpp
- gdal/frmts/grib/degrib/degrib/tdlpack.cpp
Since nobody is maintaining the code in those blocks, we might as well not have a configuration to compile them.
Unconditionally blocks out TDLPACK-related code, instead of offering a compile-time config option.
- These blocks have not compiled since #1009
- I filed an issue about that (#1648)
> grib: disable dead code with `#if 0` instead of `#ifdef ENABLE_TDLPACK` (fixes #1648)

- autotest/ogr/ogr_elasticsearch.py
- gdal/doc/source/drivers/vector/elasticsearch.rst
- gdal/ogr/ogrsf_frmts/elastic/ogr_elastic.h
- gdal/ogr/ogrsf_frmts/elastic/ogrelasticdatasource.cpp
- gdal/ogr/ogrsf_frmts/elastic/ogrelasticdriver.cpp
- gdal/ogr/ogrsf_frmts/elastic/ogrelasticlayer.cpp
This enables the ElasticSearch driver to work with Elasticsearch 7.x. The `MAPPING_NAME` layer creation option is ignored when converting to Elasticsearch 7.x because mapping types are no longer used. The `MAPPING_NAME` option continues to work the same way in Elasticsearch version < 7.
#1246
> Elasticsearch: Enable support for Elasticsearch 7 (fixes #1246)

- gdal/doc/source/drivers/raster/fits.rst
Add to the documentation specific instructions for CFITSIO linking.
This was suggested in #1598.
> Documentation: add FITS specific installation instructions in fits.rst.

- gdal/alg/marching_squares/segment_merger.h
Don't double increment iterator returned from `emitLine_` function.
Another thing I noticed here. In `emitLines_`, `lines` is erased from the member `lines_` if it is empty, the function then continues. I believe this is therefore unsafe? I think `emitLines_` shouldn't erase from `lines_`. We should be careful with iterators.
#1670 
* OS: Windows 10 x64 (and Ubuntu 18.04.2 LTS x64)
* Compiler: MSVC 1900 (and gcc 7.4.0)
> Fix SegmentMerger list iterator skipping and out of bounds error.

- gdal/frmts/kea/keaband.cpp
Currently, in the KEA driver when passing a `nullptr` as a metadata value results in a crash instead of deleting the item. `kealib` doesn't support deleting of metadata, so this PR simply returns failure instead.
This fixes situations where GDAL was crashing when trying to remove a metadata item on a KEA file (for example, running `ComputeStatistics()` multiple times with `bApproxOK=TRUE`).
* OS:
* Compiler:
cc: @bhjolly @petebunting @neilflood
> KEA: return error when deleting metadata item rather than crashing

- gdal/doc/source/programs/gdallocationinfo.rst
Usage of gdallocationinfo is not very intuitive. When not supplied with a location it will simply wait for input, not exit or print a message. This example of stdin input will hopefully make it more clear.
Uses autotest/utilities/data/utmsmall.tif
> Doc gdallocationinfo: Add stdin example

- gdal/frmts/gtiff/geotiff.cpp
A few weeks ago we had made major improvement by having each TIFF
directory to own its ow TIFF handle, and thus avoiding frequent
reloading of the Tile/Strip arrays.
However part of the previous logic remained in the driver, which
caused the arrays to be rewritten each time we switched between IFD.
> GTiff: improve performance of generation of internal overviews

- gdal/doc/source/programs/gdal_retile.rst
- gdal/swig/python/scripts/gdal_retile.py
Adds `-resume` option to `gdal_retile.py` discussed in PR #885.  
Uses `os.rename()` to atomically move output tiles from .tmp to finalized state.  This allows gdal_retile.py to infer that tiles passing `os.path.exists()` are complete and safe to use.   
#885
> Add resume option to gdal_retile.py

- gdal/swig/python/setup.py
Upstream fix to the packaging of the swig wheel.
This PR fixes scope issues around adding compile flags to clang during the build of darwin wheels. More specifically, the darwin options try to extend the extension object bound to ext, however, it's only in scope under the for loop, so I moved all the logic under the for loop as that seems like intended behavior and does in fact fix the build on darwin.
https://github.com/NixOS/nixpkgs/pull/64551
* OS: macOS 10.14.5
* Compiler: clang 7.1.0
> swig/python/setup.py: Fix swig python wheel on darwin

- autotest/gdrivers/tiledb_write.py
- gdal/frmts/tiledb/tiledbdataset.cpp
This PR enables partial updates to TileDB arrays through the GDAL API. Python typically indexes from zero, so if a TileDB GDAL style array is created outside of the GDAL API then this code adapts to a change in starting index.
> tiledb: partial updates to existing arrays

- gdal/ogr/ogr_spatialref.h
Two links in the documentation of ogr_spatialref.h point to the wrong location.
Updates two links to the new correct location.
#1767
> Update broken links in ogr_spatialref.h (fixes  #1767)

- autotest/gdrivers/netcdf.py
- gdal/frmts/netcdf/netcdfsg.cpp
Suppose a netCDF file uses different node coordinate dimensions for any two of its node coordinate variables. This PR makes it so that these datasets consisting of malformed CF-1.8 do not create layers.
Specifically, this PR also addresses Coverity Scan Issue CID 1404242. See the related issue below.
Thanks to @rouault for finding this issue and providing a fix.
Issue #1770 
* OS: openSUSE Tumbleweed
* Compiler: GCC 9.1.1 (revision 273734)
> Fix Coverity Scan Issue CID 1404242 and Broken Malformed CF Rejection

- gdal/frmts/netcdf/netcdfsgwriterutil.cpp
- gdal/frmts/netcdf/netcdfsgwriterutil.h
The CF-1.8 portion of the netCDF Driver keeps an approximate count of memory usage during normal operation. If enough writes are logged, relative to the maximum buffer size, then underflow could possibly occur. This was in part, if not completely, because transactions received from the log, were not being re-recorded into the memory log but their usage were still being subtracted out. This PR fixes this issue by adding logged transactions back into the buffer memory counter.
This PR also adds an assert to the counter subtraction to have this check that it does not underflow be performed in tests.
Thanks to @rouault for reporting this issue.
Issue #1772 
* OS: openSUSE Tumbleweed
* Compiler: GCC 9.1.1
> Address buffer memory counting underflow in CF-1.8- issue #1772

- gdal/doc/source/user/multidim_raster_data_model.rst
Fixed typo in link to: NumPy documentation about multidimensional array _indexing_ order issues
Page: https://gdal.org/user/multidim_raster_data_model.html
> gdal.org - Fix typo in "Multidimensional Raster Data Model" documentation

- gdal/.gitignore
Follow up for commit 9598f66a2e, which introduced the new executable `gdalmdimtranslate`.
The executable is in the `git status` after compiling the latest on the master branch.
> Add `apps/gdalmdimtranslate` to .gitignore

- gdal/frmts/netcdf/netcdfdataset.cpp
According with the NUWG NetCDF Conventions for naming units, the value "rad" for radian unit shouldn't be used. Instead, the correct value should be "radian".
As one can see in the end of the following document:
https://www.unidata.ucar.edu/software/netcdf/netcdf/Units.html
Issues: #1799
In order to solve this issue, the value "radian" is being added as possible value for the X/Y axis/coordinates unit.
The value "rad", which instead means "absorbed dose", still being allowed, to keep retro-compatibility.
> frmts/netcdf; Allow "radian" value for the X/Y axis units (geos projection)

- gdal/frmts/netcdf/netcdfdataset.cpp
This currently happens in GOES with the FDCF fire product (and other
products).  Rather than hide the data, drop the valid range and warn.
This does not fix the issue of the Power field's max valid being too
low.
The issues are known to the data provider.
https://www.ncdc.noaa.gov/data-access/satellite-data/goes-r-series-satellites#FDC
See #1811
The PR has been tested with a custom test not included here as I don't have a small test case.  Counting on the Travis CI tests to check for other things that might be impacted from having bad valid ranges.
> netcdfdataset.cpp: Disregard valid range if min > max.

- gdal/gcore/gdaldataset.cpp
- gdal/ogr/ogr_proj_p.cpp
- gdal/port/cpl_multiproc.h
- gdal/port/cpl_vsil_curl.cpp
See https://developercommunity.visualstudio.com/content/problem/124121/thread-local-variables-fail-to-be-initialized-when.html
> Fix issues with thread_local and C++ objects that don't work well with DLL on Windows

- gdal/swig/include/gdal_array.i
- gdal/swig/include/python/typemaps_python.i
"obj0" was only meant as a porting helper and should not be used, even
with swig 3.0, see swig/swig@cd8fc0a.
Use the correct "$self" notation, which is expanded to the correct
code regardless of swig version and options.
> Replace SWIG Python obj0/swig_obj[0] with version agnostic $self

- autotest/pyscripts/test_gdal2tiles.py
- gdal/doc/source/programs/gdal2tiles.rst
- gdal/swig/python/scripts/gdal2tiles.py
See https://lists.osgeo.org/pipermail/gdal-dev/2019-August/050696.html
Should there be basic tests for the `resample` option in `gdal/autotest/pyscripts/test_gdal2tiles.py`?
> gdal2tiles.py: add remaining resample methods

- gdal/ogr/ogrsf_frmts/sqlite/ogrsqlitevirtualogr.cpp
* OS: iOS 12.4
* Compiler: clang (cross for iOS)
> SQLITE: fix crash in loading sqlite extensions on ios (fixes #1820)

- gdal/doc/source/drivers/vector/flatgeobuf.rst
Adds an example of ogr2ogr usage with FlatGeobuf. It took me a while to figure out that the output file MUST have the `.fgb` extension
> flatgeobuf.rst: Add ogr2ogr example

- gdal/frmts/openjpeg/openjpegdataset.cpp
` while( (nPair = CPLAtomicInc(&(poJob->nCurPair))) < nPairs ||  !poJob->bSuccess )`
The logic allows accessing poJob->oPairs[nPair] even if nPair >=nPairs in case when !poJob->bSuccess is true
Correct logic should continue the cycle if nPair<nPairs and poJob->bSuccess is true. And break the cycle if nPair>=nPairs or poJob->bSuccess is false.
> Openjpeg driver: Memory corruption due to a wrong condition logic

- gdal/frmts/raw/rrasterdataset.cpp
Minor typo fix in rrasterdataset 
"prejection" -> "projection"
> fix tiny typo

- gdal/gcore/overview.cpp
This PR replaces `sqrt( R*R + I*I )` method with `std::hypot(R, I)` to fix precision lost within complex absolute values computation.
Function `std::hypot`  implements precise algorithm for calculating absolute value of complex number without undue overflow or underflow.
See: 
* https://en.cppreference.com/w/cpp/numeric/math/hypot
* https://en.wikipedia.org/wiki/Hypot#Implementation
>  gcore: Fix precision lost with complex data

- gdal/doc/source/download.rst
The download pages should indicate criteria behind advertising the selection of providers of GDAL binaries; to address potential questions why X is not listed.
- https://github.com/OSGeo/gdal/pull/1866#discussion_r326299551 and https://github.com/OSGeo/gdal/pull/1866#issuecomment-533248059
- #1641
> Docs: clarify criteria for advertising providers of binary packages

- gdal/frmts/prf/phprfdataset.cpp
- gdal/gcore/gdal_proxy.h
- gdal/gcore/gdalproxypool.cpp
Fixes floating point exception on copy overviews from PRF dataset to destination dataset.
Sample command line:
```
gdal_translate \
-co COPY_SRC_OVERVIEWS=YES \
-of GTiff ./input.prf ./output.tif
```
Error occurs when passing zero block dimensions at the PRF driver ([see: phprfdataset.cpp:138](https://github.com/drons/gdal/blob/fixCoreDumpOnZeroBlockSize/gdal/frmts/prf/phprfdataset.cpp#L138) ).
> Proxy pool: Load band block sizes if not provided at creation time.

- gdal/ogr/ogrsf_frmts/flatgeobuf/packedrtree.cpp
- gdal/ogr/ogrsf_frmts/flatgeobuf/packedrtree.h
CC @bjornharrtell 
I haven't tested the performance impact. Passing by reference could possibly speed up things a tiny bit, but not sure that's measurable in practice.
> FlatGeobuf: constify and pass more arguments by reference in PackedRTree and Rect classes

- gdal/doc/source/drivers/vector/csv.rst
- gdal/doc/source/drivers/vector/pg.rst
- gdal/doc/source/drivers/vector/sqlite.rst
- gdal/doc/source/programs/gdal2tiles.rst
- gdal/doc/source/programs/gdalwarp.rst
- gdal/doc/source/programs/ogr2ogr.rst
- gdal/doc/source/programs/ogrinfo.rst
It adds some examples to the command line programs `ogr2ogr`, `ogrinfo`, `gdal2tiles` and `gdalwarp`. Also inside the drivers `pg`, `csv` and `sqlite`. 
I find the existing examples rather complex, therefore I added some rather simple examples. The idea behind it is to make it easier for new users to get started with the GDAL/OGR command line tools.
> Doc: add examples commandline programs

- gdal/ogr/ogrsf_frmts/mitab/mitab_imapinfofile.cpp
Update mitab_imapinfofile.cpp WindowsLatin2 definition for WindowsLatin2 to {"WindowsLatin2", "CP1250"} (fixes #1571)
> MITAB: Update WindowsLatin2 definition

- autotest/gcore/rasterio.py
- gdal/gcore/rasterio.cpp
gcore: fix resampling over nodata blocks (fixes #1941)
This fixes GDALRasterBand::RasterIOResampled when dealing with interpolation over nodata blocks if the input buffer type differs from output buffer type.
> gcore: fix resampling over nodata blocks (fixes #1941)

- gdal/frmts/jp2kak/jp2kakdataset.cpp
Concurrently decoding from multiple jp2 files results in an error being raised:
>  ERROR 1: Kakadu Core Error:
>  Multi-threaded implementation error detected.  Before passing a `kdu_thread_env' reference into any 
>  of the `kdu_codestream' machinery's interface functions you need to pass a `kdu_thread_env' 
>  reference into one of the top-level interface functions that configures the codestream for multi- 
>  threaded processing.  The main functions of this form are `kdu_codestream::create' and 
>  `kdu_codestream::open_tile', although there are others which can see a `kdu_thread_env' 
>  environment for the first time.
I have not digged deep into the issue, but the proposed patch fixes that error.
> JP2KAK: fix issue with multi-threaded reads

- gdal/doc/source/programs/gdal2tiles.rst
- gdal/swig/python/scripts/gdal2tiles.py
Add a warning when `gdal2tiles.py` input is a raster with non-Byte data type. Also add note to the documentation.
Fixes #1956
> gdal2tiles: warn when input raster has non-Byte data type (fixes #1956)

- gdal/swig/python/osgeo/__init__.py
Since Python 3.8 on Windows, the PATH is no longer used to try to load
.dlls from which the .pyd extensions depend on.
https://docs.python.org/fr/3/whatsnew/3.8.html#bpo-36085-whatsnew
This is a bit annoying in a development environment, so add a hint when
this sitation occurs. And allow the user to define the USE_PATH_FOR_GDAL_PYTHON
environment variable to allow the PATH to still be considered.
> osgeo/__init__.py: add hint&workaround for ImportError on Windows Python >= 3.8

- gdal/frmts/vrt/vrtdataset.h
- gdal/frmts/vrt/vrtrawrasterband.cpp
We need mmap-based io for raw dataset wrapped with vrt. Currently, two methods of GetVirtualMemAuto, buffer, or filemap,  are controlled by the option "USE_DEFAULT_IMPLEMENTATION"="YES/NO". 
This PR adds an explicit GetVirtualMemAuto interface to VRTRawRasterBand so that the RawRasterBand method can be called. The FileMapping (mmap) method can be selected by setting  USE_DEFAULT_IMPLEMENTATION=NO.  Without the interface, VRTRawRasterBand uses its parent class method, which returns a buffer-based VirtualMem (USE_DEFAULT_IMPLEMENTATION=YES) or nullptr (USE_DEFAULT_IMPLEMENTATION=NO).
> VRTRawRasterBand: add GetVirtualMemAuto interface to enable mmap io

- autotest/gcore/tiff_srs.py
- autotest/osr/osr_ct_proj.py
- gdal/doc/source/drivers/raster/gtiff.rst
- gdal/frmts/gtiff/gt_wkt_srs.cpp
- gdal/ogr/ogr_proj_p.cpp
- gdal/ogr/ogr_proj_p.h
- gdal/ogr/ogr_srs_api.h
- gdal/ogr/ogrct.cpp
- gdal/ogr/ogrspatialreference.cpp
- gdal/swig/include/osr.i
- gdal/swig/python/extensions/osr_wrap.cpp
- gdal/swig/python/osgeo/osr.py
*  Add a OSR_ADD_TOWGS84_ON_IMPORT_FROM_EPSG=YES/NO config option for importFromEPSG(). And in the GTiff driver, do not write TOWGS84 that come from EPSG codes, unless GTIFF_WRITE_TOWGS84=YES is explicitly set
* Add a OSRGetPROJSearchPaths() function
*  OSR_CT: add a OSR_CT_USE_DEFAULT_EPSG_TOWGS84 configuration option that can be set to YES to explicit honour default TOWGS84 terms of a EPSG code
> Several TOWGS84 related changes

- gdal/doc/source/user/virtual_file_systems.rst
This is a typo as well but I don't know the intended meaning so can't fix it.
"/vsicrypt/ is a special file handler **is** installed that allows reading..."
could mean:
"/vsicrypt/ is a special file handler **if** installed that allows reading..."
which is odd phrasing.  If that is what is meant, could consider:
"If installed, /vsicrypt/ is a special file handler that allows reading..."
Doing nothing works fine too since I think that the information is conveyed as is.
* OS:
* Compiler:
> Docs: fix typo in virtual_file_systems.rst

- autotest/cpp/testblockcachewrite.cpp
- gdal/gcore/gdal_priv.h
- gdal/gcore/gdalabstractbandblockcache.cpp
- gdal/gcore/gdalarraybandblockcache.cpp
- gdal/gcore/gdaldataset.cpp
- gdal/gcore/gdalhashsetbandblockcache.cpp
- gdal/gcore/gdalrasterband.cpp
- gdal/gcore/gdalrasterblock.cpp
When writing several GDAL datasets in parallel from several threads, a
thread can force a dirty block of another thread/dataset to be written. By
doing so, it will remove it from the list of cached blocks, so if the thread
that explictly manipulates this dataset reacquire the block, it will see an
old version of the block. The effect of this can be particularly seen with
GeoTIFF files with multi band pixel leaving organization, where acquiring
a block of a band causes corresponding blocks of other bands to be cached.
The main fix done here is in GDALRasterBlock::Internalize() to avoid evicting
a dirty block of another dataset when there are other candidates. This considerably
reduces the likelihood of the bug.
Another fix is done in GDALDataset::EnterReadWrite() to wait for the completion …
> Block cache: fix corruption on multithreaded write on datasets (fixes #2011)

- autotest/gcore/vrt_read.py
- gdal/doc/source/drivers/raster/vrt.rst
- gdal/frmts/vrt/vrtdataset.cpp
- gdal/frmts/vrt/vrtdataset.h
as a convenient way of creating a on-the-fly VRT with a subset of bands
> VRT driver: add 'vrt://{gdal_dataset}?bands=num1,...,numN' syntax

- gdal/apps/gdal_grid_lib.cpp
- gdal/apps/gdal_rasterize_lib.cpp
- gdal/apps/gdal_translate_lib.cpp
- gdal/apps/gdalbuildvrt_lib.cpp
- gdal/apps/gdaldem_lib.cpp
- gdal/apps/gdalinfo_lib.cpp
- gdal/apps/gdalmdiminfo_lib.cpp
- gdal/apps/gdalmdimtranslate_lib.cpp
- gdal/apps/gdalwarp_lib.cpp
- gdal/apps/nearblack_lib.cpp
- gdal/apps/ogr2ogr_lib.cpp
After looking through the docs I noticed there were quite a few broken links, so I went ahead and updated them. An example can be found here: https://gdal.org/api/gdal_utils.html#gdal__utils_8h_1a1cf5b30de14ccaf847ae7a77bb546b28
It seemed as though most of the links were relative, leading to links such as: https://gdal.org/api/gdal_translate.html 
instead of: 
https://gdal.org/programs/gdal_translate.html
In lieu of searching for every broken link in the docs, I grepped through the project to find any potential links (pardon the pipe)
``grep -r "accepted options are the ones" | grep "cpp"``
* OS: Ubuntu 18.04 LTS
> DOCS: Updated broken documentation links within src files

- gdal/ci/travis/sanitize/before_install.sh
- gdal/ci/travis/sanitize/install.sh
- gdal/ci/travis/sanitize/script.sh
Found out I could reuse the sanitize setup on a plain Ubuntu 16.04 with these changes. Should still work at Travis.
> Allow Travis sanitize build to work on plain Ubuntu 16.04

- autotest/gcore/gdal_api_proxy.py
- autotest/gcore/vsicrypt.py
- autotest/gdrivers/netcdf_cf.py
- autotest/gdrivers/netcdf_multidim.py
- autotest/ogr/ogr_esrijson.py
- autotest/ogr/ogr_geojson.py
- autotest/ogr/ogr_ingres.py
- autotest/ogr/ogr_rfc41.py
- autotest/ogr/ogr_virtualogr.py
- gdal/ci/travis/trusty_clang/before_install.sh
- gdal/ogr/ogrsf_frmts/geojson/ogresrijsonreader.cpp
- gdal/swig/python/scripts/mkgraticule.py
On top of PR #2069. Only last commit is specific to this PR
> Fix autotest/scripts issues raised by Flake8 F632 'use ==/!= to compare str, bytes, and int literals'

- gdal/doc/source/api/index.rst
- gdal/doc/source/api/python_gotchas.rst
Adds a new page to the API documentation that brings in the Python Gotchas from the wiki as described in https://github.com/OSGeo/gdal/issues/1940. Updates the API docs table of contents to link to the new page. 
https://github.com/OSGeo/gdal/issues/1940
https://github.com/OSGeo/gdal/issues/1939
* OS:
* Compiler:
> Doc: fix issue 1940 - ported Python gotchas from wiki to API docs

- gdal/GNUmakefile
Current use of absolute $(GDAL_ROOT) path leads to super long linking
command, that can go over the 256K Mac OS limit.
> Unix build: do not use absolute path in linking command (fixes #2075)

- autotest/gdrivers/vicar.py
- gdal/doc/source/drivers/raster/pds.rst
- gdal/doc/source/drivers/raster/vicar.rst
- gdal/frmts/pds/pdsdataset.cpp
- gdal/frmts/pds/vicardataset.cpp
- gdal/frmts/pds/vicardataset.h
- gdal/frmts/pds/vicarkeywordhandler.cpp
- gdal/frmts/pds/vicarkeywordhandler.h
...that can be set to YES so that PDS3 datasets that contain a VICAR label are opened by the VICAR driver
> PDS3/VICAR: add a GDAL_TRY_PDS3_WITH_VICAR configuration option 

- gdal/docker/ubuntu-full/Dockerfile
- gdal/docker/ubuntu-small/Dockerfile
alpine installs ca-certificates when libcurl is installed.
Fixes #2101 
Adds ca-certificates to the base ubuntu images so that connection to https servers works.
#2101
> Docker: Allow https for ubuntu containers

- autotest/gdrivers/tiledb_write.py
- gdal/frmts/tiledb/tiledbdataset.cpp
This PR uses the metadata feature that is available in TileDB 1.7+ rather than creating a sidecar file. The benefits are API compatibility with TileDB as well as supporting versioned metadata. Backwards compatibility with the sidecar approach has been maintained where possible.
> tiledb: use array metadata to store xml

- gdal/doc/source/drivers/raster/jpeg2000.rst
Removed trailing encoded spaces from link to modified JasPer library.
> Doc: Fix broken link in jpeg2000.rst

- autotest/gcore/tiff_srs.py
- autotest/gcore/tiff_write.py
- autotest/gdrivers/dted.py
- autotest/ogr/ogr_shape.py
- autotest/osr/osr_compd.py
- autotest/osr/osr_ct_proj.py
- autotest/osr/osr_epsg.py
- gdal/frmts/gtiff/geotiff.cpp
- gdal/frmts/gtiff/gt_wkt_srs.cpp
- gdal/frmts/gtiff/gt_wkt_srs.h
- gdal/ogr/ogr_spatialref.h
- gdal/ogr/ogr_srs_api.h
- gdal/ogr/ogrct.cpp
- gdal/ogr/ogrspatialreference.cpp
- gdal/swig/include/osr.i
- gdal/swig/python/extensions/osr_wrap.cpp
- gdal/swig/python/osgeo/osr.py
When importing from EPSG, GDAL 3.0.0 to 3.0.2 followed the scheme used in
GDAL 1.x and GDAL 2.x, that is they tried to attach a TOWGS84 transformation.
While the intent was to have some sort of backward compatibility, this may
be a pain for the future.
So do the following changes:
- importFromEPSG(): no longer attach a TOWGS84 transformation, unless the
user set the OSR_ADD_TOWGS84_ON_IMPORT_FROM_EPSG=YES configuration option
- Add a OGRSpatialReference::AddGuessedTOWGS84() to attach such a transformation,
when possible (note: this will do it in a more prudent way than GDAL 1.x/2.x,
that is only if a transformation is found for the whole area of use of the CRS)
- exportToProj4(): if the SRS has no transformation to WGS84,
attach a +towgs84 if the SRS has a EPSG code and …
> Revise how SRS methods deal with TOWGS84

- autotest/utilities/test_ogrinfo.py
- gdal/apps/ogrinfo.cpp
Discovered when reading https://github.com/OSGeo/gdal/pull/2113#issuecomment-566868430
> ogrinfo: fix to output WKT2 SRS by default. Was done correctly for several geometry column, but not single one

- autotest/ogr/ogr_mitab.py
- gdal/doc/source/drivers/vector/mitab.rst
- gdal/ogr/ogrsf_frmts/mitab/mitab_spatialref.cpp
Refs https://github.com/OSGeo/gdal/pull/2113#issuecomment-566990508
Past behaviour can be restored with setting the MITAB_SET_TOWGS84_ON_KNOWN_DATUM
configuration option to YES.
> MITAB: do not set (by default) TOWGS84 when reading a known Datum 

- gdal/ogr/ogr_proj_p.cpp
- gdal/ogr/ogrct.cpp
With PROJ >= 6.3, make PROJ the default. Otherwise default to BEST_ACCURACY
Previous behaviour was FIRST_MATCHING
BEST_ACCURACY matches closely the behaviour of PROJ 6.3.0, except that it
is evaluated just once per call to OGRProjCT::Transform()
> Coordinate transformation: add a OGR_CT_OP_SELECTION=PROJ/BEST_ACCURACY/FIRST_MATCHING config option

- gdal/ogr/ogr_proj_p.cpp
- gdal/ogr/ogrct.cpp
With PROJ >= 6.3, make PROJ the default. Otherwise default to BEST_ACCURACY
Previous behaviour was FIRST_MATCHING
BEST_ACCURACY matches closely the behaviour of PROJ 6.3.0, except that it
is evaluated just once per call to OGRProjCT::Transform()
> [backport 3.0] Coordinate transformation: add a OGR_CT_OP_SELECTION=PROJ/BEST_ACCURACY/FIRST_MATCHING config option

- autotest/ogr/ogr_mysql.py
- gdal/ci/travis/ubuntu_1804/before_install.sh
- gdal/ogr/ogrsf_frmts/mysql/ogrmysqldatasource.cpp
Support MySQL 8.0 use SRID for  indexing geometry by creating table with geom column
as 'NOT NULL SRID <#srid>'
Also update CI test by updating MySQL from 8.0.1 to 8.0.18. 
(SRID index is supported from 8.0.3)
#1015
MySQL 8.0, MariaDB
> ogr/mysql: Add SRID to geometry when creating layer table(fixes #1015)

- .gitignore
Current GDAL does not support build using CMake but there are external project to add CMake project files to GDAL. To avoid merging CMake related files  into GDAL project, gitignore CMake related files.
> gitignore: aware of CMake file

- gdal/GDALmake.opt.in
- gdal/GNUmakefile
- gdal/configure
- gdal/configure.ac
- Don't modify datarootdir, datadir and mandir in configure.
- Use htmldir for installing docs (which are html). This will default to
docdir but also allows a special html directory to be specified.
- Rename INST_HTML to reduce confusion because it is only used for
the project web-update target, not the normal install-docs.
(also a simple commit to ensure datarootdir is specified which is causing warnings)
* OS: Gentoo Linux
> Doc: allow user full control over installation directory

- gdal/swig/python/GNUmakefile
With SWIG-3.0.2:
SWIG:1: Warning 125: Use of the include path to find the input file is
deprecated and will not work with ccache. Please include the path when
specifying the input file.
Add path to gdal_array.i in gdal/swig/python/GNUmakefile.
* OS: Gentoo Linux
* Compiler: GCC
> Python bindings: Fix SWIG warning of missing path for input file

- autotest/cpp/testcopywords.cpp
- gdal/gcore/rasterio.cpp
(when SSSE3 is not available)
Fix issue reported on https://lists.osgeo.org/pipermail/gdal-dev/2019-December/051371.html
> GDALUnrolledCopy<GByte,2,1>: fix SSE2-only implementation

- gdal/ogr/ogrsf_frmts/mysql/ogr_mysql.h
- gdal/ogr/ogrsf_frmts/mysql/ogrmysqldatasource.cpp
- gdal/ogr/ogrsf_frmts/mysql/ogrmysqllayer.cpp
- gdal/ogr/ogrsf_frmts/mysql/ogrmysqlresultlayer.cpp
- gdal/ogr/ogrsf_frmts/mysql/ogrmysqltablelayer.cpp
#What does this PR do?
When using MySQL 8.0.3 and later, utilize System geometry metadata table instead of manual management.
#1015
MySQL 8.0 / MariaDB
This improvement is depends on #2111
> Use ST_GEOMETRY_COLUMNS table for metadata in MySQL 8.0 and later (Enhance #1015)

- gdal/ogr/ogrsf_frmts/sqlite/ogr_sqlite.h
SPATIALITE_AMALGAMATION is only defined with HAVE_SPATIALITE.
sqlite3.h was always being included by line 45 anyway https://github.com/OSGeo/gdal/blob/84d972714a80fa019fd11f53b86fa3d5eb2db6c6/gdal/ogr/ogrsf_frmts/sqlite/ogr_sqlite.h#L45
having two conditional includes as well seems wrong.
sqlite3.h is being located using -I so #include should have <>.
This code does look like the result of several reports and associated changes:
https://trac.osgeo.org/gdal/ticket/3342
https://trac.osgeo.org/gdal/ticket/4269
https://trac.osgeo.org/gdal/changeset/41503
There is even a symlink in the Debian/Ubuntu package because of gdal:
```
spatialite (2.4.0~rc2-4) unstable; urgency=medium
* Now -dev package depends also on libsqlite3-dev.
* Added a symlink for sqlite3.h within /usr/include/spatialite …
```
> ogrsf_frmts/sqlite: simplify to one #include sqlite3.h

- gdal/NEWS
- gdal/ogr/ogrsf_frmts/geojson/ogrgeojsonlayer.cpp
- gdal/ogr/ogrsf_frmts/geojson/ogrgeojsonwritelayer.cpp
> Set StringsAsUTF8 flag to TRUE for GeoJSON

- gdal/swig/python/scripts/gdal2tiles.py
Since `GDAL_CACHEMAX` is only read once, setting it here has no effect anymore for future calls (even multiprocessed).
By setting the cache directly using `SetCacheMax`, we can fix the cache per process.
Fixes gdal2tiles max cache setting
N/A
Discovery of this was done on Ubuntu azure machines.
F4, 4 threads to tile: Ram 4/8GB
F32, 20 threads to tile: SIGKILL
F32: 16 threads to tile: 58/64GB
This shows us the default 5% GDAL_CACHEMAX is being used for every process instead of being split over processes.
> gdal2tiles: Fix max cache setting

- gdal/doc/source/programs/ogr2ogr.rst
documents the fact that ogr2ogr's -explodecollections happens after any operations from -sql and not before.
> update ogr2ogr -explodecollections documentation with order relative to -sql

- gdal/doc/source/development/rfc/rfc76_ogrpythondrivers.rst
Fix links for OGR Python driver examples
> Update links for OGR Python driver examples

- gdal/swig/python/scripts/gdal2tiles.py
Adds a check for for the min/max zoom passed to gdal2tiles to ensure min <= max.
#2161
> gdal2tiles: Check that min zoom <= max zoom (fixes #2161)

- autotest/ogr/ogr_mitab.py
- gdal/doc/source/drivers/vector/mitab.rst
- gdal/ogr/ogrsf_frmts/mitab/mitab.h
- gdal/ogr/ogrsf_frmts/mitab/mitab_ogr_datasource.cpp
- gdal/ogr/ogrsf_frmts/mitab/mitab_ogr_driver.cpp
- gdal/ogr/ogrsf_frmts/mitab/mitab_tabfile.cpp
Add support of friendly names (description) to MapInfo tab (MITAB). For details see https://support.pitneybowes.com/SearchArticles/VFP05_KnowledgeWithSidebarHowTo?id=kA180000000CtuHCAS&popup=false&lang=en_US 
None
> MITAB: Add friendly layer name (description) support.

- gdal/MIGRATION_GUIDE.TXT
- gdal/configure
- gdal/configure.ac
for 3.0 https://github.com/OSGeo/gdal/commit/45e06386d9099cbbe4f8eb7b4c2b8edca09ed144 / #1412 changed the arguments of `--with-pg` configure option from taking a path to taking a boolean. This is easily overlooked by users upgrading from earlier versions and effectively disables PostgreSQL support despite this option defaults to `yes`. Packagers are having trouble with this too, see https://github.com/OSGeo/homebrew-osgeo4mac/issues/1291 and https://github.com/PostgresApp/PostgresApp/issues/548
To mitigate the issue, I add a configure error if the argument of `--with-pg` is in the old form (similar to what you did with the equivalent change for `--with-xml2` in https://github.com/OSGeo/gdal/commit/bfdf002a53e4ef7ce935b365c4490c96dee6f605 / #2173) and mention the breaking change in the …
> improve handling of --with-pg

- .travis.yml
- autotest/gcore/cog.py
- autotest/gcore/tiff_write.py
- autotest/gdrivers/gpkg.py
- autotest/gdrivers/jp2lura.py
- autotest/gdrivers/jp2openjpeg.py
- autotest/gdrivers/test_validate_jp2.py
- autotest/ogr/ogr_fgdb.py
- autotest/ogr/ogr_gpkg.py
- autotest/ogr/ogr_mvt.py
- autotest/utilities/test_ogr2ogr.py
- gdal/ci/travis/python3/before_install.sh
- gdal/ci/travis/python3/install.sh
Latest pip version only supports Python >= 3.5, thus Trusty is too old.
Also fixes a number of import patterns that didn't play nice with pytest & python 3
> .travis.yml: move python3 config to Xenial

- autotest/gdrivers/tiledb_write.py
- gdal/frmts/tiledb/tiledbdataset.cpp
Zeros the tile read when the array is being updated. This is a pattern followed by other drivers e.g. https://github.com/OSGeo/gdal/blob/master/gdal/frmts/hdf4/hdf4imagedataset.cpp#L300 and prevents artifacts when updating
> tiledb: zero tile data on read when updating

- autotest/gcore/vsis3.py
- gdal/port/cpl_aws.cpp
This PR fixes a copy/paste error at line 890 of `port/cpl_aws.cpp` that caused `~/.aws/credentials` to be loaded instead of `~/.aws/config` here:
https://github.com/OSGeo/gdal/blob/cdd65c9ce4f9ed11b53620c79c25df4bdd29797c/gdal/port/cpl_aws.cpp#L878-L890
This caused issues when using a non-default AWS region stored in the default `~/.aws/config` file, as this file was never parsed.
The test in autotest checking for non-default profiles did not catch this error, because it was using the `AWS_CONFIG_FILE` config option to point to a non-default config file. I have modified the test to make it use the default config file so that the non-tested lines are now covered (I had to play around with `$HOME` in order to do this without tampering with the user's real config/credentials files).
> AWS: Fix error in loading ~/.aws/config file

- gdal/doc/source/drivers/raster/dted.rst
Corrects the documentation to reflect the support status of DTED for Create() and CreateCopy(). Currently the docs state that DTED supports Create(), however, the DTED driver reports that it only supports CreateCopy() via its metadata information. This is backed up by the fact that up until GDAL 3.1 you were unable to use gdalwarp directly to output a file in DTED format. GDAL 3.1 introduced the ability to output in formats that supported CreateCopy() and you can now use gdalwarp with the DTED format which highlights that DTED does in fact support CreateCopy() not Create().
None found
Nil
Not relevant
> Correct dted.rst to reflect DTED driver supports CreateCopy() only

- gdal/doc/source/drivers/raster/msg.rst
This PR fixes the link and install instructions for the MSG driver using a library by EUMETSAT. The library in question is now available at a new address, under a FOSS license, and as a git repo and thus is cloneable.
#2205 is related.
This is not specific to any environment.
> MSG driver doc: Update link (fixes #2205)

- autotest/ogr/ogr_shape.py
- gdal/doc/source/drivers/vector/shapefile.rst
- gdal/ogr/ogrsf_frmts/shape/ogrshapelayer.cpp
Should help for use case raised by https://github.com/qgis/QGIS/pull/34381
> Shape: expose .dbf and .cpg source encodings in the SHAPEFILE metadata domain

- gdal/frmts/tiledb/tiledbdataset.cpp
If a user specify a vsis3 prefix then the TileDB driver can use this as a direct s3 uri internally. 
This was discovered when using the Rasterio library to open arrays from s3.
https://github.com/mapbox/rasterio/issues/1864
> redirect vsis3 calls to tiledb s3 direct calls

- gdal/frmts/dimap/dimapdataset.cpp
Some Dimap files do not contain the <Dataset_Components> element. We don't want to error out on these if the needed <Raster_Data> is present
> DIMAP: don't look inside Dataset_Components if Raster_Data is present

- gdal/doc/source/programs/gdal_rasterize.rst
Adds missing documentation for the `-optim` option of GDAL rasterize. This was done in the original PR, but the documentation has become lost at some point. This PR is more or less a straight copy-paste of the original documentation:
https://github.com/OSGeo/gdal/pull/222/files#diff-ec9a80598d8c1071fb421f9b9eb560d7
I'm not sure if there's any additional documentation files for the C++ API, or other wrappers such as the Python API, that need to be updated.
#222
> Docs: Add missing -optim option in gdal_rasterize

- gdal/swig/python/osgeo/__init__.py
Remove deprecated reference to Python imp module, which caused a startup
warning on QGIS. Replaced those references with a call to importlib. Fixes #2264.
> Python: Removed calls to imp module (fixes #2264)

- gdal/ogr/ogrsf_frmts/flatgeobuf/ogrflatgeobuflayer.cpp
- gdal/port/cpl_error.h
@bjornharrtell I find the Flatgeobuf driver super verbose. This PR disables most CPLDebug() for non-DEBUG builds as they are presumably only useful for the developer, and not for users, and even if they are not displayed they still burn a bit of CPU to figure they must not be displayed. I've just kept a few instances where there was debug messages in CPLError() cases.
> FlatGeobuf: disable most CPLDebug() for non-DEBUG builds

- autotest/ogr/ogr_flatgeobuf.py
- gdal/ogr/ogrsf_frmts/flatgeobuf/ogr_flatgeobuf.h
- gdal/ogr/ogrsf_frmts/flatgeobuf/ogrflatgeobufdataset.cpp
- gdal/ogr/ogrsf_frmts/flatgeobuf/ogrflatgeobuflayer.cpp
And also remove CreateGeomField capability, that should only be
declared if OGRLayer::CreateGeomField() is implemented (for several
geometry fields per feature)
> FlatGeoBuf: implement Binary, Bool, Short and Float field types

- autotest/ogr/ogr_flatgeobuf.py
- gdal/ogr/ogrsf_frmts/flatgeobuf/ogrflatgeobufdataset.cpp
- gdal/ogr/ogrsf_frmts/flatgeobuf/ogrflatgeobuflayer.cpp
-  FlatGeobuf: allow creating a file in write-only mode (/vsizip/, /vsis3/ etc), and delete temporary file ASAP on Unix
- FlatGeobuf: advertize OLCRandomRead when index is present
-  FlatGeobuf: do not read index if the extent of the spatial filter is larger than the layer extent
> FlatGeobuf: streamed writing and two other small improvements

- gdal/swig/python/setup.py
fixes #2158
Doing `pip install gdal[numpy]` will install `gdal` with `numpy > 1.0.0`.
`pip` will ensure that `numpy` is installed first so that it's detected
and the releveant features/bindings/etc. are compiled and made available
for users.
FYI I did not touch how `numpy` was installed in the various CI scripts, being a bit afraid of breaking things and/or making a mess.
> Python: Add numpy as extras_require dependency (fixes #2158)

- gdal/ogr/ogrsf_frmts/flatgeobuf/ogr_flatgeobuf.h
- gdal/ogr/ogrsf_frmts/flatgeobuf/ogrflatgeobuflayer.cpp
- Also avoid a potential issue if ensureFeatureBuf() would fail, and
further GetNextFeature() would be done. The new size would have been
prematurely set to m_featureBufSize
- Some added comments
> FlatGeobuf: validate feature size against file size if > 100 MB and < 2 GB.

- gdal/doc/source/drivers/vector/flatgeobuf.rst
- gdal/ogr/ogrsf_frmts/flatgeobuf/ogr_flatgeobuf.h
- gdal/ogr/ogrsf_frmts/flatgeobuf/ogrflatgeobufdataset.cpp
- gdal/ogr/ogrsf_frmts/flatgeobuf/ogrflatgeobuflayer.cpp
Fixes #2287
- add a TEMPORARY_DIR layer creation option
- write final file in a batch way to minimize switches between reads and writes
In the example mentionned in #2287, conversion time is now:
- 4m24 when using -lco TEMPORARY_DIR=/vsimem/
- 5m15 without option (vs presumably several hours before)
> Flatgeobuf write performance improvements

- autotest/utilities/test_gdal_viewshed.py
- gdal/alg/gdal_alg.h
- gdal/alg/viewshed.cpp
- gdal/apps/gdal_viewshed.cpp
- gdal/doc/source/programs/gdal_viewshed.rst
- gdal/swig/include/Operations.i
- gdal/swig/python/extensions/gdal_wrap.cpp
- gdal/swig/python/osgeo/gdal.py
By setting the MINIMUM_HEIGHT extra argument GDALViewshedGenerate can also return a raster containing the minimum height from either ground level or the DEM surface in order for it to be visible.
> Added more functionality to GDALViewshedGenerate

- autotest/pyscripts/test_gdal_edit.py
- gdal/NEWS
- gdal/doc/source/programs/gdal_edit.rst
- gdal/scripts/gdal-bash-completion.sh
- gdal/swig/python/scripts/gdal_edit.py
Assign/override the georeferenced bounds of the dataset from three points: upper-left, upper-right and lower-left. Unlike option `-a_ullr`, this also supports rotated datasets (edges not parallel to coordinate system axes).
> gdal_edit.py: add -a_ulurll switch

- autotest/gcore/vsiswift.py
- gdal/doc/source/user/virtual_file_systems.rst
- gdal/port/cpl_swift.cpp
- gdal/port/cpl_swift.h
- gdal/port/cpl_vsil_curl.cpp
- gdal/port/cpl_vsil_curl_class.h
- gdal/port/cpl_vsil_swift.cpp
Addresses https://github.com/OSGeo/gdal/issues/2239.
Implements re-issue of the auth token when expired. To allow the re-issue, `GDAL_HTTP_MAX_RETRY` needs to be set at least to `1`.
Adds authentication using OpenStack Identity API v3. It might not be complete implementation. I have implemented it to the extent I was able to connect to a Swift instance I have access to.
> /vsiswift/: V3 authentication method, handling auth token expiration

- autotest/ogr/ogr_mysql.py
AutoTest writing and reading back geometries by get_wkt_data_series() for MySQL.
It succeeded with MySQL 8 but  fails with MariaDB.
#2130 
MariaDB
> MySQL/MariaDB: test with wkt data series

- autotest/gcore/numpy_rw.py
- gdal/swig/include/gdal_array.i
- gdal/swig/python/extensions/gdal_array_wrap.cpp
Fixes issue reported in https://lists.osgeo.org/pipermail/gdal-dev/2020-March/051817.html
> NUMPYDataset::Open() / gdal_array.OpenArray(): honour writeable flag of the numpy array to decide if the GDAL dataset is read-only or updateable

- gdal/doc/source/drivers/vector/vrt.rst
Mismatched tag for VRT - `<SrcLayer>` was ended with `</SrcSQL>` causing issues when copying and pasting
> Docs: Fix incorect name of VRT XML element

- autotest/ogr/ogr_elasticsearch.py
- gdal/doc/source/drivers/vector/elasticsearch.rst
- gdal/ogr/ogrsf_frmts/elastic/ogr_elastic.h
- gdal/ogr/ogrsf_frmts/elastic/ogrelasticdatasource.cpp
- gdal/ogr/ogrsf_frmts/elastic/ogrelasticdriver.cpp
- gdal/ogr/ogrsf_frmts/elastic/ogrelasticlayer.cpp
This PR updates point layer creation of geometry objects with `Point` instead of `POINT`.
In addition, while ES support is going through breaking changes in GDAL 3.1.x, renaming the driver name to `Elasticsearch` for consistency.
- https://github.com/geopython/pygeoapi/pull/385#issuecomment-603290464
* OS: Ubuntu bionic
> Elasticsearch: rename driver to Elasticsearch, update geometry type name for Points

- gdal/doc/source/drivers/raster/grib.rst
Links have moved and are pointing now to the correct URL again.
Did a search and replace for the missing URL part. Apparently NCEP has moved everything one level down from `docs/grib2` to `docs/grib2/grib2_doc/`
> Docs: Update grib.rst links to NCEP documentation

- autotest/pyscripts/test_gdal2tiles.py
- gdal/doc/source/programs/gdal2tiles.rst
- gdal/swig/python/scripts/gdal2tiles.py
Added new `--xyz` option to generate tiles in the [OSM Slippy Map standard](https://wiki.openstreetmap.org/wiki/Slippy_Map) where the `Y` coordinate is flipped.
Also fixed incorrect indentation in a few places.
Fixes #2098
> gdal2tiles.py: Added support for XYZ tiles (OSM Slippy Map)

- gdal/frmts/kea/keaband.cpp
- gdal/frmts/kea/keaband.h
- gdal/frmts/kea/keadataset.cpp
- gdal/frmts/kea/keadataset.h
- gdal/frmts/kea/keamaskband.cpp
- gdal/frmts/kea/keamaskband.h
- gdal/frmts/kea/keaoverview.cpp
- gdal/frmts/kea/keaoverview.h
- gdal/frmts/kea/kearat.cpp
- gdal/frmts/kea/kearat.h
Ports fixes from kealib 1.4.13's standalone driver. These include:
- Locks around internal data structures for thread safety
- Checking the result of GetDefaultRAT() as this can be `nullptr` in certain circumstances (generally partially corrupt files)
Relevant changes from `kealib` are in the `gdal` subdir files from: https://github.com/ubarsc/kealib/compare/190ef7a..HEAD
Note: `kealib` 1.4.13 now prints a warning if being compiled against an `hdf5` that **isn't** thread safe.
* OS:
* Compiler:
> KEA: Backport thread safety fixes and nullptr tests from standalone driver

- autotest/cpp/test_osr.cpp
- autotest/gcore/tiff_srs.py
- gdal/frmts/gtiff/gt_wkt_srs.cpp
- gdal/ogr/ogr_spatialref.h
- gdal/ogr/ogrsf_frmts/gpkg/ogrgeopackagedatasource.cpp
- gdal/ogr/ogrsf_frmts/sqlite/ogrsqlitedatasource.cpp
- gdal/ogr/ogrspatialreference.cpp
Addresses https://github.com/qgis/QGIS/issues/34993
Implements a simplified version of the idea mentioned in
https://lists.osgeo.org/pipermail/gdal-dev/2020-March/051881.html
with a variant of the more radical approach suggested in
https://lists.osgeo.org/pipermail/gdal-dev/2020-March/051885.html
That is the new method OGRSpatialReference::StripTOWGS84IfKnownDatumAndAllowed()
will remove TOWGS84 information from SRS whose datum name is known,
unless the OSR_STRIP_TOWGS84 configuration option is set to NO.
When TOWGS84 information is striped, a debug message is emitted.
> Strip TOWGS84 when datum is known, in GTiff, Spatialite and GPKG drivers

- gdal/doc/source/drivers/raster/vrt.rst
…te in GCPList element
Update VRT driver documentation to indicate dataAxisToSRSAxisMapping is a valid attribute with identical format and meaning as SRS element.
#2378 (already marked as closed)
* OS: 
* Compiler:
> vrt.rst: update GCPList element to include dataAxisToSRSAxisMapping attribute #2378

- gdal/doc/source/conf.py
The copyright year is still showing 2019. Let's welcome 2020.
> Docs: Update copyright year in site footer

- gdal/ogr/ogrsf_frmts/vfk/vfkdatablock.cpp
- gdal/ogr/ogrsf_frmts/vfk/vfkdatablocksqlite.cpp
- gdal/ogr/ogrsf_frmts/vfk/vfkreader.h
This should end fixing the issue raised in
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=16309 where a corrupted
.vfk files with a lot of line strings takes a long time to process.
The speed-up comes from using a hash map to map from a ring-in-building end
point to the ring, instead of iterating. This speeds up the reconstruction in
that case from ~20s to ~2s
@landam Could you review this and tests this work as expected with real datasets ?
> VFK: use a faster implementation of VFKDataBlockSQLite::LoadGeometryPolygon()

- gdal/frmts/tiledb/tiledbdataset.cpp
When creating a TileDB array global order is used for performance, if the file is large and exceeds `GDAL_CACHEMAX` then the tiles can be written out of order in `TileDBRasterBand::IWriteBlock`.
This PR uses `BlockBasedFlushCache` and checks the tile order on global writes.
This is an internal change and the related issue is https://github.com/TileDB-Inc/TileDB-Geospatial/issues/7
> Flush cache in block order for TileDB global writes

- autotest/cpp/testblockcachewrite.cpp
-  support out-of-source build and test.
Current test-block-cache-write test use relative path from in-source directory.
This patch allow out-of-source build and test using definition of test_data.h 
N.A.
> test: indirect data path

- gdal/doc/source/community.rst
As it looks like #gdal on Freenode restricts voice to
registered users..
> Add instructions to register nickname with Freenode

- gdal/frmts/tiledb/tiledbdataset.cpp
- gdal/gcore/gdal_priv.h
- gdal/gcore/gdaldataset.cpp
- gdal/gcore/gdaldriver.cpp
This PR provides compatiblity with the `vsis3` prefix used in Rasterio. It also provides a fix for setting the metadata in FlushCache when using s3.
As TileDB can perform updates directly on s3 I removed the error check in `vsicurl`, if this should be retained then I can make the changes required to add a conditional compilation.
I was testing with Rasterio so I haven't added a GDAL specific test case here.
> vsis3 compatibility

- gdal/frmts/tiledb/tiledbdataset.cpp
This is a bug I noticed when compiling GDAL with the TileDB dev branch (which is set to 2.0). It doesn't impact user functionality as metadata storage is an internal feature.
> For TileDB 1.7 or greater enable use of internal metadata

- gdal/docker/alpine-normal/Dockerfile
- gdal/docker/alpine-small/Dockerfile
- gdal/docker/alpine-ultrasmall/Dockerfile
- gdal/docker/ubuntu-full/Dockerfile
- gdal/docker/ubuntu-small/Dockerfile
Use `LABEL` instruction instead of deprecated `MAINTAINER` in Dockerfiles
Reasoning:
https://docs.docker.com/engine/reference/builder/#maintainer-deprecated
> The MAINTAINER instruction sets the Author field of the generated images. The LABEL instruction is a much more flexible version of this and you should use it instead, as it enables setting any metadata you require, and can be viewed easily, for example with docker inspect. To set a label corresponding to the MAINTAINER field you could use:
`LABEL maintainer="SvenDowideit@home.org.au"`
This will then be visible from docker inspect with the other labels.
> Use LABEL instead of deprecated MAINTAINER

- gdal/frmts/dted/dteddataset.cpp
DTED: Adds EGM96 (DTED_VerticalDatum=E96) in addition to MSL for COMPD_CS support
> DTED: Add support for E96 DTED files for COMPD_CS 

- autotest/gdrivers/bag.py
- gdal/frmts/hdf5/bagdataset.cpp
BAG XML metadata schema has been modified with version 1.5; actually, GDAL only handles latest format, this pull request proposes to handle backward compatibility (from 1.0 to 1.6 versions)
> Backward compatibility for BAG metadata reading

- autotest/gdrivers/grib.py
- autotest/gdrivers/netcdf.py
- gdal/frmts/netcdf/netcdfdataset.cpp
- gdal/ogr/ogr_spatialref.h
- gdal/ogr/ogr_srs_api.h
- gdal/ogr/ogrct.cpp
- gdal/ogr/ogrspatialreference.cpp
- gdal/swig/include/osr.i
- gdal/swig/python/extensions/osr_wrap.cpp
- gdal/swig/python/osgeo/osr.py
Contributes to fixing issue raised in
https://lists.osgeo.org/pipermail/gdal-dev/2020-April/052003.html
Best used in combination with https://github.com/OSGeo/PROJ/pull/2185
but should also work without it.
> Fix support of WKT1_GDAL with netCDF rotated pole formulation

- autotest/gcore/tiff_read.py
- autotest/gdrivers/jpeg.py
- gdal/frmts/gtiff/libtiff/tif_jpeg.c
- gdal/frmts/jpeg/jpgdataset.cpp
to allow up to the limit set by JPEGMEM (500 MB) instead of a 100 MB limit (fixes for o17855_k004.jpg of https://github.com/qgis/QGIS/issues/35957 and should also address https://github.com/qgis/QGIS/issues/35982 for most cases)
> JPEG: tune sanity check for multiple-scan images

- gdal/ogr/ogrsf_frmts/flatgeobuf/geometryreader.cpp
ref https://github.com/OSGeo/gdal/issues/2459
I'm not sure this is the correct fix though and wonder why the other similar cases are slightly different (the ->toCurve ones).
> FlatGeobuf: add null check for readMultiPolygon

- gdal/gcore/gdaldataset.cpp
Fix wrong IO of subpixel shifted window when buffer size is equal to window size and image has pixel interleaving (fixes #2507).
This case cannot be tested using current autotests because python dataset.ReadRaster() does not support subpixel shifts.
Given GeoTIFF with ```INTERLEAVE=PIXEL```. Try to read buffer shifted by 0.5 pixels:
```c++
int bufferSize = 100;
GDALRasterIOExtraArg args;
INIT_RASTERIO_EXTRA_ARG(args);
args.eResampleAlg = GRIORA_Bilinear;
args.bFloatingPointWindowValidity = true;
args.dfXOff = 0.5;
args.dfYOff = 0.5;
args.dfXSize = bufferSize;
args.dfYSize = bufferSize;
dataset->RasterIO(GF_Read, 0, 0, bufferSize, bufferSize, buffer, bufferSize, bufferSize, GDT_Byte, 3, nullptr, 0, 0, 0, &args);
```
Expected (when using band interleaving image)
Got
> Fix wrong IO of subpixel shifted window

- gdal/swig/python/setup.py
The Python 2 install uses ThreadedPoolExecutor.map() which returns an iterator.
That iterator needs to be consumed else errors are not reported and the module
install process does not wait for modules to be compiled.
Fixes #2515
* OS: windows
* Compiler: msvc
> Fix Python2 install to be synchronous and report all errors

- gdal/ogr/ogrsf_frmts/gml/xercesc_headers.h
- gdal/ogr/ogrsf_frmts/gmlas/xercesc_headers.h
- gdal/ogr/ogrsf_frmts/ili/xercesc_headers.h
There had been INFINITY definition in Xerces-C long time ago.
It had been removed in May 2002.
https://github.com/apache/xerces-c/commit/15272ee3c915c49c73695c3532a0313979b6b841
* OS: mac os x
* Compiler: clang
In file included from /Users/runner/runners/2.169.1/work/cmake4gdal/cmake4gdal/gdal/gdal/gcore/gdal_priv.h:69:
/Applications/Xcode_11.4.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:661:56: error: use of undeclared identifier 'INFINITY_XERCES'
if (__r >= ::nextafter(static_cast<_RealT>(_MaxVal), INFINITY)) {
The error can be observed in my private build experiment with cmake only.
> Drop dead code block

- gdal/doc/source/programs/gdalsrsinfo.rst
Also removed unneeded quote from command line.
You are welcome to adjust the rest of the examples.
> Make output more match current relaity

- gdal/apps/ogr2ogr_bin.cpp
Running `ogr2ogr --long-usage` currently generates output like this:
```
...
-fieldmap index1,index2,...: Specifies the list of field indexes to be
copied from the source to the destination. The (n)th value specified
in the list is the index of the field in the target layer definition
in which the n(th) field of the source layer must be copied. Index count
starts at zero. There must be exactly as many values in the list as
the count of the fields in the source layer. We can use the 'identity'
setting to specify that the fields should be transferred by using the
same order. This setting should be used along with the append setting. -a_srs srs_def: Assign an output SRS
-t_srs srs_def: Reproject/transform to this SRS on output
-s_srs srs_def: Override source SRS
...
```
This change is to get …
> Add missing line feed

- gdal/ogr/ogrsf_frmts/ili/ili2reader.h
Missing patch for #2532
#2532 is incompleted (sorry). Here is another part of dead block.
There had been INFINITY definition in Xerces-C long time ago.
It had been removed in May 2002.
apache/xerces-c@15272ee
#2532
> Drop deprecated INFINITY_XERCES definition

- gdal/frmts/tiledb/tiledbdataset.cpp
This is a check that the returned metadata is truncated if necessary to provide a valid XML string for metadata parsing in GDAL. By not using the returned `v_num` we could potentially have an invalid XML string. 
Can we backport this on to v3.1?
> use returned length to truncate string for tiledb metadata

- gdal/GNUmakefile
Splits the $(LIBGDAL) call in GNUmakefile across several lines.  
Otherwise it can exceed the 32,000 character limit on MSYS2 and similar systems.
#2077 helps in many cases, but is still not sufficient when there are many files to be compiled in.  
This should also be a more robust fix for #1429 
* OS:  Windows with MSYS2/MSYS/Cygwin or similar
* Compiler:  gcc 7.1.0
> GNUmakefile: split long line

- gdal/alg/gdalwarper.h
- gdal/frmts/vrt/vrtwarped.cpp
This function allows specifying extra options for transformer.
Thanks to that, it is for example possible to set RPC_HEIGHT
to get better aligned rasters with RPC georeferencing metadata.
Originally suggested by Even in https://github.com/qgis/QGIS/pull/36385
> Add GDALAutoCreateWarpedVRTEx function to GDAL API

- autotest/ogr/ogr_mvt.py
- gdal/ogr/ogrsf_frmts/mvt/ogrmvtdataset.cpp
by sorting sub-directory names, and also revise logic to attribute FID when reading directories
> MVT: fix 'random' failures in test_ogr_mvt_point_polygon_clip()

- autotest/ogr/ogr_shape.py
- gdal/ogr/ogrsf_frmts/shape/ogrshapedatasource.cpp
that should hopefully fix random hangs on test_ogr_shape_115_shp_zip()
> OGRShapeDataSource::RefreshLockFile(): fix threading issue

- autotest/ogr/ogr_sql_test.py
- gdal/ogr/swq_op_general.cpp
Second part of arithmetic expression were not taken into account for type conversion, leading to calculus errors. 
This example returned bad result
```shell
$ ogrinfo -sql "select cast((1) as integer)/1.  from division" division_shp/division.shp
...
OGRFeature(division):0
FIELD_1 (Integer) = 0
$ ogrinfo -sql "select (1*1)/1.  from division" division_shp/division.shp
...
OGRFeature(division):0
FIELD_1 (Integer) = 0
```
This fixes the following QGIS issue https://github.com/qgis/QGIS/issues/35449
* OS: Debian 10
* Compiler: gcc 9.2.1
> swq_op_general.cpp: Fix arithmetic expression

- autotest/ogr/ogr_mitab.py
- gdal/ogr/ogrsf_frmts/mitab/mitab_spatialref.cpp
On reading, the SRS_PT_TRANSVERSE_MERCATOR_MI_21/_22/_23_/_24 special cases
are redirected on standard Transverse Mercator
On writing, if Tranverse Mercator + datum = KKJ, use the 24 projection code
> MITAB: fix reading and writing of Transverse Mercator projections based on KKJ

- gdal/configure
- gdal/configure.ac
Change the order of checks in configure.ac so that by the time the checks for proj are performed the dependencies of proj are already in LIBS. With this approach it is sure that the libraries provided to configure through the `--with-*` flags are also used in the attempt to link with proj.
I am aware of `--with-proj-extra-lib-for-test` in 3.1 but I thought that this approach would lead to less repetition in the call to `configure` and be more consistent.
Addresses #2511.
Evidently I have not tested all possible combinations, does the CI cover enough cases to be confident about the change?
Same as described in #2511.
There is a similar PR for master in https://github.com/OSGeo/gdal/pull/2513
> configure.ac: Configure proj dependencies before proj (master)

- .travis.yml
- enable commit notifications to dedicated IRC channel "gdal-activity"
- this follows how other projects handle this as QGIS, PostGIS (pushing commit notifications into dedicated <PROJECT>-activity channel, so packagers and developers get notices of changes, if they wish).
@rouault has also been set as founder of the new activity channel.
> enable commit notifications to dedicated #gdal-activity IRC channel

- gdal/alg/gdalwarper.h
QGIS builds on windows were failing when trying to use the newly added GDALAutoCreateWarpedVRTEx function. Only now I have realized I have missed to add CPL_DLL to the header, causing the linker to complain about unresolved external symbol GDALAutoCreateWarpedVRTEx
https://cdash.orfeo-toolbox.org/viewBuildError.php?buildid=42309
> Add missing CPL_DLL to GDALAutoCreateWarpedVRTEx

- gdal/ogr/ogrspatialreference.cpp
Fixes documentation in two functions of OGRSpatialReference.
Looking at the code of `GetAxis`, I understand that it works also for iAxis=2. Documentation seems to be obsolete (and gives the impression you cannot get the third axis).
Documentation of `exportToPROJJSON` seems to be a copy-paste.
Note: `SetAxes` only accepts `X` and `Y`. What if I want to set `Z`?
> fix documentation of exportToPROJJSON and GetAxis of OGRSpatialReference

- autotest/gcore/rasterio.py
- gdal/gcore/gdal.h
- gdal/swig/include/gdal.i
- gdal/swig/include/gdal_array.i
- gdal/swig/include/python/gdal_python.i
- gdal/swig/python/extensions/gdal_array_wrap.cpp
- gdal/swig/python/extensions/gdal_wrap.cpp
(fixes for GDAL bindings similar issue reported in refs #2587)
> SWIG bindings: validate range of resample_alg algorithm

- gdal/gcore/gdaldataset.cpp
Fixed buffer overflow in GDALDataset::BuildParseInfo for SQL query when joining multiple tables that each have FID columns. An ESRI FileGDB dataset was crashing with a heap error: each table had "OBJECTID" for poSrcLayer->GetFIDColumn().
Previously, buffers for psParseInfo->sFieldList were allocated to (nFieldCount + SPECIAL_FIELD_COUNT + 1), where the '+1' seemed to be assuming a single FID column (added at the bottom of the function). This buffer was overrun when multiple tables each had such an FID column.
This fix increments the nFieldCount for each table that has a qualifying FID column, and removes the +1 on the buffer allocation.
> GDALDataset: Fix buffer overflow in BuildParseInfo for SQL query

- gdal/ogr/ogrsf_frmts/flatgeobuf/ogrflatgeobuflayer.cpp
This change allowed me to compile with VS 2019, build toolset 1926.
* OS:
* Compiler:
> Fix runtime_error is not a member of std

- gdal/data/osmconf.ini
- gdal/ogr/ogrsf_frmts/osm/ogr_osm.h
- gdal/ogr/ogrsf_frmts/osm/ogrosmdatasource.cpp
This series of commit provides two ways of customizing the early dropping of some tags:
- Disable the dropping globally, by enabling `report_all_tags` in `osmconf.ini`.
This is in analogy to the existing `report_all_nodes` and `report_all_ways`. However, the per-type `ignore` continue to remove the tags they list.
- Disable the early dropping for attributes which are listed in the per-type `attribute` list. This fixes a surprising behaviour that some tags simply didn't work in the attribute list. However, the new behaviour means that a key listed as an `attribute`for just one type now is also handled for the other types, either by the other types' `ignore` and `attribute` lists, or appearing in `other_tags` or `all_tags`.
The variable of globally ignored keys is explicitly chosen as …
> OSM: Fix tag filtering inconsistencies

- gdal/data/osmconf.ini
This PR does not change any behaviour, but rectifies the documentation and default setup of the `attribute_name_laundering` option in `osmconf.ini`. Attribute name laundering is enabled by default:
https://github.com/OSGeo/gdal/blob/0452e8c57913f4744c3e704077f33310f91e3d86/gdal/ogr/ogrsf_frmts/osm/ogrosmdatasource.cpp#L265
Commenting, i.e. not providing, the parameter doesn't change the default. So attribute name laundering needs to be explicitly disabled in `osmconf.ini` if desired.
> OSM: Rectify attribute_name_laundering option

- gdal/alg/viewshed.cpp
In the pixel-is-area convention used by GDAL, floor'ing
is the appropriate rounding mode.
> Viewshed: adjust computation of observer position (refs #2599)

- gdal/alg/gdalsievefilter.cpp
- gdal/doc/source/programs/gdal_sieve.rst
- gdal/swig/java/javadoc.java
Corrects a typo in gdal_sieve docstring
* OS:
* Compiler:
> Fix docstring typo in gdal_sieve

- autotest/ogr/data/lvbag/inval_pnd.xml
- autotest/ogr/ogr_lvbag.py
- gdal/doc/source/drivers/vector/lvbag.rst
- gdal/ogr/ogrsf_frmts/lvbag/ogr_lvbag.h
- gdal/ogr/ogrsf_frmts/lvbag/ogrlvbagdatasource.cpp
- gdal/ogr/ogrsf_frmts/lvbag/ogrlvbagdriver.cpp
- gdal/ogr/ogrsf_frmts/lvbag/ogrlvbaglayer.cpp
Issue: https://github.com/OSGeo/gdal/issues/2615
Parsing should not be able to continue once an error occurred in the process. Feature building will need the layer definition at some point. Check if the layer definition is complete, if not the try once and then fail (`GetNextFeature()`). We cannot rely on the forward parsing pass to build the layer definition when features are requested as done in the previous version.
> FIX: Continue after error in parsing document

- gdal/ogr/ogrsf_frmts/shape/ogrshape.h
Many methods are marked as `virtual` within `OGRShapeLayer`. Is this pure for readability? If not they can all be removed, like this protected keyword. The class is marked final.
> OGRShapeLayer is final, cannot inherit

- gdal/frmts/postgisraster/postgisrasterdataset.cpp
- gdal/ogr/ogrsf_frmts/pg/ogrpgdatasource.cpp
If the application name is not set in the connection string then set the application name to the current GDAL version. PostgreSQL connections can take a long time before they are closed and they do show up in the database session list. Being able to identify database sessions makes diagnostics easier.
Ran valgrind, no mem leaks.
> Set the application name in PostgreSQL connections

- gdal/ci/travis/osx/script.sh
- gdal/ci/travis/python3/script.sh
- gdal/ci/travis/trusty_clang/script.sh
I noticed that a lot of the CI tests are using `GDAL_SKIP JP2ECW`, so this is just a test to see what happens when this is removed.
Edit: I'm still not entirely sure what this controls, but it appears that this is no longer needed in most cases.
> Remove GDAL_SKIP=JP2ECW, see how CI reacts

- gdal/doc/source/drivers/vector/vrt.rst
I added spaces to fix indenting and and removed unneeded line feeds from the ODBC Point Layer example to make it consistent with the other examples.
> Fix indenting in VRT doc

- gdal/port/cpl_port.h
For Visual Studio if GDAL is a shared library, this PR avoids defining `CPL_DLL` as `__declspec(dllexport)` when consumers use GDAL library (and therefore prevents from a lot of C4251 warnings).
Thereby, if GDAL is shared and compiled with Visual Studio, `CPL_DLL` is defined as :
- `__declspec(dllexport)` at compile time
- empty for consumers
Notes:
- `CPL_DLL` should be `__declspec(dllimport)` at consume time, but it also generates warnings due to stl classes exposed in public GDAL classes. `CPL_DLL` defined as empty is fine because GDAL doesn't have global variables in public headers.
- In this PR, GDAL executables are also built with `CPL_DLL` as `__declspec(dllexport)` (same behaviour than before) which is not very neat, but works (without warnings because C4251 is disabled in nmake …
> Fix warning C4251 if Visual Studio and shared for consumers of gdal lib

- autotest/gcore/transformer.py
- autotest/osr/osr_ct.py
- autotest/utilities/test_gdalwarp_lib.py
- gdal/alg/gdaltransformer.cpp
- gdal/ogr/ogrct.cpp
> gdalwarp: fix crash if warping a dataset without source or target CRSwhen -ct is specified

- autotest/gcore/transformer.py
- gdal/alg/gdal_rpc.cpp
New option `RPC_DEM_SRS`  for `GDALCreateRPCTransformer`, which can be used analogously to `SRC_SRS` or `DST_SRS` in `GDALCreateGenImgProjTransformer2`. This can be useful in cases where a DEM supplied to `RPC_DEM` does not have an explicit vertical SRS so height values sampled from the DEM are not transformed to be relative to the WGS84 ellipsoid. Previously, one workaround to this was to simply provide a VRT with the correct (explicit) SRS to `RPC_DEM`. 
I've checked with `valgrind --leak-check=yes echo "0 0" | gdaltransform -rpc -to RPC_DEM_SRS="EPSG:4326+5773" -to RPC_DEM=/path/to/dem.tif /path/to/image.tif` and there didn't seem to be any immediate issues.
* OS: WSL 2 Ubuntu 20.04
* PROJ: 7.0.1
> RPC_DEM_SRS option for GDALCreateRPCTransformer to override SRS of RPC_DEM.

- autotest/ogr/ogr_s57.py
- gdal/doc/source/drivers/vector/s57.rst
- gdal/ogr/ogrsf_frmts/s57/ogrs57datasource.cpp
- gdal/ogr/ogrsf_frmts/s57/ogrs57driver.cpp
- gdal/ogr/ogrsf_frmts/s57/s57.h
- gdal/ogr/ogrsf_frmts/s57/s57featuredefns.cpp
- gdal/ogr/ogrsf_frmts/s57/s57reader.cpp
- gdal/ogr/ogrsf_frmts/s57/s57writer.cpp
Add a LIST_AS_STRINGLIST open option that can be set to OFF to restore GDAL < 3.2 behaviour 
(fixes #2660)
> S57: report attributes tagged as list in S57 dictionaries as StringList fields

- gdal/apps/gdal_rasterize_lib.cpp
When a "-ts 0 0" parameter is used with gdal_rasterize, then the following error is displayed:
"ERROR : Wrong value for -outsize parameter."
Since the "-outsize" parameter is not documented, the user cannot understand which parameter is wrong.
This PR changes the error string to a meaningful one: "ERROR : Wrong value for -ts parameter."
> Fix an error string in gdal_rasterize

- gdal/generate_vcxproj.bat
- gdal/nmake.opt
Add vs2019 compatibility
vcver is 16.0, for v142 toolset
added a VSFRIENDLYVERSION to nmake.opt to help using dependencies built with different versions of VS
address #2676
> Add vs2019 compatibility

- gdal/docker/ubuntu-full/Dockerfile
- gdal/docker/ubuntu-full/bh-gdal.sh
- gdal/docker/ubuntu-full/bh-proj.sh
- gdal/docker/util.sh
Enable debug symbols in "ubuntu-full" docker images for Proj and GDAL non-release builds. This allows easier issue reproduction against master.
* debug symbols are in external files to minimise process memory
* symbols included for proj & gdal
* enable via `--with-debug-symbols/--without-debug-symbols` argument to build scripts
* included by default for non-release builds
* adds about 200MB to the image size
**Note:** Currently only applies to ubuntu-full, if there's interest could expand it to other image flavours.
I also simplified the ubuntu-full Dockerfile by moving proj & gdal builds to scripts, and added some more command safety: mostly driven by shellcheck and changing `;` → `&&` for consecutive commands.
Todo:
> docker: optionally package with debug symbols

- autotest/postinstall/README.md
- autotest/postinstall/test_c/Makefile
- autotest/postinstall/test_c/test_c.c
- autotest/postinstall/test_cpp/Makefile
- autotest/postinstall/test_cpp/test_cpp.cpp
- autotest/postinstall/test_pkg-config.sh
- gdal/ci/travis/osx/install.sh
- gdal/ci/travis/ubuntu_1804/install.sh
This PR adds some post-install tests that check to build C and C++ apps that link to an installed version of libgdal.
pkg-config is also tested, to ensure the correct include and library paths are provided.
This test suite currently only works for *nix.
A running example looks like:
```
$ ./gdal/autotest/postinstall/test_pkg-config.sh /tmp/gdal/prefix
Running post-install tests with pkg-config
Testing C app
rm -f test_c test_c.o
cc -g -Wall -Werror -I/tmp/gdal/prefix/include   -c -o test_c.o test_c.c
cc -o test_c test_c.o -L/tmp/gdal/prefix/lib -lgdal
Testing expected ldd output ... passed
Testing expected version ... passed
rm -f test_c test_c.o
Testing C++ app
rm -f test_cpp test_cpp.o
g++ -std=c++11 -g -Wall -Werror -I/tmp/gdal/prefix/include   -c -o test_cpp.o test_cpp.cpp
g++ -o …
```
> Add post-install tests to build apps using gdal.h with pkg-config

- gdal/doc/source/api/cpl.rst
- gdal/doc/source/api/cpl_cpp.rst
- gdal/doc/source/api/index.rst
The Common Portability Library is primarily a C API, however there are currently two C++ API components. This PR splits these off the C API section, and into a renamed "Miscellaneous C++ API" section.
Here is the HTML output from these changes in the TOC:
> Doc: split Common Portability Library C++ API

- autotest/gdrivers/tiledb_write.py
- gdal/frmts/tiledb/tiledb_headers.h
- gdal/frmts/tiledb/tiledbdataset.cpp
The previous TileDB driver supported indexing an image by band, however a user may wish to use pixel interleave format. In addition with TileDB support multiple attributes per location in an image they may wish to collapse the band dimension and have the values represented solely by attributes.
This PR maintains the existing support for a pixel value in a separate band but also adds support for interleave and multiple attributes per location.
* OS:
* Compiler:
> TileDB support for pixel interleave and single formats

- autotest/ogr/data/lvbag/inval_polygon.xml
- autotest/ogr/ogr_lvbag.py
- gdal/doc/source/drivers/vector/lvbag.rst
- gdal/ogr/ogrsf_frmts/lvbag/GNUmakefile
- gdal/ogr/ogrsf_frmts/lvbag/makefile.vc
- gdal/ogr/ogrsf_frmts/lvbag/ogr_lvbag.h
- gdal/ogr/ogrsf_frmts/lvbag/ogrlvbagdatasource.cpp
- gdal/ogr/ogrsf_frmts/lvbag/ogrlvbagdriver.cpp
- gdal/ogr/ogrsf_frmts/lvbag/ogrlvbaglayer.cpp
Many bugfixes and improvements for the LVBAG driver
- FIX: Remove unionized source layers from the dataset _after_ unioning is done
- Rewrite code to use the internal C++11 memory functions
- Make nMaxSimultaneouslyOpened configurable for testing
- FIX: Parse year as Date type
- Add SRS/Geom type based on dataset name and LVBAG 2.0 kadaster specification
- Fit invalid data if possible
- Set invalid dates to null
Fixes: https://github.com/OSGeo/gdal/issues/2707
Fixes: https://github.com/OSGeo/gdal/issues/2636
> LVBAG; bugfixes and improvements

- autotest/cpp/test_osr_set_proj_search_paths.cpp
- gdal/ogr/ogr_proj_p.cpp
Fix a bug affecting PostGIS raster (#2744), and much likely GMT
(https://lists.osgeo.org/pipermail/gdal-dev/2020-July/052381.html)
If OSRCleanup() was called, deinit() was called on the
current OSRPJContextHolder object, but due to https://github.com/OSGeo/gdal/commit/e873aa230b2f960b9d5076d3849870c00387f096
that removed init(), the PROJ context was let at nullptr if
OSRGetProjTLSContext() was called afterwards. This could result
in a crash in PROJ due to a bug into it, for example if OGRSpatialReference::Clone()
was called , or more subtely to potential thread issues if OSRCleanup()
would be called in several threads using OSR API (due to the default nullptr
PROJ context being used concurrently)
> OSR: fix issue with PROJ context and OSRCleanup() (fixes #2744)

- autotest/utilities/test_gdalinfo_lib.py
- gdal/swig/include/python/gdal_python.i
- gdal/swig/python/osgeo/gdal.py
The python gdalinfo call should be able to accept cli-style args as either a string or a list of strings. However, in order to return results in json format, the format arg must be explicitly set. This happens when providing a single string of arguments for options but NOT for a list of strings.
This fixes the issue by setting format directly, checking if '-json' is in new_options (allowing it to be set directly with the format option or to be an option in a string list) and modifies/adds tests to confirm that it works properly. The fix was made to the swig interface and includes the resulting gdal.py
Test case added that would fail with the old setup but works now: https://github.com/OSGeo/gdal/commit/fa7ba8d3ae0c7d27c7848038b88d0ad376ee22a7#diff-4af94d498c1e509ba178f04b7758bedeR133-R137 …
> gdalinfo: allow list of cli-style string 

- autotest/gcore/vsis3.py
- gdal/port/cpl_json.cpp
- gdal/port/cpl_json.h
- gdal/port/cpl_vsi.h
- gdal/port/cpl_vsil_az.cpp
- gdal/port/cpl_vsil_curl.cpp
- gdal/port/cpl_vsil_curl_class.h
- gdal/port/cpl_vsil_s3.cpp
- gdal/port/cpl_vsil_webhdfs.cpp
- gdal/swig/include/cpl.i
- gdal/swig/python/extensions/gdal_wrap.cpp
- gdal/swig/python/osgeo/gdal.py
* Add VSINetworkStatsGetAsSerializedJSON() to return collected
statistics as a JSON serialized string
e.g.
```json
{
"methods": {
"PUT": {
"count": 1,
"uploaded_bytes": 6
}
},
"handlers": {
"vsis3": {
"files": {
"/vsis3/s3_fake_bucket3/another_file.bin": {
"methods": {
"PUT": {
"count": 1,
"uploaded_bytes": 6
}
},
"actions": {
"Write": {
"methods": {
"PUT": {
"count": 1,
"uploaded_bytes": 6
}
}
}
}
}
},
"methods": {
"PUT": {
"count": 1,
"uploaded_bytes": 6
}
}
}
}
}
```
Statistics collecting should be enabled with the CPL_VSIL_NETWORK_STATS_ENABLED
configuration option set to YES before any network activity starts
(for efficiency, reading it is cached on first access, until VSINetworkStatsReset() is called)
Statistics can also be emitted on standard output at process termination if
the …
> Add logging capabilities for /vsicurl, /vsis3 and the like

- gdal/ogr/ogrsf_frmts/nas/nashandler.cpp
- gdal/ogr/ogrsf_frmts/nas/nasreader.cpp
- gdal/ogr/ogrsf_frmts/nas/nasreaderp.h
With [GeoInfoDok NEU](http://www.adv-online.de/GeoInfoDok/GeoInfoDok-NEU/binarywriterservlet?imgUid=61160780-c5f2-bc61-f27f-31c403b36c4c&uBasVariant=11111111-1111-1111-1111-111111111111) the update mechanism changed.  This PR adds support for those changes.
none
> [NAS] add support for new GID7 updates

- gdal/doc/source/programs/gdal_proximity.rst
- gdal/doc/source/programs/options/ot.rst
- gdal/swig/python/scripts/gdal_proximity.py
Two related but separate documentation edits are done here:
* The general documentation for `-ot` is expanded to the complete list of datatypes supported by GDAL conditioned with "supported by the driver" (I assume the driver will log/raise and exception if a chosen data type is not supported).
* The documentation for `-ot` for `gdal_proximity.py` is detailed separately, as it should recommend a subset of these data types and document the default of Float32. Unsigned integer types should be preferred, since proximity results are positive, so this is reflected in a change with the command usage information.
> DOC: expand general docs for -ot, except gdal_proximity.py [skip ci]

- gdal/ogr/ogrsf_frmts/shape/ogrshapedriver.cpp
Shapefiles support Date, but not DateTime. This is leading to issues like https://github.com/qgis/QGIS/issues/38011 in QGIS.
> ogrshapedriver: do not claim to support DateTime data type

- gdal/configure
- gdal/configure.ac
- gdal/doc/source/drivers/vector/dgnv8.rst
- gdal/doc/source/drivers/vector/dwg.rst
- gdal/doc/source/drivers/vector/index.rst
- gdal/doc/source/drivers/vector/oda.rst
- gdal/ogr/ogrsf_frmts/dwg/GNUmakefile
This PR adds support for current ODA versions. ODA is a proprietary library from [Open Design Alliance](https://www.opendesign.com/products).
The previous [commit](https://github.com/OSGeo/gdal/commit/0b85844a85ddf0feee424fd05f92bc4a3604d577), regarding ODA support has more than 3 years now.
This PR also adds building instructions to compile GDAL/OGR with ODA support.
To compile GDAL with ODA 2021, two ODA libraries are required (Kernel and Drawings). These libraries must be merged and compiled before building GDAL.
```bash
cd ~/dev/cpp/ODA2021.2
mkdir base_7.2
tar xvzf Kernel_lnxX64_7.2dll.tar.gz -C base_7.2
tar xvzf Drawings_lnxX64_7.2dll.tar.gz -C base_7.2
```
To compile, an activation key is required. It can be requested from [ODA Products …
> Adding ODA lib requirements to compile GDAL with ODA 2021

- gdal/configure
- gdal/configure.ac
> Unix build: fix detection of minor version number of Poppler with the new YY.MM.X numbering scheme (fixes #2823)

- autotest/pyscripts/test_gdal2tiles.py
- gdal/data/template_tiles.mapml
- gdal/data/tms_MapML_APSTILE.json
- gdal/data/tms_MapML_CBMTILE.json
- gdal/doc/source/drivers/vector/mapml.rst
- gdal/doc/source/programs/gdal2tiles.rst
- gdal/swig/python/scripts/gdal2tiles.py
Add data/template_tiles.mapml, data/tms_MapML_APSTILE.json and data/tms_MapML_CBMTILE.json
> gdal2tiles: add -w mapml output, and possibilities to use custom tiling scheme / profile

- gdal/ogr/ogrsf_frmts/pgeo/ogrpgeodriver.cpp
- gdal/port/cpl_odbc.cpp
Together these fixes fix the automatic driver installation under linux. (Paired with https://github.com/evanmiller/mdbtools/commit/3517b0eee6383655c85a2c1b7cb3ac6df384cc4f they (kind of, mostly) fix use of the pgeo driver under the linux/unixodbc environment)
> [pgeo] Fixes to automatic ODBC driver installation

- gdal/doc/source/drivers/vector/pg.rst
Relates: https://github.com/OSGeo/gdal/issues/2824
In the last example I changed "poly.shp" into "poly" but I am not sure if was poly.shp intentionally for some reason.
> PG docs: use documented syntax in examples

- autotest/utilities/test_gdal_grid.py
- gdal/apps/gdal_grid_bin.cpp
- gdal/apps/gdal_grid_lib.cpp
- gdal/doc/source/programs/gdal_grid.rst
This pull requests implements the -tr parameter (mentioned here: https://lists.osgeo.org/pipermail/gdal-dev/2020-January/051472.html) to gdal_grid. The code is similar to already existing code in other binaries.
Tests have been added in PyTest, to show the equality of the -outsize and -tr parameter. Also documentation have been edited.
> Addition of -tr option for gdal_grid

- gdal/doc/source/drivers/raster/kea.rst
- the former bitbucket repo points to this newish GH repo: URL update
> libkea repo: new URL

- gdal/doc/source/drivers/vector/odbc.rst
- gdal/ogr/ogrsf_frmts/odbc/ogrodbcdriver.cpp
This works fine, at least with updated versions of mdbtools (and for reference the pgeo and geomedia drivers don't have this ifdef in place)
>  Allow mdb files to be opened with the generic ODBC driver on non-windows systems

- gdal/ogr/ogrsf_frmts/geomedia/ogrgeomedialayer.cpp
- gdal/ogr/ogrsf_frmts/odbc/ogrodbclayer.cpp
- gdal/ogr/ogrsf_frmts/pgeo/ogrpgeolayer.cpp
Avoids forced conversion of these fields to strings
> Correctly handle datetime fields provided by the mdbtools ODBC driver

- gdal/ogr/ogrsf_frmts/odbc/ogrodbcdatasource.cpp
...which causes an error flag to be set and no
alternative drivers to be used to attempt to open a MDB dataset
This breaks the PGEO driver (among others) on Windows, which ultimately
requires an "OGR_SKIP=ODBC" environment variable to be set in order
to read Personal Geodatabases on Windows
Refs:
https://trac.osgeo.org/gdal/ticket/5594#comment:4
https://github.com/qgis/QGIS/issues/20256#issuecomment-495841943
> Fix ODBC driver fails to correctly fallback to alternative Access ODBC driver name

- gdal/data/pdfcomposition.xsd
Makes a minor improvement to the XSD documentation for the PDF Composition XML format. My colleagues and I struggled to get labels working because we didn't realise that any features with a OGR Style String containing a `LABEL` tool needed to be in a separate `<VectorLabel>` element. This adds an extra sentence to the documentation that clarifies this.
None
> Minor improvement to the XSD documentation for PDF Composition

- gdal/frmts/esric/esric/x64/Debug/esric.log
- gdal/frmts/mrf/LERCV1/Lerc1Image.cpp
- gdal/frmts/mrf/LERCV1/Lerc1Image.h
- gdal/frmts/mrf/LERC_band.cpp
- When compressing floating point data, if NAN or INF values are present, LERC compression fails.  This change makes it possible to use LERC 1 with such data, including reading back those non-finite values.
* OS:
* Compiler:
> MRF: LERC V1 support for NaN and other bug fixes

- autotest/ogr/ogr_odbc.py
- gdal/ogr/ogrsf_frmts/geomedia/ogrgeomediadatasource.cpp
- gdal/ogr/ogrsf_frmts/odbc/ogrodbcdatasource.cpp
- gdal/ogr/ogrsf_frmts/pgeo/ogrpgeodatasource.cpp
- gdal/ogr/ogrsf_frmts/walk/ogrwalkdatasource.cpp
- gdal/port/cpl_odbc.cpp
- gdal/port/cpl_odbc.h
The Windows ODBC driver does not like quoted filenames, yet the UnixODBC driver requires these (for filenames with spaces). So
ifdef the expected formats for the corresponding platforms. Follow up https://github.com/OSGeo/gdal/pull/2837
Also flip the order of the candidate DSN string templates, to try the more common/modern "Microsoft Access Driver (*.mdb, *.accdb)" driver name first.
> Fix DSN string construction for Windows Access ODBC driver, template candidate preference order

- gdal/port/cpl_vsi.h
- gdal/port/cpl_vsil_plugin.cpp
This PR adds an option to wrap a plugin handler with `VSICreateCachedFile`
Can/should be backported
Replaces #2817
> VSI Plugin: add caching option

- gdal/swig/csharp/GNUmakefile
- gdal/swig/csharp/makefile.vc
- gdal/swig/include/csharp/typemaps_csharp.i
The existing implementation has shown to corrupt strings when bindings are generated and used with .NET Core.
I'm not sure why the existing implementation seem to work in .NET Framework. It does seem buggy - length is number of characters not bytes.
The proposed implementation in this PR has been verified working in .NET Core but is not verified with .NET Framework but I believe it should work.
> CSharp bindings: Fixed implementation of Utf8BytesToString

- gdal/docker/ubuntu-full/Dockerfile
Requirement for latest TileDB-Py library
Simply bumps the version for TileDB built in the full ubuntu docker image
None to my knowledge
> TileDB: bump tiledb to v2.0.8 for ubuntu full docker image

- gdal/frmts/mrf/mrf_band.cpp
Fix a bug in caching MRF.  If a tile is all no-data, the first band IReadBlock didn't fill the return buffer.
* OS:
* Compiler:
> MRF: missing data return on initial caching of nodata tiles

- gdal/ogr/ogrgeometry.cpp
> fix memory leak in OGRGeometry::Crosses

- autotest/gcore/vrt_read.py
- gdal/frmts/vrt/vrtdataset.cpp
This fixes an issue introduced in master per 4efd242aa51366a06299dd74aefd608404d5016a
that triggers on the test case of #2911
But this fix doesn't fix #2911. It just avoids this new regression.
> VRTDataset::IRasterIO(): fix excessive recursion prevention

- gdal/doc/source/drivers/raster/pdf.rst
Poppler switched to a CMake-based build system a while ago. Even for CMake, the parameter was initially called `ENABLE_XPDF_HEADERS`, but this was changed to `ENABLE_UNSTABLE_API_ABI_HEADERS` in poppler 0.73.0 (Jan 2019).
> Update poppler build configuration requirement

- gdal/port/cpl_path.cpp
VSI handlers can be attached to any prefix, however attaching them to "scheme://" prefixes (e.g. https://) to enable gdal to directly open urls without having to rewrite them will lead to them being considered as relative.
e.g. `gdalbuildvrt output.vrt http://file1.tif http://file2.tif` will create a vrt file who's `SourceFileName` will have `relativeToVrt` set to `1`.
This patch marks filenames containing `://` to be absolute.
> treat "scheme://.." filenames as absolute

- gdal/swig/python/scripts/gdal2tiles.py
@dminor Could you look at this pull request ? It fixes the issue reported in #2932 which is due to your changes in #2808. Basically with #2808, --zoom=0-0 or --zoom=10-10 produce the same tiles, which match the native resolution of the raster. This is rather unexpected to me and to the reporter of #2932. So this pull request partially reverts #2808, while hopefully still fixing it.
> gdal2tiles: fix regression of #2808 when tmaxz != nativezoom (fixes #2932)

- autotest/utilities/test_gdalwarp_lib.py
- gdal/alg/gdalwarpkernel.cpp
Contributes to improving #2754, regarding not manually passing -wo XSCALE=
Does not address correct guessing of the target dataset resolution
> Warp: fix computation of kernel resampling width when wraping accros the antimeridian

- gdal/doc/source/drivers/raster/cog.rst
Improves layout of section in https://gdal.org/drivers/raster/cog.html#general-creation-options
Now: 
- SPARSE_OK=TRUE/FALSE ((GDAL >= 3.2): Should empty blocks be
With this PR:
- SPARSE_OK=TRUE/FALSE ((GDAL >= 3.2): Should empty blocks be omitted on disk?
This PR replaces #2943
> cog.rst: fix wrong indentation

- autotest/ogr/ogr_geojson.py
- autotest/ogr/ogr_geom.py
- autotest/ogr/ogr_geos.py
- autotest/ogr/ogr_layer_algebra.py
- autotest/ogr/ogr_mvt.py
- autotest/ogr/ogr_sql_sqlite.py
- autotest/pymod/ogrtest.py
- autotest/utilities/test_ogr2ogr.py
- gdal/ogr/ogrgeometryfactory.cpp
The only change in code is the TransformBeforeAntimeridianToWGS84() method.
Instead of intersecting the geometry with a multipolygon made of two parts,
one left of the antimeridian, one right of it, but which were at a very
close distance, which resulted in a LINESTRING EMPTY intersection with OverlayNG,
we compute the difference between our geometry and a thin polygon around the
antimeridian, which works for older GEOS too.
> Fixes related to GEOS 3.9 OverlayNG

- autotest/gdrivers/vrtovr.py
- autotest/utilities/test_gdalbuildvrt_lib.py
- gdal/apps/gdalbuildvrt_lib.cpp
- gdal/data/gdalvrt.xsd
- gdal/doc/source/drivers/raster/vrt.rst
- gdal/frmts/vrt/vrtdataset.cpp
- gdal/frmts/vrt/vrtdataset.h
- gdal/frmts/vrt/vrtsourcedrasterband.cpp
- gdal/frmts/vrt/vrtsources.cpp
- Explicit virtual overviews are overviews that are reported on VRT rasterbands,
and rely only on the fact that the source(s) making those bands have themselves
overviews, but this is not enforced.
Such virtual overviews are generally not needed, unless in some situations, like
wrapping a VRT dataset to a lower resolution.
The VRTDataset.OverviewList XML element is added to declare such overviews.
GDALDataset::BuildOverviews() can also 'build' them when the VRT_VIRTUAL_OVERVIEWS
configuration option is set to YES.
-  gdalbuildvrt: add support for automatically declaring virtual overviews in very restricted situations.
All sources must have the same resolution, and this must be the one of
the VRT dataset itself.
> VRT: add support for explicit virtual overviews 

- gdal/docker/README.md
- gdal/docker/alpine-normal/build.sh
- gdal/docker/alpine-small/build.sh
- gdal/docker/alpine-ultrasmall/build.sh
- gdal/docker/ubuntu-full/build.sh
- gdal/docker/ubuntu-small/build.sh
- gdal/docker/util.sh
This PR will alter the docker build scripts to optionally allow building multi-arch and pushing those manifests to registries. This effectively enables containers with ARM support for devices such as Raspberry Pi.
Completes #2959
* OS: MacOS
* Compiler: N/A (sort of, it's Docker w/ QEMU)
> build(gdal/docker): registry/image/tag, multi arch support

- gdal/doc/source/programs/gdal_calc.rst
Fixes #1848
Adds note and example about the possibility of getting unexpected results with doing intermediate operations using operands of the same datatype.
Fixes #1848
* OS:
* Compiler:
> Adds note about same datatype operations

- autotest/gdrivers/nitf.py
- gdal/data/nitf_spec.xml
Adds additional NITF TREs in support of the Spectral NITF Implementation Profile (SNIP)
The SNIP is in NGA.STND.0072_1.0_SNIP 7 June 2019. It out references to the relevant TREs in Table 6-2. 
MATESA is defined in STDI-0002 Appendix AK. 
GRDPSB is defined in STDI-0002 Appendix P.
The test examples are from the SNIP Reference Implementation Product 1B, which is public released.
N/A
N/A
> nitf: add TREs in support of Spectral NITF Implementation Profile

- autotest/cpp/test_cpl.cpp
- gdal/port/cpl_http.cpp
Add custom read file function to curl in CPLHTTPFetch. 
On Windows curl needs file path in system encoding. So the path encoding in FORM_FILE_PATH variable differs from GDAL usual path encoding - UTF8.
> Add read function for form file in CPLHTTPFetch

- gdal/docker/ubuntu-full/Dockerfile
- gdal/docker/ubuntu-full/bh-gdal.sh
- gdal/swig/java/GNUmakefile
1. Adds support for FileGDB drivers
*  Ubuntu-Full isn't really full without write support for one of the most common GIS formats.
2. Adds support for MDB driver
*  You still occasionally encounter personal geodatabases in the wild
3. Updates OpenJDK 8 to OpenJDK 11
*  Current LTS
> Docker/ubuntu-full: Add support for FileGDB and MDB drivers

- autotest/gdrivers/nitf.py
- gdal/data/nitf_spec.xml
- gdal/data/nitf_spec.xsd
- gdal/frmts/nitf/nitffile.c
This PR adds the capability to read the BANDSB TRE, defined in the Spectral NITF Implementation Profile
STDI-0002-1 Appendix X.
In nitf_spec.xml, this TRE requires recursive variable search in <loop> blocks, and requires raw bits to be read and used as conditionals in <if> blocks.
https://github.com/OSGeo/gdal/pull/2414
https://github.com/OSGeo/gdal/pull/2973
* OS:
* Compiler:
> NITF: Add BANDSB TRE from Spectral NITF Implementation Profile

- gdal/swig/python/scripts/gdalcompare.py
With the standard division operator, the parameter passed to the range function can be a float. This assure to always use floor division for Python 2 and 3.
> gdalcompare: fix floor division in Python 3

- gdal/gcore/gdalopeninfo.cpp
- gdal/port/cpl_vsi.h
- gdal/port/cpl_vsi_virtual.h
- gdal/port/cpl_vsil.cpp
- gdal/port/cpl_vsil_curl.cpp
- gdal/port/cpl_vsil_curl_class.h
- gdal/port/cpl_vsil_plugin.cpp
- gdal/port/cpl_vsil_plugin.h
This patch allows vsi filesystems to return a list of sibling files. This can be used to explicitely disallow opening/querying for .aux or .ovr files without having to set GDAL_DISABLE_READDIR_ON_OPEN to EMPTY_DIR.
One might argue that this has nothing to do in the VSIFileSystem API, but the current lack of this function has already lead to an hack which has been cleaned up by this commit.
> VSI: add callback to explicitely list sibling files

- gdal/ogr/ogrsf_frmts/shape/dbfopen.c
- If within a method that can fail, return error result when FRead() fails.
- Otherwise, Convert FRead(..., Size, 1) to FRead(..., 1, Size).
- Only change places where the return value of FRead() is currently ignored.
- Fixes another msan issue similar to OSGeo#2970
> Improve msan behavior of dbfopen API calls.

- autotest/cpp/test_cpl.cpp
- gdal/port/cpl_http.cpp
- gdal/port/cpl_http.h
- gdal/port/cpl_multiproc.h
Those functions are to be used to install callbacks that will take care
of executing network requests submitted to CPLHTTPFetch/CPLHTTPFetchEx().
This is meant to allow QGIS for example to be able to plug its network layer
instead of using the Curl implementation.
> Add CPLHTTP[Push|Pop]FetchCallback() and CPLHTTPSetFetchCallback() callback mechanisms

- gdal/frmts/dimap/dimapdataset.cpp
Some mosaic products may be missing the R1C1 tile. Use the first available `<Data_File>` in that case.
> DIMAP: fix loading when R1C1 tile is not present

- autotest/gdrivers/nitf.py
- gdal/data/nitf_spec.xml
This PR adds the capability to read the ACCHZB and ACCVTB TREs, defined in the Spectral NITF Implementation Profile
These TREs are defined in STDI-0002-1-v5.0 Appendix P.
https://github.com/OSGeo/gdal/pull/2983
https://github.com/OSGeo/gdal/pull/2973
* OS:
* Compiler:
> NITF: Add ACCHZB and ACCVTB TREs

- autotest/gdrivers/nitf.py
- gdal/data/nitf_spec.xml
This PR adds the capability to read the MSTGTA and PIATGB TREs, defined in the Spectral NITF Implementation Profile
MSTGTA is defined in STDI-0002-1-v5.0 Appendix E.
PIATGB is defined in STDI-0002-1-v5.0 Appendix C.
These TREs are not populated in the SNIP reference implementation product 1B, so arbitrary data was used to populate the TREs in the unit tests.
https://github.com/OSGeo/gdal/pull/3001
* OS:
* Compiler:
> NITF: Add SNIP TREs MSTGTA and PIATGB

- autotest/pyscripts/test_gdal_calc.py
- gdal/doc/source/programs/gdal_calc.rst
- gdal/swig/python/scripts/gdal_calc.py
Support mulitple calc arguments to produce a multiband file
Currently, producing a multiband file requires producing separate files, then merging them either by constructing a VRT file, either by using gdal_merge
It stays compatible with the old way of calling gdal_calc from other python scripts by supporting both single calc values and lists of calc values
Example:
gdal_calc.py -A A.tif --A_band=1 -B.tif --B_band=2 -Z Z.tif --calc="(A+B)" --calc="(B+Z)" --calc="(Z/2)" --overwrite --outfile tmp/test_gdal_calc_py_8_1.tif
It is not compatible with --allBands - ie you have to either specify allBands, either have multiple calcs but not both
> gdal_calc: support multiple calc arguments to produce a multiband file

- autotest/gdrivers/nitf.py
- gdal/data/nitf_spec.xml
This PR adds the capability to read the PIXQLA and PIXMTA TREs, defined in the Spectral NITF Implementation Profile
PIXQLA is defined in STDI-0002-1-v5.0 Appendix AA.
PIXMTA is defined in STDI-0002-1-v5.0 Appendix AJ.
This PR also adds correct TRE locations for other recent SNIP TREs.
https://github.com/OSGeo/gdal/pull/3015
https://github.com/OSGeo/gdal/pull/3001
https://github.com/OSGeo/gdal/pull/2983
* OS:
* Compiler:
> NITF: Add support for SNIP TREs, PIXQLA and PIXMTA

- gdal/port/cpl_http.cpp
This adds the `GDAL_CURL_CA_BUNDLE` environment variable for the use case where users want to set the path for the GDAL curl CA Bundle without worrying about modifying/impacting the main one used by other tools.
Part 1 of #3024
> Add GDAL_CURL_CA_BUNDLE environment variable

- gdal/ogr/ogrsf_frmts/avc/avc_binwr.cpp
Replace FILE with VSILFILE
#3034 
* OS: Win32
* Compiler: MSVC 140
> replace FILE with VSILFILE on Win32

- autotest/gcore/tiff_write.py
- gdal/doc/source/drivers/raster/gtiff.rst
- gdal/doc/source/programs/gdaladdo.rst
- gdal/frmts/gtiff/geotiff.cpp
- gdal/frmts/gtiff/gt_overview.cpp
- gdal/frmts/gtiff/gt_overview.h
- gdal/frmts/gtiff/gtiff.h
Supersedes #3014
@tbonfort I kept your first 3 commits, but I put before https://github.com/OSGeo/gdal/commit/bed9da378be158a56dad0956068c91598624cd4f which was the fix for the issue you saw. Basically the issue is that RestoreVolatileParameters() called by SetDirectory() from OpenOffset() was mostly a no-op because nCompression wasn't set at that point... Using libtiff in a multi-directory context is a mess beyond imagination!
And this fix actually underlined a unrelated issue with LERC... fixed by the first commit in the series (actually moved in its own PR https://github.com/OSGeo/gdal/pull/3038)
I let you confirm that things work as expected for you
>  GTiff: add WEBP_LEVEL_OVERVIEW config option to set WebP compression level on overviews

- autotest/gdrivers/jp2openjpeg.py
- gdal/doc/source/drivers/raster/jp2openjpeg.rst
- gdal/frmts/openjpeg/openjpegdataset.cpp
Available with OpenJPEG > 2.3.1
Funded by ESA for S2-MPC project
> JP2OpenJPEG: add support for generating files with PLT marker segments and multithreaded encoding

- autotest/gcore/tiff_write.py
Check that blocksize can be overidden when BuildOverviews is called at creation time (i.e. witout reopening the dataset). Written when hunting down an issue that was on my end after all, but doesn't hurt to have this in the master test suite.
> check ovr blocksize can be overriden at creation time

- autotest/gcore/cog.py
- autotest/gcore/tiff_write.py
- autotest/utilities/test_gdal_translate_lib.py
- gdal/apps/gdal_translate_bin.cpp
- gdal/apps/gdal_translate_lib.cpp
- gdal/doc/source/programs/gdal_translate.rst
- gdal/frmts/gtiff/geotiff.cpp
- gdal/gcore/gdaldriver.cpp
Add feature to copy XMP metadata in `CreateCopy`, in particular for `GTiff` driver (`COG` indirectly), and all drivers that use `DefaultCreateCopy` method.
`gdal_translate` adds the option `-noxmp` to not copy this data when desired
> Lets copy XMP metadata

- autotest/gdrivers/nitf.py
- gdal/doc/source/drivers/raster/nitf_advanced.rst
- gdal/frmts/nitf/nitffile.c
This PR adds a NITF creation option to create TREs from a hexadecimal string.
Several TREs defined in the Spectral NITF Implementation Profile have non-string fields (uint, float32, etc).  This capability will help develop more effective tests of SNIP TREs.
The SNIP is in NGA.STND.0072_1.0_SNIP 7 June 2019.
https://github.com/OSGeo/gdal/pull/2983
* OS:
* Compiler:
> NITF: Add hexadecimal TRE creation

- autotest/gcore/tiff_write.py
test never added for #1611, doing this now. fails locally, awaiting ci tests.
> add test for default tiff ovrview blocksize (#1611)

- autotest/gdrivers/nitf.py
- gdal/data/nitf_spec.xml
- gdal/data/nitf_spec.xsd
- gdal/frmts/nitf/nitffile.c
This PR adds the capability to read the CSEXRB TRE, defined in the Spectral NITF Implementation Profile
CSEXRB is defined in STDI-0002-1-v5.0 Appendix AH.
This TRE requires ~~two~~ one parsing change~~s~~:
1) ~~The ability to use 32 bit unsigned int fields as loop variables (max possible loop value can exceed signed int max)~~
2) The ability to read unsigned int fields between 1 and 8 bytes in width
https://github.com/OSGeo/gdal/pull/3049
https://github.com/OSGeo/gdal/pull/3023
* OS:
* Compiler:
> NITF: Add SNIP TRE - CSEXRB

- autotest/gdrivers/nitf.py
- gdal/frmts/nitf/nitffile.c
This PR adds missing fields to the XML output of the "xml:TRE" metadata domain.  The fields that were not previously included were contained within \<loop\> or \<if\> blocks that accessed variables outside the immediate block scope.  These variables need md_prefix to be provided in order to recursively find the variable.
https://github.com/OSGeo/gdal/pull/2983
* OS:
* Compiler:
> NITF: Add nested variable support in xml:TRE

- autotest/gdrivers/nitf.py
- gdal/data/nitf_spec.xml
This PR adds the capability to read the ILLUMB TRE, defined in the Spectral NITF Implementation Profile
ILLUMB is defined in STDI-0002-1-v5.0 Appendix AL.
https://github.com/OSGeo/gdal/pull/3058
https://github.com/OSGeo/gdal/pull/3023
* OS:
* Compiler:
> NITF: Add ILLUMB TRE from SNIP specification

- autotest/ogr/ogr_gpkg.py
- gdal/ogr/ogrsf_frmts/gpkg/ogrgeopackagetablelayer.cpp
- GetNextFeature() without spatial filter doesn't need spatial index
- GetFeature() too
- DeleteField(), AlterFieldDefn() or ReorderFields() are unrelated too
> GPKG: defer in a bit more situations spatial index creation

- gdal/configure
- gdal/configure.ac
Upstream changed the library name without an SONAME bump, this caused issues and was reverted in Debian, see:
https://bugs.debian.org/971425
The charls Debian package still uses the CharLS library name for 2.1.
> Support CharLS 2.1 on Debian as well.

- autotest/ogr/data/mitab/all_geoms.mif.golden.csv
- autotest/ogr/ogr_mitab.py
- gdal/ogr/ogrsf_frmts/mitab/mitab.h
- gdal/ogr/ogrsf_frmts/mitab/mitab_feature.cpp
- gdal/ogr/ogrsf_frmts/mitab/mitab_imapinfofile.cpp
Make sure the correct type of point object is created depending on the type of symbol used. Also map MapInfo's custom symbol styles to OGR symbol styles. The symbol id is set to "mapinfo-custom-sym-[CUSTOM_STYLE]-[FILENAME]" with a fallback id on the form "[FILE_EXTENSION]-[FILENAME]" and finally "ogr-sym-9".
> Support for font and custom symbols in mitab

- autotest/gdrivers/nitf.py
- gdal/data/nitf_spec.xml
This PR adds the capability to read the CSRLSB and CSWRPB TREs, defined in the Spectral NITF Implementation Profile
CSRLSB and CSWRPB are defined in STDI-0002-1-v5.0 Appendix AH.
https://github.com/OSGeo/gdal/pull/3071
https://github.com/OSGeo/gdal/pull/3058
* OS:
* Compiler:
> NITF: Add support for SNIP TREs, CSRLSB and CSWRPB

- autotest/pyscripts/test_gdal_calc.py
- gdal/doc/source/programs/gdal_calc.rst
- gdal/swig/python/osgeo/utils/gdal_calc.py
Multiple improvements for gdal_calc.py
general additions:
* AlphaList - now includes lowercase + uppercase alphabet
* GDALDataTypeNames - tuple of available output datatypes names
* DefaultNDVLookup - dictionary.keys() changed from string to GDALDataType; DefaultNDVLookup[GDT_Int16] = -32768 (changed to min int16, was -32767)
* Support Alpha inputs as a Sequence of inputs
* store_input_file - extended to support multiple inputs with the same alpha (which will make a list)
* accept dataset inputs in additions of filename inputs
* Support input files with different GeoTransforms and Dimensions - Implementation of this feature will be in another PR
new options:
* opts.NoDataValue=... - use opts.NoDataValue to indicate None datatype (opts.NoDataValue=None already indicates default value)
* …
> gdal_calc.py - improvements

- gdal/doc/source/user/virtual_file_systems.rst
Adds GDAL_HTTPS_PROXY config option in the docs.
Followup #972
Fixes #3111
> Docs: add GDAL_HTTPS_PROXY config option (fixes #3111)

- autotest/gdrivers/nitf.py
- gdal/data/nitf_spec.xml
This PR adds the capability to read the SECURA and SNSPSB TREs, defined in the Spectral NITF Implementation Profile
SECURA is defined in STDI-0002-1-v5.0 Appendix AI.
SNSPSB is defined in STDI-0002-1-v5.0 Appendix P.
https://github.com/OSGeo/gdal/pull/3090
* OS:
* Compiler:
> NITF: Add SNIP TREs - SECURA and SNSPSB

- autotest/gdrivers/mrf.py
- gdal/frmts/mrf/LERCV1/Lerc1Image.cpp
- gdal/frmts/mrf/LERCV1/Lerc1Image.h
- gdal/frmts/mrf/LERCV1/makefile.vc
- gdal/frmts/mrf/LERC_band.cpp
Add function to read size from tile
Fixes raw LERC1 detection/read via MRF, it was broken by previous commits
* OS:
* Compiler:
> MRF: Restore raw Lerc1 detection

- autotest/gdrivers/memmultidim.py
- autotest/gdrivers/netcdf_multidim.py
- gdal/frmts/hdf4/hdf4multidim.cpp
- gdal/frmts/mem/memdataset.cpp
- gdal/frmts/netcdf/netcdfmultidim.cpp
- gdal/frmts/vrt/vrtdataset.h
- gdal/gcore/gdal.h
- gdal/gcore/gdal_priv.h
- gdal/gcore/gdalmultidim.cpp
- gdal/gcore/gdalrasterband.cpp
- gdal/swig/include/MultiDimensional.i
- gdal/swig/python/extensions/gdal_wrap.cpp
- gdal/swig/python/osgeo/gdal.py
* Multidim API: [Set/Get][Offset/Scale](): extend to get/set storage data type
- Add 'Ex' suffixed C API functions for that
- Implement in MEM and netCDF drivers
- Make GDALMDArray::CopyFromAllExceptValues() take into account that
* GDALMDArrayUnscaled: implement Write() to be able to get from unscaled values to raw values
* GDALMDArrayUnscaled::IWrite(): speed optimization when writing to netCDF 4
* GDALGroup::CopyFrom(): add ARRAY:AUTOSCALE=YES and ARRAY:AUTOSCALE_DATA_TYPE=Byte/UInt16/Int16/UInt32/Int32 creation options
> Multidim: improvements related to scale/offset

- autotest/gdrivers/fits.py
- autotest/ogr/ogr_basic_test.py
- autotest/ogr/ogr_geojson.py
- gdal/frmts/fits/fitsdataset.cpp
- gdal/ogr/ogr_p.h
- gdal/ogr/ogrfeature.cpp
- gdal/ogr/ogrsf_frmts/geojson/ogrgeojsonwriter.cpp
- gdal/ogr/ogrutils.cpp
- FITS: display more informative error message when opening raster dataset in vector mode, or vice-verca
- OGRFeature::GetFieldAsString() and GeoJSON output: do not output Float32 with excessive precision
Funded by CNES
> Fits adjustments

- autotest/ogr/ogr_as_sqlite_extension.py
- autotest/pymod/xmlvalidate.py
- gdal/swig/python/osgeo/auxiliary/base.py
- gdal/swig/python/osgeo/utils/epsg_tr.py
- gdal/swig/python/osgeo/utils/esri2wkt.py
- gdal/swig/python/osgeo/utils/gcps2vec.py
- gdal/swig/python/osgeo/utils/gcps2wld.py
- gdal/swig/python/osgeo/utils/gdal2xyz.py
- gdal/swig/python/osgeo/utils/gdal_auth.py
- gdal/swig/python/osgeo/utils/gdal_calc.py
- gdal/swig/python/osgeo/utils/gdal_fillnodata.py
- gdal/swig/python/osgeo/utils/gdal_merge.py
- gdal/swig/python/osgeo/utils/gdal_pansharpen.py
- gdal/swig/python/osgeo/utils/gdal_polygonize.py
- gdal/swig/python/osgeo/utils/gdal_proximity.py
- gdal/swig/python/osgeo/utils/gdal_retile.py
- gdal/swig/python/osgeo/utils/gdal_sieve.py
- gdal/swig/python/osgeo/utils/gdalchksum.py
- gdal/swig/python/osgeo/utils/gdalcompare.py
- gdal/swig/python/osgeo/utils/gdalident.py
- gdal/swig/python/osgeo/utils/gdalimport.py
- gdal/swig/python/osgeo/utils/gdalmove.py
- gdal/swig/python/osgeo/utils/mkgraticule.py
- gdal/swig/python/osgeo/utils/ogrmerge.py
- gdal/swig/python/osgeo/utils/pct2rgb.py
- gdal/swig/python/osgeo/utils/rgb2pct.py
- gdal/swig/python/samples/attachpct.py
- gdal/swig/python/samples/tile_extent_from_raster.py
- gdal/swig/python/setup.py
osgeo.auxiliary package added. to be home for auxilary functions for GDAL python scripting. more stuff should arrive here soon :)
auxiliary/base.py - combined all versions of GetOutputDriverFor, GetOutputDriversFor. removed duplicated versions from other source files. added some other useful functions.
setup.py - added osgeo.auxiliary
pct2rgb.py, rgb2pct.py - added a doit function and return ds
ogr/ogr_as_sqlite_extension.py - added main function
xmlvalidate.py - added main stub
attachpct.py - use GetOutputDriverFor
replace sys.exit(x) by return x for the osgeo.utils functions
prerequisite:
https://github.com/OSGeo/gdal/pull/3115
> refactor python scripts and add osgeo.auxilary package

- autotest/gdrivers/nitf.py
- gdal/data/nitf_spec.xml
This PR adds the capability to read the RSMAPB, RSMDCB, and RSMECB TREs, defined in the Spectral NITF Implementation Profile.  The SNIP is in NGA.STND.0072_1.0_SNIP 7 June 2019. It out references to the relevant TREs in Table 6-2.
The RSM* TREs are defined in STDI-0002-1-v5.0 Appendix U.
These are the last three SNIP related TREs!
https://github.com/OSGeo/gdal/pull/3113
https://github.com/OSGeo/gdal/pull/3090
* OS:
* Compiler:
> NITF: Add SNIP TREs - RSMAPB, RSMDCB, RSMECB

- autotest/gdrivers/nitf.py
- gdal/doc/source/drivers/raster/nitf.rst
- gdal/doc/source/drivers/raster/nitf_advanced.rst
- gdal/frmts/nitf/nitfdataset.cpp
- gdal/frmts/nitf/nitfdataset.h
- gdal/frmts/nitf/nitfdes.c
- gdal/frmts/nitf/nitffile.c
- gdal/frmts/nitf/nitflib.h
This PR adds an xml:DES metadata domain to extract user-defined Data Extension Segments from a NITF file.  A DES creation option was also added to facilitate testing.
* OS:
* Compiler:
> NITF: Add xml:DES metadata domain and DES creation option

- gdal/doc/source/programs/gdal2tiles.rst
- gdal/doc/source/user/configoptions.rst
Documentation fix for https://github.com/OSGeo/gdal/issues/3162.
It was mentioned there that 
> There is an initiative to collect all configuration options into one page https://gdal.org/user/configoptions.html but the page is far from perfect. For example GDAL_PDF_DPI is still missing,
But it is currently present when I visit that page
> Update gdal2tiles.rst - Explicitly mention common config options

- autotest/pyscripts/test_gdal2tiles.py
- gdal/data/tms_MapML_CBMTILE.json
- gdal/doc/source/programs/gdal2tiles.rst
Unfortunately this makes it non-usable by gdal2tiles, but still by the COG driver
> tms_MapML_CBMTILE.json: fix it to use correct resolution / scaleDenominator

- gdal/frmts/heif/makefile.vc
Allow Visual Studio to build heif driver
* OS: Windows
* Compiler: Visual Studio
> add missing makefile.vc for heif

- autotest/gdrivers/mbtiles.py
- autotest/pyscripts/test_gdal2tiles.py
- autotest/utilities/test_gdalwarp.py
- gdal/frmts/gtiff/cogdriver.cpp
- gdal/frmts/mbtiles/mbtilesdataset.cpp
- gdal/ogr/ogrsf_frmts/gpkg/ogrgeopackagedatasource.cpp
- gdal/swig/python/scripts/gdal2tiles.py
With PROJ 8, lat=90 no longer project to infinity in Mercator, which shows
fragile heuristics in the code.
> gdal2tiles/COG/MBTiles/GeoPackage: adjustments for EPSG:3857 output (due to PROJ 8 changes)

- autotest/gcore/vrtmisc.py
- autotest/utilities/test_gdal_translate_lib.py
- gdal/apps/gdal_translate_lib.cpp
- gdal/data/gdalvrt.xsd
- gdal/doc/source/drivers/raster/vrt.rst
- gdal/frmts/dimap/dimapdataset.cpp
- gdal/frmts/vrt/vrtdataset.cpp
- gdal/frmts/vrt/vrtdataset.h
- gdal/frmts/vrt/vrtdriver.cpp
- gdal/frmts/vrt/vrtrasterband.cpp
- gdal/frmts/vrt/vrtsourcedrasterband.cpp
- gdal/gcore/rasterio.cpp
Assorted set of improvements that help for example to gdal_translate a DIMAP JPEG2000 dataset (read by JP2KAK) to tiled GeoTIFF
> VRT: preserve source block size

- gdal/doc/source/programs/gdal2tiles.rst
Fix a typo in the gdal2tiles documentation page
> Update gdal2tiles.rst - fix typo

- .gitignore
- gdal/gcore/gdalpython.cpp
there is a project called pystack . which used to print the python
process's stack info . pystack will use gdb to attach the python process
and call some function defined in python's executable file or python
library
such as
call (void *) PyGILState_Ensure()
call (void) PyRun_SimpleString("exec(r\"f = open('/tmp/pystack', 'w'); \
itervalues = lambda d:getattr(d,'itervalues',d.values)();import gc,traceback,itertools,sys; \
f.write('Dumping Threads\\n\\n\\n');f.write('\\n---------------\\n'.join(str(traceback.format_stack(o)
) for o in itervalues(sys._current_frames())));f.close()\")")
...
but the symbol PyGILState_Ensure also defined in gdal .so if a python
script use gdal , we can't use pystack to debug this .
so i changed the symbol of gdal by add Lib infix
Provide environment details, …
> fix:fix symbol conflicts with python libraries

- gdal/MIGRATION_GUIDE.TXT
> Fix method name in migration guide

- gdal/doc/source/development/rfc/index.rst
- gdal/doc/source/development/rfc/rfc77_drop_python2_support.rst
Add RFC 77: Drop Python 2 support in favor of Python 3.6
https://github.com/OSGeo/gdal/issues/3114
> rfc77_drop_python2_support - RFC 77: Drop Python 2 support in favor of Python 3.6

- gdal/doc/source/drivers/raster/wms.rst
Fixed wrong link pointing to old link, updated with the right Github page
It seems not
* OS:
* Compiler:
> Doc/wms.rst: fixed wrong link

- gdal/ogr/ogrsf_frmts/pg/ogrpgresultlayer.cpp
- gdal/ogr/ogrsf_frmts/pg/ogrpgtablelayer.cpp
When the PostGIS driver doesn't find any SRID set in `geometry_columns`, it falls back to querying a single row of data using `ST_SRID()`. But if the row it randomly picks happens to have a `NULL` geometry then the result is an undefined SRID.
This change filters out `NULL` geometries from the SRID-detection queries in `OGRPGTableLayer::ResolveSRID()` and `OGRPGResultLayer::ResolveSRID()`.
Not quite sure how to write a test-case for it, since by definition the result ordering returned by PostgreSQL is undefined without passing an `ORDER BY` clause.
> PG: When detecting SRID from table contents, ignore null geometries

- gdal/swig/python/osgeo/__init__.py
This PR prepares the ground for deprecating older Python versions in newer versions of GDAL.
It sets Python 3.6 as the minimum supported Python version for GDAL 3.3 and will raise a deprecation warning if you are using a Python version that will get unsupported in the next version of GDAL.
Setting `fail_on_unsupported_version = False` to True will cause importing osgeo to fail on an unsupported Python version.
Otherwise a deprecation warning will be issued instead.
Importing osgeo fom an unsupported Python version might still partially work
because the core of GDAL Python bindings might still support an older Python version.
Hence the default option to just issue a warning.
To get complete functionality upgrading to the minimum supported version is needed.
Currently, When setting …
> osgeo/__init__.py - add Python version check and deprecation warning

- gdal/ogr/ogrspatialreference.cpp
as CompoundCRS with a VerticalCRS being an ellipsoidal height, which is
not conformant. But needed for LAS 1.4 that only supports WKT1
Requires PROJ 7.2.1 / https://github.com/OSGeo/PROJ/pull/2470
```python:
from osgeo import osr
srs = osr.SpatialReference()
srs.ImportFromEPSG(32631)
srs.PromoteTo3D()
print(srs.ExportToWkt(['FORMAT=WKT1', 'ALLOW_ELLIPSOIDAL_HEIGHT_AS_VERTICAL_CRS=YES']))
```
outputs:
'COMPD_CS["WGS 84 / UTM zone 31N + Ellipsoid (metre)",PROJCS["WGS 84 / UTM zone 31N",GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4326"]],PROJECTION["Transverse_Mercator"],PARAMETER["latitude_ …
> OGRSpatialReference::exportToWKT(): add a option to allow export of Geographic/Projected 3D CRS in WKT1_GDAL

- gdal/swig/python/osgeo/__init__.py
Update the python - gdal version support.
What was the minimum supported Python version of GDAL 3.2 ? Python 2.7? older?
Did gdal ever drop a python version support before?
https://github.com/OSGeo/gdal/pull/3165
> osgeo/__init__.py - update gdal_version_and_min_supported_python_version

- autotest/gcore/rasterio.py
- gdal/gcore/overview.cpp
so as to minimize the error |rms**2 - sumSquare/weight|
Relates to #3196
Also removes a useless test in the optimized case of downsampling
by a factor of 2 in the absence of mask/nodata
> RMS resampling: improve slightly the rounding to integer

- .github/workflows/code_checks.yml
- .github/workflows/conda.yml
- gdal/ci/travis/conda/compile.sh
- gdal/ci/travis/conda/setup.sh
Implements a GHA builder to build Conda packages for the current SHA and adds them as artifacts to the build.
> Conda package building for GDAL based on Conda Forge recipe

- gdal/doc/source/user/virtual_file_systems.rst
Curly braces aren't visible in HTML output. I've replaced :file: to inline literal because escaping with backslashes doesn't work here.
> Fix curly braces formatting in vsizip

- autotest/gdrivers/nitf.py
- gdal/data/nitf_spec.xml
- gdal/data/nitf_spec.xsd
- gdal/frmts/nitf/nitffile.c
This PR introduces a new field type to nitf_spec.xml to handle NITF Extended Character Set (ECS).  ECS consists of 1-byte characters that align to the ISO-8859-1 extended ASCII standard.
ECS is defined in MIL-STD-2500C
ECS character \mu (0xB5) is used for several TREs including ILLUMB (STDI-0002 Appendix AL) and PIXMTA (STDI-0002 Appendix AJ).
https://github.com/OSGeo/gdal/pull/3071
https://github.com/OSGeo/gdal/pull/3023
* OS:
* Compiler:
> NITF: Add support for ISO8859-1 fields in NITF TREs

- .github/workflows/conda.yml
- gdal/ci/travis/conda/compile.sh
- gdal/ci/travis/conda/setup.sh
- gdal/ci/travis/conda/upload.sh
@JorisVandenBossche [suggested](https://twitter.com/jorisvdbossche/status/1336573419823960065?s=20) we create public channel for deploying builds from master is available at https://anaconda.org/gdal-master/
This PR adds that, but the push only happens if the branch is ``refs/heads/master``
> Attempt to deploy to gdal-master Anaconda channel

- autotest/gcore/vsiadls.py
- autotest/gcore/vsiadls_real_instance.py
- autotest/gcore/vsiaz.py
- autotest/pymod/webserver.py
- gdal/doc/source/user/virtual_file_systems.rst
- gdal/port/GNUmakefile
- gdal/port/cpl_azure.cpp
- gdal/port/cpl_azure.h
- gdal/port/cpl_path.cpp
- gdal/port/cpl_vsi.h
- gdal/port/cpl_vsil.cpp
- gdal/port/cpl_vsil_adls.cpp
- gdal/port/cpl_vsil_az.cpp
- gdal/port/cpl_vsil_curl.cpp
- gdal/port/cpl_vsil_curl_class.h
- gdal/port/cpl_vsil_curl_streaming.cpp
- gdal/port/cpl_vsil_gs.cpp
- gdal/port/cpl_vsil_oss.cpp
- gdal/port/cpl_vsil_s3.cpp
- gdal/port/cpl_vsil_swift.cpp
- gdal/port/cpl_vsil_webhdfs.cpp
- gdal/port/makefile.vc
- gdal/swig/python/samples/gdal_ls.py
It has similar capabilities as /vsiaz/ and in particular uses the same
configuration options for authentication. Its advantages over /vsiaz/ are a real
management of directory and Unix-style ACL support. Some features require the Azure
storage to have hierarchical support turned on. Consult
https://docs.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-introduction
The main enhancements over /vsiaz/ are:
* True directory support (no need for the artificial :file:`.gdal_marker_for_dir`
empty file that is used for /vsiaz/ to have empty directories)
* One-call recursive directory deletion with VSIRmdirRecursive()
* Atomic renaming with VSIRename()
* VSIGetFileMetadata() support for the "STATUS" and "ACL" metadata domains
* VSISetFileMetadata() support for the "PROPERTIES" and "ACL" …
> Add /vsiadls/ virtual file system for Azure Data Lake Storage Gen2

- autotest/gdrivers/gpkg.py
- autotest/ogr/ogr_gpkg.py
- gdal/ogr/ogrsf_frmts/gpkg/ogrgeopackagedatasource.cpp
Addresses the previous inline comment saying
```
/* Should we do something special with undefined SRS ? */
```
and distinguishes between SRS ID of `0` and `-1` according to https://www.geopackage.org/spec121/#r11
> GeoPackage 1.2.1
>  1.1.1.1.1. File Format
>   Requirement 11
>    The record with an srs_id of -1 SHALL be used for undefined Cartesian coordinate reference systems.
>    The record with an srs_id of 0 SHALL be used for undefined geographic coordinate reference systems.
> 
* OS: any
* Compiler: any
> GeoPackage: Fix handling of invalid SRS ID

- gdal/doc/source/programs/gdaladdo.rst
Adds "bilinear" among the resampling algorithm list for "-r" option.
Followup https://github.com/OSGeo/gdal/commit/9d3b8c9a8453beee22a08f67d5a60b84dc634558
> Doc: gdaladdo: mention bilinear resampling

- gdal/port/cpl_vsil.cpp
This PR fixes a documentation error. 
Following the previous instructions (mode 0666), the directory was created without execute permissions, rendering it unusable. E.g. after creating a `../Test/KMZ/123/files` directory:
~~~
$ LANG=C ls -la ../Test/KMZ/123/files
ls: cannot access '../Test/KMZ/123/files/.': Permission denied
ls: cannot access '../Test/KMZ/123/files/..': Permission denied
total 0
d????????? ? ? ? ?             ? .
d????????? ? ? ? ?             ? ..
~~~
Note that looking for `VSIMkdir` in GDAL reveals a number of suboptimal (`0755`) and broken (`0744`) code:
https://github.com/OSGeo/gdal/search?q=vsimkdir
However, I don't know if VSI and OS implementation would properly apply umask in all cases.
> doc: Recommended default mode for VSIMkdir is 0755

- autotest/gdrivers/tiledb_write.py
- gdal/frmts/tiledb/tiledbdataset.cpp
This PR adds support for reading and writing TileDB arrays at user specified timestamps enabling a user to version the array data.
None
> TileDB: Add support for array versioning

- autotest/ogr/ogr_geojson.py
- gdal/ogr/ogrsf_frmts/geojson/ogrgeojsonwriter.cpp
Adresses issue of https://github.com/OSGeo/gdal/issues/1974#issuecomment-748677786
I considered doing a reprojection to EPSG:4326 long,lat of any input CRS,
but it might break uses cases where one wants to use GeoJSON with other CRS.
So I have limited to fixing the axis order for EPSG geographic or projected CRS
whose axis order is northing/easting, latitude/longitude.
But this fix has the potential to break use cases of GDAL < 3 that still worked
up to now. Sigh...
> OGRGeometry::ExportToJson(): takes into account CRS and axis order to swap

- autotest/ogr/ogr_gpkg.py
- gdal/ogr/ogrsf_frmts/gpkg/ogrgeopackagedatasource.cpp
Improve the writing side of the GeoPackage driver in order to support round-trip of the two special `undefined` SRS-s.
- Improves #3286
- Closes #3302
> GeoPackage: Fix handling of invalid SRS ID when writing

- autotest/gdrivers/ecw.py
Fix the following Python deprecation warning:
```
gdrivers/ecw.py::test_ecw_9
gdrivers/ecw.py::test_ecw_11
/usr/local/lib/python3.8/dist-packages/_pytest/python.py:183: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
result = testfunction(**testargs)
```
[tostring](https://docs.python.org/3.6/library/array.html#array.array.tostring) is deprecated since version 3.2, will be removed in version 3.9.
> autotest: Fix deprecation warning in gdrivers ecw test

- autotest/ogr/ogr_mssqlspatial.py
- autotest/ogr/ogr_pg.py
- gdal/ogr/ogr_core.h
- gdal/ogr/ogrfielddefn.cpp
- gdal/ogr/ogrsf_frmts/mssqlspatial/ogrmssqlspatiallayer.cpp
- gdal/ogr/ogrsf_frmts/mssqlspatial/ogrmssqlspatialtablelayer.cpp
- gdal/ogr/ogrsf_frmts/pg/ogr_pg.h
- gdal/ogr/ogrsf_frmts/pg/ogrpglayer.cpp
- gdal/ogr/ogrsf_frmts/pgdump/ogrpgdumplayer.cpp
- gdal/port/cpl_odbc.cpp
- gdal/swig/include/ogr.i
- gdal/swig/python/extensions/ogr_wrap.cpp
- gdal/swig/python/osgeo/ogr.py
Implements support for UUID as a string subtype and native datatype support for PostgreSQL, MSSQL and FileGDB.
* https://github.com/OSGeo/gdal/issues/3141 
* https://github.com/OSGeo/gdal/issues/3057
> New feature: UUID string subtype

- autotest/cpp/test_osr.cpp
- gdal/ogr/ogrspatialreference.cpp
Fixes https://lists.osgeo.org/pipermail/proj/2020-December/010008.html
> GetEPSGGeogCS(): fix when projected CRS can't be exported to WKT2

- gdal/doc/source/programs/gdal2tiles.rst
- gdal/swig/python/scripts/gdal2tiles.py
- gdal/swig/python/scripts/tests/gdal2tiles/test_option_parser.py
Allow the max zoom for gdal2tiles to be automatically calculated, even when min zoom is specified using the '10-' syntax.
This is a minor improvement I thought could prove useful, let me know what your opinions are.
None
> gdal2tiles: Allow automatic max zoom when min zoom is specified

- autotest/utilities/test_gdaldem_lib.py
- gdal/apps/gdaldem_bin.cpp
- gdal/apps/gdaldem_lib.cpp
- gdal/doc/source/programs/gdaldem.rst
- gdal/swig/include/python/gdal_python.i
- gdal/swig/python/osgeo/gdal.py
> gdaldem TRI: add a -alg Riley option to use the Riley 1999 formula, for terrestrial use cases

- autotest/pymod/gdaltest_python3.py
Fixes error handling in test suite file downloader.
The correct name of the exception is ContentTooShortError, and it
subclasses URLError so it must be listed before URLError if we want to
catch it.
* OS:
* Compiler:
> gdaltest: Fix handling of ContentTooShortError in gdalurlopen

- autotest/gcore/hdf4_read.py
The old URL does a 503, and I don't see anything on GeoGratis that would point me to it.
> Update Landsat 7 download URL

- gdal/swig/python/osgeo/utils/gdal_edit.py
Fixes `gdal_edit.py my_img.tif -scale` crashing with `IndexError: list index out of range` by making the parameter check the same as for the `-offset` parameter` 6 lines below (`gdal_edit.py my_img.tif -offset` prints `Unrecognized option : -offset`).
> gdal_edit.py: Correctly handle '-scale' without number

- gdal/swig/python/scripts/gdal2tiles.py
This simple change updates the script to fix the bug that if using `--xyz` the leaflet example does not output `tms: false`. There may be a better way to write this as I am just beginning with python so feel free to update without using this exact code.
None
Tested on Windows 10 latest
> fixes not writing tms bug in the leaflet example if using --xyz

- gdal/swig/python/README.rst
- gdal/swig/python/setup.py
README.rst - correct deprecated Imports comment
gdal/swig/python/setup.py - use find_packages (if available); remove Python 2 classifier; set python_requires='>=3.6.0'
> README.rst and setup.py additions/fixes

- gdal/frmts/pcidsk/sdk/blockdir/blocktilelayer.cpp
- gdal/frmts/pcidsk/sdk/channel/cbandinterleavedchannel.cpp
- gdal/frmts/pcidsk/sdk/channel/ctiledchannel.cpp
- gdal/frmts/pcidsk/sdk/core/cpcidskfile.cpp
- gdal/port/cpl_vsil_curl.cpp
The pcidsk_fuzzer exposed a bug in VSICurlHandle::Read(). The values were: iterOffset=280, nOffsetToDownload=0, osRegion.size()=272. I didn't try to understand why the file offset seems to be past the end of file. But this change can do no harm and it removes a vunerability. I ran the gtiff_fuzzer for a day and there were no errors.
I ran the pcidsk_fuzzer for 2 days using -timeout=60 and the only errors left are slow-unit errors which I'm not sure how to fix.
> PCIDSK: Fixed remaining address and undefined sanitizer fuzzer errors.

- gdal/frmts/wms/gdalwmsrasterband.cpp
- gdal/frmts/wms/wmsdriver.h
Missing tiles are filled with NoDataValue when NoDataValue is defined instead of always being zero.
To keep it backwards compatible with existing WMS driver use, the name of the ZeroBlock tag in the WMS definition file is not changed.
* OS:
* Compiler:
> WMS: Use noDataValue on empty blocks

- autotest/pyscripts/test_pct.py
- gdal/doc/source/programs/gdal_calc.rst
- gdal/doc/source/programs/gdalattachpct.rst
- gdal/doc/source/programs/index.rst
- gdal/doc/source/programs/rgb2pct.rst
- gdal/swig/python/osgeo/utils/auxiliary/color_palette.py
- gdal/swig/python/osgeo/utils/auxiliary/color_table.py
- gdal/swig/python/osgeo/utils/auxiliary/util.py
- gdal/swig/python/osgeo/utils/gdal_calc.py
- gdal/swig/python/osgeo/utils/gdalattachpct.py
- gdal/swig/python/osgeo/utils/pct2rgb.py
- gdal/swig/python/osgeo/utils/rgb2pct.py
- gdal/swig/python/samples/README.md
- gdal/swig/python/scripts/gdalattachpct.py
color palette python modules improvements
- gdalattachpct.py - upgraded attachpct.py into a module, added support for color table files and format
- gdal/swig/python/samples/attachpct.py - upgraded into a module
- gdal/swig/python/samples/README.md - remove attachpct.py
- gdal/swig/python/osgeo/utils/gdalattachpct.py - use GetOutputDriverFor (to support other drivers), get_color_table (to allow loading color palette from a ds or a txt file), open_ds (allow a ds input in addition of a filename)
- gdal/doc/source/programs/gdalattachpct.rst - document gdalattachpct.py
- gdal/doc/source/programs/index.rst - reference gdalattachpct.py
- autotest/pyscripts/test_pct.py - rename and add tests for gdalattachpct.py
- gdal/swig/python/osgeo/utils/[rgb2pct.py, pct2rgb.py] - use get_color_table to …
> improve color palette support: gdal_calc, gdalattachpct, rgb2pct, pct2rgb

- autotest/gcore/cog.py
- autotest/gcore/tiff_write.py
- autotest/gdrivers/gpkg.py
- autotest/gdrivers/jp2lura.py
- autotest/gdrivers/test_validate_jp2.py
- autotest/ogr/ogr_gpkg.py
- autotest/pymod/test_py_scripts.py
- autotest/pyscripts/test_gdal2tiles.py
- autotest/pyscripts/test_gdal_calc.py
- autotest/pyscripts/test_gdal_edit.py
- autotest/pyscripts/test_gdal_fillnodata.py
- autotest/pyscripts/test_gdal_ls_py.py
- autotest/pyscripts/test_gdal_merge.py
- autotest/pyscripts/test_gdal_pansharpen.py
- autotest/pyscripts/test_gdal_polygonize.py
- autotest/pyscripts/test_gdal_proximity.py
- autotest/pyscripts/test_gdal_retile.py
- autotest/pyscripts/test_gdal_sieve.py
- autotest/pyscripts/test_gdalinfo_py.py
- autotest/pyscripts/test_gdalmove.py
- autotest/pyscripts/test_ogr2ogr_py.py
- autotest/pyscripts/test_ogrinfo_py.py
- autotest/pyscripts/test_ogrmerge.py
- autotest/pyscripts/test_pct.py
- gdal/swig/python/samples/ogr2ogr.py
test_py_scripts - simplify get_py_script; add samples_path, get_data_dir and use them in tests instead of hardcode paths
This will allow adding/removing/changing Python script/modules paths easily.
This PR also cleanup some redundant spaces and empty lines from the effected files.
I'm not sure if FrankW's folder structure is relevant for anything. if not I'll remove it.
> test_py_scripts - simplify get_py_script; add samples_path, get_data_dir

- autotest/gdrivers/mrf.py
- autotest/gdrivers/wms.py
- gdal/frmts/mrf/LERC_band.cpp
- gdal/frmts/mrf/marfa.h
- gdal/frmts/mrf/mrf_util.cpp
- gdal/frmts/wms/gdalwmsdataset.cpp
- gdal/frmts/wms/minidriver_tiled_wms.cpp
- gdal/frmts/wms/wmsdriver.h
MRF driver can read tiles with LERC encoded data for the WMS driver, but it needs to know the expected NoDataValue.
When combined with the previously existing capability of the WMS driver to pass the expected DataType, this allows a LERC encoded tiled data service to be read correctly via the WMS driver.
* OS:
* Compiler:
> WMS and MRF: Let WMS pass expected NoDataValue to MRF for reading data

- autotest/gdrivers/daas.py
- autotest/gdrivers/daas_real_instance.py
- gdal/doc/source/drivers/raster/daas.rst
- gdal/frmts/daas/daasdataset.cpp
and also use pixelType from bands[] instead of deprecated top-level one
> DAAS: fix pixel retrieval of dataset with UInt16 data type and one mask band (fixes #3061)

- gdal/port/cpl_multiproc.cpp
This is an attempt to improve the "Ironically, creation of this initial mutex is not threadsafe" on Windows with implementation based on the `CRITICAL_SECTION`.
C++11 guarantees:
> Dynamic initialization of a block variable with static storage duration
>  is performed the first time control passes through its declaration (...)
> If control enters the declaration concurrently while the variable is
> being initialized, the concurrent execution shall wait for completion of the initialization.
~ http://eel.is/c++draft/stmt.dcl#4
MSVC guarantees:
> This behaviour is also available starting in Visual Studio 2015
> By default, Visual Studio enables this option.
~ https://docs.microsoft.com/en-us/cpp/build/reference/zc-threadsafeinit-thread-safe-local-static-initialization
Provide environment …
> Make creation of global hCOAMutex thread-safer on Windows

- gdal/port/cpl_multiproc.cpp
Although adding an `CPLAssert(hCOAMutex);` might seem logical
here, do not enable it (see comment below). It calls CPLError that
uses the hCOAMutex itself leading to recursive mutex acquisition
and likely a stack overflow.
Fall back to this, ironically, NOT thread-safe re-initialisation of
hCOAMutex in case of a memory error or call to CPLCleanupMasterMutex
sequenced in an unusual, unexected or erroneous way.
For example, an unusual sequence could be:
- GDALDriverManager has been instantiated,
- then OGRCleanupAll is called which calls CPLCleanupMasterMutex,
- then CPLFreeConfig is called which acquires the hCOAMutex
- that has already been released and destroyed.
Refines #3399
* OS: Windows
* Compiler: MSVC
> Remove too strict CPLAssert checking global hCOAMutex

- gdal/port/cpl_odbc.cpp
Removes the white space trimming from the ODBC fetching code which removes spaces from ODBC text field on retrieval.
The behaviour makes it difficult to use ODBC results for some use cases that consider white space important, and was discovered here https://github.com/pramsey/pgsql-ogr-fdw/issues/208
Either the behaviour should be removed, or made conditional on a run-time option. A compile-time option seems not worth the effort. Initial PR for CI tests, and then can use this PR for final commit or run-time option implementation.
> Remove ODBC text trimming behaviour

- .github/workflows/code_checks.yml
ubuntu-latest is now at 20.04 and causes warnings/errors:
https://github.com/OSGeo/gdal/pull/3424/checks?check_run_id=1810156472
> CI: force code_quality_checks and doxygen to ubuntu 18.04

- .github/workflows/ubuntu_18.04/install.sh
- .github/workflows/ubuntu_18.04_32bit/start.sh
Disable spatialite rttopo support on Ubuntu 18.04
(Fixes #3441)
> CI: Disable spatialite rttopo support on Ubuntu 18.04 (Fixes #3441)

- gdal/ogr/ogrsf_frmts/amigocloud/ogramigocloudlayer.cpp
Handle the date and datetime field types as is, instead of converting them to string type.
> AmigoCloud ogr driver: Fix date/datetime field type handling.

- gdal/docker/README.md
- gdal/docker/alpine-normal/build.sh
- gdal/docker/alpine-small/build.sh
- gdal/docker/alpine-ultrasmall/build.sh
- gdal/docker/ubuntu-full/Dockerfile
- gdal/docker/ubuntu-full/build.sh
- gdal/docker/ubuntu-small/Dockerfile
- gdal/docker/ubuntu-small/build.sh
- gdal/docker/util.sh
The `BASE_IMAGE` argument is never passed to the dockerfile. This makes `ubuntu` the default base image, even if we specify `BASE_IMAGE_NAME` as specified in the readme.
The following code currently succeeds on master (even if the image doesn't exist). After this change the `docker build` process errors as expected.
```
BASE_IMAGE_NAME="nonexistingimage" ./ubuntu-small/build.sh --gdal v3.2.1 --proj 7.2.1 --platform linux/amd64
```
I also added explicitely the `USER root` in the dockerfile since some of these base images might not use it by default. For the current defaults, this is a noop.
* OS:
* Compiler:
> Docker: Rename BASE_IMAGE_NAME to TARGET_IMAGE . Add new parameter BASE_IMAGE

- gdal/docker/util.sh
I am by far experienced in writing bash scripts and had to google every syntax I used. Let me know if you want to rewrite anything. 
Only sets the build arg when the BASE_IMAGE is set, to use the default in the dockerfile when unset. 
#3471
> Docker: Pass BASE_IMAGE build arg conditionally

- gdal/doc/source/drivers/vector/csv.rst
> Fix typo in csv.rst

- gdal/doc/source/drivers/vector/xlsx.rst
Add two examples that illustrate the transformation of CSV files to a spreadsheet.
> XLSX documentation: add examples

- gdal/configure
- gdal/m4/geos.m4
- gdal/m4/sfcgal.m4
This fixes a couple of bugs with finding GEOS and SFCGAL. Firstly, if `--with-geos` or `--with-sfcgal` are passed, but failed to be found, this was silently ignored. This should only happen if the option is 'auto', or people might think things were correctly found when they weren't. Secondly, it also saves `LDFLAGS` when testing compilability, as sometimes flags in `CFLAGS` and `LDFLAGS` go together. 
- [n/a] Add test case(s)
- [n/a] Add documentation
* OS:
* Compiler:
> Fix configure issues finding dependencies

- autotest/gcore/hfa_rfc40.py
- gdal/swig/include/gdal_array.i
- gdal/swig/include/python/gdal_python.i
- gdal/swig/python/osgeo/gdal.py
- gdal/swig/python/osgeo/gdal_array.py
Removes usage of the deprecated aliases in NumPy for types that are standard in Python. 
Fixes #3444.
- [n/a] Add test case(s)
- [n/a] Add documentation
* OS:
* Compiler:
> python: Remove deprecated NumPy aliases for standard types.

- gdal/ogr/ogrsf_frmts/shape/dbfopen.c
- gdal/ogr/ogrsf_frmts/shape/sbnsearch.c
- gdal/ogr/ogrsf_frmts/shape/shapefil.h
- gdal/ogr/ogrsf_frmts/shape/shpopen.c
- gdal/ogr/ogrsf_frmts/shape/shptree.c
Upstream at https://github.com/OSGeo/shapelib/tree/2025ce22196f100a773e2d0bbdc86cfd2ad0ad18
General cleanup.  No functional changes.
- Use stdbool true/false for internal variables
- Localize variables
- Combine variable definition and initialization when possible
- Add const when possible
- Remove or comment out most unused variables
- Remove some extra empty space
- Add some missing headers
- Sort standard headers
- Move static variable to after includes
- Remove RCS/CVS/SVN Id/Revision tags except for SHP_CVSID
- Remove some "goto error;" from shpopen.c
> shapelib: update from upstream: general cleanup; no functional changes

- gdal/doc/source/drivers/vector/dgnv8.rst
- gdal/doc/source/drivers/vector/dwg.rst
- gdal/ogr/ogrsf_frmts/dgn/ogrdgnlayer.cpp
- gdal/ogr/ogrsf_frmts/dwg/ogrdgnv8layer.cpp
This small PR does three things:
* Fix #3496 
* Fix DGN/DWG Ulink output for a specific Application ID (by IPCC/Portugal)
* Fix minor typo in DGN and DWG docs
The current pattern code in both `gdal/ogr/ogrsf_frmts/dgn/ogrdgnlayer.cpp` and `gdal/ogr/ogrsf_frmts/dwg/ogrdgnv8layer.cpp` uses the same `oField` do create all feature fields. I had to reverse the order to prevent the side effect of assigning a `SetSubType` to the previous `oField`.
The current code outputs the first 4 bytes, witch are always the same.
```
OGRFeature(elements):141784
Type (Integer) = 17
Level (Integer) = 3
GraphicGroup (Integer) = 0
ColorIndex (Integer) = 31
Weight (Integer) = 0
Style (Integer) = 0
Text (String) = Quinta das Urzes
ULink (String(JSON)) = { "6549": [ { "size": 8, "domain": "0x10", "subdomain": …
```
> Fix DGN driver Text property type

- .github/workflows/code_checks.yml
- .github/workflows/mingw_w64/install-python.sh
- autotest/gcore/test_driver_metadata.py
- autotest/gdrivers/data/isce/isce.slc.xml
- autotest/ogr/ogr_geojson.py
- autotest/utilities/test_gdalwarp_lib.py
- gdal/apps/gdal_translate_lib.cpp
- gdal/data/gdalvrt.xsd
- gdal/data/netcdf_config.xsd
- gdal/data/ogrvrt.xsd
- gdal/data/pdfcomposition.xsd
- gdal/doc/source/development/rfc/rfc31_ogr_64.rst
- gdal/doc/source/development/rfc/rfc49_curve_geometries.rst
- gdal/doc/source/development/rfc/rfc66_randomlayerreadwrite.rst
- gdal/doc/source/development/rfc/rfc6_sqlgeom.rst
- gdal/doc/source/drivers/raster/gsbg.rst
- gdal/doc/source/drivers/raster/sentinel2.rst
- gdal/doc/source/drivers/vector/netcdf.rst
- gdal/doc/source/tutorials/vector_python_driver.rst
Typos found via`codespell -q 3 -L als,ang,ans,dum,geometrie,hist,iff,inout,lod,merget,nd,objext,oder,oposition,parm,parms,pres,poiter,posession,repid,ressource,sinc,som,sur,te,templat,thare,titel,tre`
Not relevant
Not relevant
> Fix various source comment typos throughout the codebase

- gdal/doc/source/drivers/vector/filegdb.rst
- gdal/doc/source/drivers/vector/sqlite.rst
Fixes the incorrect display of a single en-dash where two dashes should be displayed in 
SQLite / Spatialite RDBMS doc page https://gdal.org/drivers/vector/sqlite.html
and in ESRI File Geodatabase (FileGDB) doc page https://gdal.org/drivers/vector/filegdb.html
> Fix dispaly of two dashes instead of a single en-dash in SQLite and FileGDB doc pages

- gdal/port/cpl_vsil.cpp
- gdal/port/cpl_vsil_s3.cpp
Was tested by uploading a set of "small files" and "big files" from local storage to S3
Test files were generated with:
```
import shutil
import os
dirname = 'small_files'
if not os.path.exists(dirname):
os.mkdir(dirname, 0o755)
for z in range(10):
zdirname = dirname + ('/%02d' %z)
os.mkdir(zdirname, 0o755)
for y in range(10):
ydirname = zdirname + ('/%02d' %y)
os.mkdir(ydirname, 0o755)
for x in range(10):
newfile = open(ydirname + ("/testfile.%02d" % x), "wb")
newfile.write (os.urandom(100 * 1024))
newfile.close ()
dirname = 'large_files'
if not os.path.exists(dirname):
os.mkdir(dirname, 0o755)
for x in range(10):
newfile = open(dirname + ("/testfile.%02d" % x), "wb")
newfile.write (os.urandom(100 * 1024 * 1024))
newfile.close ()
```
And then comparing timing of:
```
time aws s3 cp …
```
> /vsis3/ sync: improve upload performance by setting the default number of threads and increase the chunk size

- autotest/gdrivers/netcdf_multidim.py
- gdal/doc/source/drivers/raster/netcdf.rst
- gdal/frmts/netcdf/netcdfmultidim.cpp
If set, single-dimensional variables will be exposed
as a "virtual" subgroup. This enables the user to get a clearer organization of
variables, for example in datasets where variables belonging to different
trajectories are indexed by different dimensions but mixed in the same netCDF
group.
Useful in particular for datasets such as Sentinel-3 altimetry products, L2 SRAL/MWR
> netCDF multidim: add a GROUP_BY=SAME_DIMENSION option to GetGroupNames()

- autotest/gcore/cog.py
- gdal/doc/source/drivers/raster/cog.rst
- gdal/doc/source/drivers/raster/gtiff.rst
- gdal/frmts/gtiff/cogdriver.cpp
- gdal/frmts/gtiff/geotiff.cpp
Adds `COMPRESS_OVERVIEW` as a configuration option for GTiff overview creation
#3453
> GTiff: allow customising overview compression type (fixes #3453) 

- gdal/doc/source/drivers/vector/gpkg.rst
This has apparently been available since 2.2 but the option does not appear in the documentation.
> Doc: Document OGR_CURRENT_DATE config option used by GeoPackage

- gdal/doc/source/drivers/raster/gpkg.rst
- gdal/doc/source/drivers/vector/gpkg.rst
A follow-up to PR #3519, as [suggested](https://github.com/r-spatial/sf/issues/1618#issuecomment-790633693) by @dbaston.
- referral to the specific time format required by GeoPackage standard
- copy into the documentation of the raster driver, where it has its effect as well
However in relation to binary reproducibility, should the `gpkg_metadata_reference` table not be taken into account as well? It also has a `timestamp` column using the same format (a specific format of ISO 8601) - see [Requirement 100](https://www.geopackage.org/spec120/#r100).
It appears that `gpkg_metadata_reference` is _not_ created [when running](https://github.com/r-spatial/sf/issues/1618#issuecomment-790769027) functions of the R packages `sf` and `stars`, which use GDAL, resulting in reproducible files indeed, …
> Document OGR_CURRENT_DATE config option: update for vector and add to raster

- .github/workflows/android.yml
- .github/workflows/asan_build.yml
- .github/workflows/clang_static_analyzer.yml
- .github/workflows/code_checks.yml
- .github/workflows/conda.yml
- .github/workflows/macos.yml
- .github/workflows/mingw_w64.yml
- .github/workflows/ubuntu_18.04.yml
- .github/workflows/ubuntu_18.04_32bit.yml
- .github/workflows/ubuntu_20.04.yml
- .github/workflows/validate_xml.yml
- .github/workflows/windows_build.yml
- gdal/doc/source/contributing/developer.rst
- gdal/ogr/ogrlinestring.cpp
This should save time and electrons for the many documentation-only PRs.
> CI: Skip GitLab CI for documentation-only commits

- appveyor.yml
This is a continuation of #3529 covering AppVeyor. Unfortunately it doesn't seem like an equally simple solution is possible for Travis.
> CI: Skip AppVeyor for doc-only commits

- autotest/gdrivers/pds4.py
- gdal/data/pds4_template.xml
- gdal/frmts/fits/fitsdataset.cpp
- gdal/frmts/pds/pds4dataset.cpp
- gdal/frmts/pds/pds4dataset.h
as expected by WCS translation.
Also adapt the PDS4 driver in CREATE_LABEL_ONLY=YES mode to alter
the <disp:vertical_display_direction> element (and warn if it is
missing)
Co-authored-by: Even Rouault <even.rouault@spatialys.com>
> FITS: apply vertical mirroring on reading/writing

- appveyor.yml
- gdal/doc/source/contributing/rst_style.rst
- gdal/doc/source/faq.rst
- gdal/doc/source/programs/gdal2tiles.rst
- gdal/doc/source/programs/gdal_calc.rst
- gdal/doc/source/software_using_gdal.rst
- gdal/doc/source/tutorials/wktproblems.rst
Attempt to fix AppVeyor skip config set in #3533. I will push a doc-only commit shortly to check that this is working.
> CI: Fix AppVeyor skip for doc-only commits

- gdal/swig/include/perl/gdal_perl.i
Warn when Perl bindings are used unless an environment variable has been defined to suppress it.
> Deprecate Perl bindings in 3.5

- autotest/osr/osr_url.py
- gdal/ogr/ogrspatialreference.cpp
This allows https:// to be used when looking up CRS 
fixes #3548
* OS:
* Compiler:
> OGRSpatialReference::SetFromUserInput() allow https:// when loading CRS from opengis.net

- gdal/ogr/ogrsf_frmts/amigocloud/ogramigocloudtablelayer.cpp
AmigoCloud uses fid of type String ("amigo_id"). This change is a work around to handle the query with nFeatureId as a string value.
> AmigoCloud driver: fix GetFeature

- gdal/doc/source/drivers/vector/cad.rst
AFAIK, the new repository, with 0.3.4 version, is https://github.com/nextgis-borsch/lib_opencad the previous was the GSoC @BishopGIS
* OS:
* Compiler:
> DOC: CAD Driver: update libopencad repository

- gdal/frmts/wms/gdalhttp.cpp
- gdal/frmts/wms/wmsdriver.h
- gdal/port/cpl_curl_priv.h
- gdal/port/cpl_http.cpp
- gdal/port/cpl_vsil_curl.cpp
- gdal/port/cpl_vsil_curl_class.h
- gdal/port/cpl_vsil_webhdfs.cpp
Delegation type can be set using CPLHTTPSetOptions option 'GSSAPI_DELEGATION'
or CPLGetConfigOption option 'GDAL_GSSAPI_DELEGATION'
See: https://curl.se/libcurl/c/CURLOPT_GSSAPI_DELEGATION.html
> CPLHTTP: Allow to set GSSAPI credential delegation type

- autotest/ogr/ogr_geos.py
- autotest/pymod/ogrtest.py
- gdal/ogr/ogrgeometry.cpp
Avoid throwing an exception for certain invalid geometries when calling `OGRGeometry::IsValid` from SWIG bindings.
#3578
> OGR: Avoid SWIG generating exception on OGRGeometry::isValid

- gdal/ogr/ogrsf_frmts/flatgeobuf/ogr_flatgeobuf.h
- gdal/ogr/ogrsf_frmts/flatgeobuf/ogrflatgeobufdataset.cpp
- gdal/ogr/ogrsf_frmts/flatgeobuf/ogrflatgeobuflayer.cpp
Issue hinted by clang static analyzer.
Note to @bjornharrtell : you can't use std::is_base_of<> as a way of determining at run-time if an object can be dynamically cast to some type. std::is_base_of<> is a mechanism operating only on types (at compilation time), and not instances.
> FlatGeoBuf: fix crash in GetFileList() on a dataset opened in update mode

- autotest/gcore/basic_test.py
- autotest/gcore/numpy_rw.py
- autotest/gcore/rasterio.py
- autotest/gcore/tiff_ovr.py
- autotest/gdrivers/mrsid.py
- gdal/swig/include/Band.i
- gdal/swig/include/Dataset.i
- gdal/swig/include/MultiDimensional.i
- gdal/swig/include/cpl.i
- gdal/swig/include/gdal.i
- gdal/swig/include/gdal_array.i
- gdal/swig/include/python/gdal_python.i
- gdal/swig/include/python/typemaps_python.i
- gdal/swig/python/extensions/gdal_array_wrap.cpp
- gdal/swig/python/extensions/gdal_wrap.cpp
- gdal/swig/python/extensions/ogr_wrap.cpp
- gdal/swig/python/osgeo/gdal.py
- gdal/swig/python/osgeo/gdal_array.py
Several improvements:
- accept any memoryview (includes bytes, bytearray objects) as input of WriteRaster()
- return a bytearray object as output of ReadRaster() (and if passing buf_obj, accept a writeable memoryview)
- add buf_obj argument to ReadRaster()
- add band_list argument to Dataset.ReadAsArray()
- add Dataset.WriteArray()
- improve input value validation in typemaps for GDALRioResampleAlg and GDALDataType
> Python bindings: improvements in [Read|Write][Raster|Array] methods

- gdal/doc/source/programs/gdal_translate.rst
Add clarifying note about gdal_translate scale ranges
https://lists.osgeo.org/pipermail/gdal-dev/2021-March/053694.html
> Doc: Add clarifying note about gdal_translate scale ranges

- gdal/doc/source/programs/gdal_edit.rst
colorinterp_X fails with, for example: "Unrecognized option : colorinterp_1=gray" if '-' flag isn't used.
* OS:
* Compiler:
> added necessary '-' to option

- gdal/frmts/ecw/gdal_ecw.h
This is only for original 5.4 version. ECW SDK 5.4 update 1 or 5.5 build fine.
> ECW: fix build with original ECW SDK 5.4 (fixes #2776)

- gdal/configure
- gdal/configure.ac
Configure script needs to add the jpeg external static library before to test libtiff, to add the correct library inclusion flags to the conftest compilation. Otherwise the compilation fails with unresolved external symbols for libjpeg.
Fixes gdal compilation error when looking for libtiff support by searching first for libjpeg. 
* OS: Linux
* Compiler: gcc/clang
> Compilation:Fix gdal compilation when using latest proj and libtiff with static jpeg

- gdal/ogr/ogr_core.h
- gdal/swig/include/ogr.i
The C #define has a unfortunate trailing space at the end of the
string. We must also replicate that in SWIG.
> SWIG: fix expansion of ODsCRandomLayerWrite

- .github/workflows/windows_build.yml
This is just a cosmetic change, but I'm completely newbie here, so please excuse me if I made something wrong. 
The use of deprecated "::set-env"/"::set-path" can be dropped from the Windows build workflow. It also makes the `ACTIONS_ALLOW_UNSECURE_COMMANDS` flag unnecessary.
Notes:
- In the `shell: cmd` steps, must NOT add spaces before `>>`, or they will be included in the environment variable. See `%INCLUDE%>> %GITHUB_ENV%`
- The environment file `GITHUB_PATH`, appears not to work for multiple entries. This is why the `PATH` is still exported via `GITHUB_ENV`
> Drop the deprecated "::set-env" workflow commands

- autotest/ogr/ogr_gpkg.py
- gdal/doc/source/drivers/raster/gpkg.rst
- gdal/doc/source/drivers/vector/gpkg.rst
- gdal/ogr/ogrsf_frmts/gpkg/ogr_geopackage.h
- gdal/ogr/ogrsf_frmts/gpkg/ogrgeopackagedatasource.cpp
- gdal/ogr/ogrsf_frmts/gpkg/ogrgeopackagedriver.cpp
- gdal/swig/python/gdal-utils/osgeo_utils/samples/validate_gpkg.py
Fixes #2479
Nothing particularly exciting. GeoPackage 1.3 is very compatible with 1.2. The only changes done in the driver are:
- accept user_version 103XX (raised a warning before). To be backported in 3.2 branch
- no longer create triggers on gpkg_metadata and gpkg_metadata_reference tables. This change is also mostly backward compatible with 1.2 and will be done in it unconditionally.
- add a VERSION=1.3 creation option. Default remains at 1.2
The rest of changes are enhancements in validate_gpkg.py script
> Add support for GeoPackage 1.3

- gdal/frmts/tiledb/tiledbdataset.cpp
If trying to open a /vsis3/ TIFF file without appropriate /vsis3/
credentials, it takes a few seconds to the TileDB driver to realize
t can't open it. So avoid it trying when the extension if tif.
A bit of a hack...
CC @normanb : this is more a workaround than a proper fix. There's probably something to improve on the tiledb lib side. GDAL's /vsis3/ is much faster to realize that it can't do the connection to S3.
> TileDB: do not try to identify /vsis3/ files ending with .tif

- autotest/pyscripts/test_gdal_utils.py
- gdal/swig/python/gdal-utils/osgeo_utils/auxiliary/base.py
- gdal/swig/python/gdal-utils/osgeo_utils/auxiliary/color_palette.py
- gdal/swig/python/gdal-utils/osgeo_utils/auxiliary/raster_creation.py
- gdal/swig/python/gdal-utils/osgeo_utils/auxiliary/util.py
improve get_ovr_idx:
def get_ovr_idx(filename_or_ds: PathOrDS, ovr_idx: Optional[Union[int, float]]):
"""
returns a non-negative ovr_idx, from a given ovr_idx number
for ovr_idx = None => returns 0
for ovr_idx: int >= 0 => returns the given ovr_idx
for ovr_idx: int < 0 => -1 is the last overview; -2 is the one before the last and so on
for ovr_idx: float => returns the best overview by the given resolution (ovr_idx represents the resolution in this case)
"""
This PR also adds some other basic utility functions and testing
> util.py - get_ovr_idx to support selecting by resolution + some utility functions + testing

- autotest/gdrivers/gpkg.py
- autotest/ogr/ogr_gpkg.py
- gdal/doc/source/drivers/vector/gpkg.rst
- gdal/ogr/ogrsf_frmts/gpkg/ogr_geopackage.h
- gdal/ogr/ogrsf_frmts/gpkg/ogrgeopackagedatasource.cpp
- gdal/ogr/ogrsf_frmts/gpkg/ogrgeopackagedriver.cpp
- gdal/ogr/ogrsf_frmts/gpkg/ogrgeopackagetablelayer.cpp
- gdal/swig/python/gdal-utils/osgeo_utils/samples/validate_gpkg.py
This option has now long lived and is superseded by the
data_type='attributes' supported since GeoPackage 1.2 / GDAL 2.2.
Only keep read support for it.
Also remove the creation of the dummy ogr_empty_table special table that
was made to be compliant with Requirement 17 that has now been retired.
> GPKG: remove creation support for data_type='aspatial' legacy tables

- gdal/doc/source/api/csharp.rst
Removes some broken link from the docs
- Remove the link to buildbot
- remove the link to CodePlex Archive which will shutdown in 2 months
None
This is a documentation only change.
* OS: All
* Compiler: None
> Minor fixes for the C# docs

- autotest/gdrivers/envi.py
- autotest/gdrivers/genbin.py
- gdal/frmts/pds/pds4dataset.cpp
- gdal/gcore/gdaldataset.cpp
- gdal/gcore/rawdataset.cpp
- gdal/gcore/rawdataset.h
Raw datasets with BIP interleaving used to allocate for each band a
buffer of raster_width * data_type_size * nbands, which resulted in a
quadratic RAM allocation in number of bands. This could prevent opening
of large files and resulted in suboptimal speed at reading/writing.
Proper fix for #3213
>  ENVI, Ehdr, etc: lower memory req. for BIP interleave, and improve efficiency

- .github/LICENSE.TXT
- CONTRIBUTING.md
move LICENSE.TXT from gdal subdir to the root dir so that it will be picked up by [github interface](https://github.com/OSGeo/gdal/community).
> add a symlink to LICENSE.TXT in .github subdir

- gdal/port/cpl_port.h
Microsoft have deprecated str{n,}casecmp and str{n,}icmp
Before this change I get a deprecation warning from cpl_port.h when I use the EQUAL and EQUALN macros when building a stand-alone/plugin driver on Windows with the conda gdal, WIN10 SDK and the mingw-m64 clang11 compiler
None recorded, but the issue was discussed in
https://lists.osgeo.org/pipermail/gdal-dev/2021-April/053856.html
Windows with the conda gdal, WIN10 SDK and the mingw-m64 clang11 compiler
> Microsoft have deprecated str{n,}casecmp and str{n,}icmp

- gdal/doc/source/api/index.rst
- gdal/doc/source/api/python.rst
gdal/doc/source/api/[python.rst, index.rst] - rewrite the Python Examples section and move the Python API link with the rest of the Python stuff links
https://github.com/OSGeo/gdal/pull/3678
> Python sphinx docs reorganize

- gdal/NEWS
Correct version number typo in GDAL 3.3 NEWS
> Correct typo in GDAL 3.3 NEWS

- gdal/doc/source/programs/gdal2tiles.rst
There is a missing command line option (-x, --exclude) for gdal2tiles.py.
Reference: https://github.com/OSGeo/gdal/blob/5d233d423a4be9e4c75fd611da841f66f8c50065/gdal/swig/python/gdal-utils/osgeo_utils/gdal2tiles.py#L1362
* OS:
* Compiler:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/osgeo/gdal/3699)
> gdal2tiles.rst - Add missing -x, --exclude option

- gdal/doc/source/drivers/raster/stacta.rst
Fix broken URL to:
- https://github.com/stac-extensions/tiled-assets
> stacta manual: new tiled-assets URL

- autotest/gcore/overviewds.py
- gdal/frmts/gtiff/geotiff.cpp
- gdal/frmts/jp2kak/jp2kakdataset.cpp
- gdal/frmts/jpeg/jpgdataset.cpp
- gdal/frmts/openjpeg/openjpegdataset.cpp
- gdal/frmts/vrt/vrtrasterband.cpp
- gdal/gcore/gdal_priv.h
- gdal/gcore/gdaldataset.cpp
- gdal/gcore/gdaloverviewdataset.cpp
- gdal/gcore/gdalrasterband.cpp
and also "{x}only". This however needs cooperation from drivers.
I've just updated the GTiff, JP2KAK, JPEG, OpenJPEG and VRT ones. Others
would need similar changes in their specific GetOverviewCount() / IRasterIO()
implementation.
Fixes https://github.com/OSGeo/gdal/pull/3181#issuecomment-822868290
> Fix OVERVIEW_LEVEL=NONE open option

- gdal/doc/source/sponsors/index.rst
On the PDF in the same folder the sponsor level is called `Platinum` so I assume the rst-file has a typo.
> Small typo fix for sponsor level name

- autotest/pyscripts/test_gdal_calc.py
- gdal/swig/python/gdal-utils/osgeo_utils/auxiliary/gdal_argparse.py
- gdal/swig/python/gdal-utils/osgeo_utils/epsg_tr.py
- gdal/swig/python/gdal-utils/osgeo_utils/esri2wkt.py
- gdal/swig/python/gdal-utils/osgeo_utils/gdal2xyz.py
- gdal/swig/python/gdal-utils/osgeo_utils/gdal_calc.py
- gdal/swig/python/gdal-utils/osgeo_utils/samples/gdallocationinfo.py
gdal_argparse.py - GDALArgumentParser an extended `argparse.ArgumentParser` to be used with all `gdal-utils`
gdal_calc.py - use `GDALArgumentParser ` instead of the old `optparse.OptionParser` 
use minor improvements to `ArgumentParser` uses in other utils
> ArgumentParser: gdal_calc + others

- .github/workflows/asan/start.sh
- .github/workflows/ubuntu_18.04/install.sh
- .github/workflows/ubuntu_18.04_32bit/start.sh
- gdal/GDALmake.opt.in
- gdal/ci/travis/graviton2/install.sh
- gdal/ci/travis/s390x/install.sh
Besides being useless, it was found to cause a hang in the OpenCL's call
clGetPlatformIDs() of gdalwarp when linking against ECW SDK...
> GDALmake.opt.in: in non-libtool LD_SHARED builds, do not link applications against libgdal dependencies, but only against libgdal itself

- gdal/swig/makefile.vc
- gdal/swig/python/GNUmakefile
CC @idanmiara 
I noticed this during the build of one of the Docker image that threw the following warning:
```
for f in `ls ./scripts/*.py` ; do  /gdal/gdal/install-sh -c $f /build/usr/bin ; done
ls: ./scripts/*.py: No such file or directory
make[2]: Leaving directory '/gdal/gdal/swig/python'
make[1]: Leaving directory '/gdal/gdal/swig'
```
> swig/python/GNUmakefile and swig/makefile.vc: remove useless command to install scripts in bin directory

- gdal/doc/source/drivers/raster/cog.rst
Adds minor improvements to the COG docs to clarify which compression methods are used by default.
As clarified by Even in IRC.
> docs: Mention default compressions for COG

- autotest/gcore/tiff_write.py
- gdal/frmts/gtiff/geotiff.cpp
Creating a COG file with nodata=NaN could result in the overviews
being corrupted.
CC @kannes This fixes the issue you reported yesterday on #gdal
> GTIFF/COG: fix overviews with NaN nodata value

- gdal/swig/python/gdal-utils/osgeo_utils/auxiliary/color_table.py
- gdal/swig/python/gdal-utils/osgeo_utils/gdalattachpct.py
fix some minor bugs for GDAL 3.3
`color_table.py` - fix some inaccurate type hints
`gdalattachpct.py` -  `driver_name` was not initialized so it might crash if no `-of` is provided.
> type hints fix and variable init

- gdal/swig/python/gdal-utils/osgeo_utils/__init__.py
- gdal/swig/python/gdal-utils/setup.py
`gdal/swig/python/gdal-utils/osgeo_utils/__init__.py` - `gdal-utils` version: add `gdal_utils_version` and bump `__version__`
`gdal/swig/python/gdal-utils/[setup|osgeo_utils/__init__].py` - fix typo `__pacakge_name__ ` ->  `__package_name__`
> `gdal-utils` version: add `gdal_utils_version` and bump `__version__`; fix typo

- .github/workflows/windows_build.yml
- gdal/swig/csharp/makefile.vc
fixes #3711 
This fixes the problem. It is based on a concatenation of the various threads about this across the web.
The effect seems to be widespread. The cause seems to be some as yet unidentified change in the vs2019 environment.
> Fix for .net core build error fixes #3711

- autotest/pyscripts/test_gdal_utils.py
- autotest/pyscripts/test_osr_util.py
- gdal/swig/python/gdal-utils/osgeo_utils/auxiliary/array_util.py
- gdal/swig/python/gdal-utils/osgeo_utils/auxiliary/osr_util.py
- gdal/swig/python/gdal-utils/osgeo_utils/samples/gdallocationinfo.py
This PR solves two issues, I wanted to separate them but apparently for writing proper tests that don't depend on `numpy` I needed to merge them.  
I've added many tests for to make it right this time...
1.
`osr_util.py` depends on numpy. this PR remove this dependency.
`osgeo_utils/auxiliary/array_util.py` - add `ArrayLike`, `ScalarLike`, `ArrayOrScalarLike` types (replaces `NumpyCompatibleArray`, `NumpyCompatibleArrayOrReal`)
osr_util.py, gdallocationinfo.py, numpy_util.py - use new types
autotest/pyscripts/test_gdal_utils.py - test new types
2.
osr_util.py - add `default_axis_order` flag to allow the user to change the default
some applications use `gis_order`, this PR will allow them to override the default if they wish by adding the following code to their package/module …
> `osr_util.py` - bugfix and add `default_axis_order` flag; `arrays.py` - add types to remove dependency on `numpy`

- autotest/pyscripts/test_gdal_utils.py
- autotest/pyscripts/test_osr_util.py
- gdal/swig/python/gdal-utils/osgeo_utils/auxiliary/array_util.py
- gdal/swig/python/gdal-utils/osgeo_utils/auxiliary/osr_util.py
- gdal/swig/python/gdal-utils/osgeo_utils/samples/gdallocationinfo.py
backport https://github.com/OSGeo/gdal/pull/3778
> Backport 3.3 (#3778): osr_util.py - bugfix and add default_axis_order flag; arrays.py - add types to remove dependency on numpy

- autotest/gcore/rat.py
- gdal/frmts/gtiff/geotiff.cpp
Fixes #3783 by making sure that the PAM is
read before setting the RAT.
Without that, when serializing the PAM,
`GTiffDataset::LoadGeoreferencingAndPamIfNeeded()`
is called, but if it wasn't called before it will
reload the RAT from the old `xml` that at this
point contains the old RAT effectively overwriting
any change made by `SetDefaultRat()` call.
> Fix RAT SetDefaultRAT for GTiff driver

- autotest/ogr/ogr_wkbwkt_geom.py
- gdal/ogr/ogrutils.cpp
Allow input WKT strings to span multiple lines.
https://github.com/r-spatial/sf/issues/1674
> OGR: Support multiline WKT input

- gdal/ogr/ogrsf_frmts/vrt/ogrvrtlayer.cpp
If the geometry column names contain a space the query requires the name to be quoted to avoid query parsing errors
> ogr_vrt: Fix vrt spatial filter for geometry columns with space

- autotest/gcore/vsiaz.py
- gdal/port/cpl_vsil_az.cpp
Should avoid an issue occuring sometimes with appending blocks to Azure
AppendBlob. It appears that the uploaded size is different, and we may be
appending blocks multiple times due to timeouts/failures. Not sure if the
operation succeeds on the server-side, but the client does not get a
response and retries, but we see server timeouts in these cases.
Based on patch by Robin Princeley
> /vsiaz/: avoid appending same chunk several times

- gdal/frmts/postgisraster/postgisraster.h
- gdal/frmts/postgisraster/postgisrasterdataset.cpp
- gdal/frmts/postgisraster/postgisrasterdriver.cpp
This PR allow users to use just the service name in Postgis raster driver connection strings.
All the support was already there. The condition to check if there is a dbname was changed, to check if we have a database or a service name. We only report failure if both are not present.
```bash
$ gdalinfo "PG:service=ortos schema=ortos table=ortos_2018_2k_desertas column=rast mode=2"
Driver: PostGISRaster/PostGIS Raster driver
Files: none associated
Size is 96000, 220000
Coordinate System is:
BOUNDCRS[
SOURCECRS[
PROJCRS["PTRA08 / UTM zone 28N",
(...)
Data axis to CRS axis mapping: 1,2
Origin = (354000.000000000000000,3607300.000000000000000)
Pixel Size = (0.100000000000000,-0.100000000000000)
Corner Coordinates:
Upper Left  (  354000.000, 3607300.000) ( 16d33'20.63"W, 32d35'36.87"N)
Lower …
```
> Improve Postgis raster support for libpq services (fixes #3820)

- .github/workflows/fedora_rawhide.yml
- autotest/conftest.py
Should fix the recent MacOSX failures
(https://github.com/OSGeo/gdal/runs/2554610301)
and the ones on Fedora Rawhide (fixes #3814)
> autotest: fixes strange issues when importing files of autotest 

- autotest/pyscripts/test_gdallocationinfo_py.py
- gdal/swig/python/gdal-utils/osgeo_utils/auxiliary/osr_util.py
- gdal/swig/python/gdal-utils/osgeo_utils/auxiliary/raster_creation.py
- gdal/swig/python/gdal-utils/osgeo_utils/auxiliary/util.py
- gdal/swig/python/gdal-utils/osgeo_utils/samples/gdallocationinfo.py
* gdal/swig/python/gdal-utils/osgeo_utils/auxiliary/util.py - add `ovr_only: bool = False` parameter to `_open_ds`
* gdal/swig/python/gdal-utils/osgeo_utils/auxiliary/osr_util.py - change `transform_points()` to return None as it makes an inline replacement
* gdal/swig/python/gdal-utils/osgeo_utils/samples/gdallocationinfo.py - fix inline_xy_replacement; fix unscaling; fix formatting; use faster `BandRasterIONumPy` instead of `band.ReadAsArray`; add optional parameters `return_ovr_pixel_line`, `transform_round_digits`
* autotest/pyscripts/test_gdallocationinfo_py.py - add another test
> `gdallocationinfo` fixes + more tests

- autotest/gdrivers/ecw.py
- gdal/frmts/ecw/ecwdataset.cpp
- gdal/frmts/ecw/ecwsdk_headers.h
Enabled reading ECW files from virtual file systems.
I'm inspect `libecwj2-3.3` source code, [ `CNCSJPCFileIOStream::SetIOCallbacks`](https://github.com/sasgis/libecwj2/blob/93d7869826c36df85f45fc23d767d52dee9e529b/Source/C/NCSEcw/NCSJP2/NCSJPCFileIOStream.cpp#L302) affects only on ECW [decompress](https://github.com/sasgis/libecwj2/blob/93d7869826c36df85f45fc23d767d52dee9e529b/Source/C/NCSEcw/shared_src/fileio_decompress.c#L83) path and we can't `GDAL_DCAP_VIRTUALIO` flag to `YES`.
See: https://trac.osgeo.org/gdal/ticket/6482
> ECW: Register VSIL functions as IO callbacks for ECW=3.3

- autotest/pyscripts/test_gdal_utils.py
- gdal/swig/python/gdal-utils/osgeo_utils/auxiliary/base.py
This PR fixes the `num` auxiliary function. 
Before this PR `num(f: float)` returned `int(f)`
i.e. num(42.5)` returned 42 (instead of 42.5)
Tests added for this case.
> gdal-utils/osgeo_utils/auxiliary/base.py - fix `num()`

- gdal/doc/source/programs/gdallocationinfo.rst
Reverts OSGeo/gdal#2524
x y can be supplied interactively.
> Revert "gdallocationinfo.rst: x y mandatory"

- gdal/gcore/gdal_mdreader.cpp
> fixed issue with GDALLoadRPBFile failing when RPB file does not contain errBias or errRand fields

- gdal/ogr/ogr_geometry.h
- gdal/ogr/ogrgeometryfactory.cpp
Add an optional size argument to `OGRGeometryFactory::createFromGeojson` for non-null terminated strings
* Compiler: gcc 9
> createFromGeoJson: support non-null terminated #3870
