OSGeo/gdal

gdal/doc/source/sponsors/faq.rst
This PR affects the Sponsors > Faq docs page. It changes an instance of md hyperlink to rst so that it renders properly - see first paragraph: https://gdal.org/sponsors/faq.html#sponsoring-faq. It also addresses two minor grammar nits.
None
NA
=> Sponsoring FAQ doc page: fix link format, grammar nits

autotest/pyscripts/test_gdal_utils.py, gdal/swig/python/gdal-utils/osgeo_utils/auxiliary/util.py
osgeo_utils/auxiliary/util.py - fix `get_bands()` for `ovr_idx==0` + added tests
https://github.com/OSGeo/gdal/pull/3838
=> osgeo_utils/auxiliary/util.py - fix `get_bands()` for `ovr_idx==0` + added tests

gdal/doc/source/drivers/vector/gpkg.rst
Add a note about configuration option OGR_SQLITE_JOURNAL to the documentation of the GeoPackage driver.
=> Add note about config option OGR_SQLITE_JOURNAL (GPKG)

gdal/gcore/gdal_priv.h
Update doxygen
`GDALMDArray::GetFilename` does not exist before GDAL 3.4
=> GetFilename does not exit before GDAL 3.4

autotest/ogr/ogr_sql_rfc28.py, autotest/ogr/ogr_wfs.py, gdal/ogr/ogr_swq.h, gdal/ogr/swq.cpp, gdal/ogr/swq_parser.cpp, gdal/ogr/swq_parser.y
(fixes #3919, fixes qgis/QGIS#43181)
=> OGRSQL: fix wrong evaluation of attribute filter when a OR with >= 3 clauses is nested inside in another OR

.github/workflows/windows_build.yml, gdal/swig/python/osgeo/__init__.py
Prevent FileNotFoundError that can happen when importing from osgeo on Windows, python>=3.8.
I didn't see anywhere obvious to put a test case for this specific import behavior, let me know if that should go somewhere.
Fixes #3898 
* OS:
* Compiler:
=> Python import: fix FileNotFoundError when PATH has nonexistent paths (fixes #3898)

gdal/ogr/ogr_srsnode.cpp
This PR prevents putting quotes around the spatial CS type, such as `Cartesian`, inside the CS node of the WKT.
WKT reference: http://docs.opengeospatial.org/is/18-010r7/18-010r7.html#45
Before this PR, the following code fails to generate a WKT because it puts quotes around `Cartesian` and fails this check in proj: https://github.com/OSGeo/PROJ/blob/29f849485bf2ea9caa7ca3da7d93ece1daf4d7d5/src/iso19111/io.cpp#L2727. This problem was triggered by a fairly exotic WKT that preserved the `CS` node after being imported and after manipulating the nodes. A minimal repro is below:
```
#include <gdal.h>
#include <ogr_spatialref.h>
#include <stdio.h>
int main() {
const char* wkt = "DERIVEDPROJCRS[\"unnamed\",BASEPROJCRS[\"unnamed\",BASEGEOGCRS[\"WGS 84\",DATUM[\"World Geodetic System 1984\", …
```
=> WKT: prevent putting quotes around spatial CS type

gdal/ogr/ogrspatialreference.cpp
This PR adds `DERIVEDPROJCRS` to the list of WKT keywords when using `OGRSpatialReference::SetFromUserInput`. After this PR, `OGRSpatialReference::SetFromUserInput` works identically to `OGRSpatialReference::importFromWkt` with a WKT containing `DERIVEDPROJCRS`.
Minimal repro:
```
#include <gdal.h>
#include <ogr_spatialref.h>
#include <stdio.h>
int main() {
const char* wkt = "DERIVEDPROJCRS[\"unnamed\",BASEPROJCRS[\"unnamed\",BASEGEOGCRS[\"WGS 84\",DATUM[\"World Geodetic System 1984\", ELLIPSOID[\"WGS 84\",6378137,298.257223563,LENGTHUNIT[\"metre\",1]]],PRIMEM[\"Greenwich\",0,ANGLEUNIT[\"degree\",0.0174532925199433]],ID[\"EPSG\",4326]],CONVERSION[\"Oblique Stereographic\",METHOD[\"Oblique Stereographic\",ID[\"EPSG\",9809]],PARAMETER[\"Latitude of natural …
```
=> WKT: Add `DERIVEDPROJCRS` to WKT keywords for `OGRSpatialReference::SetFromUserInput`

gdal/doc/source/programs/gdal_calc.rst
Add missing backtick in https://gdal.org/programs/gdal_calc.html
=> Fix fomatting issue in gdal_calc.py doc

gdal/doc/source/programs/gdaltindex.rst, gdal/doc/source/programs/index.rst
- it updates the documentation of [gdaltindex](https://gdal.org/programs/gdaltindex.html#gdaltindex). 
`gdaltindex` meanwhile can create all OGR-supported datasets and is not limited to Shapefile anymore. 
- it also updates the basic example for using GeoPackage instead of Shapefile
Please let me know if `OGR-supported dataset` is the correct wording in this case. Otherwise I am happy to correct.
- not found
=> Doc: update gdaltindex output formats

gdal/doc/source/tutorials/osr_api_tut.rst, gdal/ogr/ogrspatialreference.cpp
* gdal/ogr/ogrspatialreference.cpp - SetWellKnownGeogCS: update the docs, reformat WKT strings.
* gdal/doc/source/tutorials/osr_api_tut.rst - add a reference to "CRS27", "CRS83" or "CRS84" in the "CRS and axis order" section
=> ogrspatialreference.cpp - SetWellKnownGeogCS: update the docs, reformat WKT strings.

autotest/gdrivers/jp2openjpeg.py, gdal/doc/source/drivers/raster/jp2openjpeg.rst, gdal/frmts/openjpeg/openjpegdataset.cpp
to write Tile-part Length Marker.
Depends on openjpeg >= 2.5.0 / https://github.com/uclouvain/openjpeg/pull/1359
=> JP2OpenJPEG: add a TLM=YES creation option

autotest/gdrivers/nitf.py, gdal/doc/source/drivers/raster/nitf.rst, gdal/frmts/nitf/nitfdataset.cpp, gdal/frmts/openjpeg/openjpegdataset.cpp
To comply with STDI-0006 NITF Version 2.1 Commercial Dataset Requirements Document (NCDRD)
=> NITF: add PROFILE=NPJE_VISUALLY_LOSSLESS/NPJE_NUMERICALLY_LOSSLESS with JP2OpenJPEG driver

autotest/gcore/vsiswift.py, gdal/doc/source/user/virtual_file_systems.rst, gdal/port/cpl_swift.cpp, gdal/port/cpl_swift.h
Two fixes for OpenStack Swift Objectstore endpoint URL detection:
1. When parsing an openstack list of endpoints, the swift endpoint may not necessarily be named "swift". However it will always have the `"type": "object-store"`. Change logic to look for `"type"`, rather than `"name"`.
2. OpenStack endpoint URLs can come in threes, eg: three different "interfaces" each with their own URL, for "public", "admin", or "internal". Add logic to check for interface type, look for "public" (or choose the first URL if "interface" not present).
OpenStack Swift feature addition: When using `OS_IDENTITY_API_VERSION=3`, in authVersion3 mode, allow the use of application_credential authentication if:
* OS_IDENTITY_API_VERSION == "3"
* OS_AUTH_TYPE == "v3applicationcredential"
* …
=> Fix openstack swift endpoint detection, add application_credential authentication support

gdal/apps/testreprojmulti.cpp
When trying to build GDAL I had a compilation issue. poCT is of type OGRCoordinateTransformation which has no method called TranformEx() however it does have a method called Transform() which states in the comments in ogr_spatialref.h : "This method is the same as the C function OCTTransformEx()." .
=> Updated pointer: poCT in testrepojmulti.cpp to call correct "Transform" method

gdal/makefile.vc
makefile.vc was calling linux utilites: "rm", "cp" and "zip" inside of the windows makefile. This was causing an error when I was building the windows build on my local machine. I have updated the section to check if the $(DISTDIR) exists and if not make the directory and then copy the gdal build artefacts into the $(DISTDIR).
=> Removed linux commands in makefile.vc

autotest/gcore/numpy_rw.py, gdal/frmts/gtiff/geotiff.cpp
Reproducer/test case provided by @sgillies
=> GTiff signedbyte: do not write 0 values for tiles/strips entirely at a negative nodata value (fixes #3984)

gdal/ogr/ogrsf_frmts/geojson/ogrgeojsonwriter.cpp
Transform CPLDebug into CPLError
Rationale:
This is a serious error condition that causes the function to fail and to set a null geometry for the feature
Without it, a NULL geometry is returned and there is no `LastErrorMsg`
It doesn't break any unit tests
Refs: #4004
=> Error msg when geometry is not supported in GeoJSON

gdal/ogr/ogrsf_frmts/oci/ogrocidatasource.cpp
With TRUNCATE the Oracle table already exists and there should be a row in USERS_SDO_GEOM_METADATA, for which the extent will be updated.
Don't try to create a new row in USERS_SDO_GEOM_METADATA (otherwise fails with ORA-13223).
OCI TRUNCATE option now works correctly (doesn't give exception).
Fixes issue #4027 
Test case - Create a table in Oracle from a source layer, and then try to reload the data into the same table:
```
ogr2ogr -progress -f OCI -nln OGR_TEST -lco GEOMETRY_NAME=geom -lco SRID=27700 -lco LAUNDER=YES OCI:/@mydb: test.gdb test_layer
ogr2ogr -progress -f OCI -nln OGR_TEST -lco TRUNCATE=YES -lco GEOMETRY_NAME=geom -lco SRID=27700 -lco LAUNDER=YES OCI:/@mydb: test.gdb test_layer
```
* OS: Windows 10 x64
* Compiler: MSCV 2015
=> OCI: Don't try to create new layer with TRUNCATE option (fixes #4027)

autotest/osr/osr_basic.py, gdal/ogr/ogrspatialreference.cpp
This PR adds ellipsoidal and spherical coordinate system support for `OGRSpatialReference::GetLinearUnits`, as long as they have a third axis for height.
Before this PR, if you called `SetLinearUnits` on an ellipsoidal/spherical coordinate system with a non-`1.0` value it would store the units correctly, but if you followed that with a call to `GetLinearUnits` it would return `1.0`. However, this wasn't a problem with `GetTargetLinearUnits` because it would return the cached result.
I tested with the following code:
```
#include <gdal.h>
#include <ogr_spatialref.h>
#include <stdio.h>
int main() {
{
OGRSpatialReference srs;
OGRErr err0 = srs.SetFromUserInput("EPSG:4979");
OGRErr err1 = srs.SetLinearUnits("unnamed", 0.5);
const double units = srs.GetLinearUnits();
printf("Value: %f\n", …
```
=> OGRSpatialReference: Support GetLinearUnits for ellipsoidal and spherical coordinate systems that have a height axis

autotest/gcore/data/pixfun_pow.vrt, autotest/gcore/pixfun.py, autotest/gdrivers/vrtderived.py, gdal/doc/source/drivers/raster/vrt.rst, gdal/frmts/vrt/pixelfunctions.cpp, gdal/frmts/vrt/vrtdataset.h, gdal/frmts/vrt/vrtderivedrasterband.cpp, gdal/gcore/gdal.h
This commit introduces a new pixel function signature,
GDALDerivedPixelFuncWithArgs, that extends GDALDerivedPixelFunc with an
additional argument of named string arguments. These arguments can be
specified using the PixelFunctionArguments tag already used for pixel
functions defined in Python. It is the responsibility of the pixel
function to check the validity of its own arguments.
Not aware of any.
=> VRT: Support named arguments to C++ derived band pixel functions

autotest/ogr/ogr_pg.py, autotest/ogr/ogr_sqlite.py, autotest/osr/osr_ct.py, autotest/osr/osr_epsg.py, gdal/ogr/ogrct.cpp, gdal/ogr/ogrspatialreference.cpp
Backport of https://github.com/OSGeo/gdal/pull/4041
=> [Backport 3.3] Fixes for AutoIdentifyEPSG() and OGRCoordinateTransformation related to axis order

gdal/frmts/msgn/msg_reader_core.cpp
Mask the records_per_line variable when compiling with -DNDEBUG.
It fixes compilation with `-Werror` on newer Clang versions. More specifically, it fixes the `-Wunused-but-set-variable` warning. This one is a bit more annoying than other warnings as it cannot be easily disabled by setting `CXXFLAGS=-Wno-error=unused-but-set-variable` because the configure script appends a `-Wall` *after* the `CXXFLAGS` so it re-activates the warning, which then breaks the compilation when `-Werror` is also set.
* OS: `unknown`
* Compiler: Clang 13 cross-compiling using Emscripten.
=> Fix -Wunused-but-set-variable warning.

gdal/gcore/rasterio.cpp
Fixed progress calculation in GDALDataset::BlockBasedRasterIO()
https://github.com/OSGeo/gdal/blob/1d77534d0a1ee1efcda7d9f3d0bf1f7b91348e34/gdal/gcore/rasterio.cpp#L4145
Instead std::max, we must use std::min, otherwise progress will always return 1.0.
#4067
=> rasterio.cpp: fixed progress calculation

autotest/gdrivers/webp.py, gdal/frmts/webp/webpdataset.cpp
Supports the 'exact' option, which preserves the RGB values under transparent areas.
=> WEBP: Support 'exact' option

gdal/swig/makefile.vc
Passes -threads to SWIG when building python wrappers for windows. This enables releasing the GIL during long-running operations. The GNUmakefile's are already passing this flag.
=> Build: Build windows python wrappers with -threads argument

autotest/gcore/pixfun.py, gdal/doc/source/drivers/raster/vrt.rst, gdal/frmts/vrt/pixelfunctions.cpp
This PR adds pixel functions to interpolate between a set of raster sources representing evenly-spaced positions along a 3rd dimension such as time or elevation. Interpolation can be either piecewise linear or piecewise exponential. Example applications include linearly interpolating among hourly temperature grids or exponentially interpolating among decadal population grids.
None
* OS:
* Compiler:
=> VRT: Add interpolation pixel functions

autotest/pymod/gdaltest.py
Changes the default User-Agent to avoid being blocked by some CDN providers (bad reputation?)
#4095
=> change the default urllib user-agent to avoid being blocked

gdal/frmts/vrt/vrtdataset.h, gdal/frmts/vrt/vrtsources.cpp
Co-authored-by: Sander Jansen <s.jansen@gmail.com>
=> VRT: use source floating point coordinates when valid (fixes #4098)

gdal/frmts/vrt/vrtfilters.cpp, gdal/frmts/vrt/vrtsourcedrasterband.cpp
A follow up on #4099 to include a few extra cases where we could pass psExtraArgs to GetSrcDstWindow.
=> VRT: more potential flt parameters for GetSrcDstWindow for consistency (fixes #4098)

gdal/doc/source/drivers/raster/georaster.rst
Fix a typo and an error in explanation of EXTENTSRID option.
* OS:
* Compiler:
=> Fix the GeoRaster driver documentation

gdal/ogr/ogrsf_frmts/xls/ogrxlslayer.cpp
Sets the OLCStringsAsUTF8 capability to TRUE for XLS layers.
See https://lists.osgeo.org/pipermail/qgis-developer/2021-July/063855.html
=> XLS: Set OLCStringsAsUTF8 capability to TRUE

autotest/gdrivers/data/kml/small_world_in_document_pct.kml, autotest/gdrivers/kmlsuperoverlay.py, gdal/frmts/kmlsuperoverlay/kmlsuperoverlaydataset.cpp
Previously only GroundElements which were placed inside a Document > Folder element were supported, but this Folder element is not mandatory.
=> [kmlsuperoverlay] Allow reading kml documents with a GroundOverlay element directly inside a Document element

gdal/doc/source/drivers/raster/vrt.rst
Small documentation fix to the Raster VRT "Writing Pixel Functions" block.
=> fix the function name to match the text

gdal/doc/source/programs/gdalcompare.rst
gdalcompare.rst - update the docs to reference `osgeo_utils`
https://github.com/OSGeo/gdal/issues/4128
=> gdal/doc/source/programs/gdalcompare.rst - update the docs to reference `osgeo_utils`

gdal/swig/python/gdal-utils/osgeo_utils/gdal_calc.py
gdal_calc.py - fix `hideNoData` for input: `NoDataValue!='none'`, `hideNoData=True`
This fix is for the case that the user wants to set ndv to the output ds and also wants the calc operation to ignore the input ndv while performing the calculation itself.
=> gdal_calc.py - fix `hideNoData` for input: `NoDataValue!='none'`, `hideNoData=True`

gdal/swig/python/gdal-utils/osgeo_utils/gdal_calc.py
backport https://github.com/OSGeo/gdal/pull/4136
=> [backport #4136] gdal_calc.py - fix hideNoData for input: NoDataValue!='none', hideNoData=True

gdal/configure, gdal/configure.ac, gdal/doc/source/drivers/raster/gtiff.rst, gdal/doc/source/drivers/raster/jpeg.rst, gdal/frmts/gtiff/libtiff/tif_jpeg.c, gdal/frmts/gtiff/libtiff/tif_jpeg_12.c, gdal/nmake.opt
Previously we required that the libjpeg used for 8 bit sample support
had the libjpeg-6b ABI. The changes done in libtiff/tif_jpeg.c
and tif_jpeg_12.c now remove this constraint, and it is thus now
possible to have JPEG 12 bit support in a build that uses libjpeg-turbo
with IJG v8 ABI for 8-bit.
=> Enable JPEG-in-TIFF for 12 bit samples (for internal libtiff), whatever libjpeg is used for 8 bit sample support

gdal/frmts/msg/msgdataset.cpp, gdal/frmts/msg/msgdataset.h
This PR fixes a race condition in the MSG driver.
The MSG driver looks for a matching "prologue"-file when calling `MSGDataset::Open`. The filename depends on the satellite number. There are only 4 satellites and all of them are tried until an existing prologue is found. The satellite number is stored as a static variable `iCurrentSatellite` and each call to `Open` triggers a loop that modifies this variable. If multiple threads try to open a MSG dataset, the state of `iCurrentSatellite` is modified in all threads.
This PR changes `iCurrentSatellite` to be a class variable and adds a static hint `iCurrentSatelliteHint` which provides a start value for the lookup. Additionally, the lookup logic (loop) was simplified.
To use the MSG driver the _PublicDecompWT_  code from EUMETSAT is …
=> MSG: fix race condition in satellite number lookup

autotest/pyscripts/test_gdal_utils.py, gdal/swig/python/gdal-utils/osgeo_utils/auxiliary/util.py
util.py - fix get_raster_min_max() and add a test.
On a side note... the docstring `"""ComputeRasterMinMax(Band self, int approx_ok=0)"""` is somewhat misleading as it suggests that `approx_ok` is the name of the argument, but apparently it does not accept it as a named argument but only as a positional argument. 
https://github.com/OSGeo/gdal/pull/4151 (I should have added the test there... :)
=> util.py - fix get_raster_min_max() and add a test

autotest/cpp/test_cpl.cpp, gdal/port/cpl_vsi_mem.cpp
It delays destroying the `VSIMemFile` object on `bUnlinkAndSeize` by reusing the same mechanism as `VSIMemFile::Unlink`
https://github.com/OSGeo/gdal/issues/4158
Creating an unit test requires that the undocumented Python API `gdal.VSIGetMemFileBuffer_unsafe` is replaced by a public `gdal.VSIGetMemFileBuffer` that will use this
=> Delay destroying VSIMemFile on bUnlinkAndSeize

gdal/doc/source/user/multidim_raster_data_model.rst
Fix typos in multidimensional raster documentation. Thanks!
None.
* OS:
* Compiler:
=> Fix typos in multidimensional raster docs

autotest/cpp/test_cpl.cpp, gdal/port/cpl_vsi_mem.cpp
=> [Backport 3.3] VSIGetMemFileBuffer(): delay destroying VSIMemFile on bUnlinkAndSeize (fixes #4158)

autotest/gdrivers/data/zarr/array_dimensions_upper_level.zarr/.zgroup, autotest/gdrivers/data/zarr/array_dimensions_upper_level.zarr/.zmetadata, autotest/gdrivers/data/zarr/array_dimensions_upper_level.zarr/lat/.zarray, autotest/gdrivers/data/zarr/array_dimensions_upper_level.zarr/lat/.zattrs, autotest/gdrivers/data/zarr/array_dimensions_upper_level.zarr/lon/.zarray, autotest/gdrivers/data/zarr/array_dimensions_upper_level.zarr/lon/.zattrs, autotest/gdrivers/data/zarr/array_dimensions_upper_level.zarr/subgroup/.zgroup, autotest/gdrivers/data/zarr/array_dimensions_upper_level.zarr/subgroup/var/.zarray, autotest/gdrivers/data/zarr/array_dimensions_upper_level.zarr/subgroup/var/.zattrs, autotest/gdrivers/zarr_driver.py, gdal/frmts/zarr/zarr.h, gdal/frmts/zarr/zarr_array.cpp, gdal/frmts/zarr/zarr_group.cpp, gdal/frmts/zarr/zarrdriver.cpp
helps for datasets such as /vsis3/hrrrzarr/sfc/20210809/20210809_00z_anl.zarr/0.1_sigma_level/HAIL_max_fcst/0.1_sigma_level/HAIL_max_fcst
=> Zarr: handle _ARRAY_DIMENSIONS variables being in a upper-directory of the variable of interest

autotest/gcore/pixfun.py, gdal/frmts/vrt/pixelfunctions.cpp
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=36980
=> VRT InvPixelFunc(): avoid (mostly harmless) floating point division by zero

autotest/alg/fillnodata.py, autotest/pyscripts/test_gdal_fillnodata.py, gdal/alg/rasterfill.cpp, gdal/doc/source/programs/gdal_fillnodata.rst, gdal/swig/python/gdal-utils/osgeo_utils/gdal_fillnodata.py
It has likely never worked, and was equivalent to the default mode
(on top of PR #4200)
=> gdal_fillnodata.py: remove broken -nomask option

gdal/ogr/ogrsf_frmts/dwg/ogrdwglayer.cpp
When dwg files contain closed AcDb2dPolyline or AcDb3dPolyline, ogr read it to unclosed line because closed AcDb2dPolyline or AcDb3dPolyline end point not equal to start point, only use isClosed function show it was closed.
=> [dwg] Make Closed AcDb2dPolyline and AcDb3dPolyline to Closed OGRLineString

autotest/ogr/ogr_pgeo.py, gdal/ogr/ogrsf_frmts/pgeo/ogrpgeotablelayer.cpp
This is a non-intrusive subset of https://github.com/OSGeo/gdal/pull/4255
=> [pgeo] Correctly reflect that non-spatial tables have no geometry, not unknown geometry (3.3)

gdal/ogr/ogrsf_frmts/geomedia/ogrgeomediadatasource.cpp, gdal/ogr/ogrsf_frmts/walk/ogrwalkdatasource.cpp
This avoids noisy warnings raised by mdbtools odbc driver when trying to open an mdb files which isn't a geomedia/walk database,
as mdbtools dumps a lot of debug warnings when a query is attempted against a table which doesn't exist
=> [geomedia, walk] Check sql tables for required tables before trying to query them when trying to open a .mdb dataset

gdal/doc/source/programs/gdal_calc.rst
Fixes rendering of "versionadded" on doc page of gdal_calc.
=> doc: Fix faulty sphinx rst versionadded directive

autotest/ogr/ogr_mdb.py, autotest/ogr/ogr_pgeo.py
It's too messy to try to handle both drivers in a single test suite, as the behaviour for the PGeo driver is differing more and more
from the MDB driver.
=> Split pgeo and mdb driver test suites

autotest/ogr/ogr_pgeo.py, gdal/doc/source/drivers/vector/pgeo.rst, gdal/ogr/ogrsf_frmts/openfilegdb/ogr_openfilegdb.h, gdal/ogr/ogrsf_frmts/openfilegdb/ogropenfilegdbdatasource.cpp, gdal/ogr/ogrsf_frmts/pgeo/ogr_pgeo.h, gdal/ogr/ogrsf_frmts/pgeo/ogrpgeodatasource.cpp, gdal/ogr/ogrsf_frmts/pgeo/ogrpgeotablelayer.cpp
Add support for retrieving layer definition and metadata special "GetLayerDefinition table_name" and "GetLayerMetadata
table_name" SQL queries
Exposes the same functionality as the fgdb/openfilegdb drivers offer for retrieving these properties
* OS:
* Compiler:
=> [pgeo] Add support for retrieving layer definition and metadata

autotest/pyscripts/test_gdal_utils.py, gdal/swig/python/gdal-utils/osgeo_utils/auxiliary/util.py
Fix previous PR, which I mistakenly set the approx_ok default to be True (https://github.com/OSGeo/gdal/pull/4151), which breaks backwards compatibility and also inconsistent with the default in `ComputeRasterMinMax`. 
I couldn't find a small test file that yields different min, max values for approx_ok True/False.
* gdal-utils/osgeo_utils/auxiliary/util.py - change default parameter get_raster_min_max(...,approx_ok = True)
* autotest/pyscripts/test_gdal_utils.py - parameterize the test_min_max test so that more cases would be added easily (i.e. approx_ok=False)
https://github.com/OSGeo/gdal/pull/4167
https://github.com/OSGeo/gdal/pull/4151
=> util.py - fix get_raster_min_max() default approx_ok value

autotest/pyscripts/test_gdal_utils.py, gdal/swig/python/gdal-utils/osgeo_utils/auxiliary/color_palette.py, gdal/swig/python/gdal-utils/osgeo_utils/auxiliary/color_table.py
* `get_color_table_from_raster` was failing if the ds did not have a color table. now fixed.
* autotest/pyscripts/test_gdal_utils.py - add `test_read_write_color_table_from_raster()`
=> color_table.py - fix get_color_table_from_raster for ds w/o color table + tests

gdal/frmts/vrt/vrtdataset.cpp, gdal/frmts/vrt/vrtdataset.h, gdal/frmts/vrt/vrtrasterband.cpp, gdal/frmts/vrt/vrtsourcedrasterband.cpp, gdal/gcore/gdal_priv.h, gdal/gcore/gdaldataset.cpp
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=37717
=> Add a per-thread mechanism to count call depth and use it in VRT driver to avoid infinite recursive calls on corrupted datasets

autotest/ogr/ogr_odbc.py
A fix for the mdbtools driver issue has been submitted upstream
=> [odbc] Allow test to be run locally

gdal/swig/include/cpl.i, gdal/swig/python/extensions/gdal_wrap.cpp, gdal/swig/python/osgeo/gdal.py
Adds implementations of `CPLGetThreadLocalConfigOption()` & `CPLSetThreadLocalConfigOption()` into the Python API as `gdal.GetThreadLocalConfigOption()` and `gdal.SetThreadLocalConfigOption()`.
Bindings were updated using SWIG 3.0.12 which is the same version listed in the existing wrapper.
=> Python: Add thread-local config methods

gdal/frmts/dimap/dimapdataset.cpp
The dynamically created VRT that wraps the underlying datasets does not expose any overviews.
This PR adds this capability, although I'm not sure wether this is a hack or the correct way
to do so.
Before (cancelled):
```
time /opt/bin/gdalwarp  -ts 1248 4835 DIM_PHR1B_PMS_201911041624143_SEN_5886713101.XML og.tif
Creating output file that is 1248P x 4835L.
Processing DIM_PHR1B_PMS_201911041624143_SEN_5886713101.XML [1/1] : 0^C
real	0m20,575s
user	2m36,811s
sys	0m0,748s
```
After:
```
time /opt/bin/gdalwarp  -ts 1248 4835 DIM_PHR1B_PMS_201911041624143_SEN_5886713101.XML ng.tif --config VRT_VIRTUAL_OVERVIEWS YES
Creating output file that is 1248P x 4835L.
Processing DIM_PHR1B_PMS_201911041624143_SEN_5886713101.XML [1/1] : 0...10...20...30...40...50...60...70...80...90...100 - done.
real …
```
=> DIMAP: expose virtual overviews

gdal/doc/source/programs/gdaldem.rst
Aspect was in the slope text. Also added a dot at the end of hillshade, slope and aspect texts. Now all sentences have a dot at the end (in the mode part of the file).
=> gdaldem.rst: fixed formatting in documentation (aspect mode)

autotest/ogr/ogr_index_test.py
Refactor ogr_index_test.py to remove dependency on test order
In particular, incorrect test ordering causes a segfault in some circumstances.
(If interested in diagnosing that further, running `pytest ogr/ogr_index_test.py --random-order-seed=8` on commit 364c56b7e8f59b0f1a335dec63c7dcb3de5d4508 produces it reproducibly for me)
Also split some assertions into separate tests.
#4407
=> Refactor ogr_index_test.py to remove dependency on test order

gdal/swig/python/gdal-utils/osgeo_utils/gdal2tiles.py
=> gdal2tiles: fix tile grid origin of openlayers with xyz and geodetic profile as arguments (fixes #4425)

autotest/gdrivers/wms.py, gdal/frmts/wms/wmsdriver.cpp
It sets the default `bbox` in the WMS driver according to the CRS (instead of a hard-coded WGS84 world extent)
#4093
=> WMS: use correct default bbox according to the SRS

.github/workflows/code_checks.yml
Fixes #4448. cppcheck_1604 relies on the deprecated ubuntu-16.04 image, which will no longer be available after 20 Sept. The existing cppcheck_2004 build carries out the same checks using a more modern image.
=> Remove cppcheck_1604

autotest/gdrivers/wmts.py, gdal/frmts/wmts/wmtsdataset.cpp
Fixes https://lists.osgeo.org/pipermail/gdal-dev/2021-September/054655.html
=> WMTS: do not take into account a TileMatrixSetLink that points to a non-existing TileMatrixSet.

autotest/gcore/vsis3.py, autotest/pymod/gdaltest.py, autotest/pymod/webserver.py
Refactor gcore/vsis3.py to remove dependency on test order.
Refactor to apply environment variable overrides only during the test using now-standard test fixtures, rather than altering the global GDAL environment.
I apologise in advance that there are a _ridiculous_ number of changes to appease flake8 - in retrospect, I wish I had done these first. If it's simply too much (and I suspect it is), options are:
* Merge without the linting changes, which are in the final commit, and submit a separate PR for them (will the build pipeline permit this?)
* Tell me to go away and lint the whole file first in one PR, and then do the dependency changes
#4407
=> Remove vsis3 test order dependency

gdal/Doxyfile, gdal/doxygen_index.md
Add a new doxygen_index.md file, and use the Doxygen setting
USE_MDFILE_AS_MAINPAGE to include it as the contents of the Main Page.
Fixes #3689.
Adds some descriptive content to the "Main Page" of the raw Doxygen output at https://gdal.org/doxygen/index.html so it's not just mysteriously blank.
I've copied the intro paragraph about GDAL from the main website verbatim, and added some words of my own about the Doxygen site and how to use it.
Issue raised in #3689 
* OS: MacOS 11.5.2
* Compiler: Doxygen 1.9.2
=> Docs: Add a descriptive Main Page to the Doxygen site.

autotest/gdrivers/gpkg.py, autotest/ogr/ogr_gpkg.py, gdal/ogr/ogrsf_frmts/gpkg/ogrgeopackagedatasource.cpp
=> capitalize cartesian as Cartesian

autotest/gdrivers/gdalhttp.py
Refactor gdalhttp.py to remove dependency on test order (#4407 )
Also refactor code to reduce duplication, and ensure all tests have a
timeout. I was finding that test_http_4, known to be flakey, was hanging
for me due to a lack of any timeout.
=> Test - Refactor gdalhttp.py to remove dependency on test order

gdal/swig/python/GNUmakefile, gdal/swig/python/trimmedsysconfig.py
The fix isn't pretty. I basically copied and trimmed /usr/lib/python3.8/distutils/sysconfig.py
as I couldn't find a direct replacement for that function.
Fixes #4334
CC @snowman2 in case you have a suggestion for something more elegant
=> swig/python/GNUmakefile: no longer used distutils to determine site_package_dir

gdal/ogr/ogrsf_frmts/sqlite/ogrsqlitelayer.cpp
Add missing SQL datatypes (from https://www.sqlite.org/datatype3.html) to sqlite driver field type detection algorithm (BuildFeatureDefn). Now all types from sqlite docs can be recognised by gdal
Main problem was with floating-point fields. Only FLOAT and DECIMAL field types was supported.
If first row contains null in floating-point field and field type (in sqlite metadata) REAL, DOUBLE, DOUBLE PRECISION, NUMERIC data in field is processed as string
As a result floating-point fields occasionally may have string output type in ogr2ogr and data in them is rounded to 15 characters (for string fields gdal uses sqlite3_column_text which calls sqlite printf('%!.15g') for REAL storage class)
To reproduce this behaviour create sqlite database with commands bellow and convert it to another format …
=> sqlite/ogrsqlitelayer.cpp: Add missing SQL data types to sqlite driver

gdal/swig/python/trimmedsysconfig.py
For a unknown and unreproducible reason, we've still observed a failure
on Fedora in https://github.com/OSGeo/gdal/pull/4520/checks?check_run_id=3655557289
where Debian layout was wrongly detected.
=> Python installation: try to make Debian layout detection more robust (fixes #4516)

gdal/frmts/grib/gribdataset.cpp, gdal/gcore/gdaldataset.cpp
Substitutes the links https://gdal.org/doxygen/gdal_datamodel.html#GDALDataset and http://gdal.org/gdal_datamodel.html to the no longer existing GDAL Data Model page with the the link to the Raster Data Model page at https://gdal.org/user/raster_data_model.html
Fixes https://github.com/OSGeo/gdal/issues/4527
=> Docs: fix link to GDAL Data Model (fixes #4527)

.github/workflows/asan/start.sh
Otherwise the output is not very useful as it just shows us libgdal and offset in the stack dump whereas with the symbolizer we are able to see the functions.
* OS:
* Compiler:
=> Add ASAN symbolizer so stack traces are useful

gdal/m4/acinclude.m4, gdal/port/cpl_config.h.in, gdal/port/cpl_port.h, gdal/port/cpl_vsil_unix_stdio_64.cpp
and remove (unused by GDAL) VSI_LARGE_API_SUPPORTED macro from cpl_port.h
=> Cleanup / stronger enforcement of 64-bit file I/O

gdal/doc/source/drivers/raster/mem.rst, gdal/frmts/mem/memdataset.cpp
MEM: Open functions adds support for the 'GEOTRANSFORM' options
When using `"MEM:::DATAPOINTER=342343408,PIXELS=100,LINES=100,BANDS=3,DATATYPE=Byte,PIXELOFFSET=3,LINEOFFSET=300,BANDOFFSET=1"` to create a memory data When creating a memory data set, it supports passing in spatial coordinate information.
- [] Add documentation
* OS: linux / windows 7 later
* Compiler: gcc 8.3 / msvc 14
=> MEMDataset::Open functions adds support for the 'GEOTRANSFORM' options

autotest/ogr/data/geojson/sparse_fields.geojson, autotest/ogr/ogr_geojson.py, gdal/ogr/ogrsf_frmts/geojson/directedacyclicgraph.hpp, gdal/ogr/ogrsf_frmts/geojson/ogrgeojsonreader.cpp, gdal/ogr/ogrsf_frmts/geojson/ogrgeojsonreader.h, gdal/ogr/ogrsf_frmts/geojson/ogrgeojsonseqdriver.cpp, gdal/ogr/ogrsf_frmts/geojson/ogrtopojsonreader.cpp
Detailed rationale of the fix: http://erouault.blogspot.com/2021/09/order-of-geojson-properties-and-graph.html
=> GeoJSON: expose field names in a more consistent orders when some feature lacks some fields (refs qgis/QGIS#45139)

autotest/gdrivers/wcs.py, gdal/frmts/wcs/wcsdataset201.cpp, gdal/frmts/wcs/wcsutils.cpp, gdal/frmts/wcs/wcsutils.h
Fixes(?) the CompareNumbers fct in wcsutils.cpp
#4483
* OS:
* Compiler:
=> Replace CompareNumbers with in-place numeric comparisons.

gdal/configure.ac
Use pkg-config for libdap when dap-config is not available.
libdap (3.20.8-1) in Debian no longer provides dap-config.
This causes the gdal build to fail as reported in [Debian Bug #995325](https://bugs.debian.org/995325):
> ```
>  configure:40397: checking for qh_new_qhull in -lqhull
>  configure:40420: gcc -o conftest -DHAVE_AVX_AT_COMPILE_TIME -DHAVE_SSSE3_AT_COMPILE_TIME -DHAVE_SSE_AT_COMPILE_TIME -g -O2 -ffile-prefix-map=/build/gdal-3.3.2+dfsg=. -fstack-protector-strong -Wformat -Werror=format-security -fvisibility=hidden -Wdate-time -D_FORTIFY_SOURCE=2 -Wl,-z,relro -Wl,-z,now conftest.c -lqhull  -lgeos_c -lodbc -lodbcinst -lkmlbase -lkmldom -lkmlengine -lkmlxsd -lkmlregionator -lexpat -lxerces-c -lpthread -lopenjp2 -L/usr/lib/x86_64-linux-gnu/hdf5/serial -lnetcdf …
```
=> Use pkg-config for libdap when dap-config is not available.

gdal/doc/source/drivers/raster/netcdf.rst, gdal/frmts/netcdf/netcdf_cf_constants.h, gdal/frmts/netcdf/netcdfdataset.h
Tolerate "degrees_E"/"degrees_N" as valid axis names
NOAA seems to use these in their NetCDF files
Refs: #4581
Finding a test file is difficult since the original is 7GB and GDAL corrects the dimension names when writing a NetCDF file
=> Tolerate "degrees_E"/"degrees_N" as valid axis names

gdal/swig/python/gdal-utils/osgeo_utils/pct2rgb.py
Fixes an oversight in the pct2rgb.py arguments parsing logic, introduced with https://github.com/OSGeo/gdal/commit/33374e4545101c36baa50d1434d095c964d53817 (https://github.com/OSGeo/gdal/pull/3131), which prevents pct2rgb.py provided by GDAL 3.3.x to properly work.
It seems the logic in master branch is totally different, and I'm not sure if the issue is also present in master.
Issue https://github.com/qgis/QGIS/issues/45344 reported for QGIS 3.20.3 on Windows (GDAL 3.3.1).
=> pct2rgb: fix parsing arguments (release/3.3)

gdal/frmts/gtiff/geotiff.cpp
Many years ago, we had regular trouble with GDAL using internal libtiff without
symbol renaming and linking to an external libtiff 3.x. Hence this
mechanism that attempted at detecting this scenario and warning about
it. This is now largely obsolete.
=> GTiff: remove obsolete libtiff 3.x detection

autotest/cpp/testclosedondestroydm.cpp
- update testclosedondestroydm to catch up data place changes
- there moved test data to dedicated test subdir
Fix test case to be able to find a test data.
reduce these errors on C++ test.
```
./testclosedondestroydm
ERROR 4: ../gdrivers/data/rgb_warp.vrt: No such file or directory
ERROR 4: ../gdrivers/data/A.TOC: No such file or directory
ERROR 4: Failed to open file ../gdrivers/data/A.TOC.
ERROR 4: ../gdrivers/data/testtil.til: No such file or directory
ERROR 4: ../gdrivers/data/product.xml: No such file or directory
ERROR 4: ../gdrivers/data/METADATA.DIM: No such file or directory
ERROR 4: ../gdrivers/tmp/cache/file9_j2c.ntf: No such file or directory
ERROR 4: ../gdrivers/data/bug407.gif: No such file or directory
ERROR 4: …
```
=> test: Catch moved test data in individual directory

gdal/frmts/mrf/GNUmakefile
Without this fix, when LERCV1 is not defined, make clean fails as it will try to run "make clean" in $HOME.
=> fix mrf 'make clean' when lercv1 not defined

ogr/ogrsf_frmts/mitab/mitab_middatafile.cpp, ogr/ogrsf_frmts/mitab/mitab_priv.h
The limit can be adjusted at runtime with the MITAB_MAX_LINE_LENGTH
configuration option.
=> MITAB: allow reading MID/MIF files with lines up to 1 million bytes (fixes #3943)

doc/source/conf.py
I haven't tested the changes, but I think this should fix it.
Currently, on the documentation website <https://gdal.org/>, clicking on the link "Edit on Github" on the top right leads to <https://github.com/OSGeo/gdal/edit//master/gdal/doc/source/index.rst> which is a 404 page. The correct link should be <https://github.com/OSGeo/gdal/edit/master/doc/source/index.rst>.
This seems to be caused by commit 9e9f8b2.
=> docs: fix broken "Edit on Github" link

doc/source/_extensions/redirects.py, ogr/ogrsf_frmts/gpkg/ogrgeopackagedriver.cpp
Changes GDAL_DMD_HELPTOPIC value from non existent drivers/vector/geopackage.html to drivers/vector/gpkg.html
The GDAL_DMD_HELPTOPIC was changed from drv_geopackage.html to drivers/vector/geopackage.html with https://github.com/OSGeo/gdal/commit/542a11742b2ae809b6e2eed4ad35275976738bbb (https://github.com/OSGeo/gdal/pull/2992) since 3.2.0RC1.
A redirection from https://gdal.org/drivers/vector/geopackage.html to https://gdal.org/drivers/vector/gpkg.html should be set in order to workaround the current issue in QGIS.
https://github.com/qgis/QGIS/issues/45875
=> GPKG: fix GDAL_DMD_HELPTOPIC

doc/source/_extensions/redirects.py
(Hopefully) Fixes doc redirection from https://gdal.org/drivers/vector/geopackage.html to https://gdal.org/drivers/vector/gpkg.html incorrectly introduced by me with https://github.com/OSGeo/gdal/commit/6aa16e0eb980cc57d9e4b79579706b9a60398aee (https://github.com/OSGeo/gdal/pull/4768)
https://github.com/OSGeo/gdal/pull/4768
=> GPKG: fix doc redirection

GDALmake.opt.in, GNUmakefile, apps/GNUmakefile, configure.ac, gcore/GNUmakefile, gcore/generate_gdal_version_h.sh, generated_headers/.gitignore, generated_headers/GNUmakefile, port/GNUmakefile, scripts/cppcheck.sh, swig/python/fallback_build_mingw32_under_unix.sh, swig/python/fallback_build_mingw32_under_unix_py37.sh
This moves port/cpl_config.h and gcore/gdal_version.h to
generated_headers/. This should not be visible from outside users, since
the header will still be installed in ${prefix}/include.
The motivation behind this is to be able, in a same git checkout, to
continue to do autoconf in-source-tree builds as well as cmake
out-of-source-tree builds. The cmake builds would be confused by the
existing autoconf generateds files in port/ and gcore/ if there were
present (a check in the cmake build has been already put in place to avoid
doing builds that would use such stale files)
Something similar could probably be done for makefile.vc builds, but
this is more pressing for my own needs.
=> Unix builds: move generated headers to a generated_headers subdirectory

swig/include/ogr.i, swig/python/extensions/ogr_wrap.cpp
Running the tests with a custom allocator caused crashes as GetFieldAsBinary was using malloc for allocation but in the swig generated python/extensions/ogr_wrap.cpp file at line 15401 you can see that the memory is freed using VSIFree which does not match the allocation.
This change fixes the ogr.i file however I am not sure of the process to regenerate the *_wrap.cpp files using swig as using the makefile.vc in gdal/swig creates quite a different file from what is checked in. However I can add these to the pull request if required. 
* OS:
* Compiler:
=> Change GetFieldAsBinary to use VSIMalloc.

doc/source/about_no_title.rst
The link on the [main documentation page](https://gdal.org/) to the news file is broken for release 3.4.0, because the file has been renamed from NEWS to NEWS.md in https://github.com/OSGeo/gdal/commit/631010291ba98717fa3a6e880b5a964494c336f4
=> Fix broken link for the news page

ogr/ogrsf_frmts/pg/ogrpgdatasource.cpp
Previously the logic to skip leading whitespace only skipped over the
space character (0x20), but for SQL all leading whitespace characters
can be skipped.  Use the built-in std::isspace function to test for
this, rather than testing for the space character specifically.
The previous logic led to differences in the behaviour of queries,
because the logic to detect a 'SELECT' statement failed to detect valid
SELECT queries that began with whitespace other than 0x20.
Refs #4301
Skip all leading whitespace, instead of just spaces, in SQL statements for the PostgreSQL driver.
Related to #4301.
* OS: MacOS 11.6
* Compiler: Xcode
=> PG: skip all leading whitespace in SQL statements.

cmake/helpers/CheckDependentLibraries.cmake, cmake/modules/packages/FindRDB.cmake, doc/source/drivers/raster/rdb.rst, frmts/CMakeLists.txt, frmts/rdb/CMakeLists.txt
Updates CMake files in order to enable building the rdb driver.
I did not add anything to `doc/source/build_hints.rst` because the only build requirement is, that the rdb can be found by CMake.
Instead I have updated the information in `doc/source/drivers/raster/rdb.rst`.
I currently only compiled the update on Ubuntu focal. I could add downloading and building with the rdblib in the CI steps, because the rdblib can be downloaded from a server.
=> rdb: enable building rdb driver via CMake

frmts/grib/CMakeLists.txt, frmts/grib/degrib/degrib/myerror.cpp
Should fix (or at least help..) for the scenario of
https://lists.osgeo.org/pipermail/gdal-dev/2021-November/055009.html
=> GRIB: fix thread-safetey of errSprintf()

autotest/gdrivers/data/ers/srtm.ers, frmts/ers/ersdataset.cpp, frmts/ers/ershdrnode.cpp, frmts/ers/ershdrnode.h
This PR adds support for comments in ERS file headers.  A comment starts with a `#` character and continues to the end of the line.  ER Mapper documentation describes comments in this fashion and we've recently encountered files in the wild that contain comments.  Since comments may appear at the start of the file, ERS file identification logic is modified to accommodate presence of such comments.
The `srtm.ers` test case is modified to exercise comment logic and all ERS test cases are still passing.
=> Add support for comments in ERS files

cmake/helpers/CheckDependentLibraries.cmake, port/CMakeLists.txt
Check for iconv_open availability in libiconv on OSX due to how things could be built on that platform in regard to `LIBICONV_PLUG`
=> CMake: iconv on OSX

doc/source/drivers/vector/lvbag.rst
Kadaster is not good at preserving links when changing their website, links to their site need to be updated periodically.
Using archive.org might be a good idea for stable links.
=> Update BAG 2.0 Extract URLs

cmake/helpers/CheckDependentLibraries.cmake, cmake/modules/packages/FindRDB.cmake
Fixes warnings like
```
CMake Warning at cmake/helpers/CheckDependentLibraries.cmake:35 (find_package):
By not providing "Findrdb.cmake" in CMAKE_MODULE_PATH this project has
asked CMake to find a package configuration file provided by "rdb", but
CMake did not find one.
Could not find a package configuration file provided by "rdb" with any of
the following names:
rdbConfig.cmake
rdb-config.cmake
Add the installation prefix of "rdb" to CMAKE_PREFIX_PATH or set "rdb_DIR"
to a directory containing one of the above files.  If "rdb" provides a
separate development package or SDK, be sure it has been installed.
```
@tnixeu Could you check that this pull request still work with the rdb driver ? On Linux, I got the above warning due to different of case FindRDB.cmake vs 'rdb' in find_package() …
=> CMake: avoid warning messages for rdb and TileDB

autotest/gcore/tiff_write.py, doc/source/drivers/raster/gtiff.rst, doc/source/programs/gdaladdo.rst, frmts/gtiff/geotiff.cpp, frmts/gtiff/gt_overview.cpp, frmts/gtiff/gt_overview.h, frmts/gtiff/gtiff.h
Fixes #4848
- COMPRESS_OVERVIEW configuration option now honours LERC_DEFLATE
and LERC_ZSTD for external overviews
- MAX_Z_ERROR_OVERVIEW configuration option is added for LERC
compressed internal and external overviews.
- ZLEVEL_OVERVIEW configuration option is added for DEFLATE/LERC_DEFLATE
compressed internal and external overviews.
- ZSTD_LEVEL_OVERVIEW configuration option is added for ZSTD/LERC_ZSTD
compressed internal and external overviews.
=> GTiff: LERC overview related improvements

doc/source/drivers/raster/bag.rst, doc/source/drivers/raster/pdf.rst, doc/source/drivers/raster/vrt.rst, doc/source/drivers/raster/vrt_multidimensional.rst, doc/source/license.rst
Hitting a 404 on https://raw.githubusercontent.com/OSGeo/gdal/master/gdal/data/gdalvrt.xsd
I thought to fix it, and tried to find all failing raw.githubusercontent url's in the doc sources
=> Fixing some raw.githubusercontent url's in documentation

autotest/ogr/ogr_shape.py, ogr/ogrsf_frmts/shape/ogrshapelayer.cpp
by using the official CRS definition (without TOWGS84). This makes sense
since it's the only known TOWGS84[] style transformation to WGS 84
Addresses test case of https://lists.osgeo.org/pipermail/qgis-developer/2021-November/064340.html
=> Shape: better deal with ETRS89 based CRS with TOWGS84[0,0,0,0,0,0,0]

frmts/kea/keadataset.cpp
Fixes a situation when a file is identified as `kea` but can't be opened for any reason. This could be because it is corrupt or locked by `libhdf5` because the file is open elsewhere for update.
Previously, the file would fail to open with no message. Now provides the error from `libkea` (which in turns comes from `libhdf5`) which isn't always that useful but at least the user gets some feedback that the open was attempted but failed. Otherwise the user may think that the `kea` driver hasn't been built etc.
https://github.com/ubarsc/kealib/pull/14
=> KEA: print error message when opening of kea file fails

swig/python/gdal-utils/osgeo_utils/gdal2tiles.py
If no kml related options are specific,  the generation of kml file will be enabled if  the SRS is EPSG:4326 and disabled for another SRS. This change also make sure that the original meaning of --force-kml and --no-kml will not be changed regardless of what SRS. More details can be found in this PR: https://github.com/OSGeo/gdal/pull/4937
=> making --no-kml option takes effect (fixes #4936)

autotest/gcore/tiff_ovr.py, doc/source/drivers/raster/gtiff.rst, doc/source/programs/gdaladdo.rst, frmts/gtiff/geotiff.cpp, frmts/gtiff/gt_overview.cpp
* Propagate SPARSE_OK creation option to (internal) overviews
when calling BuildOverviews() on the created dataset
* Propagate SPARSE_OK open option to internal overviews (dataset
opened in update mode) or external overviews (dataset opened in
read-only mode)
* Take into account the newly added SPARSE_OK_OVERVIEW configuration
option to internal overviews (dataset opened in update mode) or
external overviews (dataset opened in read-only mode)
=> GTiff: propage SPARSE_OK to overviews (refs #4932)

ogr/ogrsf_frmts/selafin/io_selafin.cpp, ogr/ogrsf_frmts/selafin/ogrselafindatasource.cpp
SELAFIN files, without dataset but only with the mesh frame, can exist, especially coming from editors as  Bluekenue, Basemesh SalomeHydro, or more recently QGIS.
When opening such file by drag/drop such files in QGIS, opening the file is tested with OGR driver, which returns a very big (and bad) layer count. That make QGIS crashes or being freeze.
This little PR fixes this issue. In such case, the file can't be opened by OGR, but it doesn't consider anymore bad layer count.
=> Selafin: fix time step count when none dataset in the file

configure.ac
This will align with the default of the CMake builds.
And actually fix the taking account of the --with-rename... options that
was was broken in the non --with-hide-internal-symbols case.
=> configure: change default of RENAME_INTERNAL_LIBTIFF/LIBGEOTIFF/SHAPELIB_SYMBOLS to yes

autotest/gdrivers/grib.py, frmts/grib/gribcreatecopy.cpp, frmts/grib/gribdataset.cpp
and fix reading it for TMerc, LCC, ACEA and LAEA
=> GRIB: fix writing negative longitude of natural origin for Transverse Mercator

autotest/cpp/test_gdal.cpp, autotest/gcore/rasterio.py, autotest/gdrivers/envi.py, autotest/gdrivers/pds4.py, doc/source/drivers/raster/envi.rst, doc/source/drivers/raster/georaster.rst, doc/source/drivers/raster/gtiff.rst, doc/source/drivers/raster/paux.rst, doc/source/drivers/raster/pds4.rst, doc/source/drivers/raster/rraster.rst, frmts/pds/pds4dataset.cpp, gcore/gdaldriver.cpp
Aims #4911
Better doc to explain how interleaving is handled by CreateCopy()
Added a system that tries to automatically match the src data interleaving by default, if not specified otherwise.
That might break backward compatibility for people that were relying on the default driver data interleaving when using CreateCopy() with no creation options.
~~The system is "fragile" regarding the different syntaxes for INTERLEAVE (BAND/PIXEL/LINE or BIP/BI/BSQ) and is currently hard coding BIP/BIL/BSQ for ENVI drivers only.~~
UPDATE : an XML parsing is performed to explore the declared INTERLEAVE syntaxes in the current driver creation options
=> Smarter GDALDriver::CreateCopy()

autotest/ogr/ogr_s57.py, doc/source/drivers/vector/s57.rst, ogr/ogrsf_frmts/pg/ogr_pg.h, ogr/ogrsf_frmts/pg/ogrpgdatasource.cpp, ogr/ogrsf_frmts/pg/ogrpgtablelayer.cpp, ogr/ogrsf_frmts/s57/ogrs57driver.cpp, ogr/ogrsf_frmts/s57/ogrs57layer.cpp, ogr/ogrsf_frmts/s57/s57reader.cpp
And also PG: error out if non UTF-8 content is transmitted in COPY mode, when client_encoding=UTF8
=> S57: enable recoding to UTF-8 by default (RECODE_BY_DSSI=YES open option) (fixes #4751)

autotest/cpp/test_ogr.cpp, ogr/ogrsf_frmts/dxf/ogrdxfwriterds.cpp
When MarkSuppressOnClose is called on a DXF, the final copy from the `tmp` to the DXF file is not done. 
This improves performance when the creation of a big file is cancelled.
Added test checks that `MarkSuppressOnClose` works... that is not modified by this PR. I checked that the added code in `ogrdxfwriterds.cpp` to avoid the unneeded copy is used debugging the execution.
The test just adds a bunch of points in a dxf to be able to easily debug it and see how it behaves.
=> Do not copy final DXF when MarkSuppressOnClose was called

autotest/gcore/cog.py, frmts/gtiff/cogdriver.cpp
Fixes https://lists.osgeo.org/pipermail/gdal-dev/2021-December/055108.html
=> COG: fix potential generation failure when main imagery has overview and mask none

autotest/ogr/ogr_gmt.py, doc/source/drivers/vector/gmt.rst, ogr/ogrsf_frmts/gmt/ogr_gmt.h, ogr/ogrsf_frmts/gmt/ogrgmtdatasource.cpp, ogr/ogrsf_frmts/gmt/ogrgmtdriver.cpp, ogr/ogrsf_frmts/gmt/ogrgmtlayer.cpp
CC @joa-quim Can you confirm that a OGR GMT file that lacks the "# @R" region header will work properly ? (see https://github.com/OSGeo/gdal/issues/4993#issuecomment-993450875)
=> OGR GMT: allow writing to /vsistdout/ (fixes #4993)

.github/workflows/cmake_builds.yml, autotest/cpp/CMakeLists.txt, cmake/helpers/GdalSetTestEnv.cmake, gdal.cmake, swig/CMakeLists.txt, swig/csharp/CMakeLists.txt, swig/csharp/build_dll.cmake, swig/java/CMakeLists.txt
Note that it is currently disabled on the CMake Windows CI because we
get the following error:
```
Microsoft (R) Visual C# 2005 Compiler version 8.00.50727.9031
for Microsoft (R) Windows (R) 2005 Framework version 2.0.50727
Copyright (C) Microsoft Corporation 2001-2005. All rights reserved.
d:\a\gdal\gdal\swig\csharp\AssemblyInfo.cs(98,12): error CS0246: The type or namespace name 'SecurityRules' could not be found (are you missing a using directive or an assembly reference?) [D:\a\gdal\gdal\build\swig\csharp\csharp_samples.vcxproj]
```
Things works fine locally for me with Microsoft (R) Visual C# Compiler version 3.9.0-6.21124.20 (db94f4cc)
CC @szekerest  / @bjornharrtell  w.r.t above issue. I haven't also ported swig/csharp/makefile.vc logic related to using dotnet rather than mono. I …
=> CMake: add/fix CSharp support

frmts/ecw/ecwdataset.cpp, frmts/hdf5/hdf5vfl.h, ogr/ograpispy.cpp, ogr/ogrsf_frmts/dwg/ogrteigha.cpp, ogr/ogrsf_frmts/mongodb/ogrmongodbdriver.cpp, ogr/ogrsf_frmts/mongodbv3/ogrmongodbv3driver.cpp, port/cpl_vsil_curl.cpp
- when driver unloading doesn't occur properly
- Remove most uses of GDALIsInGlobalDestructor() : Previously GDALDestroy() was a __attribute__ ((destructor)) function,
which could cause issues with automatic C++ objects that could get destroyed before it. Now it should be safe to access those C++ objects since they must still be alive at the time GDALDestroy() is called.
=> DWG/DGNv8: avoid potential crash with ODA 2022 on Linux

autotest/gdrivers/xyz.py, frmts/xyz/xyzdataset.cpp
The XYZ Gridded ASCII driver failed to open a valid ASCII-file
with a floating point step size that can't be represented
accurately with a double. (e.g. '0.1')
This issue only occurred when the ASCII file is organized by
the X column (added in GDAL 3.2.1).
The fix uses the RELATIVE_ERROR when checking if consecutive
step sizes are constant instead of using operator==.
=> XYZ-driver: Fix incorrect failure to open ASCII-file due to floating point comparison

alg/viewshed.cpp
The diff here might not show much, but I removed Unicode character 'POP DIRECTIONAL FORMATTING' (U+202C).
It looks like this was added by mistake in 2e9d67f055ad6e2b8343df02030918918fbe9b27.
This pop character only makes sense if there is a bidirectional marker to pop, so that makes the string unbalanced. Interestingly I came across this in the Julia GDAL wrapper, which also copies original docstrings. The Julia parser errored with "unbalanced bidirectional formatting in string literal".
I see that GitHub now also shows a yellow banner above https://github.com/OSGeo/gdal/blob/master/alg/viewshed.cpp that warns about bidirectional Unicode characters.
=> remove hidden bidirectional unicode character

swig/python/gdal-utils/osgeo_utils/gdal2tiles.py
This PR implements parallel generation of overview tiles. And the breaking change I've ever seen is the output information of generating overview tiles in verbose mode(see images below), because overview tiles are generated in separate process, so I think it is a little difficult and unnecessary to maintain the generating order of the overview tile.
old style:
new style:
#4895
=> gdal2tiles: implement parallel generation of overview tiles

frmts/mrf/marfa_dataset.cpp
It got broken a while ago, it is not used often
Fix a logic error in MRF, when padding between tiles is requested
* OS:
* Compiler:
=> MRF: Padding space logic fix

apps/gdalsrsinfo.cpp, ogr/ogrspatialreference.cpp
new behaviour:
```
$ gdalsrsinfo EPSG:3411
CRS EPSG:3411 is deprecated, and the following output will use its non-deprecated replacement EPSG:3413.
To use the original CRS, set the OSR_USE_NON_DEPRECATED configuration option to NO.
PROJ.4 : +proj=stere +lat_0=90 +lat_ts=70 +lon_0=-45 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs
OGC WKT2:2018 :
PROJCRS["WGS 84 / NSIDC Sea Ice Polar Stereographic North",
BASEGEOGCRS["WGS 84",
ENSEMBLE["World Geodetic System 1984 ensemble",
MEMBER["World Geodetic System 1984 (Transit)"],
MEMBER["World Geodetic System 1984 (G730)"],
MEMBER["World Geodetic System 1984 (G873)"],
MEMBER["World Geodetic System 1984 (G1150)"],
MEMBER["World Geodetic System 1984 (G1674)"],
MEMBER["World Geodetic System 1984 (G1762)"],
MEMBER["World Geodetic System 1984 (G2139)"], …
```
=> gdalsrsinfo: emit message when replacement of deprecated CRS occurs

data/osmconf.ini
Railway is very common OSM line, 58th of mostly used attribute incluing polygon.
https://taginfo.openstreetmap.org/keys/railway
* OS:
* Compiler:
=> OSM: extended attributes of line by railway

autotest/gdrivers/saga.py, frmts/saga/sagadataset.cpp
Quite a straighforward change.
I tested locally using
```
import rasterio
rst = '/home/johan/git/saga-gis/saga-gis/src/accessories/python/test_data/test.sdat'
rst_out = '/tmp/test.sdat'
with rasterio.open(rst) as src:
arr = src.read()[0]
profile = src.profile
profile["nodata"] = 56
print(profile)
arr = np.where(arr == 256, 0, arr).astype("int16")
with rasterio.open(rst_out, "w", **profile) as dst:
dst.write(arr, 1)
```
and asserted that /tmp/test.sgrd contains 
NODATA_VALUE	= 56.000000
I tried adding a test to the gdal test suite, but I'm missing how to save the file correctly:
```
##############################################################################
def test_saga_9():
gdal_type = gdal.GDT_Float64
ds = gdal.GetDriverByName('SAGA').Create('tmp/test9.sdat', 2, 2, 1, gdal_type)
ds = …
```
=> SAGA: allow setting nodata

frmts/raw/byndataset.cpp
Helps reading datasets such as http://s3.microsurvey.com/os/fieldgenius/geoids/Lithuania.zip
The reported CRS will still be a Canadian one...
CC @IvanLucena
=> BYN: remove validation of nTideSys and nPtType fields

autotest/gdrivers/netcdf.py, doc/source/drivers/raster/netcdf.rst, frmts/netcdf/netcdfdataset.cpp, frmts/netcdf/netcdfdataset.h
and in CreateCopy() use NC_GLOBAL#Conventions metadata item from source
dataset if present.
-  **WRITE_GDAL_VERSION=[YES/NO]**: (GDAL >= 3.5.0)
Define if a "GDAL" text global attribute should be added on file creation
with the GDAL version. Defaults to YES
-  **WRITE_GDAL_HISTORY=[YES/NO]**: (GDAL >= 3.5.0)
Define if the "history" global attribute should be prepended with a date/time
and GDAL information. Defaults to YES.
=> netCDF: add WRITE_GDAL_VERSION and WRITE_GDAL_HISTORY creation option

cmake/modules/packages/FindPoppler.cmake, doc/source/build_hints.rst, frmts/pdf/CMakeLists.txt
to be consistent with other FindPoppler.cmake modules like https://github.com/pfultz2/extra-cmake-modules/blob/master/find-modules/FindPoppler.cmake or https://api.kde.org/ecm/find-module/FindPoppler.html
=> CMake: use Poppler_ for variable names

doc/source/development/rfc/index.rst, doc/source/development/rfc/rfc85_policy_code_additions.rst
Rendered document at https://github.com/rouault/gdal/blob/rfc_85/doc/source/development/rfc/rfc85_policy_code_additions.rst
=> Add RFC 85: Policy regarding substantial code additions

.github/workflows/cmake_builds.yml
build-windows-conda builds fail with a
mkdir (6656) C:\Miniconda\envs\gdalenv\Library\usr\bin\mkdir.exe: *** fatal error - cygheap base mismatch detected - 0x180347408/0x180349408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
Comparing the last good build
https://github.com/OSGeo/gdal/runs/4939650106?check_suite_focus=true
and the first bad one
https://github.com/OSGeo/gdal/runs/4940229374?check_suite_focus=true
it seems the issue is …
=> CI: fix crash on Windows Conda CMake builds

gdal.cmake
Fixes a cmake error with `MINGW` and `CMAKE_BUILD_TYPE` `Debug`
mingw triplets with vcpkg, CMake 3.21
=> Fix MinGW Debug builds with CMake

autotest/ogr/ogr_fielddomain.py, gcore/gdal.h, gcore/gdal_priv.h, gcore/gdaldataset.cpp, ogr/ogr_core.h, ogr/ogrsf_frmts/generic/ogremulatedtransaction.cpp, ogr/ogrsf_frmts/generic/ogrmutexeddatasource.cpp, ogr/ogrsf_frmts/generic/ogrmutexeddatasource.h, ogr/ogrsf_frmts/mem/ogr_mem.h, ogr/ogrsf_frmts/mem/ogrmemdatasource.cpp, swig/include/Dataset.i, swig/include/ogr.i, swig/python/extensions/gdal_wrap.cpp, swig/python/extensions/ogr_wrap.cpp, swig/python/osgeo/gdal.py, swig/python/osgeo/ogr.py
This PR builds off https://github.com/OSGeo/gdal/pull/5152 (~~temporarily included in this branch~~) and adds two functions for management of field domains -- DeleteFieldDomain and UpdateFieldDomain. Both are implemented for the memory driver only for now, with GPKG driver implementations to follow (in a separate PR)
=> Add domain management functions

autotest/gcore/vsis3.py, port/cpl_vsil.cpp, port/cpl_vsil_curl.cpp, port/cpl_vsil_curl_class.h, port/cpl_vsil_curl_streaming.cpp
This fixes scenarios with using repeated VSISync() that may use
/vsis3_streaming/ to download file, and /vsis3/ to upload it.
=> /vsis3/: make sure file properties of /vsis3_streaming/foo are invalidated when /vsis3/foo ones are

frmts/gtiff/gt_wkt_srs.cpp
When reading GeoTIFF projection definitions, paths previously given in OSRSetPROJSearchPaths was not taken account, leading to proj error not finding proj.db.
=> GeoTIFF : Use proj search paths (fixes #5184)

autotest/gdrivers/netcdf.py, doc/source/drivers/raster/netcdf.rst, frmts/netcdf/netcdfdataset.cpp, frmts/netcdf/netcdfdataset.h
*   netCDF: add a VARIABLES_AS_BANDS=YES/NO open option
If set to YES, and if the netCDF file only contains 2D variables of
the same type and indexed by the same dimensions, then they should be
reported as multiple bands of a same dataset. Default is NO (that is
each variable will be reported as a separate subdataset)
* netCDF: allow update mode of raster datasets
* netCDF: implement SetMetadataItem()/SetMetadata()
* netCDF: avoid warnings when CreateCopy() a non-georeferenced dataset, and opening a 1x1 non-georeferenced dataset
=> netCDF: VARIABLES_AS_BANDS=YES/NO open option, update mode and metadata related enhancements

autotest/ogr/ogr_gpkg.py, doc/source/drivers/vector/gpkg.rst, ogr/ogrsf_frmts/gpkg/ogrgeopackagedatasource.cpp, ogr/ogrsf_frmts/gpkg/ogrgeopackagedriver.cpp, ogr/ogrsf_frmts/sqlite/ogrsqlitebase.h, ogr/ogrsf_frmts/sqlite/ogrsqlitedatasource.cpp
helps fixing qgis/qgis#23991, but requires QGIS changes as well
=> GPKG: add a NOLOCK=YES option to open a file without any lock (for read-only access

.github/workflows/doc_build.yml
This pull request migrates the documentation building process to github actions.
Thanks for considering it.
It fixes #4367.
Should the azure pipeline be removed in this pull request too?
The 'spelling' step implemented in https://github.com/OSGeo/PROJ/blob/c80c4ededbad6a11e9731ae5e118f7cfd9138f67/.github/workflows/doc_build.yml#L92 fails due to some spelling warnings. I have commented it out for now. It wasn´t implemented in azure. Should it be removed?
=> Migrate doc building to github action workflows

autotest/ogr/ogr_gpkg.py, gdal/doc/source/drivers/vector/gpkg.rst, gdal/ogr/ogrsf_frmts/gpkg/ogrgeopackagedatasource.cpp, gdal/ogr/ogrsf_frmts/gpkg/ogrgeopackagedriver.cpp, gdal/ogr/ogrsf_frmts/sqlite/ogrsqlitebase.h, gdal/ogr/ogrsf_frmts/sqlite/ogrsqlitedatasource.cpp
(helps fixing qgis/qgis#23991, but requires QGIS changes as well)
Backport of PR #5207
=> [Backport 3.4] GPKG: add a NOLOCK=YES option to open a file without any lock (for read-only access)

autotest/cpp/CMakeLists.txt, autotest/cpp/Makefile, autotest/cpp/gdal_unit_test.cpp, autotest/cpp/gdal_unit_test.h, autotest/cpp/makefile.vc, autotest/cpp/test_cpl.cpp, autotest/cpp/test_data.h, autotest/cpp/test_gdal.cpp, autotest/cpp/test_gdal_aaigrid.cpp, autotest/cpp/test_gdal_dted.cpp, autotest/cpp/test_gdal_gtiff.cpp, autotest/cpp/test_ogr.cpp, autotest/cpp/test_ogr_geos.cpp, autotest/cpp/test_ogr_lgpl.cpp, autotest/cpp/test_ogr_shape.cpp, autotest/cpp/test_osr.cpp, autotest/cpp/test_osr_ct.cpp, autotest/cpp/test_osr_pci.cpp, autotest/cpp/test_osr_proj4.cpp
with the content of commit 81c82782567ed5b57930efd3ff8d67ac8f58bf45
where we couldn't reach the author, which is moved to a dedicated file.
Agreement of authors has been noted in https://github.com/OSGeo/gdal/issues/5198
Fixes #5198
=> autotest/cpp: relicence LGPL licensed files to MIT except one exception

doc/source/drivers/raster/png.rst
Adds a sentences to the docs about the libpng imposed maximum dimensions of PNG files.
#4870
=> Mention maximum dimension of PNG files (#4870)

doc/source/programs/gdal_merge.rst
Add some notes about gdal_merge's behaviour when merging nodata pixels.
Fixes #1827.
=> Doc: Add note about nodata behaviour in gdal_merge

doc/source/drivers/raster/jpeg.rst, doc/source/drivers/raster/png.rst
Further improve documentation about maximum dimensions of PNG and JPEG files. Mention libpng being used by the PNG driver similarly to what the JPEG page does.
Sorry could have thought of that in the earlier PR already.
https://github.com/OSGeo/gdal/issues/4870
Thanks to @jratike80 for their input!
=> Doc: Mention libpng on PNG page, max dimensions of JPEG

alg/gdalwarper.cpp
This makes it easier to possible to open multiple times the same warped
VRT and then distribute each warped VRT handle to different threads.
=> Warped VRT opening: do not open the source dataset with GDAL_OF_SHARED

doc/source/programs/gdal_rasterize.rst
Fixes single/double quotes for '-where' parameter in [gdal_rasterize docs](https://gdal.org/programs/gdal_rasterize.html).
On Windows (OSGeo4W), the example command `gdal_rasterize -a ROOF_H -where 'class="A"' -l footprints footprints.shp city_dem.tif` doesn't work, while `gdal_rasterize -a ROOF_H -where "class='A'" -l footprints footprints.shp city_dem.tif` does work.
* OS:
* Compiler:
=> gdal_rasterize: fix single/double quotes for '-where' parameter in docs

.github/workflows/cmake_builds.yml
At least one CI configuration must cover the minimum supported version of CMake. This PR make the GH Actions Ubuntu 20.04 cmake build use version 3.10.2
=> Build with CMake 3.10

frmts/esric/esric_dataset.cpp
Fix a file naming bug in the Esri bundled cache driver. The bug did not affect the lower resolution levels, where a single file is present.
* OS:
* Compiler:
=> ESRIC: Fix bundle file name

port/cpl_vsil_curl.cpp
Improves the error message when a VSI request fails. This is to simplify debugging such issues as knowing the response code can help understand what's the underlying cause.
Example output with the fix:
```
$ gdal_translate -srcwin 10 10 2000 2000 /vsigs/foobar/raster.tif out.tif
Input file size is 170239, 79702
ERROR 1: Request for 1859354131-1859361062 failed with response_code=42
ERROR 1: Request for 1861843881-1861850812 failed with response_code=42
ERROR 1: Request for 1865380401-1865387332 failed with response_code=42
ERROR 1: Request for 1869606905-1869613836 failed with response_code=42
```
=> VSICurl: Print response code for failed range requests

doc/source/drivers/raster/netcdf.rst, frmts/netcdf/netcdfdataset.cpp
Perhaps more convenient for usage in GUI like QGIS than the existing
GDAL_NETCDF_IGNORE_XY_AXIS_NAME_CHECKS environment variable
=> netCDF: add a IGNORE_XY_AXIS_NAME_CHECKS=YES open option (refs qgis/QGIS#47158)

cmake/helpers/CheckDependentLibraries.cmake
Windows Conda builds with the MrSID drivers failed because it couldn't
find the geotiff headers. Other drivers need it but must include the
Conda include directories because of other packages, hence it was
unnoticed.
geotiff-config.cmake doesn't define an explicit CMake target but only
CMake variables.
CC @dg0yt
=> CMake: fix handling of geotiff-config.cmake

frmts/mrf/PNG_band.cpp
PNGs can be considerable larger than the input, especially if zlib level zero is used, which means store uncompressed.
This change makes the output buffer larger and enforces a minimum zlib level of 1.
* OS:
* Compiler:
=> MRF: Adjust PNG limits

.github/workflows/cmake_builds.yml, autotest/postinstall/test_pkg-config.sh
- Uses msys2/setup-msys2@v2 to setup the Mingw64 CMake CI environment, including numpy.
Mingw + python setup time: 4 min instead of 15 min
- Configures GH Actions cache to actually enable `ccache` effects. 
Build step with empty cache: 26 min 
Build step with full cache: 1 min 
Cache size: 0.03 GB
- Adds post-install test with `pkg-config` for Mingw64.
=> CI: Revise mingw cmake build

frmts/hfa/hfadataset.cpp, frmts/hfa/hfaopen.cpp
Default `spheroid.tab` from `Erdas imagine` defines "Pulkovo_1942" datum as "Pulkovo 1942" (without "_" symbol), so we need to translate these names on read/write for correct interaction with `Erdas`.
=> HFA: Fix "Pulkovo 1942" datum write to IMG files

swig/python/gdal-utils/osgeo_utils/gdal2tiles.py, swig/python/gdal-utils/scripts/gdal2tiles.py
Eliminate running mpi4py.futures module by switching to MPICommExecutor.
Allows launch via "mpiexec ... python -m osgeo_utils.gdal2tiles --mpi ..."
in addition to "mpiexec ... gdal2tiles.py --mpi ..."
=> gdal2tiles: simplify mpi4py launch

.github/workflows/cmake_builds.yml
The --test-dir option is new to cmake 3.20 and previous versions didn't
raise any warning/error about it, and thus just tried to find tests in
the current directory
=> CI: make ctest actually do something with cmake 3.10.2 on Ubuntu configuration

swig/python/gdal-utils/osgeo_utils/gdal2tiles.py, swig/python/gdal-utils/scripts/gdal2tiles.py
An incompatibility between pdb and multiprocessing using the
'spawn' start method was being worked around by setting
__spec__ = None in the gdal2tiles wrapper script.
Moved workaround into the gdal2tiles module and made more general by
fixing __spec__ regardless of where the __main__ module is defined.
=> gdal2tiles: move workaround out of wrapper script

autotest/cpp/CMakeLists.txt, autotest/cpp/Makefile, autotest/cpp/data/pixelfn.vrt, autotest/cpp/makefile.vc, autotest/cpp/test_gdal_pixelfn.cpp, autotest/gcore/pixfun.py, doc/source/drivers/raster/vrt.rst, frmts/vrt/pixelfunctions.cpp, frmts/vrt/vrtdataset.h, frmts/vrt/vrtderivedrasterband.cpp
* Implements metadata for C++ pixel functions
* Adds two new types of arguments, to be specified in the metadata: builtins (currently `NoData`, `scale` and `offset`) and constants
* Adds two new builtin functions: `replace_nodata` and `scale`
=> Pixelfn metadata

ogr/ogr_core.h
As discussed in https://lists.osgeo.org/pipermail/gdal-dev/2022-February/055504.html
when using clang++ options "-Werror,-Wfloat-equal" compile fails on an internal header:
/usr/local/gdal.git.llvm/include/ogr_core.h:158:21: error: comparing floating point
with == or != is unsafe [-Werror,-Wfloat-equal]
        return MinX == other.MinX &&
               ~~~~ ^  ~~~~~~~~~~
+ 3 similar errors.
Turns on same compiler #pragma as used earlier in the same header file.
I did _not_ switch to
#ifdef __GNUC__
as that does not fix the failure with clang++13.
This is pull/commit that causes the problem. 
https://github.com/OSGeo/gdal/pull/5122/commits/3d877aa5da8868ed5c3aacf98845c90bc0d36e54
* OS:  Ubuntu 21.10
* Compiler: clang++ 13.0.0
=> OGREnvelope: ignore fp warnings for operator== like IsInit()

doc/source/drivers/raster/jp2openjpeg.rst, doc/source/drivers/raster/sentinel2.rst, doc/source/programs/gdal_grid.rst
Adds missing decl_configoption reference tag in [gdal_grid](https://gdal.org/programs/gdal_grid.html) (GDAL_NUM_THREADS), [jp2openjpeg](https://gdal.org/drivers/raster/jp2openjpeg.html) (GDAL_NUM_THREADS and GDAL_GEOREF_SOURCES) and [sentinel2](https://gdal.org/drivers/raster/sentinel2.html) (GDAL_NUM_THREADS and GDAL_CACHEMAX) docs.
=> Docs: add missing decl_configoption in gdal_grid, jp2openjpeg and sentinel2

autotest/cpp/test_osr_ct.cpp, autotest/gcore/vrtmisc.py, autotest/ogr/ogr_geojson.py, autotest/ogr/ogr_gml_geom.py, autotest/osr/osr_ct.py, autotest/osr/osr_ct_proj.py, autotest/osr/osr_esri.py, autotest/osr/osr_ozi.py, autotest/pymod/gdaltest.py, autotest/pyscripts/test_osr_util.py, ogr/ogrspatialreference.cpp
It can be set to "TRADITIONAL_GIS_ORDER" / "AUTHORITY_COMPLIANT" (the later
being the default value when the option is not set) to control the value of the
data axis to CRS axis mapping strategy when a OSRSpatialReference object is
created. Calling SetAxisMappingStrategy() will override this default value.
=> Add a OSR_DEFAULT_AXIS_MAPPING_STRATEGY configuration option

.github/workflows/ubuntu_20.04/build-deps.sh
Fix ubuntu root user execute this ci script but tar filegdb.tgz failed.
* OS:
* Compiler:
=> fix(ci): ubuntu root tar ownership dont match

frmts/dimap/dimapdataset.cpp
PNEO `Radiometric_Data.Radiometric_Calibration.Instrument_Calibration.Band_Measurement_List.*` has changed the nomenclature of `BAND_ID` :cry: and is now referenced as `R`,`G`,`B`,`NIR`,`RE`,`DB` instead of the previous `B0`,`B1`, etc...
This pull request silences the warning that is raised when `BAND_ID` does not match `B[0-9]+` . A cleaner solution mapping the band's alphabetic id with it's band number is desirable for a future release.
=> DIMAP: avoid warning when extracting metadata from unsupported band_id

frmts/dimap/dimapdataset.cpp
As a followup to #5419, this patch assigns metadata to all 6 PNEO bands. Should also correctly handle the B0,B1,B2,B3 cases and adds band metadata to "P"/"PAN".
Tested on 18 combinations of P,PMS,PMS-FS etc..., band metadata is registered correctly except in the PMS-X case (where the 3 bands are ordered NIR,R,G), but handling that specific case would require a more significant refactoring.
=> DIMAP: register metadata on all 6 PNEO bands

doc/source/programs/gdal_calc.rst
Improve doc readability of --extent gdal_calc option
(I didn't compile the doc locally to test my changes)
=> Improve doc readability of --extent gdal_calc option

doc/source/drivers/raster/vrt.rst
Small documentation addition, example code for 'xml:VRT' metadata domain from a non-file data source. 
This example shows how to obtain the XML content of a VRT representation of a raster, without instantiating/reading an actual file. 
Prompted by mailing list discussion: https://lists.osgeo.org/pipermail/gdal-dev/2022-March/055544.html
=> vrt.rst:  example code, xml domain for VRT content

autotest/gcore/tiff_write.py, frmts/gtiff/geotiff.cpp
This limitation came from the initial revision of metadata writing, in e86e2db8d5ddd5d716384f5dd49ab2b435e3879b,
20 years ago. There's no limitation in the TIFF spec nor in libtiff
itself, to text tag data larger than 32 KB, so just remove it.
=> GTiff: remove limitation to 32,000 bytes when writing the GDAL metadata tag (fixes #4116)

swig/python/README.rst
I didn't change much, but this was very out of date -- `easy_install` is not a thing anymore.
And I added a section on conda, because that is by far the easiest way to get GDAL on Windows and Mac systems, and maybe even LInux.
=> Updated install instructions for Python bindings

port/cpl_aws.cpp, port/cpl_aws_win32.cpp
Fixes undefined symbols when building without atlbase.h on windows.
Amends #5436.
---
Wish list:
For packaging, I would prefer to control "AWS EC2 host detection" as a feature, at least with CMake.
(This is possible with nmake now via `HAVE_ATLBASE_H`.)
=> Fix build without atlbase.h

doc/source/drivers/vector/xls.rst, doc/source/drivers/vector/xlsx.rst
Adds missing decl_configoption reference tag in [XLS](https://gdal.org/drivers/vector/xls.html) (OGR_XLS_HEADERS and OGR_XLS_FIELD_TYPES) and [XLSX](https://gdal.org/drivers/vector/xlsx.html) (OGR_XLSX_HEADERS and OGR_XLSX_FIELD_TYPES) drivers docs.
=> Docs: add missing decl_configoption in XLS and XLSX drivers

frmts/netcdf/netcdfdataset.cpp
Fixes an error when building netcdf without NETCDF_HAS_NC4.
Linux gcc:
~~~
/mnt/vcpkg-ci/buildtrees/gdal/src/58ed61cfea-138d7f5529.clean/frmts/netcdf/netcdfdataset.cpp: At global scope:
/mnt/vcpkg-ci/buildtrees/gdal/src/58ed61cfea-138d7f5529.clean/frmts/netcdf/netcdfdataset.cpp:724:23: error: expected constructor, destructor, or type conversion before ‘(’ token
724 |     CreateBandMetadata(paDimIds, panExtraDimGroupIds, panExtraDimVarIds);
|                       ^
~~~
Windows cl:
~~~
D:\buildtrees\gdal\src\58ed61cfea-138d7f5529.clean\frmts\netcdf\netcdfdataset.cpp(724): error C2065: 'paDimIds': undeclared identifier
D:\buildtrees\gdal\src\58ed61cfea-138d7f5529.clean\frmts\netcdf\netcdfdataset.cpp(724): error C2065: 'panExtraDimGroupIds': undeclared identifier …
=> Fix compilation without NETCDF_HAS_NC4

doc/source/programs/gdal_calc.rst
Fixes a typo in color-table option string for gdal_calc.py docs: modify option string from `color-table` to `--color-table`.
See https://github.com/OSGeo/gdal/blob/1c5bc766513c4407f702bd8cd8bfa958ed61cfea/swig/python/gdal-utils/osgeo_utils/gdal_calc.py#L673
=> Docs: fix a typo in color-table option for gdal_calc

doc/source/programs/pct2rgb.rst, doc/source/programs/rgb2pct.rst, swig/python/gdal-utils/osgeo_utils/pct2rgb.py, swig/python/gdal-utils/osgeo_utils/rgb2pct.py
- adds the `-pct` option description in the [`pct2rgb.py`](https://gdal.org/programs/pct2rgb.html) docs (fixes https://github.com/OSGeo/gdal/pull/4587#issuecomment-932778801)
- fixes a typo in the `-pct` option description of [`rgb2pct.py`](https://gdal.org/programs/rgb2pct.html)  docs
- fixes some typos in the `-pct` option help string of `pct2rgb.py` and `rgb2pct.py`
=> Docs and help strings: add missing -pct option description in pct2rgb and fix some typos in pct2rgb and rgb2pct

autotest/gcore/tiff_srs.py, frmts/gtiff/gt_wkt_srs.cpp, frmts/gtiff/libgeotiff/geo_normalize.c
Avoid erroneous new warnings
"The definition of geographic CRS EPSG:%d got from GeoTIFF keys "
"is not the same as the one from the EPSG registry, "
"which may cause issues during reprojection operations. "
- do not massage datum name to WKT1 (avoid warnings with datum names
that have spaces)
- do not try to compare when the datum is dynamic
- do not try to compare when the code is of a geographic 3D CRS.
Other issues fixed during investigation:
- Fix handling of prime meridian with units != degree
- Internal libgeotiff: fix import of dynamic datum.
=> GTIFF SRS reading: avoid warnings due to previous fix for #5399 and other fixes

cmake/helpers/GdalDriverHelper.cmake
When switching a GDAL/OGR_ENABLE_DRIVER_xxx_PLUGIN value from ON to OFF,
it is easy to get stale plugins in the build and install trees, that can
cause weird issues, due to the plugin having precedence on the core
driver. So clean any such stale plugin in that situation.
=> CMake: add logic to remove stale plugins

.github/workflows/android.yml, .github/workflows/android_cmake.yml, .github/workflows/asan_build.yml, .github/workflows/clang_static_analyzer.yml, .github/workflows/cmake-lint.yml, .github/workflows/cmake_builds.yml, .github/workflows/code_checks.yml, .github/workflows/conda.yml, .github/workflows/doc_build.yml, .github/workflows/fedora_rawhide.yml, .github/workflows/macos.yml, .github/workflows/mingw_w64.yml, .github/workflows/ubuntu_18.04.yml, .github/workflows/ubuntu_18.04_32bit.yml, .github/workflows/ubuntu_20.04.yml, .github/workflows/validate_xml.yml, .github/workflows/windows_build.yml
This change to the workflows cancel CI runs for a branch or PR when a new push is made to the same target. Typically, this happens when a contributor notices a defect after one push, locally or by a fast CI jobs (e.g. CMake Lint) and pushes a fix while the long-running workflows are still in progress.
This a common behaviour in other CIs, but needs extra activation in GH Actions. It frees runners from obsolete workload, making them available for running new jobs.
Upsides: This also affects the additional workflows in forks.
Downsides: A notification is sent for each canceled workflow. GDAL has many of them...
References: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
Disclaimer: I'm not an expert on GH Actions.
=> CI: Cancel PR and branch workflows on new push

alg/gdaltransformer.cpp, apps/gdalwarp_lib.cpp, autotest/alg/applyverticalshiftgrid.py
Due to change https://github.com/OSGeo/PROJ/pull/3119
=> gdalwarp: fix issue with vertical shift mode when only one of the CRS is 3D, with PROJ 9.1

.github/workflows/cmake-lint.yml
Another small cleanup. Unless you want to remove this workflow entirely.
=> CI: Disable CMake Lint job, not task

frmts/gtiff/geotiff.cpp, frmts/gtiff/libtiff/tif_dirwrite.c
=> GTiff: avoid hang when trying to create a larger than 4GB classic TIFF, and switch to BigTIFF before that happens

ogr/ogrsf_frmts/sosi/ogrsosilayer.cpp
The OGR SOSI driver segfaults if a SOSI file contains an invalid point geometry definition (i.e. two rows with identical coordinate pairs).
This PR adds a warning for those cases and skips the duplicated point.
=> OGR SOSI driver: catch segfault with invalid point geometries

.github/workflows/cmake_builds.yml
This reverts commit 4424fde8780ff1e0bbda4918d08293e3e92acc4e.
Conda has updated to a fixed Poppler package
Fixes #5513
=> Revert "CI: fix build issue on CMake build-windows-conda config (refs #5513)"

apps/gdalbuildvrt_lib.cpp, autotest/utilities/test_gdalbuildvrt_lib.py
Similar to 13cfbf880c19e62517c1b7f60c01c156fba1a6a5 that applied only to non-separate mode
=> GDALBuildVRT(): in -separate mode, add support for sources such as MEM dataset or non-materialized VRT files

autotest/cpp/test_cpl.cpp, port/cpl_recode_iconv.cpp
If the number of bytes per character was different from the size of
wchar_t, the size of the input was not computed correctly.
=> Fix out of bounds read in CPLRecodeFromWCharIconV()

apps/gdalbuildvrt_lib.cpp, autotest/utilities/test_gdalbuildvrt_lib.py
Fixes issue introduced by bbdced448d964d62917ece73b2afbd2be6067584
and reported on https://lists.osgeo.org/pipermail/gdal-dev/2022-March/055662.html
=> gdalbuildvrt: fix 3.4.1 regression when using -b to select less bands than source dataset

autotest/ogr/ogr_flatgeobuf.py, ogr/ogrsf_frmts/flatgeobuf/ogr_flatgeobuf.h, ogr/ogrsf_frmts/flatgeobuf/ogrflatgeobuflayer.cpp
CC @bjornharrtell 
2 commits: the first one is a bugfix, the second one an improvement:
- fix GetFeature() when featuresCount != 0 and indexNodeSize == 0, such as files produced by the next commit
- in SPATIAL_INDEX=NO mode, write a meaningful featureCount and extent in the header. Previously featureCount=0 and extent=null where written. Writing meaningful values is a bit tricky since it involves first creating a dummy header of the right size, and overriding it at file closing.
=> FlatGeobuf: in SPATIAL_INDEX=NO mode, write a meaningful featureCount and extent in the header

autotest/cpp/test_cpl.cpp, gdal/port/cpl_recode_iconv.cpp
=> [3.4 backport] Fix out of bounds read in CPLRecodeFromWCharIconV() (#5542)

frmts/fits/fitsdataset.cpp
=> FITS: fix non-conformant use of &v[0] that crashes with clang 14 -O2

autotest/cpp/test_osr.cpp, autotest/ogr/data/geojson/featurecollection_point.json, autotest/ogr/data/geojson/featurecollection_pointz.json, autotest/ogr/data/geojson/pointz.json, autotest/ogr/ogr_geojson.py, ogr/ogr_spatialref.h, ogr/ogrsf_frmts/geojson/ogrgeojsondatasource.cpp, ogr/ogrsf_frmts/geojson/ogrgeojsonreader.cpp, ogr/ogrspatialreference.cpp
Cf 'An OPTIONAL third-position element SHALL be the height in meters above or below
the WGS 84 reference ellipsoid', paragraph 4. of https://datatracker.ietf.org/doc/html/rfc7946
=> GeoJSON reader: expose EPSG:4979 as CRS when none is specified and 3D geoms are found

autotest/gdrivers/gribmultidim.py, doc/source/drivers/raster/grib.rst, frmts/grib/gribdataset.cpp
We disable use of the .idx file as it doesn't contain all the details we
need to instanciate the GRIBArray objects.
=> GRIB multidim: fix crash when a .idx file is present (fixes #5569)

autotest/gdrivers/sentinel2.py, frmts/sentinel2/sentinel2dataset.cpp
Previous code was identifying zipped S2 datasets based only on their file names. Thus renaming a S2 dataset containing zip file would make it invisible to glda. This commit introduces extra check for presence of format specific metadata files inside a zip to determine if it is a S2 containing zip file. Primary detection is still done by file name thus speeding up the most common case when file name indicates on its content.
I was not able to run black on Python code and clang-format on C++ code as existing code base has not been reformatted.
=> SENTINEL2: identify zipped S2 datasets from file content

frmts/mrf/LERC_band.cpp
Lerc2 decoding might need access to three bytes past the end of the compressed buffer
When decoding, LERC2 might access to up three more bytes than the encoded buffer. When refactoring the MRF code to use the LERC2 public API, this padded was not taken into account, this PR restores the correct behavior.
* OS:
* Compiler:
=> MRF: Add padding after encoding LERC

cmake/helpers/configure.cmake, cmake/template/cpl_config.h.in, configure.ac, port/cpl_config.h.in, port/cpl_conv.cpp
Renames `GDAL_HAVE_XLOCALE_H` to `HAVE_XLOCALE_H` to be consistent with `ogr/ogrsf_frmts/geojson/libjson/json_tokener.c` that uses `HAVE_XLOCALE_H`. Otherwise it may not work compiling that file when there is `xlocale.h`
#5027
Detected doing Cross Compilation in macOS x86_64 to M1 (arm)
=> Rename GDAL_HAVE_XLOCALE_H to HAVE_XLOCALE_H

cmake/helpers/CheckDependentLibraries.cmake, doc/source/build_hints.rst, gdal.cmake
From updated build_hints page:
```
Some of the GDAL dependencies (GEOTIFF, GIF, JPEG, JSONC, LERC, OPENCAD, PNG, QHULL, TIFF, ZLIB)
have a copy of their source code inside the GDAL source code tree. It is possible
to enable this internal copy by setting the GDAL_USE_<Packagename_in_upper_case>_INTERNAL:BOOL=ON
variable. When set, this has precedence over the external library that may be
detected. The behavior can also be globally controlled with the following variable:
.. option:: GDAL_USE_INTERNAL_LIBS=ON/OFF/WHEN_NO_EXTERNAL
Control how internal libraries should be used.
If set to ON, they will always be used.
If set to OFF, they will never be used (unless individually enabled with
GDAL_USE_<Packagename_in_upper_case>_INTERNAL:BOOL=ON)
If set to WHEN_NO_EXTERNAL (default value), they …
```
=> CMake: add a GDAL_USE_INTERNAL_LIBS=ON/OFF/WHEN_NO_EXTERNAL variable

third_party/LercLib/BitStuffer2.cpp, third_party/LercLib/BitStuffer2.h
Apply the LERC "fix v22 decode short blob" patch from Esri/lerc to the internal Lerc library source. 
https://github.com/Esri/lerc/pull/198
* OS:
* Compiler:
=> MRF: Prevent LERC out of bounds access

doc/source/drivers/raster/ecw.rst, doc/source/drivers/raster/xyz.rst
Fixes the links to the gdal_grid and gdal_edit tools docs in the [XYZ](https://gdal.org/drivers/raster/xyz.html) and [ECW](https://gdal.org/drivers/raster/ecw.html) drivers docs.
Currently, such links, ``gdal_grid <gdal_grid.html>`__` and ``gdal_edit.py <gdal_edit.html>`__`, point respectively to non existent https://gdal.org/drivers/raster/gdal_grid.html and https://gdal.org/drivers/raster/gdal_edit.html pages.
I've substituted them with `:ref:`gdal_grid`` and `:ref:`gdal_edit``.
I wonder if this would have been addressed by the redirection code in https://github.com/OSGeo/gdal/blob/de5c6b3dc4016c2abf055a9c7281e17bdad53e73/doc/source/_extensions/redirects.py#L85-L86
=> Fix gdal_grid and gdal_edit links in XYZ and ECW drivers docs

frmts/grass/pkg/Makefile.in
Add `-Wl,-rpath,<path>` to Makefile.in of the GDAL GRASS driver. This is supposed to be a generic solution replacing the [Debian patch](https://salsa.debian.org/debian-gis-team/gdal-grass/-/commit/0192b0418e04d79678bdd5c4c377b8cece5e0939).
The reason for this PR, as well as the Debian patch, is that GRASS shared libraries are in a non-standard location that is usually not in the common list of directories with shared libraries, also not in `/etc/ld.so.conf.d/*` and not in `LD_LIBRARY_PATH`.
=> GDAL GRASS driver: add rpath to Makefile.in

autotest/ogr/ogr_parquet.py, ogr/ogrsf_frmts/parquet/ogrparquetlayer.cpp, ogr/ogrsf_frmts/parquet/ogrparquetwriterlayer.cpp
- on layer creation, no longer warn when no CRS is provided, since this
is now an optional member
- on reading, when 'crs' is absent, assume EPSG:4326 as mentioned in the
specification
=> GeoParquet: update to version 0.2.0

ogr/ogrsf_frmts/cad/libopencad/CMakeLists.txt, ogr/ogrsf_frmts/cad/libopencad/cadlayer.cpp
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=46887
Otherwise we get the following infinite call stack:
```
#5  0x00007fffedee20a6 in DWGFileR2000::GetObject (this=0x5555557a5c60, dHandle=0, bHandlesOnly=false) at /home/even/gdal/gdal/ogr/ogrsf_frmts/cad/libopencad/dwg/r2000.cpp:1098
#6  0x00007fffedf191e0 in CADLayer::addHandle (this=0x5555557a4180, handle=512, type=CADObject::INSERT, cadinserthandle=512) at /home/even/gdal/gdal/ogr/ogrsf_frmts/cad/libopencad/cadlayer.cpp:178
#7  0x00007fffedf194f2 in CADLayer::addHandle (this=0x5555557a4180, handle=512, type=CADObject::INSERT, cadinserthandle=512) at /home/even/gdal/gdal/ogr/ogrsf_frmts/cad/libopencad/cadlayer.cpp:226
#8  0x00007fffedf194f2 in CADLayer::addHandle (this=0x5555557a4180, handle=512, type=CADObject::INSERT, …
```
=> CAD/libopencad: avoid infinite recursion / stack overflow.

autotest/ogr/ogr_parquet.py, doc/source/drivers/vector/parquet.rst, ogr/ogrsf_frmts/parquet/ogr_parquet.h, ogr/ogrsf_frmts/parquet/ogrparquetdriver.cpp, ogr/ogrsf_frmts/parquet/ogrparquetwriterlayer.cpp
- update version to 0.3.0
- add orientation=counterclockwise metadata item
- add a POLYGON_ORIENTATION=COUNTERCLOCKWISE/UNMODIFIED layer creation
option to let the user decide if winding order must be adjusted
(default), or not.
=> Parquet: update to GeoParquet 0.3.0

autotest/gdrivers/nitf.py, frmts/nitf/nitfdataset.cpp
Defines the polar zone coordinates system in NITF for CADRG (RPF) datasets equal to the definition in ADRG and SRP to make comparing of metadata easier.
none
* OS:
* Compiler:
=> NITF: CADRG polar zone coordinate system definition aligned with ADRG and SRP

port/cpl_vsil_unix_stdio_64.cpp
Fixes compilation on Haiku OS (https://www.haiku-os.org/). Like Solaris, Haiku doesn't have the `d_type` member of the `dirent` structure.
Is this ok, or would you rather I add a cmake `CHECK_STRUCT_HAS_MEMBER` test?
https://github.com/haikuports/haikuports/pull/6854
* OS: Haiku OS
* Compiler: gcc 11
=> Add support for Haiku OS

cmake/helpers/CheckDependentLibraries.cmake
This PR enables using netcdf's exported CMake config.
This allows to handle transitive usage requirements, and it saves expensive tests for feature detection.
Fixes #5452.
Depends on #5450.
~Blocked by https://github.com/msys2/MINGW-packages/issues/10993~
=> CMake: Use netcdf config

ogr/ogrsf_frmts/cad/libopencad/cadlayer.cpp
=> libopencad: avoid out-of-bounds access on invalid file. Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=45962

doc/source/drivers/raster/grass.rst, doc/source/drivers/vector/grass.rst
This PR reduces the content of the two raster and vector driver manual pages to external links to the new pages, reachable here:
- https://github.com/OSGeo/gdal-grass/blob/main/docs/grass_raster.md
- https://github.com/OSGeo/gdal-grass/blob/main/docs/grass_vector.md
Fixes #5667
=> GDAL-GRASS driver docs: simplify and point to external source

alg/CMakeLists.txt, alg/GNUmakefile, alg/gdal_alg_priv.h, alg/gdalgeoloc.cpp, alg/gdalgeoloc.h, alg/gdalgeoloc_carray_accessor.h, alg/gdalgeoloc_dataset_accessor.h, alg/gdalgeolocquadtree.cpp, alg/gdalgeolocquadtree.h, alg/gdaltransformer.cpp, alg/gdalwarper.cpp, alg/makefile.vc, alg/rasterfill.cpp, autotest/cpp/test_gdal.cpp, autotest/gcore/data/sstgeo.vrt, autotest/gcore/data/warpsst.vrt, autotest/gcore/geoloc.py, autotest/gcore/transformer.py, autotest/gdrivers/netcdf.py, autotest/gdrivers/vrtwarp.py, doc/source/development/rfc/rfc4_geolocate.rst, frmts/netcdf/netcdfdataset.cpp, gcore/CMakeLists.txt, gcore/GNUmakefile, gcore/gdalcachedpixelaccessor.h, gcore/gdalmultidim.cpp, port/cpl_quad_tree.cpp, port/cpl_quad_tree.h
Despite a few past attempts to improve it, the inverse transformer
relying on a backmap was far from being exact, with errors frequently
above 1 pixel.
This commit fixes it by using an (exact, non-interative) inverse bilinear
interpolation method (https://stackoverflow.com/a/812077) during backmap
generation itself (when the geolocation array expresses an affine
transformation, the backmap itself is exact), but also when inverse
transforming a coordinate, to fine tune the initial solution obtained
by bilinear interpolation of the backmap.
The FSHIFT and ISHIFT offsets, that were probably more empirical than
are no longer needed.
The oversampling factor [0.1,2] (default: 1.3) of the backmap can now be
controlled with the GEOLOC_BACKMAP_OVERSAMPLE_FACTOR transformer option
(or the …
=> Geoloc transformer: fix inverse transform to be exact

doc/source/programs/ogr2ogr.rst
The -spat and -clipdstsql options are misspelled.
=> ogr2ogr.rst: fix typos in -clipsrc and -clipdst documentation

doc/source/development/rfc/rfc31_ogr_64.rst
**RFC 31** makes reference to a `DETECT_TYPE` open option, but this option does not appear to exist. The name as implemented by the Shapefile driver is actually `ADJUST_TYPE`.
Reference:
* [ogrshapelayer.cpp](https://github.com/OSGeo/gdal/blob/08713ef0092be807434a945897682db4a92a07e6/ogr/ogrsf_frmts/shape/ogrshapelayer.cpp)
* [ogrshapedriver.cpp](https://github.com/OSGeo/gdal/blob/08713ef0092be807434a945897682db4a92a07e6/ogr/ogrsf_frmts/shape/ogrshapedriver.cpp)
=> rfc31_ogr_64.rst: correct option name to ADJUST_TYPE

swig/python/gdal-utils/osgeo_utils/gdal2tiles.py
Use with statement to ensure multiprocessing.Pool cleanup
as well as handling GDAL_CACHEMAX adjustment and reset.
=> gdal2tiles: refactor multiprocessing (fixes #5581)

port/cpl_recode_iconv.cpp
I'm currently packaging gdal for use with Buildroot (https://buildroot.org/) which basically aids in cross-compiling
for various (embedded) toolchains/architectures.
Unfortunately with some toolchains (e.g. arm-buildroot-linux-uclibcgnueabi-gcc) I'm getting errors during compilation:
```
cpl_recode_iconv.cpp: In function ‘char* CPLRecodeIconv(const char*, const char*, const char*)’:
cpl_recode_iconv.cpp:90:18: error: invalid cast from type ‘int’ to type ‘iconv_t’ {aka ‘long int’}
90 |     if( sConv == reinterpret_cast<iconv_t>(-1) )
|                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cpl_recode_iconv.cpp: In function ‘char* CPLRecodeFromWCharIconv(const wchar_t*, const char*, const char*)’:
cpl_recode_iconv.cpp:239:18: error: invalid cast from type ‘int’ to type ‘iconv_t’ {aka ‘long int’} …
```
=> port/cpl_recode_iconv.cpp: fix invalid cast error

frmts/png/pngdataset.cpp
When creating a PNG failed the error message did not include the root cause of the failure. Added VSIStrerror(errno) following example of GTiff.
=> PNG: report cause when unable to create file

autotest/gdrivers/zarr_driver.py, frmts/zarr/zarrdriver.cpp
And when exposing subdatasets, also expose the main/current one in the
list
=> Zarr: hide X/Y subdatasets of a single 2D georeferenced array when opening with 2D raster API (fixes #5681)

BUILDING.md, README.md
This PR adds a BUILDING.md, so that people who try to figure out how to build by looking at the source code will find the existing documentation.
=> BUILDING.md: Add build instructions

frmts/kea/keadataset.cpp
This PR adds support for the `GDT_Int64` and `GDT_UInt64` image types. The underlying `libkea` library always had support for 64 bit types but with this PR these types can now be passed through to it.
Any chance a 64 bit int type may be added to the RasterAttributeTable in future? This is another area where `libkea` does have support and would be nice to access from GDAL...
* OS:
* Compiler:
=> KEA: add 64bit image types

ogr/ogr_feature.h
Reported and suggested by @andrew-aitchison
=> OGRFeatureDefn::GetFieldDefnUnsafe(): fix -Wsign-conversion

port/cpl_http.cpp
**vsicurl: add NEGOTIATE to proxy auth methods**
see https://github.com/curl/curl/blob/68784d73c3f8bc0d14502b4e1e930b1741c41699/docs/cmdline-opts/proxy-negotiate.d
deprecate CURLAUTH_GSSNEGOTIATE
see https://github.com/curl/curl/commit/e38ba430142153e95e2b0abe08a31d626a5c5864
=> vsicurl: add NEGOTIATE to proxy auth methods

port/cpl_http.cpp
**vsicurl: add NEGOTIATE to proxy auth methods**
see https://github.com/curl/curl/blob/68784d73c3f8bc0d14502b4e1e930b1741c41699/docs/cmdline-opts/proxy-negotiate.d
deprecate CURLAUTH_GSSNEGOTIATE
see https://github.com/curl/curl/commit/e38ba430142153e95e2b0abe08a31d626a5c5864
=> [Backport 3.5] vsicurl: add NEGOTIATE to proxy auth methods

doc/source/about_no_title.rst
The release notes URL had an extra `gdal` in the path, which made the URL invalid.
=> Corrected URL to release notes

ogr/ogrsf_frmts/vfk/vfkpropertydefn.cpp, ogr/ogrsf_frmts/vfk/vfkreader.cpp
This PR adds support for UTF-8 in VFK driver. Reason: VFK in version 6 swiched encoding from ISO-8859-2 to UTF-8 (https://www.cuzk.cz/Katastr-nemovitosti/Poskytovani-udaju-z-KN/Vymenny-format-KN/Vymenny-format-ISKN-v-textovem-tvaru/Popis_VF_ISKN-v6_0.aspx in Czech). 
This is a quick solution which can be also backported. Previously supported WINDOWS-1250 encoding is replaced by UTF-8. VFK files with WINDOWS-1250 is not used since VFK version 2. Support for WINDOWS-1250 can be discarded by GDAL VFK implementation because there is no regression.
How to test:
```sh
wget https://services.cuzk.cz/vfk/anonym/mapa/930431.zip
unzip 930431.zip
ogrinfo 602515.vfk TYPPPD -fid 1
...
VYZNAM (String) = Hranice okresu pohyblivá, nestálá (na obou koncích)
```
=> VFK: add support for UTF-8 (quick fix)

autotest/ogr/ogr_parquet.py, doc/source/drivers/vector/parquet.rst, ogr/ogrsf_frmts/arrow/ogr_feather.h, ogr/ogrsf_frmts/arrow_common/ogr_arrow.h, ogr/ogrsf_frmts/arrow_common/ograrrowlayer.hpp, ogr/ogrsf_frmts/arrow_common/ograrrowwriterlayer.hpp, ogr/ogrsf_frmts/parquet/CMakeLists.txt, ogr/ogrsf_frmts/parquet/ogr_include_parquet.h, ogr/ogrsf_frmts/parquet/ogr_parquet.h, ogr/ogrsf_frmts/parquet/ogrparquetdataset.cpp, ogr/ogrsf_frmts/parquet/ogrparquetdriver.cpp, ogr/ogrsf_frmts/parquet/ogrparquetlayer.cpp, ogr/ogrsf_frmts/parquet/ogrparquetwriterlayer.cpp
SQL statements are run through the OGR SQL engine. Statistics can be used to
speed-up evaluations of SQL requests like:
"SELECT MIN(colname), MAX(colname), COUNT(colname) FROM layername"
=> Parquet: use statistics to speed-up evaluations of SQL requests with MIN/MAX/COUNT

doc/source/build_hints.rst
Missed the relevant option when packaging up for Gentoo.
Bug: https://bugs.gentoo.org/845369
Document how to enable/disable the C# bindings build for CMake.
N/A
=> doc: add C# reference to CMake hints

autotest/gdrivers/gpkg.py, ogr/ogrsf_frmts/gpkg/gdalgeopackagerasterband.cpp, ogr/ogrsf_frmts/gpkg/gpkgmbtilescommon.h, ogr/ogrsf_frmts/gpkg/ogr_geopackage.h, ogr/ogrsf_frmts/gpkg/ogrgeopackagedatasource.cpp
If a block/tile flush happens when only a subset of all bands is
'dirty', and in particular if the alpha band is not yet written, then
the tile was wrongly considered as transparent.
The issue could happen even when writing all bands together, but under
strong pressure on the block cache, due to other threads doing
concurrent reads and forcing partial flushing.
=> GPKG: writer: fix corruption when only a subset of all bands of a tile is flushed

swig/python/gdal-utils/osgeo_utils/gdal_calc.py
gdal_calc should raise an error if it could not create output dataset, instead of raising an unexpected error when executing some code like `myOut.SetGeoTransform(GeoTransformCheck) `.
https://github.com/OSGeo/gdal/blob/d5957ab81e51e9e4244053641b26da0dc4c9e31d/swig/python/gdal-utils/osgeo_utils/gdal_calc.py#L363-L373
I notice that the gdal c++ library will put an error message to stderr, for example `ERROR 4: Attempt to create new tiff file /w/a.tif failed: No such file or directory`. But it will be useful if we detect this error in python side, because gdal_calc is not only an command line tool but a library.
=> gdal_calc: detect dataset creation failed

frmts/safe/safedataset.cpp
Fixes issue reported in https://lists.osgeo.org/pipermail/gdal-dev/2022-May/055882.html
With that fix, the only reported subdatasets now are:
```
SUBDATASET_1_NAME=SENTINEL1_CALIB:UNCALIB:S1A_IW_GRDH_1SDV_20220529T045822_20220529T045847_043421_052F5A_01B5.SAFE/manifest.safe:IW_VH:AMPLITUDE
SUBDATASET_1_DESC=Single band with IW swath and VH polarization and UNCALIB calibration
SUBDATASET_2_NAME=SENTINEL1_CALIB:UNCALIB:S1A_IW_GRDH_1SDV_20220529T045822_20220529T045847_043421_052F5A_01B5.SAFE/manifest.safe:IW_VV:AMPLITUDE
SUBDATASET_2_DESC=Single band with IW swath and VV polarization and UNCALIB calibration
SUBDATASET_3_NAME=SENTINEL1_CALIB:UNCALIB:S1A_IW_GRDH_1SDV_20220529T045822_20220529T045847_043421_052F5A_01B5.SAFE/manifest.safe:IW:AMPLITUDE
SUBDATASET_3_DESC=IW swath with all …
```
=> SAFE: for non-SLC products, do not report subdatasets that can't be opened

autotest/ogr/ogr_arrow.py, ogr/ogrsf_frmts/arrow_common/ograrrowwriterlayer.hpp
The current field metadata key for the extension name is using a double colon, but that should be a single colon, see https://arrow.apache.org/docs/format/Columnar.html#extension-types
Noticed this while testing to read GDAL produced files with pyarrow with extension types registered for those "geoarrow.<geometry_type>" types (https://github.com/jorisvandenbossche/python-geoarrow/)
Does this require a test case? 
I see that this key is actually checked for when reading, but since it also checks in the metadata for the known geometry columns (and its encoding), this ARROW:extension:name key is not required I suppose.
=> Arrow: fix extension name key in field metadata

autotest/gcore/gdal_stats.py, gcore/gdalrasterband.cpp, perftests/computeminmax.py
re-use the optimizations of ComputeStatistics(), using SSE2 when available
Before:
```
$ python perftests/computeminmax.py
testByte(): 8.776
testUInt16(): 7.174
testInt16(): 8.210
testFloat32(): 7.846
testFloat64(): 9.407
```
After:
```
$ python perftests/computeminmax.py
testByte(): 0.316
testUInt16(): 0.779
testInt16(): 2.863
testFloat32(): 6.993
testFloat64(): 8.078
```
To be compared with timings of ComputeStatistics():
```
$ python ../perftests/computestatistics.py
testByte(): 0.483
testUInt16(): 1.262
testInt16(): 28.417
testFloat32(): 29.075
testFloat64(): 30.382
```
=> GDALRasterBand::ComputeRasterMinMax(): add optimized implementation for Byte and UInt16 data types

apps/CMakeLists.txt, apps/longpathaware.manifest
This also requires the operating system to accept long paths, by setting
a LongPathsEnabled registry key to 1, e.g with the following Powershell command:
```
New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" -Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force
```
See https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=powershell#enable-long-paths-in-windows-10-version-1607-and-later
=> Windows: command line applications: embed manifest to declare longPathAware=true property (fixes #5836)

frmts/nitf/nitfdataset.cpp
=> NITF: Use correct index for image segment (fixes #5855)

ogr/ogrfeature.cpp, ogr/ogrsf_frmts/gpkg/ogrgeopackagelayer.cpp
With those improvements, the ogr_bench program on the nz-building-outlines.gpkg file mentioned in RFC 86 (https://github.com/OSGeo/gdal/pull/5830) runs from 15.2 s down to 7.5 s
=> GPKG: optimize feature reading, in particular DateTime fields

autotest/ogr/ogr_gpkg.py, ogr/ogrsf_frmts/gpkg/ogr_geopackage.h, ogr/ogrsf_frmts/gpkg/ogrgeopackagedatasource.cpp, ogr/ogrsf_frmts/gpkg/ogrgeopackagetablelayer.cpp, swig/python/gdal-utils/osgeo_utils/samples/validate_gpkg.py
(https://docs.opengeospatial.org/is/18-000/18-000.html)
There is non-user-visible change related to that (as we don't have any
API to report relationships between table), but this brings:
- recognizing the extension as known
- take it into account during column renaming and table renaming/deletion
to avoid corruption of the database.
- make the validate_gpkg.py validate the use of the extension
CC @nyalldawson
=> GPKG: preliminary non-user-visible support for Related Tables Extension

doc/source/drivers/vector/csv.rst
The default AUTODETECT_SIZE_LIMIT open option for the CSV driver is 1,000,000, as per ogrcsvlayer.cpp, but is incorrectly stated in the docs as 100,000. The PR corrects the typo.
Related to #5885
=> CSV docs: Fix default AUTODETECT_SIZE_LIMIT typo

ogr/ogrsf_frmts/hana/ogr_hana.h, ogr/ogrsf_frmts/hana/ogrhanalayer.cpp
This PR fixes the following compiler error that occurs when compiling on MacOS.
ogr_hana.h:349:5: error: unknown type name 'uint'; did you mean 'int'?
uint GetMajorVersion() const { return majorVersion_; }
=> Resolve compilation errors in HANA driver

frmts/gtiff/geotiff.cpp, frmts/jpeg/jpgdataset.h, frmts/pdf/gdal_pdf.h, frmts/pdf/pdfdataset.cpp, frmts/png/pngdataset.h, gcore/gdal_priv.h, gcore/gdalrasterband.cpp, gcore/rasterio.cpp
Fixes #5589
```cpp
/**
* \brief Return the suggested/most efficient access pattern to blocks
*        (for read operations).
*
* While all GDAL drivers have to expose a block size, not all can guarantee
* efficient random access (GSBAP_RANDOM) to any block.
* Some drivers for example decompress sequentially a compressed stream from
* top raster to bottom (GSBAP_TOP_TO_BOTTOM), in which
* case best performance will be achieved while reading blocks in that order.
* (accessing blocks in random access in such rasters typically causes the
* decoding to be re-initialized from the start if accessing blocks in
* a non-sequential order)
*
* The base implementation returns GSBAP_UNKNOWN, which can also be explicitly
* returned by drivers that expose a somewhat artificial block size, because they …
```
=> Add a GDALRasterBand::GetSuggestedBlockAccessPattern() method

.github/workflows/android.yml, .github/workflows/android_cmake.yml, .github/workflows/asan_build.yml, .github/workflows/clang_static_analyzer.yml, .github/workflows/cmake-lint.yml, .github/workflows/code_checks.yml, .github/workflows/coverity_scan.yml, .github/workflows/doc_build.yml, .github/workflows/fedora_rawhide.yml, .github/workflows/mingw_w64.yml, .github/workflows/ubuntu_18.04.yml, .github/workflows/ubuntu_18.04_32bit.yml, .github/workflows/ubuntu_20.04.yml, .github/workflows/validate_xml.yml, .github/workflows/windows_build.yml
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: naveen <172697+naveensrinivasan@users.noreply.github.com>
=> chore: Set permissions for GitHub actions

apps/ogr2ogr_lib.cpp, autotest/ogr/ogr_fgdb.py, autotest/ogr/ogr_gpkg.py, autotest/ogr/ogr_openfilegdb.py, doc/source/drivers/vector/filegdb.rst, ogr/ogrfeature.cpp, ogr/ogrsf_frmts/filegdb/FGdbDriver.cpp, ogr/ogrsf_frmts/filegdb/FGdbLayer.cpp, ogr/ogrsf_frmts/openfilegdb/ogropenfilegdblayer.cpp
FileGDB and OpenFileGDB:
- on reading, when parsing the XML layer definition, use the
AreaFieldName and LengthFieldName attributes to set the default value
of the corresponding OGR fields to the driver specific value of
"FILEGEODATABASE_SHAPE_AREA" / "FILEGEODATABASE_SHAPE_LENGTH"
FileGDB:
- on writing, add a CREATE_SHAPE_AREA_AND_LENGTH_FIELDS=YES/NO creation
option to automatically create the Shape_Area and Shape_Length special
fields
- make ogr2ogr automatically set that option when the source layer has
the Shape_Area and Shape_Length special fields
=> FileGDB/OpenFileGDB: handle Shape_Area/Shape_Length fields

ogr/ogrsf_frmts/hana/ogrhanatablelayer.cpp
This PR fixes another compilation error observed on some systems.
=> Fix missing header file in ogrhanatablelayer.cpp

doc/source/build_hints.rst, doc/source/development/cmake.rst, doc/source/development/index.rst
Fixes #5875
Credits to PROJ's equivalent page for providing the skeleton.
=> Doc: document how to use GDAL with CMake configuration file

gcore/rasterio.cpp, gcore/rasterio_ssse3.cpp, gcore/rasterio_ssse3.h
The issue was due to an inconsistent declaration of the
GDALUnrolledCopy_GByte_3_1_SSSE3() method in rasterio.cpp and
rasterio_ssse3.cpp (GInt64 vs GPtrDiff_t, which are of different size on
x32)
=> Fix build related to rasterio_ssse3 on x32 architecture (fixes #5917)

autotest/postinstall/test_pkg-config.sh, cmake/helpers/GdalVersion.cmake, gdal.cmake
Autotools creates DLL with a version suffix. This PR makes also cmake add a version suffix to the DLL.
=> Add version suffix to DLL when compiling for MinGW target

doc/source/development/rfc/index.rst, doc/source/development/rfc/rfc86_column_oriented_api.rst
This RFC describes the addition of new methods to the `OGRLayer` class to retrieve batches of features with a column-oriented memory layout, that suits formats that have that organization or downstream consumers that expect data to be presented
in such a way, in particular the [Apache Arrow](https://arrow.apache.org/docs/), [Pandas](https://pandas.pydata.org/) / [GeoPandas](https://geopandas.org/) ecosystem, R spatial packages, and many modern (data analytics focused) databases / engines which are column oriented (eg Snowflake, Google BigQuery, ..)
(Semi-)rendered version of the RFC at: https://github.com/rouault/gdal/blob/rfc_86/doc/source/development/rfc/rfc86_column_oriented_api.rst
=> Add RFC 86: Column-oriented read API for vector layers

frmts/mrf/mrf_band.cpp
Fix a bug in MRF, where deflate was disabled by mistake on builds without ZSTD
* OS:
* Compiler:
=> MRF: When zstd is missing disable zstd, not deflate

cmake/helpers/CheckDependentLibraries.cmake
Compile checks do not need `-Werror` - I hope
Situation here: `CXXFLAGS` contain some extra parameters (`-lunwind -Wl,--exclude-libs=libunwind.a`) which make clang throw an "unused parameter" warning which in turn make this check fail which in turn erroneously lead to `ICONV_CPP_CONST` being set which in turn leads in a compile time failure which is tricky to track down.
Is there a reason for `-Werror` here? I hope CI or @rouault can tell so we can come up with a more targeted check.
=> Be less sensitive on warnings at configure time

autotest/ogr/ogr_openfilegdb_write.py, ogr/ogrsf_frmts/filegdb/FGdbLayer.cpp, ogr/ogrsf_frmts/openfilegdb/ogropenfilegdblayer.cpp, ogr/ogrsf_frmts/openfilegdb/ogropenfilegdblayer_write.cpp
=> OpenFileGDB write: fix issues related to rollback and default field width of string fields

port/cpl_error.h
Variadic functions can't be called with `__stdcall` calling convention on Windows. See also this blog post by Raymond Chen:
https://devblogs.microsoft.com/oldnewthing/20040108-00/?p=41163
I'm not sure what compilers are actually doing when variadic functions are decorated with `__stdcall`. I'd guess they fall back to `__cdecl`. GCC seems to do that silently. But clang emits a lot of warnings during compilation. E.g.:
```
[569/1221] Building CXX object frmts/netcdf/CMakeFiles/gdal_netCDF.dir/netcdflayersg.cpp.obj
In file included from C:/_/mingw-w64-gdal/src/gdal-3.5.0/frmts/netcdf/netcdflayersg.cpp:29:
In file included from C:/_/mingw-w64-gdal/src/gdal-3.5.0/frmts/netcdf/netcdfdataset.h:44:
In file included from C:/_/mingw-w64-gdal/src/gdal-3.5.0/port/cpl_string.h:35: …
```
=> CPLDebug: Variadic functions can't use __stdcall calling convention.

cmake/template/cpl_config.h.in
Fixes a regression from b90f823be80d6447aec23d15525fdfc8fb5310cf
Before that change, `CPL_STDCALL` was set to `__stdcall` only for MSVC compilers (not MinGW). After that change, it is always set on Windows (MSVC or MinGW doesn't matter).
This proposed change reverts to not using `__stdcall` for MinGW. Instead, the interface would use `__cdecl` again which was used before and is the preferred calling convention for MinGW.
=> cpl_config.h: Don't use __stdcall on MinGW 

port/cpl_error.h
Backport #5962
**Authored by:** @mmuetzel
=> [Backport release/3.5] CPLDebug: Variadic functions can't use __stdcall calling convention.

autotest/ogr/ogr_geos.py, ogr/ogrgeometry.cpp
The fix in GEOS 3.11 was likely https://github.com/libgeos/geos/commit/ba190d9016f94f92c7e152cb723dc683fd416a04
=> OGRGeometry::UnionCascaded(): avoid crash with GEOS < 3.11 on empty multipolygon input

frmts/gtiff/geotiff.cpp, frmts/gtiff/libtiff/tif_webp.c
=> [Backport release/3.5] GTiff driver: WEBP: avoid unnecessary temporary buffer creation and copy

autotest/ogr/ogr_geos.py, ogr/ogrgeometry.cpp
=> [Backport release/3.5] OGRGeometry::UnionCascaded(): avoid crash with GEOS < 3.11 on empty multipolygon input

gdal.cmake
Allows for specifying an alternative linker to use instead of
the system default (Eg "gold", "lld", "bfd" or "mold"), for the
build time performance benefits these alternative linkers can offer
Strongly inspired from https://github.com/qgis/QGIS/pull/49067
Credits to @nyalldawson
=> CMake: add a USE_ALTERNATE_LINKER option

data/s57objectclasses.csv
Fix for a missing semicolon in the attribute list for "Small Bottom Object". 
Also adds a missing colon to the two description rows so that the CSV validates.
Issue #6000.
=> Fix missing punctuation in s57objectclasses.csv (fixes #6000)

data/s57objectclasses.csv
Backport #6001
**Authored by:** @audun
=> [Backport release/3.5] Fix missing punctuation in s57objectclasses.csv (fixes #6000)

autotest/osr/osr_basic.py, ogr/ogrspatialreference.cpp
…where the 'vertical CRS' is actually the geographic CRS, to mean ellipsoidal height, which is supported in recent PROJ versions
=> OGRSpatialReference::SetFromUserInput(): allow using strings like EPSG:3157+4617 

autotest/gcore/tiff_write.py, frmts/gtiff/geotiff.cpp
The culprit was that metadata writing calls GetUnitType() which calls
LookForProjection(), which resets the m_bGeoTIFFInfoChanged flag.
Reseting that flag was apparently needed in the past, but is apparently
no longer needed nowadays (there are other resets of it during file opening or
createcopy), at least this doesn't break existing regression tests.
=> GTiff: avoid SetMetadata() to cancel effect of SetGeoTransform() (fixes #6015)

autotest/gcore/tiff_write.py, frmts/gtiff/geotiff.cpp
=> [Backport release/3.5] GTiff: avoid SetMetadata() to cancel effect of SetGeoTransform() (fixes #6015)

alg/gdaltransformer.cpp
Since the origins (2b323d0e164864662dcb3abccf236a20bf391290), the identity
geotransform was considered as not being valid. This was presumably
because at that time some drivers might have returned
GetGeoTransform(...) == CE_None with an identity matrix, whereas there
was none set. There might be some esoteric drivers that still behave
like that, but that should be marginal, and they should rather be fixed.
=> gdalwarp/GDALCreateGenImgProjTransformer2: support identity source geotransform as a valid one (fixes #5954)

autotest/gdrivers/netcdf.py, frmts/netcdf/netcdfdataset.cpp
=> [Backport release/3.5] netCDF: avoid error in SetMetadataItem() when computing statistics (3.5.0 regression, fixes #6023)

doc/source/build_hints.rst, ogr/ogrsf_frmts/CMakeLists.txt
=> [Backport release/3.5] CMake: fix build with GDAL_BUILD_OPTIONAL_DRIVERS:BOOL=OFF (fixes #6031)

alg/gdaltransformer.cpp
=> [Backport release/3.5] gdalwarp/GDALCreateGenImgProjTransformer2: support identity source geotransform as a valid one (fixes #5954)

gcore/gdalrasterband.cpp
Support for 64 bit images was recently added, but the GetHistogram function did not yet support them. The switch statements for handling pixel data types requires cases for Int64 and UInt64. Without them, the histogram was always just zeros.
=> gcore/gdalrasterband.cpp: Support 64 bit images in Band.GetHistogram()

gcore/gdalrasterband.cpp
Backport #6059
**Authored by:** @neilflood
=> [Backport release/3.5] gcore/gdalrasterband.cpp: Support 64 bit images in Band.GetHistogram()

autotest/gcore/vsis3.py, doc/source/user/virtual_file_systems.rst, port/cpl_aws.cpp, port/cpl_aws.h
This PR provide credentials mechanism for web identity token on AWS EKS, see https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html.
On AWS EKS it is possible to setup service account so they are "linked" to an IAM role. AWS EKS change the configuration of the pod using the service account so they mount a specific secret containing a JWT token linked to the arn of the IAM role
From that token it is possible to get temporary credentials calling the AssumeRoleWithWebIdentity action from sts AWS service
* OS:
* Compiler:
=> vsis3: Provide credentials mechanism for web identity token on AWS EKS (fixes #4058)

autotest/osr/osr_ct_proj.py, ogr/ogrct.cpp
Current behavior:
```
>>> from osgeo import osr, gdal
>>> src = osr.SpatialReference()
>>> src.SetAxisMappingStrategy(osr.OAMS_AUTHORITY_COMPLIANT)
>>> assert src.ImportFromEPSG(6931) == 0
>>> dst = osr.SpatialReference()
>>> dst.SetAxisMappingStrategy(osr.OAMS_AUTHORITY_COMPLIANT)
>>> assert dst.ImportFromEPSG(4326) == 0
>>> ctr = osr.CoordinateTransformation(src, dst)
>>> ctr.TransformBounds(
...         458872.4197335826, -2998046.478919534, 584059.8115540259, -2883810.102037343, 21
...     )
ERROR 1: Point outside of projection domain
(62.36651782187522, 8.701995124479733, 63.605850064663514, 11.449280848814887)
>>> gdal.GetLastErrorMsg()
'Point outside of projection domain'
```
- https://github.com/rasterio/rasterio/pull/2526#issuecomment-1186044742
=> BUG: Improve TransformBounds error handling

ogr/ogrspatialreference.cpp
=> [Backport release/3.5] OGRSpatialReference: evaluate OSR_DEFAULT_AXIS_MAPPING_STRATEGY config option at each object construction (fixes #6084)

autotest/utilities/test_gdal_viewshed.py, swig/include/Operations.i, swig/python/extensions/gdal_wrap.cpp, swig/python/osgeo/gdal.py
=> [Backport release/3.5] SWIG bindings: fix wrong typemaps for char** arguments of gdal.ViewshedGenerate (fixes #6086)

ogr/ogrsf_frmts/arrow/ogr_feather.h, ogr/ogrsf_frmts/arrow/ogrfeatherdataset.cpp, ogr/ogrsf_frmts/cad/ogr_cad.h, ogr/ogrsf_frmts/cad/ogrcadlayer.cpp, ogr/ogrsf_frmts/dwg/ogrdwgdriver.cpp, ogr/ogrsf_frmts/filegdb/FGdbDatasource.cpp, ogr/ogrsf_frmts/filegdb/FGdbLayer.cpp, ogr/ogrsf_frmts/geoconcept/ogrgeoconceptdriver.cpp, ogr/ogrsf_frmts/mem/ogrmemdriver.cpp, ogr/ogrsf_frmts/mssqlspatial/ogrmssqlspatialdriver.cpp, ogr/ogrsf_frmts/mvt/ogrmvtdataset.cpp, ogr/ogrsf_frmts/ods/ogrodsdatasource.cpp, ogr/ogrsf_frmts/openfilegdb/ogropenfilegdbdatasource.cpp, ogr/ogrsf_frmts/parquet/ogr_parquet.h, ogr/ogrsf_frmts/parquet/ogrparquetdataset.cpp, ogr/ogrsf_frmts/pgeo/ogrpgeodatasource.cpp, ogr/ogrsf_frmts/pgeo/ogrpgeolayer.cpp, ogr/ogrsf_frmts/vdv/ogr_vdv.h, ogr/ogrsf_frmts/vdv/ogrvdvdatasource.cpp, ogr/ogrsf_frmts/vrt/ogrvrtdatasource.cpp, ogr/ogrsf_frmts/xlsx/ogrxlsxdatasource.cpp
Backports metadata fixes from https://github.com/OSGeo/gdal/pull/6089 to 3.5
=> Backport metadata fixes

autotest/gdrivers/envi.py, frmts/raw/envidataset.cpp
=> [Backport release/3.5] ENVI: fix duplicated 'coordinate system string' when editing an existing file (fixes #6130)

doc/source/drivers/vector/parquet.rst, ogr/ogrsf_frmts/parquet/ogrparquetdriver.cpp
In [docs](https://gdal.org/drivers/vector/parquet.html#layer-creation-options): adds UNCOMPRESSED, removes BZ2 and substitutes LZ4 with LZ4_RAW.
In OGRParquetDriver: removes BZ2 and LZ4_FRAME and substitutes LZ4 with LZ4_RAW. Would be OK to also remove the LZO method (it is not supported by the C++ implementation)?
See:
https://github.com/apache/parquet-format/blob/master/Compression.md
https://github.com/apache/arrow/blob/02c8598d264c839a5b5cf3109bfd406f3b8a6ba5/cpp/src/arrow/util/compression.cc#L48-L78
https://github.com/apache/arrow/blob/02c8598d264c839a5b5cf3109bfd406f3b8a6ba5/cpp/src/parquet/types.cc#L38-L51
https://github.com/apache/arrow/blob/02c8598d264c839a5b5cf3109bfd406f3b8a6ba5/cpp/src/parquet/types.cc#L57-L70
https://github.com/OSGeo/gdal/issues/6115#issuecomment-1200104043
=> Parquet driver: fix compression methods

frmts/sigdem/sigdemdataset.cpp
Backport #6180
**Authored by:** @SeTSeR
=> [Backport release/3.5] fmts/sigdem: Add missing header

autotest/osr/osr_ct.py, swig/include/osr.i, swig/python/extensions/osr_wrap.cpp, swig/python/osgeo/osr.py
Fixes https://lists.osgeo.org/pipermail/gdal-dev/2022-August/056132.html
=> SWIG: add inverseCT optional parameter to CoordinateOperation.SetOperation(), and add CoordinateOperation.GetInverse()

fuzzers/CMakeLists.txt
Fixes a minor typo in fuzzer/CMakeLists.txt
None
=> CMake: fix CMAKE_CROSSCOMPILING typo in fuzzer CMakeLists.txt

fuzzers/CMakeLists.txt
Backport #6201
**Authored by:** @ryanking13
=> [Backport release/3.5] CMake: fix CMAKE_CROSSCOMPILING typo in fuzzer CMakeLists.txt

doc/source/drivers/raster/gtiff.rst
The GTiff driver page doesn't do a great job of telling folks *why* they might choose one TIFF codec over another. Now that there are so many to choose from, we should editorialize a little bit to point people in the right direction.
=> Codec background in GTiff driver page

cmake/modules/packages/FindECW.cmake
=> [Backport release/3.5] CMake: fix static linking of ECW SDK 5.5 on Windows (fixes #6190)

autotest/pyscripts/test_gdal2tiles.py, swig/python/gdal-utils/osgeo_utils/gdal2tiles.py
=> [Backport 3.5] gdal2tiles: allow oversampling in -p raster mode (fixes #6207)

swig/python/gdal-utils/osgeo_utils/gdal_calc.py
Fixes a small typo (misspelling of "geotransforms") in the `gdal_calc.py` `--help` information for the flag `--extents`.
---
I was getting ready to use this functionality and noticed this typo. Apologies for opening up such a minor PR but I figured it couldn't hurt. Feel free to close this and incorporate the change in a bigger commit if desired. Big thanks to all the maintainers for keeping the amazing tool that is GDAL up and running!
=> Typo-Fix: gdal_calc.py --extent flag description

cmake/modules/packages/FindKDU.cmake, frmts/jp2kak/CMakeLists.txt
Fixes building against the Kakadu driver for ARM CPUs on Linux and OSX. Tested on Linux aarch64 and x64. 
Unfortunately I don't have access to an Apple M1 to check the OSX changes with.
None
=> JP2KAK: add support for ARM builds

alg/gdal_rpc.cpp, autotest/gcore/tiff_read.py, autotest/gcore/tiff_write.py, autotest/gcore/vrt_read.py, frmts/vrt/vrtsources.cpp
Before this commit, we would query small windows, of growing radius when
querying in the same area, at 'random' locations. When transforming
several points with the same transformer object, there was no guarantee
that the same input coordinates would result in reading the DEM in the
same window. For 'normal' rasters, this didn't make any difference, but
when requesting a VRT with non-integer src/dst offsets or scaling, there
is no guarantee that extracting values from those windows results in
consistent values being returned (can be seen as a bug of the VRT
driver, but it is extraordinary complicated, if not impossible, to offer
such stability property with it).
Consequently let's query the DEM by non-overlapping fixed-size blocks,
which eliminates that issue.
=> RPC DEM extraction: use a block base approach to query the DEM

cmake/modules/packages/FindKDU.cmake, frmts/jp2kak/CMakeLists.txt
Backports https://github.com/OSGeo/gdal/pull/6222 to the `release/3.5` branch
https://github.com/OSGeo/gdal/pull/6222
=> JP2KAK: Backport 6222 to release/3.5

cmake/helpers/configure.cmake, cmake/template/cpl_config.h.in, gdal.cmake
This PR makes the CMake build system propagate `CPL_DISABLE_DLL` via `cpl_config.h`, as used to be done with `nmake`  AFAIU. The original implementation with `target_compile_definitions` seems to not propagate to compiling the individual units, probably due to the use of object libraries. This fixes:
- `DllMain` appearing in the static lib,
- `__declspec(dllexport)` being applied which building the static lib.
Cf. https://github.com/microsoft/vcpkg/issues/26362#issuecomment-1221256210, https://github.com/microsoft/vcpkg/pull/26457
Side notes: 
- I wonder if some of the `MSVC` condition should be changed in `WIN32` conditions (in CMake and in the source files), to increase consistency between MSVC and MinGW builds.
- There could be more cleanup around nmake-ish `cpl_config.h.vc*`, but this …
=> Fix propagation of CPL_DISABLE_DLL

frmts/msgn/msg_basic_types.cpp, frmts/msgn/msg_basic_types.h, frmts/msgn/msg_reader_core.cpp, frmts/msgn/msg_reader_core.h, frmts/msgn/msgndataset.cpp
Should now handle vis/NIR and HRV for each of MSG4, MSG3(RSS) and MSG2(IODC) with reasonable accuracy in reprojection.
Related to #5866
=> [Backport 3.5] MSGN: fix georeferencing (#6244)

autotest/gcore/vsicurl.py, doc/source/user/virtual_file_systems.rst, port/cpl_http.cpp
This is an alternative to GDAL_HTTP_HEADER_FILE, but easier to
use for less technical end users, since it allows to specify the headers
inline, without requiring an extra file.
=> /vsicurl / CPLHTTPFetch(): add GDAL_HTTP_HEADERS configuration option

swig/python/gdal-utils/osgeo_utils/gdal2tiles.py
Update OpenLayers to Version 7. The current version is not available from the CDN anymore
=> gdal2tiles: fix OpenLayers CDN

autotest/ogr/ogr_hana.py, ogr/ogrsf_frmts/hana/ogr_hana.h, ogr/ogrsf_frmts/hana/ogrhanadatasource.cpp, ogr/ogrsf_frmts/hana/ogrhanatablelayer.cpp, ogr/ogrsf_frmts/hana/ogrhanautils.cpp, ogr/ogrsf_frmts/hana/ogrhanautils.h
This PR fixes the following issues in HANA driver:
- LaunderName function doesn't properly work with non-ASCII characters
- Geometry column name in OGRHanaDataSource::ICreateLayer is not laundered
- OGRHanaTableLayer::CreateField function must use Unicode variant of odbc::Connection::prepareStatement
=> HANA: LaunderName returns wrong value for non-ASCII characters

.github/workflows/doc_build.yml
restore behavior added in 2e3f6126c41fdc19a70d9ccbefbe3e75d29430f that was lost in azure pipelines to gha migration
=> gdal.org doc build: copy resources/ directory for gdal2tiles need

port/cpl_odbc.cpp
As per ODBC documentation of the [SQLGetData](https://docs.microsoft.com/en-us/sql/odbc/reference/develop-app/getting-long-data?view=sql-server-ver16) function, there are 2 possible scenario when reading large columns data (e.g WKT);
1. some drivers will return the remaining bytes to be read in `cbDataLen` while
2. some drivers will return  `SQL_NO_TOTAL` in `cbDataLen`
The current code was not addressing the second use case. This PR address it.
#6196 
- [use case for `SQL_NO_TOTAL`] Given an ODBC connection for the [Kinetica database](https://docs.kinetica.com/7.1/connectors/sql_guide/#odbc)
- Given a table pre-loaded with WKT
- When running `ogrinfo` it should not fail
```
ogrinfo --debug ON -so -al 'ODBC:user/password@kinetica-odbc-connection,prism.operator_acreage_view(WKT)'
```
- …
=> ODBC: fix issue with odbc large data (fixes #6196)

apps/gdalinfo_lib.cpp, autotest/utilities/test_gdalinfo.py, doc/source/programs/gdalinfo.rst
`gdalinfo -json` output now includes a "stac" key, which is a dictionary of commonly-used STAC extension data.
STAC extensions supported:
- projection: https://github.com/stac-extensions/projection
- raster: https://github.com/stac-extensions/raster
- eo: https://github.com/stac-extensions/eo (only description)
All of the STAC fields are duplicated from other data already included in the JSON output. At some point in the future, it may make sense to output STAC Items from `-json` by default or provide a `-stac` flag; however, that would be a more significant change and would require some additional decisions (e.g. how to handle item ids, asset structure, etc).
No changes are made to the existing keys in the JSON output, so this should not affect existing usage.
EDIT: example output …
=> gdalinfo: add a STAC section to `gdalinfo -json` output

doc/source/download.rst
Gdal is available as a port in [vcpkg](https://github.com/microsoft/vcpkg), a C++ library manager that simplifies installation for gdal and other project dependencies. Documenting the install process here will help users get started by providing a single set of commands to build gdal, ready to be included in their projects.
We also test whether our library ports build in various configurations (dynamic, static) on various platforms (OSX, Linux, Windows: x86, x64, UWP, ARM) to keep a wide coverage for users.
I'm a maintainer for vcpkg, and [here](https://github.com/microsoft/vcpkg/blob/master/ports/gdal/portfile.cmake) is what the port script looks like. We try to keep the library maintained as close as possible to the original library.
=> Add vcpkg installation instructions

apps/gdalinfo_lib.cpp, autotest/utilities/test_gdalinfo.py
We auto-populate the band name and description so we don't have empty eo:bands (empty are invalid [per the extension](https://github.com/stac-extensions/eo#band-object)).
```shell
$  gdalinfo -json autotest/gcore/data/md_dg.tif | jq  '.stac."eo:bands"'   
[
{
"name": "b1",
"description": "Red"
},
{
"name": "b2",
"description": "Green"
},
{
"name": "b3",
"description": "Blue"
}
]
```
https://github.com/OSGeo/gdal/pull/6265#issuecomment-1235671013
=> gdalinfo -json: fix eo:bands in stac output

apps/gdal_translate_bin.cpp, apps/gdal_translate_lib.cpp, autotest/utilities/test_gdal_translate_lib.py, doc/source/programs/gdal_translate.rst, gcore/gdaloverviewdataset.cpp, swig/include/python/gdal_python.i, swig/python/osgeo/gdal.py
To specify which overview level of source file must be used. The default choice,
AUTO, will select the overview level whose resolution is the closest to the
target resolution. Specify an integer value (0-based, i.e. 0=1st overview level)
to select a particular level. Specify AUTO-n where n is an integer greater or
equal to 1, to select an overview level below the AUTO one. Or specify NONE to
force the base resolution to be used (can be useful if overviews have been
generated with a low quality resampling method, and a higher quality resampling method
is specified with :option:`-r`.
When :option:`-ovr` is specified to an integer value,
and none of :option:`-outsize` and :option:`-tr` is specified, the size of
the overview will be used as the output size.
When :option:`-ovr` is specified, …
=> gdal_translate: add a -ovr <level|AUTO|AUTO-n|NONE> flag (fixes #1923)

autotest/ogr/ogr_hana.py, ogr/ogrsf_frmts/hana/ogrhanadatasource.cpp
For some reason HANA's ODBC driver doesn't report about missing connection parameters.
This PR adds checks for mandatory connection parameters and prints an error if a check is not successful.
=> HANA: inform about missing mandatory connection parameters

apps/nearblack_lib.cpp, autotest/utilities/test_nearblack_lib.py
Before this change, we would systematically erode non_black_pixels from
the top/bottom/left/right edges even when they were valid. Only consider erosion
if those edges pixels are invalid/black.
=> nearblack: skip erosion when pixel at edge is valid

autotest/gdrivers/srp.py, frmts/adrg/srpdataset.cpp
adds the SRP pixelspacing value to the SRP-dataset metadata The value was already read from the data but not used.
none
* OS:
* Compiler:
=> ADRG: add SRP pixel spacing value (SRP_PSP) to the srpdataset metadata

autotest/gdrivers/zarr_driver.py, doc/source/drivers/raster/zarr.rst, frmts/zarr/zarrdriver.cpp
and add more informative error messages for quoting errors and/or lack of /vsicurl/ prefix.
Also improve doc related to /vsicurl/
cf https://lists.osgeo.org/pipermail/gdal-dev/2022-September/056200.html
=> Zarr: do not open non-existant dataset when prefixing with ZARR:, 

autotest/gdrivers/zarr_driver.py, doc/source/drivers/raster/zarr.rst, frmts/zarr/zarrdriver.cpp
=> [Backport release/3.5] Zarr: do not open non-existant dataset when prefixing with ZARR:, 

frmts/pdf/CMakeLists.txt
Workaround https://bugs.launchpad.net/ubuntu/+source/poppler/+bug/1989434 which is an issue with broken security update on Ubuntu 18.04 of poppler 0.62.0-2ubuntu2.13
If we detect that gmem.h includes GooCheckedOps.h but that one is not installed, create a dummy one in a temporary directory To be removed once https://bugs.launchpad.net/ubuntu/+source/poppler/+bug/1989434 is fixed
=> Fix build on Ubuntu 18.04 with PDF driver due to broken Poppler security update

frmts/pdf/CMakeLists.txt
=> [Backport release/3.5] Fix build on Ubuntu 18.04 with PDF driver due to broken Poppler security update

autotest/cpp/test_cpl.cpp, doc/source/user/configoptions.rst, port/cpl_conv.cpp
in a [directives] leading section to disable environment
variables to be used as configuration options (fixes #6280)
=> Configuration file: add a ignore-env-vars=yes setting

.github/workflows/android_cmake/start.sh
(refs https://github.com/OSGeo/gdal/pull/5426#discussion_r975184720)
=> CI android_cmake: use correct cross compiler for SQLite3

.github/workflows/cmake_builds.yml, gdal.cmake, swig/python/CMakeLists.txt
but only if it is an absolute path. GDAL_SET_INSTALL_RELATIVE_RPATH=ON will still have no effect on Python bindings.
=> CMake: honour CMAKE_INSTALL_RPATH for Python bindings (fixes #6371)

autotest/ogr/ogr_ods.py, autotest/ogr/ogr_xlsx.py, ogr/ogrsf_frmts/ods/ogrodsdriver.cpp, ogr/ogrsf_frmts/xlsx/ogrxlsxdriver.cpp
- ODS: make it possible to open file without .ods extension if prefixed with ODS: (refs #6375)
- XLSX: make it possible to open file without .xlsx extension if prefixed with XLSX: (fixes #6375), and improve detection to recognize even if no XLSX: prefix or .xlsx extension
=> ODS/XLSX: accept ODS: / XLSX: prefixes

doc/source/programs/gdal2tiles.rst
`--tmscompatible` has been a valid option for a while and was already described in the `gdal2tiles.py` help section but was not explicitly defined in the online documentation. This simply corrects that oversight.
=> DOC: Adding --tmscompatible option to gdal2tiles.py documentation

autotest/ogr/ogr_gpkg.py, doc/source/drivers/vector/gpkg.rst, ogr/ogrsf_frmts/gpkg/ogrgeopackagedatasource.cpp, ogr/ogrsf_frmts/gpkg/ogrgeopackagedriver.cpp, ogr/ogrsf_frmts/sqlite/ogrsqlitedatasource.cpp
and automatically turn it on (with warning) when not being able to open a WAL file in read-only mode
Fixes https://lists.osgeo.org/pipermail/gdal-dev/2022-September/056217.html
=> GPKG: add a IMMUTABLE=YES/NO open option

doc/source/drivers/vector/csv.rst, ogr/ogrsf_frmts/csv/ogr_csv.h, ogr/ogrsf_frmts/csv/ogrcsvdatasource.cpp, ogr/ogrsf_frmts/csv/ogrcsvdriver.cpp, ogr/ogrsf_frmts/csv/ogrcsvlayer.cpp
=> [Backport release/3.5] CSV: push the maximum size of a line to 10 million by default, and make it configurable with a MAX_LINE_SIZE open option

apps/gdalbuildvrt_lib.cpp, autotest/gcore/vrtmisc.py, frmts/vrt/vrtdataset.h, frmts/vrt/vrtsourcedrasterband.cpp, frmts/vrt/vrtsources.cpp
For 3.5 backport, 2b14a0396608adc2c1696977346426df4cc0302d and first commit of this PR will have to be cherry-picked
=> VRT serialization: do not (generally) open source band when serialization of a ComplexSource with NODATA (fixes qgis/QGIS#48052)

.github/workflows/doc_build.yml
Cf https://github.com/sphinx-doc/sphinx/issues/10865
=> CI: avoid installing sphinx 5.2.0 that causes a doc build issue

ogr/ogrsf_frmts/cad/libopencad/cadgeometry.h, ogr/ogrsf_frmts/cad/libopencad/dwg/r2000.cpp
(fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=51826)
=> libopencad: avoid casting an invalid value as ResolutionUnit

autotest/gcore/tiff_write.py, autotest/gdrivers/jpegxl.py, frmts/gtiff/tif_jxl.c, frmts/jpegxl/jpegxl.cpp
(e.g. R,G,B,undefined,Alpha)
+ JXL-in-TIFF: check on reading consistency between JXL extra channel info and ExtraSamples TIFF tag
=> JPEGXL & JXL-in-TIFF: preserve Alpha color interpretation when the Alpha band does not immediately follow color bands

ogr/ogrsf_frmts/cad/libopencad/cadgeometry.h, ogr/ogrsf_frmts/cad/libopencad/dwg/r2000.cpp
=> [Backport release/3.5] libopencad: avoid casting an invalid value as ResolutionUnit

swig/python/CMakeLists.txt
When I try to compile gdal on ubuntu 18.04, I get an error saying that `EXTENSION_SUFFIXES` doesn't exist. If I change `setuptools.command.build_ext` to` importlib.machinery` it does work correctly, and I was able to compile gdal.
I tested it on the official ubuntu 18.04 docker, with compiling the source code of gdal 3.5.2.
=> fix the swig-python cmake file in order to compile on ubuntu 18.04

swig/python/CMakeLists.txt
Backport #6443
**Authored by:** @idanaviv10
=> [Backport release/3.5] fix the swig-python cmake file in order to compile on ubuntu 18.04

doc/source/drivers/raster/zarr.rst
`ZSTD_LEVEL` defaults to 13, which is outside of the 1-9 range. I'm not sure if we accept 1-19 or 1-22 here, but GTif uses 1-19 and I can't find the code where this is actually used.
=> Zarr: fix `ZSTD_LEVEL` range in Zarr docs

autotest/gcore/tiff_write.py, autotest/gdrivers/jpegxl.py, autotest/gdrivers/webp.py, frmts/gtiff/geotiff.cpp, frmts/jpegxl/jpegxl.cpp, frmts/webp/webpdataset.cpp
- WEBP: report a COMPRESSION_REVERSIBILITY=LOSSLESS/LOSSY metadata item in IMAGE_STRUCTURE
- JPEGXL: report a COMPRESSION_REVERSIBILITY=LOSSLESS (possibly)/LOSSY metadata item in IMAGE_STRUCTURE
- GTiff: report a COMPRESSION_REVERSIBILITY=LOSSLESS (possibly)/LOSSY metadata item in IMAGE_STRUCTURE for WEBP and JXL compression
* Requires reading the header of one tile/strip and the availability of the standalone WEBP and JPEGXL drivers.
* Use that information to set the m_bWebPLossless/m_bJxlLossless flags in update mode
- GTiff: read/write JPEGXL and WEBP compression parameters (for main dataset only) in IMAGE_STRUCTURE metadata domain of GDAL_METADATA tag
=> WEBP/JPEGXL/GTiff: add COMPRESSION_REVERSIBILITY item in IMAGE_STRUCTURE metadata domain

autotest/gdrivers/jp2openjpeg.py, autotest/gdrivers/nitf.py, frmts/ecw/ecwdataset.cpp, frmts/nitf/nitfdataset.cpp, frmts/nitf/nitfdataset.h, frmts/openjpeg/openjpegdataset.cpp, gcore/gdaljp2abstractdataset.cpp, gcore/gdaljp2abstractdataset.h, gcore/gdaljp2box.cpp, gcore/gdaljp2metadata.h, gcore/gdaljp2structure.cpp
- JPEG2000 drivers: report a COMPRESSION_REVERSIBILITY=LOSSLESS/LOSSLESS (possibly)/LOSSY metadata item in IMAGE_STRUCTURE domain
- JP2OpenJPEG: for reversible compression, write a hint in the COM marker if the compression is lossy or not, and use it on reading
- NITF: report COMPRESSION_REVERSIBILITY for JPEG2000 compressed images
=> JPEG2000 drivers: report compression reversibility

ogr/ogrsf_frmts/gpkg/ogrgeopackagedatasource.cpp
Fix the values of the `min` `max` `mean` `std_dev` columns of the `gpkg_2d_gridded_tile_ancillary` table
When creating overlays for a GeoPackage containing raster tiles that have a nodata of e.g. -9999
The values of min max mean will be calculated without ignoring the nodata entries.
Reason:
In the `GDALGeoPackageDataset::CreateCopy` implementation `poDS->SetGeoTransform(adfGeoTransform);` is called before the nodata values are taken over.
`SetGeoTransform` calls `GDALGeoPackageDataset::FinalizeRasterRegistration` which in turn calls `poOvrDS->InitRaster` for each zoom level.
This is currently done before the nodata has been assigned to the parent dataset so when the overview tiles are created in `GDALGPKGMBTilesLikePseudoDataset::WriteTileInternal` `bHasNoData` will be false and de …
=> GPKG: raster overlays: Fix min max mean std_dev values when creating overviews

autotest/cpp/test_cpl.cpp, autotest/gcore/vsipathspecificoption.py, autotest/gcore/vsis3.py, doc/source/user/configoptions.rst, doc/source/user/virtual_file_systems.rst, gcore/gdalopeninfo.cpp, port/cpl_alibaba_oss.cpp, port/cpl_aws.cpp, port/cpl_azure.cpp, port/cpl_conv.cpp, port/cpl_google_cloud.cpp, port/cpl_swift.cpp, port/cpl_vsi.h, port/cpl_vsil.cpp, port/cpl_vsil_curl.cpp, port/cpl_vsil_s3.cpp, port/cpl_vsil_webhdfs.cpp, swig/include/cpl.i, swig/python/extensions/gdal_wrap.cpp, swig/python/osgeo/gdal.py
- Add VSISetPathSpecificOption() / VSIGetPathSpecificOption() / VSIClearPathSpecificOptions()
Those are just better named functions of the VSISetCredential() /
VSIGetCredential() / VSIClearCredentials() introduced in GDAL 3.5, which
are kept for backward compatibility, but deprecated.
- /vsis3/: make CPL_VSIS3_USE_BASE_RMDIR_RECURSIVE a path-specific configuration option
- Make GDAL_DISABLE_READDIR_ON_OPEN a path-specific configuration option
=> Make CPL_VSIS3_USE_BASE_RMDIR_RECURSIVE and GDAL_DISABLE_READDIR_ON_OPEN path-specific options

doc/source/programs/vector_common_options.rst
Just a tiny typo fix in the docs. Trivial enough to do no testing or compiling or anything like that :)
=> Typo fix "messege" -> "message"

doc/source/drivers/raster/cog.rst, doc/source/drivers/raster/gtiff.rst
Hi! This tripped me up in some software that doesn't pass gdal warnings / errors. So I wondered why I got no output and apparently the reason was an incorrectly set block size. This hint aims to inform users about the need that the blocksize must be divisible by 16.
=> Docs (GTiff & COG): blocksize must be divisible by 16

doc/source/drivers/raster/stacit.rst
The STAC specification has several collection-like specifications - these changes fix links to point the correct STAC Search documents and clarify that the catalog-type regular STAC Collections are not supported. Some other minor clarifications were added.
None - updates docs only
=> Clarify STAC support in STACIT driver documentation

port/cpl_odbc.cpp, port/cpl_odbc.h
Not private, so it's possible to create useful derived classes.
=> Make CPLODBCSession and CPLODBCStatement member variables 'protected' (fixes #6314)

autotest/ogr/ogr_gpkg.py, ogr/ogrsf_frmts/gpkg/ogr_geopackage.h, ogr/ogrsf_frmts/gpkg/ogrgeopackagetablelayer.cpp
This PR implements the Upsert feature operation in the OGR Geopackage driver (ie. if record does not exist then Create, else Set).
For context, the OGR Upsert operation was added here https://github.com/OSGeo/gdal/pull/6199
=> Geopackage: Add upsert operation support

alg/gdalwarper.cpp, alg/gdalwarpkernel.cpp, alg/gdalwarpoperation.cpp, autotest/cpp/test_cpl.cpp, port/cpl_mask.h
This PR attempts to some parts of the warp code easier to read by adding functions to manipulate bit masks stored in a GUInt32*. I thought of putting this in a custom type but it seemed better to be less invasive, avoid changing signatures, and stick with GUInt32*.
None
=> Add CPLMask functions to simplify bitmask handling

autotest/ogr/ogr_sqlite.py, ogr/ogrsf_frmts/sqlite/ogr_sqlite.h, ogr/ogrsf_frmts/sqlite/ogrsqlitedatasource.cpp, ogr/ogrsf_frmts/sqlite/ogrsqlitetablelayer.cpp
=> [Backport release/3.5] SQLite: allow creating layers named like 'foo(bar)' (fixes #6548)

port/cpl_http.cpp
Fixes https://lists.osgeo.org/pipermail/gdal-dev/2022-October/056330.html
Cf https://github.com/curl/curl/pull/3148 and https://github.com/curl/curl/issues/9024
=> CPLHTTPFetch(): ignore SSL/TLS errors about non-properly terminated connections

autotest/ogr/ogr_gpkg.py, doc/source/development/rfc/rfc86_column_oriented_api.rst, ogr/ogrsf_frmts/gpkg/ogrgeopackagelayer.cpp, swig/include/ogr.i, swig/include/python/ogr_python.i, swig/python/extensions/ogr_wrap.cpp, swig/python/osgeo/ogr.py
If GetLayerDefn() wasn't called directly or indirectly, only the FID and
geometry columns were fetched. This was the reason for the odd results
in the RFC 86 benchmarks.
=> GPKG: fix issue when GetNextArrowArray() is called before GetArrowSchema(), and improve Python bindings

ogr/ogrsf_frmts/gpkg/ogr_geopackage.h, ogr/ogrsf_frmts/gpkg/ogrgeopackagelayer.cpp, ogr/ogrsf_frmts/gpkg/ogrgeopackagetablelayer.cpp
Ignored fields were ignored in GetNextFeature(), but they were still requested to SQLite, which is not efficient at all.
=> GPKG: perf improvement: do not request ignored fields

port/cpl_http.cpp
=> [Backport release/3.5] CPLHTTPFetch(): ignore SSL/TLS errors about non-properly terminated connections

frmts/nitf/nitfimage.c
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=52642
=> NITF: avoid excessive memory allocation on broken files

autotest/ogr/ogr_basic_test.py, autotest/ogr/ogr_gpkg.py, autotest/ogr/ogr_pg.py, ogr/ogr_api.h, ogr/ogrsf_frmts/generic/ogrlayer.cpp, ogr/ogrsf_frmts/gpkg/ogr_geopackage.h, ogr/ogrsf_frmts/gpkg/ogrgeopackagedatasource.cpp, ogr/ogrsf_frmts/gpkg/ogrgeopackagetablelayer.cpp, ogr/ogrsf_frmts/ogrsf_frmts.h, ogr/ogrsf_frmts/pg/CMakeLists.txt, ogr/ogrsf_frmts/pg/ogr_pg.h, ogr/ogrsf_frmts/pg/ogrpgtablelayer.cpp, swig/include/ogr.i, swig/include/python/callback.i, swig/include/python/docs/ogr_layer_docs.i, swig/include/python/typemaps_python.i, swig/python/extensions/gdal_array_wrap.cpp, swig/python/extensions/gdal_wrap.cpp, swig/python/extensions/gnm_wrap.cpp, swig/python/extensions/ogr_wrap.cpp, swig/python/osgeo/ogr.py
This method iterates over features to retrieve their geometry types. This
is mostly useful for layers that report a wkbUnknown geometry type.
By default this method returns an array of nEntryCount entries with each
geometry type (in OGRGeometryTypeCounter::eGeomType) and the corresponding
number of features (in OGRGeometryTypeCounter::nCount).
Features without geometries are reported as eGeomType == wkbNone.
Optimized implementations for GPKG and PostgreSQL
=> Add OGRLayer::GetGeometryTypes() 

autotest/cpp/test_cpl.cpp, autotest/ogr/ogr_gpkg.py, ogr/ogrsf_frmts/gpkg/ogr_geopackage.h, ogr/ogrsf_frmts/gpkg/ogrgeopackagetablelayer.cpp, ogr/ogrsf_frmts/sqlite/ogrsqlitebase.h, ogr/ogrsf_frmts/sqlite/ogrsqlitevfs.cpp, port/cpl_threadsafe_queue.hpp
We create a temporary database with only the RTree, and we insert records into it in a dedicated thread, in parallel of the main thread that inserts rows in the user table. When the layer is finalized, we just use bulk copy statements of the form
INSERT INTO rtree_xxxx_rowid/node/parent SELECT * FROM temp_rtree.my_rtree_rowid/node/parent
to copy the RTree auxiliary tables into the main database, which is a very fast operation.
With that, "ogr2ogr out.gpkg nz-building-outlines.parquet" goes from 62 seconds down to 40 seconds (35% faster)
with the dataset at https://storage.googleapis.com/open-geodata/linz-examples/nz-building-outlines.parquet
=> GPKG: speed-up: implement background RTree creation in bulk insertion in a new table

apps/CMakeLists.txt, apps/bench_ogr_batch.cpp, apps/bench_ogr_c_api.cpp, autotest/ogr/ogr_gpkg.py, ogr/ogr_p.h, ogr/ogrsf_frmts/flatgeobuf/ogrflatgeobuflayer.cpp, ogr/ogrsf_frmts/generic/ograrrowarrayhelper.cpp, ogr/ogrsf_frmts/generic/ograrrowarrayhelper.h, ogr/ogrsf_frmts/gpkg/ogr_geopackage.h, ogr/ogrsf_frmts/gpkg/ogrgeopackagelayer.cpp, ogr/ogrsf_frmts/gpkg/ogrgeopackagetablelayer.cpp, ogr/ogrutils.cpp, swig/include/python/ogr_python.i, swig/python/osgeo/ogr.py
With those improvements, the timing of [bench_ogr_batch](https://github.com/OSGeo/gdal/blob/3f5cd1cc33685a627ee786bccaa0bf312d394ad9/apps/bench_ogr_batch.cpp), which uses ArrowArray batch reading, on GPKG and FlatGeoBuf files converted from https://storage.googleapis.com/open-geodata/linz-examples/nz-building-outlines.parquet goes from:
- FlatGeoBuf: 4.5 s -> 3.2 s
- GPKG: 4.5 s -> 2.2 s (single-threaded) -> 1.5 s (main thread + worker thread)
compared to 1.4 s on the GeoParquet file (whose reading uses threading)
=> FlatGeoBuf and GPKG: improve DateTime parsing perf + GPKG improve GetNextArrowArray() perf

autotest/ogr/ogr_elasticsearch.py, ogr/ogrsf_frmts/elastic/ogr_elastic.h, ogr/ogrsf_frmts/elastic/ogrelasticlayer.cpp
This PR implements the Upsert feature operation in the OGR Elasticsearch driver (ie. if record does not exist then Create, else Set).
For context, the OGR Upsert operation was added here https://github.com/OSGeo/gdal/pull/6199
=> Elasticsearch: Add upsert operation support

autotest/gcore/tiff_ovr.py, frmts/gtiff/geotiff.cpp, frmts/gtiff/gt_overview.cpp, gcore/overview.cpp
A workaround for affected versions is to set the GDAL_OVR_CHUNK_MAX_SIZE configuration option to a large int32 value, like 2100000000.
=> Overview building: fix MODE resampling on large datasets (fixes #6587)

ogr/ogrsf_frmts/hana/ogrhanadatasource.cpp
find_first_of() returns a position or std::string::npos, not a bool.
CC @mrylov
=> HANA: fix invalid use of find_first_of() (CID 1500389) (master only)

ogr/ogrgeometry.cpp
… (ie MultiPoint, MultiLineString, MultiPolygon) as being mergeable as GeometryCollections. Affect GML driver (fixes #6616)
=> OGRMergeGeometryTypesEx(): do not consider different type of MultiGeometries

autotest/gdrivers/data/grib/subgrids.grib2.idx, autotest/gdrivers/grib.py, frmts/grib/gribdataset.cpp
=> [Backport release/3.6] GRIB2: fix crash and invalid metadata when processing index .idx file with sub-messages (fixes #6613)

ogr/ogrgeometry.cpp
=> [Backport release/3.6] OGRMergeGeometryTypesEx(): do not consider different type of MultiGeometries

swig/csharp/CMakeLists.txt
Backport #6621
**Authored by:** @szekerest
=> [Backport release/3.6] CMake: fix Win32 csharp build (#6620)

autotest/ogr/ogr_gpkg.py, ogr/ogrsf_frmts/gpkg/ogr_geopackage.h, ogr/ogrsf_frmts/gpkg/ogrgeopackagedatasource.cpp, swig/python/gdal-utils/osgeo_utils/samples/validate_gpkg.py
=> [Backport release/3.6] GPKG: add compatibility with GPKG 1.0 gpkg_data_column_constraints table

autotest/gcore/basic_test.py, swig/include/python/python_exceptions.i, swig/python/osgeo/gdal.py, swig/python/osgeo/gnm.py, swig/python/osgeo/ogr.py, swig/python/osgeo/osr.py
The Python gdal/ogr/osr/gnm modules each have a global state flag determining whether or not errors raise Exceptions. It defaults to not, and can be set or unset. However, because this is global, conflicts can arise in what a section of code requires, sometimes in code from other libraries. To avoid interfering with other code, one often needs to save current state, set desired state, perform some actions, then reset to saved state. 
This PR adds a Python Context Manager class which handles this process, so that a Python `with` statement can have a desired state within that block, and not interact with the global state. 
It is added to the generic `python_exceptions.i` SWIG code, so it appears in each of the different GDAL modules.
=> swig/python_exceptions.i: Add Context Manager for handling Python exception state

autotest/ogr/ogr_gpkg.py, ogr/ogrsf_frmts/gpkg/ogr_geopackage.h, ogr/ogrsf_frmts/gpkg/ogrgeopackagetablelayer.cpp, ogr/ogrsf_frmts/vdv/ogrvdvdatasource.cpp
- CreateFeature() and SetFeature() ignore the value in the columns
- CreateField()/DeleteField()/ReorderFields() correctly book-keep the generated column status, but not that DeleteField() before SQLite 3.35.5 involves whole table recreation which loses the generated column expression. ReorderFields() also loses the generated column expression due to whole table recreation (for all SQLite versions)
=> GPKG: add support for reading tables with generated columns (fixes #6638)

autotest/gdrivers/gpkg.py, doc/source/drivers/raster/gpkg.rst, ogr/ogrsf_frmts/gpkg/gdalgeopackagerasterband.cpp, ogr/ogrsf_frmts/gpkg/ogr_geopackage.h, ogr/ogrsf_frmts/gpkg/ogrgeopackagedatasource.cpp
This is implemented as a NODATA_VALUE metadata item in GDAL ``<GDALMultiDomainMetadata>`` XML element.
=> GPKG raster: implement setting the nodata value for Byte dataset (fixes #1569)

cmake/helpers/CheckDependentLibraries.cmake
=> [Backport release/3.6] CMake: remove RECOMMENDED flag to BRUNSLI and QB3. Add it for CURL

cmake/helpers/configure.cmake
=> [Backport release/3.6] configure.cmake: fix wrong detection of pread64 for iOS (patch by Nik Sands)

ogr/ogrsf_frmts/gpkg/ogrgeopackagedatasource.cpp, ogr/ogrsf_frmts/gpkg/ogrgeopackagetablelayer.cpp, swig/python/gdal-utils/osgeo_utils/samples/validate_gpkg.py
=> [Backport release/3.6] GPKG: avoid nullptr dereference on corrupted databases

cmake/modules/packages/FindHDF4.cmake
Fixes `Could NOT find HDF4 (missing: HDF4_mfhdf_LIBRARY) (found version "4.2.15")`. The static xdr library is named `libxdr.lib` when building HDF-4.2.15 with CMake on Windows.
=> Fix static HDF4 libraries not found on Windows

cmake/modules/packages/FindHDF4.cmake
Backport #6683
**Authored by:** @cgohlke
=> [Backport release/3.6] Fix static HDF4 libraries not found on Windows

ogr/ogrsf_frmts/gpkg/ogr_geopackage.h, ogr/ogrsf_frmts/gpkg/ogrgeopackagedatasource.cpp
=> [Backport release/3.6] GPKG: fix bad performance of ST_Transform() by caching the OGRCoordinateTransformation object

ogr/ogrsf_frmts/gpkg/ogrgeopackagedatasource.cpp, ogr/ogrsf_frmts/sqlite/ogrsqlitedatasource.cpp
- this simplify a tiny bit the code
- and this allows to issue a 'PRAGMA writable_schema=ON' statement, to be able to read databases with STRICT tables (created with sqlite>=3.37) with earlier sqlite versions.
=> SQLite/GPKG: move PRELUDE_STATEMENTS evaluation just after database opening

alg/gdalwarpoperation.cpp
When I enabled debug logs to track large warp operations, I noticed that the current chunk is printed.  This PR also logs the number of chunks to make it easier to understand how far a warp operation has progressed.
=> Also log number of chunks in warp operation progress debug logs

doc/source/development/rfc/index.rst, doc/source/development/rfc/rfc87_signed_int8.rst
Pre-rendered view of RFC text at https://github.com/rouault/gdal/blob/rfc87/doc/source/development/rfc/rfc87_signed_int8.rst
=> Add RFC 87: Signed int8 data type for raster

swig/python/CMakeLists.txt
=> [Backport release/3.6] Python bindings: add a 'python_generated_files' target that facilitate generation of bindings without building the lib

ogr/ogrsf_frmts/wfs/ogrwfsfilter.cpp
=> [Backport release/3.6] WFS/CSW: do not remove single or double quote character in a LIKE filter

doc/source/drivers/raster/vrt.rst
Simple typo fixes in VRT documentation.
None
* OS:
* Compiler:
=> DOC: fix typos in vrt.rst

frmts/jpeg/libjpeg/jerror.c
on iOS with QT 6.4.1 it looks like there is another symbol clash in bundled jpeg QT lib
=> found another not renamed symbol on iOS

autotest/ogr/ogr_sql_test.py, ogr/swq_op_general.cpp
When comparing integer array fields with integers the code represents the arrays with their string serialized form, comparing with the string representation of the integer value which is null led to the crash.
=> SWQ: fix crash when comparing integer array fields (fixes: #6714)

apps/gdal_translate_lib.cpp, autotest/gcore/tiff_read.py, autotest/gdrivers/netcdf.py, frmts/cals/calsdataset.cpp, frmts/gtiff/geotiff.cpp, frmts/hfa/hfadataset.cpp, frmts/netcdf/netcdfdataset.cpp, frmts/raw/ehdrdataset.cpp, frmts/vrt/vrtrasterband.cpp, frmts/vrt/vrtsourcedrasterband.cpp, gcore/gdal_priv.h, gcore/gdaldriver.cpp, gcore/gdalproxydataset.cpp, gcore/gdalrasterband.cpp, ogr/ogrsf_frmts/sqlite/rasterlite2.cpp, swig/include/Band.i, swig/include/gdal.i, swig/include/gdal_array.i, swig/python/extensions/gdal_wrap.cpp, swig/python/gdal-utils/osgeo_utils/auxiliary/numpy_util.py, swig/python/osgeo/gdal.py, swig/python/osgeo/gdal_array.py
so that users are aware of the change and can adapt accordingly.
Attempt to alleviate the complaints about the silent breakage situation
Downside is that re-adds some clutter in our code base
=> RFC87: emit a warning when querying PIXELTYPE band IMAGE_STRUCTURE metadata item

autotest/ogr/ogr_vdv.py, ogr/ogrsf_frmts/vdv/ogrvdvdatasource.cpp
=> [Backport release/3.6] VDV: make creation of temporary .gpkg files more robust on some platforms

port/cpl_getexecpath.cpp
=> [Backport release/3.6] CPLGetExecPath(): add MacOSX and FreeBSD implementations; prevent potential one-byte overflow on Linux&Windows

autotest/ogr/ogr_csv.py, ogr/ogrsf_frmts/csv/ogrcsvlayer.cpp
Fixes use case of https://lists.osgeo.org/pipermail/gdal-dev/2022-November/056507.html
=> CSV: accept comma as decimal separator in X_POSSIBLE_NAMES, Y_POSSIBLE_NAMES and Z_POSSIBLE_NAMES fields

autotest/gcore/tiff_srs.py, frmts/gtiff/geotiff.cpp
=> [Backport release/3.6] GTiff: if CRS is DerivedProjected, write it to PAM .aux.xml file (fixes #6758)

autotest/ogr/ogr_csv.py, ogr/ogrsf_frmts/csv/ogrcsvlayer.cpp
=> [Backport release/3.6] CSV: accept comma as decimal separator in X_POSSIBLE_NAMES, Y_POSSIBLE_NAMES and Z_POSSIBLE_NAMES fields

autotest/ogr/ogr_pg.py, ogr/ogrsf_frmts/pg/ogrpgtablelayer.cpp
=> [Backport release/3.6] PG: avoid error when inserting single feature of FID 0 (fixes #6728)

doc/source/development/rfc/index.rst, doc/source/development/rfc/rfc88_googletest.rst
Rendered view of the RST at https://github.com/rouault/gdal/blob/rfc88_text_googletest/doc/source/development/rfc/rfc88_googletest.rst
=> Add RFC88 text: Use GoogleTest framework for C/C++ unit tests

alg/gdalwarpkernel.cpp, autotest/alg/warp.py, autotest/gdrivers/mbtiles.py, autotest/utilities/test_gdal_viewshed.py, autotest/utilities/test_gdalwarp.py
=> [Backport release/3.6] Warper: use exact coordinate transformer on source raster edges to avoid missing pixels (fixes #6777)

autotest/conftest.py
For some reason, it doesn't seem the ``testpaths`` setting of pytest.ini is honoured as expected when running ``pytest autotest`` from the build directory (at least on Linux)
=> autotest/conftest.py: add collect_ignore_glob to ignore pymod/ files

ogr/ogrspatialreference.cpp
https://github.com/OSGeo/PROJ/pull/3488 added a PJ_TYPE_DERIVED_PROJECTED_CRS value to the PJ_TYPE enumeration that we didn't test obviously. But better just use proj_is_crs() to be more robust.
=> OGRSpatialReference::importFromWkt(): fix compatibilty with PROJ master 9.2.0dev

ogr/ogrspatialreference.cpp
=> [Backport release/3.6] OGRSpatialReference::importFromWkt(): fix compatibilty with PROJ master 9.2.0dev

frmts/jpeg/jpgdataset.cpp
=> [Backport release/3.6] Add minimal support for reading 12-bit JPEG images with libjpeg-turbo 2.2dev and internal libjpeg12

ogr/ogrsf_frmts/flatgeobuf/ogr_flatgeobuf.h, ogr/ogrsf_frmts/flatgeobuf/ogrflatgeobuflayer.cpp, ogr/ogrsf_frmts/flatgeobuf/packedrtree.cpp, ogr/ogrsf_frmts/flatgeobuf/packedrtree.h
should help a bit with https://lists.osgeo.org/pipermail/gdal-dev/2022-November/056534.html
Also speed-up things a bit by avoiding use of shared_ptr<>: from 26 s to 23 s when ogr2ogr from/to FlatGeoBuf with a file of 1.8 GB and 3.3 million features.
=> FlatGeobuf: decrease memory usage when inserting lots of features

doc/source/drivers/vector/mssqlspatial.rst, ogr/ogrsf_frmts/mssqlspatial/ogrmssqlspatialdatasource.cpp
MS SQL supports only two authentication modes: `TrustedConnection` or username and password given as `UID` and `PWD` in the connection string.
If `TrustedConnection` is not avaialable, login credentials  can be exposed to other users when command line tools (_ogrinfo_ or _ogr2ogr_) are used.
A somewhat more secure way to handle login information, is to store it in environment variables. 
This PR allows the `MSSQLSPATIAL` driver to fetch `UID` and `PWD` from environment variables `MSSQLSPATIAL_UID` and `MSSQLSPATIAL_PWD`, if no other authentication information is provided. That way `UID` and `PWD` do not have to be provided on the command line. 
* OS: Linux
=> MSSQLSPATIAL: Get UID and PWD from environment variable

frmts/nitf/nitffile.c
There was a bug in nitffile.c in method NITFWriteTREsFromOptions. In this method there is a loop. Within this loop, is a string compare method that accepts the length to compare. This string compare method is used to filter out options that do not have the correct prefix by `continue`-ing the loop (in our case the prefix is TRE=). The string compare length variable is initialized prior to the loop (in our case 4), but once a hex string is passed in, this length is increased by 4. On the next iteration of the loop, this string comparison length is not reset to the original value so all subsequent TREs are filtered out because the string comparison fails (incorrectly).  This commit fixes that issue.
https://github.com/OSGeo/gdal/issues/6827
* Compiler: gcc (Ubuntu …
=> Fixes NITF driver bug that prevents adding subsequent TREs after a HEX TRE (fixes #6827)

autotest/ogr/ogr_gpkg.py, doc/source/drivers/vector/gpkg.rst, ogr/ogrsf_frmts/gpkg/ogr_geopackage.h, ogr/ogrsf_frmts/gpkg/ogrgeopackagedatasource.cpp, ogr/ogrsf_frmts/gpkg/ogrgeopackagedriver.cpp, ogr/ogrsf_frmts/openfilegdb/ogropenfilegdbdatasource.cpp
Relationships can only be updated to change their base or related table fields, or the relationship related table type. It is not permissible to change the base or related table itself, or the mapping table details. If this is desired then a new relationship should be created instead.
=> [gpkg] Implement relationship creation, deletion and update support

apps/ogr2ogr_lib.cpp, autotest/utilities/test_ogr2ogr_lib.py
The logic before this fix would select points that shouldn't be selected, or reject ones that ought to be included. Added test cases represent situations that resulted in unselected points before that fix.
CC @jratike80
=> ogr2ogr: densify points of spatial filter specified with -spat_srs to avoid reprojection artifacts

apps/gdalwarp_lib.cpp, autotest/utilities/test_gdalwarp_lib.py
=> [Backport release/3.6] gdalwarp: fix issue with vertical shift, in particular when CRS has US survey foot as vertical unit (fixes #6839)

autotest/ogr/ogr_geom.py, swig/include/python/ogr_python.i, swig/python/osgeo/ogr.py
=> [Backport release/3.6] Python bindings: make Geometry.__str__() use ExportToIsoWkt() (fixes #6842)

autotest/ogr/ogr_sqlite.py, doc/source/drivers/vector/sqlite.rst, ogr/ogrsf_frmts/sqlite/ogr_sqlite.h, ogr/ogrsf_frmts/sqlite/ogrsqlitedatasource.cpp, ogr/ogrsf_frmts/sqlite/ogrsqlitedriver.cpp, ogr/ogrsf_frmts/sqlite/ogrsqlitetablelayer.cpp
Adds support for creating one-to-many relationships by adding foreign key constraints to fields.
=> [sqlite] Implement AddRelationship support

apps/ogr2ogr_lib.cpp, autotest/utilities/test_ogr2ogr_lib.py, doc/source/drivers/vector/geojsonseq.rst
=> [Backport release/3.6] ogr2ogr: add warning when -t_srs is ignored by drivers that automatically reproject to WGS 84 (fixes #6859)

ogr/ogr_feature.h
https://github.com/OSGeo/gdal/commit/b0797370a3ed238bc5e74435262c2e889f58fe03
adds two new classes GetFields() and GetGeomFields() for easier C++ iteration.
Unfortunately clang++ -Wsign-conversion is unhappy about the implicit change of signedness in the size() functions. This pull appeases clang++ -Wsign-conversion
* OS:
* Compiler:
=> ogr/ogr_feature.h Make implicit sign conversion in  size() functions of classes GetFields() and GetGeomFields() explicit

autotest/gdrivers/png.py, frmts/mrf/PNG_band.cpp, frmts/png/filter_sse2_intrinsics.c, frmts/png/pngdataset.cpp, frmts/png/pngdataset.h
- When whole image decompression is asked, on non-interleave image of
type Byte, use a dedicated code-path that can use libdeflate instead of zlib to
do the deflate decompression. Only enable it on CPUs with SSE2, to be able to apply
fast filters.
- Present the image as a single-block is it is of type Byte and <=  512x512 pixels.
- MRF driver: make it use PNG driver to benefit from above optimization
Tests dataset creation:
```
gdal_translate autotest/gcore/data/small_world.tif small_world_big.png -r bilinear -outsize 8000 4000
gdal_translate small_world_big.png small_world_big.gpkg -co TILEFORMAT=PNG
gdal_translate small_world_big.png small_world_big_png.mrf -co COMPRESS=PNG
```
Reading in band-separate way
----------------------------
hyperfine --warmup 1  'python -c "from osgeo import …
=> PNG: 1.7-2.0x speed-up in whole image decompression with libdeflate on Intel/AMD CPUs

swig/csharp/CMakeLists.txt
This PR is a patch to pr #6843 which fixes the problem with netstandard.
fixes #6871 
#6871 
#6843 
* OS:
* Compiler:
=> CMake: Fix NetStandard

cmake/modules/packages/FindBlosc.cmake
Update regex and variable name to correctly match version from blosc.h.
=> Locate blosc version number when running CMake

cmake/modules/packages/FindBlosc.cmake
Backport #6887
**Authored by:** @havardAasen
=> [Backport release/3.6] Locate blosc version number when running CMake

autotest/gdrivers/gpkg.py, autotest/ogr/ogr_gpkg.py, doc/source/drivers/raster/gpkg.rst, doc/source/drivers/vector/gpkg.rst, doc/source/user/sql_sqlite_dialect.rst, ogr/ogrsf_frmts/gpkg/ogr_geopackage.h, ogr/ogrsf_frmts/gpkg/ogrgeopackagedatasource.cpp, ogr/ogrsf_frmts/sqlite/ogrsqliteregexp.h, ogr/ogrsf_frmts/sqlite/ogrsqlitesqlfunctions.cpp, ogr/ogrsf_frmts/sqlite/ogrsqlitesqlfunctionscommon.cpp
Applies to both SQL SQLite dialect and GPKG
The ``gdal_get_pixel_value()`` function (added in GDAL 3.7) can be used to extract the value of a pixel in a GDAL dataset. It requires the configuration option OGR_SQLITE_ALLOW_EXTERNAL_ACCESS to be set to YES (for security reasons).
It takes 5 arguments:
* a string with the dataset name
* a band number (numbering starting at 1)
* a string being "georef" to indicate that subsequent values will be georeferenced coordinates, or "pixel" to indicate that subsequent values will be in column, line pixel space
* georeferenced X value or column number
* georeferenced Y value or line number
Example:
SELECT gdal_get_pixel_value('../gcore/data/byte.tif', 1, 'georef', 440720, 3751320)
SELECT gdal_get_pixel_value('../gcore/data/byte.tif', 1, 'pixel', 0, 0)
=> SQLITE/GPKG: add a gdal_get_pixel_value() SQL function.

autotest/ogr/ogr_layer_algebra.py, ogr/ogrsf_frmts/generic/ogrlayer.cpp, swig/python/gdal-utils/osgeo_utils/ogr_layer_algebra.py
=> [Backport release/3.6] OGR layer algebra: make sure result layer has no duplicated field names (fixes #6851)

autotest/gcore/vrt_read.py, doc/source/drivers/raster/vrt.rst, frmts/vrt/vrtdataset.cpp
Adds 'a_srs' to the allowed options for a "vrt:// connection.  The effect of the a_srs option is to assign the coordinate reference system of the source in the same way as the argument to gdal_translate does. 
Examples
```
gdalinfo vrt://NETCDF:"/vsicurl/https://www.ncei.noaa.gov/data/sea-surface-temperature-optimum-interpolation/v2.1/access/avhrr/202109/oisst-avhrr-v02r01.20210930.nc":sst?a_srs=OGC:CRS84
gdalinfo  vrt://autotest/gdrivers/data/netcdf/srid.nc?a_srs=EPSG:3031
gdalinfo  "vrt://autotest/gdrivers/data/netcdf/srid.nc?a_srs=EPSG:3031&bands=1,1"
```
=> vrtdataset: vrt connection syntax 'a_srs'

autotest/ogr/ogr_pg.py, autotest/ogr/ogr_pgdump.py, ogr/ogrsf_frmts/pg/ogrpgdatasource.cpp, ogr/ogrsf_frmts/pgdump/ogrpgdumpdatasource.cpp
Currently, the PG and PGDump drivers do not correctly support the TEMPORARY layer creation options. The current code is using pg_temp_1 as the schema name, which is incorrect. Instead the [pg_temp](https://www.postgresql.org/docs/current/runtime-config-client.html) alias should be used in cases where the schema is supplied. I've fixed both the PG and PGDump drivers. The PGDump driver is for correctness with the current documentation, noting that the benefits of using the feature in PGDump are likely minimal as the driver format is likely used for data exchange rather than processing within an OGR script.
* OS: All 
* Compiler: All
=> Fix PG and PGDump drivers to support the TEMPORARY layer CO

autotest/gcore/vrt_read.py, doc/source/drivers/raster/vrt.rst, frmts/vrt/vrtdataset.cpp
Adds 'a_ullr' to the allowed options for a "vrt:// connection. The effect is to override the georeferenced bounds in the same way as the option to gdal_translate.
```
gdalinfo  "vrt://autotest/gdrivers/data/netcdf/srid.nc?a_ullr=0,90,360,-90"
gdalinfo  "vrt://autotest/gdrivers/data/netcdf/srid.nc?a_ullr=0,1,1,0&bands=1,1"
```
#6893
=> vrtdataset: vrt connection option 'a_ullr'

autotest/ogr/ogr_csv.py, doc/source/drivers/vector/csv.rst, ogr/ogrsf_frmts/csv/ogrcsvdatasource.cpp, ogr/ogrsf_frmts/csv/ogrcsvdriver.cpp, port/cpl_csv.cpp
Adds the PIPE separator for CSV vector driver in read mode. 
I tested on GNAF file (download link from link in #6811 
Note the use of driver declaration with "CSV:<file>", else rename to ".csv". 
```R
ogrinfo CSV:TAS_ADDRESS_DEFAULT_GEOCODE_psv.psv
INFO: Open of `CSV:TAS_ADDRESS_DEFAULT_GEOCODE_psv.psv'
using driver `CSV' successful.
1: TAS_ADDRESS_DEFAULT_GEOCODE_psv (None)
```
(I haven't attempted autotests because the python is a bit more involved than I'm comfortable with yet.)
#6811  feature wish, and suggested PR approach
=> CSV vector: pipe separator for read

frmts/mrf/LERCV1/Lerc1Image.cpp, ogr/ogrsf_frmts/openfilegdb/filegdbindex_write.cpp
Without the change buld fails on upcomig `gcc-13` as:
frmts/mrf/LERCV1/Lerc1Image.cpp: In member function 'bool Lerc1NS::Lerc1Image::isallsameval(int, int, int, int) const':
frmts/mrf/LERCV1/Lerc1Image.cpp:730:5: error: 'uint32_t' was not declared in this scope
730 |     uint32_t val = *reinterpret_cast<const uint32_t *>(&(*this)(r0, c0));
|     ^~~~~~~~
/build/gdal/frmts/mrf/LERCV1/Lerc1Image.cpp:29:1: note: 'uint32_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
28 | #include <algorithm>
+++ |+#include <cstdint>
* OS:
* Compiler:
=> Add missing <cstdint headers for uint*_t types

frmts/mrf/LERCV1/Lerc1Image.cpp, ogr/ogrsf_frmts/openfilegdb/filegdbindex_write.cpp
Backport #6915
**Authored by:** @trofi
=> [Backport release/3.6] Add missing <cstdint headers for uint*_t types

MIGRATION_GUIDE.TXT, port/cpl_vsi.h
The VSILFILE* type is no longer aliased to FILE* in builds without the DEBUG define (that is production builds). External code that used FILE* with GDAL VSI*L API has to be changed to use VSILFILE*. This aliasing dates back to old times where both types were indifferently used in the code base. In the mean time, this was cleaned up. But there was a drawback of having VSILFILE* being either a dedicated type or an alias of FILE* depending whether DEBUG is defined, especially with the C++ API, for people building their plugins with DEBUG and running them against a non-DEBUG GDAL build, or the reverse.
=> No longer alias VSILFILE* to FILE* in non-DEBUG builds (fixes #6790)

apps/ogr2ogr_lib.cpp, apps/ogrinfo_lib.cpp, autotest/ogr/ogr_mem.py, autotest/ogr/ogr_oapif.py, autotest/ogr/ogr_wfs.py, autotest/osr/osr_basic.py, data/ogrinfo_output.schema.json, doc/source/drivers/vector/oapif.rst, ogr/ogr_api.h, ogr/ogr_spatialref.h, ogr/ogrsf_frmts/generic/ogrlayer.cpp, ogr/ogrsf_frmts/ogrsf_frmts.h, ogr/ogrsf_frmts/wfs/ogr_wfs.h, ogr/ogrsf_frmts/wfs/ogroapifdriver.cpp, ogr/ogrsf_frmts/wfs/ogrwfsdatasource.cpp, ogr/ogrsf_frmts/wfs/ogrwfslayer.cpp, ogr/ogrspatialreference.cpp, swig/include/ogr.i, swig/include/osr.i, swig/include/python/gdal_python.i, swig/include/python/typemaps_python.i, swig/python/extensions/ogr_wrap.cpp, swig/python/extensions/osr_wrap.cpp, swig/python/osgeo/gdal.py, swig/python/osgeo/ogr.py
-   OAPIF: add support for OGC API Features - Part 2 CRS extension
storageCrs when found is used to set the layer CRS, express the spatial
extent in that CRS, and set the crs and bbox-crs query parameters to
request items/features in that CRS.
storageCrsCoordinateEpoch is also used when found
- OAPIF driver: add CRS/PREFERRED_CRS open options to control the active CRS
- OAPIF: add a SERVER_FEATURE_AXIS_ORDER open option
- Add OGRLayer::GetSupportedSRSList() and SetActiveSRS(), and implement in OAPIF driver
- ogrinfo: output CRS supported list
- ogr2ogr: use SetActiveSRS() when possible when -t_srs is used
- WFS: implement GetSupportedSRSList() and SetActiveSRS()
=> OAPIF: implement Part 2 / CRS extension, and related enhancements

autotest/gdrivers/netcdf.py, doc/source/drivers/raster/netcdf.rst, frmts/netcdf/netcdfdataset.cpp, frmts/netcdf/netcdfdataset.h
Implements the wish of #6195 to assume a regular grid NetCDF in a reasonable longitude/latitude range adopts the `OGC:CRS84` crs, when all prior attempts to find one have failed. 
- when all other attempts have been tried, we check the bounds and give it longlat crs if within -180,360 -90,90
- new config option `GDAL_NETCDF_ASSUME_LONGLAT` default NO, set to YES to apply the crs 
- new open option `ASSUME_LONGLAT` same as config option `GDAL_NETCDF_ASSUME_LONGLAT` 
There is a python test on `netcdf/trmm-nc2.nc` that invokes the use of the setting (this file otherwise doesn't have a crs set). 
#6195 
here on a remote file, provides a CRS OGC:CRS84 only if the config option is set
```
export GDAL_NETCDF_ASSUME_LONGLAT=YES
gdalinfo NETCDF:"/vsicurl/https://rsg.pml.ac.uk/thredds/fileServer/cci …
```
=> Netcdf 6195 assume longlat

autotest/ogr/data/parquet/schema.json, autotest/ogr/ogr_parquet.py, doc/source/drivers/vector/parquet.rst, ogr/ogr_core.h, ogr/ogrsf_frmts/arrow_common/ogr_arrow.h, ogr/ogrsf_frmts/arrow_common/ograrrowwriterlayer.hpp, ogr/ogrsf_frmts/parquet/ogrparquetlayer.cpp, ogr/ogrsf_frmts/parquet/ogrparquetwriterlayer.cpp
Main changes in the implementation are:
- "geometry_type" is renamed as "geometry_types" and is always an array
- "bbox" is written with zmin and zmax when there are 3D geometries
- slightly improved deduction of OGR layer geometry type when there are mixes like LineString, LineString Z, MultiLineString in geometry_types
CC @jorisvandenbossche @paleolimbot @cholmes
=> Parquet: update to GeoParquet 1.0.0-beta.1 specification (fixes #6646)

ogr/ogrsf_frmts/gml/ogrgmldatasource.cpp
=> [Backport release/3.6] GML: fix recognizing WFS GetFeature response with a very long initial XML element (fixes #6940)

apps/ogr2ogr_lib.cpp
Fixes https://lists.osgeo.org/pipermail/gdal-dev/2022-December/056666.html
=> ogr2ogr: silent reprojection errors related to IsPolarToWGS84() in OGRGeometryFactory::transformWithOptions()

autotest/gcore/rasterio.py, autotest/gdrivers/aaigrid.py, frmts/aaigrid/aaigriddataset.cpp
=> [Backport release/3.6] AAIGRID: fix CreateCopy() of source raster with south-up orientation (fixes #6946)

frmts/vrt/vrtsourcedrasterband.cpp
Given that there's no guarantee that VRTSourcedRasterBand is attached to a VRTDataset
=> VRTSourcedRasterBand: replace potentially unsafe cpl::down_cast<> by dynamic_cast<>

frmts/vrt/vrtsourcedrasterband.cpp
=> [Backport release/3.6] VRTSourcedRasterBand: replace potentially unsafe cpl::down_cast<> by dynamic_cast<>

port/cpl_http.cpp, port/cpl_vsil_curl.cpp, port/cpl_vsil_curl_streaming.cpp
=> [Backport release/3.6] Avoid warning with curl >= 7.87 about CURLOPT_PROGRESSFUNCTION being deprecated (fixes Alpine CI)

autotest/ogr/ogr_gpkg.py, ogr/ogrsf_frmts/gpkg/ogr_geopackage.h, ogr/ogrsf_frmts/gpkg/ogrgeopackagedatasource.cpp, ogr/ogrsf_frmts/gpkg/ogrgeopackagetablelayer.cpp
Async RTree building doesn't play well with multiple layers: SQLite3 locks being hold for a long time, random failed commits, etc
=> GPKG: fix threaded RTree building when creating several layers (3.6.0 regression)

ogr/ogrsf_frmts/gpkg/ogrgeopackagedatasource.cpp, ogr/ogrsf_frmts/sqlite/ogrsqliteexecutesql.cpp
=> [Backport release/3.6] GPKG/SQLite dialect: fix issues when SQL statement provided to ExecuteSQL() starts with space/tabulation/newline (fixes #6976)

alg/llrasterize.cpp, autotest/alg/rasterize.py
=> [Backport release/3.6] RasterizeLayer: prevent out-of-bounds index/crash on some input data (fixes #6981)

frmts/esric/esric_dataset.cpp, ogr/ogrsf_frmts/selafin/ogrselafindriver.cpp
When checking metadata in pyogrio, I noticed those two drivers had a deviating entry for `DCAP_VECTOR`:
- ESRIC: is a raster driver, and the code generally assumes that DCAP_VECTOR then will be nullptr, not a "NO" string.
- Selafin: is a vector driver, and the exact content of the string doesn't matter that much in practice, but all other vector drivers are using `"YES"` instead.
Does this need a test?
=> BUG: fix DCAP_VECTOR metadata for Selafin and ESRIC drivers

frmts/esric/esric_dataset.cpp, ogr/ogrsf_frmts/selafin/ogrselafindriver.cpp
Backport #6994
**Authored by:** @jorisvandenbossche
=> [Backport release/3.6] BUG: fix DCAP_VECTOR metadata for Selafin and ESRIC drivers

swig/csharp/CMakeLists.txt, swig/csharp/apps/GDALAdjustContrast.cs, swig/csharp/drawing_compat.cs, swig/csharp/exe_template_dcomp.csproj
@bjornharrtell @szekerest 
This is a reasonably complicated explanation:
1. The C# bindings build includes a number of sample apps. These are (excellent) code exemplars and also are used in all builds to test the C# bindings - but I don't think they are intended to be used for production or that anybody does so. The Sample applications use `System.Drawing.Bitmap` to manipulate bitmaps.
2. `System.Drawing.Bitmap` uses GDI+ (at least in the non-mono builds) and the cross-platform implementations of that have always been "interesting". Microsoft has clarified the situation by saying that `System.Drawing.Common` (that implements Bitmap) is NOT supported cross-platform (see https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only) after …
=> CSHARP: Add SkiaSharp

autotest/ogr/data/gml/citygml.gml, autotest/ogr/ogr_gml_read.py, ogr/ogrsf_frmts/gml/gmlhandler.cpp
=> [Backport release/3.6] GML: default srsDimension to 3 for CityGML files (fixes #6989)

alg/gdalwarpoperation.cpp, apps/gdalwarp_bin.cpp, apps/gdalwarp_lib.cpp, autotest/utilities/test_gdalwarp_lib.py, doc/source/programs/gdalwarp.rst, swig/include/python/gdal_python.i, swig/python/osgeo/gdal.py
.. option:: -srcband <n>
Specify a input band number to warp (between 1 and the number of bands
of the source dataset). This option may be repeated multiple times, to warp
several bands of the input dataset. The alpha band should not be specified
in the list, as it will be automatically retrieved (unless :option:`-nosrcalpha`
is specified).
If :option:`-srcband` is not specified, all input bands are used.
.. option:: -dstband <n>
Specify the output band number in which to warp.
If :option:`-srcband` is specified, there must be as many occurences of
:option:`-dstband` as there are of :option:`-srcband`.
The output alpha band should not be specified, as it will be automatically
created if the input dataset has an alpha band, or if :option:`-dstalpha`
is specified.
If :option:`-dstband` is …
=> gdalwarp: add -srcband and -dstband options

autotest/gdrivers/jpegxl.py, frmts/jpegxl/jpegxl.cpp
=> [Backport release/3.6] JPEGXL: advertize COMPRESSION_REVERSIBILITY=LOSSY when there is a JPEG reconstruction box

autotest/gdrivers/jpeg.py, frmts/jpeg/jpgdataset.cpp
This can be turned back as a warning only by setting GDAL_ERROR_ON_LIBJPEG_WARNING to FALSE
=> JPEG: change behavior to return an error and not just a warning with reading a truncated file

apps/gdalmdimtranslate_lib.cpp
=> [Backport release/3.6] gdalmdimtranslate: do not require VRT driver to be registered (fixes #7021)

autotest/gcore/bmp_write.py, frmts/bmp/bmpdataset.cpp
=> [Backport release/3.6] BMP: Make sure file is created at proper size if only calling Create() without writing pixels (fixes #7025)

alg/gdal_alg_priv.h, alg/gdalrasterpolygonenumerator.cpp, alg/gdalsievefilter.cpp, alg/polygonize.cpp
=> [Backport release/3.6] GDALRasterPolygonEnumeratorT::NewPolygon(): check memory allocation to avoid crash (fixes #7027)

swig/python/setup.py.in
In `finalize_options()`, there is a code-path for existing string-style include/library dirs. In a standalone build this results in appending an empty directory to each list, which leads to CC invocations with bare `-I` and `-L -lgdal`, the latter resulting in modules not being linked to `libgdal`, as the second `-lgdal` argument is interpreted as a dir.
Fix by checking whether `include_dirs`/`library_dirs` are non-empty before appending.
I'm triggering this by using a `setup.cfg` file to cleanly pass build options, something like:
```console
$ wget https://pypi.org/packages/source/G/GDAL/GDAL-3.6.2.tar.gz 
$ tar xzf GDAL-3.6.2.tar.gz
$ cd GDAL-3.6.2
$ echo >setup.cfg <<EOF
[build_ext]
library_dirs=/path/1:/path/2
include_dirs=/path/1:/path/2
libraries=gdal …
```
=> python: fix setup.py directory list issue on macOS

port/cpl_http.cpp
Current CPLHTTPFetch function only allows to send form using POST request method.  This PR also add ability to send form using PUT or PATCH request method.
=> cpl_http: Change behaviour - CUSTOMREQUEST option overrides POST request method while sending form

ogr/ogrsf_frmts/gpkg/ogrgeopackagetablelayer.cpp
Proposal to fix some cases where ogr2ogr and VectorTranslate write invalid gpkg output files.
When -nlt (or geometrytype in VectorTranslate) is specified in combination with one of the following situations:
- when executing an sql statement returning NULL geoms
- when executing an sql statement doing a spatial operation (eg. ST_Buffer) on the geom that returns no rows
This results in:
- the following error being written: ERROR 1: sqlite3_exec(CREATE TABLE "belgie_empty2" ( "fid" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "geom" POLYGON, "geom" TEXT)) failed: duplicate column name: geom
- the gpkg written is invalid: gives an exception when opened.
These are cases 3.i and 4.i in the following issue: #6976
The change in this PR avoids that an attribute column having the same name as the …
=> Fix ogr2ogr error + invalid gpkg output file in some cases

alg/gdalwarpkernel.cpp, apps/gdalwarp_lib.cpp, autotest/utilities/test_gdalwarp_lib.py
=> [Backport release/3.6] gdalwarp: fix vshift mode when vertical unit of dstSrs is non-metric

autotest/gdrivers/dimap.py, frmts/dimap/dimapdataset.cpp
=> [Backport release/3.6] DIMAP: optimize performance of dataset RasterIO() (improve perf on multispectral datasets with JP2KAK underlying driver)

ogr/ogrsf_frmts/hana/ogrhanadatasource.cpp
This PR fixes a bug that doesn't allow to use DSN in open options.
=> HANA: fix DSN open option

cmake/modules/packages/FindHDF4.cmake
- handle cases of Windows paths such as `C:/Program Files/blah`
- prevent CMake error such as:
```
CMake Error at cmake/modules/packages/FindHDF4.cmake:127 (set_target_properties):
set_target_properties called with incorrect number of arguments.
```
This took me a long time to debug, in the end it is a minor change, that someday will save someone else days of effort.
=> HDF4: avoid CMake error with Windows paths

cmake/modules/packages/FindHDF4.cmake
Backport #7091
**Authored by:** @jmckenna
=> [Backport release/3.6] HDF4: avoid CMake error with Windows paths

gdal.cmake
=> [Backport release/3.6] CMake: fix wrong test when GDAL_SET_INSTALL_RELATIVE_RPATH is set

port/cpl_vsisimple.cpp
=> [Backport release/3.6] CPLGetPhysicalRAM(): take into account current cgroup (v1 and v2)

ogr/ogrsf_frmts/openfilegdb/ogr_openfilegdb.h, ogr/ogrsf_frmts/openfilegdb/ogropenfilegdbdatasource.cpp, ogr/ogrsf_frmts/openfilegdb/ogropenfilegdblayer.cpp
Fixes the use case of https://lists.osgeo.org/pipermail/gdal-dev/2023-January/056790.html when identifying the following WKT in multiple layers: 'PROJCS["GK_31",GEOGCS["GCS_MGI",DATUM["D_MGI",SPHEROID["Bessel_1841",6377397.155,299.1528128]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Gauss_Kruger"],PARAMETER["False_Easting",0.0],PARAMETER["False_Northing",-5000000.0],PARAMETER["Central_Meridian",13.3333333333333],PARAMETER["Scale_Factor",1.0],PARAMETER["Latitude_Of_Origin",0.0],UNIT["Meter",1.0]]'
=> OpenFileGDB: fix performance issue when identifying a CRS

frmts/gtiff/geotiff.cpp
=> [Backport release/3.6] GTiffJPEGOverviewBand::IReadBlock(): remove hack that causes read errors in some circumstances

autotest/ogr/ogr_openfilegdb.py, ogr/ogrsf_frmts/openfilegdb/filegdbindex.cpp
=> [Backport release/3.6] OpenFileGDB: detect broken .spx file with wrong index depth (fixes qgis/qgis#32534)

ogr/ogrsf_frmts/openfilegdb/filegdbindex.cpp
=> [Backport release/3.6] OpenFileGDB: index reading: avoid integer overflow on index larger than 2 GB

scripts/setdevenv.sh
This PR updates `setdevenv.sh` so that it can be sourced from `zsh` in addition to `bash`. It continues to produce an error if executed (rather than sourced) in both shells.
Without this PR, the script causes `zsh` to exit if it is sourced. 
None
=> setdevenv.sh: Support zsh

port/cpl_findfile.cpp
This PR updates `CPLDefaultFindFile` to emit a warning if a file is not found and `GDAL_DATA` is not defined.
There are handful of C++ unit tests that depend on files found in `GDAL_DATA`, and I was trying to provide information in these  cases that would guide the developer to fix their test environment. I'm not sure if there are other usages of `CPLFindFile` where it would be undesirable to emit this warning.
This seemed like a better solution than providing custom a error message for each test assert that somehow relies on `GDAL_DATA` (seems to require a lot of copy/paste), or just adding a test that verifies that `GDAL_DATA` is defined (maybe would fail unnecessarily for some test environment)
Example output for a failing test that depends on `GDAL_DATA`:
```
GDAL C/C++ API tests …
```
=> CPLFindFile: Warn if file not found and GDAL_DATA not defined

autotest/cpp/test_cpl.cpp, autotest/cpp/test_ogr_shape.cpp
Removes order dependencies between C++ unit tests. Without this PR, the following fail:
`gdal_unit_test --gtest_shuffle --gtest_random_seed=25391 --gtest_filter="test_cpl*"`
`gdal_unit_test --gtest_shuffle --gtest_random_seed=31047 --gtest_filter="*shape*"`
None
* OS:
* Compiler:
=> Autotest: Remove order dependencies between C++ tests

autotest/osr/osr_basic.py, ogr/ogrspatialreference.cpp
for consistency with importFromWkt()
=> OSRSpatialReference::SetFromUserInput(): skip leading white space (fixes #7170)

autotest/ogr/ogr_openfilegdb_write.py, ogr/ogrsf_frmts/openfilegdb/ogr_openfilegdb.h, ogr/ogrsf_frmts/openfilegdb/ogropenfilegdblayer.cpp, ogr/ogrsf_frmts/openfilegdb/ogropenfilegdblayer_write.cpp
=> [Backport release/3.6] OpenFileGDB: allow CreateField() with OBJECTID as the column name (fixes #51435)

autotest/gcore/cog.py, frmts/gtiff/cogdriver.cpp
=> [Backport release/3.6] COG: avoid warning message when using -co COMPRESS=WEBP -co QUALITY=100 (fixes #7153)

autotest/gdrivers/nitf.py, frmts/nitf/nitfdataset.cpp, frmts/nitf/nitffile.c
=> [Backport release/3.6] NITF: update CLEVEL to appropriate values when using compression / multiple image segments

apps/ogr2ogr_bin.cpp, apps/ogr2ogr_lib.cpp, autotest/utilities/test_ogr2ogr_lib.py, doc/source/programs/ogr2ogr.rst
.. option:: -dateTimeTo UTC|UTC(+|-)HH|UTC(+|-)HH:MM]
.. versionadded: 3.7
Converts date time values from the timezone specified in the source value
to the target timezone expressed with :option:`-dateTimeTo`.
Datetime whose timezone is unknown or localtime are not modified.
HH must be in the [0,14] range and MM=00, 15, 30 or 45.
=> ogr2ogr: add a -dateTimeTo option to convert datetime between timezones (fixes #5256)

doc/source/drivers/raster/netcdf.rst
Fixes the incorrect rendering of the [ASSUME_LONGLAT](https://gdal.org/drivers/raster/netcdf.html#open-options) and [GDAL_NETCDF_ASSUME_LONGLAT](https://gdal.org/drivers/raster/netcdf.html#configuration-options) NetCDF driver options.
=> [Docs] Fix NetCDF driver options rendering

apps/ogr2ogr_lib.cpp
This PR attempts to improve the performance of `ogr2ogr` with a `-clipsrc` or `-clipdst` argument by testing whether geometries intersect the clipping area (relatively cheap) before computing their intersection (relatively expensive.)
I tested the performance of this using a dataset of ~300,000 parcel polygons for the state of Vermont. In the best reasonable case (clipping out part of one town, or 0.1% of the total polygons) it reduces runtime by ~50%, depending on the GEOS version. In the worst case, where every polygon is within the clipping window, it increases runtime by ~1%.
It could be made more efficient with a way to cache the `GEOSGeometry*` between successive calls to GEOS functions.
None.
=> ogr2ogr: Improve performance of -clipsrc and -clipdst

alg/gdal_alg.h, alg/gdaltransformer.cpp, alg/gdaltransformgeolocs.cpp
Consistency of GDALSuggestedWarpOutput2 signature and definition, and nearby documentation clarifications that render in gdal_alg.html
Discussed at https://lists.osgeo.org/pipermail/gdal-dev/2023-February/056836.html
=> gdal_alg.html: padfExtent/s consistency, and small doc fixes

autotest/gcore/tiff_ovr.py, gcore/gdaldefaultoverviews.cpp
=> [Backport release/3.6] GTiff: fix generation of external overviews on 1xsmall_height rasters (fixes #7194)

gcore/rawdataset.cpp, gcore/rawdataset.h
(amends 3c5f1a040b98fbe188d55e1ee7061e6937cfaaac)
=> RawDataset: avoid Valgrind use-of-unitialized memory warning 

autotest/gdrivers/tiledb_read.py, autotest/gdrivers/tiledb_write.py, frmts/tiledb/tiledbdataset.cpp, gcore/rasterio.cpp
This PR changes the way that the TileDB driver requests data using rasterio. The reason for this change is to optimize for use within MapServer so that complete regions are requested at once and the TileDB driver internally does the parallel reads.
This PR in turn fixes https://github.com/OSGeo/gdal/issues/7099 as the TileDB `Query` is now initialized for every call.
Marked as WIP until the CI passes.
https://github.com/OSGeo/gdal/issues/7099
=> tiledb rasterio

alg/gdalcutline.cpp, alg/gdalwarper.h, alg/gdalwarpkernel.cpp, alg/gdalwarpoperation.cpp
=> Warper: do not use OpenCL code path when cutline (or source alpha) is used

cmake/modules/packages/FindSQLite3.cmake
This fixes a build issue
> "Unknown CMake command cmake_push_check_state". 
When FindSQLite3.cmake is invoked. 
None
* OS: Apple M1 Pro, Ventura 13.0.1 (22A400)
* Compiler: Apple clang version 14.0.0 (clang-1400.0.29.202)
=> Add required CMakePushCheckState include to FindSQLite3.cmake

autotest/gcore/gdal_stats.py, autotest/gdrivers/ecw.py, frmts/gtiff/geotiff.cpp, gcore/gdalrasterband.cpp
Previously only the nodata value was taken into account to ignore masked pixels.
CC @nyalldawson
=> ComputeRasterMinMax(), ComputeStatistics(), GetHistogram(): take into account mask band

alg/gdalcutline.cpp, alg/gdalwarper.h, alg/gdalwarpkernel.cpp, alg/gdalwarpoperation.cpp
=> [Backport release/3.6] Warper: do not use OpenCL code path when cutline (or source alpha) is used

port/cpl_compressor.cpp
=> [Backport release/3.6] Avoid use of deprecated ZSTD_getDecompressedSize() function with libzstd 1.3+

autotest/CMakeLists.txt, autotest/conftest.py, cmake/template/pytest.ini.in
This PR stores the GDAL version available to CMake in the generated `pytest.ini`. Before tests are run, pytest can then check this version against what it reads from `gdal.__version__` to make sure that paths/etc. were set properly. If they were not, it will bail before any tests are run, emitting a message that should more clearly indicate the problem to the developer.
```
➜  build-gdal-Desktop-Debug pytest autotest/ogr
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/usr/lib/python3/dist-packages/_pytest/main.py", line 265, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "/usr/lib/python3/dist-packages/_pytest/config/__init__.py", line 982, in _do_configure
INTERNALERROR> …
```
=> Autotest: Check for build/runtime verison mismatch

alg/delaunay.c, alg/gdalgrid.cpp, alg/gdalgrid.h, apps/gdal_grid_lib.cpp, autotest/gcore/multidim.py, autotest/gdrivers/memmultidim.py, frmts/mem/memdataset.cpp, frmts/mem/memmultidim.h, frmts/netcdf/netcdfmultidim.cpp, gcore/CMakeLists.txt, gcore/gdal.h, gcore/gdal_priv.h, gcore/gdalmultidim.cpp, gcore/gdalmultidim_gridded.cpp, swig/include/MultiDimensional.i, swig/include/Operations.i, swig/python/extensions/gdal_wrap.cpp, swig/python/osgeo/gdal.py
Return a gridded array from scattered point data, that is from an array
whose last dimension is the indexing variable of X and Y arrays.
e.g. the zeta variable in:
```
dimensions:
node = 303714 ;
time = UNLIMITED ; // (1 currently)
variables:
float lon(node) ;
lon:long_name = "nodal longitude" ;
lon:standard_name = "longitude" ;
lon:units = "degrees_east" ;
float lat(node) ;
lat:long_name = "nodal latitude" ;
lat:standard_name = "latitude" ;
lat:units = "degrees_north" ;
float zeta(time, node) ;
zeta:long_name = "Water Surface Elevation" ;
zeta:units = "meters" ;
zeta:positive = "up" ;
zeta:standard_name = "sea_surface_height_above_geoid" ;
zeta:grid = "Bathymetry_Mesh" ;
zeta:coordinates = "time lat lon" ;
zeta:type = "data" ;
zeta:location = "node" ;
```
The gridding is done in 2D, …
=> Add GDALMDArray::GetGridded() and GDALMDArrayGetGridded()

apps/gdalwarp_lib.cpp, autotest/utilities/test_gdalwarp_lib.py
=> [Backport release/3.6] gdalwarp: allow up to inaccuracy in cropline coordinates up to 0.1% of a pixel size for rounding (fixes #7226)

autotest/gdrivers/mem.py, doc/source/drivers/raster/mem.rst, frmts/mem/memdataset.cpp
Adds a missing 'SPATIALREFERENCE' element to the MEM driver DSN format.
First attempt (rebase problem) with discussion and review and additions  at #7266.
=> MEM: add spatialreference element 

autotest/conftest.py, autotest/gcore/tiff_ovr.py, autotest/gcore/tiff_read.py, autotest/gcore/tiff_write.py, autotest/gcore/vsicurl.py, autotest/gcore/vsizip.py, autotest/gdrivers/gpkg.py, autotest/gdrivers/netcdf.py, autotest/gdrivers/vrtwarp.py, autotest/gdrivers/wms.py, autotest/ogr/ogr_gml_read.py, autotest/ogr/ogr_wfs.py, cmake/template/pytest.ini.in
Add pytest marker for slow tests. This allows a consistent message to be provided when slow tests are skipped.
https://github.com/OSGeo/gdal/pull/1194 has some discussion about tradeoffs in adding markers.
=> autotest: Add pytest marker for slow tests

apps/test_ogrsf.cpp, autotest/ogr/data/geojson/ids_0_1_null_1_null.json, autotest/ogr/data/geojson/ids_0_1_null_unset.json, autotest/ogr/ogr_geojson.py, ogr/ogrsf_frmts/geojson/ogr_geojson.h, ogr/ogrsf_frmts/geojson/ogrgeojsondatasource.cpp, ogr/ogrsf_frmts/geojson/ogrgeojsondriver.cpp, ogr/ogrsf_frmts/geojson/ogrgeojsonlayer.cpp, ogr/ogrsf_frmts/geojson/ogrgeojsonreader.cpp, ogr/ogrsf_frmts/geojson/ogrgeojsonreader.h
=> [Backport release/3.6]  GeoJSON: avoid duplication of FID in streaming parser (fixes #7258) 

autotest/CMakeLists.txt
This PR symlinks `conftest.py` into the build directory so that changes to that file are visible to the test suite without rerunning `cmake`.
Discussion in https://github.com/OSGeo/gdal/commit/9b3905e695acb0f9634e45acbce52500326f0f46
=> autotest: Symlink conftest.py into build directory

autotest/ogr/ogr_fgdb.py, ogr/ogrsf_frmts/filegdb/FGdbLayer.cpp, ogr/ogrsf_frmts/filegdb/FGdbUtils.cpp, ogr/ogrsf_frmts/filegdb/FGdbUtils.h, ogr/ogrsf_frmts/openfilegdb/ogropenfilegdblayer.cpp, ogr/ogrsf_frmts/openfilegdb/ogropenfilegdblayer_write.cpp
as it is not supported in FileGeodatabase for floating-point types.
and also correct ObjectID field to have a Length of 4.
Fixes #7283
=> FileGDB/OpenFileGDB: do not touch field precision for floating-point data types

autotest/gcore/vrt_read.py, doc/source/drivers/raster/vrt.rst, frmts/vrt/vrtdataset.cpp
Adds 'expand' to the allowed options for a "vrt:// connection. The effect is to expand a palette image index by a 1 band dataset  RGB, RGBA, or Gray dataset.
=> VRT: 'expand' opt for vrt:// connection

autotest/gcore/vrt_read.py, doc/source/drivers/raster/vrt.rst, frmts/vrt/vrtdataset.cpp
Adds 'a_offset' and 'a_scale' to the allowed options for a "vrt:// connection.
=> VRT 'a_offset' and 'a_scale' options for vrt:// connection

autotest/ogr/ogr_ngw.py
Marks the ogr_ngw tests as slow. The slowest of these, ogr_ngw_test_sf, takes about 7 minutes to run on my machine. Several of the remaining tests take > 5 seconds to run, which is longer than other tests that are currently marked as slow (e.g., test_ogr_wfs_esri_2). But because the faster tests depend on state set by the slower tests, the entire module needs to be marked as slow.
Alternatively, or additionally, these tests could be marked with `pytest.mark.run_on_demand()`.
Based on a look at the current tests that are marked as slow, I think the testing docs could be updated to recommend a marking as slow for tests taking > 5 seconds.
#4453
=> autotest: Mark ogr_ngw tests as slow

autotest/gcore/vrt_read.py, doc/source/drivers/raster/vrt.rst, frmts/vrt/vrtdataset.cpp
Adds 'ot' output type to the allowed options for a "vrt:// connection.
=> VRT 'ot' option for vrt:// connection

autotest/ogr/ogr_geojson.py, ogr/ogrsf_frmts/geojson/ogrgeojsonreader.cpp
Set the field subtype to OFSTJSON even when the first occurrence of the field was a string.
fixes #7313
=> GEOJSON: fix mixed type field not flagged as JSON if first occurrence is a string  (fixes #7313)

cmake/helpers/configure.cmake, cmake/template/cpl_config.h.in, port/cpl_config.h.in, port/cpl_multiproc.cpp
Check for `pthread_spin_lock` instead of `pthread_spin_lock_t` to avoid the following uclibc build failure:
```
/tmp/instance-7/output-1/build/gdal-3.5.2/port/cpl_multiproc.cpp: In function 'CPLSpinLock* CPLCreateSpinLock()': /tmp/instance-7/output-1/build/gdal-3.5.2/port/cpl_multiproc.cpp:2265:9: error: 'pthread_spin_init' was not declared in this scope; did you mean 'pthread_cond_init'?
2265 |         pthread_spin_init(&(psSpin->spin), PTHREAD_PROCESS_PRIVATE) == 0 )
|         ^~~~~~~~~~~~~~~~~
|         pthread_cond_init
/tmp/instance-7/output-1/build/gdal-3.5.2/port/cpl_multiproc.cpp: In function 'int CPLAcquireSpinLock(CPLSpinLock*)':
/tmp/instance-7/output-1/build/gdal-3.5.2/port/cpl_multiproc.cpp:2283:12: error: 'pthread_spin_lock' was not declared in this scope; did you mean …
```
=> fix uclibc build without NPTL

doc/source/development/dev_environment.rst
Clarify build vs test requirements.
The python 3.5 requirement comes from our minimum pytest version, but I am not sure that the tests run with 3.5 (IIRC, the CI is using 3.6). I can look into this.
#7330
=> Doc: Clarify requirements for building vs testing

autotest/ogr/ogr_geojson.py, ogr/ogrsf_frmts/geojson/ogrgeojsonreader.cpp
=> [Backport release/3.6] GEOJSON: fix mixed type field not flagged as JSON if first occurrence is a string  (fixes #7313)

autotest/ogr/ogr_shape.py
This PR just updates `ogr_shape.py` to use newer conventions: calling `assert` instead of `if x: pytest.fail()`, using `@pytest.mark.parametrize` instead of loops, and calling helper functions that already exist in `gdaltest.py`.
Diff ignoring whitespace changes: https://github.com/OSGeo/gdal/compare/master...dbaston:gdal:pytest-clean?expand=1&w=1
None
=> autotest: Update ogr_shape.py with newer conventions

apps/ogrinfo_lib.cpp
Currently `ogrinfo -json -features` behaves differently from `ogrinfo -features -json`.
This PR fixes such weird behaviour, so `ogrinfo -json -features` will be the same as `ogrinfo -features -json`. Moreover ogrinfo will fail if both `-so` (or `-summary`) and `-features` parameters are present in the command.
See https://github.com/OSGeo/gdal/issues/7342#issuecomment-1454046572 and https://github.com/OSGeo/gdal/issues/7342#issuecomment-1454221549
* OS:
* Compiler:
=> ogrinfo: fix -json -so -features parameters behaviour

autotest/ogr/ogr_gml_geom.py, ogr/ogr2gmlgeometry.cpp
=> [Backport release/3.6] GML export: fix CurvePolygon export of CompoundCurve and CircularString child elements (fixes #7294)

autotest/ogr/ogr_geojson.py, ogr/ogrsf_frmts/geojson/ogrgeojsonwritelayer.cpp
=> [Backport release/3.6] GeoJSON writer: take into account COORDINATE_PRECISION for top bbox (fixes #7319)

cmake/modules/packages/FindCryptoPP.cmake, cmake/modules/packages/FindDeflate.cmake
Credits to @dg0yt for hinting the fix
=> FindCryptoPP.cmake: properly take into account _LIBRARY_RELEASE/_DEBUG (fixes #7338)

swig/python/gdal-utils/osgeo_utils/gdal_polygonize.py
Running ``gdal_polygonize.py GDEM-10km-colorized.tif out.gpkg`` goes from 2m14s to 18s on https://asterweb.jpl.nasa.gov/images/GDEM-10km-colorized.tif
=> gdal_polygonize.py: use transactions to speed-up writing

cmake/modules/packages/FindCryptoPP.cmake, cmake/modules/packages/FindDeflate.cmake
=> [Backport release/3.6] FindCryptoPP.cmake: properly take into account _LIBRARY_RELEASE/_DEBUG (fixes #7338)

autotest/ogr/ogr_mitab.py, ogr/ogrsf_frmts/mitab/mitab_spatialref.cpp
=> [Backport release/3.6] MITAB: Fix a typo at MITABGetCustomDatum serialization

HOWTO-RELEASE, doc/source/api/python_bindings.rst, doc/source/development/building_from_source.rst, doc/source/development/dev_practices.rst, doc/source/drivers/raster/isis3.rst, doc/source/drivers/raster/sentinel2.rst, doc/source/drivers/raster/vicar.rst, doc/source/drivers/vector/gml.rst, doc/source/user/gdal_python_utilities.rst
* This changes everything in doc folder
* It should be validated by maintainers to not break anything
* code blocks are unchanged since it's assumed they are all in python3
#7383
* Compiler: sphinx (doc changes only)
=> Doc: Use python3 for executable rather than python (fixes #7383)

autotest/gdrivers/mrf.py, frmts/mrf/marfa.h
=> [Backport release/3.6] MRF: restore SetSpatialRef() that was wrongly deleted in 3.6.0

autotest/conftest.py
Prints the contents of `gdal.VersionInfo('BUILD_INFO')` below the platform information printed by `pytest`. I now realize the `pytest_report_header` hook used here is probably the more idiomatic way to report on environment variables that affect tests, so I moved the information from 0bfe1ad here as well.
Motivation: Trying to figure out why a single parquet test fails locally but passes CI, suspecting that a PROJ version difference factors into it. The PROJ version is reported in CMake configure output, but that pretty distant from the test output.
Result:
```
Test session starts (platform: linux, Python 3.10.6, pytest 7.2.1, pytest-sugar 0.9.6)
Test order randomisation NOT enabled. Enable with --random-order or --random-order-bucket=<bucket_type>
GDAL Build Info:
PAM_ENABLED: YES …
```
=> autotest: Print GDAL build info in test report header

.github/workflows/ubuntu_18.04_32bit/start.sh, autotest/gdrivers/netcdf.py, autotest/gdrivers/netcdf_multidim.py, port/cpl_userfaultfd.cpp
=> [Backport 3.6] userfaultfd: avoid it to stall on 32bit and test real working of syscall in CPLIsUserFaultMappingSupported()

MIGRATION_GUIDE.TXT, alg/gdalpansharpen.cpp, alg/gdalpansharpen.h, autotest/gdrivers/vrtpansharpen.py, doc/source/drivers/raster/vrt.rst, frmts/vrt/vrtpansharpened.cpp
Pansharpening now requires that panchromatic and multispectral bands have valid geotransform (in early versions, it was assumed in the case of missing geotransform that they covered the same geospatial extent). The undocumented VRT pansharpened MSShiftX and MSShiftY options (and the corresponding C++ GDALPansharpenOptions::dfMSShiftX and dfMSShiftY members) have been removed, due to using the inverted convention as one would expect, and being sub-par solution compared to using geotransform to correlate pixels of panchromatic and multispectral bands.
=> Pansharpening: require geotransform on panchromatic and multispectral bands

autotest/gcore/basic_test.py, autotest/gcore/numpy_rw.py, autotest/gdrivers/memmultidim.py, autotest/ogr/ogr_basic_test.py, autotest/ogr/ogr_geos.py, autotest/ogr/ogr_pg.py, autotest/osr/osr_basic.py, autotest/pymod/gdaltest.py, autotest/pymod/ogrtest.py, autotest/utilities/test_gdalbuildvrt_lib.py, swig/include/python/gdal_python.i, swig/include/python/ogr_python.i, swig/include/python/osr_python.i, swig/include/python/python_exceptions.i
PR #6637 introduced a gdal/ogr/osr.ContextMgr() class, which I forgot when committing 26151f7ae405c5b213a823a316d30047d1283cb3 ("Python bindings: add gdal.enable_exceptions() context manager") in PR
So:
- remove this redundant gdal/ogr/osr.enable_exceptions()
- remove gdaltest/ogrtest.enable_exceptions()
- use ContextMgr() instead
- and make its useExceptions argument default to True
=> Python bindings: remove redundant exception managers

frmts/gtiff/cogdriver.cpp
This enables multithreading on the warp which greatly increases the speed of the COG creation.
fixes: #7478
> do you have an example test that checks Config changes, my grepping has turned up empty on GDAL_NUM_THREADS, the tests I found mostly just check the output to make sure its still the same, not that muliple threads were used?
> Do we need any docs updated for this?
> I dont think this changes the python docs
=> COG: set GDAL_NUM_THREADS to NUM_THREADS if its not already set

autotest/gdrivers/memmultidim.py, autotest/gdrivers/netcdf_multidim.py, autotest/gdrivers/zarr_driver.py, frmts/mem/memdataset.cpp, frmts/mem/memmultidim.h, frmts/netcdf/netcdfmultidim.cpp, frmts/zarr/zarr.h, frmts/zarr/zarr_array.cpp, frmts/zarr/zarr_group.cpp, frmts/zarr/zarrdriver.cpp, gcore/gdal.h, gcore/gdal_priv.h, gcore/gdalmultidim.cpp, swig/include/MultiDimensional.i
Resize an array to new dimensions.
Not all drivers may allow this operation, and with restrictions (e.g.
for netCDF, this is limited to growing of "unlimited" dimensions)
Resizing a dimension used in other arrays will cause those other arrays
to be resized.
Implemented in MEM, netCDF and ZARR drivers
=> Multidimensional API: add GDALMDArray::Resize() / GDALMDArrayResize() 

ogr/ogrsf_frmts/osm/ogrosmdatasource.cpp
Fixes a bug were the maximum key size was always just the length of the last key in the setting. This meant that any longer previous keys were never used.
=> osm: Fix handling of closed_ways_are_polygons setting in osmconf.ini

ogr/ogrsf_frmts/osm/ogrosmdatasource.cpp
Backport #7487
**Authored by:** @xabbu42
=> [Backport release/3.6] osm: Fix handling of closed_ways_are_polygons setting in osmconf.ini

autotest/ogr/ogr_pg.py, doc/source/drivers/vector/pg.rst, ogr/ogrsf_frmts/pg/ogr_pg.h, ogr/ogrsf_frmts/pg/ogrpgdatasource.cpp, ogr/ogrsf_frmts/pg/ogrpgdriver.cpp
Adds a `SKIP_VIEWS` open option to the Postgres driver to replace the undocumented `PG_SKIP_VIEWS` config option
=> PG: Add SKIP_VIEWS open option to replace PG_SKIP_VIEWS config option

doc/requirements.txt, doc/source/conf.py
Fix the search bar of the documentation. Right now the search box is looping forever because of JQuery `Uncaught ReferenceError: jQuery is not defined`. We had a similar problem in QGIS (https://github.com/qgis/pyqgis/issues/109). Hopefully this small PR should fix the problem
* OS: Debian Sid
=> Add jquery sphinx extension

frmts/gtiff/geotiff.cpp
I've verified that with thix fix the GeoTIFF referenced in #7484 once warped with gdalwarp overlays correctly on top of OSM
=> GTiff: correctly read GCPs from ArcGIS 9 .aux.xml when TIFFTAG_RESOLUTIONUNIT=3 (pixels/cm) (fixes #7484)

frmts/gtiff/geotiff.cpp
=> [Backport release/3.6] GTiff: correctly read GCPs from ArcGIS 9 .aux.xml when TIFFTAG_RESOLUTIONUNIT=3 (pixels/cm) (fixes #7484)

autotest/gcore/vrt_read.py, doc/source/drivers/raster/vrt.rst, frmts/vrt/vrtdataset.cpp
Add 'scale' and 'exponent' to allowed options for a "vrt:// connection.
Note this does not implement the case where 'scale' is include with no value as per '-scale' in gdal_translate. 
Discussion and summary of related PRs: #7477
=> VRT 'scale' and 'exponent' option for vrt:// connection

alg/llrasterize.cpp, autotest/alg/rasterize.py
CC @SebastienPeillet . Cf https://github.com/OSGeo/gdal/issues/7523. This PR seems to preserve the behaviour you modified per https://github.com/OSGeo/gdal/pull/6415, while fixing #7523. It is quite hard to find the appropriate epsilon to distinguish pure numerical inaccuracy from a geometry slightly touching a pixel edge...
=> Rasterize all touched: tighten(decrease) the tolerance to consider that edge of geometries match pixel obundaries (fixes #7523)

autotest/ogr/ogr_openfilegdb_write.py, ogr/ogrsf_frmts/openfilegdb/filegdbtable_write.cpp
=> [Backport release/3.6] OpenFileGDB: fix write corruption when re-using freespace slots in some editing scenarios (fixes #7504)

alg/llrasterize.cpp, autotest/alg/rasterize.py
=> [Backport release/3.6] Rasterize all touched: tighten(decrease) the tolerance to consider that edge of geometries match pixel obundaries (fixes #7523)

.travis.yml, doc/source/drivers/raster/netcdf.rst, doc/source/drivers/vector/pgdump.rst, frmts/netcdf/netcdfvirtual.cpp
Attempts to skip Travis runs for doc-only commits. Unfortunately I can't test this in a fork so I'll do so here.
#3529
=> CI: Make Travis skip doc-only commits

.github/workflows/linux_build.yml
This container is being pulled but was incorrectly omitted from the list of cache sources.
Adding this should prevent an unnecessary container rebuild in a feature branch on a fork for which a pull request has not yet been created.
=> CI: Use master container as cache for feature branches

autotest/gcore/vrt_read.py, doc/source/drivers/raster/vrt.rst, frmts/vrt/vrtdataset.cpp
Add 'outsize' to allowed options for a "vrt://" connection. 
Discussion and summary of related PRs:  #7477
=> VRT 'outsize' option for vrt:// connection

ogr/ogrutils.cpp
A small documentation fix, as I was confused by looking at the online docs for `OGRParseDate` assuming it wouldn't handle milliseconds. But it actually does that, for example as can be seen in the tests:
https://github.com/OSGeo/gdal/blob/75dccb1be8097a55a772385192bf55192d75a0f4/autotest/cpp/test_ogr.cpp#L482-L483
=> DOC: OGRParseDate does not ignore second decimal portion

.github/workflows/cmake_builds.yml
Some VM workers unexpectly link to OpenSSL from C:/Program Files/OpenSSL/lib/VC (at 1.1.1) but likely use headers of 3.1.0 from conda.
```
Found OpenSSL: optimized;C:/Program Files/OpenSSL/lib/VC/libcrypto64MD.lib;debug;C:/Program Files/OpenSSL/lib/VC/libcrypto64MDd.lib (found version "1.1.1t") found components: SSL Crypto
[...]
cpl_sha256.cpp.obj : error LNK2019: unresolved external symbol EVP_PKEY_get_size referenced in function CPL_RSA_SHA256_Sign
```
=> CI: fix build errors with openssl not coming from Conda; and use libjpeg-turbo

docker/util.sh
Docker 23 uses BuildKit by default on Linux,
but BuildKit prevents custom networks using
docker build --network, so disable BuildKit
for now.
This fixes the error:
ERROR: network mode "docker_build_gdal" not supported by buildkit - you can define a custom network for your builder using the network driver-opt in buildx create
when running `./ubuntu-small/build.sh --gdal master --proj master --platform linux/amd64` from the docker directory on Ubuntu 22.04 with Docker 23.0.3.
Could not find any.
* OS: Ubuntu 22.04
* Compiler: gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
=> docker/util.sh: avoid BuildKit on Docker 23

autotest/cpp/test_cpl.cpp, autotest/osr/osr_basic.py, autotest/osr/osr_basic_subprocess.py, ogr/ogr_proj_p.cpp, port/cpl_conv.cpp, port/cpl_conv.h
People expect PROJ_DATA / PROJ_LIB to be set through configuration options, whereas they only work as environment variables or when calling OSRSetPROJSearchPaths().
Make CPLSetConfigOption('PROJ_DATA', ...) to work by making it call OSRSetPROJSearchPaths()
=> Allow CPLSetConfigOption('PROJ_DATA', ...) to work by making it call OSRSetPROJSearchPaths()

gcore/gdal.h, ogr/ogr_core.h, ogr/ogrsf_frmts/openfilegdb/ogropenfilegdbdriver.cpp, ogr/ogrsf_frmts/openfilegdb/ogropenfilegdblayer_write.cpp, swig/include/ogr.i
And use ALTER_ALTERNATIVE_NAME_FLAG to determine whether field alias should be updated, not ALTER_NAME_FLAG
=> Add ALTER_ALTERNATIVE_NAME_FLAG for use changing a field's alternative name 

swig/python/gdal-utils/osgeo_utils/gdal2tiles.py
=> [Backport release/3.6] gdal2tiles: update 'ol-layerswitcher' widget to v4.1.1 (fixes #7544)

autotest/ogr/ogr_gpkg.py, ogr/ogrsf_frmts/gpkg/ogrgeopackagedatasource.cpp, ogr/ogrsf_frmts/gpkg/ogrgeopackagetablelayer.cpp
Note that the GeoPackage specifications for the gpkg_data_columns table specify that both a field "name" and field "title" can be present. The specifications do not further elaborate on what the intended differentiation is between these values. Accordingly, we set the field alias using either the name value or the title value, depending on which has been populated in the GeoPackage (and which isn't just a direct copy of the column name)
* OS:
* Compiler:
=> [gpkg] Set field alternative names using name attribute from gpkg_data_columns table

autotest/gcore/cog.py, gcore/tilematrixset.cpp
Increases the maximum zoom level allowed for GoogleMapsCompatible COGs from 24 to 30.
#7585 
* OS:
* Compiler:
=> COG: Allow creating GoogleMapsCompatible COGs with zoom level > 24 (fixes #7585)

apps/ogrinfo_lib.cpp, autotest/cpp/test_ogr.cpp, autotest/ogr/ogr_gpkg.py, ogr/ogr_api.h, ogr/ogr_feature.h, ogr/ogrfielddefn.cpp, ogr/ogrsf_frmts/generic/ogreditablelayer.cpp, ogr/ogrsf_frmts/generic/ogremulatedtransaction.cpp, ogr/ogrsf_frmts/gpkg/ogrgeopackagetablelayer.cpp, swig/include/ogr.i
Adds the API framework for handling field comments for OGR layers
And support reading comments for GPKG fields, using "description" from gpkg_data_columns.
(Write capacity for field comments will be added to GPKG driver in a follow up PR)
=> Add optional comment to OGRFieldDefn, read for gpkg layers

.github/workflows/cmake_builds.yml
Recent builds fails with
```
/usr/local/Cellar/libkml/1.3.0_1/include/kml/base/xml_element.h:31:10: fatal error: 'boost/intrusive_ptr.hpp' file not found
```
This is due to this change in the libkml recipee
https://github.com/Homebrew/homebrew-core/pull/128140 which makes boost a build-only dependency.
Explicit installation of boost is now needed to use libkml headers
=> CI: build_mac: fix issue with libkml

swig/include/csharp/gdal_csharp.i
Initially, there was a defined wrapper only for gdal_wrap function. Other functions were not implemented, and a custom-defined method joggling with pointers is the only option to use a utility. Some older types, like `SWIGTYPE_p_p_GDALDatasetShadow` are not required with new GDAL versions and can be replaced by high-level C# methods.
This will bring more clarity into using specified functions in .NET environment. 
Resolves #7152, resolves #813, resolves #1436
Related to https://github.com/MaxRev-Dev/gdal.netcore/issues/97
=> C# Bindings: Add missing GDAL wrappers

autotest/requirements.txt, ogr/ogrsf_frmts/tiger/ogr_tiger.h
=> [Backport release/3.6] Tiger: fix compiler warning with clang 16.0.0 and autotest/requirements.txt

autotest/gdrivers/netcdf.py, doc/source/drivers/vector/netcdf.rst, frmts/netcdf/netcdflayer.cpp
The driver writes the following attributes for each OGR fields / netCDF variables:
[...]
-  *standard_name*": (GDAL >= 3.7) OGR field alternative name, if it is compatible of the convention for the value of standard_name.
-  *long_name*: (GDAL >= 3.7) OGR field comment, or if not set, OGR field alternative name if it is not compatible of standard_name, or "Field {ogr_field_name}" otherwise.
CC @mdsumner : turning a Twitter joke into code :-)
=> netCDF vector: add support for getting/setting alternative name and comment

ogr/ogr_xerces.cpp
(fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=58029)
=> OGRXercesInstrumentedMemoryManager::deallocate(): avoid harmless unsigned integer overflow

doc/source/development/building_from_source.rst
=> fix typo on libarchive cmake flag

gcore/overview.cpp
Implements the SQUARE function with an AVX2 intrinsic to avoid build errors.
Fixes #7625. Fixes gcore build error in Windows x64 build with AVX2 enabled.
#7625 
* OS: Windows 10
* Compiler: MSVC for Visual Studio 17 2022
=> gcore: Fix for Windows x64 build with AVX2 enabled (fixes #7625)

autotest/ogr/ogr_gpkg.py, doc/source/drivers/vector/gpkg.rst, ogr/ogrsf_frmts/gpkg/ogrgeopackagedatasource.cpp, ogr/ogrsf_frmts/gpkg/ogrgeopackagetablelayer.cpp
Execution time can be ~ 1.5x faster.
Before:
```
$ time ogrinfo nz-building-outlines.gpkg -sql "select count(*) from \"nz-building-outlines\" where st_maxx(geometry)>=1500000 and st_maxy(geometry)>= 5200000 and st_minx(geometry) <=1800000 and st_miny(geometry) <= 5800000" -al -q
Layer name: SELECT
OGRFeature(SELECT):0
count(*) (Integer) = 701300
real	0m0,909s
user	0m0,633s
sys	0m0,276s
```
After:
```
$ time ogrinfo nz-building-outlines.gpkg -sql "select count(*) from \"nz-building-outlines\" where ST_EnvelopesIntersects(geometry, 1500000, 5200000 ,1800000 ,5800000)" -al -q
Layer name: SELECT
OGRFeature(SELECT):0
count(*) (Integer) = 701300
real	0m0,605s
user	0m0,310s
sys	0m0,290s
```
=> GPKG: add ST_EnvIntersects() for faster spatial filtering when there is no spatial index

.github/workflows/linux_build.yml
Use cached containers for pull requests and pushes to a fork, unless the commit message includes the text "[skip cache]"
Only push a container to the container registry if the build succeeded.
#7592
=> CI: Rebuild containers for pushes to OSGeo/gdal

autotest/ogr/ogr_sql_test.py, swig/include/python/docs/gdal_dataset_docs.i, swig/include/python/docs/ogr_datasource_docs.i, swig/include/python/gdal_python.i, swig/include/python/ogr_python.i, swig/python/CMakeLists.txt
```
ExecuteSQL(self, statement, spatialFilter: ogr.Geometry = None, dialect: Optional[str] = "", keep_ref_on_ds=False) -> ogr.Layer
Example 1
---------
with ds.ExecuteSQL("SELECT * FROM layer") as lyr:
print(lyr.GetFeatureCount())
Example 2
---------
def get_sql_lyr():
return gdal.OpenEx("test.shp").ExecuteSQL("SELECT * FROM test", keep_ref_on_ds=True)
with get_sql_lyr() as lyr:
print(lyr.GetFeatureCount())
```
=> Python bindings: make Dataset.ExecuteSQL() usable as a context manager to automatically release the layer (fixes #7459)

autotest/ogr/ogr_gpkg.py, ogr/ogrsf_frmts/gpkg/ogr_geopackage.h, ogr/ogrsf_frmts/gpkg/ogrgeopackagedatasource.cpp, ogr/ogrsf_frmts/gpkg/ogrgeopackagetablelayer.cpp
Refs https://github.com/opengisch/QgisModelBaker/issues/531
If a table has several geometry coluns in its DDL and is declared as many times in a modified gpkg_geometry_columns whose uk_gc_table_name unique constraint has been modified to have (table_name, column_name) as the unique constraint, then instantiate as many OGR layers has geometry columns.
e.g with the following content
```
INSERT INTO gpkg_geometry_columns VALUES('test','poly','POLYGON',0,0,0)
INSERT INTO gpkg_geometry_columns VALUES('test','pt','POINT',0,0,0)
CREATE TABLE "test" ( "ogc_fid" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "poly" POLYGON, "pt" POINT, "area" REAL, "eas_id" INTEGER, "prfedea" TEXT(16))
```
the driver will report 2 layers: "test (poly)" and "test (pt)" In "test(poly)", the "pt" geometry column will be …
=> GPKG: minimum (read) support for non-standard multiple geometry columns per table

doc/source/user/raster_data_model.rst
Include Int8 in raster data model documentation
I can't speak authoratively about the broader context and implications ...
=> raster_data_model.rst: include new Int8

autotest/gcore/tiff_write.py, autotest/gdrivers/jp2openjpeg.py, frmts/vrt/vrtdataset.cpp, frmts/vrt/vrtdriver.cpp, frmts/vrt/vrtsources.cpp
(https://lists.osgeo.org/pipermail/gdal-dev/2023-April/057141.html)
as well as an issue when serializing such VRT
=> VRT: fix warning regarding with OpenShared with vrt://http://example.com/test.jp2 with the JP2OpenJPEG driver

autotest/conftest.py, autotest/gcore/cog.py, autotest/gcore/mask.py, autotest/gcore/pam.py, autotest/gcore/tiff_ovr.py, autotest/gcore/tiff_read.py, autotest/gcore/tiff_write.py, autotest/gdrivers/gpkg.py, autotest/gdrivers/isis.py, autotest/gdrivers/jp2openjpeg.py, autotest/gdrivers/jpeg.py, autotest/gdrivers/jpegxl.py, autotest/gdrivers/mrf.py, autotest/gdrivers/netcdf.py, autotest/gdrivers/vrtmask.py, autotest/gdrivers/webp.py, autotest/ogr/ogr_openfilegdb_write.py, autotest/ogr/ogr_parquet.py, autotest/osr/osr_basic.py, autotest/osr/osr_compd.py, autotest/osr/osr_ct.py, autotest/osr/osr_proj4.py, autotest/pymod/gdaltest.py, autotest/utilities/test_gdal_translate_lib.py, autotest/utilities/test_gdalwarp.py, autotest/utilities/test_gdalwarp_lib.py, autotest/utilities/test_ogr2ogr_lib.py, cmake/template/pytest.ini.in
Use a single pattern for conditional skipping, as discussed in #7436
#7436
=> autotest: Use pytest.mark instead of skip decorators

doc/source/user/virtual_file_systems.rst, port/cpl_http.cpp
- :decl_configoption:`GDAL_HTTP_SSLCERT` = filename. Filename of the the SSL client certificate. Cf https://curl.se/libcurl/c/CURLOPT_SSLCERT.html
- :decl_configoption:`GDAL_HTTP_SSLCERTTYPE` = string. Format of the SSL certificate: "PEM" or "DER". Cf https://curl.se/libcurl/c/CURLOPT_SSLCERTTYPE.html
- :decl_configoption:`GDAL_HTTP_SSLKEY` = filename. Private key file for TLS and SSL client certificate. Cf https://curl.se/libcurl/c/CURLOPT_SSLKEY.html
- :decl_configoption:`GDAL_HTTP_KEYPASSWD` = string. Passphrase to private key. Cf https://curl.se/libcurl/c/CURLOPT_KEYPASSWD.html
Addresses https://lists.osgeo.org/pipermail/gdal-dev/2023-April/057146.html
(note: only compiled tested by me)
=> /vsicurl/ / HTTP support: add options to support SSL client certificates

frmts/ogcapi/gdalogcapidataset.cpp, gcore/tilematrixset.cpp
The OGC API Tiles dataset was not working as expected.
A complete document was being passed to TileMatrixSet::parse, which was causing a series of issues:
- the comparisons with the well-known uris were never verified
- all the other ways of retrieving a TMS were failing and it was falling back to reading TMS from a file (which had the entire document in the filename causing buffer overflow)
The well-known URI was being compared to a word/name, rather than an uri. I added support to two of the most popular ones, but we could add more.
Submitted changes:
- Passed uri to TileMatrixSet::parse
- updated uris of well-known tile matrix sets
With these changes, I can read raster and vector tiles from these urls:
`gdalinfo -oo API=TILES --config CPL_DEBUG ON …
=> - Added fixes for the OGC API Tiles driver

autotest/pymod/gdaltest.py
Fixes `gdaltest.download_file` so that files are completely downloaded even if the size cannot be determined from the `content-length` header. An example file that is not correctly downloaded is  `http://www2.census.gov/geo/tiger/tiger2006se/AL/TGR01001.ZIP` in `ogr/ogr_tiger.py`.
None
=> autotest: Fix incomplete downloads

autotest/ogr/ogr_sxf.py
This test prints actual and expected values whether not there is an error. We can just let pytest print the differences if the `assert` fails.
=> ogr_sxf.py: Quiet debugging output

autotest/ogr/ogr_parquet.py, autotest/pymod/gdaltest.py, autotest/utilities/test_gdalinfo_lib.py, autotest/utilities/test_gdalmdiminfo_lib.py, autotest/utilities/test_ogrinfo_lib.py
Removes duplicated JSON validation code.
Adds error handling to skip tests instead of failing if external resources in the JSON schema cannot be resolved.
Example spurious failure: https://github.com/dbaston/gdal/actions/runs/4876661250/jobs/8700425769#step:16:4680
Output with this PR:
```
utilities/test_gdalinfo_lib.py ✓s✓✓✓✓✓✓✓✓✓✓✓                                                                                                                            100% ██████████
=============================================================================== short test summary info ================================================================================
SKIPPED [1] autotest/utilities/test_gdalinfo_lib.py:62: Failed to resolve remote reference in schema
```
None
=> autotest: Consolidate JSON validation logic, catch timeout errors

doc/source/drivers/raster/lcp.rst
Added band names used for looking up metadata, projection handling if .prj file is present, and information about no data value. URLs were updated.
=> Doc: update format description for LCP raster

doc/Makefile, doc/source/development/dev_documentation.rst
Small change to clarify the journey from Doxygen markup to HTML documentation.
None
=> Doc: Add doxygen target to doc Makefile

autotest/gcore/basic_test.py, autotest/ogr/ogr_basic_test.py, autotest/ogr/ogr_shape.py, swig/include/python/docs/gdal_dataset_docs.i, swig/include/python/docs/ogr_datasource_docs.i, swig/include/python/gdal_python.i, swig/include/python/ogr_python.i
Allows the OGRDataSource proxy to serve as a context manager, so instead of:
```
ds = drv.CreateDataSource(fname)
lyr = ds.CreateLayer('test', geom_type = ogr.wkbPoint)
f = ogr.Feature(lyr.GetLayerDefn())
f.SetGeometry(ogr.CreateGeometryFromWkt("POINT (0 0)"))
lyr.CreateFeature(f)
del ds  # or ds = None, or ds.Destroy(), or ds.FlushCache()
```
(one of the "gotchas" documented at https://gdal.org/api/python_gotchas.html#saving-and-closing-datasets-datasources)
You can do 
```
with drv.CreateDataSource(fname) as ds:
lyr = ds.CreateLayer('test', geom_type = ogr.wkbPoint)
f = ogr.Feature(lyr.GetLayerDefn())
f.SetGeometry(ogr.CreateGeometryFromWkt("POINT (0 0)"))
lyr.CreateFeature(f)
```
I'm guessing there is a reason this hasn't been done...in which case this PR can document that reason :)
=> Python bindings: Use ogr.DataSource and gdal.Dataset as context managers

.github/workflows/code_checks.yml, autotest/ogr/ogr_geojson.py, ogr/ogrsf_frmts/geojson/libjson/GDAL_README.txt, ogr/ogrsf_frmts/geojson/libjson/json_object.c, ogr/ogrsf_frmts/geojson/libjson/json_tokener.c, ogr/ogrsf_frmts/geojson/libjson/json_util.c, scripts/clang-format.sh
=> [Backport release/3.7] Fix parsing of floating-point numbers in JSON with internal libjson-c on Windows

autotest/gcore/cog.py, autotest/gcore/tiff_write.py, doc/source/drivers/raster/cog.rst, doc/source/drivers/raster/gtiff.rst, frmts/gtiff/geotiff.cpp, frmts/gtiff/gtiffdataset_read.cpp
Updating a COG file generally breaks part of the optimizations, but still produce a valid GeoTIFF file. Starting with GDAL 3.8, to avoid undesired loss of the COG characteristics, opening such a file in update mode will be rejected, unless the IGNORE_COG_LAYOUT_BREAK open option is also explicitly set to YES.
Previously, we already got a warning that optimizations were broken, but this was after the fact, which might be frustrating for the user that needs to regenerate the COG.
CC @vincentsarago good idea ? bad idea ?
=> COG: only update mode if the IGNORE_COG_LAYOUT_BREAK=YES open option is specified (fixes #7735)

autotest/gcore/hdf4multidim.py, autotest/gdrivers/memmultidim.py, autotest/gdrivers/netcdf.py, autotest/gdrivers/netcdf_multidim.py, autotest/gdrivers/zarr_driver.py, autotest/ogr/ogr_fgdb.py, autotest/ogr/ogr_openfilegdb.py, frmts/mem/memdataset.cpp, frmts/mem/memmultidim.h, frmts/netcdf/netcdfmultidim.cpp, frmts/zarr/zarr.h, frmts/zarr/zarr_array.cpp, frmts/zarr/zarr_attribute.cpp, frmts/zarr/zarr_group.cpp, frmts/zarr/zarr_sharedresource.cpp, frmts/zarr/zarr_v2_array.cpp, frmts/zarr/zarr_v2_group.cpp, frmts/zarr/zarr_v3_array.cpp, frmts/zarr/zarr_v3_group.cpp, gcore/gdal.h, gcore/gdal_priv.h, gcore/gdalmultidim.cpp, swig/include/MultiDimensional.i, swig/include/python/gdal_python.i
- Python bindings: make gdal.Group.GetGroupNames() and GetMDArrayNames() return an empty list instead of None
- Multidim API: add DeleteGroup(), DeleteMDArray(), DeleteAttribute() methods in C/C++/SWIG API
- MEM multidim: implement DeleteGroup(), DeleteMDArray(), DeleteAttribute()
- netCDF multidim: implement DeleteAttribute()
- Zarr multidim: implement DeleteGroup(), DeleteMDArray(), DeleteAttribute()
=> Multidim API: add methods to delete groups, arrays and attributes

gdal/ogr/ogrsf_frmts/cad/libopencad/dwg/r2000.cpp
Fixes build of the 3.1 branch on Ubuntu 22.04.2 LTS
with gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
=> Add missing limits include

autotest/ogr/data/dxf/attrib.dxf, autotest/ogr/ogr_dxf.py, ogr/ogrsf_frmts/dxf/ogrdxflayer.cpp
Constant ATTDEFs are used in the construction of dynamic blocks in AutoCAD.
* OS:
* Compiler:
=> DXF: Show constant ATTDEFs as text

autotest/ogr/data/dxf/attrib.dxf, autotest/ogr/ogr_dxf.py, ogr/ogrsf_frmts/dxf/ogrdxflayer.cpp
Backport #7723
**Authored by:** @atlight
=> [Backport release/3.7] DXF: Show constant ATTDEFs as text

autotest/pyscripts/test_gdal_calc.py, swig/python/gdal-utils/osgeo_utils/gdal_calc.py
It allows specifying `--NoDataValue=none`, which was previously failing due to `type=float` in the `parser.add_argument` call.
=> gdal_calc.py: allow "none" or a float for --NoDataValue

autotest/pyscripts/test_gdal_calc.py, swig/python/gdal-utils/osgeo_utils/gdal_calc.py
Backport #7793
**Authored by:** @waldner
=> [Backport release/3.7] gdal_calc.py: allow "none" or a float for --NoDataValue

ogr/ogrsf_frmts/shape/shpopen.c
Backport #7774
**Authored by:** @agiudiceandrea
=> [Backport release/3.7] [Shapefile] SHPRestoreSHX: update SHX content length even if an error occurred

frmts/netcdf/netcdfdataset.cpp, frmts/netcdf/netcdfdataset.h
Helps for https://lists.osgeo.org/pipermail/gdal-dev/2023-May/057209.html
The time dimension is unlimited, and is the one used to determine GDAL bands. Retrieving the values of the time variable for the metadata requires scanning a lot of places within the file, which is network access unfriendly.
So:
- do not set the NETCDF_DIM_xxxx_VALUES dataset metadata item for such use case
- and defer loading of the NETCDF_DIM_xxxx band metadata item until it is really required
All that combines enables access of a given band with a more reasonable amount of HTTP access.
- 85 requests for ``gdalwarp "vrt://netCDF:\"/vsicurl/http://localhost:8080/tos_day_ACCESS1-3_rcp85_r1i1p1_20560101-20651231.nc\":tos?bands=1" out2.tif -overwrite``
- 19 requests for same invokation with GDAL_NETCDF_BOTTOMUP=NO env …
=> netCDF: optimize loading of network located dataset with unlimited dimension

autotest/gcore/tiff_ovr.py, autotest/gcore/tiff_write.py, frmts/gtiff/gtiffdataset.cpp, frmts/gtiff/gtiffrasterband.cpp, frmts/gtiff/gtiffrasterband_read.cpp, gcore/gdal_priv.h, perftests/gtiff_multi_ds_parallel_write.py, port/CMakeLists.txt, port/cpl_vsi_mem.cpp
This avoids less contention on the block cache mutex and saves memory
copies, particular when writing dataset-level RasterIO() with a buffer
with data for all bands, and with a pixel interleaving.
The optimization triggers if the following conditions are met:
- (xsize, ysize) = (bufxsize, bufysize), ie no resampling
- origin (xoff, yoff) of buffer to write is aligned on a tile boundary
- end (xoff+xsize, yoff+ysize) of buffer is aligned on tile boundary or
raster right/bottom
- only for bit depth = 8, 16, 32, 64 or 128
- the block cache for the bands to considered has not been initialized
at all
- and for dataset level write with pixel interleaving, all bands are
written at once.
The visible side effects of this optimization are hopefully few, but one
particular case exhibited by the …
=> [Perf improvement] GTiff: avoid using block cache when writing whole blocks

apps/gdallocationinfo.cpp
=> [Backport release/3.7] gdallocationinfo: set exit code to 1 as soon as one coordinate is off the file (fixes #7759)

swig/python/CMakeLists.txt
=> [Backport release/3.7] Python bindings: do not pass deprecated -py3 SWIG switch for SWIG >= 4.1
