- doc/source/api/index.rst
The R package 'rgdal' will be retired in 2023 with breaking changes beginning in June. This is documented here:
https://cran.r-project.org/web/packages/rgdal/index.html
and
https://r-spatial.org/r/2023/05/15/evolution4.html
A  new R package 'gdalraster' provides bindings to the Raster API. This PR updates the URL for R bindings to point to 'gdalraster' on CRAN:
https://cran.r-project.org/web/packages/gdalraster/index.html
> Doc: update URL for R bindings

- doc/source/drivers/raster/gpkg.rst
stray backticks in the gpkg.rst
I'm not sure if the embedded 
```
```text`` <url>` 
```
is meant to be expressed in a different way? I just removed the internal pairs.
> gpkg.rst stray backticks

- frmts/adrg/adrgdataset.cpp
> [Backport release/3.7] Fix gcc 13.1.1 -Werror=array-bounds false positive

- .github/workflows/ubuntu_18.04/test.sh
- autotest/ogr/ogr_mysql.py
- ogr/ogrsf_frmts/mysql/ogr_mysql.h
- ogr/ogrsf_frmts/mysql/ogrmysqldatasource.cpp
- ogr/ogrsf_frmts/mysql/ogrmysqllayer.cpp
- ogr/ogrsf_frmts/mysql/ogrmysqlresultlayer.cpp
- ogr/ogrsf_frmts/mysql/ogrmysqltablelayer.cpp
- make sure that OGRLayer::GetSpatialRef() == OGRGeomFieldDefn::GetSpatialRef()
- add missing dataset capabilities
- re-enable ogr_mysql_24 test
> MySQL: fix compliance issues with test_ogrsf

- alg/gdalwarper.cpp
- autotest/utilities/test_gdalwarp_lib.py
> [Backport 3.7] GDALWarpResolveWorkingDataType(): take into account both source and target dataset

- autotest/ogr/ogr_tiledb.py
- frmts/tiledb/tiledbsparse.cpp
> [Backport release/3.7] TileDB: FillPrimitiveListArray(): fix data corruption with spatial filter (Coverity CID 1512587, 1512576)

- doc/source/programs/gdal_merge.rst
- doc/source/programs/gdal_translate.rst
- doc/source/programs/gdalwarp.rst
- doc/source/programs/ogrinfo.rst
- doc/source/programs/options/srs_def.rst
- doc/source/user/configoptions.rst
Migrates program notes from https://trac.osgeo.org/gdal/wiki/UserDocs, except for https://trac.osgeo.org/gdal/wiki/UserDocs/Gdal2Tiles (would take me some time to understand those notes)
> Doc: Migrate remaining program notes from wiki

- port/cpl_vsi_virtual.h
Fixes the build if only `cpl_vsi_virtual.h` is included.
* OS: Debian 11
* Compiler: gcc 10.2.1
> Add missing include <memory>

- autotest/gdrivers/zarr_driver.py
- frmts/zarr/zarr_v3_array.cpp
(fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=59607)
> ZarrV3: fix crash on invalid shape/chunk_shape values (master only)

- swig/include/java/gdal_java.i
- swig/include/java/typemaps_java.i
- swig/java/apps/GDALTestIO.java
This commit extends the ReadRaster and WriteRaster methods in the Java API by changes to the SWIG definitions in gdal_java.i.
This is my first commit and is done by inspection. The changes are straightforward. Please let me know what things I need to continue to do. Tests? If so how? Do you need some kind of documentation? Please advise. Thanks.
> SWIG JAVA: add Read/WriteRaster abilities for GDT_UInt64 & GDT_Int64

- port/cpl_port.h
- port/cpl_vsisimple.cpp
> [Backport release/3.7] Fix build error with MSYS64 UCRT64 with gcc 13 (fixes #7909)

- .github/workflows/ubuntu_20.04/Dockerfile.ci
- apps/gdalmdiminfo_lib.cpp
- autotest/gdrivers/tiledb_multidim.py
- doc/source/drivers/raster/tiledb.rst
- docker/ubuntu-full/Dockerfile
- frmts/gtiff/libtiff/tif_lzw.c
- frmts/mem/memmultidim.h
- frmts/tiledb/CMakeLists.txt
- frmts/tiledb/tiledbcommon.cpp
- frmts/tiledb/tiledbdense.cpp
- frmts/tiledb/tiledbheaders.h
- frmts/tiledb/tiledbmultidim.cpp
- frmts/tiledb/tiledbmultidim.h
- frmts/tiledb/tiledbmultidimarray.cpp
- frmts/tiledb/tiledbmultidimattribute.cpp
- frmts/tiledb/tiledbmultidimattributeholder.cpp
- frmts/tiledb/tiledbmultidimgroup.cpp
- gcore/gdal_priv.h
- gcore/gdalmultidim.cpp
It requires GDAL to be built and run against TileDB >= 2.15 (for older
versions, it is just disabled)
The driver supports:
- creating and reading groups and subgroups
- creating and reading multidimensional dense arrays with a numeric data type
- creating and reading numeric or string attributes in groups and arrays
- storing an indexing array of a dimension as a TileDB dimension label
The multidimensional API supports reading dense arrays created by the classic
raster API of GDAL.
CC @normanb
> TileDB: add read/write multidimensional support

- apps/gdal_translate_lib.cpp
- autotest/utilities/test_gdal_translate.py
- autotest/utilities/test_gdal_translate_lib.py
- doc/source/programs/gdal_translate.rst
The warning suggests to use ``-scale 0 1 <offset> <offset+scale>``
- also improves doc with that issue and suggestion
- and error out if -scale and -unscale are specified
> gdal_translate: emit warning when -a_scale/-a_offset + -unscale is specified (fixes #7863)

- .github/workflows/linux_build.yml
- .github/workflows/ubuntu_20.04/test.sh
Pass `-j` flag to `ctest` in Linux build configurations that use `ctest` instead of calling `pytest` directly.
> CI: Run ctest in parallel for most Linux builds

- apps/CMakeLists.txt
- apps/nearblack_bin.cpp
- apps/nearblack_lib.cpp
- apps/nearblack_lib.h
- apps/nearblack_lib_floodfill.cpp
- autotest/utilities/test_nearblack_lib.py
- doc/source/programs/nearblack.rst
- swig/include/python/gdal_python.i
This algorithm, based on https://en.wikipedia.org/wiki/Flood_fill#Span_filling, works with concave areas, which the traditional -alg twopasses algorithm didn't work well.
Refs #6264
> Nearblack: add "-alg floodfill" to select a flood fill algorithm

- autotest/ogr/ogr_gtfs.py
- ogr/ogrsf_frmts/gtfs/ogrgtfsdriver.cpp
Fixes the date parsing in the GTFS importer. Previously dates in 2023 were imported as 2223.
None
* OS:  n/a
* Compiler: n/a
> GTFS: Fix date parsing

- fuzzers/build.sh
Avoids running into memory leak of https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=47258 that was fixed in internal libpng per f19f56b4f126421ef3bcd7cf6490c39431933dde
> ossfuzz builds: use internal libpng

- autotest/gcore/gcps2geotransform.py
- autotest/gcore/misc.py
- autotest/gcore/tiff_write.py
- autotest/gcore/vsioss.py
- autotest/gdrivers/ecrgtoc.py
- autotest/gdrivers/gdalhttp.py
- autotest/gdrivers/gif.py
- autotest/gdrivers/grib.py
- autotest/gdrivers/mbtiles.py
- autotest/gdrivers/nitf.py
- autotest/gdrivers/pcidsk.py
- autotest/gdrivers/wms.py
- autotest/ogr/ogr_cad.py
- autotest/ogr/ogr_feature.py
- autotest/ogr/ogr_gml_geom.py
- autotest/ogr/ogr_gpkg.py
- autotest/ogr/ogr_mem.py
- autotest/ogr/ogr_ngw.py
- autotest/ogr/ogr_refcount.py
- autotest/ogr/ogr_rfc35_mitab.py
- autotest/osr/osr_compd.py
- autotest/osr/osr_esri.py
- autotest/osr/osr_pci.py
- autotest/osr/osr_proj4.py
- autotest/pymod/gdaltest.py
- autotest/pyscripts/test_gdal_ls_py.py
- autotest/utilities/test_gdal_translate.py
- autotest/utilities/test_gdal_translate_lib.py
- autotest/utilities/test_gdalwarp.py
- autotest/utilities/test_gdalwarp_lib.py
Removes `gdaltest.post_reason`, largely by moving the information it would provide into `assert` statements.
https://github.com/OSGeo/gdal/issues/7573 is resolved by this PR.
> autotest: remove gdaltest.post_reason

- autotest/ogr/ogr_ogrtest.py
- autotest/pymod/ogrtest.py
Add "pointwise" flag to skip GEOS topological equality testing. This may be needed in some cases where it is important to assert a specific ring ordering or orientation.
Improve assertion messages by allowing pytest to format the differences between failed vertices, and printing the entire WKT for the actual and expected geometries.
Rename internal variables for clarity.
https://github.com/OSGeo/gdal/pull/7945#discussion_r1230993442
> autotest: Enhancements to ogrtest.check_feature_geometry

- doc/source/user/configoptions.rst
- gcore/gdalproxypool.cpp
This relaxes the VRT pool size clamping so it doesn't get reset to 100 when configured to be over 1000 (or less than 2).
#7977
> GDALDatasetPool: Make VRT pool size clamping more lenient (#7977)

- autotest/gcore/basic_test.py
- autotest/ogr/ogr_basic_test.py
- swig/include/python/gdal_python.i
- swig/include/python/ogr_python.i
Modify gdal.Dataset to track gdal.Band objects it creates. When
gdal.Dataset closes, extant gdal.Band objects will be invalidated. If an
invalidated gdal.Band object is used, it will throw an exception instead
of creating a segfault.
I think this is the approach described in https://github.com/OSGeo/gdal/pull/7697#issuecomment-1535461854. I have a little hesitation about the list of references in `Dataset` growing without bound. This could be avoided by having bands cleanup their own references in Dataset (if they go out of scope first) or by having `GetRasterBand` return the same `Band` object if it is called multiple times with the same index.
The exception thrown when an invalidated `Band` is used is uninformative (`TypeError: in method 'Band_Checksum', argument 1 of type …
> Python bindings: Invalidate band refs when dataset closes

- autotest/gcore/vsicurl_streaming.py
Skips a test that I sometimes see failing, but only on Travis graviton2
https://app.travis-ci.com/github/OSGeo/gdal/jobs/604580643#L20341
> autotest: skip test_vsicurl_streaming_1 on Travis

- autotest/ogr/data/testograpispy.py
- autotest/ogr/ogr_basic_test.py
- swig/include/ogr.i
Increments reference count on `OGRFeatureDefn` so that a layer definition can be accessed without segfaulting after the layer has been destroyed.
This took some trial and error to figure out so I was a bit skeptical until I realized it is an independent rediscovery of https://github.com/OSGeo/gdal/commit/36700d390937c409f91a72fc0d217a37077ecbde
> SWIG: Increment FeatureDefn ref count on ogr.Layer.GetLayerDefn()

- autotest/cpp/CMakeLists.txt
- autotest/cpp/test_ogr_organize_polygons.cpp
- ogr/ogrgeometryfactory.cpp
Adds some tests for `OGRGeometryFactory::organizePolygons`. These are not exhaustive but document the basic behavior as well as some edge cases.
I commented out asserts that I would have expected to pass but do not. There are two categories of these:
1. The `pbIsValidGeometry` parameter does not behave how I would expect. It is described as "value will be set TRUE if result is valid or FALSE otherwise", but there are a number of situations where this value is `TRUE` but the result is invalid, e.g.:
- `organizePolygons` was called with a single invalid input
- `organizePolygons` was called with a method that does not perform topological validation
- `organizePolygons` was called with a method that performs topological validation, but the invalidity is not detected because …
> autotest: Add some tests for OGRGeometryFactory::organizePolygons

- swig/include/python/osr_python.i
- swig/python/modify_cpp_files.cmake
Refs #4907
Works around https://github.com/swig/swig/issues/2638 and https://github.com/swig/swig/issues/2037#issuecomment-874372082 to avoid the ""swig/python detected a memory leak of type 'OSRSpatialReferenceShadow *', no destructor found." error message of https://github.com/OSGeo/gdal/issues/4907 The issue is that starting with SWIG 4.1, the SWIG_Python_DestroyModule(), which is run in the gdal module (since __init__.py loads gdal in first), removes the destructor on the OGRSpatialReferenceShadow type (among others), which prevents full free of object of those type.
The following hack just makes SWIG_Python_DestroyModule() a no-op, which will leak a bit of memory, but anyway SWIG currently can only free one single SWIG module, so we had already memleaks
To be revisted if above …
> Python bindings: works around issue with SWIG 4.1 related to module unloading

- autotest/ogr/ogr_gml_read.py
- doc/source/drivers/vector/gml.rst
- ogr/ogrsf_frmts/gml/gmlhandler.cpp
- ogr/ogrsf_frmts/gml/gmlreaderp.h
- ogr/ogrsf_frmts/gml/ogrgmldatasource.cpp
- ogr/ogrsf_frmts/gml/ogrgmldriver.cpp
Fixes https://github.com/OSGeo/gdal/issues/7947
That capability was added by default in #7133, but there are use cases (like reading XPlannung datasets) where this is desirable, so make it available only if requested with the new USE_BBOX=YES open option.
> GML: add a USE_BBOX=YES open option to allow using gml:boundedBy as feature geometry

- swig/include/python/osr_python.i
- swig/python/modify_cpp_files.cmake
> [Backport release/3.7] Python bindings: works around issue with SWIG 4.1 related to module unloading

- autotest/ogr/ogr_gml_read.py
- ogr/ogrsf_frmts/gml/gmlhandler.cpp
- ogr/ogrsf_frmts/gml/gmlreaderp.h
- ogr/ogrsf_frmts/gml/ogrgmldatasource.cpp
- ogr/ogrsf_frmts/gml/ogrgmldriver.cpp
> [Backport release/3.7] GML: add a USE_BBOX=YES open option to allow using gml:boundedBy as feature geometry

- doc/source/development/rfc/rfc45_virtualmem.rst
Third code section under SWIG bindings for RFC45 is missing a closing docstring quote, making it render wrong and harder to read.
https://gdal.org/development/rfc/rfc45_virtualmem.html#swig-bindings
None
None?
> Fix missing quotes in RFC45 SWIG bindings

- autotest/conftest.py
Removes a global configuration option setting from `conftest.py`. It is already set where needed at https://github.com/OSGeo/gdal/blob/6e9103bd5acb1ff8da305c4e77fa30335ffa3b70/autotest/gdrivers/ecw.py#L116
> autotest: remove global setting of ECW_DO_NOT_RESOLVE_DATUM_PROJECTION

- autotest/gcore/colortable.py
- autotest/gcore/gdal_stats.py
- autotest/gcore/hfa_write.py
- autotest/gcore/pam.py
- autotest/gcore/rat.py
- autotest/gcore/tiff_read.py
- autotest/gcore/vsizip.py
- autotest/gdrivers/netcdf.py
- autotest/ogr/ogr_sql_rfc28.py
- autotest/ogr/ogr_sql_sqlite.py
- autotest/ogr/ogr_sql_test.py
Refactors some test files to remove dependencies between test functions.
I'm wondering if it would be a good idea to mark test files with no inter-test dependencies (`pytestmark = pytest.mark.independent` ?) and then use `pytest --random-order` for these tests in one of the CI configurations.
#4407
> autotest: Remove some inter-test dependencies

- autotest/gcore/basic_test.py
- autotest/ogr/ogr_basic_test.py
- swig/include/python/gdal_python.i
- swig/include/python/ogr_python.i
Continues the pattern set in #7965 where closing a `Dataset` or `DataSource` invalidates associated `Band` and `Layer` objects, covering mask bands and overview bands, as well as layers created with `CreateLayer` and `CopyLayer`.
#7965
> Python bindings: Invalidate more band, layer refs

- doc/source/programs/gdal_rasterize.rst
It removes duplicate text from gdal_rasterize [docs](https://gdal.org/programs/gdal_rasterize.html#cmdoption-gdal_rasterize-arg-dst_filename):
* OS:
* Compiler:
> Docs: remove duplicate text from gdal_rasterize.rst

- autotest/pyscripts/test_gdal_calc.py
- swig/python/gdal-utils/osgeo_utils/gdal_calc.py
CC @idanmiara  You introduced --hideNoData in d9e9e827d85 and documented it as implying --NoDataValue=none, but the implementation was setting the default noDataValue depending on the data type. So I've fixed the implementation to follow the documentation, which seems the most natural expected behaviour.
> gdal_calc.py: make --hideNoData imply --NoDataValue=none as documented (fixes #8009)

- autotest/gcore/tiff_write.py
- gcore/gdalpamrasterband.cpp
and similarly for unit type.
This enables the GTiff driver to be able to mix its internal metadata with PAM one (fixes #7997)
A few code cleanups too
> PAM rasterband: on .aux.xml reading do not systematically set (offset,scale) to (0,1)

- swig/java/apps/GDALtest.java
- swig/java/apps/ogr2ogr.java
- swig/java/apps/ogrinfo.java
Some java deprecation warnings were getting in the way of easily seeing real compile errors during the build process. Bring that code up to date to eliminate the warnings.
> Eliminate some deprecations / compiler warnings

- apps/gdalwarp_lib.cpp
- autotest/utilities/test_gdalwarp_lib.py
> [Backport release/3.7] gdalwarp: make -cutline to work again with PostGIS datasources (fixes 3.7.0 regression, fixes #8023)

- autotest/pyscripts/test_gdal_calc.py
- swig/python/gdal-utils/osgeo_utils/gdal_calc.py
> [Backport release/3.7] gdal_calc.py: make --hideNoData imply --NoDataValue=none as documented (fixes #8009)

- gcore/rasterio.cpp
> [Backport release/3.7] GDALBufferHasOnlyNoData() / GTiff SPARSE_OK=YES: recognize negative floating point 0 as 0 (fixes #8025)

- autotest/cpp/test_cpl.cpp
- autotest/gcore/misc.py
- port/cpl_conv.cpp
- port/cpl_conv.h
- swig/include/cpl.i
- swig/include/python/gdal_python.i
Fix for https://github.com/OSGeo/gdal/issues/8018
Maybe there is a better name than `CPLGetGlobalConfigOption`. I couldn't think of a word that exactly means the opposite of "thread-local".
> Python bindings: Prevent migration of config options between env vars, global and thread-local storage

- autotest/gcore/misc.py
- frmts/rasterlite/rasterlitedataset.cpp
- swig/include/cpl.i
Exposes a `GetConfigOptions` function that returns the set of options obtainable with `GetConfigOption`, with the exception of environment variables. This is done by blending the results of `CPLGetConfigOptions` and `CPLGetThreadLocalConfigOptions`.
I had conflicting opinions about this. On the one hand, the `GetConfigOptions` name is similar to `GetConfigOption`, so the functions should behave similarly and return thread-local config options that shadow global config options. On the other hand, the SWIG bindings should behave similarly to the underling C API, but this would introduce an unintuitive behavior difference between `GetConfigOption` and `GetConfigOptions`. This conflict could also be resolved by changing the behavior of `CPLGetConfigOptions`. I'm not seeing real usage in the …
> SWIG: Add GetConfigOptions

- .github/workflows/coverage/build.sh
- .github/workflows/coverage/test.sh
- .github/workflows/linux_build.yml
- .github/workflows/ubuntu_20.04/Dockerfile.ci
For push operations on master, pushes to https://gdalautotest-coverage-results.github.io/coverage_html/index.html
(was tested on my fork : https://github.com/rouault/gdal/actions/runs/5379543312/jobs/9760905648 )
Pull requests and pushes should also appear at https://coveralls.io/github/OSGeo/gdal
> CI: add a coverage job

- autotest/gcore/basic_test.py
- autotest/ogr/ogr_gpkg.py
- autotest/ogr/ogr_shape.py
- swig/include/python/typemaps_python.i
Allows functions/methods in the Python bindings to accept options via a dictionaries.
A typemap (`char **dict`) already existed to accept a dictionary or sequence and convert it into a CSL, but it was only applied to `SetMetadata`. I updated the `char **dict` typemap to use the `CSLFromPySequence` helper, and set the `char **options` typemap to alias this.
I noticed that `CSLFromPySequence` has some special handling for UTF8 strings that was not present in the sequence-to-CSL code I replaced in `char **dict`. The dict-to-CSL pathway in `char **dict` does not have any special handling, but it appears that UTF8 option names and values are successfully transmitted to GDAL.
> Python bindings: Allow passing options as dict

- swig/python/gdal-utils/osgeo_utils/samples/validate_geoparquet.py
Avoids logging into GitHub via credentials in a `.netrc` file when downloading GeoParquet schemas in `validate_geoparquet.py`. This causes a test failure if the login fails or the associated token does not have certain permissions, even though the schemas being accessed are public.
None
> validate_geoparquet: avoid GitHub login via .netrc

- apps/CMakeLists.txt
- apps/gdal_footprint_bin.cpp
- apps/gdal_footprint_lib.cpp
- apps/gdal_utils.h
- apps/gdal_utils_priv.h
- autotest/pymod/test_cli_utilities.py
- autotest/utilities/test_gdal_footprint.py
- autotest/utilities/test_gdal_footprint_lib.py
- doc/source/conf.py
- doc/source/programs/gdal_footprint.rst
- doc/source/programs/index.rst
- gcore/gdal_priv.h
- gcore/gdalnodatamaskband.cpp
- gcore/gdalrasterband.cpp
- scripts/completionFinder.py
- swig/include/gdal.i
- swig/include/python/gdal_python.i
The gdal_footprint utility can be used to compute the footprint of
a raster file, taking into account nodata values (or more generally the mask
band attached to the raster bands), and generating polygons/multipolygons
corresponding to areas where pixels are valid, and write to an output vector file.
Documentation at https://github.com/rouault/gdal/blob/gdal_footprint/doc/source/programs/gdal_footprint.rst
Fixes #6264
> Add gdal_footprint utility

- apps/ogrinfo_lib.cpp
- autotest/ogr/ogr_gpkg.py
- ogr/ogrsf_frmts/gpkg/ogr_geopackage.h
- ogr/ogrsf_frmts/gpkg/ogrgeopackagedatasource.cpp
- ogr/ogrsf_frmts/gpkg/ogrgeopackagetablelayer.cpp
- ogr/ogrsf_frmts/sqlite/ogrsqliteutility.cpp
- ogr/ogrsf_frmts/sqlite/ogrsqliteutility.h
On the dataset of https://github.com/qgis/QGIS/issues/53525, this speeds up ogrinfo -json by a factor of 2.
Before:
```
$ time ogrinfo -json file_300_filled_layers.gpkg > out.json
real	0m0,565s
user	0m0,524s
sys	0m0,040s
```
After:
```
$ time ogrinfo -json file_300_filled_layers.gpkg > out.json
real	0m0,258s
user	0m0,217s
sys	0m0,041s
```
> ogrinfo: speed-up on GPKG with large number of layers

- apps/ogrinfo_lib.cpp
- autotest/ogr/ogr_fielddomain.py
- autotest/ogr/ogr_openfilegdb_write.py
- autotest/utilities/test_ogrinfo_lib.py
- ogr/ogr_p.h
- ogr/ogr_wkb.cpp
- ogr/ogrsf_frmts/openfilegdb/filegdb_fielddomain.h
- ogr/ogrspatialreference.cpp
- ogr/ogrutils.cpp
- swig/include/ogr.i
Fixes the warning "Unsupported field type for range domain: esriFieldTypeDate" of https://lists.osgeo.org/pipermail/gdal-dev/2023-June/057394.html
> OpenFileGDB: add support for DateTime field domains

- autotest/cpp/test_ogr.cpp
- autotest/ogr/ogr_gpkg.py
- doc/source/drivers/vector/gpkg.rst
- ogr/ogr_p.h
- ogr/ogrsf_frmts/gpkg/ogr_geopackage.h
- ogr/ogrsf_frmts/gpkg/ogrgeopackagedatasource.cpp
- ogr/ogrsf_frmts/gpkg/ogrgeopackagedriver.cpp
- ogr/ogrsf_frmts/gpkg/ogrgeopackagelayer.cpp
- ogr/ogrsf_frmts/gpkg/ogrgeopackagetablelayer.cpp
- ogr/ogrutils.cpp
- swig/python/gdal-utils/osgeo_utils/samples/validate_gpkg.py
as allowed by GeoPackage 1.4 (fixes https://github.com/OSGeo/gdal/issues/8037)
and add a DATETIME_PRECISION layer creation option
> GeoPackage: deal with DateTime fields without milliseconds or seconds

- autotest/gcore/cog.py
- autotest/gcore/tiff_write.py
- autotest/gcore/vrtmisc.py
- autotest/gdrivers/jpeg.py
- autotest/gdrivers/png.py
- doc/source/programs/gdal_translate.rst
- doc/source/programs/options/co.rst
- frmts/gtiff/cogdriver.cpp
- frmts/gtiff/gtiffdataset.h
- frmts/gtiff/gtiffdataset_write.cpp
- frmts/jpeg/jpgdataset.cpp
- frmts/png/pngdataset.cpp
- frmts/vrt/vrtdriver.cpp
- gcore/gdal_priv.h
- gcore/gdaldriver.cpp
Fixes #7956
- .. co:: COPY_SRC_MDD
:choices: AUTO, YES, NO
:default: AUTO
:since: 3.8
Defines if metadata domains of the source dataset should be copied to the
destination dataset.
In the default AUTO mode, only "safe" domains will be copied, which
include the default metadata domain (some drivers may include other
domains such as IMD, RPC, GEOLOCATION).
When setting YES, all domains will be copied (but a few reserved ones like
IMAGE_STRUCTURE or DERIVED_SUBDATASETS).
Currently only recognized by the GTiff, COG, VRT, PNG and JPEG drivers.
When setting NO, no source metadata will be copied.
- .. co:: SRC_MDD
:choices: <domain_name>
:since: 3.8
Defines which source metadata domain should be copied.
This option restricts the list of source metadata domains to be copied
(it implies …
> Add COPY_SRC_MDD=AUTO/YES/NO and SRC_MDD=domain_name creation options

- cmake/modules/Ccache.cmake
should fix the following warning (as reported in
https://github.com/OSGeo/gdal/issues/8105)
```
CMake Deprecation Warning at cmake/modules/Ccache.cmake:10 (cmake_minimum_required):
Compatibility with CMake < 3.5 will be removed from a future version of
CMake.
Update the VERSION argument value or use a ... suffix to tell
CMake that the project does not need compatibility with older versions.
Call Stack (most recent call first):
CMakeLists.txt:58 (include)
```
> Ccache.cmake: fix warning

- .github/workflows/cmake_builds.yml
- autotest/pymod/gdaltest.py
- autotest/pyscripts/test_gdal_edit.py
- autotest/pyscripts/test_gdal_merge.py
- autotest/pyscripts/test_gdal_pansharpen.py
- autotest/pyscripts/test_gdal_retile.py
- autotest/utilities/test_gdal_contour.py
- autotest/utilities/test_gdal_grid.py
- autotest/utilities/test_gdal_rasterize.py
- autotest/utilities/test_gdal_translate.py
- autotest/utilities/test_gdaladdo.py
- autotest/utilities/test_gdalbuildvrt.py
- autotest/utilities/test_gdaldem.py
- autotest/utilities/test_gdaltindex.py
- autotest/utilities/test_gdalwarp.py
- autotest/utilities/test_gdalwarp_lib.py
- autotest/utilities/test_gnmutils.py
- autotest/utilities/test_nearblack.py
- autotest/utilities/test_ogrlineref.py
- autotest/utilities/test_ogrtindex.py
- cmake/template/pytest.ini.in
- swig/python/gdal-utils/osgeo_utils/gdal_pansharpen.py
This PR makes tests under the `utilities` and `pyscripts` folders run independently, using the following types of changes:
- Pulling out generated data that is used by multiple tests into module-scoped fixtures.
- Moving cleanup steps from a dummy test into a fixture, or in some cases writing generated files to a location provided by `tmp_path` to avoid the need for a cleanup fixture. The `tmp_path` method is more invasive but probably easier for understand, so it might be worth doing this in all cases.
- Merging tests, occasionally, such as a test that writes a file followed by a test that reads the file.
-  Flagging tests as non-independent using the `random_order(disabled=True)` marker (44b24c8c656d23112bb9ff0ea3852be3ae7fdcb5).
These will need to be addressed eventually if we want to …
> autotest: make utilities, pyscript tests run independently

- autotest/gdrivers/data/stacit/test_page2.json
- frmts/stacit/stacitdataset.cpp
> [Backport release/3.7] STACIT: correctly process asset 'href' starting with 'file://' (fixes #8135)

- swig/include/gnm.i
- swig/include/ogr.i
This actually ammends be9f8da7b466cb78ecafc4edf66c1838c81e4425 which caused warnings about missing destructor for "CPLErr*" when running Python OGR scripts
> SWIG bindings: fix warning related to redefinition of CPLErr

- autotest/ogr/ogr_wfs.py
- doc/source/drivers/vector/wfs.rst
- ogr/ogrsf_frmts/wfs/ogrwfslayer.cpp
WFS datasources with no primary key cannot be naturally ordered by the server, and so using the STARTINDEX argument causes a 400 error with the response:
> Cannot do natural order without a primary key, please add it or
> specify a manual sort over existing attributes
An example is here: https://geo.irceline.be/wfs?request=GetFeature&version=2.0.0&service=WFS&TYPENAMES=bc_24hmean&COUNT=1000000&STARTINDEX=0
This change avoids issuing `STARTINDEX` if:
* the feature count is known by the time the first GetFeature request is issued
* the feature count is less than the page size.
In other words, this change allows us to use small datasets that have no primary key, while still allowing paging in larger datasets (as long as they have a primary key)
1. In the gdal-dev post, @rouault suggested …
> WFS: Don't issue STARTINDEX if feature count is small

- ogr/ogrsf_frmts/hana/ogrhanadatasource.cpp
This PR contains the following bug fixes in HANA driver:
- The driver throws an exception when there is a view or a select statement having columns from different tables
- The driver outputs views that are not in TABLES list
Please note, these are critical bug fixes that need to be backported.
> HANA: bug fixes

- ogr/ogrsf_frmts/xls/include_freexl.h
- ogr/ogrsf_frmts/xls/ogrxlsdatasource.cpp
- ogr/ogrsf_frmts/xls/ogrxlslayer.cpp
> [Backport release/3.7] XLS: avoid compiler warning when building against freexl 2.0

- cmake/modules/packages/FindSPATIALITE.cmake
Fixes detection of SpatiaLite 5.1.0.  Version string changed from "5.0, something" to "5.1.0, something"
> Update FindSPATIALITE.cmake for SpatiaLite 5.1.0

- frmts/stacit/stacitdataset.cpp
Apply the `/vsis3/` prefix to data sources found within STACIT that are prefixed `s3://`. 
Addresses this mailing list item: https://lists.osgeo.org/pipermail/gdal-dev/2023-August/057524.html
I've had good results with this
```
gdalinfo --config AWS_NO_SIGN_REQUEST "YES"  "STACIT:\"https://explorer.sandbox.dea.ga.gov.au/stac/search?collections=ga_ls_landcover_class_cyear_2&bbox=122.1,-18.28,122.48,-17.91&datetime=2020-01-01/2020-02-29\":asset=level3"
```
EDIT: (putting 'collections' in the search args rather than the dsn args is *much* faster)
> STACIT: apply vsis3 protocol to  s3:// items

- frmts/nitf/nitfdataset.cpp
Last time the computation was modified was in https://github.com/OSGeo/gdal/commit/c654d4fbfb38187c0337a97862d53022ecce6d26 but this appears to be wrong to me as per
http://geotiff.maptools.org/rpc_prop.html, latitudes and longitudes are normalized to [-1,1] range with the _SCALE/_OFF coefficients. Consequently, we should do OFF +/- SCALE to get back the initial range. This analysis is consistent with was is done in the ENVI driver with
```
CPLsnprintf(sVal, sizeof(sVal), "%.16g",
CPLAtof(papszFields[3]) - CPLAtof(papszFields[8]));
SetMetadataItem("MIN_LONG", sVal, "RPC");
CPLsnprintf(sVal, sizeof(sVal), "%.16g",
CPLAtof(papszFields[3]) + CPLAtof(papszFields[8]));
SetMetadataItem("MAX_LONG", sVal, "RPC");
CPLsnprintf(sVal, sizeof(sVal), "%.16g",
CPLAtof(papszFields[2]) - …
```
> NITF: fix MIN/MAX_LONG/LAT when reading RPC00B

- frmts/nitf/nitfdataset.cpp
> [Backport release/3.7] NITF: fix MIN/MAX_LONG/LAT when reading RPC00B

- CMakeLists.txt
should fix
```
CMake Error (dev) at cmake/modules/thirdparty/FindCSharp.cmake:40 (find_package):
Policy CMP0144 is not set: find_package uses upper-case <PACKAGENAME>_ROOT
variables.  Run "cmake --help-policy CMP0144" for policy details.  Use the
cmake_policy command to set the policy and suppress this warning.
Environment variable DOTNET_ROOT is set to:
/Users/runner/.dotnet
For compatibility, find_package is ignoring the variable, but code in a
.cmake module might still use it.
Call Stack (most recent call first):
cmake/helpers/CheckDependentLibraries.cmake:793 (find_package)
gdal.cmake:265 (include)
CMakeLists.txt:246 (include)
```
of https://github.com/OSGeo/gdal/actions/runs/5798527630/job/15716491404
> CMakeLists.txt: update maximum range to 3.27

- autotest/gcore/vsiaz.py
- port/cpl_vsil_az.cpp
> [Backport release/3.7] /vsiaz/: fix cached URL names when listing /vsiaz/

- .github/workflows/linux_build.yml
CC @dbaston in case you've an idea... I've also manually deleted the image ghcr.io/osgeo/gdal-deps:fedorarawhide-master before doing a master push build, but this doesn't change anything.
> CI: workaround weird caching issue with fedora_rawhide builds

- autotest/gdrivers/vrtovr.py
- frmts/vrt/vrtdataset.cpp
- frmts/vrt/vrtdataset.h
(not appropriate for 3.7 backport due to VRTDataset ABI change)
> VRT: ignore <OverviewList> when external .vrt.ovr is present, as documented and intended

- autotest/utilities/test_gdal_create.py
- autotest/utilities/test_gdal_footprint.py
- autotest/utilities/test_gdal_rasterize.py
- autotest/utilities/test_gdal_rasterize_lib.py
- autotest/utilities/test_gdal_translate.py
- autotest/utilities/test_gdal_translate_lib.py
- autotest/utilities/test_gdal_viewshed.py
- autotest/utilities/test_gdaladdo.py
- autotest/utilities/test_gdaldem.py
- autotest/utilities/test_gdalinfo.py
- autotest/utilities/test_gdallocationinfo.py
- autotest/utilities/test_gdalmdimtranslate.py
- autotest/utilities/test_gdalsrsinfo.py
- autotest/utilities/test_gdaltindex.py
- autotest/utilities/test_gdalwarp.py
- autotest/utilities/test_gdalwarp_lib.py
- autotest/utilities/test_gnmutils.py
- autotest/utilities/test_nearblack.py
- autotest/utilities/test_ogr2ogr.py
- autotest/utilities/test_ogr2ogr_lib.py
- autotest/utilities/test_ogrinfo.py
- autotest/utilities/test_ogrlineref.py
- autotest/utilities/test_ogrtindex.py
- autotest/utilities/test_sozip.py
Updates tests in `autotest/utilities` to use `tmp_path` for temporary files.
Also splits some tests where I noticed this could be done trivially (e.g,, `gdalwarp_46`, `gdalwarp_lib_135` and parametrizes other (e.g., `test_gdalwarp_lib_override_default_output_nodata`)
> autotest: Use tmp_path fixture for utilities tests

- autotest/conftest.py
- autotest/gdrivers/plmosaic.py
Adds a `tmp_vsimem` fixture that behaves like `tmp_path` but returns a location under `vsimem` instead of the local file system.
This removes the need for tests to include cleanup code and prevents collisions between tests running in parallel.
> autotest: add tmp_vsimem fixture

- autotest/ogr/ogr_feature.py
- ogr/ogr_api.h
- ogr/ogrfeature.cpp
- swig/include/ogr.i
- swig/include/python/ogr_python.i
Make the Python `Feature.__repr__` use `DumpReadableAsString`. This is convenient for interactive use and also lets pytest generate assertion failure messages, like
```
>       assert feat1 == feat2
E       assert OGRFeature(rfc35_test):1\n  intfield (Integer) = (null)\n  foo5 (String) = foo0\n  bar10 (String) = (null)\n  baz15 (String) = (null)\n  baw20 (String) = (null)\n\n == OGRFeature(rfc35_test):2\n  intfield (Integer) = (null)\n  foo5 (String) = foo1\n  bar10 (String) = bar1\n  baz15 (String) = (null)\n  baw20 (String) = (null)\n\n
E         Full diff:
E         - OGRFeature(rfc35_test):2
E         ?                        ^
E         + OGRFeature(rfc35_test):1
E         ?                        ^
E             intfield (Integer) = (null)
E         -   foo5 (String) = foo1
E …
```
> Python bindings: Use OGRFeature::DumpReadableAsString for __repr__

- autotest/ogr/ogr_sql_sqlite.py
- ogr/ogrsf_frmts/sqlite/ogr_sqlite.h
- ogr/ogrsf_frmts/sqlite/ogrsqlitedatasource.cpp
- ogr/ogrsf_frmts/sqlite/ogrsqliteexecutesql.cpp
- ogr/ogrsf_frmts/sqlite/ogrsqliteselectlayer.cpp
> [Backport release/3.7] Fix ExecuteSQL(dialect='SQLITE', spatialFilter=...) on a Memory datasource

- doc/source/tutorials/wktproblems.rst
- swig/java/javadoc.java
It substitutes remotesensing.org/geotiff/proj_list with gdal.org/proj_list/ in https://gdal.org/tutorials/wktproblems.html and https://gdal.org/java/org/gdal/osr/SpatialReference.html#SetProjParm(java.lang.String,double)
Other no longer available resources previously hosted at remotesensing.org are also linked in other files... e.g.:
https://github.com/OSGeo/gdal/blob/af5b75ecc6b8d3cef36f2b6fecf085319d39a546/doc/source/drivers/raster/hdf4.rst?plain=1#L200-L203
https://github.com/OSGeo/gdal/blob/af5b75ecc6b8d3cef36f2b6fecf085319d39a546/frmts/hdf4/hdf4imagedataset.cpp#L62-L64
or in some libgeotiff and libtiff files, ...
https://github.com/OSGeo/gdal/pull/8256
> Doc: substitute remotesensing.org/geotiff/proj_list with gdal.org/proj_list/

- autotest/ogr/ogr_parquet.py
- ogr/ogrsf_frmts/arrow_common/ogr_arrow.h
- ogr/ogrsf_frmts/arrow_common/ograrrowlayer.hpp
- ogr/ogrsf_frmts/parquet/ogr_parquet.h
- ogr/ogrsf_frmts/parquet/ogrparquetdataset.cpp
- ogr/ogrsf_frmts/parquet/ogrparquetlayer.cpp
> Parquet: use statistics to skip row groups that don't match attribute filter

- docker/ubuntu-full/Dockerfile
GTiff: fix Typo in `docker/ubuntu-full/Dockerfile` (fixes #8279)
* OS: N/A
* Compiler: N/A
> [FIXED] Typo in ubuntu-full Dockerfile

- doc/source/development/dev_environment.rst
remove stray "_" from docker  label in "Setting up a development environment" 
https://gdal.org/development/dev_environment.html
> dev_environment.rst: fix docker  label

- autotest/gcore/vsiaz.py
- port/cpl_azure.cpp
- port/cpl_azure.h
Backport of af20bce4ee5d6e0e7af0094c94d03151945fd8db and 8ed7bd9bcdd82a1b9de2c32a8f9265962e74cfc2
> [Backport 3.7] /vsiaz/ backports

- autotest/gcore/basic_test.py
- swig/include/python/python_strings.i
- swig/include/python/typemaps_python.i
Coerces path-like data types to a string when calling functions such as `gdal.Open` that have a `const char *utf8_path` argument.
> Python bindings: Accept os.PathLike arguments where applicable

- autotest/utilities/test_gdal_footprint_lib.py
- autotest/utilities/test_gdal_rasterize_lib.py
- autotest/utilities/test_gdal_translate_lib.py
- autotest/utilities/test_gdalbuildvrt_lib.py
- autotest/utilities/test_gdaldem_lib.py
- autotest/utilities/test_gdalinfo_lib.py
- autotest/utilities/test_gdalmdiminfo_lib.py
- autotest/utilities/test_gdalmdimtranslate_lib.py
- autotest/utilities/test_gdalwarp_lib.py
- autotest/utilities/test_nearblack_lib.py
- autotest/utilities/test_ogr2ogr_lib.py
- autotest/utilities/test_ogrinfo_lib.py
- swig/include/python/gdal_python.i
Extends support for `os.PathLike` inputs to utility functions that did not pick it up automatically from the typemap.
#8286
> Python bindings: Support os.PathLike inputs in utilities

- autotest/pyscripts/test_gdal_utils.py
- swig/python/gdal-utils/osgeo_utils/auxiliary/base.py
- swig/python/gdal-utils/osgeo_utils/auxiliary/util.py
> [Backport release/3.7] osgeo_utils: allign base.get_extension() and util.DoesDriverHandleExtension() on C++ versions, and add tests (fixes #8277)

- autotest/gcore/vrt_read.py
- doc/source/drivers/raster/vrt.rst
- frmts/vrt/vrtdataset.cpp
Add 'projwin' to allowed options for a "vrt://" connection.
> VRT 'projwin' for vrt:// connection

- autotest/gcore/vrt_read.py
- doc/source/drivers/raster/vrt.rst
- frmts/vrt/vrtdataset.cpp
Add 'projwin_srs' to allowed options for a "vrt://" connection.
* OS:
* Compiler:
> VRT 'projwin_srs' for vrt:// connection

- autotest/utilities/test_gdal_footprint_lib.py
- autotest/utilities/test_gdal_grid_lib.py
- autotest/utilities/test_gdal_rasterize_lib.py
- autotest/utilities/test_gdal_translate_lib.py
- autotest/utilities/test_gdaldem_lib.py
- autotest/utilities/test_gdalmdimtranslate_lib.py
- autotest/utilities/test_gdalwarp_lib.py
- autotest/utilities/test_nearblack_lib.py
- autotest/utilities/test_ogr2ogr_lib.py
- swig/include/python/gdal_python.i
Allows dictionaries to be used for `creationOptions`, `datasetCreationOptions`, `layerCreationOptions`, etc. in high-level functions like `gdal.VectorTranslate`.
#8073
> Python bindings: accept options as dicts in CLI wrapper functions

- autotest/gdrivers/tiledb_write.py
- frmts/tiledb/tiledbdense.cpp
- frmts/tiledb/tiledbheaders.h
- add capability to read arbitrary (i.e. not created by GDAL) 2D/3D dense array, provided it uses uint64 dimension
- robustness checks in opening code path
CC @normanb
> TileDB: read/write Int8, Int64 and UInt64

- autotest/gdrivers/gpkg.py
- autotest/ogr/ogr_gpkg.py
- doc/source/drivers/raster/gpkg.rst
- doc/source/drivers/vector/gpkg.rst
- ogr/ogrsf_frmts/gpkg/gdalgeopackagerasterband.cpp
- ogr/ogrsf_frmts/gpkg/ogr_geopackage.h
- ogr/ogrsf_frmts/gpkg/ogrgeopackagedatasource.cpp
- ogr/ogrsf_frmts/gpkg/ogrgeopackagedriver.cpp
New features:
- add a CRS_WKT_EXTENSION=YES/NO dataset creation option to force addition of definition_12_063 column
-  add a METADATA_TABLES creation option to control creation of system metadata tables
Bug fixes:
- GDALGeoPackageRasterBand::GetMetadata(): fix use after free
- GDALGeoPackageRasterBand: fix missing GRID_CELL_ENCODING metadata item when there is other metadata
- remove .aux.xml file in Delete()
> GPKG: add a CRS_WKT_EXTENSION and METADATA_TABLES creation option

- cmake/helpers/CheckDependentLibraries.cmake
Fixes https://github.com/microsoft/vcpkg/issues/33565
When `-DGDAL_USE_JPEG=OFF` is used and gdal is found, the target `JPEG::JPEG` exists. Based on this some checks are executed and HAVE_JPEGTURBO_DUAL_MODE_8_12 is set to `ON`.  
Then the following if gets true and gdal tries to use jpeg: 
https://github.com/OSGeo/gdal/blob/d12af24fa7496d7bf2aa850453230278dd9070e4/frmts/mrf/CMakeLists.txt#L35-L38
Since we don't want to use jpeg anyway, we can simply skip the checks (`check_c_source_compiles`).
> Don't use jpeg if disabled

- autotest/gcore/vrt_read.py
- doc/source/drivers/raster/vrt.rst
- frmts/vrt/vrtdataset.cpp
Add `oo` to allowed options for a "vrt://" connection. 
> VRT 'oo' for vrt:// connection

- autotest/ogr/ogr_mitab.py
Fixes bug wherein `mapinfo_ds` incorrectly produced a `.tab` when a `.mif` was requested. This lead to a loss of test coverage for `.mif` files.
Introduced in #8333
> autotest: ogr_mitab.py: fix format parametrization of mapinfo_ds fixture

- autotest/ogr/ogr_gml_read.py
1) restores loss of `.xsd` testing that I caused with 4faf097. When copying `.gml` files into `tmp_path` to avoid side-effects from opening them in `data`, I missed some `xsd` files.
2) adds explicit testing that `.gfs` files are ignored when they are older than the corresponding `.gml` files. This was implicitly tested somewhere prior to 4faf097, but I added an explicit test for it.
I have a reasonable procedure in place to catch these kinds of regressions in the future. Maybe it makes sense to add it to the coverage build.
#8333
> autotest: fix recent errors introduced in GML tests

- autotest/gcore/vrt_read.py
- doc/source/drivers/raster/vrt.rst
- frmts/vrt/vrtdataset.cpp
Add 'scale' and 'unscale'  to allowed options for a "vrt://" connection.
These can be set to values `=true` or `=false`. 
Options without `key=value` form are now disallowed. 
First attempt was #8343 see for some discussion. 
> VRT 'scale' 'unscale' for vrt:// connection (2nd attempt)

- autotest/ogr/ogr_sql_test.py
- swig/include/python/ogr_python.i
The statement `assert self._dataset_strong_ref` is equivalent to `assert bool(self._dataset_strong_ref)`, whose default implementation is `len(self._dataset_strong_ref) > 0`. Since dataset defines `__len__` as `GetLayerCount()`, this is false for an empty datasource.
> Python bindings: Allow ExecuteSQL context manager to work on empty datasources

- apps/gdal_translate_lib.cpp
- autotest/gcore/vrt_read.py
- autotest/utilities/test_gdal_translate_lib.py
- frmts/vrt/vrtdataset.h
- frmts/vrt/vrtfilters.cpp
- frmts/vrt/vrtsources.cpp
- gdal_translate -scale: change dstMax value from 255.999 to 255
- VRTComplexSource (scaling typically): make sure to take into account constraints from VRTRasterBand data type in RasterIO() (rather than just taking into account output buffer data type)
> Scaling related fixes

- autotest/gcore/vrt_read.py
- doc/source/drivers/raster/vrt.rst
- frmts/vrt/vrtdataset.cpp
Add `a_coord_epoch` to allowed options for a "vrt://" connection.
Does this need a pytest requirement for the proj data files? 
> VRT 'a_coord_epoch' for vrt:// connection

- .pre-commit-config.yaml
- autotest/ogr/data/pydrivers/ogr_DUMMY.py
- autotest/ogr/ogr_pythondrivers.py
- doc/source/tutorials/vector_python_driver.rst
- examples/pydrivers/ogr_PASSTHROUGH.py
- gcore/gdalpython.cpp
- gcore/gdalpython.h
- gcore/gdalpythondriverloader.cpp
1. Add support for passing ISO WKB geometries from Python OGR drivers by using a bytes-like object (bytes, bytesarray, memoryview); as well as the existing WKT strings.
2. Expand the dummy python driver in tests to take options, and use them to test the geometry formats.
3. Update the documentation and examples; tidy up some formatting.
- Updated Python API documentation (swig/include/python/docs/)
Imports a couple more functions from the Python Stable ABI, but nothing introduced recently.
Tested on macOS with Python3.11.
> python-drivers: Support WKB geometries

- autotest/gcore/vrt_read.py
- doc/source/drivers/raster/vrt.rst
- frmts/vrt/vrtdataset.cpp
Add `nogcp` to allowed options for a "vrt://" connection.
> VRT 'nogcp' for vrt:// connection

- frmts/wcs/wcsdataset110.cpp
- frmts/wcs/wcsdataset201.cpp
removes non-standard 'FORMAT' parameter from WCS 1.1.0 and WCS 2.0.1 'DescribeCoverage' requests. The additional parameter cause errors with some strict server implementation. See #8381.
As researched by @jratike80 '&format=' is never needed and must not be accepted by DescribeCoverage:
https://github.com/OSGeo/gdal/issues/8381#issuecomment-1715643356
Thanks for your fast help on this! 👍 
If additional parameters (like 'format') are needed in special use cases they can be added with 'DescribeCoverageExtra' option.
> WCS: remove non-standard 'FORMAT' parameter from 'DescribeCoverage' requests (fixes #8381)

- alg/gdalwarpkernel.cpp
- gcore/gdal_priv_templates.hpp
- gcore/gdalsse_priv.h
- gcore/rasterio.cpp
- ogr/ogrsf_frmts/openfilegdb/filegdbindex.cpp
- port/cpl_port.h
CPL_CPU_REQUIRES_ALIGNED_ACCESS is undefined for x86 which can cause -fsanitize=alignment failures.
Let's just use CPL_CPU_REQUIRES_ALIGNED_ACCESS unconditionally. Modern compilers are able to optimize memcpy.
It seems that GDALCopyWords64 performs more conditions and FileGDBIndexIterator::GetNextRow() has less efficient code with this change, but the difference unlikely matters in practice.
---
Fix -fsanitize=alignment failures on x86 even if `MAKE_SANITIZE_HAPPY` is not defined.
> Use unaligned memory accesses unconditionally

- autotest/ogr/ogr_geojson.py
- doc/source/drivers/vector/geojson.rst
- doc/source/drivers/vector/geojsonseq.rst
- ogr/ogrsf_frmts/geojson/ogrgeojsondriver.cpp
- ogr/ogrsf_frmts/geojson/ogrgeojsonseqdriver.cpp
- ogr/ogrsf_frmts/geojson/ogrgeojsonwritelayer.cpp
- ogr/ogrsf_frmts/geojson/ogrgeojsonwriter.cpp
- ogr/ogrsf_frmts/geojson/ogrgeojsonwriter.h
This optionally prevents conversion of JSON-like string fields into JSON objects or arrays when they are written with the GeoJSON or GeoJSONSeq driver.
Optionally prevents conversion of JSON-like string fields into JSON objects or arrays when they are written with the GeoJSON or GeoJSONSeq driver.
None known
* OS: (.venv) Erica-Felt% uname -a
Darwin Erica-Felt.local 22.5.0 Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:19 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T8103 arm64
* Compiler: Apple clang version 14.0.3 (clang-1403.0.22.14.1)
> Add AUTODETECT_JSON_STRINGS option

- doc/source/user/configoptions.rst
Fix the rendering for escaping docs
https://gdal.org/user/configoptions.html
Current situation:
> Escape docs for escaping

- ogr/ogrsf_frmts/geojson/libjson/linkhash.c
Added HWASAN to the list of memory checkers to avoid false reports.
> Add hwasan flag in the linkhash library

- autotest/conftest.py
- autotest/ogr/ogr_mysql.py
- autotest/ogr/ogr_pg.py
- autotest/ogr/ogr_sqlite.py
- autotest/pyscripts/test_ogr2ogr_py.py
- autotest/utilities/test_ogr2ogr.py
This PR updates the tests for PostgreSQL, SQLite, and MySQL to run independently.
Each test runs in a clean schema / database to avoid interactions between tests.
Test tables that are used by more than one dataset can be brought in with, e.g. `@pytest.usefixtures("tpoly")`.
The Postgres tests cannot run in parallel because some of them manipulate `spatial_ref_sys`. 
#4407
> autotest: Make SQLite, MySQL, Postgres tests run independently

- doc/source/community/index.rst
Adds Javier Jimenez Shaw as member of PSC
https://lists.osgeo.org/pipermail/gdal-dev/2023-September/057667.html
N/A
> Add Javier as PSC member [skip ci]

- docker/ubuntu-full/bh-proj.sh
- docker/ubuntu-small/Dockerfile
This file is referenced in `/usr/local/lib/cmake/proj/proj-targets-release.cmake`
He add the symbolic link /usr/local/lib/libproj.so.25.9.3.0to make the find package working
Currently, I get the error 
```
#31 1.753 CMake Error at /usr/local/lib/cmake/proj/proj-targets.cmake:74 (message):
#31 1.753   The imported target "PROJ::proj" references the file
#31 1.753 
#31 1.753      "/usr/local/lib/libproj.so.25.9.3.0"
#31 1.753 
#31 1.753   but this file does not exist.  Possible reasons include:
#31 1.753 
#31 1.753   * The file was deleted, renamed, or moved to another location.
#31 1.753 
#31 1.753   * An install or uninstall procedure did not complete successfully.
#31 1.753 
#31 1.753   * The installation package was faulty and contained
#31 1.753 
#31 1.753 …
```
> Fix missing /usr/local/lib/libproj.so.25.9.3.0 file

- ogr/ogrsf_frmts/openfilegdb/gdalopenfilegdbrasterband.cpp
```
$ gdalinfo  Raster_class.gdb
[...]
Metadata:
RASTER_DATASET=Tacoma_landcover_t2
```
> OpenFileGDB raster: add a RASTER_DATASET metadata item with the name of the RasterDataset (fixes #8427)

- autotest/cpp/test_gdal.cpp
- frmts/gdalallregister.cpp
- gcore/gdal.h
implements #8422
for the naming I went with RegisterPlugins instead of AutoloadDrivers, as the
plugin mechanism can be used for registering more than just drivers (e.g. vrt
pixel functions, VSI handlers, ...)
> add GDALRegisterPlugins function to register all/only plugins

- autotest/ogr/ogr_parquet.py
- ogr/ogrsf_frmts/generic/ogrlayerarrow.cpp
- swig/include/gdal_array.i
- Python bindings: GetArrowStreamAsNumPy(): fix reading fixed size list arrays that were ignoring the parent offset (affects Parquet)
- Python bindings: GetArrowStreamAsNumPy(): fix reading fixed width binary that were misusing the offset (affects Parquet)
- Python bindings: GetArrowStreamAsNumPy(): implement reading struct (s+) fields
- OGRLayer::CanPostFilterArrowArray(): allow filtering on struct fields (if the underlying type is supported), and allow compacting struct and list fields
- OGRLayer::CanPostFilterArrowArray(): allow compacting map fields
> ArrowArray filter improvements

- alg/gdal_alg_priv.h
- alg/gdalrasterize.cpp
- alg/llrasterize.cpp
- autotest/alg/rasterize.py
> [Backport release/3.7] Rasterize: avoid burning the same pixel twice in MERGE_ALG=ADD mode within a same geometry (fixes #8437)

- autotest/gcore/vsis3.py
- port/cpl_conv.cpp
- port/cpl_vsil.cpp
Note that nSourceSize==-1 must be passed if file size is unknown
> VSIFilesystemHandler::CopyFile(): detect wrong target file size w.r.t. source file size

- apps/ogr2ogr_lib.cpp
- autotest/utilities/test_ogr2ogr_lib.py
This helps workarounding an error in a scenario like: ogr2ogr "MSSQL:xxx" "MSSQL:xxx" -sql "SELECT * FROM foo" -nln bar -update Without -gt 0, this fails with
ERROR 1: Column ogr_geometry requested for geometry, but it does not exist. (and other subsequent errors)
This is obviously a workaround, not a proper fix
> ogr2ogr: fix -gt 0 to disable transactions

- autotest/gcore/vsizip.py
- port/cpl_vsil.cpp
> [Backport release/3.7] VSIReadDirRecursive(): make it work properly with a trailing slash (especially on /vsizip/) (fixes #8474)

- autotest/gcore/basic_test.py
- autotest/ogr/ogr_basic_test.py
- swig/include/Dataset.i
- swig/include/ogr.i
- swig/include/python/docs/gdal_dataset_docs.i
- swig/include/python/docs/ogr_datasource_docs.i
- swig/include/python/gdal_python.i
- swig/include/python/ogr_python.i
Exposes `GDALClose` through SWIG so that `DataSource` and `Dataset` objects can be explicitly closed. I named the method `Close` rather than `close` for consistency with the rest of the library. I do not expect this method to be used often. For most cases, a `with` block would be a better choice.
For `DataSource`, this is essentially a synonym of `Destroy`, except that it does not leave the object in a state where further use will cause a crash. Instead, further use will cause an unintuitive `TypeError`:
```
>>> ds.Close()
0
>>> ds.GetLayerCount()
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/home/dan/dev/build-gdal-Desktop-Debug/swig/python/osgeo/ogr.py", line 830, in GetLayerCount
return _ogr.DataSource_GetLayerCount(self, *args)
TypeError: in method …
```
> SWIG: Expose GDALClose

- autotest/ogr/ogr_gpkg.py
- autotest/pymod/gdaltest.py
Adds gdaltest.reopen helper
Makes ogr gpkg tests independent, parallel-safe
#4407
> autotest: Make ogr gpkg tests independent, parallel-safe

- autotest/ogr/ogr_basic_test.py
- doc/source/api/python_gotchas.rst
- swig/include/python/ogr_python.i
Avoids some scenarios that can produce a segfault.
> Python bindings: Avoid crashes when using orphaned Geometry refs

- doc/source/drivers/vector/flatgeobuf.rst
Cf thread at https://lists.osgeo.org/pipermail/gdal-dev/2023-September/057727.html
> Doc: flatgeobuf: document amount of RAM needed for packed Hilbert RTree building

- autotest/gcore/multidim.py
- frmts/zarr/zarrdriver.cpp
- gcore/gdal.h
- gcore/gdal_priv.h
- gcore/gdalmultidim.cpp
- swig/include/MultiDimensional.i
Add a BAND_METADATA options to papszOptions:
JSON serialized array defining which
arrays of the poRootGroup, indexed by non-X and Y
dimensions, should be mapped as band metadata items. Each array item should be an object with the
following members:
- "array": full name of a band parameter array. Such array must be a one dimensional array, and its dimension must be one of the dimensions of the array on which the method is called (excluding the X and Y dimensons).
- "item_name": band metadata item name
- "item_value": (optional) String, where "%[x][.y]f", "%[x][.y]g" or "%s" printf-like formatting can be used to format the corresponding value of the parameter array. The percentage character should be repeated: "%%" "${attribute_name}" can also be used to include the value of an attribute …
> GDALMDArray::AsClassicDataset(): allow to map band indexing arrays as band metadata items

- autotest/gdrivers/envi.py
- autotest/gdrivers/plmosaic.py
- frmts/raw/envidataset.cpp
- gcore/gdaldriver.cpp
and GDALDriver::DefaultCreateCopy(): in non-strict mode, turn (ignored) errors as warnings and do not silence them
Refs #8148
> ENVI: warn if assigning different nodata value to different bands

- autotest/gcore/vrt_read.py
- doc/source/drivers/raster/vrt.rst
- frmts/vrt/vrtdataset.cpp
Add `epo` and `eco` to allowed options for a "vrt://" connection.
> VRT 'eco' 'epo' for vrt:// connection

- cmake/modules/3.20/FindPostgreSQL.cmake
I'm not sure what the balance between this list of versions and the `PostgreSQL_ADDITIONAL_VERSIONS` configuration parameter is supposed to be, but superficially it makes sense to me that all the officially released versions should be in this list?
If there any argument against pulling this back into stable branches?
> Update the list of released PgSQL versions to the present

- autotest/ogr/ogr_flatgeobuf.py
- autotest/ogr/ogr_gpkg.py
- autotest/ogr/ogr_parquet.py
- ogr/ogrsf_frmts/flatgeobuf/ogrflatgeobuflayer.cpp
- ogr/ogrsf_frmts/generic/ograrrowarrayhelper.h
- ogr/ogrsf_frmts/gpkg/ogrgeopackagelayer.cpp
- ogr/ogrsf_frmts/gpkg/ogrgeopackagetablelayer.cpp
Fixes #8509
@jorisvandenbossche 
I've decided to uniformize the behavior of all drivers to immediately return a released array when there are no rows. The GeoPackage one was for example returning a non-released empty batch at the first iteration and then a released batch.
> FlatGeoBuf: ArrowStream: return a released array when there are no rows

- autotest/utilities/test_gdal_footprint.py
- autotest/utilities/test_gdal_grid_lib.py
- autotest/utilities/test_gdal_translate.py
- autotest/utilities/test_gdal_translate_lib.py
- autotest/utilities/test_gdalbuildvrt_lib.py
- autotest/utilities/test_gdaldem_lib.py
- autotest/utilities/test_gdalmdimtranslate_lib.py
- autotest/utilities/test_gdalwarp.py
- autotest/utilities/test_gdalwarp_lib.py
- autotest/utilities/test_ogr2ogr_lib.py
- swig/include/python/gdal_python.i
* Applies `tmp_vsimem` fixture to tests in `utilities` to avoid collisions when running tests in parallel (`pytest -n`)
* Adds `os.PathLike` handling to some arguments that were lacking it
> autotest: allow utilities tests to run in parallel

- autotest/cpp/test_gdal.cpp
- frmts/gdalallregister.cpp
- gcore/gdal.h
- gcore/gdal_priv.h
- gcore/gdaldrivermanager.cpp
This PR adds an exported `CPLErr GDALRegisterPlugin(const char *name)` function to
register a single plugin by name. Returns an error if either the plugin library
file was not found, or was found but did not contain a suitable plugin loading
function name, or if the plugin loading function CPLError'd.
Some of the plugin loading functionality has been copied over from 
`GDALDriverManager::AutoLoadDrivers()` instead of being refactored into
a single function as I deemed the return-on-error behavior was too messy to
unify.
> Add GDALRegisterPlugin function to register a single plugin by name

- apps/ogrinfo_lib.cpp
- autotest/ogr/data/gmlas/gmlas_test1.txt
- autotest/ogr/data/gmlas/real_world/output/EUReg.example.txt
- autotest/ogr/data/gmlas/real_world/output/Piezometre.06512X0037.STREMY.2.txt
- autotest/ogr/ogr_geojson.py
- autotest/ogr/ogr_gpkg.py
- autotest/utilities/test_ogrinfo_lib.py
- data/ogrinfo_output.schema.json
- ogr/ogr_api.h
- ogr/ogr_core.h
- ogr/ogr_feature.h
- ogr/ogr_p.h
- ogr/ogrfielddefn.cpp
- ogr/ogrsf_frmts/arrow_common/ogr_arrow.h
- ogr/ogrsf_frmts/arrow_common/ograrrowlayer.hpp
- ogr/ogrsf_frmts/arrow_common/ograrrowwriterlayer.hpp
- ogr/ogrsf_frmts/flatgeobuf/ogrflatgeobuflayer.cpp
- ogr/ogrsf_frmts/generic/ograrrowarrayhelper.cpp
- ogr/ogrsf_frmts/generic/ograrrowarrayhelper.h
- ogr/ogrsf_frmts/generic/ogrlayerarrow.cpp
- ogr/ogrsf_frmts/geojson/ogrgeojsonreader.cpp
- ogr/ogrsf_frmts/geojson/ogrgeojsonutils.cpp
- ogr/ogrsf_frmts/geojson/ogrgeojsonutils.h
- ogr/ogrsf_frmts/gpkg/ogr_geopackage.h
- ogr/ogrsf_frmts/gpkg/ogrgeopackagelayer.cpp
- ogr/ogrsf_frmts/gpkg/ogrgeopackagetablelayer.cpp
- ogr/ogrsf_frmts/parquet/ogrparquetlayer.cpp
- ogr/ogrutils.cpp
- swig/include/ogr.i
- Add OGRFieldDefn::GetTZFlag()/SetTZFlag(), and OGR_TZFLAG_ constants
- ogrinfo: output timezone flag
- GeoJSON reading: set field TZFlag
- ArrowStream interface: set timezone on schema (when known), and do necessary conversions (fixes #8460)
- Arrow/Parquet reading: set field TZFlag
> Add time zone flag property to OGRFieldDefn, and use it in ArrowStream interface

- autotest/pyscripts/test_gdalcompare.py
- doc/source/programs/gdalcompare.rst
- swig/python/gdal-utils/osgeo_utils/gdalcompare.py
- Multiple enhancements upstreamed from Planet's version:
* RPC metadata comparison (can be disabled with SKIP_RPC option)
* GEOLOCATION metadata comparison (disabled with SKIP_GEOLOCATION)
* Fix comparing NaN nodata values
* Dump differences of pixel content (enabled with DUMP_DIFFS option)
* Improve comparison of float32/float64 data by not just checking checksum but also statistics
* Overview comparison can be skipped with SKIP_OVERVIEWS
* Add sanity check when comparing pixel-interleave datasets with more than 10 bands since that can be slow.
- Binary comparison can be done on /vsi files now
- Command line utility: add ``-dumpdiffs``, ``-skip_binary``, ``-skip_overviews``, ``-skip_geolocation``, ``-skip_geotransform``, ``-skip_metadata``, ``-skip_rpc``, and ``-skip_srs`` options
- Add …
> gdalcompare.py: multiple enhancements

- autotest/ogr/ogr_sql_test.py
- ogr/ogrsf_frmts/generic/ogr_gensql.cpp
- ogr/swq.cpp
actually fix ef90e9fce2555836ff32f2b482d519913d5c78aa which only worked on string fields having numeric values...
Thanks to QGIS test suite to catch that...
> OGR SQL: fix min/max on string fields (master only)

- doc/source/user/virtual_file_systems.rst
- port/cpl_vsil_libarchive.cpp
ArcGIS Pro Project Package (`.ppkx`) files are another 7-zipped Esri archive format, very similar to Esri Layer Packages (`.lpkx`) and Esri Map Packages (`.mpkx`). We seem to be treating those extensions simply as synonyms to `.7z`. This PR simply adds `.ppkx` to that list in the code and documentation.
Depends on the work done in #7035 to add the `/vsi7z/` virtual file system.
> VSI7Z: Accept ArcGIS Pro Project Packages

- alg/gdaltransformer.cpp
- ogr/ogrct.cpp
- GDALSerializeReprojectionTransformer(): fallback to WKT2 for SourceCRS/TargetCRS if WKT1 cannot be used
- OGRProjCT::TransformBounds(): do not emit errors when trying to reproject points at poles
> Reprojection fixes

- apps/ogr2ogr_lib.cpp
- autotest/utilities/test_ogr2ogr_lib.py
That is when:
- the input driver reports OLCFastGetArrowStream
- and the output driver reports OLCFastWriteArrowBatch
- and the input ArrowSchema is accepted by the target layer
- and there are basically no ogr2ogr options (other than -dsco, -lco, -limit, -where and -spat).
Note that the efficiency in case of -where and -spat can be less than
using the classic OGRFeature strategy when the source is Parquet and a
lot of features are discarded.
With that Parquet->Parquet or GPKG->Parquet translation can be up to 3x times faster.
$ time ogr2ogr out.parquet nz-building-outlines.parquet --config OGR2OGR_USE_ARROW_API NO
real    0m11,246s
user    0m10,934s
sys     0m0,974s
$ time ogr2ogr out.parquet nz-building-outlines.parquet
real    0m4,311s
user    0m3,968s
sys     0m0,889s
$ time ogr2ogr …
> ogr2ogr: use Arrow interface in reading and writing when possible

- doc/source/drivers/raster/jpeg.rst
Minor typo in the documentation.
> jpeg.rst: Fix typo for bitmask: `valid date` → `valid data` [ci skip]

- frmts/gtiff/gtiffdataset_read.cpp
Fix a deadlock encountered with
gdalwarp test1.tif test2.tif -co  COMPRESS=LZW   -co TILED=YES  -co BLOCKXSIZE=256  -co  BLOCKYSIZE=256   -co   BIGTIFF=YES  -multi  -co  NUM_THREADS=ALL_CPUS out.tif -overwrite
on the test datasets provided in https://github.com/OSGeo/gdal/issues/8470#issuecomment-1760639682
> GTiff multithreaded reading/writing: fix a deadlock situation

- .github/workflows/cmake_builds.yml
- ci/travis/csa_common/before_install.sh
I can reproduce the PPA issue easily on Ubuntu 20.04 (22.04 works file), but adding by URL instead seems to fix it.
The signing key is taken from the PPA page.
https://lists.osgeo.org/pipermail/ubuntu/2023-October/002046.html
> CI: Add `ubuntugis` PPA by URL

- apps/ogr2ogr_lib.cpp
- autotest/cpp/test_ogr.cpp
- ogr/ogr_geometry.h
- ogr/ogrgeometrycollection.cpp
- ogr/ogrlinestring.cpp
- ogr/ogrmultilinestring.cpp
- ogr/ogrmultipolygon.cpp
- ogr/ogrpolygon.cpp
- ogr/ogrsf_frmts/generic/ogrlayerarrow.cpp
*   OGRLineString/Polygon/MultiPolygon/MultiLineString: make it possible to run importFromWkb() on the same object and limiting the number of dynamic memory (re)allocations
- For lines, we keep track of the maximum capacity of the point array,
with a new member variable.
So doing setNumPoints(10), then setNumPoints(3), then setNumPoints(9)
just allocates an array of size 10.
- For polygons, if importing a WKB for a single ring polygon on top of
an existing single ring polygon, reuse the existing ring (and benefit
from the previous optimization)
- For multipolygons, if importing a WKB for a single part multipolygon
on top of an existing single part multipolygon, reuse the existing
polygon (and benefit from the previous optimization)
- Similar for multilinestring
* WriteArrowBatch() generic …
> Speed improvements in WKB geometry import, and ogr2ogr

- autotest/gcore/vrt_read.py
- frmts/vrt/vrtdataset.h
- frmts/vrt/vrtfilters.cpp
- frmts/vrt/vrtsources.cpp
Add a specialization when a VRTComplexSource has only a <NODATA> value and no other processing (scaling, color table expansion, LUT), and that the source data type is Byte, UInt16, Int16
On a 3-band 20791x22938 Byte VRT, "gdal_translate in.vrt out.tif" goes from 9.8s to 4s
> VRTComplexSource: perf improvement: add specialization when only NODATA for Byte/UInt16/Int16 data types

- autotest/gdrivers/mbtiles.py
- frmts/mbtiles/mbtilesdataset.cpp
> [Backport release/3.7] MBTiles: BuildOverviews(): correctly set minzoom metadata (fixes #8565)

- .github/workflows/benchmarks/build.sh
- .github/workflows/benchmarks/test.sh
- .github/workflows/cmake_builds.yml
- .github/workflows/linux_build.yml
- autotest/CMakeLists.txt
- autotest/benchmark/conftest.py
- autotest/benchmark/test_gdalwarp.py
- autotest/benchmark/test_gtiff.py
- autotest/benchmark/test_ogr2ogr.py
- autotest/benchmark/test_ogr_gpkg.py
- autotest/conftest.py
- autotest/requirements.txt
- cmake/template/pytest.ini.in
- gdal.cmake
- scripts/setdevenv.sh
- Uses [pytest-benchmark](https://pytest-benchmark.readthedocs.io/en/latest/)
- Add a autotest/benchmark module (now with only a few tests for the GTiff and GPKG driver)
- Add a new CI benchmark configuration, which builds the current tree and a reference tree, and run the benchmark test suite in both
> CI: add benchmark test suite

- ogr/ogr_proj_p.cpp
@emlys could you try this patch on top of GDAL master or 3.7 branch and confirm it fixes your isse ?
> ogr_proj_p.cpp: disable pthread_atfork() optimization on MacOS (fixes #8497)

- ogr/ogr_proj_p.cpp
> [Backport release/3.7] ogr_proj_p.cpp: disable pthread_atfork() optimization on MacOS (fixes #8497)

- apps/ogr2ogr_lib.cpp
- autotest/utilities/test_ogr2ogr_lib.py
- ogr/ogrsf_frmts/generic/ogrlayerarrow.cpp
> ogr2ogr: preserve OFSTJSON when using ArrowArray code path

- doc/source/drivers/vector/wfs.rst
All the previously used services are not available anymore.
The one used for this update is a governmental service which is expected to be available for a long time.
Data license: 
https://spdx.org/licenses/DL-DE-ZERO-2.0.html
(Any use is permitted without restrictions or conditions.)
> WFS: Update doc examples with available service

- autotest/gcore/multidim.py
- autotest/gdrivers/netcdf_multidim.py
- frmts/hdf4/hdf4multidim.cpp
- frmts/hdf5/hdf5multidim.cpp
- frmts/mem/memdataset.cpp
- frmts/mem/memmultidim.h
- frmts/netcdf/netcdfmultidim.cpp
- frmts/vrt/vrtdataset.cpp
- frmts/vrt/vrtdataset.h
- frmts/vrt/vrtmultidim.cpp
- frmts/zarr/zarr.h
- frmts/zarr/zarr_group.cpp
- frmts/zarr/zarr_v2_array.cpp
- frmts/zarr/zarr_v2_group.cpp
- frmts/zarr/zarr_v3_array.cpp
- frmts/zarr/zarr_v3_group.cpp
- gcore/CMakeLists.txt
- gcore/gdal.h
- gcore/gdal_pam.h
- gcore/gdal_priv.h
- gcore/gdalmultidim.cpp
- gcore/gdalmultidim_gridded.cpp
- gcore/gdalmultidim_subsetdimension.cpp
- swig/include/MultiDimensional.i
Return a virtual group whose one dimension has been subset according to a selection.
The selection criterion is currently restricted to the form "/path/to/array=numeric_value" (no spaces around equal)
This is similar to XArray indexing by name and label on a XArray Dataset using the sel() method.
Cf https://docs.xarray.dev/en/latest/user-guide/indexing.html#quick-overview
For example on a EMIT L2A product
(https://github.com/nasa/EMIT-Data-Resources/blob/main/python/tutorials/Exploring_EMIT_L2A_Reflectance.ipynb), this can be used to keep only valid bands with
SubsetDimensionFromSelection("/sensor_band_parameters/good_wavelengths=1")
> Multidim API: add GDALGroup::SubsetDimensionFromSelection()

- .pre-commit-config.yaml
- autotest/ogr/ogr_gpkg.py
- ogr/ogrsf_frmts/gpkg/ogr_geopackage.h
- ogr/ogrsf_frmts/gpkg/ogrgeopackagetablelayer.cpp
- ogr/ogrsf_frmts/sqlite/CMakeLists.txt
- ogr/ogrsf_frmts/sqlite/sqlite_rtree_bulk_load/README
- ogr/ogrsf_frmts/sqlite/sqlite_rtree_bulk_load/sqlite_rtree_bulk_load.c
- ogr/ogrsf_frmts/sqlite/sqlite_rtree_bulk_load/sqlite_rtree_bulk_load.h
- ogr/ogrsf_frmts/sqlite/sqlite_rtree_bulk_load/wrapper.cpp
- ogr/ogrsf_frmts/sqlite/sqlite_rtree_bulk_load/wrapper.h
- scripts/clang-format.sh
- scripts/fix_typos.sh
With optimization:
```
$ time ogr2ogr tmp.gpkg nz-building-outlines.gpkg
real    0m16,433s
user    0m18,093s
sys     0m2,135s
```
vs without optimization with sqlite 3.43.2 (modified to integrate the disabling of RTree forced reinsertion from SQLite master https://github.com/sqlite/sqlite/commit/7de8ae22f7f895d5564f2f006d22e2dfddfdf5a7. Otherwise with stock 3.43.2, it is 38 seconds)
```
$ time OGR_GPKG_MAX_RAM_USAGE_RTREE=0 ogr2ogr tmp.gpkg nz-building-outlines.gpkg
real    0m28,000s
user    0m40,287s
sys     0m5,244s
```
Fixes #7614
The core functionality is available as a library in https://github.com/rouault/sqlite_rtree_bulk_load
> GPKG: use much faster creation of RTree with a in-memory RTree building

- autotest/gcore/tiff_write.py
- frmts/gtiff/tif_jxl.c
Fixes
```
2023-10-28T20:34:37.3586623Z gcore/tiff_write.py::test_tiff_write_jpegxl_band_combinations =================================================================
2023-10-28T20:34:37.3589811Z ==9962==ERROR: AddressSanitizer: memcpy-param-overlap: memory ranges [0x7f42ae19580f,0x7f42ae195813) and [0x7f42ae19580c, 0x7f42ae195810) overlap
2023-10-28T20:34:37.9301668Z     #0 0x7f42ceadd135 in memcpy (/usr/lib/llvm-10/lib/clang/10.0.0/lib/linux/libclang_rt.asan-x86_64.so+0x58135)
2023-10-28T20:34:38.3855796Z     #1 0x7f42c7865574 in JXLPreDecode /home/runner/work/gdal/gdal/frmts/gtiff/tif_jxl.c:525:13
2023-10-28T20:34:38.3865654Z     #2 0x7f42c736f8b3 in gdal_TIFFStartTile /home/runner/work/gdal/gdal/frmts/gtiff/libtiff/tif_read.c:1481:9
2023-10-28T20:34:38.3867385Z     #3 0x7f42c736ed71 …
```
> GTiff JXL codec: fix wrong use of memcpy() in decoding, and add memcpy() optimizations

- autotest/gcore/tiff_write.py
- frmts/gtiff/tif_jxl.c
> [Backport release/3.7] GTiff JXL codec: fix wrong use of memcpy() in decoding, and add memcpy() optimizations

- apps/ogr2ogr_lib.cpp
- autotest/utilities/test_ogr2ogr_lib.py
- ogr/ogrsf_frmts/generic/ogrlayerarrow.cpp
- ogr/ogrsf_frmts/mem/ogr_mem.h
- ogr/ogrsf_frmts/mem/ogrmemdatasource.cpp
> Arrow read/write: add GDAL specific field metadata

- autotest/gcore/vsifile.py
- port/cpl_vsil.cpp
- port/cpl_vsil_win32.cpp
Also: cpl_vsil_win32: implement a WRITE_THROUGH=YEs option to pass to VSIFOpenEx2L()
> cpl_vsil_win32: check return value of FlushFileBuffers(), and open file with GENERIC_WRITE only if access=w or wb

- doc/source/download.rst
- Makes sure mamba is installed in base conda environment
- Uses installation instructions based on their current stable version
Updates the mamba installation instructions according to [mamba's documentation for their stable release](https://mamba.readthedocs.io/en/stable/mamba-installation.html#existing-conda-install-not-recommended). I understand the caveat to the download instructions is that they are assuming that a user already has conda installed instead of starting from a fresh environment.
No issues have been opened for this. Would you like for me to include/add a section for if a user is wanting to install using `mamba` from an environment where conda isn't already installed? If so, I'd probably write up instructions for their …
> Documentation: Update mamba installation instructions in download.rst

- autotest/conftest.py
- autotest/gcore/overviewds.py
- autotest/gcore/vsicurl.py
- autotest/gcore/vsioss.py
- autotest/gcore/vsiswift.py
- autotest/gcore/vsiwebhdfs.py
- autotest/gdrivers/arg.py
- autotest/gdrivers/ecrgtoc.py
- autotest/gdrivers/ecw.py
- autotest/gdrivers/eedai.py
- autotest/gdrivers/idrisi.py
- autotest/gdrivers/kea.py
- autotest/ogr/ogr_carto.py
- autotest/ogr/ogr_fgdb.py
- autotest/ogr/ogr_mongodbv3.py
- autotest/ogr/ogr_mssqlspatial.py
- autotest/ogr/ogr_mvt.py
- autotest/ogr/ogr_ogdi.py
- autotest/ogr/ogr_refcount.py
- autotest/pymod/gdaltest.py
Addresses remaining issues so that tests within individual test files exercised by the Ubuntu 20.04 CI configuration can run in random order, except for `gnm` and `utilities/gdal2tiles`.
This does _not_ mean that we can run `pytest --random-order autotest` because there are a handful of cases of inter-module interference -- where running `test_driver2.py` before `test_driver1.py` causes something in `test_driver1.py` to fail. (Examples in https://github.com/dbaston/gdal/actions/runs/6714087188/job/18246767524#step:16:3630)
#4407
> autotest: make more tests run independently

- autotest/ogr/ogr_geos.py
- ogr/ogrgeometry.cpp
> exportToGEOS(): do not drop M dimension with GEOS >= 3.12 

- autotest/ogr/ogr_geojson.py
- ogr/ogrgeometryfactory.cpp
(fixes #8645)
This heuristics had been added in cef50ff7005, but it doesn't seem to be any longer needed since the added test case in that commit still pass without it.
> OGRGeometryFactory::transformWithOptions() WRAPDATELINE=YES: remove heuristics about points exactly at +/- 180

- apps/gdalwarp_lib.cpp
> gdalwarp: do not enter a specific COG optimized code path when some of its preconditons are not met

- port/cpl_minizip_zip.cpp
(CVE-2023-45853)
Backport of https://github.com/madler/zlib/pull/843
> cpl_zipOpenNewFileInZip3(): validate length of filename, comment and extrafields

- doc/source/development/rfc/rfc86_column_oriented_api.rst
- doc/source/tutorials/vector_api_tut.rst
- ogr/ogr_recordbatch.h
Fixes URLs in the docs to the Apache Arrow GitHub repository that reference the master branch instead of the current main branch. The master branch was renamed to main in 2022 and, while GitHub helpfully redirects outdated links, I think it would be good for these docs to reference the new branch.
None.
> Fix arrow repo URLs to reference main branch instead of master

- port/cpl_json.h
Fix build failure of reverse dependencies with GCC 13.
Per: http://gcc.gnu.org/gcc-13/porting_to.html
* gdal-grass:
https://github.com/OSGeo/gdal-grass/issues/32
* osmcoastline:
https://github.com/osmcode/osmcoastline/issues/46
* pktools:
https://savannah.nongnu.org/bugs/index.php?64873
* r-cran-sf:
https://github.com/r-spatial/sf/issues/2252
* OS: Debian unstable
* Compiler: GCC 13
> Include <cstdint> for uint64_t.

- port/cpl_json.h
Backport #8682
**Authored by:** @sebastic
> [Backport release/3.8] Include <cstdint> for uint64_t.

- scripts/install_bash_completions.cmake.in
A minor annoyance. `cmake --build . --target install` installs `prefix/share/bash-completion/completions/gdalinfo` but `cmake --build . --target uninstall` does not remove it.
Seem to be the only file which is not uninstalled.
> CMake: add gdalinfo bash-completion file to list of installed files

- apps/gdalwarp_lib.cpp
- autotest/utilities/test_gdalwarp_lib.py
- frmts/gtiff/cogdriver.cpp
- frmts/gtiff/cogdriver.h
> [Backport release/3.8] gdalwarp -of COG: use target SRS from -co TILING_SCHEME when specified (fixes #8684)

- ogr/ogrsf_frmts/s57/ogrs57driver.cpp
> [Backport release/3.8] S57: stricter dataset identification to avoid recognize S-101 datasets we don't handle

- scripts/install_bash_completions.cmake.in
Backport #8699
**Authored by:** @PPazderski
> [Backport release/3.8] CMake: add gdalinfo bash-completion file to list of installed files

- autotest/ogr/ogr_gpkg.py
- ogr/ogrsf_frmts/gpkg/ogrgeopackagetablelayer.cpp
Fix constraints on gpkg_data_columns are violated when AlterFieldDefn is called in some circumstances, eg when a comment is added after an alternative name has already been set on the field.
> [gpkg] Fix adding field comments after alternative name

- autotest/pyscripts/test_gdal2tiles.py
- autotest/pyscripts/test_gdal2xyz.py
- autotest/pyscripts/test_gdal_calc.py
- autotest/pyscripts/test_gdal_edit.py
- autotest/pyscripts/test_gdal_fillnodata.py
- autotest/pyscripts/test_gdal_merge.py
- autotest/pyscripts/test_gdal_pansharpen.py
- autotest/pyscripts/test_gdal_polygonize.py
- autotest/pyscripts/test_gdal_proximity.py
- autotest/pyscripts/test_gdal_retile.py
- autotest/pyscripts/test_gdal_sieve.py
- autotest/pyscripts/test_gdalcompare.py
- autotest/pyscripts/test_gdalmove.py
- autotest/pyscripts/test_ogr_layer_algebra.py
- autotest/pyscripts/test_ogrmerge.py
- autotest/pyscripts/test_pct.py
- swig/python/gdal-utils/osgeo_utils/gdal_sieve.py
- swig/python/gdal-utils/osgeo_utils/gdalattachpct.py
- swig/python/gdal-utils/osgeo_utils/gdalcompare.py
- swig/python/gdal-utils/osgeo_utils/gdalmove.py
> [Backport release/3.8] gdal_sieve.py/gdalattachpct.py/gdalcompare.py/gdalmove.py: make sure --version and --help return 0 error code (fixes #8717)

- doc/source/development/rfc/index.rst
- doc/source/development/rfc/rfc96_deferred_plugin_loading.rst
Partially rendered view [here](https://github.com/rouault/gdal/blob/rfc96_text/doc/source/development/rfc/rfc96_deferred_plugin_loading.rst)
> Add RFC96 text: Deferred C++ plugin loading

- autotest/ogr/ogr_pmtiles.py
- ogr/ogrsf_frmts/pmtiles/ogrpmtilesdataset.cpp
> [Backport release/3.8] PMTiles: avoid undefined-shift when zoom level is too big (fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=64234)

- ogr/ogrsf_frmts/sqlite/sqlite_rtree_bulk_load/sqlite_rtree_bulk_load.c
The PR fixes the build of `gdal` for systems where `__STDC_FORMAT_MACROS` has to be defined in order to use `PRI*` macros.
See also: https://trac.macports.org/ticket/68734
* OS: macOS 10.6
* Compiler: gcc13
P. S. Notice that while `gcc` advises to `#include <cinttypes>`, which indeed gonna work for it, some older macOS with clang will still be left broken. Defining instead `__STDC_FORMAT_MACROS` fixes all of them. Whether `<inttypes.h>` or `<cinttypes>` is used is then inconsequential.
> sqlite_rtree_bulk_load.c: define __STDC_FORMAT_MACROS

- ogr/ogrsf_frmts/sqlite/sqlite_rtree_bulk_load/sqlite_rtree_bulk_load.c
Backport #8748
**Authored by:** @barracuda156
> [Backport release/3.8] sqlite_rtree_bulk_load.c: define __STDC_FORMAT_MACROS

- cmake/helpers/configure.cmake
- cmake/template/cpl_config.h.in
- port/cpl_vsi_mem.cpp
Older systems/compilers (or combinations thereof) may not have all C++17 features implemented and checking for `__cplusplus >= 201703L` is apparently not enough.
That is the case on Mac with failing builds of MacOSX 10.7–10.11 as reported with https://trac.macports.org/ticket/68716 (resulting in `Undefined symbols for architecture x86_64:   "std::__1::__shared_mutex_base::lock_shared()" ...` build error).
The patch submitted here, where the presence and usability of `std::shared_mutex` is tested during configuration, is tested with and works for macOS 13 as well as MacOSX 10.7.
(The `check_cxx_source_compiles` code is shamelessly taken and modified from cppreference.com).
> Check availability of std::shared_mutex with configure build test

- apps/gdalwarp_lib.cpp
- autotest/utilities/test_gdalwarp_lib.py
- frmts/gtiff/cogdriver.cpp
> [Backport release/3.8] gdalwarp: add a heuristic to clamp northings when projecting from geographic to Mercator (typically EPSG:3857) (fixes #8730)

- autotest/cpp/test_ogr.cpp
- ogr/ogr_core.h
- ogr/ogrsf_frmts/gpkg/ogrgeopackagelayer.cpp
- ogr/ogrutils.cpp
> [Backport release/3.8] Add a OGRPARSEDATE_OPTION_LAX option to OGRParseDate() and use it when reading GPKG files (fixes #8759)

- apps/gdalwarp_bin.cpp
- apps/gdalwarp_lib.cpp
- make sure that progress for each source file goes to 100%
- display first progress bar after message about copying nodata values
> gdalwarp: progress bar tunings

- autotest/gdrivers/kea.py
- frmts/kea/keadataset.cpp
> [Backport release/3.8] KEA: Create(): error out if passing a /vsi file. avoids crashes (fixes #8743)

- autotest/gcore/rasterio.py
- gcore/rasterio.cpp
> [Backport release/3.8] RasterIO: fix subpixel shift when reading from overviews with non-nearest resampling

- apps/gdal_footprint_lib.cpp
- autotest/utilities/test_gdal_footprint_lib.py
> [Backport release/3.8] gdal_footprint: fix -ovr on RGBA datasets (fixes #8792)

- frmts/mrf/marfa_dataset.cpp
Fix a crash that occurs when MRF overviews are requested but are not allowed. For example, when the whole MRF contains a single tile.
* OS:
* Compiler:
> MRF: Avoid crashes when no overviews can be generated

- frmts/mrf/marfa_dataset.cpp
Backport #8803
**Authored by:** @lucianpls
> [Backport release/3.8] MRF: Avoid crashes when no overviews can be generated

- autotest/gcore/vrt_read.py
- doc/source/drivers/raster/vrt.rst
- frmts/vrt/vrtdataset.cpp
see #7477. overriding/setting the nodata value of a dataset is a useful shortcut
> VRT a_nodata for vrt:// connection

- autotest/ogr/ogr_csv.py
- ogr/ogrsf_frmts/csv/ogrcsvlayer.cpp
Fixes https://gis.stackexchange.com/questions/470855/integer-field-of-csv-file-always-output-as-string-when-processed-with-ogr2ogr
> CSV writer: do not quote integer fields by default (only if STRING_QUOTING=ALWAYS is specified)

- autotest/utilities/test_gdal_translate_lib.py
- gcore/gdaloverviewdataset.cpp
Fixes https://lists.osgeo.org/pipermail/gdal-dev/2023-November/057996.html
> GDALOverviewDataset::IRasterIO(): use parent dataset when possible for more efficiency

- .github/workflows/alpine/build.sh
- .github/workflows/cmake_builds.yml
- .github/workflows/fedora_rawhide/build.sh
- .github/workflows/ubuntu_20.04/build.sh
- .github/workflows/ubuntu_22.04/build.sh
- swig/python/CMakeLists.txt
- swig/python/install_python.cmake.in
- swig/python/setup.py.in
Fixes #8811
(on top of PR #8812)
> Python scripts: define entry_points.console_scripts to have launcher shell/exe scripts

- .github/workflows/cmake_builds.yml
- swig/python/setup.py.in
This is a follow-up of #8815 for Windows, and particularly to unbreak conda-forge builds that test the presence of the .py scripts.
Before this PR, "python setup.py install" would cause the following logs:
```
Installing gdal2tiles.py script to C:\Miniconda3\envs\test\conda-bld\gdal-split_1700841951001\_h_env\Scripts
[...]
Deleting C:\Miniconda3\envs\test\conda-bld\gdal-split_1700841951001\_h_env\Scripts\gdal2tiles.py
Installing gdal2tiles-script.py script to C:\Miniconda3\envs\test\conda-bld\gdal-split_1700841951001\_h_env\Scripts
Installing gdal2tiles.exe script to C:\Miniconda3\envs\test\conda-bld\gdal-split_1700841951001\_h_env\Scripts
```
This PR hacks around easy_install to avoid the deletiong of the .py script
> swig/python/setup.py.in: workaround easy_install behavior on Windows to keep .py scripts (fixes #8811)

- autotest/ogr/ogr_shape.py
- ogr/ogrsf_frmts/shape/dbfopen.c
- ogr/ogrsf_frmts/shape/shape2ogr.cpp
Fixes https://lists.osgeo.org/pipermail/gdal-dev/2023-November/058010.html
> Shapefile: recogize '      0' as a null date

- autotest/ogr/ogr_csv.py
- ogr/ogrsf_frmts/csv/ogrcsvlayer.cpp
> [Backport release/3.8] CSV writer: do not quote integer fields by default (only if STRING_QUOTING=ALWAYS is specified)

- autotest/utilities/test_gdal_translate_lib.py
- gcore/gdaloverviewdataset.cpp
> [Backport release/3.8] GDALOverviewDataset::IRasterIO(): use parent dataset when possible for more efficiency

- ogr/ogrsf_frmts/gpx/ogr_gpx.h
- ogr/ogrsf_frmts/gpx/ogrgpxdatasource.cpp
> [Backport release/3.8] GPX: make detection of <extensions> element more robust (fixes #8827)

- autotest/gcore/cog.py
- doc/source/drivers/raster/cog.rst
- frmts/gtiff/cogdriver.cpp
> [Backport release/3.8] COG: for JPEG compression, convert single band+alpha as single band JPEG + 1-bit mask band

- autotest/ogr/ogr_shape.py
- ogr/ogrsf_frmts/shape/dbfopen.c
- ogr/ogrsf_frmts/shape/shape2ogr.cpp
> [Backport release/3.8] Shapefile: recogize '      0' as a null date

- autotest/ogr/ogr_flatgeobuf.py
- doc/source/drivers/vector/flatgeobuf.rst
- ogr/ogrsf_frmts/flatgeobuf/ogr_flatgeobuf.h
- ogr/ogrsf_frmts/flatgeobuf/ogrflatgeobufdataset.cpp
- ogr/ogrsf_frmts/flatgeobuf/ogrflatgeobufeditablelayer.cpp
- ogr/ogrsf_frmts/flatgeobuf/ogrflatgeobuflayer.cpp
> FlatGeobuf: add support for reading and writing layer title, description and metadata

- frmts/jpegxl/jpegxl.cpp
This fixes a failure in test_jpegxl_lossless_copy_of_jpeg_with_mask_band()
> JPEGXL: add compatibility with latest libjxl git HEAD

- autotest/osr/osr_esri.py
> [Backport release/3.8] autotest: test_osr_esri_28(): make it robust when run against latest EPSG dataset version

- frmts/jpegxl/jpegxl.cpp
> [Backport release/3.8] JPEGXL: add compatibility with latest libjxl git HEAD

- autotest/gcore/vsis3.py
- port/cpl_aws.cpp
> [Backport release/3.8] /vsis3/: takes into account AWS_CONTAINER_CREDENTIALS_FULL_URI environment variable (fixes #8858)

- autotest/gdrivers/data/stacta/test.json
- autotest/gdrivers/stacta.py
- frmts/stacta/stactadataset.cpp
> [Backport release/3.8] STACTA: use GDAL_DISABLE_READDIR_ON_OPEN=EMPTY_DIR instead of CPL_VSIL_CURL_ALLOWED_EXTENSIONS

- port/cpl_vsil.cpp
Fixes some minor API documentation typos / cut-n-paste errors noted during other work.
No code changes.
N/A.
* OS:
* Compiler:
> port: minor apidoc cleanup

- ogr/ogrsf_frmts/pmtiles/ogrpmtileswriterdataset.cpp
When writing temporary mbtiles files the file extension has to be .mbtiles.
Otherwise the mbtiles generation fails with:
`ERROR 3: /tmp/ogr/US2EC03M.pmtiles_73_1 should have mbtiles extension`
in ogrmvtdataset.cpp:6067
> PMTiles: Correct extension for temp mbtiles file

- ogr/ogrsf_frmts/pmtiles/ogrpmtileswriterdataset.cpp
Backport #8892
**Authored by:** @anysomewhere
> [Backport release/3.8] PMTiles: Correct extension for temp mbtiles file

- autotest/pyscripts/test_pct.py
- swig/python/gdal-utils/osgeo_utils/pct2rgb.py
> [Backport release/3.8] pct2rgb.py: emit explicit exception when source file has no color table (fixes #8793)

- apps/gdal_translate_lib.cpp
- frmts/kmlsuperoverlay/kmlsuperoverlaydataset.cpp
- gcore/gdal_priv.h
- gcore/gdaldriver.cpp
> [Backport release/3.8] GDALTranslate(): avoid useless extra GDALOpen() call on a target GeoRaster (again)

- frmts/hdf5/gh5_convenience.cpp
- frmts/hdf5/hdf5multidim.cpp
- HDF5 multidim: better warning when nodata value is out of range
- HDF5 classic 2D API: handle char,ushort,uint,int64,uint64 attributes when reading them as double
> HDF5 related nodata tunings

- port/cpl_safemaths.hpp
> [Backport release/3.8] cpl_safemaths.hpp: fix compilation with clang targetting Windows (fixes #8898)

- autotest/gcore/vrt_read.py
- doc/source/drivers/raster/vrt.rst
- frmts/vrt/vrtdataset.cpp
Add `sd_name` and `sd` to allowed options for a "vrt://" connection.
online netcdf subdataset by name or number
```bash
gdalinfo "vrt:///vsicurl/https://www.ncei.noaa.gov/data/sea-surface-temperature-optimum-interpolation/v2.1/access/avhrr/202202/oisst-avhrr-v02r01.20220218.nc?sd_name=ice"
gdalinfo "vrt:///vsicurl/https://www.ncei.noaa.gov/data/sea-surface-temperature-optimum-interpolation/v2.1/access/avhrr/202202/oisst-avhrr-v02r01.20220218.nc?sd=4"
```
> VRT: 'sd_name' and 'sd' for vrt:// connection

- ogr/ogr_proj_p.cpp
> [Backport release/3.8] OSRPJContextHolder: call pthread_atfork() once for the process

- autotest/cpp/test_ogr.cpp
- autotest/cpp/test_ogr_wkb.cpp
- autotest/ogr/ogr_parquet.py
- ogr/ogr_core.h
- ogr/ogr_wkb.cpp
- ogr/ogr_wkb.h
- ogr/ogrsf_frmts/arrow_common/ogr_arrow.h
- ogr/ogrsf_frmts/arrow_common/ograrrowlayer.hpp
- ogr/ogrsf_frmts/gpkg/ogrgeopackageutility.cpp
- ogr/ogrsf_frmts/parquet/ogrparquetdatasetlayer.cpp
- OGREnvelope3D::Is3D(): fix it to work with MinZ/MaxZ initialization values
- Add OGRWKBGetEnvelope() with a OGREnvelope3D; also fix 2D version with POINT EMPTY
- GPKG: make OGRGeoPackageGetHeader() return bounding box without instanciating a OGRGeometry
- Arrow/Parquet: implement GetExtent3D()
CC @elpaso
> GetExtent3D(): fix & enhancements

- swig/include/python/typemaps_python.i
> [Backport release/3.8] Python bindings: add missing reference increment on Py_None in error case of Geometry.GetPoints() (fixes #8945)

- doc/source/programs/ogrinfo.rst
Not heeding the warning that I am putting on this man page will cause an "-rl is incompatible with -sql" error message.
I bet there are other man pages that need this warning too...
> -rl vs. -sql: warn now on the man page before the user attempts mixing the two

- autotest/cpp/test_gdal.cpp
- gcore/gdal.h
- gcore/gdal_priv.h
- gcore/gdalarraybandblockcache.cpp
- gcore/gdaldataset.cpp
- gcore/gdalhashsetbandblockcache.cpp
- gcore/gdalrasterband.cpp
DropCache() release cache blocks but does not write cache to disk. It is similar to FlushCache(true) but does not assume that the dataset will be closed.
proposal for #8938
> added DropCache to GDALDataset

- apps/gdal_footprint_bin.cpp
- apps/gdal_footprint_lib.cpp
- autotest/utilities/test_gdal_footprint_lib.py
- doc/source/programs/gdal_footprint.rst
- swig/include/python/gdal_python.i
New options:
```
.. option:: -location_field_name <field_name>
.. versionadded:: 3.9.0
Specifies the name of the field in the resulting vector dataset where the
path of the input dataset will be stored. The default field name is
"location". To prevent writing the path of the input dataset, use
:option:`-no_location`
.. option:: -no_location
.. versionadded:: 3.9.0
Turns off the writing of the path of the input dataset as a field in the
output vector dataset.
.. option:: -write_absolute_path
.. versionadded:: 3.9.0
Enables writing the absolute path of the input dataset. By default, the
filename is written in the location field exactly as specified on the
command line.
```
First commit is a bugfix that must be backported
> gdal_footprint: write source dataset path in a 'location' field (fixes #8795)     

- apps/gdal_translate_bin.cpp
- apps/gdal_translate_lib.cpp
- autotest/utilities/test_gdal_translate_lib.py
- doc/source/programs/gdal_translate.rst
- port/cpl_string.cpp
- port/cpl_string.h
- swig/include/python/gdal_python.i
adds `-dmo` for adding one or more domain specific metadata items, as a complement to `-mo` which adds `metadata=value` items, we can specify `domain:metadata=value` with dmo, e.g. 
```bash
gdal_translate in.tif out.vrt -dmo DOMAIN:METATAG1=VALUE1 -dmo DOMAIN:METATAG1=VALUE
```
(note that random domains won't be reported by gdalinfo, so the effect may not be obvious without looking at the VRT file or querying the dataset). 
The motivating example is to add GEOLOCATION domain elements, e.g. 
```bash
gdal_translate in.tif out.vrt -dmo GEOLOCATION:X_DATASET=x.tif -dmo GEOLOCATION:Y_DATASET=y.tif ...
```
Discussed on the mailing list: https://lists.osgeo.org/pipermail/gdal-dev/2023-September/057665.html
Also removed outdated comments: …
> gdal_translate: add -dmo option, for domain-metadata items

- .github/workflows/cmake_builds.yml
- ci/travis/conda/0001-Fix-build-of-Python-bindings-due-to-https-github.com.patch
- ci/travis/conda/setup.sh
- ci/travis/osx/before_install.sh
- ci/travis/osx/install.sh
- swig/python/CMakeLists.txt
- swig/python/README.rst
- swig/python/pyproject.toml
- swig/python/setup.py.in
Fixes #8069.
Hopefully a compromise that will satisfy most needs...
- add a pyproject.toml with numpy as a build requirement
- make absence of numpy at build time an error by default, unless the GDAL_PYTHON_BINDINGS_WITHOUT_NUMPY env var is set
- despite numpy being a build requirement, numpy remains an optional dependency at install time if users just install with "pip install gdal" (for folks that would do vector only operations with GDAL)
- for people needing numpy support, they have to use "pip install gdal[numpy]".
Demo:
```
$ pip list
Package       Version
------------- -------
pip           20.0.2 
pkg-resources 0.0.0  
setuptools    44.0.0 
$ pip install -v dist/GDAL-3.9.0.tar.gz
[...]
Collecting oldest-supported-numpy
[...]
Successfully installed GDAL-3.9.0
[...]
```
```
$ pip …
```
> Python bindings: add a pyproject.toml with numpy as a build requirement

- port/cpl_vsisimple.cpp
> CPLGetPhysicalRAM(): fix getting right value when running inside Docker on a cgroups v1 system (like Amazon Linux 2) 

- frmts/vrt/vrtsources.cpp
(fixes #8967, 3.8.0 regression)
m_abyWrkBuffer and m_abyWrkBufferMask were mistakenly put at the VRTComplexSource level, missing that there can be a big number of sources whose lifetime is the same as the VRT dataset, and thus it is inappropriate to have long-lived working buffers at that level.
In master, this is changed to actually use one single instance of them for all sources, placed at the dataset level. In that branch, we can't do that as it would break ABI. So instead clear them after their immediate use (like was done in GDAL < 3.8)
Master fix in https://github.com/OSGeo/gdal/pull/8969
> [3.8 fix] VRTComplexSource: fix excessive RAM usage with many sources (fixes #8967, 3.8.0 regression)

- port/cpl_vsisimple.cpp
> [Backport release/3.8] CPLGetPhysicalRAM(): fix getting right value when running inside Docker on a cgroups v1 system (like Amazon Linux 2) 

- frmts/postgisraster/postgisrasterrasterband.cpp
- frmts/vrt/vrtdataset.h
- frmts/vrt/vrtderivedrasterband.cpp
- frmts/vrt/vrtfilters.cpp
- frmts/vrt/vrtmultidim.cpp
- frmts/vrt/vrtsourcedrasterband.cpp
- frmts/vrt/vrtsources.cpp
(fixes #8967, 3.8.0 regression)
m_abyWrkBuffer and m_abyWrkBufferMask were mistakenly put at the VRTComplexSource level, missing that there can be a big number of sources whose lifetime is the same as the VRT dataset, and thus it is inappropriate to have long-lived working buffers at that level. We can actually use one single instance of them for all sources, so move that at the dataset level.
> VRTComplexSource: fix excessive RAM usage with many sources (fixes #8967, 3.8.0 regression)

- apps/gdaladdo.cpp
- autotest/gcore/tiff_ovr.py
- autotest/pyscripts/test_gdalcompare.py
- autotest/utilities/test_gdaladdo.py
- doc/source/programs/gdaladdo.rst
- frmts/gtiff/gt_overview.cpp
- frmts/gtiff/gtiffdataset_write.cpp
- gcore/gdal_priv.h
- gcore/gdaldefaultoverviews.cpp
- GTiff overviews: generalize saving resampling method in a RESAMPLING metadata item
- gdaladdo: reuse previous resampling method (from GTiff RESAMPLING metadata item) if not specifying -r and overview levels if not specifying them
> Overview: save resampling method, and reuse it in gdaladdo

- apps/gdalbuildvrt_lib.cpp
> [Backport release/3.8] gdalbuildvrt: in -separate mode, only use ComplexSource if needed

- ogr/ogrsf_frmts/generic/ogrlayerarrow.cpp
- ogr/ogrsf_frmts/openfilegdb/ogropenfilegdbdatasource.cpp
- ogr/ogrutils.cpp
- ogr/utf8.h
- port/cpl_alibaba_oss.cpp
- port/cpl_alibaba_oss.h
- port/cpl_aws.cpp
- port/cpl_aws.h
- port/cpl_aws_win32.cpp
- port/cpl_azure.cpp
- port/cpl_azure.h
- port/cpl_google_cloud.cpp
- port/cpl_google_cloud.h
- port/cpl_swift.cpp
- port/cpl_swift.h
- port/cpl_vsil_adls.cpp
- port/cpl_vsil_az.cpp
- port/cpl_vsil_curl.cpp
- port/cpl_vsil_curl_class.h
- port/cpl_vsil_curl_streaming.cpp
- port/cpl_vsil_gs.cpp
- port/cpl_vsil_oss.cpp
- port/cpl_vsil_s3.cpp
- port/cpl_vsil_swift.cpp
- port/cpl_vsil_webhdfs.cpp
> VSICurl and derived: replace most uses of CPLString with std::string

- doc/source/drivers/vector/csv.rst
The CSV: prefix negates the sentence I removed, so I removed it.
> CSV: prefix available, so remove outdated conflicting sentence.

- apps/ogr2ogr_lib.cpp
- autotest/utilities/test_ogr2ogr_lib.py
> [Backport release/3.8] ogr2ogr: do not use ArrowArray interface if -clipsrc, -clipdst, -gcp or -wrapdateline are specified (fixes #9013)

- apps/gdal2ogr.c
Fixes compilation error in `apps/gdal2ogr.c`
**NB** Syntax error also exists in `release/3.8` branch
N/A
N/A - simple syntax error
* OS: All
* Compiler: All
> gdal2ogr.c: added missing close bracket

- autotest/ogr/ogr_gpkg.py
- doc/source/drivers/vector/gpkg.rst
- ogr/ogrsf_frmts/gpkg/ogrgeopackagetablelayer.cpp
Fixes https://lists.osgeo.org/pipermail/gdal-dev/2024-January/058177.html and https://github.com/OSGeo/gdal/pull/9018#issuecomment-1876879776
> GPKG: fix multi-threaded ArrowArray interface and re-enable it by default

- autotest/gdrivers/jpegxl.py
https://github.com/libjxl/libjxl/commit/815858b2335c267727c4b438cfdc00d5499791e0 slightly changed how lossy JXL is decoded
> jpegxl.py: make test pass with latest libjxl master

- autotest/gdrivers/jpegxl.py
> [Backport release/3.8] jpegxl.py: make test pass with latest libjxl master

- cmake/helpers/configure.cmake
- cmake/template/cpl_config.h.in
- ogr/ogrsf_frmts/geojson/libjson/random_seed.c
> [Backport release/3.8] Internal libjson: resync random_seed.c with upstream, and use getrandom() implementation when available (fixes #9024)

- autotest/ogr/ogr_gpkg.py
- doc/source/drivers/vector/gpkg.rst
- ogr/ogrsf_frmts/gpkg/ogrgeopackagetablelayer.cpp
> [Backport release/3.8] GPKG: fix multi-threaded ArrowArray interface and re-enable it by default

- autotest/ogr/ogr_geojson.py
- ogr/ogrsf_frmts/geojson/ogr_geojson.h
- ogr/ogrsf_frmts/geojson/ogrgeojsonlayer.cpp
- ogr/ogrsf_frmts/geojson/ogrgeojsonreader.cpp
- ogr/ogrsf_frmts/geojson/ogrgeojsonreader.h
Followup https://github.com/OSGeo/gdal/pull/8806, adds a "fast" implementation for `GetExtent3D` and `GetExtent`
> GEOJSON: GetExtent3D "fast" implementation 

- autotest/gdrivers/tiledb_write.py
- autotest/ogr/ogr_tiledb.py
- frmts/tiledb/tiledbdense.cpp
- frmts/tiledb/tiledbsparse.cpp
TileDB is a multi-modal array database with applications outside of geospatial, this PR adds tagging to the array so that the array can be easily recognized by other TileDB client libraries. Currently `raster`, `geometry` and `pointcloud` are used for geospatial array tags.
None within GDAL.
> Added tiledb metadata fields to easily tag array type

- autotest/ogr/ogr_openfilegdb_write.py
- ogr/ogrsf_frmts/openfilegdb/ogropenfilegdblayer_write.cpp
Since ArcGIS Pro only handles "polyline", and there is no distinction between "esriGeometyLine" and "esriGeometryPolyline", this pull request sets the feature class XML <ShapeType> metadata to "esriGeometryPolyline" any time TARGET_ARCGIS_VERSION=ARCGIS_PRO_3_2_OR_LATER is used as a layer creation option. 
https://pro.arcgis.com/en/pro-app/latest/arcpy/classes/geometry.htm
* OS:
* Compiler:
> OpenFileGDB: set xml shape type to "esriGeometryPolyline" when using arc pro layer creation options

- autotest/ogr/ogr_csv.py
- ogr/ogrsf_frmts/csv/ogrcsvlayer.cpp
(fixes https://github.com/qgis/QGIS/issues/55808)
> CSV: do not quote numeric fields even if STRING_QUOTING=ALWAYS (3.8.1 regression) 

- autotest/ogr/ogr_mem.py
- swig/include/ogr.i
- swig/include/python/ogr_python.i
@kylebarron Just seeing your yesterday toot https://mapstodon.space/@kylebarron/111723196242600250 , I gave this a try. I don't necessarily have a way to test that beyond the simple unit tests I added
> Python bindings: implement __arrow_c_stream__() interface for ogr.Layer

- autotest/gcore/numpy_rw_multidim.py
No changes in the bindings themselves apparently needed
> autotest: make it compatible with current numpy 2.0dev

- apps/gdal_footprint_lib.cpp
- apps/gdalwarp_lib.cpp
- apps/ogr2ogr_lib.cpp
- autotest/gcore/multidim.py
- autotest/osr/osr_ct.py
- frmts/vrt/vrtwarped.cpp
- gcore/gdalmultidim.cpp
- gcore/gdalmultidim_gltorthorectification.cpp
- ogr/ogr_spatialref.h
- ogr/ogrct.cpp
- ogr/ogrsf_frmts/dwg/ogrdwglayer.cpp
- ogr/ogrsf_frmts/dxf/ogr_dxf.h
- ogr/ogrsf_frmts/dxf/ogrdxf_ocstransformer.cpp
- OGRCoordinateTransformation::Transform(): change nCount parameter to size_t (C++ API only for now) (fixes #9074)
- OGRProjCT::TransformWithErrorCodes(): Improve performance of axis swapping (inspired by @SunBlack proposal) (fixes #9073)
> OGRCoordinateTransformation::Transform(): change nCount parameter to size_t, and optimize performance of axis swapping

- apps/gdalwarp_lib.cpp
- autotest/utilities/test_gdalwarp_lib.py
> gdalwarp: do not enable blank line detection when -tap and -te are specified (fixes #9059)

- autotest/ogr/ogr_csv.py
- ogr/ogrsf_frmts/csv/ogrcsvlayer.cpp
> [Backport release/3.8] CSV: do not quote numeric fields even if STRING_QUOTING=ALWAYS (3.8.1 regression) 

- ogr/ogrsf_frmts/sqlite/ogrsqliteexecutesql.cpp
- ogr/ogrsf_frmts/sqlite/ogrsqlitevirtualogr.cpp
> [Backport release/3.8] OGR2SQLITE_Setup(): robustify against potential crashing scenario

- apps/gdalwarp_lib.cpp
- autotest/utilities/test_gdalwarp_lib.py
> [Backport release/3.8] gdalwarp: do not enable blank line detection when -tap and -te are specified (fixes #9059)

- .github/workflows/android_cmake/start.sh
- .github/workflows/mingw_w64/start.sh
GHA workers have now 4 vCPUs: https://github.blog/2024-01-17-github-hosted-runners-double-the-power-for-open-source/
> CI: avoid hardcoding -j3

- doc/source/drivers/vector/geojsonseq.rst
Removed link to ndjson.org as the author of it has abandoned the domain and it's now being used for hosting malware.
Removes the link to ndjson.org
[This issue in the ndjson repo,](https://github.com/ndjson/ndjson.github.io/issues/24) explains that the domain has been abandoned.
> Remove link to ndjson.org as it's now hosting malware

- autotest/gdrivers/sentinel2.py
- doc/source/drivers/raster/sentinel2.rst
- frmts/sentinel2/sentinel2dataset.cpp
also: doc: adjust description of content of L2A subdatasets (fixes #9066)
@an-ivanov you contributed in #2024 support for L2A for SAFE_COMPACT format. Is there any reason you didn't include AOT and WVP for the 10m subdataset? They were present in the test dataset of our autotest suite, as well as in the dataset of #9066, hence my attempt at adding them here
> Sentinel2: include 10m AOT and WVP bands in 10m subdataset

- cmake/helpers/configure.cmake
- cmake/template/cpl_config.h.in
- frmts/grib/degrib/degrib/clock.c
- frmts/netcdf/netcdfdataset.cpp
- frmts/pcidsk/sdk/core/pcidsk_utils.cpp
- ogr/ogrsf_frmts/cad/libopencad/cadheader.cpp
- port/cpl_vsisimple.cpp
> [Backport release/3.8] Restore use of gmtime_r and localtime_r; extend to ctime_r; use Windows variants too

- autotest/ogr/ogr_mem.py
- swig/include/ogr.i
- swig/include/python/ogr_python.i
> Python bindings: add a ogr.Layer.WriteArrow() method consuming __arrow_c_stream__ or __arrow_c_array__ interfaces

- autotest/pyscripts/test_gdal_edit.py
- doc/source/programs/gdal_edit.rst
- doc/source/user/coordinate_epoch.rst
- swig/python/gdal-utils/osgeo_utils/gdal_edit.py
Add new options to `gdal_edit.py` that will add, update or remove a user-defined coordinate epoch from the dataset SRS.  Updated documentation.  
https://lists.osgeo.org/pipermail/gdal-dev/2024-January/058314.html
* OS:
* Compiler:
> gdal_edit: add -a_coord_epoch option and update doc

- autotest/gcore/vsifile.py
- autotest/gcore/vsis3.py
- port/cpl_vsil.cpp
- port/cpl_vsil_s3.cpp
- port/cpl_vsil_win32.cpp
- Open(): turn "\\foo\bar" (network file path) to "\\?\UNC\foo\bar" (derived from patch by @rprinceley)
- Stat(): make it work with directories for extended filenames
- VSIReadDirRecursive() / NextDirEntry(): make it work with directories for extended filenames
- Sync(): make it work with directories for extended filenames
- Add tests
> Win32 extended filenames (starting with "\\?\"): various fixes; add support for network UNC paths

- autotest/ogr/ogr_gpkg.py
- ogr/ogrsf_frmts/gpkg/ogr_geopackage.h
- ogr/ogrsf_frmts/gpkg/ogrgeopackagedatasource.cpp
- ogr/ogrsf_frmts/gpkg/ogrgeopackagetablelayer.cpp
> GPKG: fixes to make most operations compatible with PRAGMA foreign_keys=1 

- autotest/ogr/ogr_gpkg.py
- ogr/ogrsf_frmts/gpkg/ogr_geopackage.h
- ogr/ogrsf_frmts/gpkg/ogrgeopackagetablelayer.cpp
Adresses remark of https://github.com/qgis/QGIS/pull/55320#discussion_r1467859166
> GPKG creation: set Z/M columns of gpkg_geometry_columns when there are Z/M geometries in a 2D declared layer

- frmts/exr/exrdataset.cpp
- frmts/plmosaic/plmosaicdataset.cpp
- frmts/wmts/wmtsdataset.cpp
- ogr/ogrsf_frmts/gpkg/ogrgeopackagedatasource.cpp
Metadata files would still be created even when `GDAL_PAM_ENABLED NO` config was used. In my case I had a GPKG raster with overviews and `gdalinfo raster_w_overviews.gpkg --config GDAL_PAM_ENABLED NO` resulted in a bunch of zoom.aux.xml files being created. 
The PAM-flags were completely reset in some cases in the code, so the GPF_ENABLED flag was ignored if it had been set on initialization.
I saw that the handling in some places were to only unset the GPF_DIRTY flag, so I replaced all the hard resets with only unsetting the 'dirty' flag, figured this was maybe the intention behind the hard resets
> PAM only unset GPF_DIRTY flag

- ogr/ogrsf_frmts/pg/ogrpgtablelayer.cpp
The changes from OSGeo/gdal#8965 added SQL commands including a DROP FUNCTION that omits parenthesis.  That's legal on all supported versions of PG but the parenthesis were required before PG 10.  While I'm sure PG 9.X is not officially supported by GDAL, there's no harm in including the parenthesis and it helps those of us who've fallen a bit behind on PG updates.
Adds parenthesis to ``````DROP FUNCTION`
OSGeo/gdal#8965
* Postgresql: <10
> PG: Avoid new SQL for GDAL multidomain metadata serialization breaking old versions of postgresql

- autotest/gdrivers/gpkg.py
- doc/source/drivers/raster/gpkg.rst
- gcore/tilematrixset.cpp
- ogr/ogrsf_frmts/gpkg/ogrgeopackagedatasource.cpp
- ogr/ogrsf_frmts/gpkg/ogrgeopackagedriver.cpp
Also TileMatrixSet::parse(): increase maximum zoom level for InspireCRS84Quad to 29
> GPKG: support maximum level up to 29 or 30; add a ZOOM_LEVEL creation option

- autotest/ogr/ogr_mysql.py
- ogr/ogrsf_frmts/mysql/ogrmysqltablelayer.cpp
(fixes qgis/QGIS#55463)
It seems spatial predicates are not directly usable when using geographic SRS. For some reason
```sql    
select MBRIntersects(ST_GeomFromText('POLYGON((-90 -90, 90 -90, 90 90, -90 90, -90 -90))', 4326), ST_GeomFromText('POINT(0 0)', 4326));
```
returns true as expected
But
```sql    
select MBRIntersects(ST_GeomFromText('POLYGON((-179 -89, 179 -89, 179 89, -179 89, -179 -89))', 4326, 'axis-order=long-lat'), ST_GeomFromText('POINT(0 0)', 4326));
```
returns false !!!!
And
```sql    
select MBRIntersects(ST_GeomFromText('POLYGON((-179 -89, 179 -89, 179 89, -179 89, -179 -89))', 32631), ST_GeomFromText('POINT(0 0)', 32631));
```
returns true as expected
Consequence, we need to force a projected SRS for the arguments of MBRIntersects()
> MySQL: fix/workaround server-side spatial filtering when SRS is geographic with MySQL >= 8 (fixes qgis/QGIS#55463)

- autotest/ogr/ogr_mysql.py
- ogr/ogrsf_frmts/mysql/ogrmysqltablelayer.cpp
> [Backport release/3.8] MySQL: fix/workaround server-side spatial filtering when SRS is geographic with MySQL >= 8 (fixes qgis/QGIS#55463)

- autotest/cpp/test_ogr.cpp
- autotest/ogr/ogr_factory.py
- ogr/ogrgeometryfactory.cpp
Found by CIFuzz: https://github.com/OSGeo/gdal/actions/runs/7740101693/job/21105197876?pr=9166
> OGRGeometryFactory::forceTo(): fix assertion with empty geometry and target type = unknown

- autotest/cpp/test_ogr.cpp
- autotest/ogr/ogr_factory.py
- ogr/ogrgeometryfactory.cpp
> [Backport release/3.8] OGRGeometryFactory::forceTo(): fix assertion with empty geometry and target type = unknown

- docker/ubuntu-full/Dockerfile
This works around an apparent dependency bug in `libarrow-dataset-dev`, by first explicitly installing the matching version of `libarrow-acero-dev`.
Changes the `Dockerfile` to install `libarrow-acero-dev` first, with the correct version (`${ARROW_VERSION}`), before installing `libarrow-dataset-dev`.
If this is not done, installing a specific version of `libarrow-dataset-dev` seems to try to install the _latest_ version of `libarrow-acero-dev`, instead of the one with matching version, and this makes `apt-get install` fail.
An advantage with this fix, compared to bumping `ARROW_VERSION` to the currently latest version of Apache Arrow (`libarrow-dataset-dev` et al.) is that "the currently latest version of Apache Arrow" can change at any time depending on the Apache Arrow release schedule, …
> docker/ubuntu-full/Dockerfile: pin libarrow-acero-dev version (fixes #9183)

- autotest/ogr/data/kml/gx_track_without_when.kml
- autotest/ogr/ogr_libkml.py
- ogr/ogrsf_frmts/libkml/ogrlibkmlfield.cpp
> LIBKML: fix crash on a gx:Track without when subelements (fixes qgis/qgis#55963)

- port/cpl_vsil_curl.cpp
- port/cpl_vsil_curl_class.h
If 2 threads tried to download the same region at the same time, one of them would wait for the first one to have finished. But if that download failed, the waiting thread would then wrongly try to unregister the region in m_oMapRegionInDownload (the first thread has already done that), resulting in either an assertion in debug mode on ```CPLAssert(oIter != m_oMapRegionInDownload.end())``` in NotifyStopDownloadRegion() or a crash later when trying to lock region.oMutex which would be random data.
> /vsicurl/: fix potential multithreaded crash when downloading the same region in parallel and that the download fails

- autotest/gdrivers/pdf.py
- frmts/pdf/pdfdataset.cpp
> [Backport release/3.8] PDF: correctly initialize PAM when opening a subdataset (specific page for example)

- autotest/ogr/data/kml/gx_track_without_when.kml
- autotest/ogr/ogr_libkml.py
- ogr/ogrsf_frmts/libkml/ogrlibkmlfield.cpp
> [Backport release/3.8] LIBKML: fix crash on a gx:Track without when subelements (fixes qgis/qgis#55963)

- autotest/cpp/test_cpl.cpp
- port/cpl_strtod.cpp
> [Backport release/3.8] CPLAtof()/CPLStrtod(): recognize again INF and -INF

- port/cpl_vsil_curl.cpp
- port/cpl_vsil_curl_class.h
> [Backport release/3.8] /vsicurl/: fix potential multithreaded crash when downloading the same region in parallel and that the download fails

- frmts/pdf/pdfreadvectors.cpp
The content within the array should be completely ignored Fixes https://lists.osgeo.org/pipermail/gdal-dev/2024-February/058419.html
> PDF vector stream parser: correcly parse structures like '[3 3.5] 0 d '

- frmts/pdf/pdfreadvectors.cpp
> [Backport release/3.8] PDF vector stream parser: correcly parse structures like '[3 3.5] 0 d '

- frmts/mrf/mrf_band.cpp
Better and faster in most cases
Change from the ZSTD simple API to the ZSTD streaming API for compression.
See discussion at https://github.com/facebook/zstd/issues/3729
* OS:
* Compiler:
> MRF: Use ZSTD streaming API for compression

- apps/gdalbuildvrt_bin.cpp
- apps/gdalbuildvrt_lib.cpp
- autotest/utilities/test_gdalbuildvrt_lib.py
- doc/source/drivers/raster/vrt.rst
- doc/source/programs/gdalbuildvrt.rst
- frmts/vrt/data/gdalvrt.xsd
- frmts/vrt/vrtdataset.h
- frmts/vrt/vrtdriver.cpp
- frmts/vrt/vrtsources.cpp
- swig/include/python/gdal_python.i
The NoDataFromMaskSource is derived from the SimpleSource and shares the same properties except that it replaces the value of the source with the value of the NODATA child element when the value of the mask band of the source is less or equal to the MaskValueThreshold child element.
Also add a --nodata_max_mask_threshold <threshold> option to gdalbuildvrt
Example:
```
$ gdal_translate autotest/gcore/data/stefan_full_rgba.tif in.tif -a_srs EPSG:4326 -a_ullr -180 90 180 -90
$ gdalbuildvrt nodatafrommask.vrt in.tif -nodata_if_mask_less_or_equal 128 -vrtnodata 0
$ cat nodatafrommask.vrt
<VRTDataset rasterXSize="162" rasterYSize="150">
<SRS dataAxisToSRSAxisMapping="2,1">GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]], …
```
> VRT: add a NoDataFromMaskSource source

- frmts/tiledb/tiledbcommon.cpp
- frmts/tiledb/tiledbdrivercore.cpp
- ogr/ogrsf_frmts/shape/ogrshapedriver.cpp
Relates to https://github.com/conda-forge/tiledb-feedstock/issues/228
> Identification tunings in TileDB and Shapefile drivers

- .github/workflows/cmake_builds.yml
- autotest/gcore/vsifile.py
- autotest/gcore/vsis3.py
- frmts/zarr/zarr_array.cpp
- port/cpl_path.cpp
- port/cpl_vsi.h
- port/cpl_vsi_virtual.h
- port/cpl_vsil.cpp
- port/cpl_vsil_s3.cpp
- port/cpl_vsil_win32.cpp
*  Add VSIGetDirectorySeparator() to return the directory separator for the specified path
Default is forward slash. The only exception currently is the Windows
file system which returns anti-slash, unless the specified path is of the
form "{drive_letter}:/{rest_of_the_path}".
*  CPLFormFilename(), CPLProjectRelativeFilename(), VSIReadDirRecursive(), NextDirEntry(): useVSIGetDirectorySeparator()
For VSIReadDirRecursive() and NextDirEntry(), this will be a slight
change in behavior on Windows where antislash separator will now be
returned unless an absolute path of the form X:/foo is provided
*  /vsis3 Sync(): use VSIGetDirectorySeparator(),
and normalize target filename to the dir separator of the target
filesystem.
This fixes synchronization from Windows extended filenames with …
> Add VSIGetDirectorySeparator() and related changes

- doc/source/api/python/osgeo.gdal.rst
- gcore/gdaldataset.cpp
- gcore/gdalrasterband.cpp
- gcore/overview.cpp
- swig/include/python/docs/gdal_band_docs.i
- swig/include/python/docs/gdal_dataset_docs.i
- swig/include/python/gdal_python.i
- swig/python/CMakeLists.txt
Adds docstrings for most methods of `gdal.Dataset` and `gdal.Band`.
> Doc: Add Python API docs for gdal.Dataset, gdal.Band

- autotest/gdrivers/vrtderived.py
- frmts/vrt/vrtderivedrasterband.cpp
Avoid assertion failure in when using Python pixel function with bands of int8 and (u)int64 types.
> VRTDerivedRasterBand: Support Int8, (U)Int64 with Python pixel functions

- autotest/gdrivers/vrtderived.py
- frmts/vrt/vrtderivedrasterband.cpp
> [Backport release/3.8] VRTDerivedRasterBand: Support Int8, (U)Int64 with Python pixel functions

- autotest/ogr/ogr_fgdb.py
- autotest/ogr/ogr_openfilegdb.py
- autotest/ogr/ogr_openfilegdb_write.py
- autotest/ogr/ogr_pgeo.py
- autotest/utilities/test_ogrinfo_lib.py
- ogr/ogrsf_frmts/openfilegdb/filegdb_relationship.h
Previously we reported the table type as "feature", which did not match the accepted values reported by GDAL_DMD_RELATIONSHIP_RELATED_TABLE_TYPES for the drivers (and differed from the "features" string used by other drivers, eg. GPKG).
This is purely a GDAL implementation detail, it does not affect how the relationships are actually recorded in the GDB (as we only check for the table type of "media" to apply special handling)
> [openfilegdb] Correctly use "features" as related table type

- autotest/ogr/ogr_fgdb.py
- autotest/ogr/ogr_openfilegdb.py
- autotest/ogr/ogr_openfilegdb_write.py
- autotest/ogr/ogr_pgeo.py
- autotest/utilities/test_ogrinfo_lib.py
- ogr/ogrsf_frmts/openfilegdb/filegdb_relationship.h
> [Backport release/3.8] [openfilegdb] Correctly use "features" as related table type

- docker/ubuntu-full/Dockerfile
Removes apache-arrow-apt-source-latest-xxxx.deb from `/`
```
▶ docker run -it --rm ghcr.io/osgeo/gdal:ubuntu-full-latest bash
root@cc2c6905f59a:/# ls
apache-arrow-apt-source-latest-jammy.deb  boot  etc   lib    mnt  proc  run   srv  tmp  var
bin                                       dev   home  media  opt  root  sbin  sys  usr
root@cc2c6905f59a:/#
```
> Dockerfile Ubuntu - Remove apache arrow deb file

- autotest/ogr/ogr_gpkg.py
- doc/source/drivers/vector/gpkg.rst
- ogr/ogrsf_frmts/gpkg/ogr_geopackage.h
- ogr/ogrsf_frmts/gpkg/ogrgeopackagedatasource.cpp
- ogr/ogrsf_frmts/sqlite/ogr_sqlite.h
- ogr/ogrsf_frmts/sqlite/ogrsqlitebase.h
- ogr/ogrsf_frmts/sqlite/ogrsqlitedatasource.cpp
When reading relationships, always read relationships defined using foreign key constraints regardless of whether or not the related tables extension is in use.
The related table extension only permits definition of many-to-many relationships, so there's a strong case for supporting one-to-many relationships defined outside of this extension. In fact it's what's recommended upstream: https://github.com/opengeospatial/geopackage/issues/678#issuecomment-1954402113
> [gpkg] Also read relationships defined using foreign key constraints

- doc/source/programs/gdaltransform.rst
Currently each code block gets rendered with weird colors going on and off.
Me adding `.. code-block::`s should fix it.
Note however that I am just guessing, as GitHub does not render the results!
Here is an example of the HTML before my changes:
You might say I am causing the nice colors of some of the examples to go away.
Well, they looked nice just by accident!
> Update gdaltransform.rst to add missing .. code-block::s

- doc/source/programs/gdaltransform.rst
Else one might think GCPs can be given in srcfile one per line,
```
<pixel> <line> <easting> <northing> [<elevation>]
```
> Update gdaltransform.rst to hint on running gdalinfo on srcfile

- doc/source/drivers/raster/xyz.rst
Avoid users generating
`Warning 6: XYZ driver only uses the first band of the dataset.`
> Update xyz.rst to warn only three columns are used

- doc/source/drivers/vector/gml.rst
The gfs.xsd XML schema file has been moved.
> gml.rst: fix the link to the .gfx schema

- ogr/ogrsf_frmts/sqlite/CMakeLists.txt
Cf. https://lists.osgeo.org/pipermail/gdal-dev/2024-February/058508.html
The change disables the module for all static builds (`BUILD_SHARED_LIBS` off). But the key goal is to disable it in builds with `-static` CRT linkage on linux.
Alternatively, it could be flagged as `EXCLUDE_FROM_ALL`, but then it might bit rot.
AFAICS the module is neither used nor installed.
> Disable my_test_sqlite3_ext in static builds

- port/cpl_vsil_curl.cpp
will now get:
```shell
$ gdalinfo /vsicurl/https://erddap.emodnet.eu/erddap/files/biology_6640_benthos_NorthSea_e4af_0f0e_6a73/04_2021_6640_diva_benthos_erddap.nc
ERROR 1: 416: Range downloading not supported by this server: Error {
code=416;
message="Requested Range Not Satisfiable: REQUESTED_RANGE_NOT_SATISFIABLE: Don't try to connect to .nc or .hdf files on ERDDAP's /files/ system as if they were local files. It is horribly inefficient and often causes other problems. Instead: a) Use (OPeN)DAP client software to connect to ERDDAP's DAP services for this dataset (which have /griddap/ or /tabledap/ in the URL). That's what DAP is for. b) Or, use the dataset's Data Access Form to request a subset of data. c) Or, if you need the entire file or repeated access over a long period of time, …
```
> /vsicurl/: Read(): emit error message when receiving HTTP 416 Range Not Satisfiable error

- autotest/ogr/ogr_ods.py
- autotest/ogr/ogr_xlsx.py
- ogr/ogrsf_frmts/ods/ogrodsdatasource.cpp
- ogr/ogrsf_frmts/xlsx/ogrxlsxdatasource.cpp
Fixes https://github.com/OSGeo/gdal/pull/9295#discussion_r1501665102
> ODS and XLSX: declare OLCStringsAsUTF8 on newly created layers

- ogr/ogrsf_frmts/flatgeobuf/CMakeLists.txt
- ogr/ogrsf_frmts/flatgeobuf/ogrflatgeobufdataset.cpp
- scripts/cppcheck.sh
Cf https://lists.osgeo.org/pipermail/gdal-dev/2024-February/058544.html
> Make sure our vendored flatbuffers copy has a unique namespace

- autotest/gdrivers/ecw.py
- autotest/gdrivers/jp2kak.py
- autotest/gdrivers/jp2openjpeg.py
- autotest/osr/osr_xml.py
- frmts/ecw/ecwcreatecopy.cpp
- frmts/jp2kak/jp2kakdataset.cpp
- frmts/jp2lura/jp2luradataset.cpp
- frmts/opjlike/jp2opjlikedataset.cpp
- gcore/gdaljp2metadata.cpp
- gcore/gdaljp2metadata.h
- ogr/ogr_srs_xml.cpp
> JPEG2000 drivers: do not export GMLJP2 if the SRS isn't compatible

- autotest/ogr/ogr_ods.py
- autotest/ogr/ogr_xlsx.py
- ogr/ogrsf_frmts/ods/ogrodsdatasource.cpp
- ogr/ogrsf_frmts/xlsx/ogrxlsxdatasource.cpp
> [Backport release/3.8] ODS and XLSX: declare OLCStringsAsUTF8 on newly created layers

- swig/python/gdal-utils/osgeo_utils/gdal_polygonize.py
Makes gdal_polygonize.py print an error message when the creation of the destination datasource fails.
Otherwise, in such case, the script will fails at https://github.com/OSGeo/gdal/blob/master/swig/python/gdal-utils/osgeo_utils/gdal_polygonize.py#L162 and a Python traceback error message will be printed.
> gdal_polygonize.py: handle error when the creation of the destination datasource fails

- autotest/ogr/ogr_ili.py
- ogr/ogrsf_frmts/ili/ogrili2datasource.cpp
Refs https://github.com/OSGeo/gdal/pull/9351 / https://github.com/qgis/QGIS/issues/56588
> ILI2: emit an error and not just a warning when creating a dataset without a model file

- apps/gdalinfo_lib.cpp
- autotest/utilities/test_gdalinfo_lib.py
- data/gdalinfo_output.schema.json
> [Backport release/3.8] gdalinfo -json: fix wrong axis order in STAC proj:shape member (fixes #9337)

- autotest/ogr/ogr_ili.py
- ogr/ogrsf_frmts/ili/ogrili2datasource.cpp
> [Backport release/3.8] ILI2: emit an error and not just a warning when creating a dataset without a model file

- alg/gdal_alg.h
- alg/gdaltransformer.cpp
- apps/gdalwarp_lib.cpp
- autotest/alg/warp.py
Fixes  a downstream issue: https://github.com/qgis/QGIS/issues/56288
> [warp] fast track for same projection

- autotest/utilities/test_gdalwarp_lib.py
- swig/include/gdal.i
Fix gdal.Warp segfault with dst=None
It seems reasonable assume `format="MEM"` in this case, but I did not change that behavior.
None
> Python: Fix gdal.Warp segfault with dst=None

- doc/source/drivers/raster/hfa.rst
I had to read the page https://gdal.org/drivers/raster/hfa.html and noticed some typos in the page.
I fixed the ones that I understood.
https://github.com/OSGeo/gdal/blob/ced6a0ded84a892aefcdbf449689026e3645494e/doc/source/drivers/raster/hfa.rst?plain=1#L22-L26
* OS:
* Compiler:
> HFA: Fix some typos in HFA -- Erdas Imagine .img docs

- autotest/ogr/ogr_openfilegdb_write.py
- ogr/ogrsf_frmts/openfilegdb/filegdbtable.cpp
- ogr/ogrsf_frmts/openfilegdb/filegdbtable_write.cpp
When SetFeature() involves generating a row whose blob size is larger than the maximum one in the file, the file header was no properly refreshed. This didn't cause issues to the OpenFileGDB driver, which is robust to that, but ESRI based readers, like ArcMap or the FileGDB SDK, were unable to read such features.
> OpenFileGDB writer: fix corrupted maximum blob size header field in some SetFeature() scenarios (fixes #9388)

- autotest/ogr/ogr_openfilegdb_write.py
- ogr/ogrsf_frmts/openfilegdb/filegdbtable.cpp
- ogr/ogrsf_frmts/openfilegdb/filegdbtable_write.cpp
When SetFeature() involves generating a row whose blob size is larger than the maximum one in the file, the file header was no properly refreshed. This didn't cause issues to the OpenFileGDB driver, which is robust to that, but ESRI based readers, like ArcMap or the FileGDB SDK, were unable to read such features.
backport of https://github.com/OSGeo/gdal/pull/9400
> [Backport 3.8] OpenFileGDB writer: fix corrupted maximum blob size header field in some SetFeature() scenarios (fixes #9388)

- frmts/ogcapi/gdalogcapidataset.cpp
Add geotiff as supported image_format option to avoid warning message. This is foollow up to https://github.com/OSGeo/gdal/pull/9231
> Add geotiff as image_format option

- gcore/gdaldriver.cpp
When using gdal_translate, the source datasource is opened twice. However, the second time does not use any open options specified when orginally opening the data soruce. This is a probelm for OGC Tile data sources if the user specified TILEMATRIXSET or TILEMATRIX because the driver will default to WorldCRS84Quad even when that is not what was originally specified or to a different zoom level.
For example,  if you request TILEMATRIXSET="foo" then gdal open will the correct tilematrixset definition on the first open, but on the second open it will instead load the definition for the WorldCRS84Quad tilematrixset (assuming it is a listed tilematrixset).
This PR fixes the issue by passing `poSrcDS->papszOpenOptions` to the newly opened datasource.
> gdaldriver: Don't Lose papszOpenOptions

- doc/source/programs/gdal_viewshed.rst
1. Even after my change, the man page will still look bad, because the user doesn't see any image... but yes, he may see some ALT words.
2. Before my change, only we man page readers noticed the defective sentence that I changed. In the HTML it was gone due to wrong indenting.
> Update gdal_viewshed.rst to make sense, on the man page too

- autotest/gcore/rasterio.py
- gcore/gdal_priv_templates.hpp
- gcore/overview.cpp
Fix #9427
Backport of https://github.com/OSGeo/gdal/pull/9428, whose main change is to avoid to make the new function a public one to avoid extending the API.
> [Backport 3.8] Overview/RasterIO resampling: fix infinite looping when nodata has a big absolute value (#9428)

- alg/gdal_crs.cpp
- alg/gdal_tps.cpp
- autotest/cpp/test_gdal.cpp
- frmts/gtiff/gtiffdataset.cpp
- frmts/gtiff/gtiffdataset.h
- frmts/gtiff/gtiffdataset_read.cpp
- frmts/gtiff/gtiffdataset_write.cpp
- frmts/hdf4/hdf4imagedataset.cpp
- frmts/hdf5/hdf5imagedataset.cpp
- frmts/hfa/hfadataset.cpp
- frmts/hfa/hfadataset.h
- frmts/jpeg/jpgdataset.cpp
- frmts/jpeg/jpgdataset.h
- frmts/mem/memdataset.cpp
- frmts/mem/memdataset.h
- frmts/pdf/pdfcreatecopy.cpp
- frmts/pdf/pdfcreatefromcomposition.cpp
- frmts/pdf/pdfcreatefromcomposition.h
- frmts/vrt/vrtdataset.cpp
- frmts/vrt/vrtdataset.h
- gcore/gdal_misc.cpp
- gcore/gdal_pam.h
- gcore/gdal_priv.h
- gcore/gdalpamdataset.cpp
GDAL_GCP is a C-only structure. The typical/recommended pattern to create GCPs from C is:
```
GDAL_GCP* gcps = (GDAL_GCP*)CPLMalloc( count * sizeof(GDAL_GCP) );
GDALInitGCPs( count, gcps );  // zero-initialize  pixel,line,x,y,z double members of each gcps[], and affects a CPLStrdup("") string to pszId and pszInfo members of each gcps[]
CPLFree(gcps[0].pszId); // free the initial empty string
gcps[0].pszId = CPLStrdup("foo"); // for example
GDALDeinitGCPs( count, gcps ); // free memory of gcps[i].pszId and gcps[i].pszInfo
CPLFree(gcps); // free the array itself
```
This is "fine" for a C user, but quite tedious in a C++ context. Big users of creating GCPs are GDAL drivers themselves.
So we introduce a gdal::GCP class that has a single GDAL_GCP private member, and handle memory …
> Add a gdal::GCP class to make GCP handling from C++ easier

- apps/gdalinfo_lib.cpp
- autotest/utilities/test_gdalinfo_lib.py
> [Backport release/3.8] gdalinfo -json/gdal.Info(format='json'): avoid error/exception on engineering CRS (fixes #9396)

- doc/source/drivers/vector/pg.rst
Added an extra section in the documentation to give information about speeding up appending to a PostGIS table by turning COPY mode on.
I didn't know exactly where to put this in the docs page, so created a new section underneath 'Creation issues'. Feel free to move as desired, or let me know where you'd like me to move it.
Based on a discussion on the GDAL mailing list.
> docs: Add extra docs about speeding up append to PostGIS tables

- doc/source/development/rfc/index.rst
- doc/source/development/rfc/rfc99_geometry_coordinate_precision.rst
Partially rendered view at https://github.com/rouault/gdal/blob/rfc99_text/doc/source/development/rfc/rfc99_geometry_coordinate_precision.rst
> Add RFC99 text: Geometry coordinate precision

- alg/gdalwarper.h
- alg/gdalwarpoperation.cpp
- autotest/gdrivers/vrtwarp.py
- frmts/vrt/vrtdataset.h
- frmts/vrt/vrtwarped.cpp
This specialized implementation of IRasterIO() will be faster than using the VRTWarpedRasterBand::IReadBlock() method in situations where
- a large enough chunk of data is requested at once
- and multi-threaded warping is enabled (it only kicks in if the warped chunk is large enough) and/or when reading the source dataset is multi-threaded (e.g JP2KAK or JP2OpenJPEG driver).
e.g. with a 3909x3154 4-band UInt16 input JPEG2000 source dataset:
```
$ gdalwarp -overwrite -t_srs EPSG:4326 -r cubic -wo NUM_THREADS=12 input.jp2 test.vrt
Creating output file that is 3909P x 3154L.
```
Now:
```
$ time GDAL_SKIP=JP2KAK,JP2ECW gdal_translate test.vrt out.tif -co tiled=yes
Input file size is 3909, 3154
0...10...20...30...40...50...60...70...80...90...100 - done.
real    0m1,624s
user    0m11,910s
sys …
```
> VRTWarpedDataset: add an optimized IRasterIO() implementation

- doc/source/drivers/vector/sqlite.rst
This pull request updates the stated default value of the `ogr2ogr -gt` argument in the "Performance hints" section for SQLite/Spatialite. It updates to the default value 100000 as given in the `ogr2ogr` doc at:
https://gdal.org/programs/ogr2ogr.html#cmdoption-ogr2ogr-gt.
It also removes the recommendation
>Increasing to -gt 65536 or more ensures optimal performance while populating some table containing many hundredth thousand or million rows.
Should there be a recommendation to increase potentially >100000 in some cases?
> doc: update the ogr2ogr default value for -gt in SQLite performance hints

- autotest/ogr/ogr_geojson.py
- frmts/netcdf/netcdfsgwriterutil.cpp
- frmts/netcdf/netcdfsgwriterutil.h
- ogr/ogrsf_frmts/geojson/ogrgeojsonreader.cpp
This was what we exported already, which also happens to validate against http://geojson.org/schema/Polygon.json but on import, we insisted on havin a [[]] coordinates array (which does not validate the schema)
> GeoJSON reader: accept a {"type": "Polygon","coordinates": []} as a representation of POLYGON EMPTY (fixes duckdb/duckdb_spatial#273)

- autotest/ogr/ogr_shape_sbn.py
- ogr/ogrsf_frmts/shape/sbnsearch.c
Fixes https://github.com/OSGeo/shapelib/issues/106 / https://github.com/OSGeo/gdal/issues/9430
> Internal shapelib: SBNOpenDiskTree(): make it work with node descriptors with non-increasing nBinStart

- apps/gdallocationinfo.cpp
- apps/gdaltransform.cpp
- autotest/utilities/test_gdallocationinfo.py
- autotest/utilities/test_gdaltransform.py
- doc/source/programs/gdallocationinfo.rst
- doc/source/programs/gdaltransform.rst
Fixes #9411
- gdaltransform: make it output extra content at end of input line (unless -ignore_extra_input), and add -E echo mode, and -field_sep option
- gdallocationinfo: make it output extra content at end of input line (unless -ignore_extra_input), and add -E echo mode, and -field_sep option
> gdaltransform/gdallocationinfo: make it output extra content at end of input line, add echo mode and field separator

- autotest/ogr/ogr_shape_sbn.py
- ogr/ogrsf_frmts/shape/sbnsearch.c
backport of https://github.com/OSGeo/gdal/pull/9439
> [Backport 3.8]  Internal shapelib: SBNOpenDiskTree(): make it work with node descriptors with non-increasing nBinStart

- autotest/utilities/test_gdalwarp_lib.py
- swig/include/gdal.i
Backport of https://github.com/OSGeo/gdal/pull/9386
> [Backport 3.8] SWIG: Fix gdal.Warp segfault with dst=None

- swig/python/README.rst
- swig/python/pyproject.toml
Updates docs on building numpy support. I've been maintaining [this SO answer on how to fix it](https://stackoverflow.com/a/75669898/6521809) for a year now and I just ran into a new problem installing the numpy bindings. I have tested it and wheel and setuptools cannot be installed alongside gdal[numpy], it must be done before.
There is also a tweak to the version of setuptools in the `pyproject.toml` I determined through experimentation. Pip, or setuptools, or whatever completely ignores this string (happens in my packages, too), but at least it's accurate now. On its own, pip will think >=48 is good enough, which is incredibly wrong for _multiple_ reasons. I'm unaware of a fix, I had the issue back in setuptools 64.
None
ghcr.io/osgeo/gdal:ubuntu-full-3.8.3 with python 3.12.1
Gdal …
> Additional python packaging documentation, version correction

- doc/source/programs/gdal_calc.rst
On the man page, and even on the HTML, these "Version added" renders to make what was intended as
Example 1
Example 2
Example 3
Example 4
look like
Old Example 1
New Example 1
Old Example 2
New Example 2
It is a 100% disaster!
I am sure "Version added" is usually great, except in this particular spot on this particular man page!!
> Update gdal_calc.rst eliminating disastrous "version added"

- autotest/gcore/basic_test.py
- swig/include/python/gdal_python.i
Prevents a crash when using a `Layer` after its parent `Dataset` closes. We already handle this for the `DataSource` - `Layer` relationship and the `Dataset` - `Band` relationship, but `Dataset` - `Layer` was missed.
#7965
> Python bindings: Invalidate layer ref when Dataset closes

- autotest/ogr/ogr_basic_test.py
- swig/include/python/docs/ogr_featuredef_docs.i
- swig/include/python/ogr_python.i
This makes the `FeatureDefn` behavior more similar to `Feature` in which `GetField` can accept `str` or `int` arguments.
> Python bindings: Accept str arg in FeatureDefn.GetFieldDefn

- frmts/gtiff/gtiffdataset_write.cpp
Previous wording could be read as "starting from libtiff >4.3.0, predictor is only supported with 64bit samples".
> GTIFF: fix ambiguous wording for 64b predictor=2

- apps/ogr2ogr_lib.cpp
- autotest/utilities/test_ogr2ogr.py
- ogr/ogrsf_frmts/arrow_common/ograrrowrandomaccessfile.h
- ogr/ogrsf_frmts/parquet/ogr_parquet.h
- ogr/ogrsf_frmts/parquet/ogrparquetdriver.cpp
- ogr/ogrsf_frmts/parquet/ogrparquetlayer.cpp
Fixes https://github.com/OSGeo/gdal/issues/9497
> ogr2ogr/Parquet: add hack to avoid super lengthy processing when using -limit with a Parquet dataset source (workarounds/fixes #9497)

- .github/workflows/icc/Dockerfile.ci
- .github/workflows/icc/build.sh
- autotest/gcore/transformer.py
- autotest/gdrivers/eedai.py
- autotest/gdrivers/vrtpansharpen.py
- autotest/pyscripts/test_gdal_pansharpen.py
- frmts/grib/gribdataset.cpp
- gcore/overview.cpp
- ogr/ogrsf_frmts/gpkg/gdalgeopackagerasterband.cpp
> Add compatibility for Intel Compiler 2024.0.2.29

- alg/CMakeLists.txt
- alg/gdal_alg.h
- alg/los.cpp
- autotest/cpp/test_alg.cpp
This implements a basic LOS check using 2D bresenham. Height is interpolated with a linear interpolation between points.
I would like preliminary feedback (see below). I used a 2D bresenham because the height values may be floating point. 
I think if the height values are known to be integer-type at compile time, I think some templating could be used to optimize it with the 3D bresenham algorithm. For now, I used linear interpolation because it should work with all cases, and convert the dataset's height to a double.
1. Is there a way to unit test for asserts and only have the tests run if compiled in debug mode?
*  Don't test for nullptr, mark it in the API as not-null
1. Are the asserts I added on the `int` limits of pixel coordinates correct?
*  Yea, but the lower level library already …
> Implement basic Line-of-sight algorithm

- alg/los.cpp
- autotest/cpp/test_alg.cpp
* This adds optimizations for the Line of Sight algorithm if the query is vertical/horizontal.  Bresenham shouldn't be used, because it's slower than direct iteration over the raster.
* This avoids a bunch of sqrt options in GetZValueFromXY and should speed things up.
* Doing LOS checks for vertical/horizontal is common when algorithms use raster-aligned operations.
* If the Z interpolation didn't use a square root, it probably wouldn't be worth doing this change. 
* Adds more tests! 
Builds on https://github.com/OSGeo/gdal/pull/9506
* OS: Ubuntu 22
* Compiler: G++11
> LOS: Add special cases for LOS checks for vertical and horizontal lines

- frmts/mrf/marfa.h
- frmts/mrf/marfa_dataset.cpp
- frmts/mrf/mrf_band.cpp
- frmts/mrf/mrf_util.cpp
- frmts/zlib/crc32.c
Fix 9 typos endianess → endianness
> Fix 9 typos: endianess → endianness

- .pre-commit-config.yaml
- apps/CMakeLists.txt
- apps/argparse/.clang-format
- apps/argparse/README.TXT
- apps/argparse/argparse.hpp
- apps/gdal_translate_bin.cpp
- apps/gdal_translate_lib.cpp
- apps/gdal_utils_priv.h
- apps/gdal_viewshed.cpp
- apps/gdaladdo.cpp
- apps/gdalargumentparser.cpp
- apps/gdalargumentparser.h
- apps/nearblack_bin.cpp
- apps/nearblack_lib.cpp
- apps/ogr2ogr_bin.cpp
- apps/ogr2ogr_lib.cpp
- apps/ogrinfo_bin.cpp
- apps/ogrinfo_lib.cpp
- apps/sozip.cpp
- autotest/gdrivers/wcs.py
- autotest/utilities/test_gdal_translate.py
- autotest/utilities/test_gdal_viewshed.py
- autotest/utilities/test_ogr2ogr_lib.py
- doc/source/programs/ogr2ogr.rst
- port/cpl_conv.h
- port/cpl_strtod.cpp
- scripts/cppcheck.sh
Cf email thread at https://lists.osgeo.org/pipermail/gdal-dev/2024-March/thread.html#58647
Up to now, ``sozip``, ``gdal_viewshed``, ``nearblack``, ``ogrinfo``, ``gdaladdo``, ``gdal_translate``, ``ogr2ogr`` (so a mix of pure command line utilitys and utility-as-a-C-function) have been converted. This should exercise pretty much all what we need: optional and positional arguments, boolean/integer/double data types, repeated arguments, mutually exclusive arguments. So I'm quite confident now we could generalize the use of that framework to all other utilities
I've had to extend p-ranav/argparse with various changes to improve the usage/synopsis output, and add some helpers to make it easier to use:
- add Argument::store_into(variable) helpers to define in the same time the argument and where …
> Use p-ranav/argparse framework for command line argument parsing

- apps/gdalargumentparser.cpp
- autotest/utilities/test_gdal_translate_lib.py
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=67588
> GDALArgumentParser: avoid potential read heap-buffer-overflow (master only)

- CMakeLists.txt
Also see https://gitlab.kitware.com/cmake/cmake/-/merge_requests/9359
> CMake: fix NumPy detection when Intel MKL library is installed

- CMakeLists.txt
> [Backport release/3.8] CMake: fix NumPy detection when Intel MKL library is installed

- cmake/helpers/configure.cmake
The commit fixes issue #9550.  Added new apple OS (visionOS, tvOS, watchOS) to cmake config generating rules. Tested compilation on:
* OS: MacOS 14.3.1
* Compiler: CMAKE 3.29.0 + Xcode 15.2
> Added modern Apple OS support

- autotest/alg/los.py
- swig/include/Operations.i
- swig/include/python/docs/gdal_operations_docs.i
- swig/include/python/gdal_python.i
CC @Ryanf55
It might be easier to continue doing Python tests  (possibly porting your existing C++ tests)
> SWIG bindings: add gdal.IsLineOfSightVisible()

- autotest/pyscripts/test_gdalattachpct.py
- swig/python/gdal-utils/osgeo_utils/gdalattachpct.py
> [Backport release/3.8] gdalattachpct.py: fix it when output file is a VRT (fixes #9513)

- autotest/gcore/tiff_read.py
- frmts/gtiff/gtiffrasterband.cpp
> GTiff: fix read error/use-after-free when reading COGs with mask from network storage 

- .github/workflows/codeql.yml
> codeql.yml: disable CodeQL interposition during CMake time

- frmts/gtiff/libtiff/tif_dir.c
- frmts/gtiff/libtiff/tif_dir.h
- frmts/gtiff/libtiff/tif_dirinfo.c
- frmts/gtiff/libtiff/tif_dirread.c
- frmts/gtiff/libtiff/tif_dirwrite.c
- frmts/gtiff/libtiff/tif_jpeg.c
- frmts/gtiff/libtiff/tif_open.c
- frmts/gtiff/libtiff/tif_read.c
- frmts/gtiff/libtiff/tif_strip.c
- frmts/gtiff/libtiff/tiffiop.h
Cf https://gitlab.com/libtiff/libtiff/-/merge_requests/565
> Internal libtiff: TIFFWriteDirectory: Avoid overwriting following data if an IFD is enlarged

- autotest/ogr/ogr_flatgeobuf.py
- ogr/ogrsf_frmts/flatgeobuf/ogr_flatgeobuf.h
- ogr/ogrsf_frmts/flatgeobuf/ogrflatgeobufdataset.cpp
- ogr/ogrsf_frmts/flatgeobuf/ogrflatgeobufeditablelayer.cpp
- ogr/ogrsf_frmts/flatgeobuf/ogrflatgeobuflayer.cpp
- ogr/ogrsf_frmts/generic/ogrlayerarrow.cpp
- FlatGeoBuf: implement OGRLayer::GetDataset() (refs #9568). Partial backport of #8860
- CreateFieldFromArrowSchema(): don't propagate native subtype if we have to use a fallback main type. Backport of https://github.com/OSGeo/gdal/pull/9569
> FlatGeoBuf: implement OGRLayer::GetDataset(), and CreateFieldFromArrowSchema() subfield fix

- swig/python/gdal-utils/osgeo_utils/auxiliary/gdal_argparse.py
- swig/python/gdal-utils/osgeo_utils/auxiliary/util.py
(fixes #9534)
Now
```shell
$ python swig/python/gdal-utils/scripts/gdal_calc.py --outfile out.tif -A foo.tif --calc "A"
```
just returns
```
Could not open file "foo.tif": No such file or directory
```
> Python utilities: do not display full traceback on OpenDS failures 

- autotest/gcore/tiff_write.py
- frmts/gtiff/CMakeLists.txt
- frmts/gtiff/geotiff.cpp
- frmts/gtiff/gtiffdataset.h
- frmts/gtiff/gtiffdataset_write.cpp
- frmts/gtiff/libtiff/tif_lerc.c
(fixes #9530)
The LERC codec up-to-now didn't do any special processing when writing a strile in a multi-band PlanarConfig=Contig file, resulting in corruptions. Now we generate a mask buffer in that situation. Actually, if the NaN values are not at the same location accross bands, we need to write one mask-per-band, which requires liblerc >= 3.0, and in that situation change the LERC blob to multi-band instead of multi-depth/dim, with liblerc >= 3.0. When all bands have NaN values at the same location, we generate a single mask, which is compatible of liblerc < 3.0, but requires at last this version of libtiff to be read. This is the best solution we come with to fix the issue while having the maximum backward compatibility.
Corresponding upstream libtiff merge request: …
> GTiff + internal libtiff: deal with issues with multi-band PlanarConfig=Contig, LERC and NaN values (fixes #9530)

- swig/python/gdal-utils/osgeo_utils/gdal2tiles.py
The alpha channel is only checked for a fully transparent tile when the source region is of nonzero size. When there are zero pixels to copy, the tile will also be transparent and should be skipped with `--exclude`.
This occurs when the edge of the input is aligned with the tile grid. To reproduce the issue, create a GeoTIFF with:
```console
$ gdal_create -outsize 1536 1536 -a_srs EPSG:3857 -a_ullr -114.65554242953658 114.65554242953658 114.65554242953658 -114.65554242953658 -bands 4 -burn 0 -co COMPRESS=DEFLATE empty.tif
```
This will be fully transparent so should produce no tiles with `--exclude`, but currently produces tiles along one edge:
```console
$ python3 swig/python/gdal-utils/osgeo_utils/gdal2tiles.py --exclude --xyz -w none empty.tif -z 11-20 /tmp/tiled_out 
...
$ find …
```
> gdal2tiles: Fix case where --exclude still writes fully transparent tiles

- apps/gdal_translate_lib.cpp
- autotest/gcore/vrt_read.py
Also fix no-op assertions in vrt_read.py and comment out those that subsequently fail.
I came across this when trying to figure out why some tests in `tiff_read.py` fail if they run after `vrt.py`.
> gdal_translate: avoid dataset leak on invalid -exponent and -scale

- autotest/gcore/misc.py
- autotest/ogr/ogr_basic_test.py
- swig/include/python/ogr_python.i
Same as 7a77e1 but for ogr module.
> Python bindings: Make ogr.GeneralCmdLineProcessor accept int, os.PathLike

- doc/source/programs/ogrinfo.rst
Else the user will never get it right. Unless he looks at the ogr2ogr man page.
> Update ogrinfo.rst to show how to quote -where

- .github/workflows/cmake_builds.yml
- .github/workflows/ubuntu_20.04/Dockerfile.ci
This PR fixes an issue caused by the new version of EULA agreement for HANA Client binaries.
The fix must be backported to avoid CI fails by older versions.
> HANA: Upgrade EULA agreement to version 3.2

- alg/gdal_alg.h
- alg/los.cpp
- autotest/alg/los.py
- autotest/cpp/test_alg.cpp
- swig/include/Operations.i
- swig/include/python/docs/gdal_operations_docs.i
- swig/include/python/typemaps_python.i
* Lock in ABI before release to support x and y terrain intersection locations
* Implementation will come later
* Attempts to also add in the SWIG binding docs (Please verify, particularly the param types for the pointer args)
#9562 
* OS: Ubuntu 22
* Compiler: G++11
> LOS: Add intersection location parameters

- alg/gdal_alg_priv.h
- alg/gdaltransformer.cpp
- apps/gdalwarp_lib.cpp
- autotest/utilities/test_gdalwarp_lib.py
> WARP: fix resolution calc with -te

- swig/python/gdal-utils/osgeo_utils/gdal2xyz.py
Window rectangle corners shall be specified as integers.
> gdal2xyz: Change -srcwin parameter type to integer.

- autotest/alg/los.py
- swig/include/python/docs/gdal_operations_docs.i
- swig/include/python/gdal_python.i
Implementin @dbaston good suggestion. I initially tried to do that using the Python C API from the typemap, but this turned out to be tricky. Couldn't manage to get rid of a DeprecationWarning about builtin type not having a __module__ attribute. Turning the basic tuple into a namedtuple from Python avoids that itssue.
> Python bindings: return a namedtuple for gdal.IsLineOfSightVisible()

- autotest/requirements.txt
This reverts commit 6703d3071de7155d320a39a580f27230428dcaca.
According to https://github.com/python/importlib_resources/issues/298, the issue has been fixed in importlib-resources 6.3.2
> Revert "requirements.txt: add pin for importlib-resources to avoid issue with pytest with jsonschema"

- autotest/ogr/ogr_shape.py
- ogr/ogrsf_frmts/generic/ogr_gensql.cpp
- ogr/ogrsf_frmts/sqlite/ogrsqliteexecutesql.cpp
> ExecuteSQL() with OGRSQL and SQLITE dialects: get OLCStringsAsUTF8 from underlying layer

- apps/ogr2ogr_lib.cpp
- autotest/gdrivers/netcdf.py
- autotest/utilities/test_ogr2ogr_lib.py
- doc/source/programs/ogr2ogr.rst
- swig/include/python/gdal_python.i
> ogr2ogr: make -select tokenize only on comma (and not on space), and honour double-quoting 

- doc/source/user/configoptions.rst
Converts a ticket number in documentation to a link, so that even people who are not so familiar with the project can easily access the ticket.
None as far as I'm aware.
> Doc: Clarify the target of ticket number reference

- apps/test_ogrsf.cpp
- autotest/ogr/ogr_sql_sqlite.py
- autotest/ogr/ogr_sql_test.py
- gcore/gdaldataset.cpp
- ogr/ogrsf_frmts/generic/ogrlayer.cpp
- ogr/ogrsf_frmts/gpkg/ogr_geopackage.h
- ogr/ogrsf_frmts/ogrsf_frmts.h
- ogr/ogrsf_frmts/sqlite/ogr_sqlite.h
- ogr/ogrsf_frmts/sqlite/ogrsqlitebase.h
- ogr/ogrsf_frmts/sqlite/ogrsqliteexecutesql.cpp
- ogr/ogrsf_frmts/sqlite/ogrsqliteselectlayer.cpp
> ExecuteSQL(): error out if SetSpatialFilter() fails

- .github/workflows/cmake_builds.yml
- HOWTO-RELEASE
setuptools 65.3 has https://github.com/pypa/setuptools/issues/3593 "Implement PEP 625 - File Name of a Source Distribution" which modifies the source tarball. Adapt for it
> CI: adapt for setuptools >= 65.3

- autotest/ogr/ogr_arrow.py
- autotest/ogr/ogr_parquet.py
- autotest/pymod/ogrtest.py
- doc/source/drivers/vector/arrow.rst
- doc/source/drivers/vector/parquet.rst
- ogr/ogrsf_frmts/arrow/ogrfeatherdriver.cpp
- ogr/ogrsf_frmts/arrow/ogrfeatherwriterlayer.cpp
- ogr/ogrsf_frmts/arrow_common/ogr_arrow.h
- ogr/ogrsf_frmts/arrow_common/ograrrowlayer.hpp
- ogr/ogrsf_frmts/arrow_common/ograrrowwriterlayer.hpp
- ogr/ogrsf_frmts/parquet/ogr_parquet.h
- ogr/ogrsf_frmts/parquet/ogrparquetdriver.cpp
- ogr/ogrsf_frmts/parquet/ogrparquetlayer.cpp
- ogr/ogrsf_frmts/parquet/ogrparquetwriterlayer.cpp
- swig/python/gdal-utils/osgeo_utils/samples/validate_geoparquet.py
Add support for https://github.com/opengeospatial/geoparquet/pull/189
*    GeoParquet: implement read/write support for the GeoParquet 1.1 GeoArrow (struct-based) encoding.
```
- .. lco:: GEOMETRY_ENCODING
:choices: WKB, WKT, GEOARROW, GEOARROW_INTERLEAVED
:default: WKB
Geometry encoding.
WKB is the default and recommended choice for maximal interoperability.
WKT is *not* allowed by the GeoParquet specification, but are handled as
an extension.
As of GDAL 3.9, GEOARROW uses the GeoParquet 1.1 GeoArrow "struct" based
encodings (where points are modeled as a struct field with a x and y subfield,
lines are modeled as a list of such points, etc.).
The GEOARROW_INTERLEAVED option has been renamed in GDAL 3.9 from what was
named GEOARROW in previous versions, and uses an encoding where points …
```
> Parquet/Arrow: add support for GeoArrow (struct/separate) encoding (GeoParquet 1.1)

- apps/gdalinfo_bin.cpp
- apps/ogrinfo_bin.cpp
- autotest/utilities/test_gdalinfo.py
- autotest/utilities/test_ogrinfo.py
- gcore/gdaldriver.cpp
Updates `gdalinfo` to check if a file that cannot be opened has a name indicating a vector data type, and suggest the user call `ogrinfo` instead. Make the corresponding update to `ogrinfo`.
#9618
> gdalinfo, ogrinfo: Improve error output when file cannotbe opened

- autotest/gdrivers/netcdf.py
- doc/source/drivers/raster/netcdf.rst
- frmts/netcdf/netcdfdataset.cpp
- frmts/netcdf/netcdfdrivercore.cpp
Adds an option to control the names of netCDF variables created by GDAL. 
https://github.com/OSGeo/gdal/issues/1427
https://gis.stackexchange.com/questions/230642/setting-band-names-when-writing-multiple-layer-rasters-using-gdal-with-python
https://gis.stackexchange.com/questions/265204/gdal-creation-option-to-set-variable-name-to-netcdf
> netCDF: Add BAND_NAMES creation option

- autotest/gcore/vsifile.py
- port/cpl_vsil_cache.cpp
Do not read past EOF even if the client (e.g. VSIZIP) code say so.
Fix #9658
> VSICACHE: avoid EOF read

- ogr/ogrsf_frmts/ogrsf_frmts.dox
> Doc: SetIgnoredFields(): clarify interaction with SetAttributeFilter()

- autotest/ogr/ogr_gpkg.py
- ogr/ogrsf_frmts/gpkg/ogrgeopackagetablelayer.cpp
Workaround for https://gis.stackexchange.com/questions/479958/how-to-fix-failed-to-prepare-sql-error-when-creating-gpkg-file-from-osm-extrac/479964#479964 / https://lists.osgeo.org/pipermail/gdal-dev/2024-April/058840.html
For a not yet understood reason, threaded RTree building (randomly?) fails on OSX Arm64. This may not be at all specific to that platform, but a more general problem, but it can't be reproduced elsewhere. Cf https://gis.stackexchange.com/questions/479958/how-to-fix-failed-to-prepare-sql-error-when-creating-gpkg-file-from-osm-extrac/479964#479964 and random (frequent) failures on GDAL CI (https://github.com/OSGeo/gdal/commit/a83942422fd67471aee23ae11c5d06af27db2857)
> GPKG: change default value of OGR_GPKG_ALLOW_THREADED_RTREE to NO on OSX Arm64

- alg/gdalwarper.cpp
- alg/gdalwarper.h
- alg/gdalwarpkernel.cpp
- autotest/alg/warp.py
- autotest/pyscripts/test_gdal2tiles.py
- doc/source/programs/gdal2tiles.rst
- swig/python/gdal-utils/osgeo_utils/gdal2tiles.py
- Warper: add a EXCLUDED_VALUES warping option to specify pixel values to be ignored as contributing source pixels during resampling. Limited to average resampling for now
- gdal2tiles: add --excluded-values and --excluded-values-pct-threshold switches
> Warper: add a EXCLUDED_VALUES warping option, and use it in gdal2tiles

- apps/gdal_utils_priv.h
- apps/gdalbuildvrt_bin.cpp
- apps/gdalbuildvrt_lib.cpp
- doc/source/programs/gdalbuildvrt.rst
which makes sure that -sd value is an integer (fixes #9672)
> gdalbuildvrt: use GDALArgumentParser

- autotest/CMakeLists.txt
- doc/source/development/testing.rst
Modifies CMake configuration so that Python tests are run directly from the source tree, rather than from a symlink or copy in the build directory. This is an experiment in removing the following "gotcha":
> (be careful on Windows, the 
content of $build_dir/autotest is copied from $source_dir/autotest each 
time "cmake" is run, so if you edit your test .py file directly in the 
build directory, be super careful of not accidentally losing your work, 
and make sure to copy its content to the source directory first. That's 
admittedly an annoying point of the current test setup on Windows, 
compared to Unix where we use symbolic links)
described in https://lists.osgeo.org/pipermail/gdal-dev/2024-February/058425.html
A downside of this change is that, because `pytest.ini` lives only in the …
> autotest: run Python tests directly from source tree on Windows

- autotest/gcore/tiff_read.py
- frmts/gtiff/gtiffdataset_read.cpp
- port/cpl_vsi_virtual.h
- port/cpl_vsil_curl.cpp
- port/cpl_vsil_curl_class.h
Fixes #9682
With those changes, the number of GET requests for #9682 use case is down to 6:
```
$ time GDAL_NUM_THREADS=4 CPL_DEBUG=ON python -c "from osgeo import gdal; gdal.UseExceptions(); src=gdal.Open('/vsicurl/http://localhost:8080/ortho.tiff'); src.ReadAsArray()"
HTTP: libcurl/7.68.0 GnuTLS/3.6.13 zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3
VSICURL: GetFileSize(http://localhost:8080/ortho.tiff)=279686928  response_code=200
VSICURL: Downloading 0-16383 (http://localhost:8080/ortho.tiff)...
VSICURL: Got response_code=206
VSICURL: Downloading 32768-49151 (http://localhost:8080/ortho.tiff)...
VSICURL: Got response_code=206
GTiff: Using up to 4 threads for compression/decompression
GDAL: …
```
> GTiff: MultiThreadedRead(): make it take into account AdviseRead() limit to reduce the number of I/O requests

- doc/source/development/cmake.rst
* This adds a recommendation on how to find GDAL on Ubuntu 22 which is distributed with GDALL 3.4.
n/A
* OS: Ubuntu 22 with GDAL 3.4 installed as binaries.
* Compiler: G++11.4
> Add recommendation for finding older GDAL using CMake

- alg/gdalgrid.cpp
- alg/gdalwarpkernel.cpp
- autotest/cpp/test_cpl.cpp
- frmts/gtiff/gtiffdataset.cpp
- frmts/gtiff/gtiffdataset.h
- frmts/gtiff/gtiffdataset_write.cpp
- gcore/gdal_thread_pool.cpp
- gcore/overview.cpp
- ogr/ogrsf_frmts/gpkg/ogrgeopackagetablelayer.cpp
- ogr/ogrsf_frmts/mvt/ogrmvtdataset.cpp
- port/cpl_multiproc.cpp
- port/cpl_vsi_mem.cpp
- port/cpl_vsil_curl.cpp
- port/cpl_vsil_gzip.cpp
- port/cpl_worker_thread_pool.cpp
Most of those warnings are thought to be false positive, or about very minor issues
> Fix/suppress Coverity Scan warnings about locking

- apps/gdalargumentparser.cpp
- apps/gdalargumentparser.h
This can be used for further configuration of the
returned arguments.
As discussed in https://github.com/OSGeo/gdal/pull/9739#issuecomment-2074758905
> [argparse] Return argument reference from add methods

- autotest/osr/osr_ct.py
- ogr/ogr_spatialref.h
- ogr/ogr_srs_api.h
- ogr/ogrct.cpp
- ogr/ogrspatialreference.cpp
- scripts/cppcheck.sh
- swig/include/osr.i
We export CRS objects to PROJJSON rather than WKT2:2019 because PROJJSON is a bit more verbose, which helps in situations like https://github.com/OSGeo/gdal/issues/9732 /
https://github.com/OSGeo/PROJ/pull/4124 where we want to export a DerivedProjectedCRS whose base ProjectedCRS has non-metre axis.
Fixes https://github.com/OSGeo/gdal/issues/9732
> OGR_CT: use PROJJSON rather than in WKT:2019

- autotest/osr/osr_ct.py
- ogr/ogr_spatialref.h
- ogr/ogr_srs_api.h
- ogr/ogrct.cpp
- ogr/ogrspatialreference.cpp
- scripts/cppcheck.sh
- swig/include/osr.i
> [Backport release/3.9] OGR_CT: use PROJJSON rather than in WKT:2019

- gcore/gdal_misc.cpp
Lest users need to look them up each time.
There's plenty of room on the screen here, so no point in creating a look-up headache for the user.
> Update gdal_misc.cpp to show abbreviation codes

- autotest/gdrivers/tiledb_multidim.py
- autotest/ogr/ogr_tiledb.py
- cmake/helpers/CheckDependentLibraries.cmake
- doc/source/development/building_from_source.rst
- frmts/tiledb/CMakeLists.txt
- frmts/tiledb/include_tiledb.h
- frmts/tiledb/tiledbcommon.cpp
- frmts/tiledb/tiledbdense.cpp
- frmts/tiledb/tiledbdrivercore.cpp
- frmts/tiledb/tiledbheaders.h
- frmts/tiledb/tiledbmultidim.cpp
- frmts/tiledb/tiledbmultidim.h
- frmts/tiledb/tiledbmultidimarray.cpp
- frmts/tiledb/tiledbmultidimattribute.cpp
- frmts/tiledb/tiledbmultidimattributeholder.cpp
- frmts/tiledb/tiledbmultidimgroup.cpp
- frmts/tiledb/tiledbsparse.cpp
This PR updates the TileDB backend to stop using deprecated TileDB APIs. The changes are straightforward and can be divided into three categories:
* `query.set_buffer(name, offsets, data)` → `query.set_data_buffer(name, data); query.set_offsets_buffer(name, offsets)`
* `offsets` and `data` are usually `std::vector`s, but in some cases were pairs of pointers and lengths
* `tiledb::Array(ctx, path, mode, timestamp)` → `tiledb::Array(ctx, path, mode, tiledb::TemporalPolicy(tiledb::TimeTravel, timestamp))`
* `query.set_subarray(subarray)` → `tiledb::Subarray subarray_obj(ctx, array); subarray_obj.set_subarray(subarray); query.set_subarray(subarray_obj);`
Validated by successfully building the GDAL library with a special build of TileDB that excludes all deprecated APIs …
> TileDB: migrate away from deprecated APIs

- autotest/pymod/gdaltest.py
should avoid failures such as https://github.com/OSGeo/gdal/actions/runs/8788601487/job/24116441947?pr=9724
> gdalurlopen(): handle http.client.RemoteDisconnected exception

- .github/workflows/alpine_numpy2/Dockerfile.ci
- .github/workflows/alpine_numpy2/build.sh
- .github/workflows/linux_build.yml
Refs #9751
This commit should be reverted once alpine:edge switches to numpy 2
> CI: add a configuration testing numpy 2.0.0rc1

- apps/ogrinfo_lib.cpp
- autotest/utilities/test_ogrinfo_lib.py
Fixes https://github.com/USDAForestService/gdalraster/pull/324
> GDALVectorInfo(): fix 3.9.0beta1 regression regarding passing layer names

- apps/ogrinfo_lib.cpp
- autotest/utilities/test_ogrinfo_lib.py
> [Backport release/3.9] GDALVectorInfo(): fix 3.9.0beta1 regression regarding passing layer names

- ogr/ogrsf_frmts/miramon/mm_gdal_functions.c
Validate that FirstRecordOffset as computed in
MM_ReadExtendedDBFHeaderFromFile() is not negative. Otherwise it gets later passed to MMCreateExtendedDBFIndex() which casts it to a uint64_t, and thus lead to unsigned integer overflow when doing:
```
fseek_function(f,
(MM_FILE_OFFSET)offset_1era +
(MM_FILE_OFFSET)bytes_acumulats_id_grafic,
SEEK_SET);
```
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=68303
@AbelPau Can you check that this fix is correct? Here's the file (to be unzipped first) on which fuzzers/ogr_miramon_fuzzer can trigger the unsigned integer overflow (no crash, but unsigned integer overflows are bugs in 99% of the cases): 
[ossfuzz_68303.zip](https://github.com/OSGeo/gdal/files/15130911/ossfuzz_68303.zip)
I'm wondering if the ultimate fix would not to change …
> Miramon: avoid Unsigned-integer-overflow in MMCreateExtendedDBFIndex()

- ogr/ogrsf_frmts/miramon/mm_gdal_functions.c
> [Backport release/3.9] Miramon: avoid Unsigned-integer-overflow in MMCreateExtendedDBFIndex()

- doc/source/api/python_bindings.rst
- swig/python/README.rst
- swig/python/pyproject.toml
- swig/python/setup.py.in
> [Backport release/3.9] pyproject.toml: use numpy>=2.0.0rc1 for python >=3.9

- .github/workflows/doc_build.yml
- doc/source/conf.py
I've tested locally those changes with a local build of the updated proj-docs Docker image per https://github.com/OSGeo/PROJ/pull/4128
> Doc: updates to support building with upcoming update proj-docs Docker image updated to Ubuntu 24.04

- doc/source/programs/gdaltransform.rst
Yes, `<pixel>` and `<line>` should just be called `<x>` and `<y>`, but I'm not that bold to rip things up here.
By the way I wonder if there is any _vector_ format that can contain GCPs so one needn't use `-gcp` but instead just have them in `srcfile`.
> Update gdaltransform.rst to hint that it is perfectly vector ready

- apps/gdalinfo_lib.cpp
- apps/ogrinfo_lib.cpp
> [Backport release/3.9] gdalinfo and ogrinfo -json: add newline character at end of JSON output

- autotest/ogr/ogr_mem.py
- ogr/ogrfeature.cpp
- ogr/ogrsf_frmts/generic/ogrlayerarrow.cpp
Also add an option IF_FIELD_NOT_PRESERVED=ERROR to error out when lossy  conversion occurs. Default behavior is to just emit a CE_Warning.
Fixes #9792
> OGRLayer::WriteArrowBatch(): add tolerance for field type mismatches if int32/int64/real

- autotest/ogr/ogr_mem.py
- ogr/ogrfeature.cpp
- ogr/ogrsf_frmts/generic/ogrlayerarrow.cpp
> [Backport release/3.9] OGRLayer::WriteArrowBatch(): add tolerance for field type mismatches if int32/int64/real

- autotest/ogr/ogr_parquet.py
- ogr/ogrsf_frmts/parquet/ogr_parquet.h
- ogr/ogrsf_frmts/parquet/ogrparquetdatasetlayer.cpp
- ogr/ogrsf_frmts/parquet/ogrparquetdriver.cpp
- ogr/ogrsf_frmts/parquet/ogrparquetlayer.cpp
> [Backport release/3.9] Parquet: fix ResetReading() implementation, when using the ParquetDataset API and when there's a single batch

- autotest/ogr/ogr_arrow.py
- ogr/ogrsf_frmts/generic/ogrlayerarrow.cpp
> [Backport release/3.9] OGRCloneArrowArray(): add missing support for 'tss:' Arrow type

- ogr/ogrsf_frmts/miramon/mm_gdal_driver_structs.h
- ogr/ogrsf_frmts/miramon/mm_gdal_functions.c
- ogr/ogrsf_frmts/miramon/mm_gdal_functions.h
- ogr/ogrsf_frmts/miramon/mm_rdlayr.c
- ogr/ogrsf_frmts/miramon/mm_wrlayr.c
There was a confusing access to the same file:
"pFExtDBF" and "pMMBDXP->pfDataBase"
This PR deletes pFExtDBF and substitute the use of pFExtDBF by pMMBDXP->pfDataBase.
Also controls some possible deferred null pointers to avoid crashes.
Actual tests are good enough to validate this PR.
This PR is an alternative to the solution in https://github.com/OSGeo/gdal/pull/9787 which is still opened because it's not clear why there are to pointers to the same file.
> MiraMonVector deleting duplicate reference and adding some controls about deferred null pointers

- doc/source/conf.py
We don't strictly need to import them at the beginning of conf.py, but importing them early helps in having a better error message if they cannot be imported rather than waiting later when autodoc tries to load them
In my case, this was due to an obscure situation. My libgdal.so in my build tree links to a /path/to/install-libjpeg-turbo/lib/libjpeg.so.8, with it being libjpeg-turbo 3.0 with new symbols. That full path to libjpeg is embedded in libgdal.so, but /path/to/install-libjpeg-turbo/lib was not pointed in LD_LIBRARY_PATH.
This worked fine when doing "from osgeo import gdal" from a 'regular' Python interpreter, or running pytest. But strangely, this failed within the sphinx-build process. The autodoc error message wasn't helpful just saying it couldn't import the osgeo module, …
> Doc building: import GDAL Python bindings early

- alg/los.cpp
- autotest/cpp/test_alg.cpp
* Implements basic support for reporting a location where LOS  is violated. It reports the location of the first detected violation.
* It's not symmetric due to bresenham's optimizations, but it will at least return one location where terrain is violated (if it is)
#9562 
* OS: Ubuntu 22
* Compiler: G++11
```bash
cmake -S . -B build -DBUILD_TESTING=ON -DCMAKE_BUILD_TYPE=Debug
cmake --build build --target gdal_unit_test -j `nproc`
./build/autotest/cpp/gdal_unit_test --gtest_filter="test_alg.GDALIsLineOfSightVisible*"
gdb ./build/autotest/cpp/gdal_unit_test
>>> r --gtest_filter="test_alg.GDALIsLineOfSightVisible*"
```
> LOS: Implement simple violation location reporting

- autotest/pyscripts/gdal2tiles/test_option_parser.py
- autotest/pyscripts/test_gdal2tiles.py
- swig/python/gdal-utils/osgeo_utils/gdal2tiles.py
> [Backport release/3.9] gdal2tiles: support an input dataset name not being a file

- autotest/ogr/ogr_miramon_vector.py
- ogr/ogrsf_frmts/miramon/mm_gdal_driver_structs.h
- ogr/ogrsf_frmts/miramon/mm_gdal_functions.c
- ogr/ogrsf_frmts/miramon/mm_gdal_functions.h
- ogr/ogrsf_frmts/miramon/mm_wrlayr.c
- ogr/ogrsf_frmts/miramon/ogrmiramonlayer.cpp
Recovers lost code from april 14th-15th-16th. A Test has been modified because of decimal modifications:
- Writing the appropriate decimals for each case for length, perimeter, area, etc.: if a layer is in longitude/latitude, it has more decimals than if it is in UTM. If it is unknown, then it is deduced according to the location of the coordinates of the first point (uncommon case). 
- Simplification of the variables used for writing to the DBF. 
- Changes in the names of some variables to facilitate code readability. 
- Exhaustive explanation of the function MM_SprintfDoubleSignifFigures(). 
- Correction in an internet address of specifications.
- Assignment of the units 'm' in special cases where it is better to include the units than not.
- Correction of error in the case of Triangle …
> MiraMon: Lost changes + update DBF date

- autotest/gdrivers/tiledb_multidim.py
- frmts/tiledb/tiledbmultidim.h
- frmts/tiledb/tiledbmultidimgroup.cpp
- TileDB multidim: prevent infinite recursion when opening an array in a group where there are 2 or more 2D+ arrays
- TileDBGroup::OpenMDArray(): fix opening an array, member of a group, which has no explicit name
> TileDB multidimensional fixes

- ogr/ogrsf_frmts/miramon/mm_wrlayr.c
Little fixes in MiraMon metadata files. More specifically:
- Making perimeter, area, and longitude symbolically representable. 
- Writing the correct HRS in polygon metadata.
- Writing CreationDate in metadata without a wrong timekeeper +00:00 
- Making units visible in all private fields in metadata (even if then don't have units, it's a defect behavior). 
- Making perimeter, area, and longitude symbolically representable 
- Making nodes visibles
No addicional tests are needed because are tiny modifications in some aspects used when visualizing layers in MiraMon
> MiraMonVector: Little fixes in metadata files

- gcore/gdal.h
- gcore/gdaldllmain.cpp
- gcore/gdaldrivermanager.cpp
- ogr/ogrsf_frmts/generic/ogrmutexeddatasource.cpp
- ogr/ogrsf_frmts/generic/ogrmutexedlayer.cpp
- ogr/ogrsf_frmts/generic/ogrsfdriverregistrar.cpp
and another cleanup
CC @elpaso
> Deprecate GDALDestroyDriverManager() and OGRCleanupAll() for GDALCleanup()

- doc/CMakeLists.txt
- doc/Makefile
- doc/source/development/dev_documentation.rst
- gdal.cmake
Fixes #5484
Updated dev_documentation.rst:
```rst
Building documentation
######################
Documentation can be generated with Makefile targets, from the ``doc`` subdirectory
of the GDAL source repository (only on Unix systems).
The following targets are available:
* ``html``: build HTML documentation into the ``doc/build/html`` directory, where
they can be viewed using a web browser.
* ``man``: build MAN pages into the ``doc/build/man`` directory.
* ``latexpdf``: build PDF documentation into the ``doc/build/pdf`` directory
* ``doxygen``: regenerate API Doxygen XML and HTML output, that is used by the
``html`` target. Doxygen content is not automatically rebuilt when source files
are modified, hence this target must be explicitly run to refresh it.
* ``doxygen_check_warnings``: same …
```
> CMake: add html, man, latexpdf, doxygen, doxygen_check_warnings, clean_doc targets

- ogr/ogrsf_frmts/miramon/mm_wrlayr.c
* Doesn't writtes the HRS in the polygon metadata files
* Documentates special fields in node metadata files
No tests needed. Not crucial PR.
> MiraMonVector: Fix two minor metadata issues

- ogr/ogrsf_frmts/miramon/mm_rdlayr.c
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=68585
Fixes other similar possible issues
Takes care of an overflow in a sum of unsigned int64's (everywhere "+=" is used)
> MiraMonVector: Fix issue 68585 from chromium (and other similar ones)

- alg/gdalwarper.cpp
- alg/gdalwarpkernel.cpp
- autotest/alg/warp.py
- autotest/pyscripts/test_gdal2tiles.py
- doc/source/programs/gdal2tiles.rst
- swig/python/gdal-utils/osgeo_utils/gdal2tiles.py
This is similar to the --excluded-values-pct-threshold option added in
https://github.com/OSGeo/gdal/pull/9631, but here this controls the
minimum amount of transparent/invalid/nodata source pixels to cause the
target pixels to be transparent.
Only used currently for average resampling
> Warper: add a NODATA_VALUES_PCT_THRESHOLD warping option, and expose it in gdal2tiles

- alg/gdalwarper.cpp
- alg/gdalwarpkernel.cpp
- autotest/alg/warp.py
- autotest/pyscripts/test_gdal2tiles.py
- doc/source/programs/gdal2tiles.rst
- swig/python/gdal-utils/osgeo_utils/gdal2tiles.py
> [Backport release/3.9] Warper: add a NODATA_VALUES_PCT_THRESHOLD warping option, and expose it in gdal2tiles

- .github/workflows/android_cmake.yml
- .github/workflows/clang_static_analyzer.yml
- .github/workflows/cmake_builds.yml
- .github/workflows/code_checks.yml
- .github/workflows/codeql.yml
- .github/workflows/conda.yml
- .github/workflows/delete_untagged_containers.yml
- .github/workflows/doc_build.yml
- .github/workflows/freebsd.yml.disabled
- .github/workflows/linux_build.yml
- .github/workflows/macos.yml
- .github/workflows/windows_build.yml
Adds `dependabot**` to push's branches-ignore for workflows with a `push` event trigger.
For CodeQL's workflow, it was also missing the branches-ignore for the `backport**` branches, it got also added.
Closes #9851
* OS:
* Compiler:
> CI: Skip running on pushes to dependabot and backport branches

- autotest/ogr/ogr_pg.py
- ogr/ogrsf_frmts/pg/ogrpgdatasource.cpp
> PG: emit warning when using GEOMETRY_NAME!=wkb_geometry on non-PostGIS enabled database

- autotest/ogr/ogr_pg.py
- ogr/ogrsf_frmts/pg/ogrpgdatasource.cpp
> [Backport release/3.9] PG: emit warning when using GEOMETRY_NAME!=wkb_geometry on non-PostGIS enabled database

- autotest/ogr/ogr_pg.py
- ogr/ogrsf_frmts/pg/ogr_pg.h
- ogr/ogrsf_frmts/pg/ogrpgdatasource.cpp
- ogr/ogrsf_frmts/pg/ogrpgtablelayer.cpp
Fixes 3.9.0-dev regression, introduced in b00e954fc09c44c390430c28b800bca14cdb0a4c This particularly broke ogr2ogr from Shapefile to PostgreSQL.
> PG: avoid aborting transactions when calling LoadMetadata() and ogr_system_tables.metadata doesn't exist

- swig/include/python/docs/gdal_operations_docs.i
- swig/python/CMakeLists.txt
Side note, I found the first result in the example a little surprising.
> Doc: Add Python docstring for gdal.FillNodata

- autotest/ogr/ogr_pg.py
- ogr/ogrsf_frmts/pg/ogr_pg.h
- ogr/ogrsf_frmts/pg/ogrpgdatasource.cpp
- ogr/ogrsf_frmts/pg/ogrpgtablelayer.cpp
> [Backport release/3.9] PG: avoid aborting transactions when calling LoadMetadata() and ogr_system_tables.metadata doesn't exist

- doc/source/development/cmake.rst
* Recommend using CMake's supplied find module if using older GDAL versions
* Remove broken recommendation for creating a GDAL::GDAL target
Note - Ubuntu 20 comes with CMake 3.16, so this should cover all non-EOL OS's that people will generally be using.
We intentionally ignore the edge cases of custom find modules because we will assume people writing those know 
what they are doing.
https://github.com/OSGeo/gdal/pull/9714#discussion_r1575040858
* OS: Ubuntu 22 with GDAL installed through APT
* Compiler: G++11
> Simplify usage for older GDAL by using CMake's supplied find module

- .github/workflows/codeql.yml
Reduces time spent on the CodeQL workflow, where the build is required in order to do the scan, but the actual results of the compilation are not important. Caching cannot be used.
Changes:
- Set build type to Debug, so less time is spent on unused optimizations passes.
- Disable building tests, automatically enabled when including CTest.
- Removing ccache and cmake from the list of software to install with apt-get, as they aren't used. (CMake is used, but not the one from apt-get).
- Use shortcut syntax for generating the project's buildsystem and the folder in one step (cmake 3.13, minimum supported is 3.16), and a similar way to invoke the build, that is independent of the generator used
- Use Ninja generator.
I finally opted in to use the Ninja Generator, as in my final comparisons, …
> CI(CodeQL): Speed up workflow by not compiling tests and using debug builds

- alg/viewshed.cpp
- alg/viewshed.h
Use member functions to eliminate some arguments.
Rename some variables for clarity.
Localize the height variable.
> Use member functions.

- .github/workflows/alpine/build.sh
- apps/sozip.cpp
- frmts/grib/gribdataset.cpp
- frmts/netcdf/netcdfvirtual.h
- frmts/pdf/pdfsdk_headers.h
- frmts/vrt/gdaltileindexdataset.cpp
- frmts/wcs/wcsdataset110.cpp
- frmts/zarr/zarr_array.cpp
- ogr/ogrsf_frmts/elastic/ogrelasticlayer.cpp
- ogr/ogrsf_frmts/gmlas/ogrgmlasutils.cpp
- ogr/ogrsf_frmts/libkml/ogrlibkmlfield.cpp
- ogr/swq_op_general.cpp
- port/cpl_recode.cpp
- third_party/LercLib/BitStuffer2.cpp
> Fix various C++20 compilation related issues

- autotest/gcore/vsis3.py
- port/cpl_aws.cpp
This PR extends the [container credentials](https://docs.aws.amazon.com/sdkref/latest/guide/feature-container-credentials.html) functionality of `vsis3` to cover more cases, particularly [EKS Pod Identities](https://docs.aws.amazon.com/eks/latest/userguide/pod-identities.html).
Two additional environment variables are now considered in the container credentials flow: `AWS_CONTAINER_AUTHORIZATION_TOKEN_FILE` and `AWS_CONTAINER_AUTHORIZATION_TOKEN`, with the former taking precedence over the latter (as described in AWS SDK documentation).
In addition to the included tests, I have tested the `AWS_CONTAINER_AUTHORIZATION_TOKEN_FILE`-based credential flow in practice on EKS. 
This functionality has been previously improved in #8859
> /vsis3/: include AWS_CONTAINER_CREDENTIALS_TOKEN in container credentials flow

- ogr/ogrsf_frmts/miramon/mm_gdal_driver_structs.h
- ogr/ogrsf_frmts/miramon/mm_wrlayr.c
Fix: adding which polygon cycles the stringline in the stringline metadata information
It's not an error but it's useful metadata information.
> MiraMonVector: adding which polygon cycles the linestring in the linestring metadata information

- autotest/gcore/vsis3.py
- port/cpl_aws.cpp
Backport #9877
**Authored by:** @jesseanttila-cai
> [Backport release/3.9] /vsis3/: include AWS_CONTAINER_CREDENTIALS_TOKEN in container credentials flow

- ogr/ogrsf_frmts/miramon/mm_gdal_driver_structs.h
- ogr/ogrsf_frmts/miramon/mm_wrlayr.c
> [Backport release/3.9] MiraMonVector: adding which polygon cycles the linestring in the linestring metadata information

- ogr/ogrsf_frmts/miramon/data/MM_m_idofic.csv
Adds more EPSG Spatial Reference Systems in the MiraMon look-up table MM_m_idofic.csv
With this update, MiraMon is expected to recognize more EPSG spatial reference systems.
No afectation in checks is expected. No changes in code.
> MiraMonVector: Adding more matchs in the look-up table MM_m_idofic.csv

- autotest/ogr/data/gml/link_to_immediate_child.gml
- autotest/ogr/ogr_gml.py
- ogr/ogrsf_frmts/gml/gmlhandler.cpp
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=68850
> GML: fix memory leak due do xlink:href substitution in a non-nominal case.

- autotest/ogr/ogr_flatgeobuf.py
- ogr/ogrsf_frmts/flatgeobuf/ogrflatgeobuflayer.cpp
> FlatGeoBuf: more explicit error message in case of feature geometry type != layer geometry type

- autotest/ogr/data/gml/link_to_immediate_child.gml
- autotest/ogr/ogr_gml.py
- ogr/ogrsf_frmts/gml/gmlhandler.cpp
> [Backport release/3.9] GML: fix memory leak due do xlink:href substitution in a non-nominal case.

- autotest/ogr/ogr_flatgeobuf.py
- ogr/ogrsf_frmts/flatgeobuf/ogrflatgeobuflayer.cpp
> [Backport release/3.9] FlatGeoBuf: more explicit error message in case of feature geometry type != layer geometry type

- ogr/ogrsf_frmts/osm/data/osmconf.ini
In https://gdal.org/drivers/vector/osm.html#configuration we read
> The customization is essentially which OSM attributes and keys should be translated into OGR layer fields.
I therefore conclude the direction of the import is actually into OGR, and thus make it clear in the top of the file.
> Update osmconf.ini clarifying direction

- ogr/ogrsf_frmts/miramon/mm_wrlayr.c
Fixes an error recently introduced when a .arc is created with no .pol associated: a Ciclat1="" is wrongly created in A.rel metadata file. Usually Ciclat1 is filled with the polygon name that has the coordinates in this arc file.
The error was introduced in https://github.com/OSGeo/gdal/pull/9885
> MiraMonVector: Fixing recently introduced error in linestring metadata file

- autotest/gcore/vsifile.py
- autotest/gcore/vsioss.py
- autotest/gcore/vsis3.py
- autotest/pymod/webserver.py
- port/cpl_vsi.h
- port/cpl_vsi_virtual.h
- port/cpl_vsil.cpp
- port/cpl_vsil_curl_class.h
- port/cpl_vsil_s3.cpp
- swig/include/cpl.i
- swig/include/python/typemaps_python.i
Copy a source file into a target file in a way that can (potentially)
be restarted.
This function provides the possibility of efficiently restarting upload of
large files to cloud storage that implements upload in a chunked way,
such as /vsis3/ and /vsigs/.
For other destination file systems, this function may fallback to
VSICopyFile() and not provide any smart restartable implementation.
Example of a potential workflow:
```cpp
char* pszOutputPayload = NULL;
int ret = VSICopyFileRestartable(pszSource, pszTarget, NULL,
&pszOutputPayload, NULL, NULL, NULL);
while( ret == 1 ) // add also a limiting counter to avoid potentiall endless looping
{
// TODO: wait for some time
char* pszOutputPayloadNew = NULL;
const char* pszInputPayload = pszOutputPayload;
ret = VSICopyFileRestartable(pszSource, …
```
> Add VSICopyFileRestartable() to allow restart of upload of large files

- apps/ogrinfo_lib.cpp
- autotest/utilities/test_ogrinfo.py
Related to using argparse
Before this fix, ``ogrinfo`` returns:
```
ERROR 4: : No such file or directory
ogrinfo failed - unable to open ''.
```
With this fix, it returns:
```
ERROR 1: filename: 1 argument(s) expected. 0 provided.
Usage: ogrinfo [--help] [--long-usage] [--help-general]
[-json] [-ro] [-update] [--quiet] [-fid <FID>] [-spat <xmin> <ymin> <xmax> <ymax>] [-geomfield <field>]
[-where <restricted_where>]
[[-sql <statement|@filename>]|[-rl]]
[-dialect <dialect>] [-al]
[[-summary]|[-features]]
[-limit <nb_features>] [-fields YES|NO] [-geom YES|NO|SUMMARY|WKT|ISO_WKT] [-oo <NAME=VALUE>]... [-nomd]
[-listmdd] [-mdd <domain>]... [-nocount] [-noextent] [-extent3D] [-nogeomtype]
[-wkt_format WKT1|WKT2|WKT2_2015|WKT2_2019] [-fielddomain <name>] [-if <format>]...
filename …
```
> ogrinfo: fix error message when not specifying a filename

- ogr/ogrsf_frmts/miramon/mm_wrlayr.c
> [Backport release/3.9] MiraMonVector: Fixing recently introduced error in linestring metadata file

- apps/ogrinfo_lib.cpp
- autotest/utilities/test_ogrinfo.py
> [Backport release/3.9] ogrinfo: fix error message when not specifying a filename

- doc/source/programs/ogrinfo.rst
Ogrinfo doesn't add the "# " anymore. Today we sync the man page with the current output.
> Update ogrinfo.rst removing obsolete "# " not present today

- doc/source/programs/ogrinfo.rst
Here we truncate the coordinate system's out of control lines that need to be reined in on man pages.
1. At 1200 characters long, we have already gone beyond the edge of even the most luxurious man page terminal margin, and so it is wasted anyway. Looks terrible in many user setups.
2. Confirmed also wasted on https://gdal.org/programs/ogrinfo.html
1. The man page already has an example above of them.
> Update ogrinfo.rst chopping wild 1200 character long line

- autotest/ogr/ogr_miramon_vector.py
- ogr/ogrsf_frmts/miramon/mm_gdal_driver_structs.h
- ogr/ogrsf_frmts/miramon/mm_wrlayr.c
- ogr/ogrsf_frmts/miramon/ogrmiramonlayer.cpp
During the translation from a 30 Gigabyte GeoPackage, it was detected that the MiraMonVector driver did not properly detect when the offset for heights exceeded the maximum possible value in a 4-byte variable (in version 1.1). This has been fixed, and an extra check has been added at the end of the translation to ensure that no offset overflows occur.
Once this was corrected, it was also noticed that a key feature for saving space with heights was not being properly used: the MiraMon format allows writing a height only once if it is the same for all vertices of a linestring. According to the specifications, if the number of heights for the linestring is negative, then the height applies to each vertex of the linestring. While this was not a bug, it will represent significant space savings …
> MiraMonVector: Fixing the way that Z are written in MiraMon layers

- autotest/ogr/ogr_miramon_vector.py
- ogr/ogrsf_frmts/miramon/mm_gdal_driver_structs.h
- ogr/ogrsf_frmts/miramon/mm_wrlayr.c
- ogr/ogrsf_frmts/miramon/ogrmiramonlayer.cpp
> [Backport release/3.9] MiraMonVector: Fixing the way that Z are written in MiraMon layers

- ogr/ogrsf_frmts/miramon/mm_gdal_functions.c
- ogr/ogrsf_frmts/miramon/mm_gdal_functions.h
- ogr/ogrsf_frmts/miramon/mm_wrlayr.c
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=68809
A copy of a pointer was freed instead of the pointer.
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=68809
> MiraMonVector: Fixing chromium bug 68809

- doc/source/user/sql_sqlite_dialect.rst
Also folded monster long line.
(Single quotes have actually been part of the shell for 50 years.)
> Update sql_sqlite_dialect.rst to include single quote example

- doc/source/user/sql_sqlite_dialect.rst
(Else the reader thinks, "Hey, you said 'geometry', and then you use 'GEOMETRY'!")
> Update sql_sqlite_dialect.rst avoiding unexplained case change

- apps/gdal_utils_priv.h
- apps/gdalargumentparser.cpp
- apps/gdalargumentparser.h
- apps/gdaldem_bin.cpp
- apps/gdaldem_lib.cpp
```gdaldem --long-usage
Usage: gdaldem [--help] [--long-usage] [--help-general] {TPI,TRI,aspect,color-relief,hillshade,roughness,slope}
Tools to analyze and visualize DEMs.
-h, --help         Shows short help message and exits. 
--long-usage       Shows long help message and exits. 
--help-general     Report detailed help on general options. 
Subcommands:
TPI               Compute the Topographic Position Index.
TRI               Compute the Terrain Ruggedness Index.
aspect            Compute aspect.
color-relief      Color relief computed from the elevation and a text-based color configuration file.
hillshade         Compute hillshade.
roughness         Compute the roughness of the DEM.
slope             Compute slope.
For more details, consult …
```
> [gdaldem] Use GDALArgumentParser

- ogr/ogrsf_frmts/miramon/mm_wrlayr.c
Fixes chromium bug 68809.
The error was not to free the table MMDB when the first feature is created and fails. This table is created only when the first feature is successfully created. If is not successfully created this table has to be deleted.
https://github.com/OSGeo/gdal/pull/9954
> MiraMonVector: Fixing chromium bug 68809 correctly

- autotest/ogr/data/geojson/featuretype.json
- autotest/ogr/data/jsonfg/crs_none_fc_mixed_feat_no_conformsTo.json
- autotest/ogr/ogr_geojson.py
- autotest/ogr/ogr_jsonfg.py
- gcore/gdaldriver.cpp
- ogr/ogrsf_frmts/geojson/ogrgeojsondatasource.cpp
- ogr/ogrsf_frmts/geojson/ogrgeojsonutils.cpp
- ogr/ogrsf_frmts/geojson/ogrgeojsonutils.h
- port/cpl_json_streaming_parser.cpp
- port/cpl_json_streaming_parser.h
Fixes https://github.com/OSGeo/gdal/issues/9946
> GeoJSON/JSONFG: do not recognize GeoJSON files with a featureType feature property as JSONFG     

- autotest/gcore/vsiaz.py
- port/cpl_azure.h
- port/cpl_vsil.cpp
- port/cpl_vsil_adls.cpp
- port/cpl_vsil_az.cpp
- port/cpl_vsil_curl_class.h
- port/cpl_vsil_gs.cpp
- port/cpl_vsil_oss.cpp
- port/cpl_vsil_s3.cpp
- port/cpl_vsil_swift.cpp
to be able to overcome the 195 GiB file size limit when using append blocks, which is the default mode.
> /vsiaz/: add BLOB_TYPE=BLOCK and CHUNK_SIZE options to VSIFOpenEx2L()

- autotest/gcore/vsiaz.py
- autotest/gcore/vsicurl.py
- doc/source/user/configoptions.rst
- doc/source/user/virtual_file_systems.rst
- port/cpl_http.cpp
- port/cpl_http.h
- port/cpl_vsil_adls.cpp
- port/cpl_vsil_az.cpp
- port/cpl_vsil_curl.cpp
- port/cpl_vsil_curl_class.h
- port/cpl_vsil_curl_streaming.cpp
- port/cpl_vsil_gs.cpp
- port/cpl_vsil_s3.cpp
- port/cpl_vsil_swift.cpp
- port/cpl_vsil_webhdfs.cpp
*  CPLHTTPFetch(): add a RETRY_CODES option (GDAL_HTTP_RETRY_CODES config option)
Fixes #9941
```
-  .. config:: GDAL_HTTP_RETRY_CODES
:choices: ALL or comma-separated list of codes
:since: 3.10
Specify which HTTP error codes should trigger a retry attempt.
Valid values are ``ALL`` or a comma-separated list of HTTP codes.
By default, 429, 500, 502, 503 or 504 HTTP errors are considered, as
well as other situations with a particular HTTP or Curl error message.
```
*  Add C++ facilities for HTTP retry logic
> CPLHTTPFetch(): add a RETRY_CODES option, and C++'ify HTTP retry logic

- .github/workflows/linux_build.yml
now that v0.6.12 is out with a fix
> CI: linux_build.yml: remove pin to coverage-reporter-version v0.6.10

- doc/source/programs/gdal_contour.rst
Tell users on the man page. Don't wait for the traffic cop (error message) to tell them the exact same thing!
> Update gdal_contour.rst to say must specify either -i or -fl or -e

- apps/argparse/argparse.hpp
> argparse.hpp: add argument name after 'Too few arguments' error

- apps/argparse/argparse.hpp
> [Backport release/3.9] argparse.hpp: add argument name after 'Too few arguments' error

- autotest/gcore/mask.py
- gcore/gdalnodatamaskband.cpp
The method had a fallback path when allocating a temporary buffer of the size of the one passed ot the method, that intended to use a less memory intensive block-based approach, but this was buggy. Fix this, and add testing for the fallback.
Also, when attempting the fallback, emits a CE_Warning instead of a CE_Failure.
Fixes https://github.com/rasterio/rasterio/discussions/3028
> GDALNoDataMaskBand::IRasterIO(): fix crash on memory allocation failure

- autotest/ogr/ogr_sql_test.py
- ogr/ogrsf_frmts/generic/ogr_gensql.cpp
- ogr/swq_select.cpp
and error out if it doesn't exist, otherwise it evaluates as COUNT(*)
Fixes #9972
> OGRSQL: validate column name in COUNT(field_name)

- autotest/ogr/data/kml/point_with_external_style.kml
- autotest/ogr/data/kml/style_of_point_with_external_style/style.kml
- autotest/ogr/ogr_libkml.py
- ogr/ogrsf_frmts/libkml/ogr_libkml.h
- ogr/ogrsf_frmts/libkml/ogrlibkmldatasource.cpp
- ogr/ogrsf_frmts/libkml/ogrlibkmlfeaturestyle.cpp
> LIBKML: fix handling of styleUrl element referencing to an external document

- autotest/ogr/ogr_sql_test.py
- ogr/ogrsf_frmts/generic/ogr_gensql.cpp
- ogr/swq_select.cpp
> [Backport release/3.9] OGRSQL: validate column name in COUNT(field_name)

- autotest/ogr/data/kml/point_with_external_style.kml
- autotest/ogr/data/kml/style_of_point_with_external_style/style.kml
- autotest/ogr/ogr_libkml.py
- ogr/ogrsf_frmts/libkml/ogr_libkml.h
- ogr/ogrsf_frmts/libkml/ogrlibkmldatasource.cpp
- ogr/ogrsf_frmts/libkml/ogrlibkmlfeaturestyle.cpp
> [Backport release/3.9] LIBKML: fix handling of styleUrl element referencing to an external document

- ogr/ogrsf_frmts/generic/ogrlayerarrow.cpp
- port/cpl_vsisimple.cpp
also remove comment suggesting using std::aligned_storage since it is deprecated in C++23
> VSIMallocAligned(): make behaviour more predictable when nSize == 0

- doc/source/programs/gdal2tiles.rst
- doc/source/programs/gdal2xyz.rst
- doc/source/programs/gdal_calc.rst
- doc/source/programs/gdal_edit.rst
- doc/source/programs/gdal_fillnodata.rst
- doc/source/programs/gdal_merge.rst
- doc/source/programs/gdal_pansharpen.rst
- doc/source/programs/gdal_polygonize.rst
- doc/source/programs/gdal_proximity.rst
- doc/source/programs/gdal_retile.rst
- doc/source/programs/gdal_sieve.rst
- doc/source/programs/gdalattachpct.rst
- doc/source/programs/gdalcompare.rst
- doc/source/programs/gdalmove.rst
- doc/source/programs/ogr_layer_algebra.rst
- doc/source/programs/ogrmerge.rst
- doc/source/programs/pct2rgb.rst
- doc/source/programs/rgb2pct.rst
This applies a uniform ReST note to the documentation of the Python utilities. The format from `gdal_retile` has been copied and applied to all the other utilities.
As pointed out by @jratike80 in #10053, the note was missing entirely for `gdalmove`. This is now fixed with this PR. 
#10053
* OS:
* Compiler:
> Use uniform note in Python utility docs

- ogr/ogrsf_frmts/miramon/mm_gdal_functions.c
- ogr/ogrsf_frmts/miramon/mm_gdal_functions.h
- ogr/ogrsf_frmts/miramon/mm_wrlayr.c
Solves the case of giving a false error when the translating a polígon with a capital extension reference to its arc.
Some other strstr() have been corrected to a version of windows stristr() called MM_stristr() cause it's not important to be case sensitive
> MiraMonVector: fix a case sensitive comparison

- doc/source/programs/gdal_fillnodata.rst
Proof that the man page was wrong:
```
$ gdal_fillnodata 0.tif
usage:  ...
gdal_fillnodata: error: the following arguments are required: dst_filename
```
> Update gdal_fillnodata.rst adding destination file requirement

- alg/gdalsimplewarp.cpp
- alg/gdalwarper.cpp
- swig/include/python/docs/gdal_operations_docs.i
> Doc: mark GDALSimpleImageWarp() and GDALReprojectImage() as superseded per GDALWarp()

- autotest/gcore/vsifile.py
- autotest/ogr/ogr_libkml.py
- autotest/pymod/gdaltest.py
- swig/include/cpl.i
- swig/include/python/gdal_python.i
This PR adds a `gdal.vsi_open()` function that returns a file-like object, allowing virtual files to be used as "regular" Python files in some cases.  For example, a zipped CSV can be read using the Python `csv` module:
```
with gdal.vsi_open(f'/vsizip/prime_meridian.csv') as f:
records = [x for x in csv.DictReader(f)]
assert records[2]['INFORMATION_SOURCE'] == "Institut Geographique National (IGN), Paris"
```
Still need to correctly handle different linebreak/OS combinations, ensure errors are raised when accessing a closed file, handle append mode (or raise error), and probably other things.
> autotest: Add a VSIFile wrapper class

- doc/source/programs/gdal_contour.rst
(No need to say -i must be positive, as that is covered in #10103.)
> Update gdal_contour.rst clarifying "-off"

- gcore/gdalmultidim.cpp
Remove a misleading and superfluous semicolon in the source code
This should arguably have been caught by clang-format.
> gdalmultidim.cpp: Remove superfluous semicolon

- autotest/gdrivers/netcdf_multidim.py
- autotest/gdrivers/zarr_driver.py
- frmts/netcdf/netcdfmultidim.cpp
- frmts/zarr/zarr_attribute.cpp
- gcore/gdal.h
- gcore/gdal_priv.h
- gcore/gdalmultidim.cpp
- swig/include/MultiDimensional.i
- swig/include/python/gdal_python.i
- swig/include/python/typemaps_python.i
The Zarr file format stores attributes in JSON. This PR stores int64 values as integer JSON values instead of converting them to floating-point values.
https://github.com/OSGeo/gdal/issues/10062
> Zarr: Allow int64 attributes

- autotest/gdrivers/netcdf_multidim.py
- frmts/netcdf/netcdfmultidim.cpp
> [Backport release/3.9] netCDFAttribute::IWrite(): fix writing an array of (NC4) strings, from a non-string array

- ogr/ogrsf_frmts/miramon/mm_gdal_driver_structs.h
- ogr/ogrsf_frmts/miramon/mm_wrlayr.c
Allows to read more versions of metadata files. The readed keys are the same in all these versions.
> MiraMonVector: fixing accepted metadata versions/subversions

- apps/argparse/README.TXT
- apps/argparse/argparse.hpp
- apps/gdal_create.cpp
Update to PR https://github.com/p-ranav/argparse/pull/356
Also fixes the incompatibility between store_into and scan and action: when the three methods above were called, being all based on the (unique) action, the last one would overwrite the previous ones.
This issue was making the parser strictly dependent on the order of the scan/store_into/action calls making them mutually exclusive.
> [argparse] update library

- ogr/ogrsf_frmts/miramon/mm_gdal_driver_structs.h
- ogr/ogrsf_frmts/miramon/mm_wrlayr.c
> [Backport release/3.9] MiraMonVector: fixing accepted metadata versions/subversions

- autotest/ogr/ogr_openfilegdb_write.py
- ogr/ogrsf_frmts/openfilegdb/filegdbtable.cpp
- ogr/ogrsf_frmts/openfilegdb/filegdbtable.h
- ogr/ogrsf_frmts/openfilegdb/filegdbtable_write.cpp
- ogr/ogrsf_frmts/openfilegdb/filegdbtable_write_fields.cpp
- ogr/ogrsf_frmts/openfilegdb/ogropenfilegdbdatasource.cpp
- ogr/ogrsf_frmts/openfilegdb/ogropenfilegdbdatasource_write.cpp
- ogr/ogrsf_frmts/openfilegdb/ogropenfilegdblayer_write.cpp
- ogr/ogrsf_frmts/openfilegdb/test_ofgdb_write.cpp
Related to https://github.com/qgis/QGIS/issues/57536. That issue itself is much likely due to using a version of GDAL prior to fdf39012788b1110b3bf0ae6b8422a528f0ae8b6 / GDAL 3.9.0.
The following set of fixes 
- OpenFileGDB writer: correctly set flag on non-editable Shape_Length/Shape_Area special fields
We fix both the flag attribute of the field declaration in .gdbtable,
and the XML declaration of the field.
- OpenFileGDB writer: .gdbtable header must be rewritten when updating an existing feature at the end of file
The only consequence of the omission of that fix is that the file size
in the .gdbtable could be incorrect. A wrong file size in the header has no
consequence on OpenFileGDB reader/writer. It also doesn't seem to affect
Esri reader side, but it could *potentially* affect the …
> OpenFileGDB: a couple writer side fixes

- alg/viewshed.cpp
- alg/viewshed.h
- autotest/utilities/test_gdal_viewshed.py
This changes the implementation to use functions and uses threads for the separable bits. It also merges the two result vectors into one.
> gdal_viewshed: use functions in implementation

- alg/gdaltransformer.cpp
- autotest/gdrivers/netcdf.py
- autotest/utilities/test_gdalwarp_lib.py
- frmts/netcdf/netcdfdataset.cpp
Fixes https://lists.osgeo.org/pipermail/gdal-dev/2024-May/059050.html
- netCDF: try to better round geotransform values when read from single-precsion lon/lat float arrays
- Warper: relax longitude extend check to decide whether we can insert a CENTER_LONG wrapping longitude
> Fix issue related to wrapping a netCDF dataset accrong antimeridian

- autotest/gdrivers/hdf5multidim.py
- frmts/hdf5/gh5_convenience.cpp
- frmts/hdf5/hdf5_api.h
- frmts/hdf5/hdf5dataset.cpp
- frmts/hdf5/hdf5dataset.h
- frmts/hdf5/hdf5imagedataset.cpp
- frmts/hdf5/hdf5multidim.cpp
Fixes https://github.com/HDFGroup/hdf5/issues/4527
> HDF5: add support for libhdf5 >= 1.14.4.2 when built with Float16

- apps/gdalmanage.cpp
- autotest/pymod/test_cli_utilities.py
- autotest/utilities/test_gdalmanage.py
- doc/source/programs/gdalmanage.rst
```
Usage: gdalmanage [--help] [--long-usage] [--help-general] {copy,delete,identify,rename}
Identify, delete, rename and copy raster data files.
-h, --help         Shows short help message and exits. 
--long-usage       Shows long help message and exits. 
--help-general     Report detailed help on general options. 
Subcommands:
copy              Create a copy of the raster file with a new name.
delete            Delete the raster file(s).
identify          List data format of file(s).
rename            Change the name of the raster file.
For more details, consult the full documentation for the gdalmanage utility https://gdal.org/programs/gdalmanage.html
```
```
Usage: identify [--help] [--long-usage] [--help-general]
[-r] [-fr] [-u]
[<datasetname>]...
List data format …
```
> [gdalmanage] Use GDALArgumentParser

- autotest/ogr/ogr_pg.py
- doc/source/drivers/vector/pg.rst
- ogr/ogrsf_frmts/pg/ogr_pg.h
- ogr/ogrsf_frmts/pg/ogrpgdatasource.cpp
- ogr/ogrsf_frmts/pg/ogrpgtablelayer.cpp
> [Backport release/3.9] PG: avoid errors related to ogr_system_tables.metadata when user has not enough permissions

- apps/ogr2ogr_lib.cpp
- autotest/ogr/ogr_fgdb.py
- ogr/ogrsf_frmts/filegdb/FGdbLayer.cpp
> [Backport release/3.9] FileGDB: fix creating a geometry-less table with ogr2ogr (3.9.0 regression)

- autotest/ogr/data/gml/same_nested_property_name.gml
- autotest/ogr/ogr_gml.py
- doc/source/drivers/vector/gml.rst
- ogr/ogrsf_frmts/gml/gmlreaderp.h
- ogr/ogrsf_frmts/gml/hugefileresolver.cpp
- ogr/ogrsf_frmts/gml/ogrgmldatasource.cpp
> [Backport release/3.9] GML: fix issue with nested elements with identical names in GML_SKIP_RESOLVE_ELEMS=HUGE mode

- .github/workflows/cmake_builds.yml
Cf https://github.com/actions/runner-images/issues/10004
Other approach attempted in
https://github.com/rouault/gdal/commit/9ff56b3749ef28b8a2c06fefc62b4ecfda5d5090 didn't result in finding a recent enough vcruntime140.dll
> CI: workaround issue with too old vcruntime140.dll on image windows-latest 20240603.1.0

- alg/gdal_crs.cpp
- apps/ogr2ogr_lib.cpp
- autotest/utilities/test_ogr2ogr_lib.py
> [Backport release/3.9] ogr2ogr: error out if GCP transform creation fails; GCPTransformer: accept only 2 points for order=1 transformer

- apps/ogrlineref.cpp
```
Usage: ogrlineref [--help] [--long-usage] [--help-general]
[--quiet] [-progress] [-of <output_format>] [-dsco <NAME>=<VALUE>]... [-lco <NAME>=<VALUE>]...
[-create] [-l <src_line_datasource_name>] [-ln <layer_name>] [-lf <field_name>]
[-p <src_repers_datasource_name>] [-pn <layer_name>] [-pm <pos_field_name>] [-pf <field_name>]
[-r <src_parts_datasource_name>] [-rn <layer_name>] [-o <dst_datasource_name>] [-on <layer_name>]
[-of <field_name>] [-s <step>] [-get_pos] [-x <x>] [-y <y>] [-get_coord] [-m <position>]
[-get_subline] [-mb <position>] [-me <position>]
Create linear reference and provide some calculations using it.
-h, --help                       Shows short help message and exits. 
--long-usage                     Shows long help message and exits. …
```
> [ogrlineref] Use GDALArgumentParser

- swig/python/README.rst
The missing newline is preventing a code block from being correctly rendered in the python README and on GDAL's PyPI page: https://pypi.org/project/GDAL/
> Fix rendering of code block in python readme

- doc/source/programs/gdaltransform.rst
- doc/source/programs/gdalwarp.rst
- doc/source/programs/ogr2ogr.rst
- doc/source/user/coordinate_epoch.rst
Substitutes
`-s_coord_epoch and -t_coord_epoch are currently mutually exclusive, due to lack of support for transformations between two dynamic CRS.`
with
`Before PROJ 9.4, -s_coord_epoch and -t_coord_epoch were mutually exclusive, due to lack of support for transformations between two dynamic CRS.`
in [coordinate_epoch.rst](https://gdal.org/user/coordinate_epoch.html)
and substitutes
`Before PROJ 9.4, :option:`-s_coord_epoch` and :option:`-t_coord_epoch` are mutually exclusive`
with
`Before PROJ 9.4, :option:`-s_coord_epoch` and :option:`-t_coord_epoch` were mutually exclusive`
in [ogr2ogr.rst](https://gdal.org/programs/ogr2ogr.html), [gdalwarp.rst](https://gdal.org/programs/gdalwarp.html) and [gdaltransform.rst](https://gdal.org/programs/gdaltransform.html).
I'm not a native English …
> Docs: fix coordinate_epoch.rst since PROJ 9.4

- alg/contour.cpp
- autotest/alg/contour.py
> [Backport release/3.9] GDALContourGenerateEx(): validate LEVEL_INTERVAL option

- autotest/osr/osr_basic.py
- ogr/ogrspatialreference.cpp
> [Backport release/3.9] OGRSpatialReference: workaround bug of PROJ < 9.5 regarding wrong conversion id for UTM south

- apps/gdalinfo_lib.cpp
- apps/ogrinfo_lib.cpp
- autotest/utilities/test_gdalinfo_lib.py
- autotest/utilities/test_ogrinfo_lib.py
> [Backport release/3.9] gdalinfo/ogrinfo text output: avoid weird truncation of coordinate epoch when its value is {year}.0

- autotest/gcore/vsiadls.py
- autotest/gcore/vsiaz.py
- autotest/gcore/vsifile.py
- autotest/gcore/vsigs.py
- autotest/gcore/vsioss.py
- autotest/gcore/vsis3.py
- autotest/gcore/vsiswift.py
- port/CMakeLists.txt
- port/cpl_vsi.h
- port/cpl_vsi_virtual.h
- port/cpl_vsil.cpp
- port/cpl_vsil_adls.cpp
- port/cpl_vsil_az.cpp
- port/cpl_vsil_chunked_write_handle.cpp
- port/cpl_vsil_curl_class.h
- port/cpl_vsil_gs.cpp
- port/cpl_vsil_gzip.cpp
- port/cpl_vsil_oss.cpp
- port/cpl_vsil_s3.cpp
- port/cpl_vsil_swift.cpp
- swig/include/cpl.i
- swig/include/python/gdal_python.i
- swig/include/python/typemaps_python.i
Using this API directly is generally not needed, but in very advanced cases,
as VSIFOpenL(..., "wb") + VSIFWriteL(), VSISync(), VSICopyFile() or
VSICopyFileRestartable() may be able to leverage it when needed.
This is only implemented for the /vsis3/, /vsigs/, /vsiaz/, /vsiadls/
and /vsioss/ virtual file systems.
The typical workflow is to do :
- VSIMultipartUploadStart()
- VSIMultipartUploadAddPart(): several times
- VSIMultipartUploadEnd()
If VSIMultipartUploadAbort() is supported by the filesystem (VSIMultipartUploadGetCapabilities()
can be used to determine it), this function should be called to cancel an
upload. This can be needed to avoid extra billing for some cloud storage
providers.
> Add VSIMultipartUploadXXXXX() API for multi-part upload

- frmts/mrf/LERCV1/Lerc1Image.cpp
- frmts/mrf/LERCV1/Lerc1Image.h
Make LERC V1 encoding in MRF about twice as fast, by avoiding temporary vector use
* OS:
* Compiler:
> MRF: Faster LERC V1 encoding

- autotest/gcore/tiff_write.py
- frmts/gtiff/gtiffdataset_write.cpp
> [Backport release/3.9] GTiff writer: limit number of GCPs in GeoTIFF tag to 10922 to avoid overflowing uint16_t

- ogr/ogrsf_frmts/generic/ogrlayerarrow.cpp
- ogr/ogrsf_frmts/mvt/ogrmvtdataset.cpp
> Fix crash in ogr2ogr (or Arrow based workflows) from GeoPackage/GeoParquet to PMTiles (3.9.0 regression)

- ogr/ogrsf_frmts/generic/ogrlayerarrow.cpp
- ogr/ogrsf_frmts/mvt/ogrmvtdataset.cpp
> [Backport release/3.9] Fix crash in ogr2ogr (or Arrow based workflows) from GeoPackage/GeoParquet to PMTiles (3.9.0 regression)

- autotest/ogr/ogr_geom.py
- swig/include/python/ogr_python.i
Fixes https://github.com/OSGeo/gdal/issues/9920
> Python bindings: Avoid crash when using orphaned subgeometry

- alg/contour.cpp
- alg/marching_squares/level_generator.h
- alg/marching_squares/square.h
- alg/marching_squares/utility.h
- autotest/alg/contour.py
- autotest/cpp/test_marching_squares_contour.cpp
- autotest/cpp/test_marching_squares_polygon.cpp
- autotest/cpp/test_marching_squares_square.cpp
- autotest/cpp/test_marching_squares_tile.cpp
- autotest/utilities/test_gdal_contour.py
Fixes #10167
There's currently an asymmetry since the maximum raster value is included. This is due how the marching square thresholding compares pixel values to the candidate contour levels. Add a special case to modify the comparison for the level that matches the minimum raster value.
> Contour: include minimum raster value as contour line when it exactly matches the first level

- doc/source/download.rst
- doc/source/download_past.rst
- Move old releases to "Past Releases" page
- Migrate information about additional download sources from Trac
- Organize section headings:
If merged, I would remove all content from https://trac.osgeo.org/gdal/wiki/DownloadingGdalBinaries.
> Doc: Updates to download.rst

- port/cpl_vsil.cpp
I was a little confused with this yesterday, found out my error was including a trailing slash after the bucket name...
> State that VSISetPathSpecificOption path should not include trailing slash

- docker/ubuntu-full/Dockerfile
- docker/ubuntu-small/Dockerfile
Make the ubuntu-small image use the same packages as ubuntu-full
where relevant. Also tweak some whitespace and comments in the ubuntu-full image to align with the ubuntu-small image.
I'm stuck on GDAL 3.4.3 for performance reasons and have no idea how to test this, so I have only verified that the small image builds.
* OS:
* Compiler:
> Dockerfile: align ubuntu-small with ubuntu-full

- .github/workflows/cmake_builds.yml
- swig/python/CMakeLists.txt
- swig/python/trimmedsysconfig.py
> Python bindings: fix/workaround installation into /usr/local/lib/python{version}/dist-packages when prefix is /usr/local

- alg/gdalsievefilter.cpp
- autotest/alg/sieve.py
Fixes https://github.com/rasterio/rasterio/issues/3101
> GDALSieveFilter(): avoid assert() when all pixels are masked (3.9.0 regression)

- docker/ubuntu-full/Dockerfile
- docker/ubuntu-full/bh-proj.sh
- docker/ubuntu-small/Dockerfile
Fix the rm command near the top of the Dockerfile for the Ubuntu images, remove apt lists to reduce size of image, and pass --no-install-recommends when installing patchelf to avoid surprise packages in the future.
* OS:
* Compiler:
> ubuntu/Dockerfile: fix rm & remove apt lists

- alg/gdalsievefilter.cpp
- autotest/alg/sieve.py
> [Backport release/3.9] GDALSieveFilter(): avoid assert() when all pixels are masked (3.9.0 regression)

- autotest/gdrivers/vrtfilt.py
- frmts/vrt/vrtfilters.cpp
> VRT: fix serialization of separatable kernel in VRTKernelFilteredSource

- autotest/ogr/ogr_layer_algebra.py
- ogr/ogrsf_frmts/generic/ogrlayer.cpp
Fixes https://lists.osgeo.org/pipermail/gdal-dev/2024-June/059103.html
> OGR layer algebra: honour PROMOTE_TO_MULTI=YES for Points

- autotest/ogr/ogr_sqlite.py
- ogr/ogrsf_frmts/sqlite/ogrsqliteutility.cpp
Fixes https://github.com/qgis/QGIS/issues/57823
> SQLite/GPKG: detect UNIQUE constraints expressed as a ', CONSTRAINT name UNIQUE (column_name)' at the end of CREATE TABLE

- autotest/gdrivers/vrtfilt.py
- frmts/vrt/vrtfilters.cpp
> [Backport release/3.9] VRT: fix serialization of separatable kernel in VRTKernelFilteredSource

- autotest/ogr/ogr_sqlite.py
- ogr/ogrsf_frmts/sqlite/ogrsqliteutility.cpp
> [Backport release/3.9] SQLite/GPKG: detect UNIQUE constraints expressed as a ', CONSTRAINT name UNIQUE (column_name)' at the end of CREATE TABLE

- apps/gdal_translate_lib.cpp
- autotest/cpp/test_gdal.cpp
- frmts/gtiff/gtiffdataset_write.cpp
- frmts/netcdf/netcdfdataset.cpp
- frmts/zarr/zarr_array.cpp
- gcore/gdal_priv_templates.hpp
- gcore/gdalrasterband.cpp
- ogr/ogr_srs_usgs.cpp
- ogr/ogrfeature.cpp
- ogr/ogrsf_frmts/generic/ogrlayerarrow.cpp
- ogr/ogrsf_frmts/gpkg/ogrgeopackagetablelayer.cpp
- ogr/ogrsf_frmts/openfilegdb/filegdbtable_write.cpp
- ogr/ogrsf_frmts/openfilegdb/ogropenfilegdblayer_write.cpp
including a few recent regressions (as well as longer standing issues related to int64 <--> double casting)
> Various undefined behavior sanitizer fixes

- .pre-commit-config.yaml
- autotest/ogr/ogr_sql_test.py
- doc/source/user/ogr_sql_dialect.rst
- ogr/CMakeLists.txt
- ogr/ogr_swq.h
- ogr/ogrsf_frmts/generic/ogr_gensql.cpp
- ogr/ogrsf_frmts/generic/ogr_gensql.h
- ogr/swq.cpp
- ogr/swq_expr_node.cpp
- ogr/swq_parser.cpp
- ogr/swq_parser.hpp
- ogr/swq_parser.y
- ogr/swq_select.cpp
- scripts/cppcheck.sh
This is a bit inspired by the HIDDEN keyword used by some other SQL implementations, but generally in other contexts, such as hidden columns in SQLite3 virtual tables (https://www.sqlite.org/vtab.html) or MySQL invisible columns (https://dev.mysql.com/doc/refman/8.4/en/invisible-columns.html), although those are in a CREATE TABLE context.
Fixes #10259
@elpaso / @dbaston  opinions?
Other alternatives I considered by decreasing order of appeal:
- having OGRGenSQLResultsLayer consider a field name "OGR_STYLE_HIDDEN" to mean "take that field value to set SetStyleString() but do not expose it"
- having some config option (OGR_STYLE_HIDDEN=YES) read by OGRGenSQLResultsLayer to do the same
- always hide OGR_STYLE (but only when it is used in the form "expression AS OGR_STYLE", not just …
> OGR SQL: add SELECT expression [AS] OGR_STYLE HIDDEN to be able to specify feature style string without generating a visible column

- autotest/ogr/ogr_join_test.py
- autotest/ogr/ogr_pmtiles.py
- ogr/ogrsf_frmts/generic/ogr_gensql.cpp
> [Backport release/3.9] OGR SQL: fix crash when the ON expression of a JOIN contains OGR special fields (in particular feature id)

- apps/gdal_utils_priv.h
- apps/ogr2ogr_bin.cpp
- apps/ogr2ogr_lib.cpp
- autotest/utilities/test_ogr2ogr_lib.py
If specifying -makevalid, MakeValid() will be run on it to make it valid.
For consistency, change behavior of -clipsrc/-clipdst {datasetname} to not automatically make valid invalid clip geometries, but do it only if -makevalid is specified.
Fixes #10289
> ogr2ogr: error out if WKT argument of -clipsrc/-clipdst is an invalid geometry

- doc/source/programs/gdal_merge.rst
I tried to match the `-q` from `gdal_calc`, as I didn't see a common `options/quiet.rst`.
Fixes the missing documentation for an option of `gdal_merge.py`
None
* OS:
* Compiler:
> Doc: gdal_merge.py: Add missing `-q` documentation

- autotest/gdrivers/data/isg/header_dms.isg
- autotest/gdrivers/isg.py
- frmts/aaigrid/aaigriddataset.cpp
Parses ISG files that use "dms" format for "coord units" 
Context:
Trying to read the new geoid model for Japan, that is for now in beta.
https://www.gsi.go.jp/buturisokuchi/grageo_reference.html
https://www.gsi.go.jp/butsuri/data/GSIGEO2024beta.zip
I found it was not parsed by GDAL
It is in ISG 2.0 format
https://www.isgeoid.polimi.it/Geoid/ISG_format_v20_20200625.pdf
using `dms` for "coord units"
> Parse dms in ISG format

- swig/python/gdal-utils/osgeo_utils/gdal2tiles.py
Use OpenStreetMap's preferred tile url per: https://github.com/openstreetmap/operations/issues/737
https://github.com/openstreetmap/operations/issues/737
* OS:
* Compiler:
> Use correct OpenStreetMap tile url in gdal2tiles.py generated HTML

- swig/python/gdal-utils/osgeo_utils/samples/validate_gpkg.py
As found in Spatialite generated DBs, and as accepted by CITE GeoPackage ETS
> validate_gpkg.py: make it robust to CURRENT_TIMESTAMP instead of 'now'

- autotest/gdrivers/xyz.py
- doc/source/drivers/raster/xyz.rst
- frmts/xyz/xyzdataset.cpp
Adds open option `COLUMN_ORDER` to XYZ raster driver
Options available are `AUTO` (default), `XYZ` and `YXZ`. `AUTO` behaves as before.
Many XYZ files using geographic coordinates are in order "lat, long, z", but they do not have a header. (yes, geoid models ;).
Making (and deleting) a temporary file to add a header seems to be a bit strange looking at the ton of options in GDAL.
This PR adds the open option to directly set the format of the data.
If a different behaviour is needed, please let me know. I just use XYZ and YXZ because it is the cases I have met.
> Add open option COLUMN_ORDER to XYZ raster driver

- autotest/gdrivers/mrf.py
- frmts/mrf/marfa.h
- frmts/mrf/marfa_dataset.cpp
- frmts/mrf/mrfdrivercore.cpp
Allow the use of a tar file containing a single MRF directly as an MRF.
It has always been possible to open an MRF (as any other gdal format) inside a tar file by using a vsitar path.
This change allows a tar file that starts with the MRF metadata file to be directly recognized and opened for reading without having to use the vsitar path. This makes an MRF inside a TAR file act as a single file raster format, making it easier to share. All the MRF files have to be inside the tar, with the main metadata (.mrf) being the first.
The identification of such an MRF-in-TAR candidate is done by directly inspecting the tar header and the beginning of the first file inside the tar, without invoking using /vsitar.
This change does not interfere with the use of any other file inside the tar using the …
> MRF: Allow open of MRF-in-TAR as MRF

- swig/python/gdal-utils/osgeo_utils/gdal2tiles.py
Backport #10321
**Authored by:** @Firefishy
> [Backport release/3.9] Use correct OpenStreetMap tile url in gdal2tiles.py generated HTML

- frmts/kea/keaband.cpp
- frmts/kea/keaband.h
- frmts/kea/keadataset.h
KEA was always intended to be a fairly complete implementation of the GDAL data model so all data and metadata should be within the .kea file. However due to my oversight I derived from the PAM base classes. In some situations (like when calculating the histogram) these save also data into a `.aux.xml` file. The data is already in the KEA file so this is unnecessary. This PR changes the base classes so all metadata is saved in the KEA file itself and no `.aux.xml` file is created. 
https://github.com/ubarsc/kealib/pull/64
cc: @neilflood @petebunting
> KEA: don't derive from PAM classes

- port/cpl_http.cpp
> [Backport release/3.9] Fix compilation against openssl-libs-3.2.2-3 of fedora:rawhide

- apps/argparse/argparse.hpp
- apps/gdal_translate_lib.cpp
- apps/gdalbuildvrt_lib.cpp
- apps/gdalwarp_lib.cpp
- autotest/utilities/test_gdal_translate_lib.py
- autotest/utilities/test_gdalbuildvrt_lib.py
- autotest/utilities/test_gdalwarp_lib.py
- doc/source/programs/gdalwarp.rst
Fixes https://lists.osgeo.org/pipermail/gdal-dev/2024-July/059162.html
> Fix issues with gdalbuildvrt and gdalwarp regarding src/dst/vrtnodata arguments and negative values (3.9.0 regression)

- alg/viewshed.cpp
- alg/viewshed.h
- autotest/cpp/test_viewshed.cpp
- autotest/utilities/test_gdal_viewshed.py
- doc/source/programs/gdal_viewshed.rst
Adds support and tests for observers above and below the raster. Adds text to the documentation describing the behavior if an observer is outside of the raster.
> Viewshed: Oor up down

- apps/gdallocationinfo.cpp
- autotest/utilities/test_gdallocationinfo.py
> gdallocationinfo: avoid extra newline character in -valonly mode if coordinate is outside raster extent (3.9.0 regression)

- autotest/ogr/ogr_gml.py
- ogr/ogrsf_frmts/gml/ogr_gml.h
- ogr/ogrsf_frmts/gml/ogrgmldatasource.cpp
- ogr/ogrsf_frmts/gml/ogrgmllayer.cpp
Fixes #10332
Was caused by the fix 3674ec7570f324ea43eef08b6f5ce3a29de2741d for #10071
The regression mostly occurs when writing a GML file using ogr2ogr when the source layer has a named geometry column, e.g if the source is a GeoPackage or if using -sql
The problem was acutally latent and also could have occured before 3.9.1 if using CreateLayer() without a SRS + CreateGeomField()
> GML writer: fix missing SRS in Featurecollection's boundedBy element (3.9.1 regression)

- apps/gdal_rasterize_lib.cpp
- autotest/cpp/test_gdal_gtiff.cpp
- autotest/utilities/test_gdal_rasterize_lib.py
- doc/source/programs/gdal_rasterize.rst
- frmts/gtiff/gtiffrasterband_write.cpp
> gdal_rasterize: fix issue with nodata not taken into account on a GeoTIFF Int64 band 

- autotest/ogr/ogr_sql_test.py
- ogr/ogr_swq.h
- ogr/ogrsf_frmts/generic/ogr_gensql.cpp
- ogr/swq.cpp
> OGR SQL: avoid going through string serialization for MIN(), MAX(), SUM(), AVG() on numeric fields

- apps/ogr2ogr_lib.cpp
- autotest/utilities/test_ogr2ogr_lib.py
- doc/source/programs/ogr2ogr.rst
- swig/include/python/gdal_python.i
-   ogr2ogr: speed-up -clipsrc/-clipdst by avoiding GEOS when possible
If the envelope of the feature's geometry is contained in the envelope
of the -clipsrc/-clipdst geometry, we can just avoid any GEOS operation.
- ogr2ogr: add -skipinvalid to skip features whose geometry is not valid w.r.t Simple Features
> ogr2ogr: speed-up -clipsrc/-clipdst, and add -skipinvalid

- autotest/ogr/ogr_osm.py
- ogr/ogrsf_frmts/osm/data/osmconf.ini
- ogr/ogrsf_frmts/osm/ogr_osm.h
- ogr/ogrsf_frmts/osm/ogrosmdatasource.cpp
Refs https://github.com/geopandas/pyogrio/issues/419#issuecomment-2187640864
> OSM: add a [general] section at top of osmconf.ini to make it INI compliant (and Python's configparser friendly)

- apps/argparse/argparse.hpp
- apps/gdal_translate_lib.cpp
- apps/gdalbuildvrt_lib.cpp
- apps/gdalwarp_lib.cpp
- autotest/utilities/test_gdal_translate_lib.py
- autotest/utilities/test_gdalbuildvrt_lib.py
- autotest/utilities/test_gdalwarp_lib.py
- doc/source/programs/gdalwarp.rst
> [Backport 3.9]  Fix issues with gdalbuildvrt and gdalwarp regarding src/dst/vrtnodata arguments and negative values (3.9.0 regression)

- doc/source/user/configoptions.rst
- port/cpl_http.cpp
Adds `GDAL_HTTP_VERSION=2PRIOR_KNOWLEDGE`, which may allow forcing HTTP/2 on servers which don't advertise support for it.
Closes #10361
> Add support for `GDAL_HTTP_VERSION=2PRIOR_KNOWLEDGE`

- doc/source/development/dev_environment.rst
* Mention that Visual Studio must be installed 
* clcache comes from conda-forge
* Use default python version, otherwise could not find numpy 
* make more explicit that setdevenv.bat must be ran from build directory
> Doc: revise build steps on Windows with conda and Visual Studio

- apps/gdallocationinfo.cpp
- autotest/utilities/test_gdallocationinfo.py
> [Backport release/3.9] gdallocationinfo: avoid extra newline character in -valonly mode if coordinate is outside raster extent (3.9.0 regression)

- autotest/pyscripts/test_gdal2tiles.py
- swig/python/gdal-utils/osgeo_utils/gdal2tiles.py
Co-authored-by: James Scott-Brown / @jamesscottbrown
> gdal2tiles: fix exception with --nodata-values-pct-threshold but not --excluded-values on a multi-band raster

- apps/data/gdalinfo_output.schema.json
Breaking changes in stac-extensions/eo (for v2.0 presumably) have landed today per https://github.com/stac-extensions/eo/commit/81bb3b13dfed92e1a2d8776b2c9fe5f23e28a3ec
> gdalinfo_output.schema.json: pin stac-extensions/eo to v1.1.0

- autotest/pyscripts/test_gdal2tiles.py
- swig/python/gdal-utils/osgeo_utils/gdal2tiles.py
> [Backport release/3.9] gdal2tiles: fix exception with --nodata-values-pct-threshold but not --excluded-values on a multi-band raster

- autotest/ogr/ogr_wkbwkt_geom.py
- ogr/ogrgeometry.cpp
> [Backport release/3.9] WKT geometry importer: accept (non conformant) PointZ/PointZM without space as generated by current QGIS versions

- doc/source/programs/gdaldem.rst
Small doc addition for gdaldem color-relief about presence of an alpha column in the color map, transparancy  is not applied without explicitly specifying '-alpha'.
> gdaldem.rst - mention alpha column, not used without -alpha

- .github/workflows/ubuntu_20.04/Dockerfile.ci
- .github/workflows/ubuntu_22.04/Dockerfile.ci
- .github/workflows/ubuntu_24.04/Dockerfile.ci
- cmake/helpers/CheckDependentLibraries.cmake
Avoids an unintentional dependency on Java AWT caused by the implementation of FindJNI, applying a workaround suggested by https://stackoverflow.com/questions/51047978/cmake-could-not-find-jni
Reduces the size of the modified build environments by ~300MB.
> CMake: Remove unneeded dependency on Java AWT

- swig/python/gdal-utils/osgeo_utils/samples/crs2crs2grid.py
PROJ [documentation](https://proj.org/en/latest/resource_files.html#htdp) suggests using this script to generate a transformation grid file, however the script fails as the current/recent versions of HTDP appear to have changed the output file format from what this script is assuming when parsing.
https://github.com/OSGeo/gdal/issues/2655
* OS: Linux (AmazonLinux 2)
* Python 3.9
> examples/crs2crs2grid.py: Update to work with current data output format from HTDP (fixes #2655)

- .github/workflows/cmake_builds.yml
This reverts commit 81cb7e354d925fabac1aac80f5613566cf96ec65.
Fixes #10165
> Revert "CI: disable running Windows tests on build-windows-conda to workaround issue with image windows-latest 20240603.1.0"

- frmts/ogcapi/gdalogcapidataset.cpp
Avoids error message on
```ogrinfo OGCAPI:https://demo.ldproxy.net/daraa/collections/AeronauticCrv```
> OGCAPI: do not emit 'Server does not support specified IMAGE_FORMAT: AUTO' when opening a vector layer with MVT tiles only

- autotest/pyscripts/test_gdal_retile.py
- doc/source/programs/gdal_retile.rst
- swig/python/gdal-utils/osgeo_utils/gdal_retile.py
Fixes #10333
or with several input files with inconsistent SRS
> gdal_retile: error out with clear message when trying to retile a file with a geotransform with rotation terms

- frmts/ogcapi/gdalogcapidataset.cpp
> [Backport release/3.9] OGCAPI: do not emit 'Server does not support specified IMAGE_FORMAT: AUTO' when opening a vector layer with MVT tiles only

- doc/source/drivers/raster/xyz.rst
Improves XYZ driver doc formatting for new Open Options
In #10339 the Open Options were not clearly marked with bullets. This PR fixes that.
It also adds the `|about-creation-options|` paragraph to be consistent.
> [Doc] better formatting for Open Options in XYZ raster driver

- .github/workflows/cmake_builds.yml
Fixes following error:
```
Traceback (most recent call last):
File "/home/runner/work/gdal/gdal/superbuild/build/gdal/swig/python/setup.py", line 15, in <module>
from setuptools.command.build_ext import build_ext
File "/home/runner/.local/lib/python3.8/site-packages/setuptools/__init__.py", line 19, in <module>
from .dist import Distribution
File "/home/runner/.local/lib/python3.8/site-packages/setuptools/dist.py", line 30, in <module>
from . import _entry_points
File "/home/runner/.local/lib/python3.8/site-packages/setuptools/_entry_points.py", line 44, in <module>
def validate(eps: metadata.EntryPoints):
AttributeError: module 'importlib_metadata' has no attribute 'EntryPoints'
CMake Error at build_ext.cmake:5 (message):
setup.py bdist_wheel failed
```
Likely related to similar …
> CI: fix issue with build-linux-ubuntu-focal and setuptools 71.0.1

- autotest/gcore/vrt_read.py
- doc/source/drivers/raster/vrt.rst
- frmts/vrt/vrtdataset.cpp
- frmts/vrt/vrtdataset.h
- frmts/vrt/vrtderivedrasterband.cpp
- frmts/vrt/vrtdriver.cpp
- frmts/vrt/vrtfilters.cpp
- frmts/vrt/vrtmultidim.cpp
- frmts/vrt/vrtrasterband.cpp
- frmts/vrt/vrtrawrasterband.cpp
- frmts/vrt/vrtsourcedrasterband.cpp
- frmts/vrt/vrtsources.cpp
- gcore/gdal_proxy.h
- gcore/gdalproxypool.cpp
- port/cpl_quad_tree.cpp
- port/cpl_quad_tree.h
- port/cpl_worker_thread_pool.cpp
- port/cpl_worker_thread_pool.h
```rst
Starting with GDAL 3.10, the :oo:`NUM_THREADS` open option can
be set to control specifically the multi-threading of VRT datasets.
It defaults to ``ALL_CPUS``, and when set, overrides :config:`GDAL_NUM_THREADS`
or :config:`VRT_NUM_THREADS`. It applies to
ComputeStatistics() and band-level and dataset-level RasterIO().
For band-level RasterIO(), multi-threading is only available if more than 1
million pixels are requested and if the VRT is made of only non-overlapping
SimpleSource or ComplexSource belonging to different datasets.
For dataset-level RasterIO(), multi-threading is only available if more than 1
million pixels are requested and if the VRT is made of only non-overlapping
SimpleSource belonging to different datasets.
-  .. oo:: NUM_THREADS
:choices: integer, ALL_CPUS …
```
> VRT: add multi-threaded implementation for rasterband and dataset IRasterIO()

- ogr/ogrspatialreference.cpp
- swig/java/apps/OSRTest.java
- swig/java/javadoc.java
- OGRSpatialReference::EPSGTreatsAsLatLong()/EPSGTreatsAsNorthingEasting(): remove the check on the EPSG authority
- Java bindings: document EPSGTreatsAsNorthingEasting() and test it
Fixes #10409
> Java bindings: document EPSGTreatsAsNorthingEasting() and test it

- MIGRATION_GUIDE.TXT
- autotest/gcore/gdal_stats.py
- autotest/gcore/pam.py
- autotest/gcore/vrt_read.py
- autotest/gdrivers/ecw.py
- autotest/gdrivers/ehdr.py
- autotest/gdrivers/netcdf_multidim.py
- autotest/gdrivers/nitf.py
- autotest/gdrivers/vrtprocesseddataset.py
- swig/include/python/typemaps_python.i
- swig/python/gdal-utils/osgeo_utils/samples/gdalinfo.py
- swig/python/modify_cpp_files.cmake
This was the originally intended behavior, but the IF_ERROR_RETURN_NONE typemap that controls this was actually broken.
It used to work before 2006, but it was removed per commit 1c6e19f94f64888eadb02ed05d1465c673bb27b6 and later half restored in 86d4f1d47ae13a91e4950ac83d3ae898d499f291 , missing the important 'ret' typemap that was initially present.
> Python bindings: make GetStatistics() and ComputeStatistics() return None in case of error

- autotest/ogr/ogr_mem.py
- autotest/ogr/ogr_parquet.py
- ogr/ogrsf_frmts/arrow/ogrfeatherlayer.cpp
- ogr/ogrsf_frmts/arrow_common/ograrrowlayer.hpp
- ogr/ogrsf_frmts/arrow_common/ograrrowwriterlayer.hpp
- ogr/ogrsf_frmts/generic/ogrlayerarrow.cpp
- ogr/ogrsf_frmts/parquet/ogrparquetlayer.cpp
Read support was added in 3.9.0 per 21c06b9d486. Now that the arrow.json canonical extension has been made official, also implement it on the write side: i.e. in the CreateField() method of the Arrow/Parquet drivers, and in OGRLayer::GetArrowSchema() when generating a Arrow schema from a OGR layer definition.
> Arrow/Parquet/generic arrow: add write support for arrow.json extension

- doc/source/user/raster_data_model.rst
Adds `Zarr` to the list of drivers supporting subdatsets: https://gdal.org/user/raster_data_model.html#subdatasets-domain 
```
gdalinfo --format zarr | grep "Raster subdatasets"
Supports: Raster subdatasets
```
> doc/raster_data_model: Add Zarr driver to the list of drivers supporting subdatasets

- alg/CMakeLists.txt
- alg/gdal_interpolateatpoint.cpp
- alg/gdal_interpolateatpoint.h
- alg/gdal_rpc.cpp
- apps/gdallocationinfo.cpp
- autotest/gcore/interpolateatpoint.py
- autotest/gcore/transformer.py
- autotest/utilities/test_gdallocationinfo.py
- ci/travis/csa_common/script.sh
- doc/source/programs/gdallocationinfo.rst
- gcore/gdal.h
- gcore/gdal_priv.h
- gcore/gdalrasterband.cpp
- swig/include/Band.i
- swig/include/python/gdal_python.i
Creates the function `GDALInterpolateAtPoint` to interpolate a value in a raster band.
Interpolation methods are (so far) `nearest`, `bilinear` and `cubic`.
It can be used via
- `C` API `GDALRasterInterpolateAtPoint`
- `C++` API `Band::InterpolateAtPoint`  
- `python` via `InterpolateAtPoint` in a raster band
- CLI app `gdallocationinfo` with the new option `-r`
The `C` API is
``` C
CPLErr GDALRasterInterpolateAtPoint(GDALRasterBandH hBand, double dfPixel,
double dfLine,
GDALRIOResampleAlg eInterpolation,
double *pdfRealValue, double *pdfImagValue)
```
For complex layers the implementation is not done yet (to be done in a later PR), but the API is ready. In `C++` `pdfImagValue` is by default a `null_ptr` to simplify the usage.
As sugested by @rouault , the implementation is extracted from …
> Create function GDALInterpolateAtPoint

- gcore/gdaldataset.cpp
- gcore/gdaldriver.cpp
- gcore/gdaldrivermanager.cpp
- gcore/gdaljp2metadata.cpp
- gcore/gdalmultidim.cpp
- port/cpl_port.h
and use it in gcore
@dbaston Thoughts?   I'm quite tired of writing code like ``container.find(key) != containers.end()``. As of C++17, we could use ``container.count(key)``, as the closest alternative to C++20 ``container.contains(key)``, but using count() might complicate future modernization when we bump to C++20.  This ``cpl::contains(container, value)`` should be easily greppable to automate a change to ``container.contains(value)``
> Add a cpl::contains(container, value) helper

- alg/contour.cpp
- apps/gdal_contour.cpp
- autotest/utilities/test_gdal_contour.py
- doc/source/programs/gdal_contour.rst
Fixed levels are added to those automatically calculated from -i or -e.
Fixes #10172
> [gdal_contour] Allow to use -fl with -i and -e

- doc/source/drivers/vector/csv.rst
Clarify OGR_WKT_PRECISION of e.g., 6 will not produce 123.123456, but instead 123.456. in contrast to C, perl, etc.  printf() usage of the word "precision."
Also show that using very low values will result in exponential notation. (Wonder if valid in WKT...)
See also 
- RFC 94: Numeric fields width/precision metadata.
- RFC 99: Geometry coordinate precision 
Indeed besides OGR_WKT_PRECISION there needs to be a new variable, else with  items nearer to the equator of prime meridian, you get a more precise value than near the poles or antimeridian. With loss of one digit occurring at 10 deg (N,S,E,W), and 100 deg(E,W).
I.e., it is a pity that OGR_WKT_PRECISION is this way, because as we see beyond 100 degrees, people lose one digit of precision. I.e., New York will have its longitude in more …
> Update csv.rst clarifying OGR_WKT_PRECISION

- HOWTO-RELEASE
- NEWS-1.x.md
- NEWS-2.x.md
- NEWS.md
- scripts/typos_allowlist.txt
(didn't do 3.3.x and older, as they are not markdown formatted)
CC @jjimenezshaw @hobu
The file still renders in github UI: https://github.com/rouault/gdal/blob/NEWS_split/NEWS.md
> Forward port GDAL bugfixes releases NEWS additions from 3.4.x to 3.9.x to NEWS.md, and split GDAL 2.x and 1.x news into their own files

- alg/gdal_interpolateatpoint.cpp
- alg/gdal_rpc.cpp
- alg/gdalresamplingkernels.h
- alg/gdalwarpkernel.cpp
- apps/gdallocationinfo.cpp
- autotest/alg/warp.py
- autotest/gcore/interpolateatpoint.py
- autotest/gcore/transformer.py
- autotest/utilities/test_gdallocationinfo.py
- doc/source/programs/gdallocationinfo.rst
- gcore/gdalrasterband.cpp
- swig/include/python/gdal_python.i
Makes `GDALRasterInterpolateAtPoint` continuous near the borders of the image.
It also adds `cubic` interpolation.
(why adding cubic here? Unlike cubicspline, cubic matches the values of the grid in the nodes. That makes testing during development easier. See that in the images at x=0.5 and y=0.5, that are cutting at the nodes of the grid).
See that cubic may get values bigger than the maximum of the grid values.
How is it getting data near the borders, if there are no point to interpolate with? It "extends" the image with the pixel value at the border.
For instance, this is how the top left corner is "extended" to have a 4x4 kernel:
```
.___      a a a b
|a b  =>  a a a b
|c i      a a a b
c c c i
```
Fixes #10501
> InterpolateAtPoint near borders

- autotest/gcore/tiff_write.py
- autotest/requirements.txt
Pytest: Add missing requirements for test cases with minimum driver support.
When build on Win10 / VS2022 / cmake with minumum driver support and minimum Python package requirements some pytests fail.
`cmake -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Release   -DGDAL_BUILD_OPTIONAL_DRIVERS=OFF -DOGR_BUILD_OPTIONAL_DRIVERS=OFF   -DGDAL_USE_EXTERNAL_LIBS:BOOL=OFF ..\`
- For test_tiff_write_101() the required driver is ENVI, which is not available when built with minimum driver support.
- Some pytest cases require package "psutil" to import (e.g.: netcdf.py, gpkg.py, conftest.py, vrtwarp.py)
This PR adds the missing requirements.
> Pytest: Add missing requirements for test cases with minimum driver support

- ogr/ogrsf_frmts/miramon/ogrmiramonlayer.cpp
Solves the problem reported in issue 70860 by oss-fuzz where the minus sign hadn't been taken into account in a particular case when translating numerical fields.
> MiraMonVector: fix Issue 70860 in oss-fuzz

- doc/source/user/virtual_file_systems.rst
Had some issues with a nested zip and fixed it after finding the curly brace logic.
Noticed broken formatting in the docs and the fix in https://github.com/OSGeo/gdal/pull/3270 which was easy to apply.
This commit also tries to make this syntax a bit more discoverable with an extra example :)  
Sorry for mixing it in but it was a quick edit using the GitHub web editor.
- Formatting fix from https://github.com/OSGeo/gdal/pull/3270 for the other occurrences of the curly brace syntax
- Additional vsizip example showing how to access a file in a nested zip, using the curly brace syntax
> Doc: Fix curly braces in VFS, nested zip example with braces

- autotest/ogr/ogr_jsonfg.py
- ogr/ogrsf_frmts/jsonfg/ogrjsonfgdataset.cpp
> JSONFG: fix reading non-FeatureCollection documents larger than 6,000 bytes

- autotest/ogr/ogr_arrow.py
- autotest/ogr/ogr_parquet.py
- doc/source/drivers/vector/arrow.rst
- ogr/ogrsf_frmts/arrow/CMakeLists.txt
- ogr/ogrsf_frmts/arrow/ogrfeatherdriver.cpp
- ogr/ogrsf_frmts/arrow/ogrfeatherdrivercore.cpp
- ogr/ogrsf_frmts/arrow/vsifilesystemregistrar.cpp
- ogr/ogrsf_frmts/arrow_common/vsiarrowfilesystem.hpp
- ogr/ogrsf_frmts/parquet/ogrparquetdriver.cpp
- scripts/cppcheck.sh
Starting with GDAL 3.10 and Arrow 16.0, any GDAL Virtual File System can be used (in a read-only context) wherever the Arrow C++ library expects a URI, in particular outside of the context of the OGR Arrow driver, by:
- loading the libgdal.so/dll library (or the ogr_Arrow.so/dll plugin library if the Arrow driver is built as a library) with the arrow::fs::LoadFileSystemFactories() function (cf `Defining new filesystems <https://arrow.apache.org/docs/cpp/io.html#defining-new-filesystems>`__) Note: if the Arrow driver is fully loaded, e.g. by querying GetGDALDriverManager()->GetDriverByName("ARROW")->GetMetadata(), the Arrow VSI file system will be also registered.
- Prefixing any GDAL file name with the ``vsi://`` URI scheme prefix. In addition to any potential vsi prefix in the GDAL file …
> Add a Arrow VSI file system

- autotest/ogr/ogr_hana.py
- ogr/ogrsf_frmts/hana/ogr_hana.h
- ogr/ogrsf_frmts/hana/ogrhanadatasource.cpp
- ogr/ogrsf_frmts/hana/ogrhanalayer.cpp
- ogr/ogrsf_frmts/hana/ogrhanaresultlayer.cpp
- ogr/ogrsf_frmts/hana/ogrhanatablelayer.cpp
- ogr/ogrsf_frmts/hana/ogrhanautils.cpp
- ogr/ogrsf_frmts/hana/ogrhanautils.h
With QRC/1 2024 a new and faster way to estimate extents of spatial column has been added to HANA.
More precisely, users can now use special columns in [this table](https://help.sap.com/docs/hana-cloud-database/sap-hana-cloud-sap-hana-database-spatial-reference/spatial-extent-with-sys-m-st-geometry-columns?locale=en-US) to get an estimation of the extent of a spatial column.
Even though the stored extent is only an estimation, it is often good enough.
Especially for very large tables costly aggregation functions are avoided every time the extent is recomputed.
The extent information in the mentioned HANA table is only available after a delta-merge, so a fallback to the standard behaviour, i.e. via aggregation functions, was added in case the data is unavailable or has not yet been …
> HANA: Add support for fast extent estimation

- autotest/ogr/ogr_jsonfg.py
- ogr/ogrsf_frmts/jsonfg/ogrjsonfgdataset.cpp
> [Backport release/3.9] JSONFG: fix reading non-FeatureCollection documents larger than 6,000 bytes
