- autotest/gdrivers/gpkg.py
- Perform setup/teardown in fixture
- Use pytest.mark.require_driver
- Use pytest.mark.parametrize
> autotest gdrivers/gpkg.py: Update code conventions

- autotest/ogr/ogr_mssqlspatial.py
Add test for issue #1990
Also add more cases to the existing test  binary field BCP.
> MSSQL: add test for geometry column identification

- autotest/ogr/ogr_gpkg.py
- doc/source/drivers/vector/gpkg.rst
- ogr/ogrsf_frmts/gpkg/ogr_geopackage.h
- ogr/ogrsf_frmts/gpkg/ogrgeopackagedatasource.cpp
- ogr/ogrsf_frmts/gpkg/ogrgeopackagedriver.cpp
- ogr/ogrsf_frmts/gpkg/ogrgeopackagetablelayer.cpp
- swig/python/gdal-utils/osgeo_utils/samples/validate_gpkg.py
- replace _update3 RTree trigger with _update5
- replace _update1 RTree trigger with _update6 and _update7
- update validate_gpkg.py
> GPKG: implement GeoPackage 1.4 RTree triggers, and add a VERSION=1.4 dsco (fixes #7823)

- autotest/ogr/ogr_mvt.py
- ogr/ogrsf_frmts/mvt/ogrmvtdataset.cpp
When MakeValid() is available, do not remove right away inner rings that have become invalid after quantization to integer coordinates, but rather pass the whole quantized polygon to MakeValid() so it makes its best repairing it.
> MVT generation: improve dealing with polygon inner rings (fixes #7890)

- apps/gdal_rasterize_lib.cpp
> [Backport release/3.7] gdal_rasterize: fix logic error of fix of #7663 (CID 1512568)

- autotest/ogr/ogr_mvt.py
- ogr/ogrsf_frmts/mvt/ogrmvtdataset.cpp
> [Backport release/3.7] MVT generation: improve dealing with polygon inner rings (fixes #7890)

- autotest/ogr/ogr_gtfs.py
- ogr/ogrsf_frmts/gtfs/ogrgtfsdriver.cpp
Backport #7950
**Authored by:** @krate2000
> [Backport release/3.7] GTFS: Fix date parsing

- doc/source/user/configoptions.rst
- Remove GDAL_PAM_MODE which appears to be effectively unused
- Describe GDAL_PAM_PROXY_DIR
#7964
> Doc: Update PAM config options

- frmts/ogcapi/gdalogcapidataset.cpp
> [Backport release/3.7] OGCAPI: Fix TILES raster API not working

- frmts/safe/safedataset.cpp
- frmts/safe/safedataset.h
> [Backport release/3.7] SAFE: fix non-contiguous number in subdataset names (fixes #7939)

- autotest/gcore/vsis3.py
> [Backport release/3.7] vsis3.py: fix to make tests pass when port = 8081 (fixes #7952)

- frmts/ogcapi/CMakeLists.txt
- frmts/ogcapi/gdalogcapidataset.cpp
- gdal.cmake
> [Backport release/3.7] OGCAPI: make sure OGR_ENABLE_DRIVER_GML is set when the driver is built

- autotest/ogr/ogr_gpkg.py
- ogr/ogrsf_frmts/gpkg/ogr_geopackage.h
- ogr/ogrsf_frmts/gpkg/ogrgeopackagedatasource.cpp
- ogr/ogrsf_frmts/gpkg/ogrgeopackagedriver.cpp
- ogr/ogrsf_frmts/gpkg/ogrgeopackagetablelayer.cpp
- swig/python/gdal-utils/osgeo_utils/samples/validate_gpkg.py
- replace _update3 RTree trigger with _update5
- replace _update1 RTree trigger with _update6 and _update7
- update validate_gpkg.py
> [Backport 3.7] GPKG: implement GeoPackage 1.4 RTree triggers, and add a VERSION=1.4 dsco (fixes #7823)

- ogr/ogrsf_frmts/shape/dump_symbols.sh
- ogr/ogrsf_frmts/shape/gdal_shapelib_symbol_rename.h
- ogr/ogrsf_frmts/shape/shp_vsi.h
> [Backport release/3.7] Internal Shapelib: update list of symbols to rename to avoid conflicts with external shapelib (fixes microsoft/vcpkg#32070)

- doc/source/drivers/raster/heif.rst
Fixing minor typo in HEIF driver documentation
> Update heif.rst to fix minor typo

- autotest/ogr/ogr_fielddomain.py
- ogr/ogrsf_frmts/sqlite/ogrsqlitevirtualogr.cpp
Fixes https://lists.osgeo.org/pipermail/gdal-dev/2023-June/057394.html
> SQL SQLite: fix error on field of type String with GetWidth() > 0 and a field domain

- autotest/ogr/ogr_fielddomain.py
- ogr/ogrsf_frmts/sqlite/ogrsqlitevirtualogr.cpp
> [Backport release/3.7] SQL SQLite: fix error on field of type String with GetWidth() > 0 and a field domain

- autotest/gcore/rasterio.py
- autotest/osr/osr_basic.py
- doc/source/drivers/raster/gtiff.rst
- doc/source/drivers/raster/hfa.rst
- doc/source/drivers/raster/jp2kak.rst
- doc/source/drivers/raster/jp2openjpeg.rst
- doc/source/drivers/raster/vrt.rst
- doc/source/drivers/vector/sqlite.rst
- doc/source/user/configoptions.rst
- ogr/ogrspatialreference.cpp
Adds assorted config options to the docs. Also adds tests for some options that were not previously tested, but appear to be intended for public use.
> Doc: Add configuration option entries/tests

- .github/workflows/cmake_builds.yml
- autotest/cpp/test_osr_set_proj_search_paths.cpp
- ci/travis/osx/before_install.sh
> [Backport release/3.7] CI: workaround jsonschema 4.18 installation issue

- frmts/ogcapi/gdalogcapidataset.cpp
> OGCAPI: make it work when the media type of links is missing

- port/cpl_vsil_curl.cpp
- port/cpl_vsil_curl_class.h
@lnicola Can you give this a try ?
> /vsicurl/: avoid the same region to be downloaded at the same time from concurrent threads (fixes #8041)

- autotest/ogr/ogr_wfs.py
- ogr/ogrsf_frmts/wfs/ogrwfslayer.cpp
> autotest: ogr_wfs.py: make it work with pytest --random-order

- autotest/gdrivers/data/ogcapi/request_collections_NOT_EXISTS.http_data
- autotest/gdrivers/ogcapi.py
Add a few more tests to the OGCAPI regression test suite.
> OCAPI: more tests

- cmake/modules/Ccache.cmake
> [Backport release/3.7] Ccache.cmake: fix warning

- swig/include/java/typemaps_java.i
- swig/include/ogr.i
- swig/java/CMakeLists.txt
- swig/java/apps/test_ogrfielddomains.java
- swig/java/javadoc.java
> Java bindings: implement ogr.CreateCodedFieldDomain() and FieldDomain GetEnumeration() 

- apps/ogr2ogr_lib.cpp
- autotest/utilities/test_ogr2ogr_lib.py
- swig/include/python/gdal_python.i
> [Backport release/3.7] ogr2ogr: support -nlt GEOMETRY -nlt CONVERT_TO_LINEAR (fixes #8101)

- frmts/webp/webpdataset.cpp
> [Backport release/3.7] WEBP: fix build against libwebp < 0.4.0 (fixes #8111)

- apps/gdalinfo_lib.cpp
- autotest/utilities/test_gdalinfo_lib.py
- frmts/stacit/stacitdataset.cpp
> Fixes related to proj:epsg STAC projection extension

- apps/gdalinfo_lib.cpp
- autotest/utilities/test_gdalinfo_lib.py
- frmts/stacit/stacitdataset.cpp
> [Backport release/3.7] Fixes related to proj:epsg STAC projection extension

- ogr/ogrsf_frmts/hana/ogrhanadatasource.cpp
> [Backport release/3.7] HANA: bug fixes

- swig/java/apps/GDALTestMultiDim.java
It looks like I had left in a very small plane size that I had used for debugging.
> Make the java 2d multidim api test code exercise itself harder

- cmake/modules/packages/FindSPATIALITE.cmake
Backport #8173
**Authored by:** @jef-n
> [Backport release/3.7] Update FindSPATIALITE.cmake for SpatiaLite 5.1.0

- frmts/stacit/stacitdataset.cpp
Backport #8168
**Authored by:** @mdsumner
> [Backport release/3.7] STACIT: apply vsis3 protocol to  s3:// items

- doc/source/user/configoptions.rst
Documents `GDAL_OVR_PROPAGATE_NODATA`. I don't see this used in the wild at all (https://github.com/search?q=GDAL_OVR_PROPAGATE_NODATA+-path%3Atiff_ovr.py+-path%3Aoverview.cpp&type=code
) though it is tested and seems useful?
> Doc: Document GDAL_OVR_PROPAGATE_NODATA

- autotest/ogr/ogr_shape.py
- ogr/ogrsf_frmts/shape/ogrshape.h
- ogr/ogrsf_frmts/shape/ogrshapedatasource.cpp
- ogr/ogrsf_frmts/shape/ogrshapelayer.cpp
> [Backport release/3.7] Shapefile driver: make CreateLayer() + GetFileList() list the .prj file when it exists (fixes #8167)

- CITATION.cff
@dbaston @craigds @miurahr You deserve to be in the CITATION.cff file. Let me know if you're OK with this. Please feel free to add your orcid ID and set/change your affiliation if needed
> CITATION.cff: update with contributors

- apps/ogrinfo_bin.cpp
- apps/ogrinfo_lib.cpp
- autotest/utilities/test_ogrinfo.py
> [Backport release/3.7] ogrinfo: return non-zero ret code if -sql failed (fixes #8215)

- autotest/cpp/test_cpl.cpp
> [Backport release/3.7] Adjust test for libjson-c 0.17

- autotest/conftest.py
- autotest/gcore/basic_test.py
> autotest: make tmp_vsimem fixture create the directory (similarly to pytest's tmp_path)

- apps/gdal_translate_bin.cpp
- apps/gdal_translate_lib.cpp
- autotest/utilities/test_gdal_translate.py
- doc/source/programs/gdal_translate.rst
> add flag to gdal_translate to assign geotransform (#8248)

- autotest/gdrivers/zarr_driver.py
- doc/source/drivers/raster/zarr.rst
- frmts/zarr/zarrdriver.cpp
- gcore/gdal_priv.h
- gcore/gdalmultidim.cpp
>  Zarr: add MULTIBAND=YES/NO, DIM_X and DIM_Y open options (fixes #8237) 

- doc/source/drivers/vector/gmlas.rst
Trivial typo fix.
N/A
* OS:
* Compiler:
> docs: Update gmlas.rst

- autotest/gdrivers/gpkg.py
- ogr/ogrsf_frmts/gpkg/gdalgeopackagerasterband.cpp
- ogr/ogrsf_frmts/gpkg/ogrgeopackagedriver.cpp
Backport fixes commits from https://github.com/OSGeo/gdal/pull/8326
> [Backport 3.7] GPKG fixes

- autotest/gcore/pixfun.py
- doc/source/drivers/raster/vrt.rst
- frmts/vrt/pixelfunctions.cpp
- frmts/vrt/vrtderivedrasterband.cpp
> VRT: add 'min' and 'max' pixel functions

- autotest/ogr/ogr_gml_geom.py
- ogr/gml2ogrgeometry.cpp
- ogr/ogr_geometry.h
- ogr/ogrcompoundcurve.cpp
- ogr/ogrcurvepolygon.cpp
- ogr/ogrgeometrycollection.cpp
- ogr/ogrpolyhedralsurface.cpp
and use them in gml2ogrgeometry.cpp
> OGRGeometry classes: add addGeometry()/addRing()/addCurve() methods accepting a std::unique_ptr

- cmake/helpers/CheckDependentLibraries.cmake
Backport #8336
**Authored by:** @autoantwort
> [Backport release/3.7] Don't use jpeg if disabled

- swig/python/gdal-utils/osgeo_utils/gdal2tiles.py
> [Backport release/3.7] gdal2tiles: raise explicit exception if bad value for --s_srs (fixes #8331)

- autotest/ogr/ogr_parquet.py
- ogr/ogrsf_frmts/arrow_common/ograrrowlayer.hpp
found when investigating #8347
> Arrow/Parquet: fix crash on ArrowArray interface when there is a fid column

- autotest/ogr/ogr_gpkg.py
- autotest/ogr/ogr_parquet.py
- autotest/ogr/ogr_tiledb.py
- frmts/tiledb/tiledbsparse.cpp
- ogr/ogr_wkb.cpp
- ogr/ogr_wkb.h
- ogr/ogrsf_frmts/flatgeobuf/ogrflatgeobuflayer.cpp
- ogr/ogrsf_frmts/generic/ogrlayer.cpp
- ogr/ogrsf_frmts/generic/ogrlayerarrow.cpp
- ogr/ogrsf_frmts/gpkg/ogr_geopackage.h
- ogr/ogrsf_frmts/gpkg/ogrgeopackagelayer.cpp
- ogr/ogrsf_frmts/gpkg/ogrgeopackagetablelayer.cpp
- ogr/ogrsf_frmts/ogrsf_frmts.h
> GPKG/Arrow/Parquet/TileDB/FlatGeobuf GetNextArrowArray(): implement full spatial filtering (not just bbox intersection)

- doc/source/user/raster_data_model.rst
Remove i.e. vs. e.g. confusion.
> Update raster_data_model.rst to remove i.e. vs. e.g. confusion

- frmts/gif/giflib/dgif_lib.c
- scripts/clang-format.sh
> [Backport release/3.7] Gif memory leak fixes

- doc/source/drivers/raster/netcdf.rst
- frmts/netcdf/netcdfdataset.cpp
> netCDF: better doc and error message when reading from /vsi is not possible 

- autotest/ogr/data/parquet/schema.json
- autotest/ogr/ogr_parquet.py
- autotest/pyscripts/test_validate_geoparquet.py
- ogr/ogrsf_frmts/parquet/ogrparquetlayer.cpp
- ogr/ogrsf_frmts/parquet/ogrparquetwriterlayer.cpp
cf https://github.com/opengeospatial/geoparquet/releases/tag/v1.0.0
> Parquet: emit GeoParquet 1.0.0 version number now it has been released

- autotest/gdrivers/netcdf_multidim.py
- frmts/netcdf/netcdfmultidim.cpp
> [Backport release/3.7] netCDF multidim: add write support for Int8 data type (fixes #8421)

- apps/ogr2ogr_lib.cpp
- autotest/utilities/test_ogr2ogr_lib.py
> [Backport release/3.7] ogr2ogr: fix -gt 0 to disable transactions

- doc/source/api/python_gotchas.rst
- Note that exceptions will be the default in GDAL 4.0
- Update discussion of relationships to note exceptions vs crashes
- Update discussion of Destroy to describe context managers and Close
> Doc: Update Python gotchas

- port/cpl_vsil_s3.cpp
> IVSIS3LikeFSHandler::CopyFile(): retry with non-streaming source for more robustness

- apps/ogr2ogr_lib.cpp
- autotest/utilities/test_ogr2ogr_lib.py
> [Backport release/3.7] ogr2ogr: make -select '' work (or gdal.VectorTranslate(selectFields=[]))

- cmake/modules/3.20/FindPostgreSQL.cmake
Backport #8505
**Authored by:** @pramsey
> [Backport release/3.7] Update the list of released PgSQL versions to the present

- doc/source/user/virtual_file_systems.rst
- port/cpl_vsil_curl.cpp
> Doc and code enhancements about CPL_VSIL_CURL_CHUNK_SIZE / CPL_VSIL_CURL_CHUNK_SIZE

- alg/gdalwarpkernel_opencl.cpp
> OPENCL: scan multiple devices for each platform

- alg/gdalwarpkernel_opencl.cpp
> [Backport release/3.7] OPENCL: scan multiple devices for each platform

- doc/source/user/virtual_file_systems.rst
- port/cpl_vsil_libarchive.cpp
Backport #8545
**Authored by:** @arredond
> [Backport release/3.7] VSI7Z: Accept ArcGIS Pro Project Packages

- alg/gdaltransformer.cpp
- ogr/ogrct.cpp
> [Backport release/3.7] Reprojection fixes

- autotest/ogr/ogr_sql_rfc28.py
- ogr/ogrsf_frmts/generic/ogr_gensql.cpp
- ogr/ogrsf_frmts/generic/ogr_gensql.h
> [Backport release/3.7] OGRSQL: fix incorrect interaction of LIMIT clause and SetNextByIndex() (fixes #8585)

- autotest/ogr/ogr_wfs.py
- ogr/ogrsf_frmts/wfs/ogr_wfs.h
- ogr/ogrsf_frmts/wfs/ogrwfslayer.cpp
> WFS: correctly paginate when number of features is lower than page size

- autotest/ogr/ogr_openfilegdb_write.py
- doc/source/drivers/vector/openfilegdb.rst
- ogr/ogrsf_frmts/openfilegdb/ogropenfilegdblayer.cpp
> OpenFileGDB: expose layer alias name in ALIAS_NAME layer metadata item

- doc/source/drivers/vector/parquet.rst
- Now points users to the Apache Parquet project instead of Databricks
None
> Update parquet.rst to point to Apache Parquet project

- autotest/gcore/vrt_read.py
- frmts/vrt/vrtsourcedrasterband.cpp
> [Backport release/3.8] VRTSourcedRasterBand: serialize approximate statistics inside .vrt when there are overviews

- autotest/ogr/ogr_gpkg.py
- ogr/ogrsf_frmts/gpkg/ogrgeopackagetablelayer.cpp
> [Backport release/3.8] GPKG: fix SetFeature()/UpdateFeature()/DeleteFeature() on views with INSTEAD OF triggers (fixes #8707)

- autotest/ogr/ogr_gpkg.py
- ogr/ogrsf_frmts/gpkg/ogrgeopackagetablelayer.cpp
> [Backport release/3.8] [gpkg] Fix adding field comments after alternative name

- doc/source/user/configoptions.rst
Remove stray double quote in configoptions.rst
> configoptions.rst - remove stray quote

- autotest/ogr/ogr_sql_test.py
- doc/source/user/ogr_sql_dialect.rst
- ogr/CMakeLists.txt
- ogr/ogr_swq.h
- ogr/ogrsf_frmts/generic/ogr_gensql.cpp
- ogr/ogrsf_frmts/ngw/gdalngwdataset.cpp
- ogr/ogrsf_frmts/openfilegdb/ogropenfilegdbdatasource.cpp
- ogr/ogrsf_frmts/parquet/ogrparquetdataset.cpp
- ogr/ogrsf_frmts/wfs/ogrwfsjoinlayer.cpp
- ogr/swq.cpp
- ogr/swq_parser.cpp
- ogr/swq_parser.hpp
- ogr/swq_parser.y
- ogr/swq_select.cpp
Add `SELECT * EXCLUDE (...)` as described in #8668.
Still need to address some memory leaks. 
#8668
> OGRSQL: Add SELECT * EXCLUDE (...)

- ogr/ogrsf_frmts/shape/dbfopen.c
- ogr/ogrsf_frmts/shape/sbnsearch.c
- ogr/ogrsf_frmts/shape/shapefil.h
- ogr/ogrsf_frmts/shape/shp_vsi.c
- ogr/ogrsf_frmts/shape/shpopen.c
- ogr/ogrsf_frmts/shape/shptree.c
With this PR, shapelib (https://github.com/OSGeo/shapelib/pull/70) and GDAL will be sync'ed again
> Shapelib: resync with upstream

- alg/gdal_tps.cpp
- alg/gdalgenericinverse.cpp
- alg/gdalgenericinverse.h
- apps/gdalwarp_lib.cpp
- autotest/gcore/transformer.py
On https://github.com/OSGeo/gdal/issues/8672 use case, timings are:
- 3.7.3: ~ 25 minutes
- 3.8.0: ~ 1400 minutes
- this PR: ~ 140 minutes
> Inverse TPS transformer: speed improvement in gdalwarp use case (fixes #8672)

- autotest/gcore/multidim.py
- gcore/CMakeLists.txt
- gcore/gdal.h
- gcore/gdal_priv.h
- gcore/gdal_rat.cpp
- gcore/gdalmultidim.cpp
- gcore/gdalmultidim_priv.h
- gcore/gdalmultidim_rat.cpp
- swig/include/MultiDimensional.i
- swig/include/RasterAttributeTable.i
- swig/include/python/typemaps_python.i
to return a virtual Raster Attribute Table from several GDALMDArray's
> Add GDALCreateRasterAttributeTableFromMDArrays()

- alg/gdal_tps.cpp
- alg/gdalgenericinverse.cpp
- alg/gdalgenericinverse.h
- apps/gdalwarp_lib.cpp
- autotest/gcore/transformer.py
> [Backport release/3.8] Inverse TPS transformer: speed improvement in gdalwarp use case (fixes #8672)

- .github/workflows/cmake_builds.yml
- swig/python/setup.py.in
> [Backport release/3.8] Python bindings: define entry_points.console_scripts

- autotest/ogr/ogr_gpkg.py
- ogr/ogrsf_frmts/gpkg/ogr_geopackage.h
- ogr/ogrsf_frmts/gpkg/ogrgeopackagetablelayer.cpp
> [Backport release/3.8] GPKG: fix GetNextArrowArray() when there are more than 125 columns (affects ogr2ogr from such GPKG) (fixes #8757)

- apps/ogr2ogr_lib.cpp
- autotest/ogr/ogr_shape.py
- autotest/utilities/test_ogr2ogr_lib.py
- ogr/ogrsf_frmts/generic/ogrlayerarrow.cpp
> [Backport release/3.8] ogr2ogr: fix GPKG to shapefile with the -preserve_fid flag (fixes #8761)

- doc/source/development/rfc/index.rst
- doc/source/development/rfc/rfc97_feature_and_fielddefn_sealing.rst
Partially rendered view [here](https://github.com/rouault/gdal/blob/rfc97_text/doc/source/development/rfc/rfc97_feature_and_fielddefn_sealing.rst)
> RFC 97 text: OGRFeatureDefn, OGRFieldDefn and OGRGeomFieldDefn "sealing"

- autotest/gcore/cog.py
- doc/source/drivers/raster/cog.rst
- frmts/gtiff/cogdriver.cpp
Slightly related to https://github.com/OSGeo/gdal/issues/8834
> COG: for JPEG compression, convert single band+alpha as single band JPEG + 1-bit mask band

- doc/source/drivers/vector/csv.rst
I am just wildly guessing what the missing verb is.
> Try to make overly long sentence grammatical.

- autotest/ogr/ogr_geojson.py
- doc/source/drivers/vector/geojson.rst
- ogr/ogrsf_frmts/geojson/ogr_geojson.h
- ogr/ogrsf_frmts/geojson/ogrgeojsondatasource.cpp
- ogr/ogrsf_frmts/geojson/ogrgeojsondriver.cpp
- ogr/ogrsf_frmts/geojson/ogrgeojsonwritelayer.cpp
Cf https://gis.stackexchange.com/questions/470551/writing-foreign-members-to-geojson-files-using-ogr2ogr
> GeoJSON writer: add FOREIGN_MEMBERS_FEATURE and FOREIGN_MEMBERS_COLLECTION layer creation option

- apps/gdal_footprint_lib.cpp
- autotest/cpp/CMakeLists.txt
- autotest/cpp/test_utilities.cpp
- autotest/utilities/test_gdal_footprint.py
- autotest/utilities/test_gdal_footprint_lib.py
- swig/include/python/gdal_python.i
> [Backport release/3.8] Improve gdal_footprint testing, and small fix & enhancement

- autotest/gcore/hdf4_read.py
- autotest/gdrivers/hdf5.py
- autotest/gdrivers/netcdf.py
- frmts/hdf4/hdf4drivercore.cpp
- frmts/hdf5/hdf5drivercore.cpp
- frmts/netcdf/netcdfdrivercore.cpp
> SubdatasetInfo API: fix protocol and bogus

- autotest/gcore/hdf4_read.py
- autotest/gdrivers/hdf5.py
- autotest/gdrivers/netcdf.py
- frmts/hdf4/hdf4dataset.cpp
- frmts/hdf5/hdf5dataset.cpp
- frmts/netcdf/netcdfdataset.cpp
backport of https://github.com/OSGeo/gdal/pull/8881
> [Backport 3.8] SubdatasetInfo API: fix protocol and bogus

- ogr/ogrspatialreference.cpp
> [Backport release/3.8] OGRSpatialReference::importFromUrl(): changes to no longer use a 'Accept: application/x-ogcwkt' header

- frmts/hdf5/gh5_convenience.cpp
- frmts/hdf5/hdf5multidim.cpp
> [Backport release/3.8] HDF5 related nodata tunings

- doc/source/user/configoptions.rst
> configoptions.rst: a few typos

- ogr/ogr_proj_p.cpp
Cf https://lists.osgeo.org/pipermail/gdal-dev/2023-December/058058.html
> OSRPJContextHolder: call pthread_atfork() once for the process

- apps/gdal_utils_priv.h
- apps/ogr2ogr_bin.cpp
- apps/ogr2ogr_lib.cpp
- apps/ogrinfo_bin.cpp
- autotest/utilities/test_ogr2ogr.py
- autotest/utilities/test_ogrinfo.py
- doc/source/programs/ogr2ogr.rst
- doc/source/programs/ogrinfo.rst
- doc/source/programs/options/formats_raster.rst
- doc/source/programs/options/formats_vector.rst
- doc/source/programs/options/if.rst
> Fix ogrinfo -if; implements it in ogr2ogr; doc clarification

- autotest/cpp/test_gdal.cpp
- frmts/raw/envidataset.cpp
- gcore/gdal_priv.h
- gcore/gdaldataset.cpp
- gcore/gdalpamdataset.cpp
- gcore/gdalrasterband.cpp
- ogr/ogrsf_frmts/dxf/ogrdxfwriterds.cpp
GDALDataset::UnMarkSuppressOnClose()
GDALDataset::IsMarkSuppressOnClose()
related to #8980
> added additional functions to change the bSuppressOnClose flag

- .github/workflows/slow_tests.yml
- .github/workflows/slow_tests/build.sh
- .github/workflows/slow_tests/test.sh
- autotest/CMakeLists.txt
- autotest/run_slow_tests.sh
- autotest/slow_tests/raster.py
For now, only a test case representative of the one of #8967
This CI job is only run once per day
> Add autotest/slow_tests and a CI job to run them

- doc/source/user/virtual_file_systems.rst
- port/cpl_aws.cpp
Credits to @pedros007 for diagnosing the issue and finding the workarounds
> Add specific documentation section about AWS IMDS (and fix typo)

- doc/source/user/virtual_file_systems.rst
- port/cpl_aws.cpp
> [Backport release/3.8] Add specific documentation section about AWS IMDS (and fix typo)

- apps/gdal2ogr.c
Backport #9023
**Authored by:** @mpdaly
> [Backport release/3.8] gdal2ogr.c: added missing close bracket

- apps/commonutils.cpp
- gcore/gdal.h
- gcore/gdaldriver.cpp
should help implementing https://github.com/georust/gdal/pull/510
> Add GDALGetOutputDriversForDatasetName()

- .github/workflows/android_cmake.yml
- .github/workflows/backport.yml
- .github/workflows/cifuzz.yml
- .github/workflows/clang_static_analyzer.yml
- .github/workflows/cmake_builds.yml
- .github/workflows/code_checks.yml
- .github/workflows/codeql.yml
- .github/workflows/conda.yml
- .github/workflows/coverity_scan.yml
- .github/workflows/delete_untagged_containers.yml
- .github/workflows/doc_build.yml
- .github/workflows/linux_build.yml
- .github/workflows/macos.yml
- .github/workflows/slow_tests.yml
- .github/workflows/windows_build.yml
as suggested by https://github.com/ossf/scorecard/blob/main/docs/checks.md#pinned-dependencies
Dependabot is able to automatically update them
> CI: pin actions by sha

- alg/gdaltransformer.cpp
- alg/gdalwarper.h
- alg/gdalwarpkernel.cpp
- alg/gdalwarpoperation.cpp
- autotest/utilities/test_gdalwarp_lib.py
> Warping: fix issues in long/lat <--> orthographic reprojection

- ogr/ogrsf_frmts/mssqlspatial/ogr_mssqlspatial.h
- ogr/ogrsf_frmts/mssqlspatial/ogrmssqlspatialdatasource.cpp
Backport #9113
**Authored by:** @szekerest
> [Backport release/3.8] MSSQLSpatial Fix BCP performance problem (#9112)

- ogr/ogrsf_frmts/arrow_common/ograrrowlayer.hpp
> [Backport release/3.8] Arrow/Parquet: add (minimum) support for libarrow 15.0

- gcore/rasterio.cpp
Fixes https://github.com/OSGeo/gdal/pull/9040#issuecomment-1898524693
> GDALBandGetBestOverviewLevel2(): avoid numerical instability with GDAL_OVERVIEW_OVERSAMPLING_THRESHOLD = 1.0

- frmts/mrf/marfa_dataset.cpp
Adds a warning if internal overview cleaning is requested, which is not allowed in MRF
#9145
* OS:
* Compiler:
> Emit warning when attempting to clean internal overviews

- ogr/ogrsf_frmts/sqlite/ogrsqliteexecutesql.cpp
> [Backport release/3.8] ExecuteSQL(dialect=SQLite): support 'SELECT\n' for example (fixes #9093)

- frmts/exr/exrdataset.cpp
- frmts/plmosaic/plmosaicdataset.cpp
- frmts/wmts/wmtsdataset.cpp
- ogr/ogrsf_frmts/gpkg/ogrgeopackagedatasource.cpp
Backport #9161
**Authored by:** @PatrikSylve
> [Backport release/3.8] PAM only unset GPF_DIRTY flag

- apps/ogr2ogr_lib.cpp
> [Backport release/3.8] ogr2ogr: Arrow code path: take into account -limit parameter for MAX_FEATURES_IN_BATCH

- frmts/pds/pds4dataset.h
- frmts/pds/pds4vector.cpp
> [Backport release/3.8] PDS: fix compilation with Emscripten version 3.1.7

- docker/ubuntu-full/Dockerfile
Backport #9186
**Authored by:** @PerMildner
> [Backport release/3.8] docker/ubuntu-full/Dockerfile: pin libarrow-acero-dev version (fixes #9183)

- apps/gdalbuildvrt_lib.cpp
Trivial fix of include what you use in one file.
https://clang.llvm.org/extra/clang-tidy/checks/misc/include-cleaner.html
Hit while merging #5137 into another code base.
Also sort the includes since I'm already editing that block.
Should be no functional change.
None.
- [ -] ADD YOUR TASKS HERE
- [ -] Make sure code is correctly formatted (cf [pre-commit configuration](https://gdal.org/development/dev_practices.html#commit-hooks))
- [ -] Add test case(s)
- [ -] Add documentation
- [ -] Updated Python API documentation (swig/include/python/docs/)
* OS:
* Compiler:
> gdalbuildvrt_lib.cpp: IWYU - add C++ string include

- autotest/cpp/test_cpl.cpp
- port/cpl_strtod.cpp
Fixes https://lists.osgeo.org/pipermail/gdal-dev/2024-January/058312.html
> CPLAtof()/CPLStrtod(): recognize again INF and -INF

- frmts/vrt/vrtpansharpened.cpp
- gcore/gdaloverviewdataset.cpp
> [Backport release/3.8] GDALOverviewDataset and VRTPansharpenedRasterBand related fixes

- doc/source/drivers/raster/ceos.rst
- doc/source/drivers/raster/sar_ceos.rst
Fixes incorrect references links in the "SAR_CEOS -- CEOS SAR Image" and "CEOS -- CEOS Image" drivers documentation pages.
* OS:
* Compiler:
> Docs: fix refs in "SAR_CEOS -- CEOS SAR Image" and "CEOS -- CEOS Image" drivers

- gcore/gdal_misc.cpp
Related to https://lists.osgeo.org/pipermail/gdal-dev/2024-January/058312.html
> GDALDeserializeGCPListFromXML(): validate value of GCP Pixel,Line,X,Y,Z attributes

- frmts/zarr/zarr.h
- frmts/zarr/zarr_sharedresource.cpp
- frmts/zarr/zarr_v2_array.cpp
- frmts/zarr/zarr_v2_group.cpp
- frmts/zarr/zarr_v3_array.cpp
- frmts/zarr/zarr_v3_group.cpp
(fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=66497, master only)
> Zarr: avoid potential infinite recursive calls at opening

- frmts/gtiff/gtiffdataset_write.cpp
complementary to https://github.com/OSGeo/gdal/pull/9220
> GTiff: friendlier error message when attempting to create JXL compressed file with unsupported type/bits_per_sample

- autotest/gdrivers/jp2openjpeg.py
- frmts/opjlike/jp2opjlikedataset.cpp
> JP2OpenJPEG: CreateCopy(): limit number of resolutions taking into account minimum block width/height 

- autotest/ogr/ogr_gpkg.py
- doc/source/drivers/vector/gpkg.rst
- ogr/ogrsf_frmts/gpkg/ogrgeopackagedatasource.cpp
Fixes auto-created relationship mapping tables cannot be read from gpkg
> [gpkg] Ensure that mapping tables are inserted into gpkg_contents

- .github/workflows/cmake_builds.yml
Working:
- https://github.com/OSGeo/gdal/actions/runs/7987290493/job/21809463985?pr=9270 uses: image windows-2022 20240211.1.0, cmake 3.27.9, MSVC 19.37.32826.1
KO:
- https://github.com/OSGeo/gdal/actions/runs/7987537106/job/21814263291?pr=9271 uses: image windows-2022 20240218.2.0, cmake 3.28.3, MSVC 19.38.33135.0
> CI: try to fix issue with Windows Conda builds

- .github/workflows/cmake_builds.yml
Working:
- https://github.com/OSGeo/gdal/actions/runs/7987290493/job/21809463985?pr=9270 uses: image windows-2022 20240211.1.0, cmake 3.27.9, MSVC 19.37.32826.1
KO:
- https://github.com/OSGeo/gdal/actions/runs/7987537106/job/21814263291?pr=9271 uses: image windows-2022 20240218.2.0, cmake 3.28.3, MSVC 19.38.33135.0
> [Backport 3.8] CI: try to fix issue with Windows Conda builds

- autotest/ogr/ogr_gpkg.py
- doc/source/drivers/vector/gpkg.rst
- ogr/ogrsf_frmts/gpkg/ogrgeopackagedatasource.cpp
> [Backport release/3.8] [gpkg] Ensure that mapping tables are inserted into gpkg_contents

- autotest/ogr/ogr_gpkg.py
- ogr/ogrsf_frmts/gpkg/ogrgeopackagedatasource.cpp
Tables which are listed in gpkgext_relations but NOT gpkg_contents should be readable as valid layers. The GeoPackage related tables extension explicitly states that tables in gpkgext_relations are not required to be listed in gpkg_contents.
> [gpkg] Ensure that tables present in gpkgext_relations can be read

- autotest/ogr/ogr_gpkg.py
- ogr/ogrsf_frmts/gpkg/ogrgeopackagedatasource.cpp
> [Backport release/3.8] [gpkg] Ensure that tables present in gpkgext_relations can be read

- doc/source/programs/gdal_grid.rst
> Update gdal_grid.rst to discuss creating multiband files

- doc/source/index.rst
> Update index.rst noting offline individual HTML pages .ZIP

- doc/source/index.rst
https://github.com/OSGeo/gdal/pull/9294#issuecomment-1962284238
> Update index.rst to say the ZIP includes the PDF

- ogr/ogrsf_frmts/sqlite/CMakeLists.txt
Backport #9311
**Authored by:** @dg0yt
> [Backport release/3.8] Disable my_test_sqlite3_ext in static builds

- apps/gdalwarp_lib.cpp
- autotest/utilities/test_gdalwarp_lib.py
> [Backport release/3.8] gdalwarp: cutline zero-width sliver enhancement: avoid producing invalid polygons

- ogr/ogrsf_frmts/flatgeobuf/CMakeLists.txt
- ogr/ogrsf_frmts/flatgeobuf/ogrflatgeobufdataset.cpp
- scripts/cppcheck.sh
> [Backport release/3.8] Make sure our vendored flatbuffers copy has a unique namespace

- doc/source/programs/gdal_grid.rst
https://github.com/orgs/sphinx-doc/discussions/12005#discussioncomment-8584525 mentions how to add the paragraph between two includes!
> Update gdal_grid.rst to warn of errors due to not setting type

- doc/source/drivers/raster/vrt.rst
I'll put this warning in several places!
> Update vrt.rst to make it super clear there are two .vrts

- doc/source/programs/gdal_grid.rst
Else they go right off many people's screens!
> Update gdal_grid.rst to fix long lines

- ogr/ogrgeometrycollection.cpp
> OGR: fix read corrupted wkb with mixed 2D and 3D geoms

- alg/gdalpansharpen.cpp
Backport #9361
**Authored by:** @tbonfort
> [Backport release/3.8] fix error messages on pansharpening consistency checks

- autotest/gdrivers/vrtpansharpen.py
- data/gdalvrt.xsd
- doc/source/drivers/raster/vrt.rst
- frmts/vrt/vrtpansharpened.cpp
> [Backport 3.8] VRTPansharpenedDataset: allow to specify <OpenOptions> for <PanchroBand> and <SpectralBand>

- autotest/gdrivers/dimap.py
- frmts/dimap/dimapdataset.cpp
Backport #9366
**Authored by:** @tbonfort
> [Backport release/3.8] DIMAP: add radiometric metadata

- doc/source/tutorials/gdal_grid_tut.rst
Else they won't get the whole picture!
> Update gdal_grid_tut.rst reminding users where to see the actual current list

- doc/source/programs/gdaltransform.rst
(From https://www.jidanni.org/geo/openstreetmap/utah2024.html )
> Update gdaltransform.rst adding GCP example

- doc/source/programs/gdal_grid.rst
(P.S., wish someone would add an example of the first (gdalbuildvrt -separate and then gdal_translate) method too. I only figured out how to use the second.)
> Update gdal_grid.rst adding gdal_merge.py example

- doc/source/programs/gdalwarp.rst
(Or one could simply delete this URL if the contents are too old.)
> Update gdalwarp.rst to expose URL so it is accessible on a Unix man page

- doc/source/programs/gdal_grid.rst
For https://github.com/OSGeo/gdal/pull/9413#issuecomment-1983052830
> Update gdal_grid.rst adding example detaails

- swig/include/cpl.i
- swig/include/java/typemaps_java.i
- swig/include/osr.i
> SWIG: fix memory leak in SpatialReference.ExportToCF1

- autotest/ogr/ogr_geos.py
- autotest/utilities/test_ogr2ogr_lib.py
- ogr/ogrgeometry.cpp
- swig/include/ogr.i
And SWIG: expose Geometry.UnaryUnion()
> OGRGeometry::exportToGEOS(): retain Z values for POLYHEDRALSURFACE Z / TIN Z / GEOMETRYCOLLECTION Z of surfaces (master only)

- doc/source/programs/ogr2ogr.rst
> Update ogr2ogr.rst noting possibility of loss of geometry

- autotest/utilities/test_gdalinfo.py
- autotest/utilities/test_ogr2ogr.py
- autotest/utilities/test_ogrinfo.py
- doc/source/user/configoptions.rst
- gcore/gdal_misc.cpp
> Add support for --config <key>=<value> syntax

- doc/source/api/python/osgeo.ogr.rst
- swig/include/python/docs/ogr_feature_docs.i
- swig/include/python/ogr_python.i
- Alphabetize
- Remove C signatures and parameters
- Add missing docstrings
- Remove docstrings for methods not exposed in Python
- Add cross-references and some examples
> Doc: Update Python API docs for ogr.Feature

- apps/ogr2ogr_lib.cpp
- apps/ogrtindex.cpp
- frmts/wmts/wmtsdataset.cpp
- ogr/ogrsf_frmts/gmlas/ogrgmlaswriter.cpp
- ogr/ogrsf_frmts/libkml/ogrlibkmldatasource.cpp
- ogr/ogrsf_frmts/mssqlspatial/ogrmssqlspatialtablelayer.cpp
- port/cpl_odbc.cpp
- port/cpl_odbc.h
Mostly false positive, except commit "MSSQLSpatial: fix potential SQL injection of value of MSSQLSPATIAL_OGR_FID config option (https://github.com/OSGeo/gdal/security/code-scanning/525)"
> Several CodeQL fixes

- autotest/gcore/vsis3.py
- port/cpl_aws.cpp
@philvarner Can you give this a try?
> /vsis3/: include region to build s3.{region}.amazonaws.com host name (fixes #9449)

- ogr/ogrsf_frmts/sosi/ogrsosilayer.cpp
(https://github.com/OSGeo/gdal/security/code-scanning/547)
> SOSI: fix false-positive CodeQL warning about potential use-after-free

- autotest/gcore/transformer.py
- autotest/gdrivers/eedai.py
- autotest/gdrivers/vrtpansharpen.py
- autotest/pyscripts/test_gdal_pansharpen.py
- frmts/grib/gribdataset.cpp
- gcore/overview.cpp
- ogr/ogrsf_frmts/gpkg/gdalgeopackagerasterband.cpp
> [Backport release/3.8] Add compatibility for Intel Compiler 2024.0.2.29

- doc/source/drivers/vector/gpx.rst
[skip ci]
From https://github.blog/changelog/2021-02-08-github-actions-skip-pull-request-and-push-workflows-with-skip-ci/
alas, seemed not to work, as you see below:
> Update gpx.rst probably making it clearer

- autotest/ogr/ogr_libkml.py
- ogr/ogrsf_frmts/libkml/ogrlibkmllayer.cpp
> LIBKML: improve generation of internal ids for layer names starting with digits

- frmts/gtiff/libtiff/tif_dir.c
- frmts/gtiff/libtiff/tif_open.c
- frmts/gtiff/libtiff/tiffiop.h
Integrate https://gitlab.com/libtiff/libtiff/-/merge_requests/571
> Internal libtiff: Correct and harmonize swapping of internal 'tif_header' parameters

- cmake/helpers/configure.cmake
Backport #9557
**Authored by:** @vmirgorod
> [Backport release/3.8] Added modern Apple OS support

- autotest/pyscripts/test_gdalattachpct.py
- swig/python/gdal-utils/osgeo_utils/gdalattachpct.py
> gdalattachpct.py: fix it when output file is a VRT (fixes #9513)

- autotest/gcore/vsiaz.py
- port/cpl_azure.cpp
> /vsiaz/: handle properly BlobEndpoint ending with a slash (fixes #9519)

- apps/ogr2ogr_lib.cpp
- autotest/utilities/test_ogr2ogr_lib.py
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=67646
> ogr2ogr: fix nullptr dereference in wrong -clipsrc/-clipdst usage (master only, fixes ossfuzz#67646)

- port/cpl_http.cpp
This fixes the same issue as
https://github.com/OSGeo/PROJ/pull/4106 fixes
in PROJ.
* OS:
* Compiler:
> cpl_http: retry "Connection reset by peer"

- autotest/pyscripts/test_gdalbuildvrtofvrt.py
- swig/python/gdal-utils/osgeo_utils/samples/gdalbuildvrtofvrt.py
- skip source rasters that can't be opened, and add a --stop-on-error flag
- add --intermediate-vrt-add-overviews, --intermediate-vrt-overview-factors, --overview-compression
> gdalbuildvrtofvrt.py enhancements

- autotest/ogr/ogr_geom.py
- autotest/ogr/ogr_gpkg.py
- autotest/ogr/ogr_sqlite.py
- doc/source/drivers/vector/gpkg.rst
- ogr/ogr_api.cpp
- ogr/ogr_api.h
- ogr/ogr_geometry.h
- ogr/ogrcircularstring.cpp
- ogr/ogrcompoundcurve.cpp
- ogr/ogrcurve.cpp
- ogr/ogrcurvepolygon.cpp
- ogr/ogrgeometrycollection.cpp
- ogr/ogrlinestring.cpp
- ogr/ogrpolyhedralsurface.cpp
- ogr/ogrsf_frmts/gpkg/ogrgeopackagedatasource.cpp
- ogr/ogrsf_frmts/sqlite/ogrsqlitedatasource.cpp
- ogr/ogrsf_frmts/sqlite/ogrsqlitesqlfunctions.cpp
- ogr/ogrsurface.cpp
- swig/include/ogr.i
- swig/include/python/docs/ogr_geometry_docs.i
- Add OGR_G_GeodesicArea() / OGRSurface::get_GeodesicArea()
- SQLite SQL dialect: implement ST_Area(geom, use_ellipsoid)
- GPKG: implement ST_Area(geom, use_ellipsoid)
> Add OGR_G_GeodesicArea() and ST_Area(geom, use_ellipsoid)

- doc/source/substitutions.rst
- doc/source/user/configoptions.rst
- doc/source/user/vector_data_model.rst
Add discussion of newer geometry types, feature styling, field types and subtypes, field domains, and relationships.
> Doc: Update vector data model description

- autotest/gcore/numpy_rw.py
- swig/include/python/gdal_python.i
Modeled after the method of the same name on `MDArray`.
I'm wondering if `NODATA` values should also be masked.
> Python: Add Band.ReadAsMaskedArray

- ogr/ogrsf_frmts/arrow_common/ogr_arrow.h
- ogr/ogrsf_frmts/arrow_common/ograrrowlayer.hpp
- ogr/ogrsf_frmts/parquet/ogr_parquet.h
- ogr/ogrsf_frmts/parquet/ogrparquetlayer.cpp
Bugfixes extracted from https://github.com/OSGeo/gdal/pull/9586
> [Backport 3.8] Geoparquet related fixes

- autotest/ogr/data/gmlas/citygml_empty_lod1.gml
- autotest/ogr/ogr_gmlas.py
- ogr/ogrsf_frmts/gmlas/ogrgmlaslayer.cpp
Fixes https://github.com/r-spatial/sf/issues/2371
> GMLAS: fix crash when reading CityGML files (fixes r-spatial/sf#2371)

- doc/source/programs/gdalinfo.rst
For https://github.com/OSGeo/gdal/issues/9541 .
> Update gdalinfo.rst to say how to get DD format

- autotest/pyscripts/test_gdal2tiles.py
- autotest/pyscripts/test_gdal2xyz.py
- autotest/pyscripts/test_gdal_calc.py
- autotest/pyscripts/test_gdal_edit.py
- autotest/pyscripts/test_gdal_fillnodata.py
- autotest/pyscripts/test_gdal_polygonize.py
- autotest/pyscripts/test_gdal_proximity.py
- autotest/pyscripts/test_gdal_sieve.py
- autotest/pyscripts/test_gdal_utils.py
- autotest/pyscripts/test_gdallocationinfo_py.py
- autotest/pyscripts/test_gdalmove.py
- autotest/pyscripts/test_ogr_layer_algebra.py
- autotest/pyscripts/test_ogrmerge.py
- autotest/pyscripts/test_validate_geoparquet.py
Uses tmp_path fixture to prevent clobbering, enabling these tests to run in parallel.
Apparently I did this last August but somehow forgot to make a PR.
> autotest: update pyscripts tests to run in parallel

- doc/source/programs/ogrinfo.rst
> Update ogrinfo.rst fixing forgotten backslash

- doc/source/user/virtual_file_systems.rst
Yes, mentioned below, but not here!
> Update virtual_file_systems.rst  to mention STDIN and STDOUT

- doc/source/user/virtual_file_systems.rst
> Update virtual_file_systems.rst adding clarity

- doc/source/drivers/raster/pds4.rst
This is only a small add to the documentation, this PR correct an example in it.
The suggested option `-co VAR_Target=Moon` in pds4.rst results in an error producing a PDS4 raster examples.
```
Warning 1: ${TARGET} could not be substituted
```
Inspecting the resulting xml files I found :
```xml
<Target_Identification>
<name>${TARGET}</name>
<type>Satellite</type>
[...]
</Target_Identification>
```
where the option `-co VAR_TARGET_TYPE="Satellite"` were correctly interpolated.
I just changed the offending option to `-co VAR_TARGET_NAME=Moon` and it works.
By chance, I discovered that the variables names are case insensitive.
NONE
**Not Appilcable**
* OS:
* Compiler:
Thanks for this great tool!
> Update pds4.rst : Raster option VAR_Target is wrong, use VAR_TARGET_TYPE

- .github/workflows/cmake_builds.yml
- HOWTO-RELEASE
- autotest/cpp/test_cpl.cpp
- frmts/zlib/adler32.c
- frmts/zlib/compress.c
- frmts/zlib/crc32.c
- frmts/zlib/deflate.c
- frmts/zlib/infback.c
- frmts/zlib/inffast.c
- frmts/zlib/inflate.c
- frmts/zlib/inftrees.c
- frmts/zlib/trees.c
- frmts/zlib/uncompr.c
- frmts/zlib/zutil.c
- ogr/ogrsf_frmts/pmtiles/ogr_pmtiles.h
- ogr/ogrsf_frmts/pmtiles/ogrpmtilesdataset.cpp
- ogr/ogrsf_frmts/pmtiles/ogrpmtilestileiterator.cpp
- port/cpl_compressor.cpp
- port/cpl_conv.h
- port/cpl_vsil_gzip.cpp
> PMTiles: handle decompressing data with a compression ratio > 16

- doc/source/drivers/vector/vrt.rst
> Doc: OGR VRT: clarify GeometryField attributes

- port/cpl_http.cpp
- port/cpl_vsil.cpp
- port/cpl_vsil_curl.cpp
- port/cpl_vsil_curl_class.h
- port/cpl_vsil_s3.cpp
- port/cpl_vsil_swift.cpp
- port/cpl_vsil_webhdfs.cpp
> Add a VSICURLMultiCleanup() that runs with SIGPIPE ignored

- autotest/pyscripts/test_gdal2tiles.py
- doc/source/programs/gdal2tiles.rst
- swig/python/gdal-utils/osgeo_utils/gdal2tiles.py
> gdal2tiles: added support for JPEG output

- ogr/data/pci_datum.txt
- ogr/data/pci_ellips.txt
> Update pci_datum.txt and pci_ellips.txt

- autotest/conftest.py
- autotest/gcore/hfa_write.py
- autotest/gcore/tiff_read.py
- autotest/gcore/vsiadls.py
- autotest/gcore/vsiaz.py
- autotest/gcore/vsis3.py
- autotest/ogr/ogr_db2_hack.py
- autotest/ogr/ogr_dxf.py
- autotest/ogr/ogr_fgdb.py
- autotest/ogr/ogr_geoconcept.py
- autotest/ogr/ogr_geojson.py
- autotest/ogr/ogr_georss.py
- autotest/ogr/ogr_gpkg.py
- autotest/ogr/ogr_gpx.py
- autotest/ogr/ogr_hana.py
- autotest/ogr/ogr_index_test.py
- autotest/ogr/ogr_openfilegdb.py
- autotest/ogr/ogr_openfilegdb_write.py
- autotest/ogr/ogr_pds4.py
- autotest/ogr/ogr_pgdump.py
- autotest/ogr/ogr_sql_test.py
- autotest/pymod/gdaltest.py
- autotest/utilities/test_gdaltindex.py
- autotest/utilities/test_gnmutils.py
- cmake/template/pytest.ini.in
Makes various fixes to prevent unrelated tests from interfering with each other.
> autotest: Prevent unrelated tests from interfering with each other

- ogr/ogrsf_frmts/miramon/ogrmiramon.h
- ogr/ogrsf_frmts/miramon/ogrmiramondatasource.cpp
- ogr/ogrsf_frmts/miramon/ogrmiramondriver.cpp
> Miramon: more C++ification and simplification of OGRMiraMonDataSource

- autotest/gdrivers/netcdf.py
- frmts/netcdf/netcdfdataset.cpp
> netCDF: fix writing of metadata items whose value has an equal sign

- apps/gdalwarp_lib.cpp
- autotest/utilities/test_gdalwarp_lib.py
- doc/source/programs/gdalwarp.rst
- swig/include/python/gdal_python.i
> gdalwarp: allow passing a WKT geometry as -cutline value, and add -cutline_srs

- alg/contour.cpp
- autotest/alg/contour.py
> gdal_contour: fix lowest min value in polygonize mode

- ogr/ogrpgeogeometry.cpp
- ogr/ogrpgeogeometry.h
- ogr/ogrsf_frmts/openfilegdb/filegdbtable_write.cpp
- ogr/ogrsf_frmts/shape/shape2ogr.cpp
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=67831
> OpenFileGDB: writer: fix memleak in multipatch writing when there's an error

- NEWS.md
(up to commit 5eeba207b21130efad3d2f9acb56963e4b19fd21)
> NEWS.md: update for 3.9.0beta1

- alg/gdaltransformer.cpp
Fixes failure on rasterio tests/test_warpedvrt.py::test_transformer_options__width_height
> GDALSuggestedWarpOutput2(): make changes of PR #9336 honour SRC_METHOD=NO_GEOTRANSFORM

- alg/gdaltransformer.cpp
> [Backport release/3.9] GDALSuggestedWarpOutput2(): make changes of PR #9336 honour SRC_METHOD=NO_GEOTRANSFORM

- fuzzers/build.sh
Latest Poppler master has raised its minimum version of its dependencies to those of Ubuntu 22.04 but ossfuzz images still use 20.04 as their base
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=68263
> ossfuzz build.sh: update for latest poppler [ci skip]

- apps/argparse/README.TXT
- apps/argparse/argparse.hpp
- apps/ogr2ogr_lib.cpp
- apps/ogrinfo_lib.cpp
> [Backport release/3.9] ogrinfo and ogr2ogr: update to use store_into(GIntBig&)

- doc/source/programs/ogr2ogr.rst
Backport #9755
**Authored by:** @jidanni
> [Backport release/3.9] Update ogr2ogr.rst to stay on screen in Linux man page

- doc/source/api/index.rst
Added a link to Ruby language GDAL bindings to docs.
https://github.com/telus-agcg/ffi-gdal
- active project, supports Ruby 2.6-3.3 and GDAL 2.4, GDAL 3+;
- maintained and supported by a couple of big agriculture companies;
- originated in 2015;
- provides both low-level FFI and high-level idiomatic Ruby wrapper.
> docs: added a link to Ruby language GDAL bindings

- .github/workflows/stale.yml
Cf https://lists.osgeo.org/pipermail/gdal-dev/2024-April/058850.html for rationale
> CI: add a stale target for pull requests without recent activity

- docker/README.md
- docker/ubuntu-full/Dockerfile
- docker/ubuntu-full/bh-gdal.sh
- docker/ubuntu-full/bh-proj.sh
- docker/ubuntu-full/bh-set-envvars.sh
- docker/ubuntu-small/Dockerfile
- docker/ubuntu-small/bh-set-envvars.sh
> [Backport release/3.9] Docker: update to Ubuntu 24.04

- autotest/gdrivers/tiledb_multidim.py
- autotest/ogr/ogr_tiledb.py
- cmake/helpers/CheckDependentLibraries.cmake
- doc/source/development/building_from_source.rst
- frmts/tiledb/CMakeLists.txt
- frmts/tiledb/include_tiledb.h
- frmts/tiledb/tiledbcommon.cpp
- frmts/tiledb/tiledbdense.cpp
- frmts/tiledb/tiledbdrivercore.cpp
- frmts/tiledb/tiledbheaders.h
- frmts/tiledb/tiledbmultidim.cpp
- frmts/tiledb/tiledbmultidim.h
- frmts/tiledb/tiledbmultidimarray.cpp
- frmts/tiledb/tiledbmultidimattribute.cpp
- frmts/tiledb/tiledbmultidimattributeholder.cpp
- frmts/tiledb/tiledbmultidimgroup.cpp
- frmts/tiledb/tiledbsparse.cpp
Backport #9725
**Authored by:** @teo-tsirpanis
> [Backport release/3.9] TileDB: migrate away from deprecated APIs

- apps/gdalinfo_lib.cpp
- apps/ogrinfo_lib.cpp
Refs https://github.com/qgis/QGIS/issues/57266
> gdalinfo and ogrinfo -json: add newline character at end of JSON output

- ci/travis/osx/before_install.sh
- ci/travis/osx/script.sh
> CI: re-enable MacOS Python tests

- autotest/pyscripts/gdal2tiles/test_option_parser.py
- autotest/pyscripts/test_gdal2tiles.py
- swig/python/gdal-utils/osgeo_utils/gdal2tiles.py
> gdal2tiles: support an input dataset name not being a file

- ci/travis/osx/before_install.sh
- ci/travis/osx/script.sh
> [Backport release/3.9] CI: re-enable MacOS Python tests

- alg/los.cpp
- autotest/cpp/test_alg.cpp
Backport #9785
**Authored by:** @Ryanf55
> [Backport release/3.9] LOS: Implement simple violation location reporting

- autotest/ogr/ogr_miramon_vector.py
- ogr/ogrsf_frmts/miramon/mm_gdal_driver_structs.h
- ogr/ogrsf_frmts/miramon/mm_gdal_functions.c
- ogr/ogrsf_frmts/miramon/mm_gdal_functions.h
- ogr/ogrsf_frmts/miramon/mm_wrlayr.c
- ogr/ogrsf_frmts/miramon/ogrmiramonlayer.cpp
> [Backport release/3.9] MiraMon: Lost changes + update DBF date

- autotest/gdrivers/tiledb_multidim.py
- frmts/tiledb/tiledbmultidim.h
- frmts/tiledb/tiledbmultidimgroup.cpp
> [Backport release/3.9] TileDB multidimensional fixes

- .github/workflows/code_checks.yml
- doc/Makefile
- doc/source/development/dev_documentation.rst
> doc/Makefile: add a 'doxygen_check_warnings' target to ease local checks

- ogr/ogrsf_frmts/miramon/mm_wrlayr.c
> [Backport release/3.9] MiraMonVector: Little fixes in metadata files

- apps/gdalargumentparser.h
- apps/ogrtindex.cpp
```
Usage: ogrtindex [--help] [--long-usage] [--help-general]
[-lnum <n>]... [-lname <name>]... [-of <output_format>] [-tileindex <tileindex>] [-write_absolute_path]
[-skip_different_projection] [-t_srs <target_srs>] [-src_srs_name <field_name>]
[-src_srs_format {AUTO|WKT|EPSG|PROJ}] [-accept_different_schemas]
<output_dataset> <src_dataset>...
Program to generate a UMN MapServer compatible tile index for a set of OGR data sources.
<output_dataset>                      Name of the output dataset. 
<src_dataset>                         Name of the source dataset(s). [nargs: 1 or more] 
-h, --help                            Shows short help message and exits. 
--long-usage                          Shows long help message and exits. 
--help-general …
```
> [ogrtindex] Use GDALArgumentParser

- ogr/ogrsf_frmts/miramon/mm_rdlayr.c
> [Backport release/3.9] MiraMonVector: Fix issue 68585 from chromium (and other similar ones)

- autotest/gcore/vsiaz.py
- autotest/gcore/vsigs.py
- port/cpl_azure.cpp
- port/cpl_azure.h
- port/cpl_google_cloud.cpp
- port/cpl_google_cloud.h
- port/cpl_vsil_adls.cpp
- port/cpl_vsil_az.cpp
- port/cpl_vsil_curl_class.h
- port/cpl_vsil_gs.cpp
- port/cpl_vsil_s3.cpp
> [Backport release/3.9] /vsigs/ and /vsiaz/: fixes related to RmdirRecursive() / UnlinkBatch()

- doc/source/programs/gdaltransform.rst
> Update gdaltransform.rst -gcp example

- swig/csharp/CMakeLists.txt
- swig/java/CMakeLists.txt
> Java and CSharp bindings: do not build sample/tests programs if BUILD_TESTING=OFF

- .github/workflows/alpine/build.sh
- apps/sozip.cpp
- frmts/grib/gribdataset.cpp
- frmts/netcdf/netcdfvirtual.h
- frmts/pdf/pdfsdk_headers.h
- frmts/vrt/gdaltileindexdataset.cpp
- frmts/wcs/wcsdataset110.cpp
- frmts/zarr/zarr_array.cpp
- ogr/ogrsf_frmts/elastic/ogrelasticlayer.cpp
- ogr/ogrsf_frmts/gmlas/ogrgmlasutils.cpp
- ogr/ogrsf_frmts/libkml/ogrlibkmlfield.cpp
- ogr/swq_op_general.cpp
- port/cpl_recode.cpp
- third_party/LercLib/BitStuffer2.cpp
> [Backport release/3.9] Fix various C++20 compilation related issues

- cmake/helpers/configure.cmake
- frmts/gtiff/libgeotiff/geotiff_proj4.c
- frmts/gtiff/libtiff/tif_hash_set.c
- frmts/northwood/northwood.cpp
- frmts/stacit/stacitdataset.cpp
- ogr/ogrsf_frmts/shape/dbfopen.c
- ogr/ogrsf_frmts/shape/sbnsearch.c
- ogr/ogrsf_frmts/shape/shpopen.c
- ogr/ogrsf_frmts/shape/shptree.c
> [Backport release/3.9] configure.cmake: fix build with mingw64 with gcc 14

- ogr/ogrsf_frmts/miramon/data/MM_m_idofic.csv
> [Backport release/3.9] MiraMonVector: Adding more matchs in the look-up table MM_m_idofic.csv

- apps/gdal_utils_priv.h
- apps/gdalmdimtranslate_bin.cpp
- apps/gdalmdimtranslate_lib.cpp
```
Usage: gdalmdimtranslate [--help] [--long-usage] [--help-general]
[-if <format>]... [-of <output_format>] [-co <NAME>=<VALUE>]...
[[-array <array_spec]...]
[-arrayoption <NAME>=<VALUE>]...
[[-group <group_spec>]...]
[-subset <subset_spec>]... [-scaleaxes <scaleaxes_spec>] [-strict] [-oo <NAME>=<VALUE>]...
[--quiet]
<src_dataset> <dst_dataset>
Converts multidimensional data between different formats, and performs subsetting.
<src_dataset>                The source dataset name. 
<dst_dataset>                The destination file name. 
-h, --help                   Shows short help message and exits. 
--long-usage                 Shows long help message and exits. 
--help-general               Report detailed help on general options. 
-if …
```
> [gdalmdimtranslate] Use GDALArgumentParser

- doc/source/programs/gdalmdimtranslate.rst
> Doc: gdalmdimtranslate: document -strict

- doc/source/drivers/raster/gtiff.rst
- doc/source/drivers/raster/jp2ecw.rst
- doc/source/drivers/raster/jp2kak.rst
- doc/source/drivers/raster/jp2lura.rst
- doc/source/drivers/raster/jp2mrsid.rst
- doc/source/drivers/raster/jp2openjpeg.rst
Minor editorial updates to openjpeg doc. No code changes. 
None.
Not applicable.
> doc: Update jp2openjpeg.rst

- ogr/ogrsf_frmts/miramon/mm_gdal_functions.c
- ogr/ogrsf_frmts/miramon/mm_gdal_functions.h
- ogr/ogrsf_frmts/miramon/mm_wrlayr.c
> [Backport release/3.9] MiraMonVector: Fixing chromium bug 68809

- ogr/ogrsf_frmts/miramon/mm_wrlayr.c
> [Backport release/3.9] MiraMonVector: Fixing chromium bug 68809 correctly

- doc/source/drivers/vector/pmtiles.rst
Added examples on translation from shape and postgres to pmtiles
> Docs: update pmtiles.rst with examples

- autotest/ogr/data/geojson/featuretype.json
- autotest/ogr/data/jsonfg/crs_none_fc_mixed_feat_no_conformsTo.json
- autotest/ogr/ogr_geojson.py
- autotest/ogr/ogr_jsonfg.py
- gcore/gdaldriver.cpp
- ogr/ogrsf_frmts/geojson/ogrgeojsondatasource.cpp
- ogr/ogrsf_frmts/geojson/ogrgeojsonutils.cpp
- ogr/ogrsf_frmts/geojson/ogrgeojsonutils.h
- port/cpl_json_streaming_parser.cpp
- port/cpl_json_streaming_parser.h
Backport of https://github.com/OSGeo/gdal/pull/9950
> [Backport 3.9] GeoJSON/JSONFG: do not recognize GeoJSON files with a featureType feature property as JSONFG

- doc/source/programs/ogrmerge.rst
I tested it and it works great.
```
$ ogrmerge --version
GDAL 3.9.0, released 2024/05/07
$ man ogrmerge | wc
153     765    7272
$ man ogrmerge.py | wc
No manual entry for ogrmerge.py
0       0       0
```
> Update ogrmerge.rst making ready for primetime

- doc/source/download.rst
Yes, even if repeating index.html . It's important.
> Update download.rst mentioning docs download

- doc/source/programs/gdal2tiles.rst
I'll leave the python note where it is.
> Update gdal2tiles.rst removing .py

- frmts/pdf/pdfsdk_headers.h
> PDF: fix build against PoDoFo with MSYS2 UCRT64 and CLANG64 environments

- autotest/gcore/mask.py
- gcore/gdalnodatamaskband.cpp
> [Backport release/3.9] GDALNoDataMaskBand::IRasterIO(): fix crash on memory allocation failure

- frmts/pdf/pdfsdk_headers.h
> [Backport release/3.9] PDF: fix build against PoDoFo with MSYS2 UCRT64 and CLANG64 environments

- doc/source/programs/gdalmove.rst
- doc/source/programs/pct2rgb.rst
- doc/source/programs/rgb2pct.rst
Remove .py extension from documentation of remaining Python programs (`gdalmove`, `pct2rgb` and `rgb2pct`), now that there are proper entry points for all of these.
- https://github.com/OSGeo/gdal/pull/8718
- https://github.com/OSGeo/gdal/pull/8774
- https://github.com/OSGeo/gdal/issues/8811
- https://github.com/OSGeo/gdal/pull/8815
- https://github.com/OSGeo/gdal/pull/8824
* OS:
* Compiler:
> Remove .py extension from gdalmove, pct2rgb and rgb2pct docs

- autotest/gdrivers/esric.py
- frmts/esric/esric_dataset.cpp
> ESRIC: ingest more bytes to be able to identify more datasets

- ogr/ogrsf_frmts/miramon/mm_gdal_functions.c
- ogr/ogrsf_frmts/miramon/mm_gdal_functions.h
- ogr/ogrsf_frmts/miramon/mm_wrlayr.c
> [Backport release/3.9] MiraMonVector: fix a case sensitive comparison

- autotest/gdrivers/esric.py
- frmts/esric/esric_dataset.cpp
> [Backport release/3.9] ESRIC: ingest more bytes to be able to identify more datasets

- doc/source/download.rst
- doc/source/index.rst
It's my first ever multi-file pull request.
I sure hope I am right about the nightly update frequency.
> Patch 54: Document nightly documentation updates

- doc/source/drivers/vector/oapif.rst
The OAPIF examples contain outdated URLs
Update sample URLs to more current service URLs
> Update OAPIF examples 

- autotest/ogr/ogr_pg.py
- doc/source/drivers/vector/pg.rst
- ogr/ogrsf_frmts/pg/ogr_pg.h
- ogr/ogrsf_frmts/pg/ogrpgdatasource.cpp
- ogr/ogrsf_frmts/pg/ogrpgtablelayer.cpp
> PG: avoid errors related to ogr_system_tables.metadata when user has not enough permissions

- apps/ogr2ogr_lib.cpp
- autotest/ogr/ogr_fgdb.py
- ogr/ogrsf_frmts/filegdb/FGdbLayer.cpp
> FileGDB: fix creating a geometry-less table with ogr2ogr (3.9.0 regression)

- autotest/ogr/data/gml/same_nested_property_name.gml
- autotest/ogr/ogr_gml.py
- doc/source/drivers/vector/gml.rst
- ogr/ogrsf_frmts/gml/gmlreaderp.h
- ogr/ogrsf_frmts/gml/hugefileresolver.cpp
- ogr/ogrsf_frmts/gml/ogrgmldatasource.cpp
> GML: fix issue with nested elements with identical names in GML_SKIP_RESOLVE_ELEMS=HUGE mode

- doc/source/user/configoptions.rst
Document the default value for this configuration variable.
#10123
> User configuration docs: mention default User-Agent

- autotest/ogr/ogr_csv.py
- ogr/ogrsf_frmts/csv/ogrcsvdatasource.cpp
> CSV: error out if invalid/inconsistent value for GEOMETRY layer creation option

- alg/gdal_crs.cpp
- apps/ogr2ogr_lib.cpp
- autotest/utilities/test_ogr2ogr_lib.py
> ogr2ogr: error out if GCP transform creation fails; GCPTransformer: accept only 2 points for order=1 transformer

- ogr/ogrsf_frmts/geojson/ogresrijsonreader.cpp
- ogr/ogrsf_frmts/geojson/ogrgeojsondriver.cpp
- ogr/ogrsf_frmts/geojson/ogrgeojsonutils.cpp
> ESRIJSON: fix paging when URL contains f=pjson instead of f=json

- autotest/ogr/ogr_openfilegdb_write.py
- ogr/ogrsf_frmts/openfilegdb/filegdbtable.cpp
- ogr/ogrsf_frmts/openfilegdb/filegdbtable.h
- ogr/ogrsf_frmts/openfilegdb/filegdbtable_write.cpp
- ogr/ogrsf_frmts/openfilegdb/filegdbtable_write_fields.cpp
- ogr/ogrsf_frmts/openfilegdb/ogropenfilegdbdatasource.cpp
- ogr/ogrsf_frmts/openfilegdb/ogropenfilegdbdatasource_write.cpp
- ogr/ogrsf_frmts/openfilegdb/ogropenfilegdblayer_write.cpp
- ogr/ogrsf_frmts/openfilegdb/test_ofgdb_write.cpp
> [Backport release/3.9] OpenFileGDB: a couple writer side fixes

- autotest/gdrivers/hdf5multidim.py
- frmts/hdf5/gh5_convenience.cpp
- frmts/hdf5/hdf5_api.h
- frmts/hdf5/hdf5dataset.cpp
- frmts/hdf5/hdf5dataset.h
- frmts/hdf5/hdf5imagedataset.cpp
- frmts/hdf5/hdf5multidim.cpp
> [Backport release/3.9] HDF5: add support for libhdf5 >= 1.14.4.2 when built with Float16

- doc/source/drivers/vector/filegdb.rst
- doc/source/drivers/vector/openfilegdb.rst
> Doc: OpenFileGDB: document that sdc format can't be read

- doc/source/development/building_from_source.rst
- doc/source/development/dev_environment.rst
- doc/source/development/index.rst
try to address https://lists.osgeo.org/pipermail/gdal-dev/2024-June/059066.html
> Doc: move build requirements to building_from_source, and put it in first place

- autotest/gdrivers/data/stacit/test.json
- autotest/gdrivers/data/stacit/test_page2.json
- autotest/gdrivers/stacit.py
- frmts/stacit/stacitdataset.cpp
> [Backport release/3.9] STACIT: implement paging using POST method

- ogr/ogrsf_frmts/geojson/ogresrijsonreader.cpp
- ogr/ogrsf_frmts/geojson/ogrgeojsondriver.cpp
- ogr/ogrsf_frmts/geojson/ogrgeojsonutils.cpp
> [Backport release/3.9] ESRIJSON: fix paging when URL contains f=pjson instead of f=json

- doc/source/drivers/vector/dwg.rst
There is no too small contribution :-)
Fix very small doc typo.
* OS:
* Compiler:
> Fix small typo

- swig/python/README.rst
Backport #10160
**Authored by:** @asjohnston-asf
> [Backport release/3.9] Fix rendering of code block in python readme

- autotest/ogr/ogr_pg.py
- doc/source/drivers/vector/nas.rst
- doc/source/drivers/vector/pg.rst
- ogr/ogrsf_frmts/pg/ogr_pg.h
- ogr/ogrsf_frmts/pg/ogrpgtablelayer.cpp
speaking of small contributions…
refs norBIT/alkisimport#82
> OGR_PG_SKIP_CONFLICTS: optionally insert with ON CONFLICT DO NOTHING

- doc/source/drivers/vector/csv.rst
https://gis.stackexchange.com/questions/482410/how-to-use-ogr2ogr-segmentize-on-a-csv-file/482411
> Update csv.rst adding very first CSV to CSV example

- alg/contour.cpp
- autotest/alg/contour.py
Refs https://github.com/OSGeo/gdal/issues/10103
> GDALContourGenerateEx(): validate LEVEL_INTERVAL option

- ogr/ogrsf_frmts/libkml/ogrlibkmldatasource.cpp
> LIBKML: fix performance issue when writing large files

- doc/source/programs/gdalwarp.rst
- doc/source/programs/ogr2ogr.rst
Refs https://github.com/OSGeo/gdal/issues/10141
> Doc: gdalwarp/ogr2ogr -ct: be more explicit about axis order issues

- ogr/ogrsf_frmts/libkml/ogrlibkmldatasource.cpp
> [Backport release/3.9] LIBKML: fix performance issue when writing large files

- alg/viewshed.cpp
- alg/viewshed.h
Shift output extent to current extent to avoid incorrect assumptions.
> Viewshed: create current extent

- autotest/gcore/tiff_write.py
- frmts/gtiff/gtiffdataset_write.cpp
> GTiff writer: limit number of GCPs in GeoTIFF tag to 10922 to avoid overflowing uint16_t

- apps/test_ogrsf.cpp
- autotest/ogr/ogr_geojson.py
- autotest/ogr/ogr_ods.py
- autotest/ogr/ogr_xlsx.py
- ogr/ogrsf_frmts/geojson/ogr_geojson.h
- ogr/ogrsf_frmts/geojson/ogrgeojsondriver.cpp
- ogr/ogrsf_frmts/geojson/ogrgeojsonlayer.cpp
- ogr/ogrsf_frmts/mem/ogr_mem.h
- ogr/ogrsf_frmts/mem/ogrmemlayer.cpp
- ogr/ogrsf_frmts/ods/ogr_ods.h
- ogr/ogrsf_frmts/ods/ogrodsdatasource.cpp
- ogr/ogrsf_frmts/ods/ogrodsdriver.cpp
- ogr/ogrsf_frmts/xlsx/ogr_xlsx.h
- ogr/ogrsf_frmts/xlsx/ogrxlsxdatasource.cpp
- ogr/ogrsf_frmts/xlsx/ogrxlsxdriver.cpp
> [Backport release/3.9] ODS, XLSX, GeoJSON: implement IUpdateFeature() that was broken up to now

- .github/workflows/cmake_builds.yml
- .github/workflows/ubuntu_20.04/Dockerfile.ci
- .github/workflows/ubuntu_24.04/Dockerfile.ci
- autotest/gdrivers/netcdf.py
- frmts/netcdf/netcdfdataset.cpp
…as the latest version of python netCDF4 (1.7.0) is not compatible of 20.04
> CI: cfchecker: move it to Ubuntu 24.04 … and disable again tests on build-windows-conda

- autotest/gdrivers/gpkg.py
- autotest/ogr/ogr_gpkg.py
- ogr/ogrsf_frmts/gpkg/ogr_geopackage.h
- ogr/ogrsf_frmts/gpkg/ogrgeopackagedatasource.cpp
> [gpkg] Implement ALTER TABLE RENAME for rasters

- autotest/gdrivers/grib.py
- frmts/grib/gribdataset.cpp
> GRIB: make .idx reading compatible of /vsisubfile/

- autotest/cpp/test_ogr.cpp
- autotest/ogr/ogr_geos.py
- ogr/ogr_geometry.h
- ogr/ogrcompoundcurve.cpp
- ogr/ogrcurvecollection.cpp
- ogr/ogrcurvepolygon.cpp
- ogr/ogrgeometry.cpp
- ogr/ogrgeometrycollection.cpp
- ogr/ogrpolyhedralsurface.cpp
> Add OGRGeometry::hasEmptyParts()/removeEmptyParts(), and use it in exportToGEOS()

- autotest/gdrivers/grib.py
- frmts/grib/gribdataset.cpp
> [Backport release/3.9] GRIB: make .idx reading compatible of /vsisubfile/

- autotest/ogr/data/parquet/schema_1_1_0.json
- autotest/ogr/ogr_parquet.py
- autotest/pyscripts/test_validate_geoparquet.py
- ogr/ogrsf_frmts/parquet/ogrparquetwriterlayer.cpp
- swig/python/gdal-utils/osgeo_utils/samples/validate_geoparquet.py
now it has been officially released
And remove hacks in validator related to it
> GeoParquet: always write version=1.1.0

- gcore/gdal_priv.h
- gcore/overview.cpp
- gcore/rasterio.cpp
> Overview generation: fix multi-threaded bug, resulting in locks/crashes with GeoPackage in particular

- autotest/ogr/data/parquet/schema_1_1_0.json
- autotest/ogr/ogr_parquet.py
- autotest/pyscripts/test_validate_geoparquet.py
- ogr/ogrsf_frmts/parquet/ogrparquetwriterlayer.cpp
- swig/python/gdal-utils/osgeo_utils/samples/validate_geoparquet.py
> [Backport release/3.9] GeoParquet: always write version=1.1.0

- gcore/gdal_priv.h
- gcore/overview.cpp
- gcore/rasterio.cpp
> [Backport 3.9] Overview generation: fix multi-threaded bug, resulting in locks/crashes with GeoPackage in particular

- swig/python/gdal-utils/osgeo_utils/ogr_layer_algebra.py
Else it sounds like "that town has not (even) a single taxi."
This was supposed to be combined with the next PR.
> Update ogr_layer_algebra.py avoiding unintended misinterpretation

- doc/source/programs/ogr_layer_algebra.rst
This was supposed to be combined with the last PR.
> Update ogr_layer_algebra.rst grammar fixes

- autotest/ogr/ogr_layer_algebra.py
- ogr/ogrsf_frmts/generic/ogrlayer.cpp
> [Backport release/3.9] OGR layer algebra: honour PROMOTE_TO_MULTI=YES for Points

- apps/gdal_translate_lib.cpp
- autotest/cpp/test_gdal.cpp
- frmts/gtiff/gtiffdataset_write.cpp
- frmts/netcdf/netcdfdataset.cpp
- frmts/zarr/zarr_array.cpp
- gcore/gdal_priv_templates.hpp
- gcore/gdalrasterband.cpp
- ogr/ogr_srs_usgs.cpp
- ogr/ogrfeature.cpp
- ogr/ogrsf_frmts/generic/ogrlayerarrow.cpp
- ogr/ogrsf_frmts/gpkg/ogrgeopackagetablelayer.cpp
- ogr/ogrsf_frmts/openfilegdb/filegdbtable_write.cpp
- ogr/ogrsf_frmts/openfilegdb/ogropenfilegdblayer_write.cpp
> [Backport release/3.9] Various undefined behavior sanitizer fixes

- doc/source/programs/ogrinfo.rst
> Update ogrinfo.rst with tip how to workaround need for input file

- autotest/ogr/ogr_libkml.py
- ogr/ogrsf_frmts/libkml/ogrlibkmldatasource.cpp
> LIBKML: fix writing a .kmz to cloud storage

- autotest/ogr/ogr_libkml.py
- ogr/ogrsf_frmts/libkml/ogrlibkmldatasource.cpp
> [Backport release/3.9] LIBKML: fix writing a .kmz to cloud storage

- frmts/kea/keaband.cpp
- frmts/kea/keaband.h
- frmts/kea/keadataset.h
Backport #10351
**Authored by:** @gillins
> [Backport release/3.9] KEA: don't derive from PAM classes

- autotest/gdrivers/data/wmts/clip_WGS84BoundingBox_with_tilematrix.xml
- autotest/gdrivers/wmts.py
- frmts/wmts/wmtsdataset.cpp
> WMTS: clip layer extent with union of extent of tile matrices

- autotest/cpp/test_ogr.cpp
- autotest/ogr/ogr_gml_geom.py
- ogr/gml2ogrgeometry.cpp
- ogr/ogr_geometry.h
- ogr/ogrcompoundcurve.cpp
- ogr/ogrcurve.cpp
- ogr/ogrcurvecollection.cpp
- ogr/ogrlinearring.cpp
- ogr/ogrpgeogeometry.cpp
- ogr/ogrsf_frmts/parquet/ogrparquetwriterlayer.cpp
> GML geometry reader: add support for gml:OrientableCurve

- autotest/cpp/test_ogr_swq.cpp
- autotest/ogr/ogr_sql_rfc28.py
- autotest/ogr/ogr_sql_test.py
- doc/source/user/ogr_sql_dialect.rst
- ogr/ogr_swq.h
- ogr/ogrsf_frmts/generic/ogr_gensql.cpp
- ogr/swq.cpp
- ogr/swq_op_registrar.cpp
- ogr/swq_select.cpp
> OGRSQL: add STDDEV_POP() and STDDEV_SAMP() aggregate functions

- autotest/gdrivers/data/wmts/clip_WGS84BoundingBox_with_tilematrix.xml
- autotest/gdrivers/wmts.py
- frmts/wmts/wmtsdataset.cpp
> [Backport release/3.9] WMTS: clip layer extent with union of extent of tile matrices

- autotest/ogr/ogr_gml.py
- ogr/ogrsf_frmts/gml/ogr_gml.h
- ogr/ogrsf_frmts/gml/ogrgmldatasource.cpp
- ogr/ogrsf_frmts/gml/ogrgmllayer.cpp
> [Backport release/3.9] GML writer: fix missing SRS in Featurecollection's boundedBy element (3.9.1 regression)

- apps/gdal_rasterize_lib.cpp
- autotest/cpp/test_gdal_gtiff.cpp
- autotest/utilities/test_gdal_rasterize_lib.py
- doc/source/programs/gdal_rasterize.rst
- frmts/gtiff/gtiffrasterband_write.cpp
> [Backport release/3.9] gdal_rasterize: fix issue with nodata not taken into account on a GeoTIFF Int64 band 

- autotest/ogr/ogr_wkbwkt_geom.py
- ogr/ogrgeometry.cpp
Cf thread at https://lists.osgeo.org/pipermail/qgis-developer/2024-July/066906.html
> WKT geometry importer: accept (non conformant) PointZ/PointZM without space as generated by current QGIS versions

- autotest/ogr/ogr_sql_test.py
- ogr/CMakeLists.txt
- ogr/swq_parser.cpp
- ogr/swq_parser.y
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=69985
> OGR SQL lexer: fix memory leak on invalid expression (master only)

- frmts/ecw/ecwcreatecopy.cpp
Fixes https://github.com/OSGeo/gdal/commit/22bd7669bc935e66dcb723321f49a27d4324a6e9
> ECW: emit error message before emitting progression, and one cleanup

- frmts/ecw/ecwdataset.cpp
- frmts/grib/gribdataset.cpp
- frmts/gtiff/gtiffdataset.h
- frmts/gtiff/gtiffdataset_read.cpp
- frmts/jp2kak/jp2kakdataset.cpp
- frmts/jpeg/jpgdataset.cpp
- frmts/jpeg/jpgdataset.h
- frmts/opjlike/jp2opjlikedataset.cpp
- frmts/png/pngdataset.cpp
- frmts/tiledb/tiledbdense.cpp
- frmts/tiledb/tiledbheaders.h
- gcore/gdal_misc.cpp
- gcore/gdal_pam.h
- gcore/gdal_priv.h
- gcore/gdaldefaultoverviews.cpp
- gcore/gdalgeorefpamdataset.cpp
- gcore/gdalgeorefpamdataset.h
- gcore/gdalopeninfo.cpp
- gcore/gdalpamdataset.cpp
Fixes #10360
and other similar related changes in other drivers
> JP2OpenJPEG: use GetSiblingFiles()

- apps/data/gdalinfo_output.schema.json
> [Backport release/3.9] gdalinfo_output.schema.json: pin stac-extensions/eo to v1.1.0

- doc/source/index.rst
Add a tag for google site verification for the search console
> [Doc] add google-site-verification to index.html

- doc/source/programs/ogr2ogr.rst
Avoid ERROR 5: -spat_srs not compatible with -sql surprise.
> Update ogr2ogr.rst document illegal combinations

- ci/travis/osx/before_install.sh
> [Backport release/3.9] CI: adapt for Conda-Forge libgdal feedstock changes

- port/cpl_vsil_libarchive.cpp
> Fix compilation against libarchive-3.3.3-5 as shipped by RHEL 8

- autotest/gdrivers/pds4.py
- frmts/pds/pds4dataset.cpp
> PDS4: flip image along horizontal axis when horizontal_display_direction = Right to Left

- port/cpl_vsil_libarchive.cpp
> [Backport release/3.9] Fix compilation against libarchive-3.3.3-5 as shipped by RHEL 8

- frmts/mrf/LERCV1/Lerc1Image.cpp
- frmts/mrf/LERC_band.cpp
> MRF/LERC: check that values are within target type range before casting

- ogr/ogrsf_frmts/miramon/ogrmiramonlayer.cpp
> [Backport release/3.9] MiraMonVector: fix Issue 70860 in oss-fuzz

- autotest/ogr/ogr_sqlite.py
- ogr/ogrsf_frmts/sqlite/ogr_sqlite.h
- ogr/ogrsf_frmts/sqlite/ogrsqlitedatasource.cpp
Refs https://github.com/airbusgeo/godal/pull/132#issuecomment-2250515567
> SQLite: run deferred table creation before StartTransaction

- autotest/gdrivers/srtmhgt.py
- frmts/srtmhgt/srtmhgtdataset.cpp
> SRTMHGT: add support for 0.5 deg resolution datasets

- autotest/gdrivers/srtmhgt.py
- frmts/srtmhgt/srtmhgtdataset.cpp
> [Backport release/3.9] SRTMHGT: add support for 0.5 deg resolution datasets

- alg/gdalsievefilter.cpp
- frmts/jpegxl/jpegxl.cpp
> [Backport release/3.9] Fix -Wnull-dereference warnings of gcc 14.2

- autotest/gdrivers/nitf.py
- frmts/nitf/nitfwritejpeg.cpp
> NITF 12-bit JPEG writer: fix potential crash if raster width > block width

- autotest/ogr/data/gmlas/test_ossfuzz_70511.xsd
- autotest/ogr/ogr_gmlas.py
- ogr/ogrsf_frmts/gmlas/ogr_gmlas.h
- ogr/ogrsf_frmts/gmlas/ogrgmlasschemaanalyzer.cpp
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=70511
> GMLAS: avoid crash on a OSSFuzz generated xsd

- autotest/ogr/ogr_gtfs.py
- ogr/ogrsf_frmts/gtfs/ogrgtfsdriver.cpp
Fixes https://github.com/duckdb/duckdb_spatial/issues/343
> GTFS: fix error when applying an attribute filter on a field whose advertized data type is not string

- autotest/ogr/ogr_libkml.py
- ogr/ogrsf_frmts/libkml/ogrlibkmldatasource.cpp
- ogr/ogrsf_frmts/libkml/ogrlibkmlfeaturestyle.cpp
On top of PR #10473
Fixes #10478
> LIBKML: fix reading/writing style URL in KMZ files

- ogr/ogrsf_frmts/pg/ogrpgdatasource.cpp
- ogr/ogrsf_frmts/pg/ogrpglayer.cpp
> PG: fix support for geometry/geography OID in range [2147483648, 4294967295]

- doc/source/user/multidim_raster_data_model.rst
- gcore/gdal.h
> Doc: document multidimensional API object lifetime

- autotest/ogr/ogr_csv.py
- ogr/ogrsf_frmts/csv/ogrcsvlayer.cpp
> CSV: emit warning when reading invalid WKT

- autotest/gdrivers/nitf.py
- frmts/nitf/nitfwritejpeg.cpp
> [Backport release/3.9] NITF 12-bit JPEG writer: fix potential crash if raster width > block width

- autotest/gdrivers/gti.py
- doc/source/drivers/raster/gti.rst
- frmts/vrt/gdaltileindexdataset.cpp
> [Backport release/3.9] GTI driver fixes

- ogr/ogrsf_frmts/pg/ogrpgdatasource.cpp
- ogr/ogrsf_frmts/pg/ogrpglayer.cpp
> [Backport release/3.9] PG: fix support for geometry/geography OID in range [2147483648, 4294967295]

- autotest/ogr/ogr_libkml.py
- ogr/ogrsf_frmts/libkml/ogrlibkmldatasource.cpp
- ogr/ogrsf_frmts/libkml/ogrlibkmlfeaturestyle.cpp
> [Backport release/3.9] LIBKML: fix reading/writing style URL in KMZ files

- autotest/gdrivers/nitf.py
- frmts/nitf/nitfdataset.cpp
> NITF: CreateCopy(): support Blue,Green,Red[,other] color interpretation ordering

- autotest/ogr/ogr_openfilegdb_write.py
- doc/source/drivers/vector/openfilegdb.rst
- ogr/ogrsf_frmts/openfilegdb/ogropenfilegdbdatasource.cpp
> OpenFileGDB: error out explicitly when attempting to create an index on multiple columns

- apps/gdaldem_lib.cpp
- autotest/utilities/test_gdaldem_lib.py
Fixes https://lists.osgeo.org/pipermail/gdal-dev/2024-August/059324.html
> gdaldem color-relief: fix issues with entry at 0 and -exact_color_entry mode, and other issues

- apps/gdaldem_lib.cpp
- autotest/utilities/test_gdaldem_lib.py
> [Lint] C++ify some aspects of gdaldem color-relief

- docker/README.md
- docker/ubuntu-small/Dockerfile
This speeds up GeoTIFF I/O quite significantly, and is only 92 KB, so it might be worth it.
N/A
> Include `libdeflate` in `ubuntu-small` images

- apps/gdal_translate_lib.cpp
- autotest/gcore/overviewds.py
- autotest/utilities/test_gdal_translate.py
- autotest/utilities/test_gdal_translate_lib.py
- gcore/gdaloverviewdataset.cpp
> gdal_translate/GDALOverviewDataset: fix half-pixel shift issue when rescaling RPC

- apps/gdaldem_lib.cpp
- autotest/utilities/test_gdaldem_lib.py
> [Backport release/3.9] gdaldem color-relief: fix issues with entry at 0 and -exact_color_entry mode, and other issues

- autotest/gdrivers/netcdf.py
- frmts/netcdf/netcdfdataset.cpp
> netCDF: honour BAND_NAMES creation option in CreateCopy()

- doc/source/index.rst
Resolves https://github.com/OSGeo/gdal/issues/10666
> Doc: Restore driver list on main page

- ogr/ogrsf_frmts/shape/gdal_shapelib_symbol_rename.h
Backport #10683
**Authored by:** @dirkvdb
> [Backport release/3.9] Add new shapelib API functions to the symbol rename header

- doc/source/download.rst
> [Backport release/3.9] Doc: add a Maintenance policy section

- autotest/ogr/ogr_geom.py
- autotest/ogr/ogr_gpkg.py
- autotest/ogr/ogr_sqlite.py
- doc/source/drivers/vector/gpkg.rst
- doc/source/spelling_wordlist.txt
- ogr/ogr_api.cpp
- ogr/ogr_api.h
- ogr/ogr_geometry.h
- ogr/ogrcircularstring.cpp
- ogr/ogrcompoundcurve.cpp
- ogr/ogrcurve.cpp
- ogr/ogrcurvepolygon.cpp
- ogr/ogrgeometrycollection.cpp
- ogr/ogrlinestring.cpp
- ogr/ogrpolyhedralsurface.cpp
- ogr/ogrsf_frmts/gpkg/ogrgeopackagedatasource.cpp
- ogr/ogrsf_frmts/sqlite/ogrsqlitesqlfunctions.cpp
- ogr/ogrsurface.cpp
- swig/include/ogr.i
- swig/include/python/docs/ogr_geometry_docs.i
and make OGR_G_GetLength() work on surfaces, suming the length of their exterior and interior rings.
and SQLite/GPKG: Add ST_Length(geom, use_ellipsoid)
> Add OGR_G_GeodesicLength() and OGRCurve/OGRSurface/OGRGeometryCollection::get_GeodesicLength()

- alg/gdalgeoloc_dataset_accessor.h
> Geoloc: fix bad usage of path API that resulted in temporary files not being created where expected

- frmts/mrsid/mrsiddataset.cpp
> MrSID: prevent infinite recursion in MrSIDDataset::IRasterIO() in some cases

- autotest/gdrivers/srtmhgt.py
- doc/source/drivers/raster/srtmhgt.rst
- frmts/srtmhgt/srtmhgtdataset.cpp
> SRTMHGT: add support for creating 7201x7201 files

- autotest/ogr/ogr_dgn.py
- doc/source/drivers/vector/dgn.rst
- ogr/ogrsf_frmts/dgn/ogr_dgn.h
- ogr/ogrsf_frmts/dgn/ogrdgndatasource.cpp
- ogr/ogrsf_frmts/dgn/ogrdgndriver.cpp
- ogr/ogrsf_frmts/dgn/ogrdgnlayer.cpp
> DGN: add ENCODING open option and creation option

- ogr/ogrsf_frmts/miramon/mm_gdal_functions.c
Fixes the Issue 69168 from Oss-Fuzz (pendant from some time ago)
> MiraMonVector: Fix Issue 69168 oss-fuzz

- autotest/ogr/ogr_geojson.py
- doc/source/spelling_wordlist.txt
- ogr/ogr_geometry.h
- ogr/ogrgeometrycollection.cpp
- ogr/ogrgeometryfactory.cpp
> OGRGeometryFactory::transformWithOptions(): in WRAPDATELINE=YES mode, return a multi polygon if a input multi polygon has been provided

- autotest/gcore/vsigs.py
- port/cpl_google_cloud.cpp
- port/cpl_google_cloud.h
- port/cpl_http.h
- port/cpl_vsil_gs.cpp
and rework all access token caching logic to support simultaneous different configurations (if accessing files using different credentials)
> /vsigs/: make sure access token with GOOGLE_APPLICATION_FILE in authorized_user mode is cached

- ogr/ogrsf_frmts/generic/ogr_gensql.cpp
With this optimization, ``ogrinfo nz-building-outlines.parquet -sql "select stddev_pop(building_id) from \"nz-building-outlines\""`` goes from 2.8 s to 0.8 s
> [Optim] OGRSQL: do not query geometry column(s) when not needed

- autotest/gdrivers/vrtwarp.py
- gcore/gdal_misc.cpp
Fixes https://lists.osgeo.org/pipermail/gdal-dev/2024-August/059412.html
Partial backport of #10708
> [Backport 3.9] Fix GDALDataTypeUnion() to check that the provided value fits into eDT

- gcore/gdalrasterband.cpp
> GDALRasterBand::BuildOverviews(): clarify warning

- frmts/mrf/QB3_band.cpp
> Enable QB3_FTL mode when available

- doc/source/gdal_rtd/static/css/gdal.css
Fixes https://github.com/OSGeo/gdal/issues/10679
> Doc: Make sidebar version text visible

- apps/gdal_rasterize_lib.cpp
- autotest/utilities/test_gdal_rasterize_lib.py
> [gdal_rasterize] Fix crash with no options after argparser

- doc/source/_extensions/configoptions.py
> Doc: insert Unicode zero-width space character in :choices: output, to be nice with browsers line-break insertion logic

- doc/source/programs/gdalwarp.rst
I'm not sure what the sentence means in its current form, so add what I believe is the missing word.
* OS:
* Compiler:
> Doc: add missing word

- autotest/ogr/ogr_vrt.py
- ogr/ogrsf_frmts/generic/ogrwarpedlayer.cpp
- ogr/ogrsf_frmts/generic/ogrwarpedlayer.h
> OGRWarpedVRT:  faster SrcFeature <--> WarpedFeature transformations

- doc/source/download.rst
> Doc: add instructions for Android installation

- apps/ogr2ogr_lib.cpp
- autotest/cpp/test_ogr.cpp
- ogr/ogrgeometryfactory.cpp
The logic already existed but was restricted to WGS 84 without any good reason.
> OGRGeometryFactory::transformWithOptions(): deal with polar or anti-meridian discontinuities when going from projected to (any) geographic CRS

- autotest/ogr/ogr_geojson.py
- ogr/ogrsf_frmts/mem/ogrmemlayer.cpp
This amends https://github.com/OSGeo/gdal/pull/10197 which didn't fix the issue of https://github.com/qgis/QGIS/pull/57736#discussion_r1636226384
> MEM layer: fix UpdateFeature() that didn't mark the layer as updated, which caused GeoJSON files to not be updated

- doc/source/download.rst
> [Backport release/3.9] Doc: add instructions for Android installation

- autotest/ogr/ogr_geom.py
- ogr/ogrgeometry.cpp
Fixes #10819
We'll now behave like recent PostGIS + GEOS.
Note that PostGIS doesn't necessarily return a fully identical geometry (it may change the winding order, remove duplicated points):
```
autotest=# select postgis_full_version();
POSTGIS="3.4.3 e365945" [EXTENSION] PGSQL="170" GEOS="3.13.0beta2-CAPI-1.19.0" PROJ="6.3.1" LIBXML="2.9.10" LIBJSON="0.13.1" LIBPROTOBUF="1.3.3" WAGYU="0.5.0 (Internal)"
(1 row)
autotest=# select st_astext(st_makevalid('MULTIPOLYGON (((0 0, 1 0, 1 0, 1 1, 0 1, 0 0)))'::geometry,'method=structure'));
---------------------------------------
MULTIPOLYGON(((0 0,0 1,1 1,1 0,0 0)))
(1 row)
autotest=# select st_astext(st_makevalid('MULTIPOLYGON (((0 0, 1 0, 1 0, 1 1, 0 1, 0 0)))'::geometry,'method=linework'));
------------------------------------------- …
```
> MakeValid(METHOD=STRUCTURE): make sure to return a MULTIPOLYGON if input is MULTIPOLYGON

- autotest/gcore/rasterio.py
- gcore/gdalnodatamaskband.cpp
- gcore/overview.cpp
- gcore/rasterio.cpp
> [Backport release/3.9] Overview: fix nearest and mode resamplings to be exact with all data types

- alg/gdalgeoloc.cpp
- alg/gdalgeoloc_dataset_accessor.h
- autotest/gcore/vrt_read.py
- frmts/vrt/vrtsourcedrasterband.cpp
- frmts/vrt/vrtsources.cpp
> [Backport release/3.9] Speed-up geolocation-array based warping of Sentinel3 datasets

- .github/workflows/cmake_builds.yml
Cf https://github.com/Homebrew/homebrew-core/pull/170959#issuecomment-2379606442
> CI Mac Homebrew: workaround issue with latest hdf5 package

- alg/contour.cpp
- alg/marching_squares/segment_merger.h
- alg/marching_squares/square.h
- autotest/alg/contour.py
> [Backport release/3.9] [gdal_contour] Fix regression when fixed level == raster max

- ogr/ogrsf_frmts/miramon/mm_wrlayr.c
This correction complements the previous one, which contained a minor error.
https://github.com/OSGeo/gdal/pull/10872
> MiraMonVector Fix issue 5250834764464128

- autotest/ogr/ogr_pg.py
- doc/source/drivers/vector/pg.rst
- ogr/ogrsf_frmts/pg/ogr_pg.h
- ogr/ogrsf_frmts/pg/ogrpgdatasource.cpp
> PG: ensure current user has superuser priviledge beore attemption to create event trigger for metadata table

- frmts/dimap/dimapdataset.cpp
> DIMAP: emit verbose error message if not able to open image file

- autotest/ogr/ogr_pg.py
- doc/source/drivers/vector/pg.rst
- ogr/ogrsf_frmts/pg/ogr_pg.h
- ogr/ogrsf_frmts/pg/ogrpgdatasource.cpp
> [Backport release/3.9] PG: ensure current user has superuser priviledge beore attemption to create event trigger for metadata table

- docker/alpine-normal/Dockerfile
- docker/alpine-small/Dockerfile
- docker/ubuntu-full/Dockerfile
- docker/ubuntu-full/bh-gdal.sh
- docker/ubuntu-full/bh-proj.sh
- docker/ubuntu-small/Dockerfile
There are some nice features in CMake
that are limited to Ninja only, for
example JOB_POOL_LINK and Multi-config:
https://cmake.org/cmake/help/latest/prop_tgt/JOB_POOL_LINK.html
https://cmake.org/cmake/help/latest/generator/Ninja%20Multi-Config.html
https://www.scivision.dev/cmake-ninja-multi-config/
The first limits the number of linking
processes running concurrently, and the second
avoids having to re-generate the build files
to make a debug/release build.
Ninja is also rumored to be slightly faster
than make, and that seems to hold for GDAL
as well, a simple benchmark (time -p) with
a warm cache (second time image is built)
for ubuntu-small on a 48 core machine
(3 GHz dual Xeon Gold 6136):
PROJ:
make:
real 65.39
user 400.61
sys 34.91
ninja:
real 64.84
user 413.17
sys 34.97
GDAL:
make: …
> docker: use ninja as build system

- doc/source/conf.py
- doc/source/gdal_rtd/static/css/gdal.css
> Doc: attempt at fixing issue with color of version switch

- doc/source/spelling_wordlist.txt
- doc/source/tutorials/index.rst
- Raster and vector processing with GDAL, FOSS4G Europe, by myself
- Robert Simmon's series: A Gentle Introduction to GDAL
> Doc: add a section about workshops and external tutorials

- autotest/ogr/ogr_mitab.py
- ogr/ogrmitabspatialref.cpp
> MapInfo SRS: better deal with EPSG:3301 'Estonian Coordinate System of 1997'

- autotest/gdrivers/safe.py
- frmts/safe/safedataset.cpp
- frmts/safe/safedataset.h
```
$ gdalinfo autotest/gdrivers/data/SAFE_FAKE/test.SAFE/manifest.safe
[...]
Metadata:
[...]
FOOTPRINT=POLYGON((-8.407759 38.130520,-11.335915 38.535374,-11.026125 40.036644,-8.035001 39.633217, -8.407759 38.130520))
```
> SAFE (Sentinel1): report a FOOTPRINT metadata item

- autotest/ogr/ogr_oapif.py
- doc/source/drivers/vector/oapif.rst
- ogr/ogrsf_frmts/oapif/ogroapifdriver.cpp
> OAPIF: add a DATETIME open option

- doc/source/drivers/raster/pdf.rst
> Remove "trademarked" terms

- doc/source/drivers/raster/pdf.rst
> [Backport release/3.9] Remove "trademarked" terms

- autotest/ogr/ogr_pgeo.py
- port/cpl_odbc.cpp
> CPLODBCSession::EstablishSession(): recode DSN to Windows current ANSI page

- apps/gdal_rasterize_lib.cpp
- autotest/utilities/test_gdal_rasterize_lib.py
> gdal_rasterize: properly honour -ts height (master only)

- doc/source/index.rst
- doc/source/thanks.rst
If anyone wants to be removed or have their information modified, you can suggest a change here or contact me directly (even.rouault at spatialys.com)
If you have a suggestion for adding someone that should be added, please contact me directly.
> Doc: add a thanks page

- port/CMakeLists.txt
> Fix build related to character_set_conv_table_generator (master only)

- doc/source/drivers/raster/zarr.rst
> Doc: Zarr: clarify INTERLEAVE default value

- autotest/gdrivers/netcdf.py
- frmts/netcdf/netcdfdataset.cpp
Fixes https://lists.osgeo.org/pipermail/gdal-dev/2024-October/059618.html
> netCDF CreateCopy(): fix taking into account NETCDF_DIM_EXTRA when source dataset is not georeferenced

- autotest/ogr/ogr_kml.py
- autotest/utilities/test_ogr2ogr.py
- ogr/ogrsf_frmts/kml/ogr_kml.h
- ogr/ogrsf_frmts/kml/ogrkmllayer.cpp
Fixes https://github.com/OSGeo/gdal/pull/10840#issuecomment-2406314579
> KML driver: writer: generate a Placemark id

- docker/util.sh
Set the SOURCE_DATE_EPOCH for releases
to get more similar images when building
the same release twice.
> docker/util.sh: set SOURCE_DATE_EPOCH for releases

- swig/python/gdal-utils/README.rst
Backport #11018
**Authored by:** @pjonsson
> [Backport release/3.10] Doc: reword sentence

- apps/gdalbuildvrt_lib.cpp
- autotest/gcore/vrtmisc.py
- doc/source/drivers/raster/vrt.rst
- doc/source/programs/gdalbuildvrt.rst
- scripts/gdal-bash-completion.sh
- swig/include/python/gdal_python.i
> gdalbuildvrt: add a -co switch

- ogr/ogrsf_frmts/miramon/mm_wrlayr.c
This correction complements the previous one, which contained a minor error.
https://issues.oss-fuzz.com/issues/372358476
> MiraMonVector: fix issue 372358476

- .github/workflows/doc_checks.yml
- autotest/gdrivers/zarr_driver.py
- doc/source/thanks.rst
- frmts/zarr/zarrdriver.cpp
> Zarr: Create(): remove created files / directories if an error occurs

- doc/source/drivers/vector/gml.rst
- ogr/ogrsf_frmts/gml/ogrgmldatasource.cpp
…(and deprecate undocumented GML_DOWNLOAD_WFS_SCHEMA)
> GML: add a GML_DOWNLOAD_SCHEMA config option matching the DOWNLOAD_SCHEMA open option 

- apps/gdalbuildvrt_lib.cpp
- autotest/gcore/vrtmisc.py
- doc/source/drivers/raster/vrt.rst
- doc/source/programs/gdalbuildvrt.rst
- scripts/gdal-bash-completion.sh
- swig/include/python/gdal_python.i
> [Backport release/3.10] gdalbuildvrt: add a -co switch

- ogr/ogrsf_frmts/miramon/mm_wrlayr.c
> [Backport release/3.10] MiraMonVector: fix issue 372358476

- autotest/gdrivers/zarr_driver.py
- frmts/zarr/zarrdriver.cpp
> [Backport release/3.10] Zarr: Create(): remove created files / directories if an error occurs

- doc/source/drivers/vector/gml.rst
- ogr/ogrsf_frmts/gml/ogrgmldatasource.cpp
> [Backport release/3.10] GML: add a GML_DOWNLOAD_SCHEMA config option matching the DOWNLOAD_SCHEMA open option 

- autotest/ogr/ogr_gpkg.py
- autotest/utilities/test_gdal_contour.py
> [Backport release/3.10] autotest: fix memory leaks

- swig/python/gdal-utils/osgeo_utils/gdal2tiles.py
- swig/python/gdal-utils/osgeo_utils/gdal_merge.py
- swig/python/gdal-utils/osgeo_utils/gdal_proximity.py
- swig/python/gdal-utils/osgeo_utils/gdal_retile.py
- swig/python/gdal-utils/osgeo_utils/gdalattachpct.py
- swig/python/gdal-utils/osgeo_utils/gdalcompare.py
- swig/python/gdal-utils/osgeo_utils/gdalmove.py
- swig/python/gdal-utils/osgeo_utils/ogr_layer_algebra.py
- swig/python/gdal-utils/osgeo_utils/ogrmerge.py
Sorry, been out of commission for a while, and will be for a bit longer, but here's the usage text update I promised.
> gdal-utils: remove .py from usage text

- swig/python/gdal-utils/osgeo_utils/gdal2tiles.py
- swig/python/gdal-utils/osgeo_utils/gdal_merge.py
- swig/python/gdal-utils/osgeo_utils/gdal_proximity.py
- swig/python/gdal-utils/osgeo_utils/gdal_retile.py
- swig/python/gdal-utils/osgeo_utils/gdalattachpct.py
- swig/python/gdal-utils/osgeo_utils/gdalcompare.py
- swig/python/gdal-utils/osgeo_utils/gdalmove.py
- swig/python/gdal-utils/osgeo_utils/ogr_layer_algebra.py
- swig/python/gdal-utils/osgeo_utils/ogrmerge.py
Backport #11092
**Authored by:** @pjonsson
> [Backport release/3.10] gdal-utils: remove .py from usage text

- doc/source/programs/gdal_translate.rst
> [Backport release/3.10] Doc: Clarify behavior of gdal_translate -scale and -exponent

- autotest/gdrivers/jpegxl.py
- doc/source/drivers/raster/jpegxl.rst
- frmts/jpegxl/jpegxl.cpp
> JPEGXL: writer: propagate DISTANCE/QUALITY setting to extra channel

- autotest/gdrivers/jpegxl.py
- doc/source/drivers/raster/jpegxl.rst
- frmts/jpegxl/jpegxl.cpp
> [Backport release/3.10] JPEGXL: writer: propagate DISTANCE/QUALITY setting to extra channel

- docker/util.sh
> [Backport release/3.10] docker: fix non-release arm64 Ubuntu builds

- frmts/heif/heifdataset.cpp
Perhaps not needed, but can't hurt
> HEIF: add casts to size_t to be on the safer side

- autotest/gcore/tiff_write.py
- frmts/gtiff/tif_jxl.c
> [Backport release/3.10] tif_jxl: writer: propagate DISTANCE/QUALITY setting to extra channel

- .github/workflows/cmake_builds.yml
- swig/python/modify_cpp_files.cmake
Fixes https://github.com/conda-forge/gdal-feedstock/issues/995
> Python bindings: fix compatibility issue with SWIG 4.3.0 and PYTHONWARNINGS=error

- .github/workflows/ubuntu_24.04/expected_gdalinfo_formats.txt
- .github/workflows/ubuntu_24.04/expected_ogrinfo_formats.txt
- .github/workflows/windows_conda_expected_gdalinfo_formats.txt
- .github/workflows/windows_conda_expected_ogrinfo_formats.txt
- ogr/ogrsf_frmts/openfilegdb/ogropenfilegdbdrivercore.cpp
> OpenFileGDB: change long name to 'ESRI FileGeodatabase (using OpenFileGDB)'

- autotest/gdrivers/data/pdf/invalid_srs.pdf
- autotest/gdrivers/pdf.py
- frmts/pdf/pdfdataset.cpp
Fixes https://issues.oss-fuzz.com/issues/376126833
> PDF: fix nullptr dereference on invalid file

- autotest/gdrivers/data/pdf/invalid_srs.pdf
- autotest/gdrivers/pdf.py
- frmts/pdf/pdfdataset.cpp
> [Backport release/3.10] PDF: fix nullptr dereference on invalid file

- .github/workflows/cmake_builds.yml
> CI: build-windows-msys2-mingw: disable hdf5 because of test failures with hdf5 1.14.5-1

- autotest/gdrivers/rs2.py
- frmts/rs2/rs2dataset.cpp
Merge changes likely coming from https://github.com/DND-DRDC-RDDC/OS_DriverMetadataExtractionCodes_RCM_C-band_SARdata/blob/5ff9896b67c38005e26a5895f42566238c53a72a/1%20-%20RCM%20C%2B%2B%20GDAL%20driver%20code/frmts/rs2/rs2dataset.cpp#L1649 and provided by Esri
> RS2: merge modifications coming from DRDC related to NITF Complex datasets

- autotest/gdrivers/nitf.py
- doc/source/drivers/raster/nitf_advanced.rst
- frmts/nitf/nitfdataset.cpp
- frmts/nitf/nitfdataset.h
- frmts/nitf/nitfrasterband.cpp
Merge changes from https://github.com/DND-DRDC-RDDC/OS_DriverMetadataExtractionCodes_RCM_C-band_SARdata/commit/1f4d014ade7ccec5b47d2d5cdc92acbeb40c15a3 and provided by Esri, and slightly modified by me.
Added test is mine.
> NITF: represent SAR products with I,Q bands as single complex band

- autotest/postinstall/test_gdal-config.sh
- ogr/ogr_recordbatch.h
Relates to https://github.com/OSGeo/grass/issues/4585
> CI: check that all our public headers can be compiled with -Wall -Wpedantic

- autotest/gcore/misc.py
- port/cpl_error.cpp
Fixes https://github.com/OSGeo/gdal/issues/11219
> CPLDebug: Accept values of YES,TRUE,1

- autotest/gcore/misc.py
- port/cpl_error.cpp
> [Backport release/3.10] CPLDebug: Accept values of YES,TRUE,1

- autotest/gnm/gnm_test.py
> [Backport release/3.10] autotest: fix test failure with msys2 mingw64

- ogr/ogrsf_frmts/lvbag/ogrlvbaglayer.cpp
> [Backport release/3.10] LVBAG: only run IsValid() if bFixInvalidData

- docker/README.md
Add mention that the GDAL 3.10 Ubuntu docker image is based on Ubuntu 24.04 as well.
None as I can see.
Not relevant, only affects Markdown documentation.
> Doc: Clarify Ubuntu version is 24.04 for GDAL 3.10

- swig/python/gdal-utils/osgeo_utils/gdal2tiles.py
This codebase is pretty clean.
> remove more Python2 compatiblity code

- autotest/utilities/test_gdal_translate_lib.py
- swig/include/python/gdal_python.i
> [Backport release/3.10] Python bindings: add a colorInterpretation argument to gdal.Translate()

- doc/source/programs/ogr2ogr.rst
added filename option for -sql
* OS:
* Compiler:
> Update ogr2ogr.rst - missing filename option

- frmts/avif/avifdataset.cpp
Backport #11289
**Authored by:** @bradh
> [Backport release/3.10] avif: typo fix

- alg/gdal_interpolateatpoint.cpp
- autotest/cpp/test_gdal_vectorx.cpp
Fix some coverity scan tests that were failing
> fix some coverity tests

- doc/source/programs/ogr2ogr.rst
> Update ogr2ogr.rst - option where syntax with filename

- .github/workflows/auto_tag_stable.yml
- HOWTO-RELEASE
- doc/source/conf.py
- doc/source/extra_path/robots.txt
Similar to what has been done in PROJ a few days ago
CC @jjimenezshaw
> Preparatory steps to have https://gdal.org default to a 'stable' branch

- doc/source/_extensions/cli_example.py
Should fix https://github.com/OSGeo/gdal/issues/11330
> Doc: Fix example xrefs in singlehtml build

- autotest/gcore/vsis3.py
- doc/source/user/virtual_file_systems.rst
- port/cpl_aws.cpp
- port/cpl_aws.h
- port/cpl_sha1.cpp
- port/cpl_sha1.h
> /vsis3/ / AWS: implement support for AWS Single-Sign On (AWS IAM Identity Center)

- autotest/gcore/vsis3.py
- doc/source/user/virtual_file_systems.rst
- port/cpl_aws.cpp
- port/cpl_aws.h
- port/cpl_sha1.cpp
- port/cpl_sha1.h
> [Backport release/3.10] /vsis3/ / AWS: implement support for AWS Single-Sign On (AWS IAM Identity Center)

- swig/include/java/gdal_java.i
- swig/include/java/typemaps_java.i
- swig/java/apps/GDALTestIO.java
- swig/java/javadoc.java
> [Backport release/3.10] Java bindings: add byte[] org.gdal.gdal.GetMemFileBuffer(String filename)

- doc/source/programs/gdal_sieve.rst
Backport #11355
**Authored by:** @kadyb
> [Backport release/3.10] update gdal_sieve.rst

- apps/ogr2ogr_lib.cpp
- autotest/ogr/ogr_oci.py
- doc/source/drivers/vector/oci.rst
- ogr/ogrsf_frmts/oci/ogr_oci.h
- ogr/ogrsf_frmts/oci/ogrocidrivercore.cpp
- ogr/ogrsf_frmts/oci/ogrocisession.cpp
- ogr/ogrsf_frmts/oci/ogrocitablelayer.cpp
- ogr/ogrsf_frmts/oci/ogrociwritablelayer.cpp
Fixes https://github.com/OSGeo/gdal/issues/11057#issuecomment-2495479779
> OCI: add a TIMESTAMP_WITH_TIME_ZONE layer creation option, and ogr2ogr tweaks

- doc/source/software_using_gdal.rst
(As for licensing, the [mobile app](https://github.com/MerginMaps/mobile) is GPL-2 and the [server side (community edition)](https://github.com/MerginMaps/server) is AGPL-3)
> Add Mergin Maps to software_using_gdal.rst

- ogr/ogr_api.h
- ogr/ogr_feature.h
- ogr/ogrsf_frmts/ogrsf_frmts.dox
- port/cpl_conv.cpp
- port/cpl_csv.cpp
- port/cpl_error.cpp
- port/cpl_path.cpp
- port/cpl_vsil_curl.cpp
> Doxygen docs: use \code instead of <pre>

- autotest/postinstall/test_cpp/test_cpp.cpp
- gdal.cmake
- ogr/ogr_api.h
- ogr/ogr_feature.h
- ogr/ogr_geometry.h
- ogr/ogr_srs_api.h
- ogr/ograpispy.h
- port/cpl_error.h
> [Backport release/3.10] CMake: export -DGDAL_DEBUG as PUBLIC for debug builds

- frmts/hdf4/hdf-eos/EHapi.c
- frmts/hdf4/hdf-eos/GDapi.c
- frmts/hdf4/hdf-eos/HdfEosDef.h
- frmts/hdf4/hdf-eos/SWapi.c
> [Backport release/3.10] Fix lots of Coverity Scan warnings in frmts/hdf4/hdf-eos

- autotest/gdrivers/zarr_driver.py
- frmts/zarr/zarr_array.cpp
Resolves issue of https://github.com/OSGeo/gdal/pull/11380
> Zarr: fix incorrect DataAxisToSRSAxisMapping for EPSG geographic CRS

- doc/source/development/cmake.rst
Backport #11359
**Authored by:** @SunBlack
> [Backport release/3.10] Add a hint in the documentation, that the configuration file was created with SameMinorVersion.

- autotest/ogr/data/gml/aixm_ElevatedCurve.xml
- autotest/ogr/data/gml/aixm_VerticalStructure_mix_point_and_line.xml
- autotest/ogr/ogr_gml.py
- ogr/gml2ogrgeometry.cpp
- ogr/ogrsf_frmts/gml/gmlhandler.cpp
- ogr/ogrsf_frmts/gml/gmlreaderp.h
> [Backport release/3.10] GML: add support for AIXM ElevatedCurve

- CMakeLists.txt
- autotest/ogr/ogr_gml.py
- ogr/ogrsf_frmts/gml/ogr_gml.h
- ogr/ogrsf_frmts/gml/ogrgmldatasource.cpp
- ogr/ogrsf_frmts/gml/ogrgmllayer.cpp
- swig/include/Dataset.i
- swig/include/java/gdal_java.i
- swig/include/python/gdal_python.i
- swig/java/apps/GDALTestIO.java
and also fix issues in Python and Java bindings related to Dataset.Close()
> GML: detect and report write error

- .github/workflows/alpine/Dockerfile.ci
- .github/workflows/alpine_32bit/Dockerfile.ci
- .github/workflows/fedora_rawhide/Dockerfile.ci
- .github/workflows/icc/Dockerfile.ci
- .github/workflows/s390x/Dockerfile.ci
- .github/workflows/ubuntu_20.04/Dockerfile.ci
- .github/workflows/ubuntu_22.04/Dockerfile.ci
- .github/workflows/ubuntu_24.04/Dockerfile.ci
- swig/python/gdal-utils/test-bdist-install.sh.txt
Dependabot is supposed to update the pins
> CI: Dockerfiles: pin FROM to please OpenSSF ScoreCard

- doc/source/sponsors/index.rst
Backport #11454
**Authored by:** @hobu
> [Backport release/3.10] Update T-Kartor sponsorship name

- apps/ogrinfo_lib.cpp
Backport #11462
**Authored by:** @jratike80
> [Backport release/3.10] Ogrinfo: command line help text fixes

- frmts/pdf/pdfsdk_headers_poppler.h
Cf https://github.com/conda-forge/gdal-feedstock/pull/1019#issuecomment-2528710051
> PDF: fix build issue on CondaForge build infrastructure (gcc 13.3)

- frmts/pdf/pdfsdk_headers_poppler.h
> [Backport release/3.10] PDF: fix build issue on CondaForge build infrastructure (gcc 13.3)

- autotest/ogr/ogr_geojson.py
- doc/source/drivers/vector/geojson.rst
- ogr/ogrsf_frmts/geojson/ogr_geojson.h
- ogr/ogrsf_frmts/geojson/ogrgeojsondatasource.cpp
- ogr/ogrsf_frmts/geojson/ogrgeojsondriver.cpp
Implementation of RFC 103 - OGR_SCHEMA open option for GeoJSON driver
https://gdal--11071.org.readthedocs.build/en/11071/development/rfc/rfc103_schema_open_option.html
> [GeoJSON] OGR_SCHEMA open option implementation

- autotest/gcore/tiff_read.py
- gcore/gdalmultidomainmetadata.cpp
> Do not sort items in IMD metadata domain

- autotest/gcore/tiff_read.py
- gcore/gdalmultidomainmetadata.cpp
> [Backport release/3.10] Do not sort items in IMD metadata domain

- autotest/gdrivers/data/dimap2/vhr2020_ms_fs/MS-FS/DIM_MS-FS.XML
- autotest/gdrivers/dimap.py
- frmts/dimap/dimapdataset.cpp
> DIMAP: read FWHM values from DIMAP2 XML files (PNEO products)

- doc/source/development/rfc/index.rst
- doc/source/development/rfc/rfc104_gdal_cli.rst
<s>This is *very* preliminary (not backed by any coding), but I hope to get early feedback if it is aiming in the right direction.</s>Preliminary implementation now available
[Rendered version](https://gdal--11216.org.readthedocs.build/en/11216/development/rfc/rfc104_gdal_cli.html)
> Add text for RFC 104: Adding a "gdal" front-end command line interface

- port/cpl_vsil_curl.cpp
Cf https://github.com/rasterio/rasterio/pull/3276#issuecomment-2543169811
> Doc: clarify VSICurlPartialClearCache()

- port/cpl_vsil_curl.cpp
> [Backport release/3.10] Doc: clarify VSICurlPartialClearCache()

- doc/source/download.rst
Fix typo in URL formatting
* OS:
* Compiler:
> Fix URL display

- doc/source/download.rst
Backport #11505
**Authored by:** @DelazJ
> [Backport release/3.10] Fix URL display

- autotest/ogr/ogr_sqlite.py
- doc/source/drivers/vector/sqlite.rst
- ogr/ogrsf_frmts/sqlite/ogrsqlitebase.h
- ogr/ogrsf_frmts/sqlite/ogrsqlitedatasource.cpp
- ogr/ogrsf_frmts/sqlite/ogrsqlitedriver.cpp
- ogr/ogrsf_frmts/sqlite/ogrsqlitelayer.cpp
Implementation of RFC 103 - OGR_SCHEMA open option for SQLite driver
https://gdal--11071.org.readthedocs.build/en/11071/development/rfc/rfc103_schema_open_option.html
> [sqlite] OGR_SCHEMA implementation - RFC 103

- autotest/ogr/ogr_gml.py
- ogr/ogrsf_frmts/gmlutils/gmlutils.cpp
> GML: honour SWAP_COORDINATES=YES even when the geometry has no SRS

- ogr/ogrsf_frmts/ogrsf_frmts.dox
> [Backport release/3.10] Doc: OGRLayer::DeleteField(): add note about OGRFieldDefn* life-time

- autotest/gcore/misc.py
- gcore/gdal.h
- gcore/gdal_priv.h
- gcore/gdaldriver.cpp
- swig/include/Driver.i
Add a function to check whether an open option is supported by the driver.
> [gdal][api] GDALDriverHasOpenOption

- autotest/ogr/ogr_vrt.py
- ogr/ogrsf_frmts/vrt/ogrvrtlayer.cpp
> OGR VRT: fix SrcRegion.clip at OGRVRTLayer level

- ogr/ogrsf_frmts/parquet/ogrparquetwriterlayer.cpp
Cf https://github.com/OSGeo/gdal/issues/11418#issuecomment-2567155935
> Parquet writer: write page index

- autotest/gcore/tiff_read.py
- frmts/gtiff/gtiffdataset.h
- frmts/gtiff/gtiffdataset_read.cpp
- frmts/gtiff/gtiffdataset_write.cpp
- frmts/gtiff/gtiffrasterband_read.cpp
- frmts/gtiff/gtiffrgbaband.cpp
> [Backport release/3.10] GTiff: more robust handling of I/O errors in network optimized code paths

- ogr/ogrsf_frmts/parquet/ogrparquetwriterlayer.cpp
> [Backport release/3.10] Parquet writer: write page index

- autotest/osr/osr_xml.py
cf https://github.com/OSGeo/gdal/actions/runs/12615376646/job/35155360375?pr=11572
> autotest: fix 'DeprecationWarning: 'count' is passed as positional argument'

- autotest/gcore/vsicurl.py
- doc/source/user/virtual_file_systems.rst
- port/cpl_vsil_curl.cpp
> /vsicurl?: accept header.<key>=<value> to specify HTTP request headers

- doc/source/faq.rst
> Doc: faq.rst: add a paragraph about 3D models

- apps/CMakeLists.txt
- apps/gdalalg_raster.cpp
- apps/gdalalg_raster_buildvrt.cpp
- apps/gdalalg_raster_buildvrt.h
- autotest/cpp/test_cpl.cpp
- autotest/utilities/test_gdalalg_raster_buildvrt.py
- autotest/utilities/test_gdalalg_raster_edit.py
- doc/source/api/cpl.rst
- doc/source/conf.py
- doc/source/programs/gdal_raster.rst
- doc/source/programs/gdal_raster_buildvrt.rst
- doc/source/programs/index.rst
- gcore/gdalalgorithm.cpp
- gcore/gdalalgorithm.h
- port/cpl_string.h
- port/cpl_vsi.h
- port/cpl_vsil.cpp
- swig/include/Algorithm.i
- swig/include/python/gdal_python.i
Equivalent of gdalbuildvrt (not all options ported)
@hobu With the addition of VSIGlob(), "gdal raster buildvrt /vsis3/my_bucket/*.tif out.vrt" works
> Add 'gdal raster buildvrt'

- fuzzers/CMakeLists.txt
- fuzzers/build_google_oss_fuzzers.sh
- fuzzers/gdal_fuzzer.cpp
> fuzzers: add a fuzzer for LIBERTIFF driver

- autotest/ogr/ogr_gml_geom.py
- ogr/gml2ogrgeometry.cpp
- ogr/ogr_p.h
> GML2OGRGeometry: report gml:id of geometry in error messages

- doc/source/drivers/raster/gtiff.rst
Backport #11603
**Authored by:** @msmitherdc
> [Backport release/3.10] update reference since link is no longer available

- doc/source/api/gdal_fwd.rst
- doc/source/api/index.rst
- gcore/CMakeLists.txt
- gcore/gdal.h
- gcore/gdal_fwd.h
- gnm/gnm_api.h
- ogr/ogr_api.h
- ogr/ogr_feature.h
- ogr/ogr_geometry.h
- ogr/ogr_srs_api.h
- swig/include/Dataset.i
- swig/include/MultiDimensional.i
- swig/include/Operations.i
- swig/include/gnm.i
- swig/include/ogr.i
- swig/include/osr.i
> Add a gdal_fwd.h public header with forward definitions of GDAL/OGR/OSR C opaque types

- swig/include/python/gdal_python.i
Backport #11630
**Authored by:** @zabop
> [Backport release/3.10] Typofix

- swig/python/CMakeLists.txt
- swig/python/install_python.cmake.in
> Python bindings: on Debian, fix install target with non-Debian provided python version

- ogr/ogrsf_frmts/parquet/ogrparquetdriver.cpp
> [Backport release/3.10] Parquet: fix compiler deprecation warning with libarrow 19.0

- ci/travis/conda/setup.sh
> CI gdal-master conda: patch version number to X.Y.99

- cmake/modules/packages/FindECW.cmake
> [ecw] Link to -framework Foundation on macos

- .github/ISSUE_TEMPLATE/10_bug_report.yml
Rationale: https://github.com/OSGeo/gdal/issues/11693#issuecomment-2602847660
> Issue template: ask users to declare their potential use of AI [ci skip]

- apps/ogrlineref.cpp
- apps/ogrtindex.cpp
- autotest/utilities/test_ogrlineref.py
> ogrlineref: make -f LIBKML to work without warning

- doc/source/user/raster_data_model.rst
> Update 'SUBDATASETS Domain' in raster_data_model.rst

- frmts/plmosaic/plmosaicdataset.cpp
- port/cpl_known_config_options.h
Currently, it's unclear if the PLMosaic driver sees significant usage and the driver could be considered for removal to simplify maintenance.  There are many other ways to accomplish similar functionality to the PLMosaic driver that are not Planet-specific (e.g. the WMTS and WMS drivers).  While it is clear that gdal is used with the Planet Basemaps API, it's currently not possible to distinguish from more general gdal usage and the PLMosaic driver specifically.  Therefore, this PR changes the PLMosaic driver to use a different user agent string than the gdal default unless a custom user agent is configured via GDAL_HTTP_USERAGENT.  The WMS driver has similar logic, and there is precedent for some drivers using a different user agent string than gdal-at-large.
Provide environment details, …
> PLMosaic Driver: Use a unique user-agent string to isolate usage of driver

- doc/source/development/building_from_source.rst
> Doc: CMake: mention that disabling the use of a package does not disable its detection

- autotest/gcore/misc.py
As discussed in https://github.com/OSGeo/gdal/pull/11718#discussion_r1934452493
> autotest: split update metadata testing out of test_misc_6

- autotest/gdrivers/data/stacit/test_stac_1.1.json
- autotest/gdrivers/stacit.py
- frmts/stacit/stacitdataset.cpp
> STACIT: STAC 1.1 support

- doc/source/programs/gdal.rst
- doc/source/programs/index.rst
- doc/source/programs/migration_guide_to_gdal_cli.rst
> Doc: add a Migration guide to "gdal" command line interface, and show examples of bash completion

- ogr/ogrsf_frmts/miramon/mm_wrlayr.c
> [Backport release/3.10] MiraMonVector: Fix issue 393742177 oss-fuzz

- autotest/ogr/ogr_mvt.py
- doc/source/drivers/vector/mvt.rst
- ogr/ogrsf_frmts/mvt/ogrmvtdataset.cpp
> MVT: allow generating tilesets with more than 1 tile at zoom level 0

- doc/source/drivers/raster/wms.rst
- frmts/wms/frmt_ags_arcgisonline.xml
- frmts/wms/minidriver_arcgis_server.h
Update several broken or moved links for ESRI MapServer API documentation and some links to a now-defunct ESRI sample server.
None
> Docs: Update ESRI WMS links

- doc/source/drivers/raster/wms.rst
- frmts/wms/frmt_ags_arcgisonline.xml
- frmts/wms/minidriver_arcgis_server.h
Backport #11789
**Authored by:** @DFEvans
> [Backport release/3.10] Docs: Update ESRI WMS links

- alg/gdal_alg_priv.h
- alg/gdalrasterize.cpp
- alg/llrasterize.cpp
- apps/gdal_rasterize_lib.cpp
Adds some comments, usage of `unique_ptr`, removes some use of `void*`
> rasterize: Minor readability improvements

- swig/python/modify_cpp_files.cmake
> [Backport release/3.10] SWIG: Avoid losing error message

- autotest/gdrivers/pdf.py
- frmts/pdf/pdfdataset.cpp
- frmts/pdf/pdfio.cpp
- frmts/pdf/pdfio.h
- frmts/pdf/pdfobject.cpp
- frmts/pdf/pdfobject.h
- frmts/pdf/pdfsdk_headers_poppler.h
> Build: fix build against Poppler 25.02.00

- apps/ogr2ogr_lib.cpp
- autotest/ogr/ogr_mvt.py
- frmts/vrt/vrtexpression.h
- gcore/gdal_priv.h
- gcore/gdal_priv_templates.hpp
- ogr/ogrsf_frmts/sqlite/ogrsqlitedatasource.cpp
- port/cpl_float.h
- scripts/typos_allowlist.txt
as raised by scripts/fix_typos.sh
> Code typo fixes

- apps/ogrlineref.cpp
- apps/ogrtindex.cpp
- autotest/utilities/test_ogrlineref.py
Backport of https://github.com/OSGeo/gdal/pull/11722
> [Backport 3.10] ogrlineref: make -f LIBKML to work without warning

- .github/workflows/android_cmake.yml
- .github/workflows/cmake_builds.yml
- .github/workflows/conda.yml
- .github/workflows/linux_build.yml
- .github/workflows/slow_tests.yml
> [Backport 3.10] CI: update to actions/cache@v4.2.0

- fuzzers/build.sh
@eschnett do you have rights to approve this PR ?
> Fix ossfuzz builds after RFC100 changes [ci skip]

- doc/source/development/rfc/index.rst
- doc/source/development/rfc/rfc107_igetextent_isetspatialfilter.rst
[Rendered view](https://gdal--11814.org.readthedocs.build/en/11814/development/rfc/rfc107_igetextent_isetspatialfilter.html)
> Add RFC107 text: Add OGRLayer::IGetExtent() and OGRLayer::ISetSpatialFilter()

- autotest/gcore/cog.py
- frmts/gtiff/gtiffdataset_write.cpp
> GTiff: CreateCopy(): fix incorrect writing of mask band when COPY_SRC_OVERVIEWS=YES and INTERLEAVE=BAND (master only)

- doc/source/_extensions/driverproperties.py
> Doc: fix doc building with sphinx 8.2.0

- frmts/zarr/zarrdrivercore.cpp
> Zarr: declare GDAL_DMD_EXTENSION=zarr

- autotest/ogr/data/csv/unbalanced_double_quotes.csv
- autotest/ogr/ogr_csv.py
- port/cpl_csv.cpp
> CSV: emit error when unbalanced double quotes are detected

- doc/source/_extensions/sphinxcontrib_programoutput_gdal.py
- doc/source/drivers/raster/bag.rst
- doc/source/drivers/raster/gti.rst
- doc/source/drivers/raster/netcdf.rst
- doc/source/drivers/raster/vrt_processed_dataset.rst
- doc/source/drivers/raster/wms_wmts_cache.rst
- doc/source/drivers/vector/filegdb.rst
- doc/source/drivers/vector/flatgeobuf.rst
- doc/source/drivers/vector/libkml.rst
- doc/source/drivers/vector/openfilegdb.rst
- doc/source/drivers/vector/pgeo.rst
- doc/source/programs/gdal_edit.rst
- doc/source/software_using_gdal.rst
- doc/source/tutorials/vector_api_tut.rst
- doc/source/tutorials/wktproblems.rst
- doc/source/user/virtual_file_systems.rst
```
codespell --version
2.3.0
```
Skipped the rfc tree.
> doc: codespell [ci skip]

- doc/source/development/rfc/rfc33_gtiff_pixelispoint.rst
- doc/source/development/rfc/rfc3_commiters.rst
- doc/source/development/rfc/rfc40_enhanced_rat_support.rst
- doc/source/development/rfc/rfc46_gdal_ogr_unification.rst
- doc/source/development/rfc/rfc5_unicode.rst
- doc/source/development/rfc/rfc6_sqlgeom.rst
- doc/source/development/rfc/rfc71_github_migration.rst
- doc/source/development/rfc/rfc76_ogrpythondrivers.rst
- doc/source/development/rfc/rfc83_use_of_project_sponsorship.rst
- doc/source/development/rfc/rfc86_column_oriented_api.rst
- doc/source/development/rfc/rfc91_dataset_close.rst
- doc/source/development/rfc/rfc92_wkb_only_geometries.rst
Trivial fixes.
```
codespell --version
2.3.0
```
> doc rfc: codespell [ci skip]

- ogr/ogrsf_frmts/cad/libopencad/cadlayer.cpp
Fix build in the case when iterators are raw pointers.
> Add missing std qualifiers

- frmts/mbtiles/mbtilesdataset.cpp
> [Backport release/3.10] MBTiles: Fix update with WEBP compression

- ogr/ogrsf_frmts/cad/libopencad/cadlayer.cpp
Backport #11879
**Authored by:** @georgthegreat
> [Backport release/3.10] Add missing std qualifiers

- doc/source/drivers/vector/pmtiles.rst
Backport #11912
**Authored by:** @springmeyer
> [Backport release/3.10] doc: update tile terminology in pmtiles.rst

- gcore/overview.cpp
> GDALResampleChunk_ConvolutionT(): avoid casting NaN to int64_t

- autotest/gcore/misc.py
- port/cpl_error.cpp
- port/cpl_error.h
- swig/include/cpl.i
- swig/include/python/gdal_python.i
- swig/include/python/typemaps_python.i
As discussed in https://github.com/OSGeo/gdal/pull/11896#discussion_r1976500777
> Add CPLQuietWarningsErrorHandler

- swig/include/python/docs/osr_coordinatetransformation_docs.i
- swig/include/python/osr_python.i
> Doc: Fix axis order of points in osr.CoordinateTransformation examples

- frmts/pdf/pdfdataset.cpp
- frmts/pdf/pdfio.cpp
- frmts/pdf/pdfio.h
- frmts/pdf/pdfobject.cpp
> [Backport release/3.10] Fix warnings when building against Poppler 25.03.00

- doc/source/programs/gdal_translate.rst
- doc/source/programs/gdalmdimtranslate.rst
- doc/source/programs/options/co.rst
- doc/source/programs/raster_common_options.rst
> Doc: Fix link to --format from -co description

- port/cpl_http.cpp
This fixes the same issue as
https://github.com/OSGeo/PROJ/pull/4419 fixes
in PROJ.
#9571 
* OS:
* Compiler:
> cpl_http: retry "SSL connection timeout"

- autotest/gdrivers/netcdf.py
- autotest/gdrivers/zarr_driver.py
- doc/source/drivers/raster/netcdf.rst
- doc/source/drivers/raster/zarr.rst
- frmts/netcdf/netcdfdataset.cpp
- frmts/netcdf/netcdfdrivercore.cpp
- frmts/zarr/zarrdriver.cpp
- frmts/zarr/zarrdrivercore.cpp
> Zarr: report array dimension in subdataset list;  Zarr+netCDF: add a LIST_ALL_ARRAYS open option that defaults to NO

- apps/gdalalg_raster_reproject.cpp
- apps/gdalalg_raster_reproject.h
- autotest/utilities/test_gdalalg_raster_reproject.py
- doc/source/programs/gdal_raster_reproject.rst
> gdal reproject: add a --size argument, add --bbox-crs as well

- apps/CMakeLists.txt
- apps/gdalalg_raster.cpp
- apps/gdalalg_raster_pipeline.cpp
- apps/gdalalg_raster_reproject.cpp
- apps/gdalalg_raster_resize.cpp
- apps/gdalalg_raster_resize.h
- autotest/utilities/test_gdalalg_raster_resize.py
- doc/source/conf.py
- doc/source/programs/gdal_raster.rst
- doc/source/programs/gdal_raster_pipeline.rst
- doc/source/programs/gdal_raster_reproject.rst
- doc/source/programs/gdal_raster_resize.rst
- doc/source/programs/index.rst
> Add gdal raster resize

- autotest/ogr/ogr_wfs.py
- ogr/ogrsf_frmts/wfs/ogrwfslayer.cpp
> [Backport release/3.10] WFS: fix crash with GetFeatureCount() and client-side filters

- autotest/ogr/ogr_sql_test.py
- ogr/CMakeLists.txt
- ogr/ogr_swq.h
- ogr/swq_expr_node.cpp
- ogr/swq_parser.cpp
- ogr/swq_parser.y
Fixes https://issues.oss-fuzz.com/issues/402248411
> OGR SQL: prevent building too deep expression that can cause stack overflow when destroying them

- ogr/ogrsf_frmts/miramon/mm_gdal_functions.c
> [Backport release/3.10] MiraMonVector: fixing a word in Catalan language

- autotest/gcore/mask.py
- autotest/gdrivers/vrtwarp.py
- frmts/vrt/vrtdataset.h
- frmts/vrt/vrtwarped.cpp
- gcore/gdal_priv.h
- gcore/gdalallvalidmaskband.cpp
- gcore/gdalnodatamaskband.cpp
- gcore/gdalnodatavaluesmaskband.cpp
- gcore/gdalrasterband.cpp
- gcore/gdalrescaledalphaband.cpp
> gcore: add more explicit error message when attempting to write an implicit mask band

- ogr/ogrsf_frmts/miramon/mm_gdal_driver_structs.h
- ogr/ogrsf_frmts/miramon/mm_wrlayr.c
- ogr/ogrsf_frmts/miramon/ogrmiramonlayer.cpp
> [Backport release/3.10] MiraMonVector: writting VRS in metadata file + fixing error in Z header

- ogr/ogrsf_frmts/mssqlspatial/ogrmssqlspatialdatasource.cpp
> [Backport release/3.10] [mssqlspatial] Fix creation of metadata tables

- autotest/ogr/ogr_geojson.py
- ogr/ogrgeojsongeometry.cpp
- ogr/ogrsf_frmts/geojson/ogrgeojsonreader.cpp
> GeoJSON geometry reading: issue more warnings when invalid constructs are found

- doc/source/development/dev_documentation.rst
Minor changes to the docs following a review and run through of the docs build process. 
cc @dbaston
> Docs: Minor fixes to typos and formatting for the docs development page

- autotest/ogr/data/gmlas/choice_double_inlined.xml
- autotest/ogr/data/gmlas/choice_double_inlined.xsd
- autotest/ogr/data/gmlas/choice_int64_inlined.xml
- autotest/ogr/data/gmlas/choice_int64_inlined.xsd
- autotest/ogr/data/gmlas/choice_int_inlined.xml
- autotest/ogr/data/gmlas/choice_int_inlined.xsd
- autotest/ogr/data/gmlas/choice_str_inlined.xml
- autotest/ogr/data/gmlas/choice_str_inlined.xsd
- autotest/ogr/ogr_gmlas.py
- ogr/ogrsf_frmts/gmlas/ogrgmlasreader.cpp
> GMLAS: fix reading multiple values of a StringList field that is a repeated element

- autotest/ogr/data/gmlas/choice_double_inlined.xml
- autotest/ogr/data/gmlas/choice_double_inlined.xsd
- autotest/ogr/data/gmlas/choice_int64_inlined.xml
- autotest/ogr/data/gmlas/choice_int64_inlined.xsd
- autotest/ogr/data/gmlas/choice_int_inlined.xml
- autotest/ogr/data/gmlas/choice_int_inlined.xsd
- autotest/ogr/data/gmlas/choice_str_inlined.xml
- autotest/ogr/data/gmlas/choice_str_inlined.xsd
- autotest/ogr/ogr_gmlas.py
- ogr/ogrsf_frmts/gmlas/ogrgmlasreader.cpp
> [Backport release/3.10] GMLAS: fix reading multiple values of a StringList field that is a repeated element

- autotest/ogr/ogr_parquet.py
- frmts/pcidsk/sdk/port/io_win32.cpp
- ogr/ogrsf_frmts/mssqlspatial/ogr_mssqlspatial.h
- ogr/ogrsf_frmts/oci/ogr_oci.h
- ogr/ogrsf_frmts/ogrsf_frmts.h
- ogr/ogrsf_frmts/parquet/ogrparquetdataset.cpp
- ogr/ogrsf_frmts/s57/s57.h
- scripts/cppcheck.sh
> Parquet: honor MIN()/MAX() field alias

- apps/data/gdal_algorithm.schema.json
- apps/gdalalg_raster_contour.cpp
- apps/gdalalg_raster_hillshade.cpp
- apps/gdalalg_raster_info.cpp
- apps/gdalalg_raster_overview_add.cpp
- apps/gdalalg_raster_reproject.cpp
- apps/gdalalg_raster_resize.cpp
- apps/gdalalg_raster_slope.cpp
- apps/gdalalg_vector_geom_buffer.cpp
- apps/gdalalg_vector_geom_segmentize.cpp
- apps/gdalalg_vector_geom_simplify.cpp
- autotest/cpp/test_gdal_algorithm.cpp
- autotest/utilities/test_gdalalg_raster_contour.py
- autotest/utilities/test_gdalalg_raster_pipeline.py
- autotest/utilities/test_gdalalg_vector_geom_segmentize.py
- autotest/utilities/test_gdalalg_vector_geom_simplify.py
- gcore/gdalalgorithm.cpp
- gcore/gdalalgorithm.h
and use it in existing algorithms
> GDALArgument: add Set[Min|Max][Included|Excluded]() to set allowed range

- alg/gdal_interpolateatpoint.cpp
- apps/gdallocationinfo.cpp
- autotest/gcore/interpolateatpoint.py
- autotest/utilities/test_gdallocationinfo.py
Applied on top of https://github.com/OSGeo/gdal/pull/12080
As discussed in https://github.com/OSGeo/gdal/pull/12080#discussion_r2028790673
> gdallocationinfo: Allow querying raster corner points

- apps/gdal_translate_lib.cpp
> gdal_translate: store srcWin in struct instead of array

- doc/source/faq.rst
- doc/source/user/virtual_file_systems.rst
- port/cpl_vsi.h
Credit to @jratike80 for uncovering
https://lists.osgeo.org/pipermail/gdal-dev/2005-September/006426.html
> Doc: document VSI meaning: Virtual System Interface

- frmts/tiledb/tiledbsparse.cpp
Fixes a typo in an error message.
* OS:
* Compiler:
> tiledbsparse: fix typo in error message

- autotest/ogr/ogr_geojson.py
- ogr/ogrsf_frmts/sqlite/ogr_sqlite.h
- ogr/ogrsf_frmts/sqlite/ogrsqlitetablelayer.cpp
- ogr/ogrsf_frmts/sqlite/ogrsqlitevirtualogr.cpp
Fixes https://lists.osgeo.org/pipermail/gdal-dev/2025-April/060433.html
> SQLite dialect: fix when a field has the same name as the FID column

- apps/gdal.cpp
- apps/gdalalg_main.cpp
- autotest/cpp/test_cpl.cpp
- autotest/cpp/test_gdal_algorithm.cpp
- autotest/utilities/test_gdal.py
- autotest/utilities/test_gdalalg_convert.py
- autotest/utilities/test_gdalalg_info.py
- autotest/utilities/test_gdalalg_raster_pipeline.py
- autotest/utilities/test_gdalalg_vector_pipeline.py
- gcore/gdalalgorithm.cpp
- gcore/gdalalgorithm.h
- port/CMakeLists.txt
- port/cpl_levenshtein.cpp
- port/cpl_levenshtein.h
- scripts/typos_allowlist.txt
Demo:
```
$ gdal rastr
ERROR 1: Algorithm 'rastr' is unknown. Do you mean 'raster'?
$ gdal raster nifo
ERROR 1: Algorithm 'nifo' is unknown. Do you mean 'info'?
$ gdal raster info --frmt=json
ERROR 5: info: Option '--frmt' is unknown. Do you mean '--format'?
```
> GDALAlgorithm: add suggestion for bad algorithm/argument name based on Damerau-Levenshtein distance

- gcore/gdalnodatamaskband.cpp
- gcore/gdalrasterband.cpp
Cf https://lists.osgeo.org/pipermail/gdal-dev/2025-April/060462.html
> Fix build issues with isnan() on GFloat16

- doc/source/drivers/vector/gpkg.rst
Fix small typo reported on IRC by ville.
> Doc: Fix typo in GPKG docs [ci skip]

- autotest/cpp/test_gdal_algorithm.cpp
- gcore/gdalalgorithm.h
Fixes Coverity 1592298 "uncaught exception"
> GDALInConstructionAlgorithmArg::SetDefault(): stricter type checking

- apps/gdalalg_dispatcher.h
- autotest/utilities/test_gdalalg_convert.py
> gdal convert: better error message if input file cannot be opened

- apps/gdalalg_raster_pipeline.cpp
- apps/gdalalg_raster_polygonize.cpp
- apps/gdalalg_vector_convert.cpp
- apps/gdalalg_vector_output_abstract.cpp
- apps/gdalalg_vector_pipeline.cpp
- apps/gdalalg_vector_rasterize.cpp
- autotest/cpp/test_gdal_algorithm.cpp
- autotest/gcore/algorithm.py
- autotest/ogr/ogr_pg.py
- doc/source/development/rfc/rfc104_gdal_cli.rst
- gcore/gdalalgorithm.cpp
- gcore/gdalalgorithm.h
- swig/include/Algorithm.i
- swig/include/gdalconst.i
Fixes https://lists.osgeo.org/pipermail/gdal-dev/2025-April/060482.html
> gdal vector pipeline: make sure read step opens in vector mode

- apps/gdalalg_raster_fillnodata.cpp
- autotest/utilities/test_gdalalg_raster_fillnodata.py
Use uncompressed temp file if needed.
Fix #12215
> [cli] gdal raster fillnodata - optimization

- apps/gdalalg_abstract_pipeline.h
- apps/gdalalg_raster_calc.cpp
- apps/gdalalg_raster_contour.cpp
- apps/gdalalg_raster_create.cpp
- apps/gdalalg_raster_fillnodata.cpp
- apps/gdalalg_raster_mosaic.cpp
- apps/gdalalg_raster_polygonize.cpp
- apps/gdalalg_raster_stack.cpp
- apps/gdalalg_raster_viewshed.cpp
- apps/gdalalg_vector_grid.cpp
- apps/gdalalg_vector_output_abstract.cpp
- apps/ogr2ogr_lib.cpp
- autotest/utilities/test_gdalalg_vector_convert.py
- autotest/utilities/test_gdalalg_vector_grid.py
- gcore/gdal_misc.cpp
- gcore/gdal_priv.h
> gdal vector convert: do not emit error message when outputting to /vsistdout/

- apps/gdalalg_mdim_convert.cpp
- apps/gdalalg_mdim_info.cpp
- apps/gdalalg_raster_create.cpp
- apps/gdalalg_raster_edit.cpp
- apps/gdalalg_raster_index.cpp
- apps/gdalalg_raster_reproject.cpp
- apps/gdalalg_vector_edit.cpp
- autotest/cpp/test_gdal_algorithm.cpp
- gcore/gdalalgorithm.cpp
- gcore/gdalalgorithm.h
Fixes https://lists.osgeo.org/pipermail/gdal-dev/2025-April/060489.html
> gdal cli: improve tokenization of creation options to avoid detecting FOO=BAR,BAZ as 2 options

- doc/source/programs/gdalwarp.rst
Fix a typo in gdalwarp documentation
None
NA
NA
NA
> gdalwarp docs: fix a typo in gdalwarp.rst

- gcore/gdal_vectorx.h
Tries to fix https://lists.osgeo.org/pipermail/gdal-dev/2025-April/060490.html
> gdal_vectorx.h: try to fix compatibility with gcc 8.5.0

- apps/CMakeLists.txt
- apps/gdalalg_raster.cpp
- apps/gdalalg_raster_pipeline.cpp
- apps/gdalalg_raster_set_type.cpp
- apps/gdalalg_raster_set_type.h
- autotest/utilities/test_gdalalg_raster_set_type.py
- doc/source/conf.py
- doc/source/programs/gdal_raster_pipeline.rst
- doc/source/programs/gdal_raster_set_type.rst
- doc/source/programs/index.rst
for consistency with `gdal vector geom set-type`
> Rename gdal raster astype to gdal raster set-type

- apps/gdalalg_main.cpp
- apps/gdalalg_main.h
- apps/gdalalg_mdim.cpp
- apps/gdalalg_raster.cpp
- apps/gdalalg_vector.cpp
- autotest/utilities/test_gdal.py
- autotest/utilities/test_gdalalg_mdim.py
- autotest/utilities/test_gdalalg_vector.py
- doc/source/programs/gdal_info.rst
- doc/source/programs/gdal_mdim.rst
- doc/source/programs/gdal_raster.rst
- gcore/gdal_misc.cpp
- gcore/gdal_priv.h
- gcore/gdalalgorithm.cpp
- swig/include/python/gdal_python.i
> Add 'gdal raster|vector|mdim --drivers'

- apps/gdalalg_raster_calc.cpp
- apps/gdalalg_raster_contour.cpp
- apps/gdalalg_raster_fill_nodata.cpp
- apps/gdalalg_raster_mosaic.cpp
- apps/gdalalg_raster_stack.cpp
- apps/gdalalg_raster_viewshed.cpp
- autotest/utilities/test_gdalalg_raster_calc.py
- doc/source/programs/gdal_raster_calc.rst
> gdal raster calc: add support for GDALG output

- apps/gdalalg_abstract_pipeline.h
- autotest/gdrivers/gdalg.py
- gcore/gdalalgorithm.cpp
- gcore/gdalalgorithm.h
as already done for non-pipeline GDALG capable algorithms
> gdal raster/vector pipeline to .gdalg.json: add 'gdal_version' member

- apps/gdalalg_abstract_pipeline.h
- autotest/gdrivers/gdalg.py
- gcore/gdalalgorithm.cpp
- gcore/gdalalgorithm.h
> [Backport release/3.11] gdal raster/vector pipeline to .gdalg.json: add 'gdal_version' member

- autotest/gdrivers/gti.py
- ogr/ogrsf_frmts/gpkg/gdalgeopackagerasterband.cpp
- ogr/ogrsf_frmts/gpkg/ogrgeopackagedatasource.cpp
- ogr/ogrsf_frmts/gpkg/ogrgeopackagetablelayer.cpp
- ogr/ogrsf_frmts/sqlite/ogrsqliteutility.cpp
- ogr/ogrsf_frmts/sqlite/ogrsqliteutility.h
> GPKG: call sqlite3_errmsg() in error messages

- autotest/utilities/test_gdalalg_raster_info.py
- gcore/gdalalgorithm.cpp
> GDALAlgorithm: fix reading a .gdalg.json dataset with 'GDALG' input format option specified

- doc/source/programs/gdal_raster_tile.rst
small typo fix in gdal_raster_tile.rst
> gdal_raster_tile.rst: tiny fix max zoom

- doc/source/programs/gdal_raster_tile.rst
Backport #12319
**Authored by:** @mdsumner
> [Backport release/3.11] gdal_raster_tile.rst: tiny fix max zoom

- doc/source/api/index.rst
- doc/source/api/ogrgeomcoordinateprecision_cpp.rst
- doc/source/api/ogrgeometry_cpp.rst
- doc/source/drivers/vector/geojsonseq.rst
- doc/source/programs/gdal_raster_hillshade.rst
- doc/source/programs/gdal_raster_slope.rst
- doc/source/programs/gdaldem.rst
- doc/source/user/multithreading.rst
- doc/source/user/ogr_sql_sqlite_dialect.rst
- doc/source/user/vector_data_model.rst
- ogr/ogr_geomcoordinateprecision.h
found by setting ``nitpicky = True`` in conf.py
> Doc: fix (just a few) missing target references

- doc/source/api/csharp/csharp_compile_legacy.rst
- doc/source/community/index.rst
- doc/source/development/dev_practices.rst
- doc/source/development/rfc/rfc76_ogrpythondrivers.rst
- doc/source/development/rfc/rfc92_wkb_only_geometries.rst
- doc/source/drivers/raster/gdalg.rst
- doc/source/drivers/raster/wms.rst
- doc/source/drivers/vector/dxf.rst
- doc/source/drivers/vector/gdalg.rst
- doc/source/faq.rst
- doc/source/programs/gdalmdiminfo.rst
- doc/source/programs/ogrinfo.rst
> [Backport release/3.11] Doc: use :source_file: whereever possible

- doc/source/api/index.rst
- doc/source/api/ogrgeomcoordinateprecision_cpp.rst
- doc/source/api/ogrgeometry_cpp.rst
- doc/source/drivers/vector/geojsonseq.rst
- doc/source/programs/gdal_raster_hillshade.rst
- doc/source/programs/gdal_raster_slope.rst
- doc/source/programs/gdaldem.rst
- doc/source/user/multithreading.rst
- doc/source/user/ogr_sql_sqlite_dialect.rst
- doc/source/user/vector_data_model.rst
- ogr/ogr_geomcoordinateprecision.h
> [Backport release/3.11] Doc: fix (just a few) missing target references

- doc/source/development/dev_documentation.rst
CC @geographika @DelazJ   borrows content from Seth's note at https://github.com/OSGeo/gdal/pull/12335#issuecomment-2869659885
> dev_documentation.rst: make :source_file: custom directive more visible

- doc/source/programs/ogrmerge.rst
See https://github.com/OSGeo/gdal/issues/12292 .
P.S., I certainly got the link syntax wrong, especially the spaces. Please fix it for me. Thanks.
> Update ogrmerge.rst to mention gdal vector concat

- apps/gdaladdo.cpp
- autotest/utilities/test_gdaladdo.py
- autotest/utilities/test_gdalalg_raster_overview.py
- gcore/gdalalgorithm.cpp
Fixes https://lists.osgeo.org/pipermail/gdal-dev/2025-May/060558.html
> gdaladdo / gdal raster overview add/delete: avoid issues with COG

- gcore/gdal_minmax_element.hpp
Fixes https://github.com/OSGeo/gdal/issues/12192#issuecomment-2869854141
> gdal_minmax_element.hpp: fix build issue with ARM32 Neon optimizations

- autotest/gdrivers/hfa.py
- frmts/hfa/hfafield.cpp
Fixes https://lists.osgeo.org/pipermail/gdal-dev/2025-May/060534.html
> HFA: do not emit warning when reading NaN nodata value

- apps/gdalalg_raster_calc.cpp
- autotest/cpp/test_gdal_algorithm.cpp
- frmts/vrt/pixelfunctions.cpp
- frmts/vrt/vrtprocesseddatasetfunctions.cpp
- frmts/zarr/zarr_v2_array.cpp
- frmts/zarr/zarr_v3_array.cpp
- gcore/gdal_priv.h
- gcore/gdal_typetraits.h
- gcore/gdalcachedpixelaccessor.h
- gcore/gdalrasterband.cpp
Fixes #12338 
@dg0yt This should avoid the issue
> Do not include cpl_float.h in gdal_priv.h, to avoid issues on Windows  with min/max macros

- autotest/gdrivers/heif.py
- frmts/heif/heifdataset.cpp
- frmts/heif/heifdataset.h
Requires libheif >= 1.19.0
Fixes #12239
CC @bradh
> HEIF: implement request_range() reading callback, in particular for /vsicurl/ access

- autotest/gdrivers/wmts.py
- frmts/wms/gdalhttp.cpp
- frmts/wmts/wmtsdataset.cpp
- port/cpl_http.cpp
and handle conflict between Accept from WMTS XML document and GDAL_HTTP_HEADERS/GDAL_HTTP_HEADER_FILE
Fixes #12354
> WMTS: honor <Accept> when sending GetCapabilities response

- gcore/gdal_minmax_element.hpp
> [Backport release/3.11] gdal_minmax_element.hpp: fix build issue with ARM32 Neon optimizations

- apps/gdaladdo.cpp
- autotest/utilities/test_gdaladdo.py
- autotest/utilities/test_gdalalg_raster_overview.py
- gcore/gdalalgorithm.cpp
> [Backport release/3.11] gdaladdo / gdal raster overview add/delete: avoid issues with COG

- autotest/gdrivers/gdalg.py
- frmts/gdalg/gdalgdriver.cpp
- gcore/gdalalgorithm.cpp
> [Backport release/3.11] GDALG: do not Open() in update mode, and 100% code coverage

- apps/CMakeLists.txt
- apps/gdalalg_raster_overview.h
- apps/gdalalg_raster_overview_refresh.cpp
- apps/gdalalg_raster_overview_refresh.h
- autotest/utilities/test_gdalalg_raster_overview_refresh.py
- doc/source/conf.py
- doc/source/programs/gdal_raster_overview.rst
- doc/source/programs/gdal_raster_overview_refresh.rst
- doc/source/programs/index.rst
Port of last remaining parts of gdaladdo
> Add 'gdal raster overview refresh'

- autotest/gdrivers/wmts.py
- frmts/wms/gdalhttp.cpp
- frmts/wmts/wmtsdataset.cpp
- port/cpl_http.cpp
> [Backport release/3.11] WMTS: honor <Accept> when sending GetCapabilities response

- autotest/gcore/vsifile.py
- autotest/ogr/ogr_libkml.py
- ogr/ogrsf_frmts/libkml/ogrlibkmldrivercore.cpp
- ogr/ogrsf_frmts/libkml/ogrlibkmlfield.cpp
- port/cpl_minizip_zip.cpp
> [Backport release/3.11] ZIP filename warning suppression, and LIBKML warning suppression

- apps/CMakeLists.txt
- apps/gdalalg_raster.cpp
- apps/gdalalg_raster_rgb_to_palette.cpp
- apps/gdalalg_raster_rgb_to_palette.h
- apps/gdaldem_lib.cpp
- autotest/cpp/test_data.h
- autotest/cpp/test_gdal.cpp
- autotest/gcore/data/qgis_qml_paletted.qml
- autotest/gcore/data/qgis_qml_singlebandpseudocolor.qml
- autotest/utilities/test_gdalalg_raster_rgb_to_palette.py
- doc/source/conf.py
- doc/source/programs/gdal_raster.rst
- doc/source/programs/gdal_raster_rgb_to_palette.rst
- doc/source/programs/index.rst
- gcore/gdal_priv.h
- gcore/gdalcolortable.cpp
> Add 'gdal raster rgb-to-palette' (port of rgb2pct.py)

- apps/CMakeLists.txt
- apps/gdalalg_raster.cpp
- apps/gdalalg_raster_reproject.cpp
- apps/gdalalg_raster_reproject.h
- apps/gdalalg_raster_update.cpp
- apps/gdalalg_raster_update.h
- autotest/utilities/test_gdalalg_raster_reproject.py
- autotest/utilities/test_gdalalg_raster_update.py
- doc/source/conf.py
- doc/source/programs/gdal_options/warp_resampling.rst
- doc/source/programs/gdal_raster.rst
- doc/source/programs/gdal_raster_reproject.rst
- doc/source/programs/gdal_raster_update.rst
- doc/source/programs/index.rst
- doc/source/programs/migration_guide_to_gdal_cli.rst
- gcore/gdalalgorithm.h
- gcore/overview.cpp
This is the equivalent of "gdalwarp in.tif existing.tif".
I considered calling it 'patch' as an alternative. Thoughts ?
> Add 'gdal raster update'

- apps/CMakeLists.txt
- apps/gdalalg_vector.cpp
- apps/gdalalg_vector_edit.cpp
- apps/gdalalg_vector_geom_set_type.cpp
- apps/gdalalg_vector_layer_algebra.cpp
- apps/gdalalg_vector_layer_algebra.h
- autotest/utilities/test_gdalalg_vector_edit.py
- autotest/utilities/test_gdalalg_vector_geom_set_type.py
- autotest/utilities/test_gdalalg_vector_layer_algebra.py
- doc/source/conf.py
- doc/source/programs/gdal_vector.rst
- doc/source/programs/gdal_vector_layer_algebra.rst
- doc/source/programs/index.rst
- gcore/gdal_priv.h
- gcore/gdalalgorithm.cpp
- gcore/gdalalgorithm.h
- gcore/gdaldataset.cpp
- ogr/ogrsf_frmts/generic/ogrlayer.cpp
>  Add 'gdal vector layer-algebra' (port of ogr_layer_algebra.py)

- .github/workflows/doc_checks.yml
Should avoid unnoticed issue like the one of https://github.com/OSGeo/gdal/commit/a22ad0361e5ce88b6a481988c8a070b2ec29b04b
> CI: doc_checks.yml: build PDF

- apps/gdalalg_raster_footprint.cpp
- apps/gdalalg_raster_index.cpp
- apps/gdalalg_raster_mosaic.cpp
- apps/gdalalg_raster_mosaic.h
- apps/gdalalg_raster_stack.cpp
- apps/gdalalg_raster_stack.h
- apps/gdalbuildvrt_lib.cpp
- autotest/utilities/test_gdalalg_raster_mosaic.py
- autotest/utilities/test_gdalalg_raster_stack.py
- autotest/utilities/test_gdalbuildvrt_lib.py
- doc/source/programs/gdal_raster_mosaic.rst
- doc/source/programs/gdal_raster_stack.rst
- doc/source/programs/gdalbuildvrt.rst
- frmts/vrt/vrtdataset.cpp
- frmts/vrt/vrtdataset.h
- frmts/vrt/vrtdriver.cpp
- frmts/vrt/vrtprocesseddataset.cpp
- frmts/vrt/vrtsources.cpp
- gcore/gdalalgorithm.cpp
- gcore/gdalalgorithm.h
- swig/include/python/gdal_python.i
> gdalbuildvrt: add -write_absolute_path and  gdal raster mosaic/stack: add a --absolute-path option

- doc/source/drivers/raster/vrt.rst
> [Backport release/3.11] Doc: Clarify VRT handling of NoData

- apps/gdal.cpp
- autotest/utilities/test_gdal.py
> gdal CLI: fix handling of --format

- autotest/cpp/test_gdal_algorithm.cpp
- gcore/gdalalgorithm.cpp
> [Backport release/3.11] GDALAlgorithm: Raise error on malformed list arguments

- apps/gdalwarp_lib.cpp
- port/cpl_vsil_s3.cpp
> [Backport release/3.11] Enhance temporary file management when warping to COG on /vsis3/

- apps/gdalalg_abstract_pipeline.h
- apps/gdalalg_raster_pipeline.cpp
- apps/gdalalg_vector_pipeline.cpp
- autotest/utilities/test_gdalalg_raster_pipeline.py
- autotest/utilities/test_gdalalg_vector_pipeline.py
> gdal raster/vector pipeline: make --help act on the last pipeline step

- alg/gdal_homography.cpp
- autotest/alg/gcps2homography.py
- autotest/alg/homography.py
> GDALCreateHomographyTransformer(): emit CPLError()s when failures happen

- autotest/gcore/tiff_read.py
- port/cpl_vsil_curl.cpp
- port/cpl_vsil_curl_class.h
> VSICurlHandle::AdviseRead() (GTIFF multithreading /vsicurl/ reading): implement retry strategy

- alg/gdal_homography.cpp
- autotest/alg/gcps2homography.py
- autotest/alg/homography.py
> [Backport release/3.11] GDALCreateHomographyTransformer(): emit CPLError()s when failures happen

- doc/source/development/building_from_source.rst
> Add missed conda repo.

- frmts/vrt/vrtsources.cpp
- gcore/gdal.h
- gcore/gdaldataset.cpp
- gcore/gdalrasterband.cpp
- gcore/rasterio.cpp
Increase the version of RasterIO ExtraArg structure
#12461 
* OS:
* Compiler:
> GCORE: Increase version number for RasterIO ExtraArg structure

- apps/CMakeLists.txt
- apps/commonutils.cpp
- apps/commonutils.h
- apps/gdalalg_raster_index.cpp
- apps/gdalalg_vector.cpp
- apps/gdalalg_vector_index.cpp
- apps/gdalalg_vector_index.h
- apps/gdalalg_vector_output_abstract.cpp
- apps/gdaltindex_lib.cpp
- apps/ogrtindex.cpp
- autotest/utilities/test_gdalalg_vector_index.py
- autotest/utilities/test_ogrtindex.py
- doc/source/conf.py
- doc/source/programs/gdal_vector.rst
- doc/source/programs/gdal_vector_index.rst
- doc/source/programs/index.rst
- gcore/gdalalgorithm.cpp
and ogrtindex: replace implementation by use of gdal vector index
Fixes #12286
> Add 'gdal vector index' (port of ogrtindex)

- alg/viewshed/viewshed_executor.cpp
Adjust distance calculation for transform.
> Apply transform to distance calculation for pitch masking.

- doc/source/drivers/vector/csv.rst
- ogr/ogrsf_frmts/csv/ogrcsvdatasource.cpp
Allows to use the PIPE as separator for layer creation.
* OS:
* Compiler:
> CSV: Allow to use the PIPE as separator for layer creation

- .github/workflows/alpine/build.sh
- apps/ogr2ogr_lib.cpp
- gcore/gdaldataset.cpp
- gcore/gdaldriver.cpp
- gnm/gnm_frmts/db/gnmdbdriver.cpp
> [Backport release/3.11] Enhance behavior/error messages regarding deferred plugins (in particular PostgreSQL)

- doc/source/programs/gdal_cli_from_python.rst
Backport #12544
**Authored by:** @dmofot
> [Backport release/3.11] Update examples in gdal_cli_from_python.rst

- autotest/gdrivers/jpeg.py
- frmts/jpeg/jpgdataset.cpp
Backport #12539
**Authored by:** @klaussnd
> [Backport release/3.11] Fix subdomain of FLIR metadata

- autotest/cpp/CMakeLists.txt
- autotest/cpp/test_cpl.cpp
- autotest/ogr/ogr_pgdump.py
- ogr/ogrfeature.cpp
- ogr/ogrsf_frmts/gpkg/ogrgeopackagetablelayer.cpp
- ogr/ogrsf_frmts/hana/ogrhanafeaturereader.cpp
- ogr/ogrsf_frmts/pg/ogr_pg.h
- ogr/ogrsf_frmts/pg/ogrpgtablelayer.cpp
- ogr/ogrsf_frmts/pgdump/ogrpgdumpdatasource.cpp
- ogr/ogrsf_frmts/pgdump/ogrpgdumplayer.cpp
- port/cpl_port.h
- port/cpl_recode.cpp
- port/cpl_string.h
> PG/PGDump: fix truncation of identifiers with UTF-8 characters

- .github/workflows/asan/test.sh
- autotest/ogr/ograpispy.py
- autotest/ubsan_suppressions.txt
- gcore/overview.cpp
- ogr/ogrlinestring.cpp
- ogr/ogrsf_frmts/flatgeobuf/ogrflatgeobuflayer.cpp
and fix / suppress last remaining ones
> CI: ASAN: error out if UndefinedBehavior or memory leak detected

- autotest/cpp/testcopywords.cpp
- gcore/gdal_priv_templates.hpp
- gcore/gdalsse_priv.h
- gcore/rasterio.cpp
- port/cpl_float.h
> Performance improvements in Float16 <--> Float32/64 conversions when F16C instruction set is enabled

- swig/csharp/apps/OSRTransform.cs
- swig/include/csharp/typemaps_csharp.i
- swig/include/osr.i
Backport #12582
**Authored by:** @szekerest
> [Backport release/3.11] CSharp interface: Add SpatialReference.FindMatches (fixes #12578)

- ogr/ogrgeometry.cpp
- swig/include/python/docs/ogr_geometry_docs.i
Backport #12584
**Authored by:** @ctoney
> [Backport release/3.11] Doc: fix description of the return value for OGRGeometry::IsRing()

- apps/gdalalg_raster_calc.cpp
- apps/gdalalg_raster_calc.h
- apps/gdalalg_raster_mosaic.cpp
- autotest/utilities/test_gdalalg_raster_calc.py
- doc/source/programs/gdal_raster_calc.rst
- gcore/gdalalgorithm.cpp
- gcore/gdalalgorithm.h
> gdal raster calc: add a --dialect=muparser|builtin, where builtin can be used to compute a single band from all bands of a single input dataset

- doc/source/drivers/vector/dxf.rst
Backport #12607
**Authored by:** @agiudiceandrea
> [Backport release/3.11] DXF: Fix links to external resources in docs

- port/cpl_conv.cpp
> Fix build with libcxx 19.1.7 on OpenBSD

- autotest/gcore/vsigs.py
- port/cpl_vsil_gs.cpp
- port/cpl_vsil_swift.cpp
- port/cpl_vsil_webhdfs.cpp
> [Backport release/3.11] Fixes/improvements in /vsigs/ , /vsiswift/ and /vsiwebhdfs

- doc/source/sponsors/index.rst
- doc/source/sponsors/past_sponsors.rst
> [Backport release/3.11] Doc: move past sponsors to a dedicated page

- autotest/cpp/test_gdal.cpp
- gcore/gdal_priv.h
- gcore/gdalrasterband.cpp
Essentially a C++ version of https://github.com/rasterio/rasterio/blob/0e78687d17353075584be84b7c9a39f7dcaa8aa4/rasterio/_base.pyx#L841
> GDALRasterBand: Add IterateWindows()

- doc/source/user/ogr_sql_dialect.rst
Backport #12703
**Authored by:** @DelazJ
> [Backport release/3.11] Fix list display in documentation

- autotest/gdrivers/aaigrid.py
- frmts/aaigrid/aaigriddataset.cpp
- frmts/aaigrid/aaigriddataset.h
> AAIGrid/GRASSASCII/ISG: avoid excessive memory allocation on truncated/corrupted/hostile file

- autotest/gcore/vsizip.py
- frmts/georaster/cpl_vsil_ocilob.cpp
- port/cpl_vsil_gzip.cpp
- port/cpl_vsil_libarchive.cpp
- port/cpl_vsil_sparsefile.cpp
- port/cpl_vsil_unix_stdio_64.cpp
- port/cpl_vsil_win32.cpp
Fixes https://github.com/geopandas/pyogrio/issues/545
> /vsizip/: fix memory leak when opening a SOZip-enabled file

- autotest/gdrivers/vrtovr.py
- frmts/vrt/vrtdataset.cpp
- frmts/vrt/vrtpansharpened.cpp
> [Backport release/3.11] VRT overviews related fixes

- doc/source/drivers/vector/osm.rst
Includes both bash and PowerShell examples due to differences (and trickiness!) in escaping the quotes.
> Doc: Add OSM examples

- scripts/install_bash_completions.cmake.in
Install symlinks for completions that are missing and remove symlinks for completions that have been removed.
https://bugs.gentoo.org/925307 (Downstream Gentoo bug about detected QA issues with the installed bash completions)
* OS:
* Compiler:
> CMake: Update installed bash completion symlinks due to previous removals and additions

- autotest/ogr/ogr_gml.py
- doc/source/drivers/vector/gml.rst
- ogr/ogrsf_frmts/gml/ogrgmldriver.cpp
- ogr/ogrsf_frmts/gml/ogrgmllayer.cpp
> [GML] Expose SKIP_CORRUPTED_FEATURES open option

- autotest/ogr/ogr_gml.py
- doc/source/drivers/vector/gml.rst
- ogr/gml2ogrgeometry.cpp
- ogr/ogrgeometryfactory.cpp
- ogr/ogrsf_frmts/gml/gmlhandler.cpp
- ogr/ogrsf_frmts/gml/ogrgmldatasource.cpp
- ogr/ogrsf_frmts/gml/ogrgmldriver.cpp
Fix #12769
Also, expose SKIP_RESOLVE_ELEMS as an open option
> [GML] Support CityGML3 Shell

- doc/source/programs/gdal_raster_stack.rst
Backport #12795
**Authored by:** @geographika
> [Backport release/3.11] Doc: Update gdal raster stack examples

- autotest/ogr/ogr_csv.py
- ogr/ogrsf_frmts/csv/ogrcsvdatasource.cpp
> CSV: fix opening directory with .csv and .prj files

- alg/gdalwarpoperation.cpp
- apps/gdalwarp_lib.cpp
> gdalwarp: for TPS warping, use -wo SOURCE_EXTRA=5 by default

- .github/workflows/armhf/test.sh
- .github/workflows/coverage/test.sh
- .github/workflows/s390x/test.sh
- apps/gdal.cpp
- apps/gdalalg_raster_tile.cpp
- apps/gdalalg_raster_tile.h
- apps/gdalgetgdalpath.cpp
- autotest/cpp/test_cpl.cpp
- autotest/utilities/test_gdalalg_raster_tile.py
- cmake/helpers/configure.cmake
- cmake/template/cpl_config.h.in
- doc/source/programs/gdal_raster_tile.rst
- doc/source/spelling_wordlist.txt
- port/CMakeLists.txt
- port/cpl_conv.cpp
- port/cpl_getexecpath.cpp
- port/cpl_multiproc.h
- port/cplgetcurrentthreadcount.cpp
- swig/include/cpl.i
> gdal raster tile: add a --parallel-method=fork on non-Windows OS

- autotest/gdrivers/envi.py
- autotest/gdrivers/gpkg.py
- doc/source/user/raster_data_model.rst
- frmts/raw/envidataset.cpp
> ENVI: warn/error out if samples/lines/bands are greater than INT_MAX

- apps/gdalalg_mdim_info.cpp
- apps/gdalmdiminfo_bin.cpp
- apps/gdalmdiminfo_lib.cpp
- autotest/utilities/test_gdalalg_mdim_info.py
> Make 'gdal mdim info' return 0 when there is no error

- apps/gdal_footprint_lib.cpp
> [Backport release/3.11] gdal_footprint: fail if there is a simplification error and there is a single input feature

- apps/gdalalg_abstract_pipeline.h
- apps/gdalalg_dispatcher.h
- apps/gdalalg_pipeline.cpp
- apps/gdalalg_raster.cpp
- apps/gdalalg_raster_convert.cpp
- apps/gdalalg_raster_convert.h
- apps/gdalalg_raster_info.cpp
- apps/gdalalg_raster_info.h
- apps/gdalalg_raster_pipeline.cpp
- apps/gdalalg_vector.cpp
- apps/gdalalg_vector_convert.cpp
- apps/gdalalg_vector_convert.h
- apps/gdalalg_vector_info.cpp
- apps/gdalalg_vector_info.h
- apps/gdalalg_vector_pipeline.cpp
- autotest/gcore/algorithm.py
- autotest/utilities/test_gdalalg_pipeline.py
- autotest/utilities/test_gdalalg_raster_pipeline.py
- autotest/utilities/test_gdalalg_vector_pipeline.py
- doc/source/programs/gdal_pipeline.rst
- doc/source/programs/gdal_raster_pipeline.rst
- doc/source/programs/gdal_vector_pipeline.rst
- gcore/gdalalgorithm.cpp
- swig/include/python/gdal_python.i
> Allow raster/vector info to be used as last step of a pipeline

- autotest/gcore/vsis3.py
- port/cpl_aws.cpp
- port/cpl_aws.h
Backport #12765
**Authored by:** @emilyselwood
> [Backport release/3.11] CPL AWS: Fix sso cache file location and region parameter (Fixes #12064)

- doc/source/drivers/raster/netcdf.rst
Minor documentation fix for NetCDF. 
None
> NetCDF Documentation Broken Link for CF conventions

- doc/source/drivers/raster/netcdf.rst
Backport #12843
**Authored by:** @pratiman-91
> [Backport release/3.11] NetCDF Documentation Broken Link for CF conventions

- doc/source/_extensions/driverproperties.py
- doc/source/drivers/vector/adbc.rst
> Doc: add missing drivers in vector driver table

- alg/gdalwarpkernel.cpp
Use UInt16 nearest neighbor warping.
This appears to have been the intention
in commit 17a737fbd7.
Commit 17a737fbd7.
* OS:
* Compiler:
> Warp: use UInt16 nearest neighbor warping

- apps/gdalalg_pipeline.cpp
- apps/gdalalg_raster_pipeline.h
- apps/gdalalg_vector_pipeline.h
- doc/source/conf.py
- doc/source/programs/gdal_pipeline.rst
- doc/source/programs/gdal_raster_pipeline.rst
- doc/source/programs/gdal_vector_pipeline.rst
- doc/source/programs/index.rst
Addresses comment https://github.com/OSGeo/gdal/issues/12757#issuecomment-3151175942
> Doc: better outline pipeline functionality

- apps/gdalalg_vector_concat.cpp
- apps/gdalalg_vector_concat.h
- apps/gdalalg_vector_pipeline.cpp
- autotest/utilities/test_gdalalg_vector_concat.py
- port/cpl_known_config_options.h
Fixes https://lists.osgeo.org/pipermail/gdal-dev/2025-August/060819.html
Backport of https://github.com/OSGeo/gdal/pull/12856
> [Backport 3.11] gdal vector concat: allow to concat more than 1000 files

- autotest/ogr/ogr_wfs.py
- ogr/ogrsf_frmts/wfs/CMakeLists.txt
- ogr/ogrsf_frmts/wfs/ogr_wfs.h
- ogr/ogrsf_frmts/wfs/ogrwfsdatasource.cpp
- ogr/ogrsf_frmts/wfs/ogrwfsjoinlayer.cpp
- ogr/ogrsf_frmts/wfs/ogrwfslayer.cpp
> WFS: emit error when GML driver not available, try to request JSON instead

- cmake/helpers/GdalCompilationFlags.cmake
- frmts/vrt/vrtdataset.cpp
- frmts/vrt/vrtdataset.h
- frmts/zarr/zarr_v2_array.cpp
- frmts/zarr/zarr_v3_array.cpp
> Fix clang -Wthread-safety-analysis related warnings, and enable it in CI builds

- frmts/gti/gdaltileindexdataset.cpp
- frmts/stacit/stacitdataset.cpp
- frmts/zarr/vsikerchunk.cpp
- port/cpl_vsi.h
- port/cpl_vsil.cpp
> GTI (STAC GeoParquet): do s3:// -> /vsis3/ substitution

- apps/gdalalg_vector_check_coverage.cpp
- apps/gdalalg_vector_check_geometry.cpp
- autotest/pymod/gdaltest.py
- autotest/utilities/test_gdalalg_vector_check_geometry.py
- doc/source/conf.py
- doc/source/programs/gdal_vector_check_geometry.rst
- doc/source/programs/index.rst
As discussed in https://github.com/OSGeo/gdal/pull/12880#discussion_r2270081590
Requires https://github.com/libgeos/geos/pull/1296
> gdal vector check-geometry: check simplicity of linear features

- swig/python/gdal-utils/osgeo_utils/samples/validate_geoparquet.py
Put in a lint suppression instead of
something that looks like it was meant
to be a function call.
* OS:
* Compiler:
> validate_geoparquet: remove dead code

- doc/source/programs/gdal_contour.rst
> [doc] gdal_contour fix unreported missing quote

- ogr/ogrsf_frmts/gpkg/ogr_geopackage.h
- ogr/ogrsf_frmts/gpkg/ogrgeopackagetablelayer.cpp
> [Backport release/3.11] GPKG: fix random crash in GetNextArrowArrayAsynchronous()

- alg/gdaltransformer.cpp
- apps/gdalwarp_lib.cpp
- autotest/utilities/test_gdalwarp_lib.py
Fixes #13017
Tweaks heuristics modified in refs #10108
> Warping: avoid inserting CENTER_LONG when warping whole >=360 longitude range to WebMercator

- frmts/miramon/miramon_band.cpp
- frmts/miramon/miramon_palettes.cpp
- frmts/miramon/miramon_palettes.h
- frmts/miramon/miramon_rasterband.cpp
- frmts/miramon/miramon_rasterband.h
- frmts/miramon/miramon_rel.cpp
- frmts/miramon/miramon_rel.h
It fixes next coverity scan defects: 
CID 1620843
CID 1620842
CID 1620841
CID 1620840
CID 1620839
CID 1620838
CID 1620837
CID 1620836
CID 1620835
CID 1620832
CID 1620831
CID 1620830
CID 1620829
CID 1620828
CID 1620827
CID 1620826
> MiraMonRaster: solving some Coverity scan defects

- autotest/ogr/ogr_gpkg.py
- ogr/ogrsf_frmts/gpkg/ogrgeopackageselectlayer.cpp
- ogr/ogrsf_frmts/sqlite/ogrsqliteselectlayer.cpp
> GPKG: optimize GetNextArrowArray() on SQL result layers that return 0 row

- autotest/cpp/CMakeLists.txt
- autotest/ogr/ogr_gpkg.py
- frmts/mrf/marfa.h
- frmts/pdf/gdal_pdf.h
- frmts/pdf/pdfwritabledataset.cpp
- ogr/ogrsf_frmts/elastic/ogr_elastic.h
- ogr/ogrsf_frmts/gpkg/ogrgeopackageselectlayer.cpp
- ogr/ogrsf_frmts/mitab/mitab.h
- ogr/ogrsf_frmts/mitab/mitab_priv.h
- ogr/ogrsf_frmts/pgdump/ogr_pgdump.h
- ogr/ogrsf_frmts/sqlite/ogr_sqlite.h
- ogr/ogrsf_frmts/sqlite/ogrsqliteselectlayer.cpp
- ogr/ogrsf_frmts/sxf/ogr_sxf.h
> [Backport release/3.11] GPKG: optimize GetNextArrowArray() on SQL result layers that return 0 row

- doc/source/sponsors/index.rst
> Google is an active Silver sponsor again

- doc/source/sponsors/index.rst
Backport #13060
**Authored by:** @hobu
> [Backport release/3.11] Google is an active Silver sponsor again

- apps/gdalalg_vector_change_field_type.cpp
- apps/gdalalg_vector_change_field_type.h
- autotest/utilities/test_gdalalg_vector_change_field_type.py
- doc/source/programs/gdal_vector_change_field_type.rst
- gcore/gdalalgorithm.cpp
- gcore/gdalalgorithm.h
Addresses https://github.com/OSGeo/gdal/issues/13046#issuecomment-3304541709
CC @elpaso
> gdal vector change-field-type: add a --src-field-type option (mutually exclusive with --field-name)

- docker/alpine-normal/Dockerfile
- docker/alpine-small/Dockerfile
- docker/ubuntu-full/Dockerfile
- docker/ubuntu-full/bh-gdal.sh
- docker/ubuntu-full/bh-proj.sh
- docker/ubuntu-small/Dockerfile
No reason to use both, and `curl` is probably better maintained these days.
> docker: consistently use curl instead of wget

- autotest/ogr/data/esrijson/esripoint.json
- autotest/ogr/ogr_esrijson.py
- ogr/ogrsf_frmts/geojson/ogresrijsonreader.cpp
- ogr/ogrsf_frmts/geojson/ogrgeojsonutils.cpp
> ESRIJSON: recognize esriFieldTypeDateOnly, esriFieldTypeTimeOnly, esriFieldTypeBigInteger, esriFieldTypeGUID and esriFieldTypeGlobalID data types

- doc/source/programs/gdaltindex.rst
Fix gdaltindex documentation. `-f` to `-of`
```
GDAL 3.11.4 "Eganville", released 2025/09/04
```
```
Usage: gdaltindex [--help] [--long-usage] [--help-general]
[-overwrite] [-recursive] [-filename_filter <val>]...
[-min_pixel_size <val>] [-max_pixel_size <val>]
[-of <output_format>] [-tileindex <field_name>]
[-write_absolute_path] [-skip_different_projection]
[-t_srs <srs_def>] [-src_srs_name <field_name>]
[-src_srs_format {AUTO|WKT|EPSG|PROJ}] [-lyr_name <name>]
[-lco <NAME>=<VALUE>]... [-gti_filename <filename>]
[-tr <xres> <yres>] [-te <xmin> <ymin> <xmax> <ymax>]
[-ot <datatype>] [-bandcount <val>] [-nodata <val>]...
[-colorinterp <val>]... [-mask] [-mo <name>=<value>]...
[-fetch_md <gdal_md_name> <fld_name> <fld_type>]... [--quiet]
<index_file> <file_or_dir>...
```
Provide …
> Fix gdaltindex documentation

- autotest/gcore/multidim.py
- gcore/gdalmultidim.cpp
> Multidim: make CreateSlicedArray() also slice indexing variables of dimensions

- autotest/gcore/multidim.py
- gcore/gdalmultidim.cpp
> [Backport release/3.11] Multidim: make CreateSlicedArray() also slice indexing variables of dimensions

- doc/source/drivers/raster/gtiff.rst
- doc/source/drivers/raster/jp2openjpeg.rst
> Doc: fix NUM_CPUS typo

- docker/util.sh
> docker: fix CI generation of images
